### ISSUE TITLE
🐛 [firebase_crashlytics] Missing Flutter dSYM file for caught error

### ISSUE THREAD

**Issue by rivella50** [firebase/flutterfire#8839] opened 2022-06-04 17:57 UTC
## Bug report

**Describe the bug**
I build an iOS .ipa file and manually invoke a crash in the deployed app.
Also i've uploaded a zip file to Firebase Crashlytics section of the corresponding archive file generated under build/ios/archive/Runner.xcarchive/dSYMs
After some minutes i see the crash report, but unfortunately for Flutter it tells me that the UUID is missing (see screenshot).
When checking in the mentioned folder of dSYMs i don't have a file for that UUID available to upload.

### Expected behavior

I would like to see information of the crash in the Flutter area of the crash report.

## Additional context

![Screenshot 2022-06-04 at 19 49 17](https://user-images.githubusercontent.com/54292/172019686-8ff34e40-5bd7-415d-8c31-3dec149dd69d.png)

---

### Flutter doctor

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 3.0.1, on macOS 12.4 21F79 darwin-arm, locale en-CH)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.1.1)
[✓] VS Code (version 1.67.2)
[✓] Connected device (2 available)
[✓] HTTP Host Availability
```

</details>

---

### Flutter dependencies

<details><summary>Click To Expand</summary>

```
Dart SDK 2.17.1
Flutter SDK 3.0.1
myProject 1.0.8+8

dependencies:
- badges 2.0.2 [flutter]
- cached_network_image 3.2.1 [flutter flutter_cache_manager octo_image cached_network_image_platform_interface cached_network_image_web]
- camera 0.9.7+1 [camera_platform_interface camera_web flutter flutter_plugin_android_lifecycle quiver]
- cloud_firestore 3.1.14 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_interface flutter meta]
- cloud_functions 3.2.16 [cloud_functions_platform_interface cloud_functions_web firebase_core firebase_core_platform_interface flutter]
- email_validator 2.0.1
- file_picker 4.6.1 [flutter flutter_web_plugins flutter_plugin_android_lifecycle plugin_platform_interface ffi path win32]
- firebase_auth 3.3.19 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 1.17.1 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_crashlytics 2.8.1 [firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface flutter stack_trace]
- firebase_messaging 11.4.1 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- firebase_storage 10.2.17 [firebase_core firebase_core_platform_interface firebase_storage_platform_interface firebase_storage_web flutter]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- flutter_cache_manager 3.3.0 [clock collection file flutter http path path_provider pedantic rxdart sqflite uuid]
- flutter_cache_manager_firebase 2.0.1 [flutter flutter_cache_manager firebase_storage path_provider path]
- flutter_image_compress 1.1.0 [flutter]
- flutter_localizations 0.0.0 [flutter intl characters clock collection material_color_utilities meta path vector_math]
- flutter_native_splash 2.2.2 [args flutter flutter_web_plugins image js lint meta path universal_io xml yaml]
- flutter_phone_direct_caller 2.1.1 [flutter]
- flutter_riverpod 2.0.0-dev.9 [collection flutter meta riverpod state_notifier]
- flutter_sfsymbols 2.0.0 [flutter]
- flutter_spinkit 5.1.0 [flutter]
- get_it 7.2.0 [async collection]
- google_maps_flutter 2.1.6 [flutter flutter_plugin_android_lifecycle google_maps_flutter_platform_interface]
- grouped_list 5.1.1 [flutter]
- image 3.2.0 [archive meta xml]
- intl 0.17.0 [clock path]
- jiffy 5.0.0 [intl]
- package_info_plus 1.4.2 [flutter package_info_plus_platform_interface package_info_plus_linux package_info_plus_macos package_info_plus_windows package_info_plus_web]
- pdfx 2.0.1+2 [flutter flutter_web_plugins plugin_platform_interface js device_info_plus uuid meta extension synchronized universal_platform photo_view vector_math]
- photo_view 0.14.0 [flutter]
- sumup 0.4.0 [flutter]
- uni_links 0.5.1 [flutter uni_links_platform_interface uni_links_web]
- url_launcher 6.1.2 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- uuid 3.0.6 [crypto]

dev dependencies:
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher material_color_utilities meta source_span stream_channel string_scanner term_glyph]
- mocktail 0.3.0 [collection matcher test]
- very_good_analysis 2.4.0

dependency overrides:
- photo_view 0.14.0 [flutter]

transitive dependencies:
- _fe_analyzer_shared 40.0.0 [meta]
- analyzer 4.1.0 [_fe_analyzer_shared collection convert crypto glob meta package_config path pub_semver source_span watcher yaml]
- archive 3.3.0 [crypto path]
- args 2.3.1
- async 2.8.2 [collection meta]
- boolean_selector 2.1.0 [source_span string_scanner]
- cached_network_image_platform_interface 1.0.0 [flutter flutter_cache_manager]
- cached_network_image_web 1.0.1 [flutter flutter_cache_manager cached_network_image_platform_interface]
- camera_platform_interface 2.2.0 [cross_file flutter plugin_platform_interface stream_transform]
- camera_web 0.2.1+6 [camera_platform_interface flutter flutter_web_plugins stream_transform]
- characters 1.2.0
- charcode 1.3.1
- clock 1.1.0
- cloud_firestore_platform_interface 5.5.7 [collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 2.6.16 [cloud_firestore_platform_interface collection firebase_core firebase_core_web flutter flutter_web_plugins js]
- cloud_functions_platform_interface 5.1.7 [firebase_core flutter meta plugin_platform_interface]
- cloud_functions_web 4.2.15 [cloud_functions_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- collection 1.16.0
- convert 3.0.2 [typed_data]
- coverage 1.3.2 [args logging package_config path source_maps stack_trace vm_service]
- cross_file 0.3.3+1 [js meta]
- crypto 3.0.2 [typed_data]
- device_info_plus 3.2.3 [flutter device_info_plus_platform_interface device_info_plus_macos device_info_plus_linux device_info_plus_web device_info_plus_windows]
- device_info_plus_linux 2.1.1 [device_info_plus_platform_interface file flutter meta]
- device_info_plus_macos 2.2.3 [device_info_plus_platform_interface flutter]
- device_info_plus_platform_interface 2.3.0+1 [flutter meta plugin_platform_interface]
- device_info_plus_web 2.1.0 [device_info_plus_platform_interface flutter_web_plugins flutter]
- device_info_plus_windows 2.1.1 [device_info_plus_platform_interface ffi flutter win32]
- extension 0.2.0
- fake_async 1.3.0 [clock collection]
- ffi 1.2.1
- file 6.1.2 [meta path]
- firebase_auth_platform_interface 6.2.7 [firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 3.3.16 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core_platform_interface 4.4.0 [collection flutter meta plugin_platform_interface]
- firebase_core_web 1.6.4 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_crashlytics_platform_interface 3.2.7 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_platform_interface 3.5.1 [firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 2.4.1 [firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]
- firebase_storage_platform_interface 4.1.7 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_storage_web 3.2.16 [async firebase_core firebase_core_web firebase_storage_platform_interface flutter flutter_web_plugins http js meta]
- flutter_blurhash 0.7.0 [flutter]
- flutter_plugin_android_lifecycle 2.0.6 [flutter]
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta vector_math]
- frontend_server_client 2.1.3 [async path]
- glob 2.0.2 [async collection file path string_scanner]
- google_maps_flutter_platform_interface 2.1.7 [collection flutter plugin_platform_interface stream_transform]
- http 0.13.4 [async http_parser meta path]
- http_multi_server 3.2.0 [async]
- http_parser 4.0.1 [collection source_span string_scanner typed_data]
- io 1.0.3 [meta path string_scanner]
- js 0.6.4
- lint 1.8.2
- logging 1.0.2
- matcher 0.12.11 [stack_trace]
- material_color_utilities 0.1.4
- meta 1.7.0
- mime 1.0.2
- node_preamble 2.0.1
- octo_image 1.0.2 [flutter flutter_blurhash]
- package_config 2.0.2 [path]
- package_info_plus_linux 1.0.5 [package_info_plus_platform_interface flutter path]
- package_info_plus_macos 1.3.0 [flutter]
- package_info_plus_platform_interface 1.0.2 [flutter meta plugin_platform_interface]
- package_info_plus_web 1.0.5 [flutter flutter_web_plugins http meta package_info_plus_platform_interface]
- package_info_plus_windows 1.0.5 [package_info_plus_platform_interface ffi flutter win32]
- path 1.8.1
- path_provider 2.0.10 [flutter path_provider_android path_provider_ios path_provider_linux path_provider_macos path_provider_platform_interface path_provider_windows]
- path_provider_android 2.0.14 [flutter path_provider_platform_interface]
- path_provider_ios 2.0.9 [flutter path_provider_platform_interface]
- path_provider_linux 2.1.7 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_macos 2.0.6 [flutter path_provider_platform_interface]
- path_provider_platform_interface 2.0.4 [flutter platform plugin_platform_interface]
- path_provider_windows 2.0.7 [ffi flutter path path_provider_platform_interface win32]
- pedantic 1.11.1
- petitparser 5.0.0 [meta]
- platform 3.1.0
- plugin_platform_interface 2.1.2 [meta]
- pool 1.5.0 [async stack_trace]
- process 4.2.4 [file path platform]
- pub_semver 2.1.1 [collection meta]
- quiver 3.1.0 [matcher]
- riverpod 2.0.0-dev.9 [collection meta stack_trace state_notifier]
- rxdart 0.27.4
- shelf 1.3.0 [async collection http_parser path stack_trace stream_channel]
- shelf_packages_handler 3.0.0 [path shelf shelf_static]
- shelf_static 1.1.0 [convert http_parser mime path shelf]
- shelf_web_socket 1.0.1 [shelf stream_channel web_socket_channel]
- sky_engine 0.0.99
- source_map_stack_trace 2.1.0 [path stack_trace source_maps]
- source_maps 0.10.10 [source_span]
- source_span 1.8.2 [collection path term_glyph]
- sqflite 2.0.2+1 [flutter sqflite_common path]
- sqflite_common 2.2.1+1 [synchronized path meta]
- stack_trace 1.10.0 [path]
- state_notifier 0.7.2+1 [meta]
- stream_channel 2.1.0 [async]
- stream_transform 2.0.0
- string_scanner 1.1.0 [charcode source_span]
- synchronized 3.0.0+2
- term_glyph 1.2.0
- test 1.21.1 [analyzer async boolean_selector collection coverage http_multi_server io js node_preamble package_config path pool shelf shelf_packages_handler shelf_static shelf_web_socket source_span stack_trace stream_channel typed_data web_socket_channel webkit_inspection_protocol yaml test_api test_core]
- test_api 0.4.9 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- test_core 0.4.13 [analyzer async args boolean_selector collection coverage frontend_server_client glob io meta package_config path pool source_map_stack_trace source_maps source_span stack_trace stream_channel vm_service yaml matcher test_api]
- typed_data 1.3.1 [collection]
- uni_links_platform_interface 1.0.0 [flutter plugin_platform_interface]
- uni_links_web 0.1.0 [flutter flutter_web_plugins uni_links_platform_interface]
- universal_io 2.0.4 [collection crypto meta typed_data]
- universal_platform 1.0.0+1
- url_launcher_android 6.0.17 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.0.17 [flutter url_launcher_platform_interface]
- url_launcher_linux 3.0.1 [flutter url_launcher_platform_interface]
- url_launcher_macos 3.0.1 [flutter url_launcher_platform_interface]
- url_launcher_platform_interface 2.0.5 [flutter plugin_platform_interface]
- url_launcher_web 2.0.11 [flutter flutter_web_plugins url_launcher_platform_interface]
- url_launcher_windows 3.0.1 [flutter url_launcher_platform_interface]
- vector_math 2.1.2
- vm_service 8.3.0
- watcher 1.0.1 [async path]
- web_socket_channel 2.2.0 [async crypto stream_channel]
- webkit_inspection_protocol 1.1.0 [logging]
- win32 2.6.1 [ffi]
- xdg_directories 0.2.0+1 [meta path process]
- xml 6.1.0 [collection meta petitparser]
- yaml 3.1.1 [collection source_span string_scanner]
```

</details>

---

**Comment by darshankawar** [comment] 2022-06-06 10:23
@rivella50 
Can you provide the complete stack trace in properly formatted text instead of screenshot ?

**Comment by rivella50** [comment] 2022-06-06 11:06
Sure:
Fatal Exception: FirebaseCrashlyticsTestCrash
0  CoreFoundation                 0x92d0c __exceptionPreprocess
1  libobjc.A.dylib                0x14ee4 objc_exception_throw
2  Runner                         0x60cd78 __56-[FLTFirebaseCrashlyticsPlugin handleMethodCall:result:]_block_invoke + 94 (FLTFirebaseCrashlyticsPlugin.m:94)
3  Flutter                        0x55a33c (Fehlt UUID bab62788d88339b192aed18e13dece71)
4  Flutter                        0x424e8 (Fehlt UUID bab62788d88339b192aed18e13dece71)
5  libdispatch.dylib              0x63094 _dispatch_call_block_and_release
6  libdispatch.dylib              0x64094 _dispatch_client_callout
7  libdispatch.dylib              0x10d44 _dispatch_main_queue_drain
8  libdispatch.dylib              0x10994 _dispatch_main_queue_callback_4CF$VARIANT$mp
9  CoreFoundation                 0x4e0c4 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
10 CoreFoundation                 0xb5e8 __CFRunLoopRun
11 CoreFoundation                 0x1e240 CFRunLoopRunSpecific
12 GraphicsServices               0x1988 GSEventRunModal
13 UIKitCore                      0x4e541c -[UIApplication _run]
14 UIKitCore                      0x27eb88 UIApplicationMain
15 Runner                         0x62c0 main + 6 (AppDelegate.swift:6)
16 ???                            0x1051503d0 (Fehlt)

**Comment by darshankawar** [comment] 2022-06-06 12:14
@rivella50 
Thanks for the update. Apart from `[FLTFirebaseCrashlyticsPlugin handleMethodCall:result:]`, there's not many instances leading to properly analyze this.

Is there a way for you to provide steps to replicate and a reproducible code sample that triggers this crash ?

**Comment by rivella50** [comment] 2022-06-06 18:52
To clarify this: It's not about the crash, it's about the missing information regarding the Flutter code.
The crash i did by clicking this button on the first screen:
```
ElevatedButton(onPressed: () => FirebaseCrashlytics.instance.crash(), child: Text('crash'))
```

**Comment by darshankawar** [comment] 2022-06-07 09:54
@rivella50 
Ah, I see. Thanks for clarifying. If it is about that you are getting missing UUID and are looking for .dSYM for UUID, I suggest you take a look at below SO links and see if they help:

https://stackoverflow.com/questions/62998185/cant-find-dsym-for-uuid-from-firebase-crashlitycs

https://stackoverflow.com/questions/57654529/missing-uuid-dsym-within-the-appstore-downloaded-dsyms-more-targets-app

Also, I think you'll need to reach out to [firebase support](https://firebase.google.com/support) in order to get resolution, as the log seems to be coming from firebase and not specific to Flutterfire.

Closing from here. If you disagree, write in comments and I'll reopen it.

**Closed by darshankawar** 2022-06-07 09:54 UTC
Labels: type: bug, Needs Attention, in triage

**Comment by rivella50** [comment] 2022-06-07 18:16
Ok, thanks a lot for your comments. I will see what the Firebase guys can tell me about it.
