### ISSUE TITLE
🐛 [flutterfire_ui] Auth: Profile screen does not rebuild after email verification status changes.

### ISSUE THREAD

**Issue by neiljaywarner** [firebase/flutterfire#8683] opened 2022-05-13 22:36 UTC
Email auth has a "waiting for email" with a spinner on the profile screen.

Expected behaviour:
1) background app
2) go to emamil, click on verify, observe success message, background email
3) Return to app from recents menu
4) Observe waiting and profile vanish

Actual behaviour: 
Signing out and signing back in causes it to vanish.
Note: I'm on flutter UI  flutterfire_ui: 0.4.0+5 because 0.4.1 seems to require flutter 3.

**Comment by darshankawar** [comment] 2022-05-16 10:39
@neiljaywarner 
Is this happening on Android or iOS ?
Does the same behavior occur using plugin's example too ?

**Comment by neiljaywarner** [comment] 2022-05-16 15:46
Plugins example required many files but authgate code cones from docs.

I didn't try ios

....sent from my phone

**Comment by BrutalCoding** [comment] 2022-05-17 00:25
I've made this "Waiting for email verification" screen myself. I discovered that this is an issue with Firebase Auth, the authStateChanges() stream does not fire when the emailVerified flag gets changed on your Firebase Auth profile. Same for FirebaseAuth.instance.userChanges() and FirebaseAuth.instance.idTokenChanges(): none of the FIrebaseAuth streams get fired when the emailVerified flag gets changed.

My solution was to create a looping timer (e.g. every 10 seconds) and call "FirebaseAuth.instance.currentUser?.reload();", for example:

`
@override
  void initState() {
    super.initState();
    _timer = Timer.periodic(const Duration(seconds: 10), (timer) {
      FirebaseAuth.instance.currentUser?.reload();
    });
  }
`

Make sure you define `Timer _timer` in your statefulwidget and don't forget to cancel the timer when the e-mail has been verified.

By forcing the ...currentUser?.reload() method, the `FirebaseAuth.instance.userChanges()` stream will get triggered and the `User` object you get back from that stream will have an up-to-date emailVerified boolean. E.g. this will work: `user?.emailVerified == true`

**Comment by darshankawar** [comment] 2022-05-17 10:39
@BrutalCoding 
Thanks for the update. Can you open a new issue mentioning all these details so that we can track and address it properly and possibly link this issue to it as a reference, because per your comment / findings, the issue probably lies in `firebase_auth` and may not be specific to `flutterfire_ui` plugin since it seems to leverage the auth implementation.

**Comment by Patrick386** [comment] 2022-05-18 10:10
I also agree with this issue.
You should be able to check the emailVerified status with reload() .

**Comment by BrutalCoding** [comment] 2022-05-26 06:56
> @BrutalCoding Thanks for the update. Can you open a new issue mentioning all these details so that we can track and address it properly and possibly link this issue to it as a reference, because per your comment / findings, the issue probably lies in `firebase_auth` and may not be specific to `flutterfire_ui` plugin since it seems to leverage the auth implementation.

Thanks for the suggestion, I have opened a new issue here https://github.com/firebase/flutterfire/issues/8777 and described in more detail the issue and reproducible steps.

I personally think that its not only Flutter's firebase_auth package that is affected by this, but it might be a widespread issue with all Firebase Auth SDK's. The reason I say this is because Firebase Auth for JavaScript faces the same issue: https://firebase.google.com/docs/reference/js/v8/firebase.auth.Auth#onauthstatechanged

**Comment by guplem** [comment] 2022-10-06 08:44
I wanted to bring some attention to more issues related to the ProfileScreen not rebuilding with #9682. Maybe it is related.

**Comment by lesnitsky** [comment] 2022-10-17 14:50
fixed in #9343

**Closed by lesnitsky** 2022-10-17 14:50 UTC
Labels: type: bug, plugin: ui
