### ISSUE TITLE
🐛 [firebase_database] onValue returns only the changed value not all of its children 

### ISSUE THREAD

**Issue by mfizz1** [firebase/flutterfire#11312] opened 2023-07-18 10:33 UTC
## Bug report

When onValue is called, the documentation states: The event has a snapshot property containing all data at that location, including child data.

However the event only returns the changed key and value using `event.snapshot.value`

Another strange behaviour is that when multiple children change on a node simultaneously, it fires multiple events even though its 1 event which wouldn't be an issue if all the children were returned. Meaning if you have 10 children in a node all updated, it fires 10 events which is not efficient.

### Steps to reproduce
```
customListener = FirebaseDatabase.instance
          .ref('data/${dataId}/customData')
          .onValue
          .listen((event) {

debugPrint(even.snapshot.value.toString())

})

```

### Expected behavior

Return all children and fire 1 event when changing anything under customData

`{customData: {title: "new", description,"newdes"}}`

Anytime title is updated both title and description nodes should return and when both are updated, only one database event should be fired.

**Comment by mfizz1** [comment] 2023-07-18 11:47
Thank you for the response. I don't believe it does. I already use `get()` and I suppose I could get all the children and do some sort of substitution with just the updated event. I do need an active listener from firebase to make changes to the UI on flutter.

To be clear this is what the documentation says:


_You can use the DatabaseEvent to read the data at a given path, as it exists at the time of the event. This event is triggered once when the listener is attached and again every time the data, including any children, changes. **The event has a snapshot property containing all data at that location, including child data.** If there is no data, the snapshot's exists property will be false and its value property will be null._

[https://firebase.google.com/docs/database/flutter/read-and-write#read_data](url)

**Comment by darshankawar** [comment] 2023-07-19 10:48
Thanks for the feedback. Seeing the same behavior using the plugin example and with code snippet provided above.

**Comment by mfizz1** [comment] 2023-07-20 07:31
I have also noted that on attach `onChildAdded` is being called twice even though there are no changes made.

**Comment by joo6077** [comment] 2023-12-13 02:37
I found the same issue when I changed node data from the server side(admin), listening to the node on the client side return values twice in a row.

2023-12-13 11:31:02.310340
2023-12-13 11:31:02.526690

like this much gap.

**Comment by russellwheatley** [comment] 2023-12-13 11:24
I wasn't able to reproduce `onChildAdded` nor `onValue` firing twice. `onValue` also provided the all the children under `customData`. I'm going to need a reproduction, @mfizz1. Thanks.

**Comment by joo6077** [comment] 2023-12-14 02:39
@russellwheatley 
It's firing twice when you update data before listening to `onValue` no matter how many times you update it. I updated the data from the Firebase console.

**Comment by russellwheatley** [comment] 2023-12-14 10:05
@joo6077 - could you provide some steps to reproduce & what you expect against what you are seeing? Thanks.

**Comment by joo6077** [comment] 2023-12-15 07:39
@russellwheatley 
https://github.com/firebase/flutterfire/assets/59814980/5174ef65-1d24-4d02-8306-62dfa5a6dc74

You can check it on this video!

I expected to get one value when I re-listen to the streamSubscription after canceling the previous streamSubscription.
But you can see get it twice.

**Comment by joo6077** [comment] 2023-12-15 07:44
@russellwheatley 


https://github.com/firebase/flutterfire/assets/59814980/4d27d6b2-e64e-4565-ad8f-0bb2097ff39c



You can check it on this video!

I expected to get one value when I re-listen to the streamSubscription after canceling the previous streamSubscription.
But it fires twice after starting to listen to it.

**Comment by russellwheatley** [comment] 2023-12-15 15:16
Hi @joo6077, thank you for the demonstration. Could you also provide instructions for me to follow with relevant code snippets to help me reproduce easily? Thanks 👍

**Comment by joo6077** [comment] 2023-12-22 07:13
@russellwheatley I was struggling to reproduce in a test project. It turns out that using Admin SDK, it intends to run twice.

**Comment by russellwheatley** [comment] 2023-12-27 13:57
@joo6077 - thanks for letting us know. If you have any other issue, please open a new one. The original OP's issue isn't a bug therefore I am closing this out.

**Closed by russellwheatley** 2023-12-27 13:57 UTC
Labels: type: bug, blocked: customer-response, plugin: database
