### ISSUE TITLE
🐛 [firebase_auth] When closing Android app with physical back button, the app crashes

### ISSUE THREAD

**Issue by EplusTeam** [firebase/flutterfire#9193] opened 2022-07-22 13:42 UTC
## Bug report

**Describe the bug**
When I want to close my Android app with the physical back button of the smartphone the app crashes.

### Steps to reproduce

1. Initialize the app with Firebase documentation
2. Run the app on an Android device
3. When the app is opened, close it with the physical back button of the smartphone
4. The app crashes and in the console appears this error:
<details><summary>Click To Expand</summary>

```
I/FlutterBluePlugin( 4204): teardown
E/BasicMessageChannel#( 4204): Parameter messenger must not be null.
D/AndroidRuntime( 4204): Shutting down VM
E/AndroidRuntime( 4204): FATAL EXCEPTION: main
E/AndroidRuntime( 4204): Process: com.wineandmore.eplus_tuning, PID: 4204
E/AndroidRuntime( 4204): java.lang.RuntimeException: Unable to destroy activity {com.wineandmore.eplus_tuning/com.wineandmore.eplus_tuning.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.BinaryMessenger.setMessageHandler(java.lang.String, io.flutter.plugin.common.BinaryMessenger$BinaryMessageHandler)' on a null object reference
E/AndroidRuntime( 4204): 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4586)
E/AndroidRuntime( 4204): 	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4609)
E/AndroidRuntime( 4204): 	at android.app.ActivityThread.-wrap7(ActivityThread.java)
E/AndroidRuntime( 4204): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1692)
E/AndroidRuntime( 4204): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 4204): 	at android.os.Looper.loop(Looper.java:154)
E/AndroidRuntime( 4204): 	at android.app.ActivityThread.main(ActivityThread.java:6682)
E/AndroidRuntime( 4204): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 4204): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
E/AndroidRuntime( 4204): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
E/AndroidRuntime( 4204): Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.BinaryMessenger.setMessageHandler(java.lang.String, io.flutter.plugin.common.BinaryMessenger$BinaryMessageHandler)' on a null object reference
E/AndroidRuntime( 4204): 	at io.flutter.plugin.common.BasicMessageChannel.setMessageHandler(BasicMessageChannel.java:132)
E/AndroidRuntime( 4204): 	at io.flutter.plugins.firebase.auth.GeneratedAndroidFirebaseAuth$MultiFactorUserHostApi$-CC.setup(GeneratedAndroidFirebaseAuth.java:358)
E/AndroidRuntime( 4204): 	at io.flutter.plugins.firebase.auth.FlutterFirebaseAuthPlugin.onDetachedFromEngine(FlutterFirebaseAuthPlugin.java:131)
E/AndroidRuntime( 4204): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.remove(FlutterEngineConnectionRegistry.java:270)
E/AndroidRuntime( 4204): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.remove(FlutterEngineConnectionRegistry.java:280)
E/AndroidRuntime( 4204): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.removeAll(FlutterEngineConnectionRegistry.java:288)
E/AndroidRuntime( 4204): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.destroy(FlutterEngineConnectionRegistry.java:121)
E/AndroidRuntime( 4204): 	at io.flutter.embedding.engine.FlutterEngine.destroy(FlutterEngine.java:425)
E/AndroidRuntime( 4204): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onDetach(FlutterActivityAndFragmentDelegate.java:699)
E/AndroidRuntime( 4204): 	at io.flutter.embedding.android.FlutterActivity.onDestroy(FlutterActivity.java:715)
E/AndroidRuntime( 4204): 	at android.app.Activity.performDestroy(Activity.java:7195)
E/AndroidRuntime( 4204): 	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1161)
E/AndroidRuntime( 4204): 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4573)
E/AndroidRuntime( 4204): 	... 9 more
Lost connection to device.
```

</details>

### Expected behavior

The app closes without any error.

### Sample project

Providing a minimal example project which demonstrates the bug in isolation from your main App _greatly_ enhances the chance of a timely fix.
Please link to the public repository URL.

---

## Additional context

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.4 21F79 darwin-x64, locale it-IT)
    • Flutter version 3.0.5 at /Users/software/flutter3
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (9 giorni fa), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc1)
    • Android SDK at /Users/software/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.69.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.44.0

[✓] Connected device (3 available)
    • SM G920F (mobile) • 04157df42ad6d634 • android-arm64  • Android 7.0 (API 24)
    • macOS (desktop)   • macos            • darwin-x64     • macOS 12.4 21F79 darwin-x64
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 103.0.5060.134

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.17.6
Flutter SDK 3.0.5
eplus_tuning 1.4.0+30

dependencies:
- after_layout 1.2.0 [flutter]
- ai_awesome_message 2.2.0 [flutter]
- auto_size_text 3.0.0 [flutter]
- collection 1.16.0
- connectivity_plus 2.3.6 [flutter connectivity_plus_platform_interface connectivity_plus_linux connectivity_plus_macos connectivity_plus_web connectivity_plus_windows]
- crypto 3.0.2 [typed_data]
- cupertino_icons 1.0.5
- device_info_plus 4.0.1 [flutter device_info_plus_platform_interface device_info_plus_macos device_info_plus_linux device_info_plus_web device_info_plus_windows]
- firebase_analytics 9.2.1 [firebase_analytics_platform_interface firebase_analytics_web firebase_core firebase_core_platform_interface flutter]
- firebase_auth 3.5.0 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 1.20.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- flutter_blue 0.8.0 [flutter convert protobuf rxdart collection meta]
- flutter_chips_input 2.0.0 [flutter]
- flutter_form_builder 7.4.0 [flutter intl collection]
- flutter_inapp_purchase 5.3.1 [flutter http meta platform]
- flutter_launcher_icons 0.9.3 [args image path yaml]
- flutter_localizations 0.0.0 [flutter intl characters clock collection material_color_utilities meta path vector_math]
- flutter_picker 2.0.5 [flutter]
- flutter_screenutil 5.5.3+2 [flutter]
- flutter_xlider 3.4.0 [flutter]
- fluttertoast 8.0.9 [flutter flutter_web_plugins]
- form_builder_validators 8.2.0 [flutter flutter_localizations intl collection]
- google_sign_in 5.4.0 [flutter google_sign_in_android google_sign_in_ios google_sign_in_platform_interface google_sign_in_web]
- http 0.13.4 [async http_parser meta path]
- intl 0.17.0 [clock path]
- intro_slider 3.0.9 [flutter]
- launch_review 3.0.1 [flutter]
- location 4.4.0 [flutter location_platform_interface location_web]
- package_info_plus 1.4.3 [flutter package_info_plus_platform_interface package_info_plus_linux package_info_plus_macos package_info_plus_windows package_info_plus_web]
- percent_indicator 4.2.2 [flutter]
- progress_indicators 1.0.0 [flutter]
- provider 6.0.3 [collection flutter nested]
- shared_preferences 2.0.15 [flutter shared_preferences_android shared_preferences_ios shared_preferences_linux shared_preferences_macos shared_preferences_platform_interface shared_preferences_web shared_preferences_windows]
- sign_in_with_apple 4.1.0 [flutter meta sign_in_with_apple_platform_interface sign_in_with_apple_web]
- sleek_circular_slider 2.0.1 [flutter]
- sliding_up_panel 2.0.0+1 [flutter]
- url_launcher 6.1.5 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- wakelock 0.6.2 [flutter meta wakelock_macos wakelock_platform_interface wakelock_web wakelock_windows]

dev dependencies:
- flutter_lints 2.0.1 [lints]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher material_color_utilities meta source_span stream_channel string_scanner term_glyph]
- license_generator 1.0.3 [http meta path yaml]

transitive dependencies:
- archive 3.3.0 [crypto path]
- args 2.3.1
- async 2.8.2 [collection meta]
- boolean_selector 2.1.0 [source_span string_scanner]
- characters 1.2.0
- charcode 1.3.1
- clock 1.1.0
- connectivity_plus_linux 1.3.1 [flutter connectivity_plus_platform_interface meta nm]
- connectivity_plus_macos 1.2.4 [connectivity_plus_platform_interface flutter]
- connectivity_plus_platform_interface 1.2.1 [flutter meta plugin_platform_interface]
- connectivity_plus_web 1.2.3 [connectivity_plus_platform_interface flutter_web_plugins flutter]
- connectivity_plus_windows 1.2.2 [connectivity_plus_platform_interface flutter]
- convert 3.0.2 [typed_data]
- dbus 0.7.7 [args ffi meta xml]
- device_info_plus_linux 2.1.1 [device_info_plus_platform_interface file flutter meta]
- device_info_plus_macos 2.2.3 [device_info_plus_platform_interface flutter]
- device_info_plus_platform_interface 2.3.0+1 [flutter meta plugin_platform_interface]
- device_info_plus_web 2.1.0 [device_info_plus_platform_interface flutter_web_plugins flutter]
- device_info_plus_windows 3.0.1 [device_info_plus_platform_interface ffi flutter win32]
- fake_async 1.3.0 [clock collection]
- ffi 2.0.1
- file 6.1.2 [meta path]
- firebase_analytics_platform_interface 3.2.1 [firebase_core flutter meta plugin_platform_interface]
- firebase_analytics_web 0.4.1+1 [firebase_analytics_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- firebase_auth_platform_interface 6.4.0 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 4.1.0 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core_platform_interface 4.5.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 1.7.1 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- fixnum 1.0.1
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta vector_math]
- google_sign_in_android 6.0.0 [flutter google_sign_in_platform_interface]
- google_sign_in_ios 5.4.0 [flutter google_sign_in_platform_interface]
- google_sign_in_platform_interface 2.2.0 [flutter quiver]
- google_sign_in_web 0.10.1+3 [flutter flutter_web_plugins google_sign_in_platform_interface js]
- http_parser 4.0.1 [collection source_span string_scanner typed_data]
- image 3.2.0 [archive meta xml]
- js 0.6.4
- lints 2.0.0
- location_platform_interface 2.3.0 [flutter meta plugin_platform_interface]
- location_web 3.1.1 [flutter flutter_web_plugins http_parser js location_platform_interface meta]
- matcher 0.12.11 [stack_trace]
- material_color_utilities 0.1.4
- meta 1.7.0
- nested 1.0.0 [flutter]
- nm 0.5.0 [dbus]
- package_info_plus_linux 1.0.5 [package_info_plus_platform_interface flutter path]
- package_info_plus_macos 1.3.0 [flutter]
- package_info_plus_platform_interface 1.0.2 [flutter meta plugin_platform_interface]
- package_info_plus_web 1.0.5 [flutter flutter_web_plugins http meta package_info_plus_platform_interface]
- package_info_plus_windows 2.0.0 [package_info_plus_platform_interface ffi flutter win32]
- path 1.8.1
- path_provider_linux 2.1.7 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_platform_interface 2.0.4 [flutter platform plugin_platform_interface]
- path_provider_windows 2.1.0 [ffi flutter path path_provider_platform_interface win32]
- petitparser 5.0.0 [meta]
- platform 3.1.0
- plugin_platform_interface 2.1.2 [meta]
- process 4.2.4 [file path platform]
- protobuf 2.1.0 [fixnum collection meta]
- quiver 3.1.0 [matcher]
- rxdart 0.27.4
- shared_preferences_android 2.0.12 [flutter shared_preferences_platform_interface]
- shared_preferences_ios 2.1.1 [flutter shared_preferences_platform_interface]
- shared_preferences_linux 2.1.1 [file flutter path path_provider_linux path_provider_platform_interface shared_preferences_platform_interface]
- shared_preferences_macos 2.0.4 [flutter shared_preferences_platform_interface]
- shared_preferences_platform_interface 2.0.0 [flutter]
- shared_preferences_web 2.0.4 [flutter flutter_web_plugins shared_preferences_platform_interface]
- shared_preferences_windows 2.1.1 [file flutter path path_provider_platform_interface path_provider_windows shared_preferences_platform_interface]
- sign_in_with_apple_platform_interface 1.0.0 [flutter plugin_platform_interface meta]
- sign_in_with_apple_web 1.0.1 [flutter flutter_web_plugins sign_in_with_apple_platform_interface js]
- sky_engine 0.0.99
- source_span 1.8.2 [collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.0 [charcode source_span]
- term_glyph 1.2.0
- test_api 0.4.9 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.1 [collection]
- url_launcher_android 6.0.17 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.0.17 [flutter url_launcher_platform_interface]
- url_launcher_linux 3.0.1 [flutter url_launcher_platform_interface]
- url_launcher_macos 3.0.1 [flutter url_launcher_platform_interface]
- url_launcher_platform_interface 2.1.0 [flutter plugin_platform_interface]
- url_launcher_web 2.0.12 [flutter flutter_web_plugins url_launcher_platform_interface]
- url_launcher_windows 3.0.1 [flutter url_launcher_platform_interface]
- vector_math 2.1.2
- wakelock_macos 0.4.0 [flutter flutter_web_plugins wakelock_platform_interface]
- wakelock_platform_interface 0.3.0 [flutter meta]
- wakelock_web 0.4.0 [flutter flutter_web_plugins js wakelock_platform_interface]
- wakelock_windows 0.2.0 [flutter wakelock_platform_interface win32]
- win32 2.7.0 [ffi]
- xdg_directories 0.2.0+1 [meta path process]
- xml 6.1.0 [collection meta petitparser]
- yaml 3.1.1 [collection source_span string_scanner]
```

</details>

---

**Comment by BitBlueDevStudio** [comment] 2022-07-22 16:00
Hello! Same issue.

@EplusTeam are you sure its only when user closing app using back button? I can't reproduce this issue, I only see many crashes in crashlytics, in different places of app. 

I just updated one small thing in app in dart code, and now it occurs. Plus, it doesnt occurs in old app version. Why? How? I didn't change any dependencies.

**Comment by ivangr1** [comment] 2022-07-22 16:44
I am also getting crashes in the Play Console since I updated to `firebase_auth 3.5.0` , although I cannot reproduce it locally

I get only always the same stacktrace:

```
java.lang.RuntimeException: 
  at android.app.ActivityThread.performDestroyActivity (ActivityThread.java:5154)
  at android.app.ActivityThread.handleDestroyActivity (ActivityThread.java:5183)
  at android.app.servertransaction.DestroyActivityItem.execute (DestroyActivityItem.java:44)
  at android.app.servertransaction.TransactionExecutor.executeLifecycleState (TransactionExecutor.java:176)
  at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:97)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2164)
  at android.os.Handler.dispatchMessage (Handler.java:107)
  at android.os.Looper.loop (Looper.java:241)
  at android.app.ActivityThread.main (ActivityThread.java:7582)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:492)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:941)
Caused by: java.lang.NullPointerException: 
  at io.flutter.plugin.common.BasicMessageChannel.setMessageHandler (BasicMessageChannel.java:35)
  at io.flutter.plugins.firebase.auth.GeneratedAndroidFirebaseAuth$MultiFactorUserHostApi.setup (GeneratedAndroidFirebaseAuth.java:19)
  at io.flutter.plugins.firebase.auth.FlutterFirebaseAuthPlugin.onDetachedFromEngine (FlutterFirebaseAuthPlugin.java:10)
  at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.remove (FlutterEngineConnectionRegistry.java:121)
  at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.remove (FlutterEngineConnectionRegistry.java:16)
  at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.removeAll (FlutterEngineConnectionRegistry.java:11)
  at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.destroy (FlutterEngineConnectionRegistry.java:10)
  at io.flutter.embedding.engine.FlutterEngine.destroy (FlutterEngine.java:31)
  at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onDetach (FlutterActivityAndFragmentDelegate.java:98)
  at io.flutter.embedding.android.FlutterActivity.onDestroy (FlutterActivity.java:18)
  at android.app.Activity.performDestroy (Activity.java:8068)
  at android.app.Instrumentation.callActivityOnDestroy (Instrumentation.java:1363)
  at android.app.ActivityThread.performDestroyActivity (ActivityThread.java:5139)
  at android.app.ActivityThread.handleDestroyActivity (ActivityThread.java:5183)
  at android.app.servertransaction.DestroyActivityItem.execute (DestroyActivityItem.java:44)
  at android.app.servertransaction.TransactionExecutor.executeLifecycleState (TransactionExecutor.java:176)
  at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:97)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2164)
  at android.os.Handler.dispatchMessage (Handler.java:107)
  at android.os.Looper.loop (Looper.java:241)
  at android.app.ActivityThread.main (ActivityThread.java:7582)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:492)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:941)
```

**Comment by BitBlueDevStudio** [comment] 2022-07-22 16:46
Looks like firebase using dynamic dependencies in theirs libs, since I didnt updated any dependencies, but did pub get. This is very strange decision! 

@ivangr1 I was able to reproduce on android 7 emulator

**Comment by BitBlueDevStudio** [comment] 2022-07-22 18:36
![telegram-cloud-document-2-5393600267956526944](https://user-images.githubusercontent.com/76124957/180502352-c91a85dc-14d2-47c6-8b80-7b78e97299eb.jpg)

![telegram-cloud-document-2-5393600267956526945](https://user-images.githubusercontent.com/76124957/180502386-5d508c57-f95b-4d83-9eb0-823336deac8c.jpg)

This is screenshots of code, which causes this crash. How can things like that get in production? Do you actually look at your code or test it??

**Comment by kinex** [comment] 2022-07-24 12:50
Downgrading to 3.4.2 results build error
```
Error: Required named parameter 'auth' must be provided.
../…/src/recaptcha_verifier.dart:57
      _factory.delegateFor(
```
So I guess there is no (easy) way back either. Please fix this ASAP. 3.5.0 cannot be used in a production app.

**Comment by sbenmeddour** [comment] 2022-07-24 13:50
> Downgrading to 3.4.2 results build error
> 
> ```
> Error: Required named parameter 'auth' must be provided.
> ../…/src/recaptcha_verifier.dart:57
>       _factory.delegateFor(
> ```
> 
> So I guess there is no (easy) way back either since I updated all FlutterFire plugins at the same time as always. Please fix this ASAP. 3.5.0 cannot be used in a production app.

```
dependency_overrides:
  firebase_auth_platform_interface: 6.3.2
```

in your pubspec file. I had to clear caches to get it working

**Comment by BitBlueDevStudio** [comment] 2022-07-24 14:08
@kinex I used this in pobspec.lock
 ```
 firebase_auth:
    dependency: "direct main"
    description:
      name: firebase_auth
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.4.1"
  firebase_auth_platform_interface:
    dependency: transitive
    description:
      name: firebase_auth_platform_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "6.3.1"
  firebase_auth_web:
    dependency: transitive
    description:
      name: firebase_auth_web
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.3.19"
```

And it works fine

**Comment by kinex** [comment] 2022-07-24 21:16
> ```
> dependency_overrides:
>   firebase_auth_platform_interface: 6.3.2
> ```
> 
> in your pubspec file. I had to clear caches to get it working

Thanks for finding this out, it works. As a side note, I think this is another issue in this package. As they introduced a breaking change in the `firebase_auth_platform_interface`, they should have increased its major version number (e.g. 7.0.0). Then dependencies would have been resolved correctly automatically without this `dependency_overrides` hack which is always risky and a lot of unnecessary work (I had to add it to 6 packages separately).

**Comment by sbenmeddour** [comment] 2022-07-25 01:41
> > ```
> > dependency_overrides:
> >   firebase_auth_platform_interface: 6.3.2
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > in your pubspec file. I had to clear caches to get it working
> 
> Thanks for finding this out, it works. As a side note, I think this is another issue in this package. As they introduced a breaking change in the `firebase_auth_platform_interface`, they should have increased its major version number (e.g. 7.0.0). Then dependencies would have been resolved correctly automatically without this `dependency_overrides` hack which is always risky and a lot of unnecessary work (I had to add it to 6 packages separately).


I agree, but we have no choice until the error on both packages is corrected
I'm sure the team will fix thix quickly so we can deploy our pending builds

**Comment by EplusTeam** [comment] 2022-07-25 08:25
> > Downgrading to 3.4.2 results build error
> > ```
> > Error: Required named parameter 'auth' must be provided.
> > ../…/src/recaptcha_verifier.dart:57
> >       _factory.delegateFor(
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > So I guess there is no (easy) way back either since I updated all FlutterFire plugins at the same time as always. Please fix this ASAP. 3.5.0 cannot be used in a production app.
> 
> ```
> dependency_overrides:
>   firebase_auth_platform_interface: 6.3.2
> ```
> 
> in your pubspec file. I had to clear caches to get it working

Downgrading with this override works fine. Thanks.

**Comment by darshankawar** [comment] 2022-07-25 12:09
Thanks for the report. There's similar open issue describing same case, https://github.com/firebase/flutterfire/issues/9210 so please follow-up in it for further updates.
Closing this as a duplicate.

Thanks @BitBlueDevStudio for identifying the root-cause https://github.com/firebase/flutterfire/issues/9193#issuecomment-1192839591. My findings were exactly like the one you found out 👍🏻

**Closed by darshankawar** 2022-07-25 12:09 UTC
Labels: type: bug, Needs Attention, in triage
