### ISSUE TITLE
🐛 [firebase_auth] signInWithEmailAndPassword returns error code "unknown"

### ISSUE THREAD

**Issue by jayjay911** [firebase/flutterfire#10966] opened 2023-05-15 10:14 UTC
## Bug report

**Describe the bug**
I am using Flutter Web and running in Chrome.

After upgrading to Flutter 3.10.0 and all my firebase dependencies I started getting unusual behaviour when attempting to sign into firebase with email and password. 

Instead of throwing a FirebaseAuthMultiFactorException as expected, it throws a FirebaseAuthException with the following message:

An unknown error occurred: FirebaseError: Firebase: Proof of ownership of a second factor is required to complete sign-in. (auth/multi-factor-auth-required).

Error code is:

"unknown"

Error code is always "unknown" even in cases where email/password are incorrect.

Issue persists in a Flutter Demo Project with only firebase dependencies

### Steps to reproduce

1. Create a Flutter Demo Project

2. Add necessary code to initialise FirebaseApp

3. Add the following to  _incrementCounter() :

```
try {
      await FirebaseAuth.instance
          .signInWithEmailAndPassword(email: "email@domain.com", password: "password");
    } on FirebaseAuthMultiFactorException catch (e) {
      print(e.message);
      print(e.code);
      rethrow;
    } on FirebaseAuthException catch (e) {
      print(e.message);
      print(e.code);
      if (e.code == 'user-not-found') {
        print('The account does not exist');
      }
      if (e.code == 'second-factor-required') {
        print('Two factor challenge must be completed first');
      }
      if (e.code == 'multi-factor-auth-required') {
        print('Two factor challenge must be completed first');
      }
    }
```

4. Add necessary dependencies to pubspec.yaml and call pub.get

### Expected behavior

I am expecting a FirebaseAuthMultiFactorException where email and password are correct, otherwise a FirebaseAuthException with a code as before.

I need the FirebaseAuthMultiFactorException obviously so I can access the resolver, and I need the code in order to handle incorrect password, user does not exist etc cases.

## Additional context

Running Flutter Web version in Chrome on M1 MacBook

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.0, on macOS 13.3.1 22E772610a darwin-arm64, locale en-ZA)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.77.3)
[✓] Connected device (2 available)
[✓] Network resources

```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 3.0.0
Flutter SDK 3.10.0
testing 1.0.0+1

dependencies:
- cloud_firestore 4.7.0 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_interface flutter meta]
- cupertino_icons 1.0.5
- firebase_analytics 10.4.0 [firebase_analytics_platform_interface firebase_analytics_web firebase_core firebase_core_platform_interface flutter]
- firebase_app_check 0.1.4 [firebase_app_check_platform_interface firebase_app_check_web firebase_core firebase_core_platform_interface flutter]
- firebase_auth 4.6.0 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_auth_web 5.5.0 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser js meta]
- firebase_core 2.12.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_database 10.2.0 [firebase_core firebase_core_platform_interface firebase_database_platform_interface firebase_database_web flutter]
- firebase_storage 11.2.0 [firebase_core firebase_core_platform_interface firebase_storage_platform_interface firebase_storage_web flutter]
- flutter 0.0.0 [characters collection js material_color_utilities meta vector_math sky_engine]

dev dependencies:
- flutter_lints 2.0.1 [lints]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters collection js matcher material_color_utilities meta source_span stream_channel string_scanner term_glyph]

transitive dependencies:
- _flutterfire_internals 1.3.0 [collection firebase_core firebase_core_platform_interface flutter meta]
- async 2.11.0 [collection meta]
- boolean_selector 2.1.1 [source_span string_scanner]
- characters 1.3.0
- clock 1.1.1
- cloud_firestore_platform_interface 5.14.0 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 3.5.0 [_flutterfire_internals cloud_firestore_platform_interface collection firebase_core firebase_core_web flutter flutter_web_plugins js]
- collection 1.17.1
- fake_async 1.3.1 [clock collection]
- firebase_analytics_platform_interface 3.6.0 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_analytics_web 0.5.4 [_flutterfire_internals firebase_analytics_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- firebase_app_check_platform_interface 0.0.8 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_app_check_web 0.0.10 [_flutterfire_internals firebase_app_check_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- firebase_auth_platform_interface 6.15.0 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_core_platform_interface 4.8.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.5.0 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_database_platform_interface 0.2.5 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_database_web 0.2.3 [firebase_core firebase_core_web firebase_database_platform_interface flutter flutter_web_plugins js]
- firebase_storage_platform_interface 4.4.0 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_storage_web 3.6.0 [_flutterfire_internals async firebase_core firebase_core_web firebase_storage_platform_interface flutter flutter_web_plugins http js meta]
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta vector_math]
- http 0.13.6 [async http_parser meta]
- http_parser 4.0.2 [collection source_span string_scanner typed_data]
- js 0.6.7 [meta]
- lints 2.1.0
- matcher 0.12.15 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.2.0
- meta 1.9.1
- path 1.8.3
- plugin_platform_interface 2.1.4 [meta]
- sky_engine 0.0.99
- source_span 1.9.1 [collection path term_glyph]
- stack_trace 1.11.0 [path]
- stream_channel 2.1.1 [async]
- string_scanner 1.2.0 [source_span]
- term_glyph 1.2.1
- test_api 0.5.1 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.2 [collection]
- vector_math 2.1.4
```

</details>

---

**Comment by jayjay911** [comment] 2023-05-15 13:33
Not sure what you need to know specifically about the Firebase project, there's a registered web app and I'm using the same configuration which has been working fine for over a year.

The only change was client side ie upgrading Flutter to 3.10.0 and all the Firebase dependencies to support Dart 3. Then suddenly my Firebase sign in stopped working as it should.

Is the following sample of code enough or do you need a github project?

Added only the following dependencies to pubspec.yaml:

  firebase_core: any
  firebase_analytics: any
  firebase_storage: any
  cloud_firestore: any
  firebase_database: any
  firebase_auth: any
  firebase_auth_web: any
  firebase_app_check: any

### Minimal Reproducible Code

<details><summary>Click To Expand</summary>

```
Future<FirebaseApp> initialize() async {
  // devConfig (FirebaseOptions) and developmentSiteKey kept private for obvious reasons.
  
  var app = await Firebase.initializeApp(options: devConfig);

  await FirebaseAppCheck.instance
      .activate(webRecaptchaSiteKey: developmentSiteKey);

  return app;
}

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  var _fbApp;
  _fbApp = initialize();
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  var fbApp;
  MyApp({super.key, this.fbApp});

  @override
  Widget build(BuildContext context) {
    return FutureBuilder(
      future: fbApp,
      builder: (BuildContext context, AsyncSnapshot<dynamic> snapshot) {
        return MaterialApp(
          title: 'Flutter Demo',
          theme: ThemeData(
            colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
            useMaterial3: true,
          ),
          home: const MyHomePage(title: 'Flutter Demo Home Page'),
        );
      },
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  Future<void> _incrementCounter() async {
    try {
      await FirebaseAuth.instance
          .signInWithEmailAndPassword(email: "jason.phillip.moore@gmail.com", password: "123456");
      // return "successful";
    } on FirebaseAuthMultiFactorException catch (e) {
      print(e.message);
      print(e.code);
      rethrow;
    } on FirebaseAuthException catch (e) {
      print(e.message);
      print(e.code);
      if (e.code == 'user-not-found') {
        print('The account does not exist');
      }
      if (e.code == 'second-factor-required') {
        print('Two factor challenge must be completed first');
      }
      if (e.code == 'multi-factor-auth-required') {
        print('Two factor challenge must be completed first');
      }
      // return e.code;
    }
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headlineMedium,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

```

</details>

---

**Comment by jayjay911** [comment] 2023-05-16 06:54
Downgrading Flutter back to version 3.7.12 and Dart back to version 2.19.6 immediately resolved the issue, error code is set and not "unknown" and the FirebaseAuthMultiFactorException is thrown properly.

So issue only occurs when I upgrade to Flutter 3.10.0 and Dart 3.

**Comment by danagbemava-nc** [comment] 2023-05-16 12:13
Thanks for the details. 

I can reproduce the error code being returned as unknown using the sample provided above on stable 3.10.0 but on stable 3.7.12, the error code is properly stated. I was only able to reproduce this on the web. My firebase project was not set up to use SMS MFA so the `FirebaseAuthException` block is what was always executed. 

Labeling for further investigation

<details>
<summary>Running on flutter 3.7.12</summary>

```
🔥  To hot restart changes while running, press "r" or "R".
For a more detailed help message, press "h". To quit, press "q".

An Observatory debugger and profiler on Chrome is available at: http://127.0.0.1:63011/jLprpnjAz0s=
The Flutter DevTools debugger and profiler on Chrome is available at: http://127.0.0.1:9100?uri=http://127.0.0.1:63011/jLprpnjAz0s=
FirebaseAuthException
The password is invalid or the user does not have a password.
wrong-password

Performing hot restart...                                        2,208ms
Restarted application in 2,210ms.
FirebaseAuthException
There is no user record corresponding to this identifier. The user may have been deleted.
user-not-found
The account does not exist
```
</details>

<details>
<summary>Running on flutter 3.10.0</summary>

```
A Dart VM Service on Chrome is available at: http://127.0.0.1:62231/ILEXAYtnLY0=
The Flutter DevTools debugger and profiler on Chrome is available at: http://127.0.0.1:9101?uri=http://127.0.0.1:62231/ILEXAYtnLY0=
FirebaseAuthException
An unknown error occurred: FirebaseError: Firebase: There is no user record corresponding to this identifier. The user may have been deleted. (auth/user-not-found).
unknown

Performing hot restart...                                          804ms
Restarted application in 809ms.
FirebaseAuthException
An unknown error occurred: FirebaseError: Firebase: The password is invalid or the user does not have a password. (auth/wrong-password).
unknown
```
</details>

**Comment by dotjon0** [comment] 2023-05-19 18:46
any updates on this?

**Comment by ntherndon97** [comment] 2023-05-24 02:03
This also affecting my app as well. Any updates would be great as to what is happening with this.

**Comment by jubnl** [comment] 2023-05-31 14:30
Until this is fixed, here's a regex that will extract the code of a FirebaseAuthException:

Note: This fix is temporary; as soon as a patch is deployed, we should use it.
```dart
String parseFirebaseAuthExceptionMessage({String plugin = "auth", required String? input}) {
  if (input == null) {
    return "unknown";
  }

  // https://regexr.com/7en3h
  String regexPattern = r'(?<=\(' + plugin + r'/)(.*?)(?=\)\.)';
  RegExp regExp = RegExp(regexPattern);
  Match? match = regExp.firstMatch(input);
  if (match != null) {
    return match.group(0)!;
  }

  return "unknown";
}
```

Usage:
```dart
try {
  // operation that might throw a FirebaseAuthException
} on FirebaseAuthException catch (e) {
  // change the plugin argument if needed
  // final code = parseFirebaseAuthExceptionMessage(input: e.message, plugin: "other");
  final code = parseFirebaseAuthExceptionMessage(input: e.message);
  if (code == "user-not-found") {
    // handle exception
  }
}
```

**Comment by agrimshar** [comment] 2023-06-01 07:04
Yeah I'm getting the same issue.

**Comment by jperezr21** [comment] 2023-06-03 20:23
Same issue here:

![image](https://github.com/firebase/flutterfire/assets/12447726/c42c2d2e-dd3d-4de4-be77-cfb6bc9e6c21)

**Comment by Rajeet10** [comment] 2023-06-06 08:46
Could anybody tell me how to fix it now in the latest flutter version?

**Comment by hydev777** [comment] 2023-06-16 02:45
Having the same problem here, all throw exception are coming unknown.

**Comment by kNoAPP** [comment] 2023-06-16 15:27
This is impacting my project as well. Running `firebase_auth` v4.6.2. This code used to work, but has since stopped being functional due to bad parsing internal to the `firebase_auth` library.

From my debugging session:
I purposely entered a correct email, but wrong password into a cloud Firebase Auth instance. Notice that while the FirebaseError contains all the correct/expected information, the debugger object does not. It doesn't appear to correctly parse this information out of the message.

DEBUG from VSC:
```
FirebaseAuthException ([firebase_auth/unknown] An unknown error occurred: FirebaseError: Firebase: The password is invalid or the user does not have a password. (auth/wrong-password).)


code: "unknown"
credential: null
email: null
message: "An unknown error occurred: FirebaseError: Firebase: The password is invalid or the user does not have a password. (auth/wrong-password)."
phoneNumber: null
plugin: "firebase_auth"
stackTrace: null
tenantId: null
```

SCREENSHOT:
![Screenshot 2023-06-16 081944](https://github.com/firebase/flutterfire/assets/23529044/82bae427-6629-41b5-8c65-6c7ca686175d)

**Comment by RaphaelRat** [comment] 2023-06-24 13:11
I also have the same issue but it works in debug mode, I only have this problem when deploying to Firebase or Gh pages.

**Comment by abderrahmen13** [comment] 2023-06-26 08:59
I have the same issue.

**Comment by sarmuelThee** [comment] 2023-07-08 00:27
hello, i am trying to do this exact thing in flutter flow (creating an authentication custom action ) and it throws the same kind of errors for me too, is there ant work around?

**Comment by anjogithub** [comment] 2023-07-10 07:03
is there any updates on this bug? also encountered this error. I alos need the FirebaseAuthMultiFactorExceptionto be able to access the resolver.

**Comment by anjogithub** [comment] 2023-07-17 09:19
i tried updating my flutter version  and firebas euth to latest versions, the error still occurs. Hopefully it would be fixed on next updates of firebase auth plugin.  
Any updates on this error/bug on web?

**Comment by Shawn-sudo** [comment] 2023-07-18 02:02
I'm experiencing a somewhat similar issue on iOS. This issue might not be limited to web only.

<img width="506" alt="Screenshot 2023-07-17 at 9 38 50 PM" src="https://github.com/firebase/flutterfire/assets/60294318/d4d926e2-cfd3-4803-96d9-1006bd6f1249">

One thing different from you guys is that I see a weird code starting with `0x` instead of a friendly error message.

**Comment by anjogithub** [comment] 2023-07-20 09:13
I am stuck on this error. Can't proceed to completeley implement Firebase MFA.
It almost 2 weeks now that i encountered this.
Badly needed a fix for this.

**Closed** 2023-07-25 07:19 UTC
Labels: type: bug, plugin: auth, platform: web, blocked-by-flutter

**Comment by anjogithub** [comment] 2023-07-25 08:09
if i may ask, how can we apply the fix? will this fix be included in the next updates of firebase_auth?

**Comment by russellwheatley** [comment] 2023-07-25 10:30
@anjogithub - will be out in the next release at some point today 👍

**Comment by papiqo** [comment] 2023-08-20 10:15
i got the same problem, i changed it to get_user_by_email, i can get uid, but my app can't use authentication
