### ISSUE TITLE
 Flutter Android Notification Count is Always null

### ISSUE THREAD

**Issue by axiftaj** [firebase/flutterfire#10899] opened 2023-05-03 11:46 UTC
This is the original ticket on which you guys are not responding though you guys have mention we will communiated on this #10659 

link:  https://github.com/firebase/flutterfire/issues/10659

source code of repo: https://github.com/axiftaj/Flutter-Firebase-Notifications/blob/331823ccad38f2e66e204a4da07975270dca3bcc/lib/main.dart#L15

I have attach the video below to prove that this is not an http error and something is wrong with plugin because it's showing title and boyd but the the count.

Video link: https://youtu.be/G86qZRswKtE

Looking forward for the response.  

PS: Also i see firebase team is only making me open new ticket rather than escalating issue within the team to discussion it father provide the solution. Firebase team is quickly closing the ticket without hearing back from me.

**Comment by darshankawar** [comment] 2023-05-04 10:11
I discussed about this issue with @Lyokone and he said he'll revisit this soon.

Per our earlier verificaton, we were not able to replicate it: https://github.com/firebase/flutterfire/issues/10659#issuecomment-1512826583, https://github.com/firebase/flutterfire/issues/10659#issuecomment-1497429865

**Comment by axiftaj** [comment] 2023-05-04 10:33
> I discussed about this issue with @Lyokone and he said he'll revisit this soon.
> 
> Per our earlier verificaton, we were not able to replicate it: [#10659 (comment)](https://github.com/firebase/flutterfire/issues/10659#issuecomment-1512826583), [#10659 (comment)](https://github.com/firebase/flutterfire/issues/10659#issuecomment-1497429865)



Thank you again investigating it, i really appreciate it.  

Also if you guys didn't able to replicated the issues you should please ask for more details rather than closing the tickets again and again 

Please don't closed the ticket until we reached the conclusion as this lead to opening the new ticket and this is a time consuming process for both of us.  

I have also added the video evidence to prove my statement.

**Comment by darshankawar** [comment] 2023-05-04 10:57
> Please don't closed the ticket until we reached the conclusion as this lead to opening the new ticket and this is a time consuming process for both of us.

@axiftaj We never closed the ticket without providing solution. In the first issue you reported, we provided https://github.com/firebase/flutterfire/issues/10659#issuecomment-1512984550

https://github.com/firebase/flutterfire/issues/10800 was a self-duplicate of first issue so we mentioned to follow-up in first.

Also, for your reference: https://github.com/firebase/flutterfire/issues/10800#issuecomment-1513134966

**Comment by axiftaj** [comment] 2023-05-04 11:06
> > Please don't closed the ticket until we reached the conclusion as this lead to opening the new ticket and this is a time consuming process for both of us.
> 
> @axiftaj We never closed the ticket without providing solution. In the first issue you reported, we provided [#10659 (comment)](https://github.com/firebase/flutterfire/issues/10659#issuecomment-1512984550)
> 
> #10800 was a self-duplicate of first issue so we mentioned to follow-up in first.
> 
> Also, for your reference: [#10800 (comment)](https://github.com/firebase/flutterfire/issues/10800#issuecomment-1513134966)

I think i disagree with this statement. 

Here is why: 

We agree to keep the follow up on this issue #10659 so we agree to closed issue #10800  

You guys provided the solution, i implemented it and i think solution provider by your team is not solving the issue

Without hearing back from me my original ticket #10659 got closed 2 times and your opened it again. 

This current ticket is the copy of my last comment on issue #10659 which wasn't address so i have again opened the new issue.

**Comment by axiftaj** [comment] 2023-05-16 05:28
@darshankawar  Hello, any update on this ?

**Comment by axiftaj** [comment] 2023-05-20 06:44
@Lyokone 
Here is the detail video have i created to show the whole process and steps i am following to show notifications. I hope this will help. 
You guys and take a look into my repository or you can use this step on the example repo provided in firebase messaging pub package  to reproduced the issue. 

Source code: https://github.com/axiftaj/Flutter-Firebase-Notifications 
Vidoe link: https://youtu.be/HwaTW9C6d2A

**Comment by axiftaj** [comment] 2023-05-25 10:52
@Lyokone  @darshankawar  any update on this, i see ticket is label as blocked customer-response. 
I have provider detail video tour  to help producing the issue.

**Comment by axiftaj** [comment] 2023-06-05 07:59
@darshankawar  any update on this

**Comment by axiftaj** [comment] 2023-06-16 11:23
Hello @darshankawar any update on this

**Comment by russellwheatley** [comment] 2023-06-26 15:23
We would like the request you are making, we need to be able to reproduce. We have already tested and were unable to reproduce. The more detail you give us the more likely we can hone in the issue. Thanks.

**Comment by axiftaj** [comment] 2023-06-26 18:32
@russellwheatley  I would love hear what details you need.  I have already explain the whole process in a video and have provided the source code in repo.  
@darshankawar

**Comment by axiftaj** [comment] 2023-07-10 10:11
@russellwheatley  @darshankawar 
Can you guys please respond to my last comment.

**Comment by isshort** [comment] 2023-09-05 07:26
The same error happened to me .

**Comment by TungLam111** [comment] 2023-11-04 14:34
> This is the original ticket on which you guys are not responding though you guys have mention we will communiated on this #10659
> 
> link: #10659
> 
> source code of repo: https://github.com/axiftaj/Flutter-Firebase-Notifications/blob/331823ccad38f2e66e204a4da07975270dca3bcc/lib/main.dart#L15
> 
> I have attach the video below to prove that this is not an http error and something is wrong with plugin because it's showing title and boyd but the the count.
> 
> Video link: https://youtu.be/G86qZRswKtE
> 
> Looking forward for the response.
> 
> PS: Also i see firebase team is only making me open new ticket rather than escalating issue within the team to discussion it father provide the solution. Firebase team is quickly closing the ticket without hearing back from me.

It's always null if you try to making request with that endpoint. take a look at https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages/send , use service account credential to generate an access token through OAuth2. Hope this help :)))

**Comment by russellwheatley** [comment] 2023-12-20 12:53
Please use this nodeje Firebase admin SDK to send messages:

```js
const admin = require('firebase-admin');
// Get service account key from firebase console
const serviceAccount = require('../ff-e2e-service.json');
admin.initializeApp({
  credential: admin.credential.cert(serviceAccount),
});
const androidToken = 'TOKEN';
admin
.messaging()
.send(
  {
    token: androidToken,
    data: {
      something:'another',
    },
    notification: {
      title: 'blah',
      body: 'Great content',
    
    },
    android: {
      priority: 'high',
      notification: {
		// THIS SETS NOTIFICATION COUNT
        notificationCount: 4,
      }
    },
  },
  
)
```

You will observe the notification count as `4` which is what is set in the script above. I've just tested this on the example app on my android device. Closing as this isn't an issue on FlutterFire.

**Closed by russellwheatley** 2023-12-20 12:53 UTC
Labels: type: bug, plugin: messaging, platform: android, Needs Attention
