### ISSUE TITLE
🐛 [firebase_performance] iOS not launching when pre-fetching firestore on 10.18.0

### ISSUE THREAD

**Issue by jainharsh21** [firebase/flutterfire#12069] opened 2023-12-22 09:58 UTC
## Bug report

**Describe the bug**
After adding firebase performance sdk to flutter application, we need to upgrade the minimum iOS deployment target to atleast 12. Post that if you have this line enabled in your podfile, the build is successful but launching fails saying can't build pre-compiled version of the application. Now we have do disable this line to have the build running but it becomes extremely slow.

  pod 'FirebaseFirestore', :git => 'https://github.com/invertase/firestore-ios-sdk-frameworks.git', :tag => '10.18.0'

**Comment by lyabs243** [comment] 2023-12-22 10:17
I have the same issue since +2 weeks now, I did many search but I am not able to find the solution. Hope someone can help on this.

**Comment by danagbemava-nc** [comment] 2023-12-22 11:00
Hi @jainharsh21, @lyabs243  what errors do you get and can you check https://github.com/invertase/firestore-ios-sdk-frameworks/issues/79 to see if it is similar to your case?

**Comment by lyabs243** [comment] 2023-12-22 12:15
Hi @danagbemava-nc , yes it is the same issue that https://github.com/invertase/firestore-ios-sdk-frameworks/issues/79 

According to the discussion a solution is to downgrade Firebase package issues and to Pinned for iOS SDK 10.16.0 in pod file but when I do that it keep telling me to update it to 10.1.0

**Comment by lyabs243** [comment] 2023-12-23 09:44
[UPDATE]

I fixed the issue after using **ccache** as explained [here](https://github.com/invertase/firestore-ios-sdk-frameworks/discussions/82).

**Comment by ajsharp** [comment] 2023-12-30 00:01
@lyabs243 massive thanks for linking this. Confirmed works for me as well.

**Comment by danagbemava-nc** [comment] 2024-01-02 11:05
Thanks for the update. I'll be closing this since the issue is from the precache and not the plugin itself.

**Closed by danagbemava-nc** 2024-01-02 11:05 UTC
Labels: type: bug, blocked: customer-response, in triage
