### ISSUE TITLE
🐛 [firebase_auth] Authenticated user is signed out if web app is started or reloaded without network connection

### ISSUE THREAD

**Issue by ScottAtRedHawk** [firebase/flutterfire#10748] opened 2023-04-08 16:12 UTC
## Bug report

**Describe the bug**
While connected with WiFi or mobile data, authentication works fine across page reloads and app restarts. When a user starts the web app without a network connection, the persisted IndexedDB database is deleted and the user is signed out. The user should be able to stay authenticated. I'm using the email/password provider. I thought the issue sounded similar to [this one](https://github.com/firebase/firebase-js-sdk/issues/5529) but the fix doesn't seem to work.

### Steps to reproduce

1. Sign in using email/password.
2. Disable WiFi/mobile data.
3. Reload the page or close the browser and reopen it.
4. The user is signed out.

### Expected behavior

The user should still be authenticated after a reloading or starting the web app without a network connection.

This [demo](https://pwachitchat.firebaseapp.com/) has the expected behavior regarding authentication and being offline. Here is the [article](https://ankitmaheshwariin.medium.com/build-a-progressive-web-app-pwa-with-ionic-4-ionic-framework-and-firebase-48183519c01) I found it from. The fact that it's using ionic shouldn't be an issue. I'd expect firebase to behave the same.

### Sample project

---

## Additional context

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.10, on macOS 13.3 22E252 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] VS Code (version 1.77.1)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.19.6
Flutter SDK 3.7.10

dependencies:
- cloud_firestore 4.5.0 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_interface flutter meta]
- cloud_functions 4.1.0 [cloud_functions_platform_interface cloud_functions_web firebase_core firebase_core_platform_interface flutter]
- cupertino_icons 1.0.5
- firebase_auth 4.4.0 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 2.9.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_remote_config 4.0.0 [firebase_core firebase_core_platform_interface firebase_remote_config_platform_interface firebase_remote_config_web flutter]
- flutter 0.0.0 [characters collection js material_color_utilities meta vector_math sky_engine]
- flutter_animate 4.1.1+1 [flutter]
- flutter_svg 2.0.4 [flutter vector_graphics vector_graphics_codec vector_graphics_compiler]
- freezed_annotation 2.2.0 [collection json_annotation meta]
- image_picker 0.8.7+1 [flutter image_picker_android image_picker_for_web image_picker_ios image_picker_platform_interface]
- intl 0.17.0 [clock path]
- json_annotation 4.8.0 [meta]
- quiver 3.2.1 [matcher]
- responsive_builder 0.6.4 [flutter provider]
- stacked 3.2.0 [flutter get_it meta provider collection stacked_shared universal_io path]
- stacked_services 1.0.0 [flutter stacked_shared stacked get crypto]
- url_launcher 6.1.10 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- url_strategy 0.2.0 [flutter_web_plugins]

dev dependencies:
- build_runner 2.3.3 [args async analyzer build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style frontend_server_client glob graphs http_multi_server io js logging meta mime package_config path pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web_socket_channel yaml]
- flutter_launcher_icons 0.12.0 [args checked_yaml cli_util image json_annotation path yaml]
- flutter_lints 2.0.1 [lints]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters collection js matcher material_color_utilities meta source_span stream_channel string_scanner term_glyph]
- freezed 2.3.2 [analyzer build build_config collection meta source_gen freezed_annotation json_annotation]
- json_serializable 6.6.1 [analyzer async build build_config collection json_annotation meta path pub_semver pubspec_parse source_gen source_helper]
- mockito 5.4.0 [analyzer build code_builder collection dart_style matcher meta path source_gen test_api]
- stacked_generator 1.1.0 [build path recase source_gen meta logger stacked_shared analyzer dart_style code_builder collection freezed_annotation json_annotation]

dependency overrides:
- flutter_svg 2.0.4 [flutter vector_graphics vector_graphics_codec vector_graphics_compiler]

transitive dependencies:
- _fe_analyzer_shared 55.0.0 [meta]
- _flutterfire_internals 1.1.0 [collection firebase_core firebase_core_platform_interface flutter meta]
- analyzer 5.7.1 [_fe_analyzer_shared collection convert crypto glob meta package_config path pub_semver source_span watcher yaml]
- archive 3.3.6 [crypto path pointycastle]
- args 2.4.0
- async 2.10.0 [collection meta]
- boolean_selector 2.1.1 [source_span string_scanner]
- build 2.3.1 [analyzer async convert crypto glob logging meta path]
- build_config 1.1.1 [checked_yaml json_annotation path pubspec_parse yaml]
- build_daemon 3.1.1 [built_collection built_value http_multi_server logging path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 2.2.0 [analyzer async build collection crypto graphs logging path package_config pool pub_semver stream_transform yaml]
- build_runner_core 7.2.7 [async build build_config build_resolvers collection convert crypto glob graphs json_annotation logging meta path package_config pool timing watcher yaml]
- built_collection 5.1.1
- built_value 8.4.4 [built_collection collection fixnum meta]
- characters 1.2.1
- checked_yaml 2.0.2 [json_annotation source_span yaml]
- cli_util 0.3.5 [meta path]
- clock 1.1.1
- cloud_firestore_platform_interface 5.12.0 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 3.4.0 [_flutterfire_internals cloud_firestore_platform_interface collection firebase_core firebase_core_web flutter flutter_web_plugins js]
- cloud_functions_platform_interface 5.2.0 [firebase_core flutter meta plugin_platform_interface]
- cloud_functions_web 4.4.0 [cloud_functions_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- code_builder 4.4.0 [built_collection built_value collection matcher meta]
- collection 1.17.0
- convert 3.1.1 [typed_data]
- cross_file 0.3.3+4 [js meta]
- crypto 3.0.2 [typed_data]
- dart_style 2.2.5 [analyzer args path pub_semver source_span]
- fake_async 1.3.1 [clock collection]
- file 6.1.4 [meta path]
- firebase_auth_platform_interface 6.13.0 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 5.3.0 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core_platform_interface 4.6.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.3.0 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_remote_config_platform_interface 1.2.0 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_remote_config_web 1.2.0 [firebase_core firebase_core_web firebase_remote_config_platform_interface flutter flutter_web_plugins js]
- fixnum 1.1.0
- flutter_plugin_android_lifecycle 2.0.9 [flutter]
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta vector_math]
- frontend_server_client 3.2.0 [async path]
- get 4.6.5 [flutter]
- get_it 7.2.0 [async collection]
- glob 2.1.1 [async collection file path string_scanner]
- graphs 2.2.0 [collection]
- http 0.13.5 [async http_parser meta path]
- http_multi_server 3.2.1 [async]
- http_parser 4.0.2 [collection source_span string_scanner typed_data]
- image 4.0.15 [archive meta xml]
- image_picker_android 0.8.6+1 [flutter flutter_plugin_android_lifecycle image_picker_platform_interface]
- image_picker_for_web 2.1.12 [flutter flutter_web_plugins image_picker_platform_interface]
- image_picker_ios 0.8.7+1 [flutter image_picker_platform_interface]
- image_picker_platform_interface 2.6.3 [cross_file flutter http plugin_platform_interface]
- io 1.0.4 [meta path string_scanner]
- js 0.6.5 [meta]
- lints 2.0.1
- logger 1.2.2
- logging 1.1.1
- matcher 0.12.13 [meta stack_trace]
- material_color_utilities 0.2.0
- meta 1.8.0
- mime 1.0.4
- nested 1.0.0 [flutter]
- package_config 2.1.0 [path]
- path 1.8.2
- path_parsing 1.0.1 [vector_math meta]
- petitparser 5.1.0 [meta]
- plugin_platform_interface 2.1.4 [meta]
- pointycastle 3.6.2 [collection convert js]
- pool 1.5.1 [async stack_trace]
- provider 6.0.5 [collection flutter nested]
- pub_semver 2.1.3 [collection meta]
- pubspec_parse 1.2.2 [checked_yaml collection json_annotation pub_semver yaml]
- recase 4.1.0
- shelf 1.4.0 [async collection http_parser path stack_trace stream_channel]
- shelf_web_socket 1.0.3 [shelf stream_channel web_socket_channel]
- sky_engine 0.0.99
- source_gen 1.2.7 [analyzer async build dart_style glob path source_span yaml]
- source_helper 1.3.3 [analyzer collection source_gen]
- source_span 1.9.1 [collection path term_glyph]
- stack_trace 1.11.0 [path]
- stacked_shared 1.3.0 [get_it]
- stream_channel 2.1.1 [async]
- stream_transform 2.1.0
- string_scanner 1.2.0 [source_span]
- term_glyph 1.2.1
- test_api 0.4.16 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- timing 1.0.1 [json_annotation]
- typed_data 1.3.1 [collection]
- universal_io 2.2.0 [collection meta typed_data]
- url_launcher_android 6.0.25 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.1.2 [flutter url_launcher_platform_interface]
- url_launcher_linux 3.0.4 [flutter url_launcher_platform_interface]
- url_launcher_macos 3.0.4 [flutter url_launcher_platform_interface]
- url_launcher_platform_interface 2.1.2 [flutter plugin_platform_interface]
- url_launcher_web 2.0.16 [flutter flutter_web_plugins url_launcher_platform_interface]
- url_launcher_windows 3.0.5 [flutter url_launcher_platform_interface]
- vector_graphics 1.1.4 [flutter vector_graphics_codec]
- vector_graphics_codec 1.1.4
- vector_graphics_compiler 1.1.4 [args meta path_parsing xml vector_graphics_codec]
- vector_math 2.1.4
- watcher 1.0.2 [async path]
- web_socket_channel 2.3.0 [async crypto stream_channel]
- xml 6.2.2 [collection meta petitparser]
- yaml 3.1.1 [collection source_span string_scanner]
```

</details>

---

**Comment by danagbemava-nc** [comment] 2023-04-10 13:43
I can reproduce the issue using the firebase_auth example. I tested with both debug and release mode and the bug reproduced in either mode. I run the app using the following command `flutter run -d web-server`. It also reproduced whether or not I run it that way. 

https://user-images.githubusercontent.com/88313112/230901627-d9bd0e44-5960-4a9e-aba8-e163b771ec87.mov

**Comment by ScottAtRedHawk** [comment] 2023-04-10 13:56
Thanks for looking into this so quickly @danagbemava-nc!

**Comment by joeydrees** [comment] 2023-04-10 17:06
I'm experiencing this problem for my web app as well, please advise.

**Comment by gscottschulz** [comment] 2023-04-11 01:47
I'm experiencing the same problem. Is there any ETA on a fix?

**Comment by Lyokone** [comment] 2023-04-18 12:09
Thanks for the report, i'll have a look

**Comment by ScottAtRedHawk** [comment] 2023-04-21 15:48
@Lyokone Have you had any progress with this? Thanks for helping!

**Comment by TarekkMA** [comment] 2024-04-23 13:20
I've retested this issue on the latest version and couldn't reproduce it, so I will close this issue for now. Please feel free to open a new issue if the problem resurfaces. We’re here to assist you!

**Closed by TarekkMA** 2024-04-23 13:20 UTC
Labels: type: bug, plugin: auth, platform: web
