### ISSUE TITLE
 FirebaseAuth.instance.currentUser always null on windows app flutter !!

### ISSUE THREAD

**Issue by Hmida71** [firebase/flutterfire#12734] opened 2024-05-01 17:50 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Core, Auth

### Which platforms are affected?

Windows

### Description

FirebaseAuth.instance.currentUser always null on windows app flutter ?

### Reproducing the issue

I am seeing this issue too on Windows. After I sign in/email-pass sign in, hot restarting the app returns currentUser as null. This also happens on subsequent app runs too.

In my case, it is always null, even after few seconds. I tried this:

```dart
FirebaseAuth.instance.authStateChanges().listen((event) {
      print('Auth state changed: $event');
});
and this : 
final userGoogle = FirebaseAuth.instance.currentUser;
    print(userGoogle);
    if (userGoogle == null) {
      isLogin = false;
    } else {
      isLogin = true;
    }
```
and it only prints null and never prints again. ??

### Firebase Core version

2.30.0

### Flutter Version

3.19.5

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Replace this line with the contents of your `flutter pub deps -- --style=compact`.

```

</details>

**Comment by TarekkMA** [comment] 2024-05-02 08:43
@Hmida71 Thank you for reporting this issue. 

Can you try this on andoird or ios and see if you have the same issue?

**Comment by russellwheatley** [comment] 2024-05-13 10:27
This is a duplicate of this issue: https://github.com/firebase/flutterfire/issues/12055 

closing out in favour of tracking there

**Closed by russellwheatley** 2024-05-13 10:27 UTC
Labels: type: bug, plugin: auth, Needs Attention, platform: windows
