### ISSUE TITLE
🐛 [cloud_firestore: ^4.11.0] FIRESTORE INTERNAL ASSERTION FAILED crashes on macOS

### ISSUE THREAD

**Issue by bat-guy** [firebase/flutterfire#11762] opened 2023-10-23 22:14 UTC
## Bug report

Firestore plugin crashes when trying to read from the collections. The same code however works for iOS simulator perfectly.
System properties:

```dart
- Xcode verison: 15.0
- MacOS version: 14.0
- iOS simulator version: iPhone 15 pro max 
- iOS version: 17.0
- Flutter version: 3.3.16
- firebase_core: ^2.19.0
- cloud_firestore: ^4.11.0
- firebase_auth: ^4.10.0
- firebase_storage: ^11.28.0 
``` 

Crash log:
```dart
*** Assertion failure in void firebase::firestore::core::FirestoreClient::Initialize(const User &, const Settings &)(), /Users/apple/Documents/Projects/flutter_mac/macos/Pods/FirebaseFirestore/Firestore/core/src/core/firestore_client.cc:217
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'FIRESTORE INTERNAL ASSERTION FAILED: Failed to open DB: Internal: Failed to open LevelDB database at /Users/apple/Library/Containers/com.example.flutterMac/Data/Library/Application Support/firestore/__FIRAPP_DEFAULT/flutter-chat-cfc59/main: LevelDB error: IO error: lock /Users/apple/Library/Containers/com.example.flutterMac/Data/Library/Application Support/firestore/__FIRAPP_DEFAULT/flutter-chat-cfc59/main/LOCK: Resource temporarily unavailable (expected created.ok())'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000180cbc8c0 __exceptionPreprocess + 176
	1   libobjc.A.dylib                     0x00000001807b5eb4 objc_exception_throw + 60
	2   Foundation                          0x0000000182428364 -[NSMutableDictionary(NSMutableDictionary) initWithContentsOfFile:] + 0
	3   FirebaseFirestore                   0x0000000102dd2624 _ZN8firebase9firestore4util16ObjcThrowHandlerENS1_13ExceptionTypeEPKcS4_iRKNSt3__112basic_stringIcNS5_11char_traitsIcEENS5_9allocatorIcEEEE + 324
	4   FirebaseFirestore                   0x0000000102dd1d08 _ZN8firebase9firestore4util5ThrowENS1_13ExceptionTypeEPKcS4_iRKNSt3__112basic_stringIcNS5_11char_traitsIcEENS5_9allocatorIcEEEE + 64
	5   FirebaseFirestore                   0x0000000102efc700 _ZN8firebase9firestore4util8internal13FailAssertionEPKcS4_iRKNSt3__112basic_stringIcNS5_11char_traitsIcEENS5_9allocatorIcEEEES4_ + 0
	6   FirebaseFirestore                   0x0000000102efc7b0 _ZN8firebase9firestore4util8internal13FailAssertionEPKcS4_iRKNSt3__112basic_stringIcNS5_11char_traitsIcEENS5_9allocatorIcEEEES4_ + 176
	7   FirebaseFirestore                   0x0000000102e2ce30 _ZN8firebase9firestore4core15FirestoreClient10InitializeERKNS0_11credentials4UserERKNS0_3api8SettingsE + 424
	8   FirebaseFirestore                   0x0000000102e38248 _ZZZN8firebase9firestore4core15FirestoreClient6CreateERKNS1_12DatabaseInfoERKNS0_3api8SettingsENSt3__110shared_ptrINS0_11credentials19CredentialsProviderINSC_9AuthTokenENSC_4UserEEEEENSB_INSD_INS	
        9   FirebaseFirestore                   0x0000000102e3820c _ZNSt3__18__invokeB7v160006IRZZN8firebase9firestore4core15FirestoreClient6CreateERKNS3_12DatabaseInfoERKNS2_3api8SettingsENS_10shared_ptrINS2_11credentials19CredentialsProviderINSD_9AuthTokenENSD	
        10  FirebaseFirestore                   0x0000000102e381c4 _ZNSt3__128__invoke_void_return_wrapperIvLb1EE6__callIJRZZN8firebase9firestore4core15FirestoreClient6CreateERKNS5_12DatabaseInfoERKNS4_3api8SettingsENS_10shared_ptrINS4_11credentials19Credentials	
        11  FirebaseFirestore                   0x0000000102e381a0 _ZNSt3__110__function12__alloc_funcIZZN8firebase9firestore4core15FirestoreClient6CreateERKNS4_12DatabaseInfoERKNS3_3api8SettingsENS_10shared_ptrINS3_11credentials19CredentialsProviderINSE_9AuthTo	
        12  FirebaseFirestore                   0x0000000102e36e94 _ZNSt3__110__function6__funcIZZN8firebase9firestore4core15FirestoreClient6CreateERKNS4_12DatabaseInfoERKNS3_3api8SettingsENS_10shared_ptrINS3_11credentials19CredentialsProviderINSE_9AuthTokenENSE	
        13  FirebaseFirestore                   0x0000000102ced0d0 _ZNKSt3__110__function12__value_funcIFvvEEclB7v160006Ev + 68
        14  FirebaseFirestore                   0x0000000102cea7c0 _ZNKSt3__18functionIFvvEEclEv + 24
	15  FirebaseFirestore                   0x0000000102cea780 _ZN8firebase9firestore4util10AsyncQueue15ExecuteBlockingERKNSt3__18functionIFvvEEE + 176
	16  FirebaseFirestore                   0x0000000102cef2ac _ZZN8firebase9firestore4util10AsyncQueue4WrapERKNSt3__18functionIFvvEEEENK3$_0clEv + 32
	17  FirebaseFirestore                   0x0000000102cef280 _ZNSt3__18__invokeB7v160006IRZN8firebase9firestore4util10AsyncQueue4WrapERKNS_8functionIFvvEEEE3$_0JEEEDTclclsr3stdE7declvalIT_EEspclsr3stdE7declvalIT0_EEEEOSC_DpOSD_ + 24
	18  FirebaseFirestore                   0x0000000102cef238 _ZNSt3__128__invoke_void_return_wrapperIvLb1EE6__callIJRZN8firebase9firestore4util10AsyncQueue4WrapERKNS_8functionIFvvEEEE3$_0EEEvDpOT_ + 24
	19  FirebaseFirestore                   0x0000000102cef214 _ZNSt3__110__function12__alloc_funcIZN8firebase9firestore4util10AsyncQueue4WrapERKNS_8functionIFvvEEEE3$_0NS_9allocatorISB_EES7_EclB7v160006Ev + 28
	20  FirebaseFirestore                   0x0000000102cedfa8 _ZNSt3__110__function6__funcIZN8firebase9firestore4util10AsyncQueue4WrapERKNS_8functionIFvvEEEE3$_0NS_9allocatorISB_EES7_EclEv + 28
	21  FirebaseFirestore                   0x0000000102ced0d0 _ZNKSt3__110__function12__value_funcIFvvEEclB7v160006Ev + 68
	22  FirebaseFirestore                   0x0000000102cea7c0 _ZNKSt3__18functionIFvvEEclEv + 24
	23  FirebaseFirestore                   0x00000001031280b8 _ZN8firebase9firestore4util4Task17ExecuteAndReleaseEv + 180
	24  FirebaseFirestore                   0x0000000102dd3194 _ZN8firebase9firestore4util19ExecutorLibdispatch11InvokeAsyncEPv + 32
	25  libdispatch.dylib                   0x00000001809bd910 _dispatch_client_callout + 20
	26  libdispatch.dylib                   0x00000001809c4ea4 _dispatch_lane_serial_drain + 748
	27  libdispatch.dylib                   0x00000001809c59d4 _dispatch_lane_invoke + 380
	28  libdispatch.dylib                   0x00000001809d061c _dispatch_root_queue_drain_deferred_wlh + 288
	29  libdispatch.dylib                   0x00000001809cfe90 _dispatch_workloop_worker_thread + 404
	30  libsystem_pthread.dylib             0x0000000180b67114 _pthread_wqthread + 288
	31  libsystem_pthread.dylib             0x0000000180b65e30 start_wqthread + 8
)
libc++abi: terminating due to uncaught exception of type NSException
``` 

The crash occurs whenever we try to read from the collection either by single snapshot or by a stream:
```dart
FirebaseFirestore.instance.collection('rooms/$roomId/messages')
  .orderBy('timestamp', descending: true)
  .startAfterDocument(_lastDoc!)
  .limit(20)
  .get()

FirebaseFirestore.instance.collection('rooms/$roomId/messages')
  .orderBy('timestamp', descending: true)
  .limit(20)
  .snapshots()
``` 

I have changed the firebase_core and firestore plugin versions but nothing seems to work on the macOS. It was working previously but suddenly started crashing. I tried clearing the cache, clean code and pod update but it still keeps crashing.

This is the same as this issue here : [https://github.com/firebase/firebase-ios-sdk/issues/5423](url)

**Comment by darshankawar** [comment] 2023-10-24 10:25
Thanks for the report @bat-guy 
I was unable to replicate the error using plugin example running on macOS desktop. Can you provide us a minimal reproducible code sample that throws the error ?


> ```dart
> - Xcode verison: 15.0
> - MacOS version: 14.0
> - iOS simulator version: iPhone 15 pro max 
> - iOS version: 17.0
> ```

Maybe it depends on this config as well, which I don't have currently.

**Comment by bat-guy** [comment] 2023-10-24 14:17
```dart
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(const Sample());
}

class Sample extends StatefulWidget {
  const Sample({super.key});

  @override
  State<Sample> createState() => _SampleState();
}

class _SampleState extends State<Sample> {

  @override
  void initState() {
    super.initState();
    FirebaseFirestore.instance.collection('rooms/$roomId/messages')
      .get();
  }

  @override
  Widget build(BuildContext context) {
    return const Placeholder();
  }
}
```

**Comment by darshankawar** [comment] 2023-10-25 11:27
Thanks for the update. I used above code sample but was unable to replicate or see any crash:

```
FirebaseFirestore.instance.collection('firestore-example-app/baby_driver/rated')
        .get();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Container(
          child: Center(
            child: Text('Test'),
          ),
        ),
      ),
    );
  }
```

Can you also provide specific collection and document that I can try to create at my end and then call it to see if a crash is triggered or not ?

Also, since you are getting `Firestore internal assertion`, can you check https://github.com/firebase/flutterfire/issues/11755#issuecomment-1778941811 and see if it helps in your case ?

**Comment by bat-guy** [comment] 2023-10-25 14:57
Thanks, I will check it. Meanwhile it doesn't matter if the collection null or empty or full, the code always crashes.

**Comment by bat-guy** [comment] 2023-10-25 19:08
Just tested it on a macbook with intel processor with macOS 12.7 and it worked perfectly.

**Comment by darshankawar** [comment] 2023-10-26 10:38
Thanks for the update. 

> intel processor with macOS 12.7

I am on same machine and hence it might not have crash for me. It seems to be OS version specific as I noticed that you are on macOS Sonoma which is latest OS version.
Currently I don't have this config to verify this issue further, but based on the report and crash reported, keeping it open for team's attention and tracking.

/cc @Lyokone

**Comment by bat-guy** [comment] 2023-11-07 14:25
@darshankawar There's an update to this.
I am not sure if this is the exact fix for this but it is working now. I installed the app by creating the dmg and then installing it. I was also working on it side by side and later on might have launched the app directly from VS code in debug mode. I think this was the issue. No matter what I tried it just kept on crashing, both the dmg installed one and the VS code run apps.
Recently, I noticed that my app was showing up in the Activity monitor even though it wasn't in foreground or running. I was running it through the iOS simulator. I force closed the instance and opened the app from applications an it ran fine. I tried to run it via terminal and it was running perfectly. So, I guess it was just a rogue instance running in background that was the cause of the crash. But if it was something else, then I would like to know that too.

**Comment by bat-guy** [comment] 2023-11-07 14:26
Also, when I was checking it on the system with intel processor, it was always a fresh dmg install.

**Comment by russellwheatley** [comment] 2023-12-21 10:36
> @darshankawar There's an update to this. I am not sure if this is the exact fix for this but it is working now. I installed the app by creating the dmg and then installing it. I was also working on it side by side and later on might have launched the app directly from VS code in debug mode. I think this was the issue. No matter what I tried it just kept on crashing, both the dmg installed one and the VS code run apps. Recently, I noticed that my app was showing up in the Activity monitor even though it wasn't in foreground or running. I was running it through the iOS simulator. I force closed the instance and opened the app from applications an it ran fine. I tried to run it via terminal and it was running perfectly. So, I guess it was just a rogue instance running in background that was the cause of the crash. But if it was something else, then I would like to know that too.

Thanks for letting us know that you resolved it. I've also tested on my macOS, M1, Sonoma and I didn't experience this issue. Closing as issue is resolved.

**Closed by russellwheatley** 2023-12-21 10:36 UTC
Labels: type: bug, plugin: cloud_firestore, platform: macos, type: crash
