### ISSUE TITLE
🐛 [firebase_messaging] On iOS, the onMessageOpenedApp stream is not getting any events if getInitialMessage method contains. a message.

### ISSUE THREAD

**Issue by limonadev** [firebase/flutterfire#12004] opened 2023-12-08 16:33 UTC
## Bug report

**Describe the bug**
When the app is completely killed and I open it by pressing a push notification, all the next push notifications while the app is still open (foreground or background) won't get notified in the `onMessageOpenedApp` method. However, the behavior is completely different when the app is opened by pressing the app icon (the regular way of opening an app).

The behavior of the `onMessageOpenedApp` method seems to depend if the app is opened via notification or via app icon.

### Steps to reproduce

1. Clone and run the [example app](https://github.com/firebase/flutterfire/tree/master/packages/firebase_messaging/firebase_messaging/example) of Firebase Messaging in an iOS device.
2. Open the app by pressing the icon only. Send push notifications, press them and observe how they are handled in the `onMessageOpenedApp` (by navigating to the next page).
3. Close and kill the app.
4. Send a push notification and open the app by pressing the notification. Send more push notifications and press them, observe how none of them are handled in the `onMessageOpenedApp` listener.

### Expected behavior

The behavior of `onMessageOpenedApp` method shouldn't depend on how the app is opened, it should be consistent between executions. In this case, the listener should receive the events of new push notifications no matter how the app was opened at the first launch.

### Sample project

Providing a minimal example project which demonstrates the bug in isolation from your main App _greatly_ enhances the chance of a timely fix.

https://github.com/firebase/flutterfire/tree/master/packages/firebase_messaging/firebase_messaging/example

---

## Additional context

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.6, on macOS 14.1.1 23B81 darwin-arm64, locale en-PE)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.85.0)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 3.1.3
Flutter SDK 3.13.6
firebase_messaging_example 0.0.0

dependencies:
- firebase_core 2.24.2 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_messaging 14.7.8 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math web sky_engine]
- flutter_local_notifications 16.2.0 [clock flutter flutter_local_notifications_linux flutter_local_notifications_platform_interface timezone]
- http 0.13.6 [async http_parser meta]

transitive dependencies:
- _flutterfire_internals 1.3.16 [collection firebase_core firebase_core_platform_interface flutter meta]
- args 2.4.2
- async 2.11.0 [collection meta]
- boolean_selector 2.1.1 [source_span string_scanner]
- characters 1.3.0
- clock 1.1.1
- collection 1.17.2
- dbus 0.7.10 [args ffi meta xml]
- fake_async 1.3.1 [clock collection]
- ffi 2.1.0
- firebase_core_platform_interface 5.0.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.10.0 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_messaging_platform_interface 4.5.17 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 3.5.17 [_flutterfire_internals firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]
- flutter_local_notifications_linux 4.0.0+1 [dbus ffi flutter flutter_local_notifications_platform_interface path xdg_directories]
- flutter_local_notifications_platform_interface 7.0.0+1 [flutter plugin_platform_interface]
- flutter_test 0.0.0 [flutter test_api matcher path fake_async clock stack_trace vector_math async boolean_selector characters collection material_color_utilities meta source_span stream_channel string_scanner term_glyph web]
- flutter_web_plugins 0.0.0 [flutter characters collection material_color_utilities meta vector_math web]
- http_parser 4.0.2 [collection source_span string_scanner typed_data]
- js 0.6.7 [meta]
- matcher 0.12.16 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.5.0 [collection]
- meta 1.9.1
- path 1.8.3
- petitparser 5.4.0 [meta]
- plugin_platform_interface 2.1.7 [meta]
- sky_engine 0.0.99
- source_span 1.10.0 [collection path term_glyph]
- stack_trace 1.11.0 [path]
- stream_channel 2.1.1 [async]
- string_scanner 1.2.0 [source_span]
- term_glyph 1.2.1
- test_api 0.6.0 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph]
- timezone 0.9.2 [path]
- typed_data 1.3.2 [collection]
- vector_math 2.1.4
- web 0.1.4-beta
- xdg_directories 1.0.3 [meta path]
- xml 6.3.0 [collection meta petitparser]
```

</details>

---

**Comment by darshankawar** [comment] 2023-12-11 10:48
Thanks for the detailed report @limonadev 
It seems the behavior was described here in the fixed PR : https://github.com/firebase/flutterfire/pull/9315
Can you check the same and see if it helps in your case or not ?

**Comment by limonadev** [comment] 2023-12-11 12:06
@darshankawar I reviewed it but it doesn't seem to fit the issue I described. Also, I'd like to point two things:
- The changes made in the PR were "reverted" (some of them) in a later commit. Especially, the changes about initState and the initial message.
- The issues I described are happening not only in the example but also in a different app that is implementing firebase messaging with Flutter. I mentioned the example app here because it was easier to get a minimal reproducible example with it.

**Comment by limonadev** [comment] 2023-12-12 12:12
I'm indeed killing the app, but the issue is not related to killing it or reopening it. If the app is killed and I open it by pressing a notification, until I kill it again no other notification pressing event will be handled in the `onMessageOpenedApp` listener. However, if I the app is killed and I open it by pressing the app icon, all the next notification pressing events will appear in that method listener. It's that discrepancy between those 2 scenarios what confuses me.

Also, I reviewed the method swizzling and everything seems normal, but the issue persists. Thanks for taking the time @darshankawar!

**Comment by darshankawar** [comment] 2023-12-13 10:16
Thanks for the update and patience while we analyse the case you are reporting @limonadev 

> 2\. Send push notifications, press them and observe how they are handled in the `onMessageOpenedApp` (by navigating to the next page).

Revisiting your original description and taking deeper look into it, can you provide how are you sending the notification ? Is it through nodejs admin SDK that is using a script as mentioned in the plugin example ? or using any third party api ?

See the one being used by the example https://github.com/firebase/flutterfire/blob/91d8aa72f627620245fe15df48f2d68f204e3d10/packages/firebase_messaging/firebase_messaging/example/scripts/send-message.js

**Comment by limonadev** [comment] 2023-12-13 12:02
Right now, as I am testing in a Simulator I'm using an .apns file

**Comment by darshankawar** [comment] 2023-12-14 10:23
Testing on simulator is fine, but we would like you to try and use the node js script from plugin example and re-verify, because We also will not support non-FCM messages from third party packages. We specifically only support messages received from the Firebase APIs since we cannot guarantee that messages received from third party packages will not have any unintended side-effects on other Firebase products such as messaging delivery reporting and Analytics data.

**Comment by limonadev** [comment] 2023-12-15 16:34
@darshankawar I tried with the Simulator and with a real device. The issue only appears in the Simulator.

**Comment by darshankawar** [comment] 2023-12-18 12:07
> The issue only appears in the Simulator.

This probably indicates it may not be a plugin issue because the code isn't separate or different for devices and simulators. Have you already checked if there's any config / setting of the simulator which might be preventing the behavior ?

**Comment by limonadev** [comment] 2023-12-18 12:51
I'm using the same configuration to run both the sim and the device. Also, the app where the problem appeared is only running iOS at this moment. However, I'd be weird if the OS is the one blocking the notifications tapping only based if the app was opened also via notification. At this point, I'm not sure in which part (even if it's not a plugin issue) the code can be making that separation based on how the app was opened and only in the sim.

**Comment by darshankawar** [comment] 2023-12-19 11:06
Thanks for the update. Going back to the original description:



> When the app is completely killed and I open it by pressing a push notification, all the next push notifications while the app is still open (foreground or background) won't get notified in the `onMessageOpenedApp` method. However, the behavior is completely different when the app is opened by pressing the app icon (the regular way of opening an app).
> 
> The behavior of the `onMessageOpenedApp` method seems to depend if the app is opened via notification or via app icon.



> ### Expected behavior
> The behavior of `onMessageOpenedApp` method shouldn't depend on how the app is opened, it should be consistent between executions. In this case, the listener should receive the events of new push notifications no matter how the app was opened at the first launch.

Keeping the issue open for team's input on what should be the expected behavior when the app is opened via notification as compared to when opened after tapping on app icon (assuming the app is terminated).

**Comment by russellwheatley** [comment] 2023-12-19 13:25
> @darshankawar I tried with the Simulator and with a real device. The issue only appears in the Simulator.

If the issue only occurs on the simulator, then this isn't an issue with FlutterFire. Furthermore, I don't recommend developing on a simulator specifically for messaging. Support for messaging on a simulator is a relatively new development but it isn't going to have parity with a real device. Closing out as there is nothing actionable from this issue.

**Closed by russellwheatley** 2023-12-19 13:25 UTC
Labels: type: bug, plugin: messaging, platform: ios
