### ISSUE TITLE
🐛 [firebase_auth] CocoaPods could not find compatible versions for pod "GTMSessionFetcher/Core":

### ISSUE THREAD

**Issue by devsig** [firebase/flutterfire#9805] opened 2022-10-27 17:20 UTC
[!] CocoaPods could not find compatible versions for pod "GTMSessionFetcher/Core":
  In Podfile:
    firebase_auth (from `.symlinks/plugins/firebase_auth/ios`) was resolved to 4.1.0, which depends on
      Firebase/Auth (= 10.0.0) was resolved to 10.0.0, which depends on
        FirebaseAuth (~> 10.0.0) was resolved to 10.0.0, which depends on
          GTMSessionFetcher/Core (~> 2.1)

    mobile_scanner (from `.symlinks/plugins/mobile_scanner/ios`) was resolved to 0.0.1, which depends on
      GoogleMLKit/BarcodeScanning (~> 2.6.0) was resolved to 2.6.0, which depends on
        MLKitBarcodeScanning (~> 1.7.0) was resolved to 1.7.0, which depends on
          MLKitVision (~> 3.0) was resolved to 3.0.0, which depends on
            GTMSessionFetcher/Core (~> 1.1)

**Comment by motucraft** [comment] 2022-10-27 23:35
https://issuetracker.google.com/issues/254418199

**Comment by j-ixcayau** [comment] 2022-10-28 04:07
Same issue here, getting this logs with flutter 3.3.6 and this versions of firebase

```
  firebase_remote_config: 3.0.3
  firebase_auth: 4.1.0
  firebase_core: 2.1.1
  firebase_analytics: 10.0.3
  firebase_dynamic_links: 5.0.3
  cloud_firestore: 4.0.3
  firebase_messaging: 14.0.3
  mlkit_scanner: 0.3.3
```


```
[!] CocoaPods could not find compatible versions for pod "GTMSessionFetcher/Core":
  In Podfile:
    firebase_auth (from `.symlinks/plugins/firebase_auth/ios`) was resolved to 4.1.0, which depends on
      Firebase/Auth (= 10.0.0) was resolved to 10.0.0, which depends on
        FirebaseAuth (~> 10.0.0) was resolved to 10.0.0, which depends on
          GTMSessionFetcher/Core (~> 2.1)

    google_sign_in_ios (from `.symlinks/plugins/google_sign_in_ios/ios`) was resolved to 0.0.1, which depends on
      GoogleSignIn (~> 6.2) was resolved to 6.2.4, which depends on
        GTMAppAuth (~> 1.3) was resolved to 1.3.1, which depends on
          GTMSessionFetcher/Core (< 3.0, >= 1.5)

    google_sign_in_ios (from `.symlinks/plugins/google_sign_in_ios/ios`) was resolved to 0.0.1, which depends on
      GoogleSignIn (~> 6.2) was resolved to 6.2.4, which depends on
        GTMSessionFetcher/Core (< 3.0, >= 1.1)

    mlkit_scanner (from `.symlinks/plugins/mlkit_scanner/ios`) was resolved to 0.1.0, which depends on
      GoogleMLKit/BarcodeScanning was resolved to 0.60.0, which depends on
        GoogleMLKit/MLKitCore (= 0.60.0) was resolved to 0.60.0, which depends on
          MLKitCommon (~> 0.60.0) was resolved to 0.60.0, which depends on
            GTMSessionFetcher/Core (~> 1.1)
```

**Comment by motucraft** [comment] 2022-10-28 05:01
@j-ixcayau 
Isn't it the same? https://github.com/firebase/flutterfire/issues/9792 https://github.com/firebase/flutterfire/issues/9796

After all, this is the issue, right?
https://issuetracker.google.com/issues/254418199

**Comment by danagbemava-nc** [comment] 2022-10-28 08:18
Hi @devsig, this issue is out of the scope of this repo since the conflict is caused by `GoogleMLKit` using an older version of `GTMSessionFetcher/Core`. 

As pointed out above, this has been reported to the Google issue tracker in https://github.com/firebase/flutterfire/issues/9805#issuecomment-1294460078. 

Closing from here as this is out of scope. 

Thank you

**Closed by danagbemava-nc** 2022-10-28 08:18 UTC
Labels: type: bug, Needs Attention, in triage

**Comment by MagnusJohansson** [comment] 2022-10-30 10:24
The Google team has assigned the MLKit bug ticket https://issuetracker.google.com/issues/254418199 with a Priority level of P4.
P4 is the lowest priority they are working with, [described as](https://developers.google.com/issue-tracker/concepts/issues#priority):


> P4 | An issue that should be addressed eventually. Such an issue is not relevant to core organizational functions or the work of other teams, or else it relates only to the attractiveness or pleasantness of the system.

All of you who are experiencing this Google bug, could you please browse to the https://issuetracker.google.com/issues/254418199  issue, and click on the "+1" blue button on the top right to make Google aware that it is affecting people.
Thanks.

**Comment by anthonyhunter** [comment] 2022-11-11 00:43
See https://issuetracker.google.com/issues/254418199#comment48 for workaround
