### ISSUE TITLE
🐛 [firebase_auth] Cannot run version 4.7.0 on iOS

### ISSUE THREAD

**Issue by Rexios80** [firebase/flutterfire#11285] opened 2023-07-14 14:21 UTC
## Bug report

**Describe the bug**
```console
Launching lib/main.dart on iPhone 14 Pro in debug mode...
main.dart:1
Xcode build done.                                           27.7s
Failed to build iOS app
Lexical or Preprocessor Issue (Xcode): 'messages.g.h' file not found
/Users/rexios/.pub-cache/hosted/pub.dev/firebase_auth-4.7.0/ios/Classes/messages.g.m:3:8

Could not build the application for the simulator.
Error launching application on iPhone 14 Pro.
Exited
```

### Steps to reproduce

1. Try to run an app on iOS using version 4.7.0

### Expected behavior

That file isn't missing

**Comment by Rexios80** [comment] 2023-07-14 14:30
I tried regenerating with pigeon and that file doesn't show up. So either it's an issue with pigeon or an issue with your pigeon config.

**Comment by Rexios80** [comment] 2023-07-14 14:31
Also can you guys like actually use semantic versioning please? I haven't updated the firebase dependencies in this project in a long time and it's pretty much impossible to go back to the last version of the auth plugin because it's incompatible with other firebase plugins, but the versions don't describe that behavior properly.

**Comment by Rexios80** [comment] 2023-07-14 14:32
Although maybe that's hard to do with so many cyclical dependencies. Idk there has to be a better way.

**Comment by mikenigels** [comment] 2023-07-15 23:18
Began seeing this issue today after recently upgrading [firebase_auth] to 4.7.0 and adding the [file_selector] package.

Seems to be related to this previous issue:
https://github.com/firebase/flutterfire/issues/9511#issuecomment-1248926811

For my case I can confirm that removing the [file_selector] package clears the issue.

**Comment by Tom3652** [comment] 2023-07-17 09:49
@mikenigels same for me i had to remove `file_selector` to be able to build, but i need this package so i am looking forward a fix on `firebase_auth` :/

Note : it builds correctly on MacOS, but not on iOS

**Comment by darshankawar** [comment] 2023-07-17 11:13
Thanks for the reports. I do see the same error as reported using latest version of the plugin.
Could this be related ? https://github.com/flutter/packages/pull/4461

/cc @Lyokone

**Comment by efraespada** [comment] 2023-07-24 19:45
I could manually fix it by replacing:

```
#import "messages.g.h"
```

by 

```
#import <firebase_auth/messages.g.h>
```

in some files in the library:

![Screenshot 2023-07-24 at 01 37 16](https://github.com/firebase/flutterfire/assets/1783618/13ba8dcb-a847-4bb6-9f11-a4ed586377e0)

Could you please fix it for the next version? 😄

**Comment by russellwheatley** [comment] 2023-07-25 10:57
The fix has been merged and will be out in the next release.

**Closed by russellwheatley** 2023-07-25 10:57 UTC
Labels: type: bug, plugin: auth, platform: ios
