### ISSUE TITLE
🐛 [cloud_firestore] New Crash Ios 12 Device

### ISSUE THREAD

**Issue by cnkygmr** [firebase/flutterfire#11553] opened 2023-09-05 08:03 UTC
## Bug report

**Describe the bug**
```
Crashed: com.google.firebase.firestore
0  grpcpp                         0x8790 grpc_core::ExecCtx::ExecCtx() + 112
1  grpcpp                         0x2fcdc grpc::SecureChannelCredentials::~SecureChannelCredentials() + 28
2  grpcpp                         0x2fee0 std::__1::__shared_ptr_pointer<grpc::SecureChannelCredentials*, std::__1::shared_ptr<grpc::ChannelCredentials>::__shared_ptr_default_delete<grpc::ChannelCredentials, grpc::SecureChannelCredentials>, std::__1::allocator<grpc::SecureChannelCredentials> >::__on_zero_shared() + 20
3  FirebaseFirestore              0x93994 firebase::firestore::remote::GrpcConnection::CreateChannel() const + 424
4  FirebaseFirestore              0x936c4 firebase::firestore::remote::GrpcConnection::EnsureActiveStub() + 124
5  FirebaseFirestore              0x93eb4 firebase::firestore::remote::GrpcConnection::CreateStream(absl::lts_20220623::string_view, firebase::firestore::credentials::AuthToken const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, firebase::firestore::remote::GrpcStreamObserver*) + 60
6  FirebaseFirestore              0x142114 firebase::firestore::remote::Stream::ResumeStartWithCredentials(firebase::firestore::util::StatusOr<firebase::firestore::credentials::AuthToken> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) + 132
7  FirebaseFirestore              0x143644 std::__1::__function::__func<firebase::firestore::remote::Stream::RequestCredentials()::$_0::operator()(absl::lts_20220623::optional<firebase::firestore::util::StatusOr<firebase::firestore::credentials::AuthToken> > const&, absl::lts_20220623::optional<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > const&) const::'lambda'(), std::__1::allocator<firebase::firestore::remote::Stream::RequestCredentials()::$_0::operator()(absl::lts_20220623::optional<firebase::firestore::util::StatusOr<firebase::firestore::credentials::AuthToken> > const&, absl::lts_20220623::optional<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > const&) const::'lambda'()>, void ()>::operator()() + 72
8  FirebaseFirestore              0x8ed0 firebase::firestore::util::AsyncQueue::ExecuteBlocking(std::__1::function<void ()> const&) + 68
9  FirebaseFirestore              0x154e74 firebase::firestore::util::Task::ExecuteAndRelease() + 184
10 libdispatch.dylib              0x607d4 _dispatch_client_callout + 16
11 libdispatch.dylib              0x9324 _dispatch_lane_serial_drain$VARIANT$mp + 592
12 libdispatch.dylib              0x9e40 _dispatch_lane_invoke$VARIANT$mp + 428
13 libdispatch.dylib              0x124ac _dispatch_workloop_worker_thread + 596
14 libsystem_pthread.dylib        0xc114 _pthread_wqthread + 304
15 libsystem_pthread.dylib        0xecd4 start_wqthread + 4
```

### Steps to reproduce

Currently only occurs in iOS 12 version

### Sample project

Providing a minimal example project which demonstrates the bug in isolation from your main App _greatly_ enhances the chance of a timely fix.
Please link to the public repository URL.

---

## Additional context

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

**Comment by danagbemava-nc** [comment] 2023-09-05 10:44
Closing this as a duplicate of https://github.com/firebase/flutterfire/issues/11216

**Closed by danagbemava-nc** 2023-09-05 10:44 UTC
Labels: type: bug, Needs Attention, in triage
