### ISSUE TITLE
🐛 [FIREBASE_MESSAGING] Firebase messaging and local notification combined code not working properly in release mode.

### ISSUE THREAD

**Issue by daphneyong11** [firebase/flutterfire#11340] opened 2023-07-21 06:57 UTC
Hi, I am trying to use local notification and firebase messaging for prompt notification in android app.
However, I noticed an error come out in the terminal record (Still can show notification on foreground, background and terminated on Android.)
In debug mode, the notification is running great, but in release mode, the custom sound is not played and when in foreground, the icon data is missing too. I am not sure is this error causing the problem, or my coding is wrong.
This is the error code shown:

```
E/flutter ( 9896): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
E/flutter ( 9896): #0 MethodChannelFirebaseMessaging.registerBackgroundMessageHandler (package:firebase_messaging_platform_interface/src/method_channel/method_channel_messaging.dart:181:53)
E/flutter ( 9896): https://github.com/firebase/flutterfire/pull/1 FirebaseMessagingPlatform.onBackgroundMessage= (package:firebase_messaging_platform_interface/src/platform_interface/platform_interface_messaging.dart:102:16)
E/flutter ( 9896): https://github.com/firebase/flutterfire/pull/2 FirebaseMessaging.onBackgroundMessage (package:firebase_messaging/src/messaging.dart:73:31)
E/flutter ( 9896): https://github.com/firebase/flutterfire/pull/3 FirebaseApi.initNotifications (package:linxpetmobile/api/firebase_api.dart:33:23)
E/flutter ( 9896):
E/flutter ( 9896): https://github.com/firebase/flutterfire/pull/4 main (package:linxpetmobile/main.dart:19:3)
E/flutter ( 9896):
E/flutter ( 9896):
```

Below is the main dart code that trigger the firebase_api.dart code:

```dart
void main() async {
WidgetsFlutterBinding.ensureInitialized();
await Firebase.initializeApp();
await FirebaseApi().initNotifications();
runApp(MyWebView());
}
```

And below is the firebase_api.dart code

```dart
import 'dart:convert';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:flutter_local_notifications/flutter_local_notifications.dart';

class FirebaseApi {
final _firebaseMessaging = FirebaseMessaging.instance;
final FlutterLocalNotificationsPlugin _localNotifications = FlutterLocalNotificationsPlugin();

FirebaseApi() {
// Initialize the FlutterLocalNotificationsPlugin
_initializeLocalNotifications();

_firebaseMessaging.setForegroundNotificationPresentationOptions(
  alert: true,
  badge: true,
  sound: true,
);
}

// Initialize FlutterLocalNotificationsPlugin
void _initializeLocalNotifications() {
const AndroidInitializationSettings initializationSettingsAndroid = AndroidInitializationSettings('launcher_icon');
final InitializationSettings initializationSettings = InitializationSettings(android: initializationSettingsAndroid);
_localNotifications.initialize(initializationSettings);
}

Future initNotifications() async {
await _firebaseMessaging.requestPermission();

final fCMToken = await _firebaseMessaging.getToken();
print('Token: $fCMToken');

FirebaseMessaging.onBackgroundMessage(handleFirebaseMessage);
FirebaseMessaging.onMessage.listen(handleFirebaseMessage);
}

Future handleFirebaseMessage(RemoteMessage message) async {
var notification = message.notification;
if (notification == null) return;

// Initialize AndroidNotificationDetails for the notification channel
final AndroidNotificationDetails androidChannel = AndroidNotificationDetails(
  'high_importance_channel',
  'High Importance Notifications',
  channelDescription: 'This channel is used for important notifications.',
  importance: Importance.max,
  priority: Priority.high,
  sound: RawResourceAndroidNotificationSound('cat'),
  playSound: true,
);

// Create the notification details
final notificationDetails = NotificationDetails(android: androidChannel);

// Show the local notification
await _localNotifications.show(
  notification.hashCode,
  notification.title,
  notification.body,
  notificationDetails,
  payload: jsonEncode(message.toMap()),
);
}
}
```

**Comment by danagbemava-nc** [comment] 2023-07-21 10:17
Hi @daphneyong11, what version of flutter are you using? 

Please also provide the output of `flutter pub deps -- --style=compact` so that we may know the versions of the flutterfire plugins you're using

Thank you

**Comment by daphneyong11** [comment] 2023-07-24 00:11
Hi @danagbemava-nc ,

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.10.6, on Microsoft Windows [Version 10.0.19045.3208], locale en-MY)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.5.3)
[√] Android Studio (version 2022.1)
[√] VS Code (version 1.80.1)
[√] Connected device (3 available)
[√] Network resources

Output of flutter pub deps
Dart SDK 3.0.6
Flutter SDK 3.10.6
linxpetmobile 1.0.0+7

dependencies:
- cupertino_icons 1.0.5
- firebase_core 2.15.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_messaging 14.6.5 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- flutter 0.0.0 [characters collection js material_color_utilities meta vector_math sky_engine]
- flutter_launcher_icons 0.13.1 [args checked_yaml cli_util image json_annotation path yaml]
- flutter_local_notifications 15.1.0+1 [clock flutter flutter_local_notifications_linux flutter_local_notifications_platform_interface timezone]
- flutter_native_splash 2.3.1 [args flutter flutter_web_plugins js html image meta path universal_io xml yaml]
- image_picker 1.0.1 [flutter image_picker_android image_picker_for_web image_picker_ios image_picker_linux image_picker_macos image_picker_platform_interface image_picker_windows]
- jitsi_meet_wrapper 0.2.0+1 [flutter jitsi_meet_wrapper_platform_interface]
- local_auth 2.1.6 [flutter local_auth_android local_auth_ios local_auth_platform_interface local_auth_windows]
- url_launcher 6.1.12 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- webview_flutter 4.2.2 [flutter webview_flutter_android webview_flutter_platform_interface webview_flutter_wkwebview]

dev dependencies:
- flutter_lints 2.0.2 [lints]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters collection js matcher material_color_utilities meta source_span stream_ch
annel string_scanner term_glyph]

transitive dependencies:
- _flutterfire_internals 1.3.4 [collection firebase_core firebase_core_platform_interface flutter meta]
- archive 3.3.7 [crypto path pointycastle]
- args 2.4.2
- async 2.11.0 [collection meta]
- boolean_selector 2.1.1 [source_span string_scanner]
- characters 1.3.0
- checked_yaml 2.0.3 [json_annotation source_span yaml]
- cli_util 0.4.0 [meta path]
- clock 1.1.1
- collection 1.17.1
- convert 3.1.1 [typed_data]
- cross_file 0.3.3+4 [js meta]
- crypto 3.0.3 [typed_data]
- csslib 1.0.0 [source_span]
- dbus 0.7.8 [args ffi meta xml]
- fake_async 1.3.1 [clock collection]
- ffi 2.0.2
- file_selector_linux 0.9.2 [cross_file file_selector_platform_interface flutter]
- file_selector_macos 0.9.3+1 [cross_file file_selector_platform_interface flutter]
- file_selector_platform_interface 2.6.0 [cross_file flutter http plugin_platform_interface]
- file_selector_windows 0.9.3 [cross_file file_selector_platform_interface flutter]
- firebase_core_platform_interface 4.8.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.6.0 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_messaging_platform_interface 4.5.4 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 3.5.4 [_flutterfire_internals firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]
- flutter_local_notifications_linux 4.0.0+1 [dbus ffi flutter flutter_local_notifications_platform_interface path xdg_directories]
- flutter_local_notifications_platform_interface 7.0.0+1 [flutter plugin_platform_interface]
- flutter_plugin_android_lifecycle 2.0.15 [flutter]
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta vector_math]
- html 0.15.4 [csslib source_span]
- http 1.1.0 [async http_parser meta]
- http_parser 4.0.2 [collection source_span string_scanner typed_data]
- image 4.0.17 [archive meta xml]
- image_picker_android 0.8.7+4 [flutter flutter_plugin_android_lifecycle image_picker_platform_interface]
- image_picker_for_web 2.2.0 [flutter flutter_web_plugins image_picker_platform_interface mime]
- image_picker_ios 0.8.8 [flutter image_picker_platform_interface]
- image_picker_linux 0.2.1 [file_selector_linux file_selector_platform_interface flutter image_picker_platform_interface]
- image_picker_macos 0.2.1 [file_selector_macos file_selector_platform_interface flutter image_picker_platform_interface]
- image_picker_platform_interface 2.9.0 [cross_file flutter http plugin_platform_interface]
- image_picker_windows 0.2.1 [file_selector_platform_interface file_selector_windows flutter image_picker_platform_interface]
- intl 0.18.1 [clock meta path]
- jitsi_meet_wrapper_platform_interface 0.1.0 [collection flutter plugin_platform_interface]
- js 0.6.7 [meta]
- json_annotation 4.8.1 [meta]
- lints 2.1.1
- local_auth_android 1.0.32 [flutter flutter_plugin_android_lifecycle intl local_auth_platform_interface]
- local_auth_ios 1.1.3 [flutter intl local_auth_platform_interface]
- local_auth_platform_interface 1.0.7 [flutter plugin_platform_interface]
- local_auth_windows 1.0.9 [flutter local_auth_platform_interface]
- matcher 0.12.15 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.2.0
- meta 1.9.1
- mime 1.0.4
- path 1.8.3
- petitparser 5.4.0 [meta]
- plugin_platform_interface 2.1.4 [meta]
- pointycastle 3.7.3 [collection convert js]
- sky_engine 0.0.99
- source_span 1.9.1 [collection path term_glyph]
- stack_trace 1.11.0 [path]
- stream_channel 2.1.1 [async]
- string_scanner 1.2.0 [source_span]
- term_glyph 1.2.1
- test_api 0.5.1 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- timezone 0.9.2 [path]
- typed_data 1.3.2 [collection]
- universal_io 2.2.2 [collection meta typed_data]
- url_launcher_android 6.0.36 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.1.4 [flutter url_launcher_platform_interface]
- url_launcher_linux 3.0.5 [flutter url_launcher_platform_interface]
- url_launcher_macos 3.0.6 [flutter url_launcher_platform_interface]
- url_launcher_platform_interface 2.1.3 [flutter plugin_platform_interface]
- url_launcher_web 2.0.18 [flutter flutter_web_plugins url_launcher_platform_interface]
- url_launcher_windows 3.0.7 [flutter url_launcher_platform_interface]
- vector_math 2.1.4
- webview_flutter_android 3.9.1 [flutter webview_flutter_platform_interface]
- webview_flutter_platform_interface 2.4.0 [flutter meta plugin_platform_interface]
- webview_flutter_wkwebview 3.7.0 [flutter path webview_flutter_platform_interface]
- xdg_directories 1.0.1 [meta path]
- xml 6.3.0 [collection meta petitparser]
- yaml 3.1.2 [collection source_span string_scanner]

**Comment by danagbemava-nc** [comment] 2023-07-24 11:19
Hi @daphneyong11, your backgroundMessengerHandler method needs to be annotated with `@pragma('vm:entry-point')`. See the plugin example code for reference https://github.com/firebase/flutterfire/blob/199e1fc43654b913ddb8257c4e3a3ceddcbb97d1/packages/firebase_messaging/firebase_messaging/example/lib/main.dart#L46

Please read the instructions in the example as well.

**Comment by daphneyong11** [comment] 2023-07-26 02:37
Hi @danagbemava-nc , I had added the @pragma('vm:entry-point') but nothing change. Still the same problem.

**Comment by danagbemava-nc** [comment] 2023-07-26 08:21
Hi @daphneyong11, please provide a complete minimal reproducible code sample in a repo we can clone so that we can properly investigate this issue. 

Thank you

**Comment by daphneyong11** [comment] 2023-07-27 02:54
Hi @danagbemava-nc I had produce a code sample. 
https://github.com/daphneyong11/notification

**Comment by daphneyong11** [comment] 2023-07-28 04:00
Hi @danagbemava-nc the error is finally removed! Thanks
But for the main problem of no custom sound in release mode and icon in foreground still maintain. 
I had update the code in the previous link.
https://github.com/daphneyong11/notification

**Comment by danagbemava-nc** [comment] 2023-07-28 09:59
Kindly read https://pub.dev/packages/flutter_local_notifications#custom-notification-icons-and-sounds of the local_notifications plugin. If you still face this issue after updating your app for release mode, kindly file an issue on their repo. 

The issue with the sound is related to the flutter_local_notifications plugin not firebase_messaging. 

Closing from here since the messaging issue has been resolved.

**Closed by danagbemava-nc** 2023-07-28 09:59 UTC
Labels: type: bug, Needs Attention, in triage
