### ISSUE TITLE
🐛 [firebase_messaging] requestPermission causing an issue

### ISSUE THREAD

**Issue by SamerOrfali** [firebase/flutterfire#9955] opened 2022-11-17 12:13 UTC
## Bug report

**Describe the bug**
when calling await FirebaseMessaging.instance.requestPermission();
I get error [firebase_messaging/unknown] Attempt to invoke virtual method 'java.lang.Object android.content.Context.getSystemService(java.lang.String)' on a null object reference

## Additional context

flutter version 3.3.8
firebase_messaging version ^14.1.0
firebase_core version  ^2.2.0
targetSdkVersion 33
device android version : Android 10

----------------------------
<img width="1191" alt="image" src="https://user-images.githubusercontent.com/34859770/202443250-4f65d3f4-44eb-4a9f-a092-ad142052abb3.png">

**Comment by darshankawar** [comment] 2022-11-17 13:05
Closing as duplicate of https://github.com/firebase/flutterfire/issues/9904

**Closed by darshankawar** 2022-11-17 13:05 UTC
Labels: type: bug, Needs Attention, in triage
