### ISSUE TITLE
🐛 [cloud_firestore] Text brightness/thickness changes when orderBy used

### ISSUE THREAD

**Issue by schnausages** [firebase/flutterfire#10872] opened 2023-04-29 18:11 UTC
## Bug report

When reading from Firestore and using orderBy, the text appearance changes while scrolling a ListView (only when Impeller is enabled -- does NOT happen with Skia) -- this also doesnt happen when using a constant string in the rendered ListView widget

VIDEO: https://imgur.com/a/1KX6xXe

*doesnt happen when orderBy isnt used (wasnt sure if this would be an Impeller or FlutterFire concern

*bug report also submitted to https://github.com/flutter/flutter/issues/125449 

### Steps to reproduce

1. Enable Impeller, fetch docs from Firestore and use orderBy
2. Scroll a ListView that renders a text field from the FS document

### Expected behavior

Expect to not see any change in appearance

### Sample project
```
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:cloud_firestore/cloud_firestore.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(context) {
    return MaterialApp(
      title: 'bug_test',
      debugShowCheckedModeBanner: false,
      home: TestExploreScreen(),
    );
  }
}

class TestExploreScreen extends StatefulWidget {
  @override
  _TestExploreScreenState createState() => _TestExploreScreenState();
}

class _TestExploreScreenState extends State<TestExploreScreen> {
  late Future exploreFuture;

//fetch list of docs from Firestore
  Future<List<DocumentSnapshot>> getExploreDocs() async {
    var _fs = FirebaseFirestore.instance.collection(
        'user_posts'); //name of posts collection or wherever user posts/comments are stored
    var _docs = await _fs
        .limit(10)
        .orderBy('date_added') // bug occurs when orderBy is used
        .get(GetOptions(source: Source.server));
    return _docs.docs;
  }

  @override
  void initState() {
    super.initState();
    exploreFuture = getExploreDocs();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        resizeToAvoidBottomInset: false,
        backgroundColor: Colors.black,
        body: SafeArea(
          child: Padding(
            padding:
                EdgeInsets.only(top: MediaQuery.of(context).size.height * .075),
            child: FutureBuilder(
              future: exploreFuture,
              builder: (context, AsyncSnapshot snapshot) {
                if (snapshot.connectionState == ConnectionState.done &&
                    !snapshot.hasError) {
                  return ListView.builder(
                    scrollDirection: Axis.vertical,
                    physics: const AlwaysScrollableScrollPhysics(
                        parent: BouncingScrollPhysics()),
                    itemCount: snapshot.data.length,
                    itemBuilder: (context, i) {
                      //provides widget with the message/text of post made by a user -- "snip_text" is name of my Firestore text field for posts
                      return TestBugTestPost(
                        postText: snapshot.data[i]['snip_text'],
                      );
                    },
                  );
                } else if (snapshot.connectionState ==
                    ConnectionState.waiting) {
                  return Container(
                    color: Colors.black,
                    child: Center(
                      child: CircularProgressIndicator(
                        backgroundColor: Colors.white,
                      ),
                    ),
                  );
                } else {
                  return Center(
                      child: Column(
                    mainAxisAlignment: MainAxisAlignment.center,
                    children: [
                      Text(
                        'No posts available...',
                        style: TextStyle(
                          color: Colors.white,
                          fontSize: 16,
                        ),
                      ),
                      SizedBox(
                        height: MediaQuery.of(context).size.height * .08,
                      ),
                      Icon(
                        Icons.feed_rounded,
                        color: Colors.white,
                        size: 34,
                      ),
                    ],
                  ));
                }
              },
            ),
          ),
        ));
  }
}

class TestBugTestPost extends StatefulWidget {
  final String postText;

  TestBugTestPost({Key? key, required this.postText}) : super(key: key);

  @override
  State<TestBugTestPost> createState() => _TestBugTestPostState();
}

class _TestBugTestPostState extends State<TestBugTestPost> {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: double.infinity,
      padding: const EdgeInsets.all(10),
      decoration: BoxDecoration(
          border: Border.symmetric(
              horizontal: BorderSide(color: Colors.white10, width: 1))),
      child: Column(
        mainAxisSize: MainAxisSize.min,
        children: [
          Text(
            'USERNAME_HERE123',
            style: TextStyle(color: Colors.white),
          ),
          Container(
            width: MediaQuery.of(context).size.width * .8,
            child: Text(
              //when the string is constant (Lorem Ipsum string), the text bug does NOT show up... only when using widget.postText
              // "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book",
              widget.postText,
              style: TextStyle(
                color: Colors.white,
                fontSize: 16,
              ),
            ),
          ),
        ],
      ),
    );
  }
}

```

---

## Additional context

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 3.7.12, on macOS 13.1 22C65 darwin-x64, locale en-US)
    • Flutter version 3.7.12 on channel stable at /Users/normalsoftware/Downloads/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4d9e56e694 (12 days ago), 2023-04-17 21:47:46 -0400
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.12.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] VS Code (version 1.71.2)
    • VS Code at /Users/normalsoftware/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.60.0

[✓] Connected device (3 available)
    • normal’s iPhone (mobile) • 00008030-001120290E2B402E • ios            • iOS 16.3.1 20D67
    • macOS (desktop)          • macos                     • darwin-x64     • macOS 13.1 22C65 darwin-x64
    • Chrome (web)             • chrome                    • web-javascript • Google Chrome 112.0.5615.137

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

 cloud_firestore: ^3.1.6
 firebase_core: ^1.0.0

---

**Comment by danagbemava-nc** [comment] 2023-05-02 13:58
Hi @schnausages, I believe this should be tracked on the flutter repo. The plugin doesn't do anything related to rendering so it's likely to be the cause of the issue. Considering this happens only when using impeller, the flutter repo is the best place for this issue. 

Closing from here. 

Thank you

**Closed by danagbemava-nc** 2023-05-02 13:58 UTC
Labels: type: bug, Needs Attention, in triage
