### ISSUE TITLE
🐛 [firebase_auth] 'PigeonParser.h' file not found in iOS

### ISSUE THREAD

**Issue by marc7garcia** [firebase/flutterfire#11720] opened 2023-10-17 17:07 UTC
## Bug report

**Describe the bug**
Error 'PigeonParser.h' file not found when compiling firebase_auth 4.11.0 on iOS.
It works on Android.

### Steps to reproduce

1. Compile any Flutter project for iOS and you get the error.

### Expected behavior

Compile and execute the app successful.

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

octor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel unknown, 3.7.12, on macOS 13.6 22G120 darwin-arm64, locale es-ES)
    ! Flutter version 3.7.12 on channel unknown at /Users/marc/Library/Developer/flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at https://flutter.dev/docs/get-started/install.
    ! Unknown upstream repository.
      Reinstall Flutter by following instructions at https://flutter.dev/docs/get-started/install.
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] IntelliJ IDEA Community Edition (version 2023.2.3)
[✓] VS Code (version 1.81.1)
[✓] Connected device (4 available)
[✓] HTTP Host Availability

**Comment by muloca** [comment] 2023-10-17 17:20
Same here!

**Comment by suysoftware** [comment] 2023-10-17 17:27
same !

**Comment by Kinomad** [comment] 2023-10-17 17:28
Just tried with new updates of firebase on iOS (published on hour ago) and I have also the same issue (but it works on Android).

firebase_core: ^2.18.0
firebase_auth: ^4.11.0
cloud_firestore: ^4.10.0
firebase_storage: ^11.3.0

```
Could not build the precompiled application for the device.
Lexical or Preprocessor Issue (Xcode): 'PigeonParser.h' file not found
/.pub-cache/hosted/pub.dev/firebase_auth-4.11.0/ios/Classes/PigeonParser.m:4:8
I tried also 'flutter pub cache clean' and a 'pod install --repo-update' (all was updated well, but still this PigeonParser error)

```

**Flutter doctor**

[✓] Flutter (Channel stable, 3.13.7, on macOS 13.6 22G120 darwin-x64, locale
    fr-FR)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.83.1)
[✓] Connected device (3 available)
[✓] Network resources

**Comment by muloca** [comment] 2023-10-17 18:35
> Just tried with new updates of firebase on iOS (published on hour ago) and I have also the same issue (but it works on Android).
> 
> firebase_core: ^2.18.0 firebase_auth: ^4.11.0 cloud_firestore: ^4.10.0 firebase_storage: ^11.3.0
> 
> ```
> Could not build the precompiled application for the device.
> Lexical or Preprocessor Issue (Xcode): 'PigeonParser.h' file not found
> /.pub-cache/hosted/pub.dev/firebase_auth-4.11.0/ios/Classes/PigeonParser.m:4:8
> I tried also 'flutter pub cache clean' and a 'pod install --repo-update' (all was updated well, but still this PigeonParser error)
> ```
> 
> **Flutter doctor**
> 
> [✓] Flutter (Channel stable, 3.13.7, on macOS 13.6 22G120 darwin-x64, locale fr-FR) [✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2) [✓] Xcode - develop for iOS and macOS (Xcode 15.0) [✓] Chrome - develop for the web [✓] Android Studio (version 2022.2) [✓] VS Code (version 1.83.1) [✓] Connected device (3 available) [✓] Network resources

Yes, here I have the same thing, on Android works ok but in iOS don't work.

**Comment by johnebere58** [comment] 2023-10-18 01:41
For now use this in your pub yaml

  cloud_firestore: 4.9.2
  firebase_core: 2.16.0
  firebase_storage: 11.2.7
  firebase_auth: 4.10.0
  firebase_messaging: 14.6.8
  firebase_analytics: 10.5.0

**Comment by Heidelbergg** [comment] 2023-10-18 02:15
Same issue here!

**Comment by frapeti** [comment] 2023-10-18 03:53
same here

**Comment by infomus** [comment] 2023-10-18 03:55
> For now use this in your pub yaml
> 
> cloud_firestore: 4.9.2 firebase_core: 2.16.0 firebase_storage: 11.2.7 firebase_auth: 4.10.0 firebase_messaging: 14.6.8 firebase_analytics: 10.5.0

This temporary fix worked for me

**Comment by gadgelogger** [comment] 2023-10-18 05:21
pubspec.yamlをこうしたらいけた
  cupertino_icons: ^1.0.2
  firebase_core: ^2.16.0
  firebase_auth: 4.10.1
  google_sign_in: ^6.1.5
  cloud_firestore: ^4.9.2

**Comment by Kinomad** [comment] 2023-10-18 07:26
For me, to back in my previous configuration in .yaml or try what is suggested in the feed doesn't work. I still have the same message on 'pigeonParser.h'

I tried with this version what was suggested by @johnebere58 and seem worked for @infomus 
cloud_firestore: 4.9.2
firebase_core: 2.16.0
firebase_storage: 11.2.7
firebase_auth: 4.10.0

But, even after pod install and update, it doesn't work for me. I also try a pub update one by one for each firebase package. I also tried to clean up all cache (flutter pub cache clean, flutter clean, flutter pub get, flutter pub update)

I don't know why my environnement doesn't want to come back in my previous configuration before to update new firebase package or to change other version of the .yaml. 

What can I do ?

**Comment by niypoo** [comment] 2023-10-18 07:27
I'm facing same issue here 

```
Failed to build iOS app
Lexical or Preprocessor Issue (Xcode): 'PigeonParser.h' file not found
/Users/myuser/.pub-cache/hosted/pub.dev/firebase_auth-4.11.0/ios/Classes/PigeonParser.m:4:8
PigeonParser.m:4
```

`Flutter --version`

```
Flutter 3.13.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 12fccda598 (4 weeks ago) • 2023-09-19 13:56:11 -0700
Engine • revision bd986c5ed2
Tools • Dart 3.1.2 • DevTools 2.25.0
```

**Comment by johnebere58** [comment] 2023-10-18 07:39
> For me, to back in my previous configuration in .yaml or try what is suggested in the feed doesn't work. I still have the same message on 'pigeonParser.h'
> 
> I tried with this version what was suggested by @johnebere58 and seem worked for @infomus cloud_firestore: 4.9.2 firebase_core: 2.16.0 firebase_storage: 11.2.7 firebase_auth: 4.10.0
> 
> But, even after pod install and update, it doesn't work for me. I also try a pub update one by one for each firebase package. I also tried to clean up all cache (flutter pub cache clean, flutter clean, flutter pub get, flutter pub update)
> 
> I don't know why my environnement doesn't want to come back in my previous configuration before to update new firebase package or to change other version of the .yaml.
> 
> What can I do ?

Quick one.

Did you also delete your Podfile.lock?
Please ensure you remove the "^" symbol from the plugins

for instance; use "firebase_core: 2.16.0" instead of "firebase_core: ^2.16.0"

**Comment by niypoo** [comment] 2023-10-18 07:43
> For now use this in your pub yaml
> 
> cloud_firestore: 4.9.2 firebase_core: 2.16.0 firebase_storage: 11.2.7 firebase_auth: 4.10.0 firebase_messaging: 14.6.8 firebase_analytics: 10.5.0

 temporally, that solution is  working.

**Comment by gadgelogger** [comment] 2023-10-18 07:49
How to solve it
Is it good to erase this folder and see it?
(I tried it for the time being, but there was no particular problem)
/Users/myuser/.pub-cache/hosted/pub.dev/firebase_auth-4.11.0/ios/classes/pigeonParser.

**Comment by messinis** [comment] 2023-10-18 08:03
same here

**Comment by Kinomad** [comment] 2023-10-18 08:52
> > For me, to back in my previous configuration in .yaml or try what is suggested in the feed doesn't work. I still have the same message on 'pigeonParser.h'
> > I tried with this version what was suggested by @johnebere58 and seem worked for @infomus cloud_firestore: 4.9.2 firebase_core: 2.16.0 firebase_storage: 11.2.7 firebase_auth: 4.10.0
> > But, even after pod install and update, it doesn't work for me. I also try a pub update one by one for each firebase package. I also tried to clean up all cache (flutter pub cache clean, flutter clean, flutter pub get, flutter pub update)
> > I don't know why my environnement doesn't want to come back in my previous configuration before to update new firebase package or to change other version of the .yaml.
> > What can I do ?
> 
> Quick one.
> 
> Did you also delete your Podfile.lock? Please ensure you remove the "^" symbol from the plugins
> 
> for instance; use "firebase_core: 2.16.0" instead of "firebase_core: ^2.16.0"

Thanks a lot @johnebere58, it worked after to delete podfile.lock and remove the symbol "^" fro the plugins, I'm now be able to build in iOS

**Comment by freshtechtips** [comment] 2023-10-18 09:16
Same here

**Comment by darshankawar** [comment] 2023-10-18 10:29
Thanks for all the reports.  I tried with plugin example by upgrading `firebase_auth` and `firebase_core` to latest versions and ran on iOS simulator which seemed to compile and run the app properly without the reported error in the console logs:

<img width="357" alt="Screenshot 2023-10-18 at 3 58 25 PM" src="https://github.com/firebase/flutterfire/assets/67046386/5f1ebeff-29b1-411e-9ee4-fbd7dab628ea">

But based on the report and number of upvotes and comments, it seemed to be occuring due to breaking changes to auth plugin in underlying SDK.

Labeling for team's attention and tracking.

**Comment by putnokiabel** [comment] 2023-10-18 11:58
@darshankawar
It looks like you're running on an iOS 15.2 simulator which isn't included in Xcode 15 (which runs iOS 17 simulators).
Since this is an Xcode-only build issue, I can imagine that the bug only occurs on Xcode 15.

**Comment by albaschez** [comment] 2023-10-18 12:16
This is what worked for us:
  firebase_core: ^2.17.0
  firebase_auth: 4.10.1
  firebase_storage: ^11.2.8
  firebase_messaging: ^14.6.9
  cloud_firestore: ^4.9.3

**Comment by Lyokone** [comment] 2023-10-18 13:17
I've opened a [PR](https://github.com/firebase/flutterfire/pull/11731) to fix this, it due to name clash between the Auth and Firestore modules.
It wasn't caught during our e2e testing because we are running Firestore tests on a separate project (so without auth). We'll investigate how we could better catch this in the future.

I'll let you know when a new version is released with the fix

**Comment by knotmine** [comment] 2023-10-18 14:03
> For now use this in your pub yaml
> 
> cloud_firestore: 4.9.2 firebase_core: 2.16.0 firebase_storage: 11.2.7 firebase_auth: 4.10.0 firebase_messaging: 14.6.8 firebase_analytics: 10.5.0

I had to downgrade firebase_ui_auth to make it work. 

`  firebase_ui_auth: ^1.8.0`

**Comment by johnebere58** [comment] 2023-10-18 18:19
Can you share a screenshot of the firebase packages you use on your pub yaml > I am on "Xcode - develop for iOS and macOS (Xcode 14.3)" and "Flutter (Channel stable, 3.13.7, on macOS 13.0 22A380 darwin-arm64, locale en-GB)"
> 
> 
> 
> The error happened to me after upgrading the flutter and pub packages.
> 
> 
> 
> I have tried all the suggestions on this page and still, the issue persists. I also have tried different versions of the Firebase-related packages with or without "^". 
> 
> 
> 
> On Android it is working alright.
> 
> 
> 
> Any other solution?
> 
> 
> 
>

**Comment by Naveed-dev30** [comment] 2023-10-18 19:34
> firebase_auth: 4.10.0

Thanks. This temporary and quick solution worked for me. Thanks for backing me.

**Closed** 2023-10-19 07:22 UTC
Labels: type: bug, impact: crowd (P2), plugin: auth, platform: ios

**Comment by ZahraVe** [comment] 2023-10-19 08:30
> Can you share a screenshot of the firebase packages you use on your pub yaml > I am on "Xcode - develop for iOS and macOS (Xcode 14.3)" and "Flutter (Channel stable, 3.13.7, on macOS 13.0 22A380 darwin-arm64, locale en-GB)"
> 
> > The error happened to me after upgrading the flutter and pub packages.
> > I have tried all the suggestions on this page and still, the issue persists. I also have tried different versions of the Firebase-related packages with or without "^".
> > On Android it is working alright.
> > Any other solution?

Have tried the latest resolvable versions as well as lower version all with or without "^"
but if it helps, the current ones are:
<img width="337" alt="Screenshot 2023-10-19 at 09 30 40" src="https://github.com/firebase/flutterfire/assets/87306265/350f1455-0134-4014-afb2-d20cb13098ea">

**Comment by ZahraVe** [comment] 2023-10-19 09:09
I am now able to run on iOS after downgrading some of the Firebase packages. 

```
[✓] Flutter (Channel stable, 3.13.7, on macOS 13.0 arm64, locale en-GB)
    • Flutter version 3.13.7 on channel stable 
    • Dart version 3.1.3
    • DevTools version 2.25.0

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • CocoaPods version 1.13.0
```

```
  firebase_core: ^2.17.0
  firebase_auth: ^4.10.1
  cloud_firestore: ^4.9.2
  cloud_functions: ^4.4.2
  firebase_dynamic_links: ^5.3.4
  firebase_messaging: ^14.6.8
```

**Comment by Lyokone** [comment] 2023-10-19 10:04
Released as part of https://pub.dev/packages/cloud_firestore/versions/4.11.0

**Comment by wilpar** [comment] 2023-10-19 15:41
Confirmed fix.  Unlocked firebase_auth from 4.10.1, ran flutter pub upgrade, and I can still run on IOS. Thanks for the fast fix.
