### ISSUE TITLE
🐛 [firebase_ui_auth] Google sign in button shuts down IOS app.

### ISSUE THREAD

**Issue by v-luis** [firebase/flutterfire#9808] opened 2022-10-27 21:30 UTC
## Bug report

Google Sign in Button on the firebase_ui_auth package SignInScreen() widget, suddenly shuts down the application on IOS. Works fine for both Web and Android applications. I do not have error logs, it just says "Lost connection to device" on Debug console, and a "Runner quit unexpectedly" warning pops-up from Xcode. I tried configuring Firebase through Flutterfire_cli and through the manual configuration, non of them work. 

![Screen Shot 2022-10-27 at 2 16 38 PM](https://user-images.githubusercontent.com/101297229/198379914-7a2e685d-005a-4b20-8cab-197908b361f2.png)
![Screen Shot 2022-10-27 at 2 16 51 PM](https://user-images.githubusercontent.com/101297229/198379927-bb3c9ba9-353d-4404-bed7-6b4529fbba14.png)

### Steps to reproduce

1. Setup ios app in Firebase using Flutterfire_cli
2. Configure Info.plist file as per flutter google_sign_in
3. Configure GoogleProvider for SignInScreen() Widget of firebase_ui_package (Taking the client id from the keys generated on Google Cloud Console 0auth credentials).
4. Run app on ios emulator. 
5. Display SignInScreen in the app and try to sign in with the Google button. 
6. App shots down unexpectedly
### Expected behavior

App will shut down unexpectedly after clicking the google sign in button. 

### Sample project
![Screen Shot 2022-10-27 at 4 07 55 PM](https://user-images.githubusercontent.com/101297229/198398623-41f0ce25-f5d1-499c-8a8d-38c70c51b175.png)
![Screen Shot 2022-10-27 at 4 09 15 PM](https://user-images.githubusercontent.com/101297229/198398626-294dfb7b-379b-43a7-b70b-fb96b24b7500.png)

## Additional context

Works perfectly on Android and Web applications.
I had implemented it with FlutterFire_UI package (deprecated) previously and works fine. 
Facebook button appears to do the same, only Apple button throws error (Facebook and Apple have not been implemented nor configured yet).
![Simulator Screen Shot - iPhone 13 - 2022-10-27 at 16 14 51](https://user-images.githubusercontent.com/101297229/198401560-06578d60-1fd2-4476-aa3b-e64eb07250f2.png)

However, in Web and Android, Facebook and Apple button do throw an error (not implemented yet) (please ignore the overflow error in the next screenshot, app in early stages). Non of the buttons shut down the app immediately here. 

![Screen Shot 2022-10-27 at 4 25 59 PM](https://user-images.githubusercontent.com/101297229/198401810-fff9e94f-4aea-4e2a-9d1f-1833e8ad6d00.png)

### Flutter doctor

<details><summary>Click To Expand</summary>

![Screen Shot 2022-10-27 at 2 21 02 PM](https://user-images.githubusercontent.com/101297229/198380023-50080673-b48c-4772-a1ca-8caf451623b5.png)

</details>

---

### Flutter dependencies

![Screen Shot 2022-10-27 at 4 12 06 PM](https://user-images.githubusercontent.com/101297229/198399121-aa799cbf-3df1-400a-bc75-33c7ec941c07.png)

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

**Comment by danagbemava-nc** [comment] 2022-10-28 09:08
Hi @v-luis, I set up `google_sign_in` and used a minimal sample for the Sign In With Google and the app does not shut down when I tap on the button. See the recording below. Can you share a minimal sample that we can use to verify this bug? 

Thank you


<details>
<summary>recordings</summary>

https://user-images.githubusercontent.com/88313112/198549866-a9bb6720-abd6-48d9-a9cd-a68cb9a36996.mov
</details>

**Comment by v-luis** [comment] 2022-10-28 18:04
Hi @danagbemava-nc  thanks for the recording, please check out the following recording for facebook and google buttons:

https://user-images.githubusercontent.com/101297229/198702828-1047b14d-f067-4f78-bdf4-134fb5182d81.mp4

https://user-images.githubusercontent.com/101297229/198702848-322295f3-495a-4d85-a8bb-fd0be5f60326.mp4

Rest works fine.
Thanks!

**Comment by v-luis** [comment] 2022-10-28 23:04
Hi @danagbemava-nc . Just to let you know, finished implementing Facebook and the button started working correctly. However, did whole implementation again from scratch for Google and button still does the same (quits app unexpectedly). I will keep working on it and let you know any advances. 
Thanks,

**Comment by workerbee22** [comment] 2022-10-29 05:20
I used the /example code from the package repo, exactly as is and get this error also.

[Package example app code in repo](https://github.com/firebase/flutterfire/tree/master/packages/firebase_ui_auth/example)

**Comment by danagbemava-nc** [comment] 2022-10-31 10:45
> Hi @danagbemava-nc . Just to let you know, finished implementing Facebook and the button started working correctly. However, did whole implementation again from scratch for Google and button still does the same (quits app unexpectedly). I will keep working on it and let you know any advances. Thanks,

Hi @v-luis, Please share your findings when you're able to  



> I used the /example code from the package repo, exactly as is and get this error also.
> 
> [Package example app code in repo](https://github.com/firebase/flutterfire/tree/master/packages/firebase_ui_auth/example?rgh-link-date=2022-10-29T05%3A20%3A04Z)

Hi @workerbee22, does it also crash for you, or do you experience something else? When I run the example app, I just get 
"an unexpected error occurred" but no crash

https://user-images.githubusercontent.com/88313112/198990368-8da77027-7501-4b9a-9a64-fa6bb67a3d05.mp4

**Comment by v-luis** [comment] 2022-10-31 22:52
@danagbemava-nc It finally worked! In the info.plist file I had the Facebook and Google CFBundleURLSchemes entries in diferrent CFBundleURLTypes entries. I grouped them in the same  CFBundleURLTypes entry and it worked.

![Screen Shot 2022-10-31 at 4 48 12 PM](https://user-images.githubusercontent.com/101297229/199124692-68123621-a330-4924-a407-f133ef43a08b.png)


@workerbee22 Hope this works for you as well. 

Thanks!

**Comment by danagbemava-nc** [comment] 2022-11-01 09:00
Hi @v-luis, thanks for the info. 

I'll be closing this as you seem to have resolved your issue. 

@workerbee22, kindly file a new issue and provide the relevant information required to reproduce as it seems your issue might be unrelated to this one. 

Thank you

**Closed by danagbemava-nc** 2022-11-01 09:00 UTC
Labels: type: bug, Needs Attention, in triage

**Comment by workerbee22** [comment] 2022-11-01 09:20
Thanks @danagbemava-nc I'll look at this and confirm 👍

**Comment by workerbee22** [comment] 2022-11-02 09:35
@danagbemava-nc Where did you find this information? The /example project within the repo for **firebase_ui_auth** has nothing like this on the `/ios/Runner/Info.plist` https://github.com/firebase/flutterfire/blob/master/packages/firebase_ui_auth/example/ios/Runner/Info.plist

So how can it ever work?

**Comment by workerbee22** [comment] 2022-11-02 09:47
I cannot find ANY references to this configuration in the official documentation at all .... or am I missing something?

Official Flutter Auth documentation is here: https://firebase.google.com/docs/auth/flutter/start

**Comment by danagbemava-nc** [comment] 2022-11-02 10:10
Hi @workerbee22, I believe that information was taken from the documentation of the [facebook_auth](https://pub.dev/packages/flutter_login_facebook) and [google_sign_in](https://pub.dev/packages/google_sign_in) packages

I only just realized that I had the CFBundleURLTypes set in my initial comment in https://github.com/firebase/flutterfire/issues/9808#issuecomment-1294736389 since I followed the setup from the readme  of `google_sign_in`

**Comment by workerbee22** [comment] 2022-11-02 23:32
@danagbemava-nc Yep its right on the front page of [google_sign_in](https://pub.dev/packages/google_sign_in).

It is also mentioned in the [offical Firebase Auth Flutter](https://firebase.google.com/docs/auth/flutter/federated-auth#google) documentation but simply as this ... blink and you'll miss it ...

<img width="742" alt="image" src="https://user-images.githubusercontent.com/5154664/199621525-6d6d0a09-1928-42c3-9527-8ba886165e30.png">
