### ISSUE TITLE
🐛 [firebase_app_check] ios build error Semantic Issue (Xcode): 'new' is unavailable error

### ISSUE THREAD

**Issue by Ko-Dean** [firebase/flutterfire#10732] opened 2023-04-06 06:49 UTC
## Bug report

**Describe the bug**
firebase_app_check install 
flutter run 
return error

### Steps to reproduce

1. appCheck install
2. flutter run 

### Flutter doctor

[✓] Flutter (Channel stable, 3.7.1, on macOS 13.2.1 22D68 darwin-arm64, locale ko-KR)
[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.76.2)
[✓] Connected device (4 available)
[✓] HTTP Host Availability

PASTE OUTPUT INSIDE HERE

```
`Launching lib/main.dart on iPhone 14 in debug mode...
main.dart:1
Xcode build done.                                           16.9s
Failed to build iOS app
Semantic Issue (Xcode): 'new' is unavailable
/Users/dean/.pub-cache/hosted/pub.dev/firebase_app_check-0.1.2/ios/Classes/FLTAppCheckProvider.m:18:55

Semantic Issue (Xcode): 'new' is unavailable
/Users/dean/.pub-cache/hosted/pub.dev/firebase_app_check-0.1.2/ios/Classes/FLTAppCheckProvider.m:22:53

Semantic Issue (Xcode): 'new' is unavailable
/Users/dean/.pub-cache/hosted/pub.dev/firebase_app_check-0.1.2/ios/Classes/FLTAppCheckProvider.m:30:57

Could not build the application for the simulator.
Error launching application on iPhone 14.
Exited`
```

**Comment by Ko-Dean** [comment] 2023-04-06 06:53
/Users/dean/.pub-cache/hosted/pub.dev/firebase_app_check-0.1.2/ios/Classes/FLTAppCheckProvider.m:18:55
/Users/dean/.pub-cache/hosted/pub.dev/firebase_app_check-0.1.2/ios/Classes/FLTAppCheckProvider.m:22:53
/Users/dean/.pub-cache/hosted/pub.dev/firebase_app_check-0.1.2/ios/Classes/FLTAppCheckProvider.m:30:57

new -> alloc  
I changed it and it was solved

**Comment by danagbemava-nc** [comment] 2023-04-06 08:56
This is a duplicate of https://github.com/firebase/flutterfire/issues/10694. 

Kindly subscribe to the original issue for updates.

Please upvote the original issue as well. 

Thank you

**Closed by danagbemava-nc** 2023-04-06 08:56 UTC
Labels: type: bug, Needs Attention, in triage
