### ISSUE TITLE
🐛 [Firebase messages] Can't send notifications from the phone.

### ISSUE THREAD

**Issue by arnair** [firebase/flutterfire#11707] opened 2023-10-15 07:37 UTC
## Bug report

I followed the documentation on sending notifications from the phone smulator/device with the new v1 api, but I got a status 401 error.
If I send a notification from the firebase admin console it works.

The code that return the 401 for sending a notification from the phone is this:
(the barer and the receiverToken are full before sending)

`  Future<void> sendNotification(
      {required String body, required String senderId}) async {
    String? bearer = await FirebaseAuth.instance.currentUser!.getIdToken();

    // FCM API endpoint
    var url = Uri.parse(
        'https://fcm.googleapis.com/v1/projects/my project/messages:send');

    var headers = {
      'Content-Type': 'application/json',
      'Authorization': 'Bearer ya29.$bearer',
    };

    // Create the request body
    var body = jsonEncode({
      'message': {
        'token': receiverToken,
        'data': {},
        'notification': {
          'title': 'FCM Message',
          'body': 'This is an FCM notification message!',
        }
      },
      "android": {
        "direct_boot_ok": true,
      },
    });
    // Send the POST request
    var response = await http.post(url, headers: headers, body: body);

    if (response.statusCode == 200) {
      print('Here FCM message sent successfully');
    } else {
      print(
          'Here Failed to send FCM message. Status code: ${response.statusCode}');
      print('Here Response body: ${response.body}');
    }
  }`

### Steps to reproduce

1. activate notifications 
2. send a notification
3. lisent to the status

### Expected behaviour

Send a notification to the token device

### Flutter dependencies

  firebase_messaging: ^14.6.9

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

**Comment by darshankawar** [comment] 2023-10-16 11:11
@arnair 
Can you provide the entire error log ?

**Comment by darshankawar** [comment] 2023-10-17 10:14
@arnair 
Since the log shows `Failed to send FCM message. Status code: 401`, it probably indicates a server key issue and in your case it may not be a valid one. Check the same.
Closing it for now as this is due to config issue and not a bug in plugin.

**Closed by darshankawar** 2023-10-17 10:14 UTC
Labels: type: bug, Needs Attention, in triage

**Comment by arnair** [comment] 2023-10-17 11:42
> @arnair Since the log shows `Failed to send FCM message. Status code: 401`, it probably indicates a server key issue and in your case it may not be a valid one. Check the same. Closing it for now as this is due to config issue and not a bug in plugin.

Can it be that is not possible to send notifications directly from the device with the v1 api? 
Because in the documentation, there is not an example about how to do that on flutter only from a cloud functions.

Thanks
