### ISSUE TITLE
🐛 [  io.flutter.plugins.firebase.firestore.FlutterFirebaseFirestorePlugin ]  Unable to destroy activity

### ISSUE THREAD

**Issue by djankur** [firebase/flutterfire#11727] opened 2023-10-18 10:19 UTC
The error seems to be related to the io.flutter.plugins.firebase.firestore.FlutterFirebaseFirestorePlugin where the setMethodCallHandler method is invoked on a null object reference. The stack trace also shows that the error occurs during the execution of the onDetachedFromEngine method in the FlutterFirebaseFirestorePlugin.java file.

**Comment by darshankawar** [comment] 2023-10-18 11:17
@djankur 
When opening an issue, please try to use [new issue template](https://github.com/firebase/flutterfire/issues/new?assignees=&labels=Needs+Attention%2C+type%3A+bug&projects=&template=---bug-report.md&title=%F0%9F%90%9B+%5BPLUGIN_NAME_HERE%5D+Your+issue+title+here) and fill out requested details so that we'll have enough info to work with.
We would need a complete runnable reproducible code sample, plugin versions and flutter doctor -v in order to properly address the issue.

Closing for now due to lack of details provided.

**Closed by darshankawar** 2023-10-18 11:17 UTC
Labels: type: bug, Needs Attention, in triage
