### ISSUE TITLE
[firebase_messaging]: getInitialMessage() doesn't work as expected on ios

### ISSUE THREAD

**Issue by Poloten** [firebase/flutterfire#12958] opened 2024-06-14 09:37 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Messaging

### Which platforms are affected?

iOS

### Description

Hi,

I have a bug when I call from initState getInitialMessage() it always return null after taps on a notification while the app is in a terminated state. It is important to reproduce this behavior, you need to have **1 active notification**; if there are 2 or more, the method returns information.
If app in backgound onBackgroundMessage - work fine, onMessage  work fine too. I know about flutter_local_notifications but data-only messages are considered lower priority than notification messages.

### Reproducing the issue

Steps to Reproduce:

1. Close app (e.g., swipe out from the recent list).
2. Send a notification message to the application via firebase.
3. Notification received. 
4. Tap on the notification.
5. Application loaded, call in initState() getInitialMessage() it returns null.

```dart
  @override
  initState() {
    super.initState();
    FirebaseMessaging.instance.getInitialMessage()
      .then((RemoteMessage? value) => setState(() {
         if (value == null) return; // always null 
             handleMessage(mesId);
         }),
      );
}
```

### Firebase Core version

3.1.0

### Flutter Version

3.22.2

### Relevant Log Output

```shell
FirebaseAppDelegateProxyEnabled - YES

contentAvailable - true

I also tried on firebase_core: 2.32.0; firebase_messaging: 14.9.4
```

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml
dependencies:
- firebase_analytics 11.0.1 [firebase_analytics_platform_interface firebase_analytics_web firebase_core firebase_core_platform_interface flutter]
- firebase_core 3.1.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_messaging 15.0.1 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]

transitive dependencies:
- firebase_analytics_platform_interface 4.0.1 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_analytics_web 0.5.7+9 [_flutterfire_internals firebase_analytics_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins]
- firebase_core_platform_interface 5.1.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.17.2 [firebase_core_platform_interface flutter flutter_web_plugins meta web]
- firebase_messaging_platform_interface 4.5.39 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 3.8.9 [_flutterfire_internals firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins meta web]

```

</details>

**Comment by TarekkMA** [comment] 2024-06-14 11:22
Hello @Poloten, Thank you for reporting this issue.

I guess this is a duplicate of this issue: #12453, Can you confirm?

**Comment by Poloten** [comment] 2024-06-17 11:08
> Hello @Poloten, Thank you for reporting this issue.
> 
> I guess this is a duplicate of this issue: #12453, Can you confirm?

Probably the same. 
Information about the number of active notifications may be helpful. (1 active notification - not work;  2 active notification - work).

**Comment by Poloten** [comment] 2024-06-20 14:51
[TarekkMA](https://github.com/TarekkMA) If I call  FirebaseMessaging.instance.getInitialMessage().then((val) => .....) after few times late, I mean some seconds, it works... In Main initState()  - it doesn't work. 
May be u can writter better bridge, like a stream ? Or maybe Future can't be resolved until message received if exist. Now it is unstable behaviour.

**Comment by TarekkMA** [comment] 2024-06-21 10:58
Closing this issue in favor of the original one. Please share your findings in the original issue, and we'll look into fixing it. Thanks!

**Closed by TarekkMA** 2024-06-21 10:58 UTC
Labels: type: bug, plugin: messaging, platform: ios, Needs Attention
