### ISSUE TITLE
GetOptions function doesn't work in flutter web

### ISSUE THREAD

**Issue by donuthappy** [firebase/flutterfire#11972] opened 2023-12-04 16:09 UTC
GetOptions(source: Source.cache) doesn't work in flutter web.
I always get empty results when option is cache.

```
CollectionReference collectionRef =
        FirebaseFirestore.instance.collection('posts');
    var listings = (await collectionRef
            .get(const GetOptions(source: Source.cache)))
        .docs;
```
This is my example code.

I set this option in main() function.
```
FirebaseFirestore.instance.settings = const Settings(
    persistenceEnabled: true,
    cacheSizeBytes: Settings.CACHE_SIZE_UNLIMITED,
  );
```

But I didn't get cache data.

Please answer for this issue.

**Comment by darshankawar** [comment] 2023-12-05 10:41
@donuthappy 
Using plugin example and adding your code snippet in it, like below did give me the `listings`:

```
Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  FirebaseFirestore.instance.settings = const Settings(
    persistenceEnabled: true, cacheSizeBytes: Settings.CACHE_SIZE_UNLIMITED
  );

  if (shouldUseFirestoreEmulator) {
    FirebaseFirestore.instance.useFirestoreEmulator('localhost', 8080);
  }
  CollectionReference collectionReference = FirebaseFirestore.instance.collection('firestore-example-app');
  var listings = ( await collectionReference.get(const GetOptions(source: Source.cache))).docs;
  print(listings.length);
```

```
Restarted application in 186ms.
13
```

In your case, what's the actual vs expected behavior you are looking for ?

**Comment by donuthappy** [comment] 2023-12-05 10:50
@darshankawar 
Thank you
Let me try.

**Comment by donuthappy** [comment] 2023-12-05 13:55
@darshankawar 
I tried with  this example code but this doesn't work.

```
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  FirebaseFirestore.instance.useFirestoreEmulator('localhost', 8080);
  runApp(const MyApp());
}
```

```
CollectionReference collectionRef =
        FirebaseFirestore.instance.collection('openfair_prod_v3');
    var listings = (await collectionRef
            .where('published', isEqualTo: true)
            .limit(500)
            .get(const GetOptions(source: Source.cache)))
        .docs;

    nLength = listings.length;
    for (var c in listings) {
      if (c.metadata.isFromCache) {
        isCache = true;
      } else {
        isCache = false;
      }
    }
```

**Comment by darshankawar** [comment] 2023-12-06 11:39
Thanks for the update. Upon running same code snippet, I get below:

```
Performing hot restart...                                          207ms
Restarted application in 208ms.
13
13
is cache
is cache
is cache
is cache
is cache
is cache

```

```
var listings = ( await collectionReference.get(const GetOptions(source: Source.cache))).docs;
  print(listings.length);
  var nLength = listings.length;
  print(nLength);
  for (var c in listings) {
    if (c.metadata.isFromCache) {
      print('is cache');
    } else {
      print('not cache');
    }
  }
```

**Comment by donuthappy** [comment] 2023-12-06 14:03
@darshankawar  Thank you!
I updated the code 
FirebaseFirestore.instance.enablePersistence();
instead of 
```
FirebaseFirestore.instance.settings = const Settings(
      persistenceEnabled: true, cacheSizeBytes: Settings.CACHE_SIZE_UNLIMITED);
```

So firebase query cache works well.
But I got one error.
`FirebaseError: Firestore has already been started and persistence can no longer be enabled. You can only enable persistence before calling any other methods on a Firestore object.`
How can I remove this error.

**Comment by darshankawar** [comment] 2023-12-07 10:51
> FirebaseError: Firestore has already been started and persistence can no longer be enabled. You can only enable persistence before calling any other methods on a Firestore object.

This error indicates you might have another instance of the firebase initialization that might be conflicting with `ensureInitialized()` ie few other places in your code that might still be importing and using firebase. You can check the same and see if it is the case or not.

Since your original question / issue of caching is resolved, I'll close this.

**Closed by darshankawar** 2023-12-07 10:51 UTC
Labels: type: bug, Needs Attention, in triage
