### ISSUE TITLE
🐛 [firebase_auth_web] ^5.2.5 which depends on intl ^0.17.0

### ISSUE THREAD

**Issue by sgehrman** [firebase/flutterfire#10403] opened 2023-02-09 03:34 UTC
update packs

**Comment by darshankawar** [comment] 2023-02-09 10:26
Closing as duplicate of https://github.com/firebase/flutterfire/issues/10199. Please see https://github.com/firebase/flutterfire/issues/10199#issuecomment-1368981937 comment for solution.

**Closed by darshankawar** 2023-02-09 10:26 UTC
Labels: type: bug, Needs Attention, in triage
