### ISSUE TITLE
🐛 [cloud_firestore] Stream error: 'Unavailable: failed to connect to all addresses

### ISSUE THREAD

**Issue by nzackoya** [firebase/flutterfire#11736] opened 2023-10-19 12:50 UTC
## Bug report

**Describe the bug**
Not sure what happened, but started getting this error 
```
Could not reach Cloud Firestore backend. Backend didn't respond within 10 seconds. This typically indicates that your device does not have a healthy Internet connection at the moment. The client will operate in offline mode until it is able to successfully connect to the backend.
Stream error: 'Unavailable: failed to connect to all addresses; last error: UNKNOWN: ipv6:%5B2a00:***:443: No route to host
```
UPD: No issues when using another VPN. This is insane!!!

### Steps to reproduce

I'm not sure how to reproduce, but nefore getting the errors I've updated to firebase_auth: ^4.11.0, then got the `'PigeonParser.h' file not found` in iOS. Then downgraded back, so the Pigeon error gone, but started getting the errors above. Tried with wifi, ~~vpn~~ and mobile internet. Also tried on different devices, platforms and emulator. All of them has the issue. But my colleague tried the project and got no issues.

### Expected behavior

It should work

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 3.13.8, on macOS 13.5.1 22G90 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] IntelliJ IDEA Community Edition (version 2022.3.2)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!

```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 3.1.4
Flutter SDK 3.13.8
frontstage 1.7.2+31

dependencies:
- algolia 1.1.2 [meta http uuid universal_io]
- app_settings 5.1.1 [flutter plugin_platform_interface]
- async 2.11.0 [collection meta]
- audioplayers 5.2.0 [audioplayers_android audioplayers_darwin audioplayers_linux audioplayers_platform_interface audioplayers_web audioplayers_windows file flutter http meta path_provider synchronized uuid]
- badges 3.1.2 [flutter]
- cached_network_image 3.3.0 [cached_network_image_platform_interface cached_network_image_web flutter flutter_cache_manager octo_image]
- cloud_firestore 4.11.0 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_interface flutter meta]
- collection 1.17.2
- connectivity_plus 5.0.1 [flutter flutter_web_plugins connectivity_plus_platform_interface js meta nm]
- country_codes 2.2.0 [flutter]
- crypto 3.0.3 [typed_data]
- dio 5.3.3 [async http_parser meta path]
- easy_image_viewer 1.2.1 [flutter]
- easy_localization 3.0.3 [flutter shared_preferences intl args path easy_logger flutter_localizations]
- email_validator 2.1.17
- enum_to_string 2.0.1
- expandable_text 2.3.0 [flutter]
- firebase_analytics 10.6.1 [firebase_analytics_platform_interface firebase_analytics_web firebase_core firebase_core_platform_interface flutter]
- firebase_auth 4.11.1 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 2.19.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_crashlytics 3.4.1 [firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface flutter stack_trace]
- firebase_dynamic_links 5.4.1 [firebase_core firebase_core_platform_interface firebase_dynamic_links_platform_interface flutter meta plugin_platform_interface]
- firebase_messaging 14.7.1 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- firebase_remote_config 4.3.1 [firebase_core firebase_core_platform_interface firebase_remote_config_platform_interface firebase_remote_config_web flutter]
- firebase_storage 11.3.1 [firebase_core firebase_core_platform_interface firebase_storage_platform_interface firebase_storage_web flutter]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math web sky_engine]
- flutter_app_badger 1.5.0 [flutter]
- flutter_branch_sdk 6.9.0 [flutter flutter_web_plugins plugin_platform_interface js]
- flutter_cache_manager 3.3.1 [clock collection file flutter http path path_provider rxdart sqflite uuid]
- flutter_flavor 3.1.3 [flutter]
- flutter_local_notifications 16.1.0 [clock flutter flutter_local_notifications_linux flutter_local_notifications_platform_interface timezone]
- flutter_riverpod 2.4.4 [collection flutter meta riverpod state_notifier]
- flutter_screenutil 5.9.0 [flutter]
- flutter_sim_country_code 0.1.2 [flutter]
- flutter_sticky_header 0.6.5 [flutter value_layout_builder]
- flutter_styled_toast 2.2.1 [flutter flutter_localizations]
- flutter_svg 2.0.7 [flutter vector_graphics vector_graphics_codec vector_graphics_compiler]
- flutter_widget_from_html_core 0.14.3 [csslib flutter html logging]
- freezed 2.4.5 [analyzer build build_config collection meta source_gen freezed_annotation json_annotation]
- freezed_annotation 2.4.1 [collection json_annotation meta]
- geocoding 2.1.1 [flutter geocoding_platform_interface geocoding_android geocoding_ios]
- geolocator 8.2.1 [flutter geolocator_platform_interface geolocator_android geolocator_apple geolocator_web geolocator_windows]
- google_sign_in 6.1.5 [flutter google_sign_in_android google_sign_in_ios google_sign_in_platform_interface google_sign_in_web]
- hive 2.2.3 [meta crypto]
- image 4.0.17 [archive meta xml]
- image_picker 1.0.4 [flutter image_picker_android image_picker_for_web image_picker_ios image_picker_linux image_picker_macos image_picker_platform_interface image_picker_windows]
- infinite_scroll_pagination 4.0.0 [flutter flutter_staggered_grid_view sliver_tools]
- json_annotation 4.8.1 [meta]
- json_schema2 2.0.4+9 [args collection logging meta path rest_client uri yaon]
- json_serializable 6.7.1 [analyzer async build build_config collection json_annotation meta path pub_semver pubspec_parse source_gen source_helper]
- just_the_tooltip 0.0.12 [flutter]
- logger 2.0.2+1
- map_launcher 3.0.1 [flutter]
- mapbox_gl 0.16.0 [flutter mapbox_gl_platform_interface mapbox_gl_web collection]
- maps_launcher 2.2.0 [flutter flutter_web_plugins url_launcher]
- open_mail_app 0.4.5 [platform url_launcher flutter]
- package_info_plus 4.2.0 [ffi flutter flutter_web_plugins http meta path package_info_plus_platform_interface win32]
- page_view_dot_indicator 2.3.0 [flutter]
- path_provider 2.1.1 [flutter path_provider_android path_provider_foundation path_provider_linux path_provider_platform_interface path_provider_windows]
- percent_indicator 4.2.3 [flutter]
- photo_view 0.14.0 [flutter]
- retry 3.1.2
- rxdart 0.27.7
- share_plus 7.2.1 [cross_file meta mime flutter flutter_web_plugins share_plus_platform_interface file url_launcher_web url_launcher_windows url_launcher_linux url_launcher_platform_interface ffi win32]
- shimmer 3.0.0 [flutter]
- showcaseview 2.0.3 [flutter]
- sign_in_with_apple 5.0.0 [flutter meta sign_in_with_apple_platform_interface sign_in_with_apple_web]
- spotify 0.11.0 [http json_annotation oauth2 pedantic]
- timezone 0.9.2 [path]
- url_launcher 6.1.14 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- uuid 3.0.7 [crypto]
- version 3.0.2
- webview_flutter 4.4.1 [flutter webview_flutter_android webview_flutter_platform_interface webview_flutter_wkwebview]

dev dependencies:
- build_runner 2.4.6 [analyzer args async build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style frontend_server_client glob graphs http_multi_server io js logging meta mime package_config path pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web_socket_channel yaml]
- flutter_lints 2.0.3 [lints]
- flutter_test 0.0.0 [flutter test_api matcher path fake_async clock stack_trace vector_math async boolean_selector characters collection material_color_utilities meta source_span stream_channel string_scanner term_glyph web]
- integration_test 0.0.0 [flutter flutter_driver flutter_test path vm_service async boolean_selector characters clock collection fake_async file matcher material_color_utilities meta source_span stack_trace stream_channel string_scanner sync_http term_glyph test_api vector_math web webdriver]

dependency overrides:
- webview_flutter_wkwebview 3.5.0 [flutter path webview_flutter_platform_interface]

transitive dependencies:
- _fe_analyzer_shared 64.0.0 [meta]
- _flutterfire_internals 1.3.9 [collection firebase_core firebase_core_platform_interface flutter meta]
- analyzer 6.2.0 [_fe_analyzer_shared collection convert crypto glob meta package_config path pub_semver source_span watcher yaml]
- archive 3.3.7 [crypto path pointycastle]
- args 2.4.2
- audioplayers_android 4.0.2 [audioplayers_platform_interface flutter]
- audioplayers_darwin 5.0.2 [audioplayers_platform_interface flutter]
- audioplayers_linux 3.1.0 [audioplayers_platform_interface flutter]
- audioplayers_platform_interface 6.1.0 [flutter meta plugin_platform_interface]
- audioplayers_web 4.1.0 [audioplayers_platform_interface flutter flutter_web_plugins js]
- audioplayers_windows 3.1.0 [audioplayers_platform_interface flutter]
- boolean_selector 2.1.1 [source_span string_scanner]
- build 2.4.1 [analyzer async convert crypto glob logging meta package_config path]
- build_config 1.1.1 [checked_yaml json_annotation path pubspec_parse yaml]
- build_daemon 4.0.0 [built_collection built_value http_multi_server logging path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 2.2.1 [analyzer async build collection crypto graphs logging package_config path pool pub_semver stream_transform yaml]
- build_runner_core 7.2.10 [async build build_config build_resolvers collection convert crypto glob graphs json_annotation logging meta package_config path pool timing watcher yaml]
- built_collection 5.1.1
- built_value 8.6.2 [built_collection collection fixnum meta]
- cached_network_image_platform_interface 3.0.0 [flutter flutter_cache_manager]
- cached_network_image_web 1.1.0 [cached_network_image_platform_interface flutter flutter_cache_manager]
- characters 1.3.0
- checked_yaml 2.0.3 [json_annotation source_span yaml]
- clock 1.1.1
- cloud_firestore_platform_interface 6.0.1 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 3.8.1 [_flutterfire_internals cloud_firestore_platform_interface collection firebase_core firebase_core_web flutter flutter_web_plugins js]
- code_builder 4.5.0 [built_collection built_value collection matcher meta]
- connectivity_plus_platform_interface 1.2.4 [flutter meta plugin_platform_interface]
- convert 3.1.1 [typed_data]
- cross_file 0.3.3+4 [js meta]
- csslib 1.0.0 [source_span]
- dart_style 2.3.2 [analyzer args path pub_semver source_span]
- dbus 0.7.8 [args ffi meta xml]
- easy_logger 0.0.2 [flutter]
- fake_async 1.3.1 [clock collection]
- ffi 2.1.0
- file 6.1.4 [meta path]
- file_selector_linux 0.9.2 [cross_file file_selector_platform_interface flutter]
- file_selector_macos 0.9.3+1 [cross_file file_selector_platform_interface flutter]
- file_selector_platform_interface 2.6.0 [cross_file flutter http plugin_platform_interface]
- file_selector_windows 0.9.3 [cross_file file_selector_platform_interface flutter]
- firebase_analytics_platform_interface 3.7.3 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_analytics_web 0.5.5+3 [_flutterfire_internals firebase_analytics_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- firebase_auth_platform_interface 7.0.1 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 5.8.4 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser js meta]
- firebase_core_platform_interface 5.0.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.8.1 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_crashlytics_platform_interface 3.6.9 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_dynamic_links_platform_interface 0.2.6+9 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_platform_interface 4.5.10 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 3.5.10 [_flutterfire_internals firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]
- firebase_remote_config_platform_interface 1.4.9 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_remote_config_web 1.4.9 [firebase_core firebase_core_web firebase_remote_config_platform_interface flutter flutter_web_plugins js]
- firebase_storage_platform_interface 4.4.9 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_storage_web 3.6.10 [_flutterfire_internals async firebase_core firebase_core_web firebase_storage_platform_interface flutter flutter_web_plugins http js meta]
- fixnum 1.1.0
- flutter_driver 0.0.0 [file flutter flutter_test fuchsia_remote_debug_protocol path meta vm_service webdriver async boolean_selector characters clock collection matcher material_color_utilities platform process source_span stack_trace stream_channel string_scanner sync_http term_glyph test_api vector_math web]
- flutter_local_notifications_linux 4.0.0+1 [dbus ffi flutter flutter_local_notifications_platform_interface path xdg_directories]
- flutter_local_notifications_platform_interface 7.0.0+1 [flutter plugin_platform_interface]
- flutter_localizations 0.0.0 [flutter intl characters clock collection material_color_utilities meta path vector_math web]
- flutter_plugin_android_lifecycle 2.0.15 [flutter]
- flutter_staggered_grid_view 0.7.0 [flutter]
- flutter_web_plugins 0.0.0 [flutter characters collection material_color_utilities meta vector_math web]
- frontend_server_client 3.2.0 [async path]
- fuchsia_remote_debug_protocol 0.0.0 [process vm_service file meta path platform]
- geocoding_android 2.1.2 [flutter geocoding_platform_interface]
- geocoding_ios 2.1.0 [flutter geocoding_platform_interface]
- geocoding_platform_interface 2.0.1 [flutter meta plugin_platform_interface]
- geolocator_android 3.2.1 [flutter geolocator_platform_interface]
- geolocator_apple 2.2.7 [flutter geolocator_platform_interface]
- geolocator_platform_interface 4.0.7 [flutter plugin_platform_interface vector_math meta]
- geolocator_web 2.1.6 [flutter flutter_web_plugins geolocator_platform_interface]
- geolocator_windows 0.1.3 [flutter geolocator_platform_interface]
- glob 2.1.2 [async collection file path string_scanner]
- google_identity_services_web 0.2.1 [js meta]
- google_sign_in_android 6.1.18 [flutter google_sign_in_platform_interface]
- google_sign_in_ios 5.6.2 [flutter google_sign_in_platform_interface]
- google_sign_in_platform_interface 2.4.1 [flutter plugin_platform_interface quiver]
- google_sign_in_web 0.12.0+3 [flutter flutter_web_plugins google_identity_services_web google_sign_in_platform_interface http js]
- graphs 2.3.1 [collection]
- html 0.15.4 [csslib source_span]
- http 0.13.6 [async http_parser meta]
- http_multi_server 3.2.1 [async]
- http_parser 4.0.2 [collection source_span string_scanner typed_data]
- image_picker_android 0.8.7+4 [flutter flutter_plugin_android_lifecycle image_picker_platform_interface]
- image_picker_for_web 3.0.0 [flutter flutter_web_plugins image_picker_platform_interface mime]
- image_picker_ios 0.8.8+1 [flutter image_picker_platform_interface]
- image_picker_linux 0.2.1 [file_selector_linux file_selector_platform_interface flutter image_picker_platform_interface]
- image_picker_macos 0.2.1 [file_selector_macos file_selector_platform_interface flutter image_picker_platform_interface]
- image_picker_platform_interface 2.9.0 [cross_file flutter http plugin_platform_interface]
- image_picker_windows 0.2.1 [file_selector_platform_interface file_selector_windows flutter image_picker_platform_interface]
- intl 0.18.1 [clock meta path]
- io 1.0.4 [meta path string_scanner]
- js 0.6.7 [meta]
- json_class 2.2.2+1 [intl logging meta]
- lints 2.1.1
- logging 1.2.0
- mapbox_gl_dart 0.2.1 [js]
- mapbox_gl_platform_interface 0.16.0 [flutter meta]
- mapbox_gl_web 0.16.0 [flutter flutter_web_plugins meta mapbox_gl_platform_interface mapbox_gl_dart image]
- matcher 0.12.16 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.5.0 [collection]
- meta 1.9.1
- mime 1.0.4
- nm 0.5.0 [dbus]
- oauth2 2.0.2 [collection crypto http http_parser]
- octo_image 2.0.0 [flutter]
- package_config 2.1.0 [path]
- package_info_plus_platform_interface 2.0.1 [flutter meta plugin_platform_interface]
- path 1.8.3
- path_parsing 1.0.1 [vector_math meta]
- path_provider_android 2.1.0 [flutter path_provider_platform_interface]
- path_provider_foundation 2.3.0 [flutter path_provider_platform_interface]
- path_provider_linux 2.2.0 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_platform_interface 2.1.0 [flutter platform plugin_platform_interface]
- path_provider_windows 2.2.0 [ffi flutter path path_provider_platform_interface win32]
- pedantic 1.11.1
- petitparser 5.4.0 [meta]
- platform 3.1.0
- plugin_platform_interface 2.1.5 [meta]
- pointycastle 3.7.3 [collection convert js]
- pool 1.5.1 [async stack_trace]
- process 4.2.4 [file path platform]
- pub_semver 2.1.4 [collection meta]
- pubspec_parse 1.2.3 [checked_yaml collection json_annotation pub_semver yaml]
- quiver 3.2.1 [matcher]
- rest_client 2.2.1+11 [http intl json_class logging meta uuid]
- riverpod 2.4.4 [meta stack_trace state_notifier]
- share_plus_platform_interface 3.3.1 [cross_file flutter meta mime plugin_platform_interface path_provider uuid]
- shared_preferences 2.2.0 [flutter shared_preferences_android shared_preferences_foundation shared_preferences_linux shared_preferences_platform_interface shared_preferences_web shared_preferences_windows]
- shared_preferences_android 2.2.0 [flutter shared_preferences_platform_interface]
- shared_preferences_foundation 2.3.3 [flutter shared_preferences_platform_interface]
- shared_preferences_linux 2.3.0 [file flutter path path_provider_linux path_provider_platform_interface shared_preferences_platform_interface]
- shared_preferences_platform_interface 2.3.0 [flutter plugin_platform_interface]
- shared_preferences_web 2.2.0 [flutter flutter_web_plugins shared_preferences_platform_interface]
- shared_preferences_windows 2.3.0 [file flutter path path_provider_platform_interface path_provider_windows shared_preferences_platform_interface]
- shelf 1.4.1 [async collection http_parser path stack_trace stream_channel]
- shelf_web_socket 1.0.4 [shelf stream_channel web_socket_channel]
- sign_in_with_apple_platform_interface 1.0.0 [flutter plugin_platform_interface meta]
- sign_in_with_apple_web 1.0.1 [flutter flutter_web_plugins sign_in_with_apple_platform_interface js]
- sky_engine 0.0.99
- sliver_tools 0.2.12 [flutter]
- source_gen 1.4.0 [analyzer async build dart_style glob path source_span yaml]
- source_helper 1.3.4 [analyzer collection source_gen]
- source_span 1.10.0 [collection path term_glyph]
- sqflite 2.3.0 [flutter sqflite_common path]
- sqflite_common 2.5.0 [synchronized path meta]
- stack_trace 1.11.0 [path]
- state_notifier 1.0.0 [meta]
- stream_channel 2.1.1 [async]
- stream_transform 2.1.0
- string_scanner 1.2.0 [source_span]
- sync_http 0.3.1
- synchronized 3.1.0
- term_glyph 1.2.1
- test_api 0.6.0 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph]
- timing 1.0.1 [json_annotation]
- typed_data 1.3.2 [collection]
- universal_io 2.2.2 [collection meta typed_data]
- uri 1.0.0 [matcher quiver]
- url_launcher_android 6.0.38 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.1.4 [flutter url_launcher_platform_interface]
- url_launcher_linux 3.0.5 [flutter url_launcher_platform_interface]
- url_launcher_macos 3.0.6 [flutter url_launcher_platform_interface]
- url_launcher_platform_interface 2.1.3 [flutter plugin_platform_interface]
- url_launcher_web 2.0.18 [flutter flutter_web_plugins url_launcher_platform_interface]
- url_launcher_windows 3.0.7 [flutter url_launcher_platform_interface]
- value_layout_builder 0.3.1 [flutter]
- vector_graphics 1.1.7 [flutter vector_graphics_codec]
- vector_graphics_codec 1.1.7
- vector_graphics_compiler 1.1.7 [args meta path_parsing xml vector_graphics_codec]
- vector_math 2.1.4
- vm_service 11.7.1
- watcher 1.1.0 [async path]
- web 0.1.4-beta
- web_socket_channel 2.4.0 [async crypto stream_channel]
- webdriver 3.0.2 [matcher path stack_trace sync_http]
- webview_flutter_android 3.12.0 [flutter webview_flutter_platform_interface]
- webview_flutter_platform_interface 2.6.0 [flutter meta plugin_platform_interface]
- win32 5.0.7 [ffi]
- xdg_directories 1.0.2 [meta path]
- xml 6.3.0 [collection meta petitparser]
- yaml 3.1.2 [collection source_span string_scanner]
- yaon 1.1.2+3 [logging yaml]
```

</details>

---

**Comment by Kinomad** [comment] 2023-10-19 13:23
I have the same issue. 

Yesterday, to avoid this issue `pigeonParser.h file not found`, I changed my .yaml with older version and everything work fine. Without to change my code, this afternoon I have this new message : 

`10.15.0 - [FirebaseFirestore][I-FST000001] WriteStream (139de2c18) Stream error: 'Unavailable: failed to connect to all addresses; last error: UNKNOWN: ipv6:%5B2a00:1450:4010:c02::5f%5D:443: No route to host' `

I updated all new plugin version of firebase (published 3h ago), but I still have the same issue.

**Comment by nzackoya** [comment] 2023-10-19 14:11
> I have the same issue.
> 
> Yesterday, to avoid this issue `pigeonParser.h file not found`, I changed my .yaml with older version and everything work fine. Without to change my code, this afternoon I have this new message :
> 
> `10.15.0 - [FirebaseFirestore][I-FST000001] WriteStream (139de2c18) Stream error: 'Unavailable: failed to connect to all addresses; last error: UNKNOWN: ipv6:%5B2a00:1450:4010:c02::5f%5D:443: No route to host' `
> 
> I updated all new plugin version of firebase (published 3h ago), but I still have the same issue.

Just to continue working use vpn, until they fix this. But not the VPNProxyMaster.

**Comment by Kinomad** [comment] 2023-10-19 15:36
> Just to continue working use vpn, until they fix this. But not the VPNProxyMaster.

Thanks @nzackoya for this temporary solution, it's work with Planet VPN

**Comment by nzackoya** [comment] 2023-10-19 16:20
@Kinomad np, just to have a whole picture, from which country are you trying to connect without VPN? I also reported a bug to google, need a list of countries in where the firestore is not working to tell them there as well

**Comment by Kinomad** [comment] 2023-10-19 20:19
@nzackoya I'm currently now in Russia (but it's worked fine till yesterday evening without VPN)

**Comment by nzackoya** [comment] 2023-10-19 20:23
@Kinomad same. If firestore is banned for russia, this is really insane

**Comment by Kinomad** [comment] 2023-10-19 20:26
@nzackoya Agree and I hope no...

**Comment by nzackoya** [comment] 2023-10-19 20:31
https://github.com/firebase/firebase-js-sdk/issues/7710#issuecomment-1771628183

**Comment by AbdElrahman-Rafaat-Amer** [comment] 2023-10-19 20:56
> @nzackoya I'm currently now in Russia for few days, but it's worked fine till yesterday evening without VPN

Hi @nzackoya, Could u mention where was you yesterday in Russia (the location/area)? and the  where you was when the issue happened (the location/area)?.
because I believe that from my test and reviewing the users who had the issue that the FireStore has issue on some ares on Russia not all of it.

**Comment by AbdElrahman-Rafaat-Amer** [comment] 2023-10-19 20:56
> @nzackoya I'm currently now in Russia for few days, but it's worked fine till yesterday evening without VPN

Hi @nzackoya, Could u mention where was you yesterday in Russia (the location/area)? and the  where you was when the issue happened (the location/area)?.
because I believe that from my test and reviewing the users who had the issue that the FireStore has issue on some ares on Russia not all of it.

**Comment by aazorin** [comment] 2023-10-19 20:59
Hi all! My clients in Russia (Moscow, Novosibirsk) also had problems working with the Firestore service.
Error: 10.16.0 - [FirebaseFirestore][I-FST000001] WriteStream (7f9651519118) Stream error: 'Unavailable: failed to connect to all addresses; last error: UNKNOWN: No route to host'

**Comment by nzackoya** [comment] 2023-10-19 22:54
@AbdElrahman-Rafaat-Amer  in Krasnodar. @aazorin says it happens in Moscow as well, so I guess it is allover the Russia if it happens in Moscow. Is some developers/users don't face any issues in russia, I suppose it could be because of persistent cache.  
Hey @darshankawar I guess this issue needs a close attention(hope this mentioning notifies)

**Comment by AbdElrahman-Rafaat-Amer** [comment] 2023-10-19 23:36
> @AbdElrahman-Rafaat-Amer in Krasnodar. @aazorin says it happens in Moscow as well, so I guess it is allover the Russia if it happens in Moscow. Is some developers/users don't face any issues in russia, I suppose it could be because of persistent cache. Hey @darshankawar I guess this issue needs a close attention(hope this mentioning notifies)

What I thought was that the issue was in all of Russia but after reviewing the users and checking their data I found that some users had no problems and the app worked fine(can write/read from FireStore) WITHOUT USING VPN but the others did not and all users in Russia.

**Comment by Kinomad** [comment] 2023-10-20 04:43
For me, I’m in Vologda

> > @AbdElrahman-Rafaat-Amer in Krasnodar. @aazorin says it happens in Moscow as well, so I guess it is allover the Russia if it happens in Moscow. Is some developers/users don't face any issues in russia, I suppose it could be because of persistent cache. Hey @darshankawar I guess this issue needs a close attention(hope this mentioning notifies)
> 
> What I thought was that the issue was in all of Russia but after reviewing the users and checking their data I found that some users had no problems and the app worked fine(can write/read from FireStore) WITHOUT USING VPN but the others did not and all users in Russia.
> 
> # Note:
> I am using native apps(Android/iOS). and I think you saw the issue I opened also

**Comment by darshankawar** [comment] 2023-10-20 10:05
@nzackoya and everyone facing this issue.
Looking at the error log, it seems to be related to network connection and not a bug in cloud_firestore plugin. Network related issues are not in control of flutterfire, as they are a thin wrapper around native Firebase SDKs to send data to and fro through Dart.
You'll probably need to raise this with [Firebase support](https://firebase.google.com/support) for further resolution.

**Comment by nzackoya** [comment] 2023-10-20 10:29
@darshankawar might be not only the server side of the firestore, but also the plugin that is outdated because of a change in server side. Could you please put this issue for investigation anyway.
Already reported a bug to Firebase support, they don't respond for already 2 days, which for this like bug and so many developers and users is really a huge stopper.

**Comment by nzackoya** [comment] 2023-10-20 13:36
@aazorin @AbdElrahman-Rafaat-Amer @Kinomad guys I have already reported this bug to [[Firebase support]](https://firebase.google.com/support)(https://firebase.google.com/support). Please do same to upvote this bug, so google team notice this issue in case they haven't already.

**Comment by AbdElrahman-Rafaat-Amer** [comment] 2023-10-20 16:29
@nzackoya I already reported it yesterday and am waiting for a response from them.

**Comment by Kinomad** [comment] 2023-10-21 07:57
@nzackoya I reported it too and I'm also waiting a response from them

**Comment by JobiJoba** [comment] 2023-10-26 03:54
I've the same issue in Thailand ... sometimes it works, sometimes not ... quite annoying -_-

**Comment by Kinomad** [comment] 2023-11-18 17:58
Hello, nobody have news about this issue when we are connected from Russia or Thailand?

**Comment by Lyokone** [comment] 2024-07-08 08:07
It looks like this is a Network issue not directly related to FlutterFire. Based on similar reports I'll close this one. If you are having this issue, I suggest trying to use a VPN to go around specific network restrictions. 
Feel free to open a new issue if you think this is not related to network.

**Closed by Lyokone** 2024-07-08 08:07 UTC
Labels: type: bug, plugin: cloud_firestore, blocked: firebase-sdk, platform: all
