### ISSUE TITLE
🐛 [flutterfire] Generates a incorrect package name in firebase project when using flavour 

### ISSUE THREAD

**Issue by rddewan** [firebase/flutterfire#11253] opened 2023-07-11 04:02 UTC
## Bug report

I have a flutter project with flavour setup , I am trying to use the flutter fire to setup firebase project but the app add to firebase has the different package name then what I set in flutterfire configure  
```dart

flutterfire configure \
  --project="onlinecatalog-dev" \
  --platforms="ios,android" \
  --out=lib/core/firebase/firebase_options_dev.dart \  
  --ios-bundle-id="com.maqe.onlineCatalog.dev" \
  --android-package-name="com.maqe.onlineCatalog.dev" \
  --debug-symbols-ios \
  --overwrite-firebase-options \
  --yes
```

### Output generated is completely different package name
``` 
i Found 11 Firebase projects. Selecting project onlinecatalog-dev.                                                                                                                                
i Selected platforms: android,ios
i Firebase android app com.maqe.onlineCatalog is not registered on Firebase project onlinecatalog-dev.                                                                                            
i Registered a new Firebase android app on Firebase project onlinecatalog-dev.                                                                                                                    
i Firebase ios app com.maqe.onlineCatalog.qa is not registered on Firebase project onlinecatalog-dev.                                                                                             
i Registered a new Firebase ios app on Firebase project onlinecatalog-dev.                                                                                                                        
✔ Generated FirebaseOptions file lib/core/firebase/firebase_options_dev.dart already exists, do you want to override it? · yes                                                                    

Firebase configuration file lib/core/firebase/firebase_options_dev.dart generated successfully with the following Firebase apps:

Platform  Firebase App Id
android   1:437684753615:android:ae9a208a4c7ac0518c53ba
ios       1:437684753615:ios:a21d69edfabc90e68c53ba
```

### Expected behavior

It should generated a correct package name as passed in `flutterfire configure`

### Sample project

Providing a minimal example project which demonstrates the bug in isolation from your main App _greatly_ enhances the chance of a timely fix.
Please link to the public repository URL.

---

### Flutter doctor

<details><summary>Click To Expand</summary>

```
richard@Richards-MacBook-Pro online_catalog % fvm flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel stable, 3.10.5, on macOS 13.4.1 22F82 darwin-arm64, locale en-TH)
    ! Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart/3.0.3/libexec/bin/dart, which is not inside your current Flutter SDK checkout at /Volumes/External/Users/richard/fvm/versions/3.10.5. Consider adding /Volumes/External/Users/richard/fvm/versions/3.10.5/bin to the front of your path.
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.2)
[✓] VS Code (version 1.80.0)
[✓] Connected device (4 available)
[✓] Network resources
```

</details>

---

**Comment by danagbemava-nc** [comment] 2023-07-11 10:52
Closing this as a duplicate of https://github.com/invertase/flutterfire_cli/issues/14

**Closed by danagbemava-nc** 2023-07-11 10:52 UTC
Labels: type: bug, Needs Attention, in triage
