### ISSUE TITLE
🐛 [cloud_firestore] 4.15.0 notSetQueryParam is invalid type and breaks our build

### ISSUE THREAD

**Issue by danielmahon** [firebase/flutterfire#12240] opened 2024-01-31 22:22 UTC
## Bug report

After upgrading to 4.15.0 `notSetQueryParam` can no longer be accessed by our `models.g.dart` file. It returns an invalid type and breaks the build. Locking version to 4.14.0 fixes the issue.

```
lib/common/domain/models.g.dart:7553:33: Error: The getter 'notSetQueryParam' isn't defined for the class '_$LessonQuery'.
 - '_$LessonQuery' is from 'package:app/common/domain/models.dart' ('lib/common/domain/models.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'notSetQueryParam'.
        isEqualTo: isEqualTo != notSetQueryParam
                                ^^^^^^^^^^^^^^^^
```

### Steps to reproduce

1. Upgrade from 4.14.0 to 4.15.0
2. Rebuild app

### Expected behavior

`notSetQueryParam` is accessible from the generated file

### Additional Info

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 3.16.8, on macOS 14.2.1 23C71 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.85.2)
[✓] VS Code (version 1.83.0-insider)
[✓] Connected device (2 available)
[✓] Network resources
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 3.2.5
Flutter SDK 3.16.8
app 0.0.2+2

dependencies:
- animate_do 3.3.2 [flutter]
- audioplayers 5.2.1 [audioplayers_android audioplayers_darwin audioplayers_linux audioplayers_platform_interface audioplayers_web audioplayers_windows file flutter http meta path_provider synchronized uuid]
- cloud_firestore 4.14.0 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_interface flutter meta]
- cloud_firestore_odm 1.0.0-dev.82 [cloud_firestore flutter json_annotation meta]
- core 0.0.1 [flutter fpdart gap riverpod rxdart]
- cupertino_icons 1.0.6
- dotted_border 2.1.0 [flutter path_drawing]
- file_picker 6.1.1 [flutter flutter_web_plugins flutter_plugin_android_lifecycle plugin_platform_interface ffi path win32]
- firebase_analytics 10.8.1 [firebase_analytics_platform_interface firebase_analytics_web firebase_core firebase_core_platform_interface flutter]
- firebase_auth 4.17.0 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 2.25.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_remote_config 4.3.9 [firebase_core firebase_core_platform_interface firebase_remote_config_platform_interface firebase_remote_config_web flutter]
- firebase_ui_auth 1.12.1 [email_validator firebase_auth firebase_core firebase_dynamic_links firebase_ui_localizations firebase_ui_oauth firebase_ui_shared flutter flutter_localizations meta]
- firebase_ui_oauth_google 1.2.17 [firebase_auth firebase_ui_oauth flutter google_sign_in]
- fl_chart 0.66.1 [equatable flutter]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math web sky_engine]
- flutter_chat_types 3.6.2 [equatable json_annotation meta]
- flutter_chat_ui 1.6.10 [diffutil_dart equatable flutter flutter_chat_types flutter_link_previewer flutter_parsed_text intl meta photo_view scroll_to_index url_launcher visibility_detector]
- flutter_hooks 0.20.4 [flutter]
- flutter_localizations 0.0.0 [flutter intl characters clock collection material_color_utilities meta path vector_math web]
- flutter_markdown 0.6.18+3 [flutter markdown meta path]
- flutter_riverpod 2.4.9 [collection flutter meta riverpod state_notifier]
- flutter_svg 2.0.9 [flutter vector_graphics vector_graphics_codec vector_graphics_compiler]
- flutter_web_plugins 0.0.0 [flutter characters collection material_color_utilities meta vector_math web]
- fpdart 1.1.0
- freezed_annotation 2.4.1 [collection json_annotation meta]
- gap 3.0.1 [flutter]
- go_router 13.1.0 [collection flutter flutter_web_plugins logging meta]
- google_fonts 6.1.0 [flutter http path_provider crypto]
- graphview 1.2.0 [flutter collection]
- grpc 3.2.4 [archive async crypto fixnum googleapis_auth meta http http2 protobuf clock]
- hooks_riverpod 2.4.9 [collection flutter flutter_hooks flutter_riverpod riverpod state_notifier]
- json_annotation 4.8.1 [meta]
- layout 1.0.5 [gap flutter]
- loggy 2.0.3 [stack_trace]
- nanoid 1.0.0
- overlay_support 2.0.1 [flutter async]
- package_info_plus 5.0.1 [ffi flutter flutter_web_plugins http meta path package_info_plus_platform_interface web win32]
- riverpod 2.4.9 [meta stack_trace state_notifier]
- riverpod_annotation 2.3.3 [meta riverpod]
- rxdart 0.27.7
- shimmer 3.0.0 [flutter]
- slang 3.29.0 [collection csv yaml json2yaml watcher]
- slang_flutter 3.29.0 [flutter slang]
- url_launcher 6.2.4 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- video_player 2.8.2 [flutter html video_player_android video_player_avfoundation video_player_platform_interface video_player_web]

dev dependencies:
- build_runner 2.4.8 [analyzer args async build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style frontend_server_client glob graphs http_multi_server io js logging meta mime package_config path pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web_socket_channel yaml]
- cloud_firestore_odm_generator 1.0.0-dev.82 [analyzer build build_config cloud_firestore_odm collection freezed_annotation graphs json_annotation meta recase source_gen source_helper]
- custom_lint 0.5.11 [analyzer analyzer_plugin args async ci cli_util collection freezed_annotation json_annotation meta package_config path pub_semver pubspec_parse rxdart uuid yaml]
- flutter_gen_runner 5.4.0 [flutter_gen_core build collection crypto glob path]
- flutter_launcher_icons 0.13.1 [args checked_yaml cli_util image json_annotation path yaml]
- flutter_lints 3.0.1 [lints]
- flutter_test 0.0.0 [flutter test_api matcher path fake_async clock stack_trace vector_math async boolean_selector characters collection material_color_utilities meta source_span stream_channel string_scanner term_glyph web]
- freezed 2.4.6 [analyzer build build_config collection meta source_gen freezed_annotation json_annotation]
- go_router_builder 2.4.1 [analyzer async build build_config collection meta path source_gen source_helper]
- json_serializable 6.7.1 [analyzer async build build_config collection json_annotation meta path pub_semver pubspec_parse source_gen source_helper]
- network_image_mock 2.1.1 [flutter mockito]
- riverpod_generator 2.3.9 [analyzer build build_config collection crypto meta path riverpod_analyzer_utils riverpod_annotation source_gen]
- riverpod_lint 2.3.7 [analyzer analyzer_plugin collection custom_lint_builder meta path riverpod riverpod_analyzer_utils source_span yaml]
- slang_build_runner 3.29.0 [build glob slang]

dependency overrides:
- analyzer 6.2.0 [_fe_analyzer_shared collection convert crypto glob meta package_config path pub_semver source_span watcher yaml]
- desktop_webview_auth 0.0.13 [crypto flutter http flutter_web_plugins plugin_platform_interface]

transitive dependencies:
- _fe_analyzer_shared 64.0.0 [meta]
- _flutterfire_internals 1.3.17 [collection firebase_core firebase_core_platform_interface flutter meta]
- analyzer_plugin 0.11.3 [analyzer collection dart_style pub_semver yaml]
- archive 3.4.10 [crypto path pointycastle]
- args 2.4.2
- async 2.11.0 [collection meta]
- audioplayers_android 4.0.3 [audioplayers_platform_interface flutter]
- audioplayers_darwin 5.0.2 [audioplayers_platform_interface flutter]
- audioplayers_linux 3.1.0 [audioplayers_platform_interface flutter]
- audioplayers_platform_interface 6.1.0 [flutter meta plugin_platform_interface]
- audioplayers_web 4.1.0 [audioplayers_platform_interface flutter flutter_web_plugins js]
- audioplayers_windows 3.1.0 [audioplayers_platform_interface flutter]
- boolean_selector 2.1.1 [source_span string_scanner]
- build 2.4.1 [analyzer async convert crypto glob logging meta package_config path]
- build_config 1.1.1 [checked_yaml json_annotation path pubspec_parse yaml]
- build_daemon 4.0.1 [built_collection built_value crypto http_multi_server logging path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 2.4.2 [analyzer async build collection convert crypto graphs logging package_config path pool pub_semver stream_transform yaml]
- build_runner_core 7.3.0 [async build build_config build_resolvers collection convert crypto glob graphs json_annotation logging meta package_config path pool timing watcher yaml]
- built_collection 5.1.1
- built_value 8.9.0 [built_collection collection fixnum meta]
- characters 1.3.0
- checked_yaml 2.0.3 [json_annotation source_span yaml]
- ci 0.1.0
- cli_util 0.4.1 [meta path]
- clock 1.1.1
- cloud_firestore_platform_interface 6.1.1 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 3.10.0 [_flutterfire_internals cloud_firestore_platform_interface collection firebase_core firebase_core_web flutter flutter_web_plugins js]
- code_builder 4.10.0 [built_collection built_value collection matcher meta]
- collection 1.18.0
- color 3.0.0
- convert 3.1.1 [typed_data]
- crypto 3.0.3 [typed_data]
- csslib 1.0.0 [source_span]
- csv 5.1.1
- custom_lint_builder 0.5.11 [analyzer analyzer_plugin collection custom_lint custom_lint_core glob hotreloader meta package_config path pubspec_parse rxdart]
- custom_lint_core 0.5.11 [analyzer analyzer_plugin collection custom_lint matcher meta package_config path pubspec_parse source_span yaml]
- dart_style 2.3.4 [analyzer args collection path pub_semver source_span]
- dartx 1.2.0 [characters collection crypto meta path time]
- diffutil_dart 3.0.0
- email_validator 2.1.17
- equatable 2.0.5 [collection meta]
- fake_async 1.3.1 [clock collection]
- ffi 2.1.0
- file 7.0.0 [meta path]
- firebase_analytics_platform_interface 3.9.1 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_analytics_web 0.5.5+13 [_flutterfire_internals firebase_analytics_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- firebase_auth_platform_interface 7.1.0 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 5.9.0 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser js meta web]
- firebase_core_platform_interface 5.0.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.11.0 [firebase_core_platform_interface flutter flutter_web_plugins js meta web]
- firebase_dynamic_links 5.4.9 [firebase_core firebase_core_platform_interface firebase_dynamic_links_platform_interface flutter meta plugin_platform_interface]
- firebase_dynamic_links_platform_interface 0.2.6+17 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_remote_config_platform_interface 1.4.17 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_remote_config_web 1.4.17 [firebase_core firebase_core_web firebase_remote_config_platform_interface flutter flutter_web_plugins js]
- firebase_ui_localizations 1.10.1 [flutter flutter_localizations path]
- firebase_ui_oauth 1.4.17 [desktop_webview_auth firebase_auth firebase_ui_auth firebase_ui_shared flutter_svg flutter]
- firebase_ui_shared 1.4.1 [flutter]
- fixnum 1.1.0
- flutter_gen_core 5.4.0 [path yaml mime xml dartx color collection json_annotation glob dart_style args pub_semver]
- flutter_link_previewer 3.2.2 [flutter flutter_chat_types flutter_linkify html http linkify meta url_launcher]
- flutter_linkify 6.0.0 [flutter linkify]
- flutter_parsed_text 2.2.1 [flutter]
- flutter_plugin_android_lifecycle 2.0.17 [flutter]
- frontend_server_client 3.2.0 [async path]
- glob 2.1.2 [async collection file path string_scanner]
- google_identity_services_web 0.3.0+2 [meta web]
- google_sign_in 6.2.1 [flutter google_sign_in_android google_sign_in_ios google_sign_in_platform_interface google_sign_in_web]
- google_sign_in_android 6.1.21 [flutter google_sign_in_platform_interface]
- google_sign_in_ios 5.7.3 [flutter google_sign_in_platform_interface]
- google_sign_in_platform_interface 2.4.5 [flutter plugin_platform_interface]
- google_sign_in_web 0.12.3+2 [flutter flutter_web_plugins google_identity_services_web google_sign_in_platform_interface http web]
- googleapis_auth 1.4.1 [args crypto http http_parser js]
- graphs 2.3.1 [collection]
- hotreloader 4.1.0 [collection logging path stream_transform vm_service watcher]
- html 0.15.4 [csslib source_span]
- http 1.2.0 [async http_parser meta web]
- http2 2.3.0
- http_multi_server 3.2.1 [async]
- http_parser 4.0.2 [collection source_span string_scanner typed_data]
- image 4.1.4 [archive meta xml]
- intl 0.18.1 [clock meta path]
- io 1.0.4 [meta path string_scanner]
- js 0.6.7 [meta]
- json2yaml 3.0.1 [meta]
- linkify 5.0.0
- lints 3.0.0
- logging 1.2.0
- markdown 7.2.1 [args meta]
- matcher 0.12.16 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.5.0 [collection]
- meta 1.10.0
- mime 1.0.5
- mockito 5.4.4 [analyzer build code_builder collection dart_style matcher meta path source_gen test_api]
- package_config 2.1.0 [path]
- package_info_plus_platform_interface 2.0.1 [flutter meta plugin_platform_interface]
- path 1.8.3
- path_drawing 1.0.1 [vector_math meta path_parsing flutter]
- path_parsing 1.0.1 [vector_math meta]
- path_provider 2.1.2 [flutter path_provider_android path_provider_foundation path_provider_linux path_provider_platform_interface path_provider_windows]
- path_provider_android 2.2.2 [flutter path_provider_platform_interface]
- path_provider_foundation 2.3.2 [flutter path_provider_platform_interface]
- path_provider_linux 2.2.1 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_platform_interface 2.1.2 [flutter platform plugin_platform_interface]
- path_provider_windows 2.2.1 [ffi flutter path path_provider_platform_interface win32]
- petitparser 6.0.2 [meta]
- photo_view 0.14.0 [flutter]
- platform 3.1.4
- plugin_platform_interface 2.1.8 [meta]
- pointycastle 3.7.4 [collection convert js]
- pool 1.5.1 [async stack_trace]
- protobuf 3.1.0 [collection fixnum meta]
- pub_semver 2.1.4 [collection meta]
- pubspec_parse 1.2.3 [checked_yaml collection json_annotation pub_semver yaml]
- recase 4.1.0
- riverpod_analyzer_utils 0.5.0 [analyzer collection crypto custom_lint_core freezed_annotation meta path source_span]
- scroll_to_index 3.0.1 [flutter]
- shelf 1.4.1 [async collection http_parser path stack_trace stream_channel]
- shelf_web_socket 1.0.4 [shelf stream_channel web_socket_channel]
- sky_engine 0.0.99
- source_gen 1.5.0 [analyzer async build dart_style glob path source_span yaml]
- source_helper 1.3.4 [analyzer collection source_gen]
- source_span 1.10.0 [collection path term_glyph]
- sprintf 7.0.0
- stack_trace 1.11.1 [path]
- state_notifier 1.0.0 [meta]
- stream_channel 2.1.2 [async]
- stream_transform 2.1.0
- string_scanner 1.2.0 [source_span]
- synchronized 3.1.0+1
- term_glyph 1.2.1
- test_api 0.6.1 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph]
- time 2.1.4 [clock]
- timing 1.0.1 [json_annotation]
- typed_data 1.3.2 [collection]
- url_launcher_android 6.2.2 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.2.4 [flutter url_launcher_platform_interface]
- url_launcher_linux 3.1.1 [flutter url_launcher_platform_interface]
- url_launcher_macos 3.1.0 [flutter url_launcher_platform_interface]
- url_launcher_platform_interface 2.3.1 [flutter plugin_platform_interface]
- url_launcher_web 2.2.3 [flutter flutter_web_plugins url_launcher_platform_interface web]
- url_launcher_windows 3.1.1 [flutter url_launcher_platform_interface]
- uuid 4.3.3 [crypto sprintf meta fixnum]
- vector_graphics 1.1.9+2 [flutter vector_graphics_codec]
- vector_graphics_codec 1.1.9+2
- vector_graphics_compiler 1.1.9+2 [args meta path_parsing xml vector_graphics_codec path]
- vector_math 2.1.4
- video_player_android 2.4.11 [flutter video_player_platform_interface]
- video_player_avfoundation 2.5.6 [flutter video_player_platform_interface]
- video_player_platform_interface 6.2.2 [flutter plugin_platform_interface]
- video_player_web 2.1.3 [flutter flutter_web_plugins video_player_platform_interface]
- visibility_detector 0.4.0+2 [flutter]
- vm_service 13.0.0
- watcher 1.1.0 [async path]
- web 0.3.0
- web_socket_channel 2.4.0 [async crypto stream_channel]
- win32 5.2.0 [ffi]
- xdg_directories 1.0.4 [meta path]
- xml 6.5.0 [collection meta petitparser]
- yaml 3.1.2 [collection source_span string_scanner]
```

</details>

---

**Comment by darshankawar** [comment] 2024-02-01 10:21
@danielmahon 
Can you provide us a minimal reproducible code sample that shows the reported error ?
I tried plugin example with latest plugin version but it didn't throw the error.

**Comment by mmatook** [comment] 2024-02-04 23:07
I can confirm this bug. 

When using cloud_firestore 4.15.0 and cloud_firestore_odm.

Example:



`
import 'package:json_annotation/json_annotation.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:cloud_firestore_odm/cloud_firestore_odm.dart';

part 'rc_customer_record.g.dart';

@JsonSerializable()
class OtherPurchase {
  OtherPurchase({
    this.purchase_date,
  });

  String? purchase_date;

  factory OtherPurchase.fromJson(Map<String, dynamic> json) =>
      _$OtherPurchaseFromJson(json);
  Map<String, dynamic> toJson() => _$OtherPurchaseToJson(this);
}

@JsonSerializable()
class Entitlement {
  Entitlement({
    this.grace_period_expires_date,
    this.product_identifier,
    this.purchase_date,
  });

  String? expires_date;
  String? product_identifier;
  String? purchase_date;
  String? grace_period_expires_date;

  factory Entitlement.fromJson(Map<String, dynamic> json) =>
      _$EntitlementFromJson(json);

  Map<String, dynamic> toJson() => _$EntitlementToJson(this);
}

@JsonSerializable()
class Subscription {
  Subscription({
    this.auto_resume_date,
    this.cancellation_date,
    this.cancellation_reason,
    this.expires_date,
    this.grace_period_expires_date,
    this.is_sandbox,
    this.original_purchase_date,
    this.ownership_type,
    this.period_type,
    this.purchase_date,
    this.refunded_at,
    this.store,
    this.store_transaction_id,
    this.unsubscribed_at,
  });

  String? auto_resume_date;
  String? cancellation_date;
  String? cancellation_reason;
  String? expires_date;
  String? grace_period_expires_date;
  bool? is_sandbox;
  String? original_purchase_date;
  String? ownership_type;
  String? period_type;
  String? purchase_date;
  String? refunded_at;
  String? store;
  String? store_transaction_id;
  String? unsubscribed_at;

  factory Subscription.fromJson(Map<String, dynamic> json) =>
      _$SubscriptionFromJson(json);

  Map<String, dynamic> toJson() => _$SubscriptionToJson(this);
}

@JsonSerializable()
class NonSubscription {
  NonSubscription({
    this.id,
    this.is_sandbox,
    this.original_purchase_date,
    this.purchase_date,
    this.store,
    this.store_transaction_id,
  });

  String? id;
  bool? is_sandbox;
  String? original_purchase_date;
  String? purchase_date;
  String? store;
  String? store_transaction_id;

  factory NonSubscription.fromJson(Map<String, dynamic> json) =>
      _$NonSubscriptionFromJson(json);

  Map<String, dynamic> toJson() => _$NonSubscriptionToJson(this);
}

const firestoreSerializable = JsonSerializable(
  converters: firestoreJsonConverters,
  // The following values could alternatively be set inside your `build.yaml`
  explicitToJson: false,
  createFieldMap: true,
  createPerFieldToJson: true,
);

@Collection<RcCustomerRecord>('rc_customers')
@firestoreSerializable
class RcCustomerRecord {
  RcCustomerRecord({
    this.aliases,
    this.appId,
    this.original_app_user_id,
    this.first_seen,
    this.last_seen,
    this.management_url,
    this.original_application_version,
    this.original_purchase_date,
    this.entitlements = const {},
    this.non_subscriptions = const {},
    this.subscriptions = const {},
    this.other_purchases = const {},
  });
  List<String>? aliases;
  Map<String, dynamic>? entitlements = {};
  Map<String, dynamic>? non_subscriptions = {};
  Map<String, dynamic>? subscriptions = {};
  Map<String, dynamic>? other_purchases = {};
  String? appId;
  String? original_app_user_id;
  String? first_seen;
  String? last_seen;
  String? management_url;
  String? original_application_version;
  String? original_purchase_date;

  factory RcCustomerRecord.fromJson(Map<String, dynamic> json) =>
      _$RcCustomerRecordFromJson(json);

  Map<String, dynamic> toJson() => _$RcCustomerRecordToJson(this);
}

final rc_customerRef = RcCustomerRecordCollectionReference();
`

produces a generated *.g file.

`
...
 RcCustomerRecordQuery whereFieldPath(
    FieldPath fieldPath, {
    Object? isEqualTo = notSetQueryParam,
    Object? isNotEqualTo = notSetQueryParam,
    Object? isLessThan,
`

With cloud_firestore v4.15.0 notSetQueryParam is an invalid type.

The workaround of locking cloud_firestore v4.14.0 works.
Thanks to @danielmahon for the info.

**Comment by dorklein** [comment] 2024-02-06 13:59
Any solution for this?

**Comment by cuong0993** [comment] 2024-02-06 15:15
Caused by this change https://github.com/firebase/flutterfire/commit/cff6f7674014037688815bdbe3198dd903a4b08e

**Comment by cuong0993** [comment] 2024-02-06 15:32
Ah ODM moved https://github.com/firebase/flutterfire/pull/12140

**Comment by rrousselGit** [comment] 2024-02-06 15:34
I forgot to publish the fix for this. Fixed in -dev.83

And yes, issues should be reported to the new repo now.

**Closed by rrousselGit** 2024-02-06 15:34 UTC
Labels: type: bug, blocked: customer-response, in triage
