### ISSUE TITLE
🐛 [firebase_database] Listener does not fire in emulator.

### ISSUE THREAD

**Issue by jonbhanson** [firebase/flutterfire#11951] opened 2023-11-27 16:41 UTC
## Bug report

I have a realtime database listener that will fire when I use it will the production database, but it does not fire with a local emulator.

### Steps to reproduce

Here is my service class:

```dart
import 'package:firebase_database/firebase_database.dart';

class RealtimeDbService {
  FirebaseDatabase db = FirebaseDatabase.instance;

  RealtimeDbService() {
    // Comment this line out to run on the production database:
    db.useDatabaseEmulator("localhost", 9000);
  }

  void loadUser() {
    db.ref('foo').child('bar').onValue.listen((event) async {
      // In the production database, this listener will execute on a blank database.
      // However, in an emulator this listener does not fire.
      print(event);
    });
  }
}
```

### Expected behavior

I would expect that with blank databases on production and the local emulator, my code would behave the same.  In this case, I would expect the listener to fire in both cases.  However, using the local emulator the listener does not fire.

---

### Flutter doctor

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.0, on macOS 14.1.1 23B81 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.84.2)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!

```

</details>

---

### Flutter dependencies

<details><summary>Click To Expand</summary>

```
Dart SDK 3.2.0
Flutter SDK 3.16.0
health_challenge 1.0.0+1

dependencies:
- app_links 3.4.5 [flutter plugin_platform_interface flutter_web_plugins]
- cloud_firestore 4.12.2 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_interface flutter meta]
- cloud_functions 4.5.3 [cloud_functions_platform_interface cloud_functions_web firebase_core firebase_core_platform_interface flutter]
- collection 1.18.0
- firebase_auth 4.12.1 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 2.23.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_database 10.3.5 [firebase_core firebase_core_platform_interface firebase_database_platform_interface firebase_database_web flutter]
- firebase_messaging 14.7.3 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math web sky_engine]
- flutter_signin_button 2.0.0 [flutter font_awesome_flutter]
- get 4.6.6 [flutter]
- google_sign_in 6.1.5 [flutter google_sign_in_android google_sign_in_ios google_sign_in_platform_interface google_sign_in_web]
- intl 0.18.1 [clock meta path]
- share_plus 7.2.1 [cross_file meta mime flutter flutter_web_plugins share_plus_platform_interface file url_launcher_web url_launcher_windows url_launcher_linux url_launcher_platform_interface ffi win32]
- timeago 3.6.0 [intl]

dev dependencies:
- flutter_lints 3.0.1 [lints]
- flutter_test 0.0.0 [flutter test_api matcher path fake_async clock stack_trace vector_math async boolean_selector characters collection material_color_utilities meta source_span stream_channel string_scanner term_glyph web]

transitive dependencies:
- _fe_analyzer_shared 61.0.0 [meta]
- _flutterfire_internals 1.3.13 [collection firebase_core firebase_core_platform_interface flutter meta]
- analyzer 5.13.0 [_fe_analyzer_shared collection convert crypto glob meta package_config path pub_semver source_span watcher yaml]
- args 2.4.2
- async 2.11.0 [collection meta]
- boolean_selector 2.1.1 [source_span string_scanner]
- characters 1.3.0
- clock 1.1.1
- cloud_firestore_platform_interface 6.0.3 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 3.8.3 [_flutterfire_internals cloud_firestore_platform_interface collection firebase_core firebase_core_web flutter flutter_web_plugins js]
- cloud_functions_platform_interface 5.5.6 [firebase_core flutter meta plugin_platform_interface]
- cloud_functions_web 4.6.6 [cloud_functions_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- convert 3.1.1 [typed_data]
- cross_file 0.3.3+6 [js meta]
- crypto 3.0.3 [typed_data]
- fake_async 1.3.1 [clock collection]
- ffi 2.1.0
- file 7.0.0 [meta path]
- firebase_auth_platform_interface 7.0.3 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 5.8.6 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser js meta]
- firebase_core_platform_interface 5.0.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.8.1 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_database_platform_interface 0.2.5+13 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_database_web 0.2.3+13 [firebase_core firebase_core_web firebase_database_platform_interface flutter flutter_web_plugins js]
- firebase_messaging_platform_interface 4.5.12 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 3.5.12 [_flutterfire_internals firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]
- flutter_web_plugins 0.0.0 [flutter characters collection material_color_utilities meta vector_math web]
- font_awesome_flutter 9.2.0 [flutter]
- glob 2.1.2 [async collection file path string_scanner]
- google_identity_services_web 0.2.2 [js meta]
- google_sign_in_android 6.1.20 [flutter google_sign_in_platform_interface]
- google_sign_in_ios 5.6.4 [flutter google_sign_in_platform_interface pigeon]
- google_sign_in_platform_interface 2.4.2 [flutter plugin_platform_interface quiver]
- google_sign_in_web 0.12.0+5 [flutter flutter_web_plugins google_identity_services_web google_sign_in_platform_interface http js]
- http 1.1.0 [async http_parser meta]
- http_parser 4.0.2 [collection source_span string_scanner typed_data]
- js 0.6.7 [meta]
- lints 3.0.0
- matcher 0.12.16 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.5.0 [collection]
- meta 1.10.0
- mime 1.0.4
- package_config 2.1.0 [path]
- path 1.8.3
- path_provider 2.1.1 [flutter path_provider_android path_provider_foundation path_provider_linux path_provider_platform_interface path_provider_windows]
- path_provider_android 2.2.1 [flutter path_provider_platform_interface]
- path_provider_foundation 2.3.1 [flutter path_provider_platform_interface]
- path_provider_linux 2.2.1 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_platform_interface 2.1.1 [flutter platform plugin_platform_interface]
- path_provider_windows 2.2.1 [ffi flutter path path_provider_platform_interface win32]
- pigeon 11.0.1 [analyzer args collection meta path yaml]
- platform 3.1.3
- plugin_platform_interface 2.1.6 [meta]
- pub_semver 2.1.4 [collection meta]
- quiver 3.2.1 [matcher]
- share_plus_platform_interface 3.3.1 [cross_file flutter meta mime plugin_platform_interface path_provider uuid]
- sky_engine 0.0.99
- source_span 1.10.0 [collection path term_glyph]
- sprintf 7.0.0
- stack_trace 1.11.1 [path]
- stream_channel 2.1.2 [async]
- string_scanner 1.2.0 [source_span]
- term_glyph 1.2.1
- test_api 0.6.1 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph]
- typed_data 1.3.2 [collection]
- url_launcher_linux 3.1.0 [flutter url_launcher_platform_interface]
- url_launcher_platform_interface 2.2.0 [flutter plugin_platform_interface]
- url_launcher_web 2.2.0 [flutter flutter_web_plugins url_launcher_platform_interface]
- url_launcher_windows 3.1.0 [flutter url_launcher_platform_interface]
- uuid 4.1.0 [crypto sprintf]
- vector_math 2.1.4
- watcher 1.1.0 [async path]
- web 0.3.0
- win32 5.0.9 [ffi]
- xdg_directories 1.0.3 [meta path]
- yaml 3.1.2 [collection source_span string_scanner]

```

</details>

---

**Comment by darshankawar** [comment] 2023-11-28 11:52
Thanks for the report @jonbhanson 
Can you take a look at the plugin [example's](https://github.com/firebase/flutterfire/blob/552119c78e2750a929c6226de22f9f6d8df948a4/packages/firebase_database/firebase_database/example/lib/main.dart#L16) usage and implementation of the local emulator and check if using it, you get same behavior or not ?

**Comment by jonbhanson** [comment] 2023-11-29 12:32
I think I figured it out.  in both Firebase Function's [`useFunctionsEmulator`](https://github.com/firebase/flutterfire/blob/1670377e3a17aecff6a93a8db8a17c8095a85c88/packages/cloud_functions/cloud_functions/lib/src/firebase_functions.dart#L103) and Firebase Firestore's [`useFirestoreEmulator`](https://github.com/firebase/flutterfire/blob/1670377e3a17aecff6a93a8db8a17c8095a85c88/packages/cloud_firestore/cloud_firestore/lib/src/firestore.dart#L124) it is possible to pass `localhost` while using an Android emulator as those methods map `localhost` to `10.0.2.2`.  However, Firebase Database's [`useDatabaseEmulator`](https://github.com/firebase/flutterfire/blob/1670377e3a17aecff6a93a8db8a17c8095a85c88/packages/firebase_database/firebase_database/lib/src/firebase_database.dart#L78C18-L78C18) does not remap `localhost`, so my app was not connecting to the database.

**Comment by darshankawar** [comment] 2023-11-30 10:32
Good to know the issue is resolved. Closing as such.


> but it would be nice if the remap feature could be added to the Realtime Database.

You may file a new feature request so that we can address it properly.

**Closed by darshankawar** 2023-11-30 10:32 UTC
Labels: type: bug, Needs Attention, in triage
