### ISSUE TITLE
[firebase_core] Update `initiateOnDeviceConversionMeasurementWithEmailAddress` code sample

### ISSUE THREAD

**Issue by Mercutio1243** [firebase/flutterfire#12231] opened 2024-01-31 09:57 UTC
## Bug report

**Describe the bug**
When using the example project from the repository with android device, I get an exception:

```
Exception has occurred.
UnimplementedError (UnimplementedError: initiateOnDeviceConversionMeasurementWithEmailAddress() is only supported on iOS.)
```

### Steps to reproduce
1) Download and run example project with Android device.
2) tab initiateOnDeviceConversionMeasurement button

### Expected behavior
No error

### Sample project

Example project from repository
---

**Comment by danagbemava-nc** [comment] 2024-01-31 10:37
Hi @Mercutio1243, the error message indicates that the method you're calling is only supported on iSO. In your actual app, you should check if the platform is iOS before you use that method. 

We will have to update the example to do that check.

**Comment by Mercutio1243** [comment] 2024-01-31 10:52
Thanks! I just wanted to use the example project to test my firebase setup, I think it will be helpful, if it avoids these errors.

**Comment by Lyokone** [comment] 2024-03-11 13:56
Closing this since it's expected behavior.

**Closed by Lyokone** 2024-03-11 13:56 UTC
Labels: type: enhancement, plugin: core, platform: ios
