### ISSUE TITLE
🐛 [firebase_auth] Please update intl dependency

### ISSUE THREAD

**Issue by eausch** [firebase/flutterfire#10352] opened 2023-01-31 08:41 UTC
Hello,
I can't update the pub `intl` in my project because `firebase_auth` depends on `intl 0.17.0`. 
```
Because no versions of firebase_auth match >4.2.5 <5.0.0 and firebase_auth 4.2.5 depends on firebase_auth_web ^5.2.4, firebase_auth ^4.2.5 requires firebase_auth_web ^5.2.4.
Because firebase_auth_web 5.2.4 depends on intl ^0.17.0 and no versions of firebase_auth_web match >5.2.4 <6.0.0, firebase_auth_web ^5.2.4 requires intl ^0.17.0.
Thus, firebase_auth ^4.2.5 requires intl ^0.17.0.
So, because app depends on both firebase_auth ^4.2.5 and intl ^0.18.0, version solving failed.
pub get failed
```
Please update the dependency.

**Comment by darshankawar** [comment] 2023-01-31 11:44
Closing as duplicate of https://github.com/firebase/flutterfire/issues/10199. Please see [this](https://github.com/firebase/flutterfire/issues/10199#issuecomment-1368981937) comment for solution.

**Closed by darshankawar** 2023-01-31 11:44 UTC
Labels: type: bug, Needs Attention, in triage
