### ISSUE TITLE
🐛 [google_sign_in] Your issue title here

### ISSUE THREAD

**Issue by VladislavYakonyuk** [firebase/flutterfire#11144] opened 2023-06-16 08:02 UTC
I have a problem when updating versions of firebase with the google_sign_In package (version conflict)

```
[!] CocoaPods could not find compatible versions for pod "GTMSessionFetcher/Core":
  In Podfile:
    firebase_auth (from `.symlinks/plugins/firebase_auth/ios`) was resolved to 4.6.3, which depends on
      Firebase/Auth (= 10.10.0) was resolved to 10.10.0, which depends on
        FirebaseAuth (~> 10.10.0) was resolved to 10.10.0, which depends on
          GTMSessionFetcher/Core (< 4.0, >= 2.1)

    google_sign_in (from `.symlinks/plugins/google_sign_in/ios`) was resolved to 0.0.1, which depends on
      GoogleSignIn (~> 5.0) was resolved to 5.0.2, which depends on
        GTMAppAuth (~> 1.0) was resolved to 1.3.1, which depends on
          GTMSessionFetcher/Core (< 3.0, >= 1.5)

    google_sign_in (from `.symlinks/plugins/google_sign_in/ios`) was resolved to 0.0.1, which depends on
      GoogleSignIn (~> 5.0) was resolved to 5.0.2, which depends on
        GTMSessionFetcher/Core (~> 1.1)
```

My pubscpec.yml

**Comment by darshankawar** [comment] 2023-06-16 10:15
Closing as self-duplicate of https://github.com/firebase/flutterfire/issues/11145

**Closed by darshankawar** 2023-06-16 10:15 UTC
Labels: type: bug, Needs Attention, in triage
