### ISSUE TITLE
🐛 [firebase_crashlytics] causing the macOS to not build in flutter

### ISSUE THREAD

**Issue by ellet0** [firebase/flutterfire#11990] opened 2023-12-07 12:51 UTC
## Bug report

**Describe the bug**
When using `firebase_crashlytics` the app will not build

### Steps to reproduce

1. Create a new flutter project using `flutter create`
2. Add the `firebase_core` and `firebase_crashlytics`
3. Use the FlutterFire CLI to automate adding Firebase project
4. Try to run the project

```console
/Users/ahmedhnewa/development/projects/fresh_notes/macos/Pods/Pods.xcodeproj: warning: The macOS deployment target 'MACOSX_DEPLOYMENT_TARGET' is set to 10.11, but the range of supported deployment target versions is 10.13 to 14.0.99. (in target 'PromisesSwift' from project 'Pods')
/Users/ahmedhnewa/development/projects/fresh_notes/macos/Pods/Pods.xcodeproj: warning: The macOS deployment target 'MACOSX_DEPLOYMENT_TARGET' is set to 10.12, but the range of supported deployment target versions is 10.13 to 14.0.99. (in target 'GoogleDataTransport' from project 'Pods')
/Users/ahmedhnewa/development/projects/fresh_notes/macos/Pods/Pods.xcodeproj: warning: The macOS deployment target 'MACOSX_DEPLOYMENT_TARGET' is set to 10.11, but the range of supported deployment target versions is 10.13 to 14.0.99. (in target 'abseil' from project 'Pods')
warning: Run script build phase 'Create Symlinks to Header Folders' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'abseil' from project 'Pods')
/Users/ahmedhnewa/development/projects/fresh_notes/macos/Pods/Pods.xcodeproj: warning: The macOS deployment target 'MACOSX_DEPLOYMENT_TARGET' is set to 10.12, but the range of supported deployment target versions is 10.13 to 14.0.99. (in target 'GoogleUtilities' from project 'Pods')
/Users/ahmedhnewa/development/projects/fresh_notes/macos/Pods/Pods.xcodeproj: warning: The macOS deployment target 'MACOSX_DEPLOYMENT_TARGET' is set to 10.12, but the range of supported deployment target versions is 10.13 to 14.0.99. (in target 'GTMAppAuth' from project 'Pods')
/Users/ahmedhnewa/development/projects/fresh_notes/macos/Pods/Pods.xcodeproj: warning: The macOS deployment target 'MACOSX_DEPLOYMENT_TARGET' is set to 10.11, but the range of supported deployment target versions is 10.13 to 14.0.99. (in target 'gRPC-Core' from project 'Pods')
warning: Run script build phase 'Create Symlinks to Header Folders' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'gRPC-Core' from project 'Pods')
/Users/ahmedhnewa/development/projects/fresh_notes/macos/Pods/Pods.xcodeproj: warning: The macOS deployment target 'MACOSX_DEPLOYMENT_TARGET' is set to 10.11, but the range of supported deployment target versions is 10.13 to 14.0.99. (in target 'gRPC-C++-gRPCCertificates-Cpp' from project 'Pods')
/Users/ahmedhnewa/development/projects/fresh_notes/macos/Pods/Pods.xcodeproj: warning: The macOS deployment target 'MACOSX_DEPLOYMENT_TARGET' is set to 10.11, but the range of supported deployment target versions is 10.13 to 14.0.99. (in target 'gRPC-C++' from project 'Pods')
warning: Run script build phase 'Create Symlinks to Header Folders' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'gRPC-C++' from project 'Pods')
warning: Run script build phase '[firebase_crashlytics] Crashlytics Upload Symbols' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'Runner' from project 'Runner')
** BUILD FAILED **

Exception: Build process failed
```

6. See error or incorrect behavior

### Expected behavior

It would be nice if we were able to run the app and build it successfully

### Sample project

A [example GitHub repo](https://github.com/freshplatform/fresh-notes)

Clone it and use FlutterFire to add the project and try to run it

---

## Additional context

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 3.16.3, on macOS 14.1.2 23B92 darwin-arm64, locale en-IQ)
    • Flutter version 3.16.3 on channel stable at /Users/ahmedhnewa/development/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b0366e0a3f (33 hours ago), 2023-12-05 19:46:39 -0800
    • Engine revision 54a7145303
    • Dart version 3.2.3
    • DevTools version 2.28.4

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/ahmedhnewa/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_SDK_ROOT = /Users/ahmedhnewa/Library/Android/sdk
    • Java binary at: /Users/ahmedhnewa/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Users/ahmedhnewa/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] IntelliJ IDEA Community Edition (version 2023.3)
    • IntelliJ at /Users/ahmedhnewa/Applications/IntelliJ IDEA Community Edition.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 233.11799.172

[✓] VS Code (version 1.84.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.78.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 14.1.2 23B92 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 110.0.5481.177
    ! Error: Browsing on the local area network for Ahmed’s iPhone. Ensure the device is unlocked and attached with a cable or
      associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Resolving dependencies... 
Got dependencies.
Dart SDK 3.2.3
Flutter SDK 3.16.3
fresh_notes 0.0.1+1

dependencies:
- auto_size_text 3.0.0 [flutter]
- bloc 8.1.2 [meta]
- cached_network_image 3.3.0 [cached_network_image_platform_interface cached_network_image_web flutter flutter_cache_manager octo_image]
- cloud_firestore 4.13.3 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_interface flutter meta]
- connectivity_plus 5.0.2 [flutter flutter_web_plugins connectivity_plus_platform_interface js meta nm]
- cupertino_icons 1.0.6
- equatable 2.0.5 [collection meta]
- firebase_analytics 10.7.2 [firebase_analytics_platform_interface firebase_analytics_web firebase_core firebase_core_platform_interface flutter]
- firebase_app_check 0.2.1+6 [firebase_app_check_platform_interface firebase_app_check_web firebase_core firebase_core_platform_interface flutter]
- firebase_auth 4.15.0 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 2.24.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_storage 11.5.3 [firebase_core firebase_core_platform_interface firebase_storage_platform_interface firebase_storage_web flutter]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math web sky_engine]
- flutter_bloc 8.1.3 [bloc flutter provider]
- flutter_localizations 0.0.0 [flutter intl characters clock collection material_color_utilities meta path vector_math web]
- flutter_quill 9.0.0-dev-7 [flutter flutter_localizations intl collection flutter_colorpicker quiver characters diff_match_patch equatable meta url_launcher flutter_keyboard_visibility device_info_plus super_clipboard]
- flutter_quill_extensions 9.0.0-dev-7 [flutter http path meta universal_html cross_file flutter_quill photo_view video_player youtube_player_flutter url_launcher super_clipboard gal gal_linux image_picker]
- flutter_staggered_grid_view 0.7.0 [flutter]
- freezed_annotation 2.4.1 [collection json_annotation meta]
- fresh_base_package 0.0.1 [flutter]
- gal 2.2.0 [flutter]
- go_router 12.1.1 [collection flutter flutter_web_plugins logging meta]
- google_sign_in 6.1.6 [flutter google_sign_in_android google_sign_in_ios google_sign_in_platform_interface google_sign_in_web]
- hydrated_bloc 9.1.2 [bloc hive meta synchronized]
- image_picker 1.0.4 [flutter image_picker_android image_picker_for_web image_picker_ios image_picker_linux image_picker_macos image_picker_platform_interface image_picker_windows]
- image_picker_android 0.8.8+2 [flutter flutter_plugin_android_lifecycle image_picker_platform_interface]
- intl 0.18.1 [clock meta path]
- json_annotation 4.8.1 [meta]
- logging 1.2.0
- lottie 2.7.0 [archive flutter path vector_math]
- meta 1.10.0
- path 1.8.3
- path_provider 2.1.1 [flutter path_provider_android path_provider_foundation path_provider_linux path_provider_platform_interface path_provider_windows]
- share_plus 7.2.1 [cross_file meta mime flutter flutter_web_plugins share_plus_platform_interface file url_launcher_web url_launcher_windows url_launcher_linux url_launcher_platform_interface ffi win32]
- sign_in_with_apple 5.0.0 [flutter meta sign_in_with_apple_platform_interface sign_in_with_apple_web]
- smooth_page_indicator 1.1.0 [flutter]
- sqflite 2.3.0 [flutter sqflite_common path]

dev dependencies:
- auto_screenshot 0.0.2 [checked_yaml collection flutter_test integration_test json_annotation path yaml]
- build_runner 2.4.7 [analyzer args async build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style frontend_server_client glob graphs http_multi_server io js logging meta mime package_config path pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web_socket_channel yaml]
- flutter_gen_runner 5.3.2 [flutter_gen_core build collection crypto glob path]
- flutter_lints 3.0.1 [lints]
- flutter_quill_test 9.0.0-dev-7 [flutter flutter_quill flutter_test]
- flutter_test 0.0.0 [flutter test_api matcher path fake_async clock stack_trace vector_math async boolean_selector characters collection material_color_utilities meta source_span stream_channel string_scanner term_glyph web]
- freezed 2.4.5 [analyzer build build_config collection meta source_gen freezed_annotation json_annotation]
- icons_launcher 2.1.6 [args image path universal_io yaml]
- json_serializable 6.7.1 [analyzer async build build_config collection json_annotation meta path pub_semver pubspec_parse source_gen source_helper]
- test 1.24.9 [analyzer async boolean_selector collection coverage http_multi_server io js matcher node_preamble package_config path pool shelf shelf_packages_handler shelf_static shelf_web_socket source_span stack_trace stream_channel test_api test_core typed_data web_socket_channel webkit_inspection_protocol yaml]

dependency overrides:
- flutter_quill 9.0.0-dev-7 [flutter flutter_localizations intl collection flutter_colorpicker quiver characters diff_match_patch equatable meta url_launcher flutter_keyboard_visibility device_info_plus super_clipboard]
- flutter_quill_extensions 9.0.0-dev-7 [flutter http path meta universal_html cross_file flutter_quill photo_view video_player youtube_player_flutter url_launcher super_clipboard gal gal_linux image_picker]
- flutter_quill_test 9.0.0-dev-7 [flutter flutter_quill flutter_test]

transitive dependencies:
- _fe_analyzer_shared 64.0.0 [meta]
- _flutterfire_internals 1.3.14 [collection firebase_core firebase_core_platform_interface flutter meta]
- analyzer 6.2.0 [_fe_analyzer_shared collection convert crypto glob meta package_config path pub_semver source_span watcher yaml]
- archive 3.4.9 [crypto path pointycastle]
- args 2.4.2
- async 2.11.0 [collection meta]
- boolean_selector 2.1.1 [source_span string_scanner]
- build 2.4.1 [analyzer async convert crypto glob logging meta package_config path]
- build_config 1.1.1 [checked_yaml json_annotation path pubspec_parse yaml]
- build_daemon 4.0.1 [built_collection built_value crypto http_multi_server logging path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 2.4.1 [analyzer async build collection convert crypto graphs logging package_config path pool pub_semver stream_transform yaml]
- build_runner_core 7.2.11 [async build build_config build_resolvers collection convert crypto glob graphs json_annotation logging meta package_config path pool timing watcher yaml]
- built_collection 5.1.1
- built_value 8.8.0 [built_collection collection fixnum meta]
- cached_network_image_platform_interface 3.0.0 [flutter flutter_cache_manager]
- cached_network_image_web 1.1.0 [cached_network_image_platform_interface flutter flutter_cache_manager]
- characters 1.3.0
- charcode 1.3.1
- checked_yaml 2.0.3 [json_annotation source_span yaml]
- clock 1.1.1
- cloud_firestore_platform_interface 6.0.7 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 3.8.7 [_flutterfire_internals cloud_firestore_platform_interface collection firebase_core firebase_core_web flutter flutter_web_plugins js]
- code_builder 4.8.0 [built_collection built_value collection matcher meta]
- collection 1.18.0
- color 3.0.0
- connectivity_plus_platform_interface 1.2.4 [flutter meta plugin_platform_interface]
- convert 3.1.1 [typed_data]
- coverage 1.6.4 [args logging package_config path source_maps stack_trace vm_service]
- cross_file 0.3.3+8 [meta web]
- crypto 3.0.3 [typed_data]
- csslib 1.0.0 [source_span]
- dart_style 2.3.4 [analyzer args collection path pub_semver source_span]
- dartx 1.2.0 [characters collection crypto meta path time]
- dbus 0.7.10 [args ffi meta xml]
- device_info_plus 9.1.1 [device_info_plus_platform_interface ffi file flutter flutter_web_plugins meta win32 win32_registry]
- device_info_plus_platform_interface 7.0.0 [flutter meta plugin_platform_interface]
- diff_match_patch 0.4.1
- fake_async 1.3.1 [clock collection]
- ffi 2.1.0
- file 6.1.4 [meta path]
- file_selector_linux 0.9.2+1 [cross_file file_selector_platform_interface flutter]
- file_selector_macos 0.9.3+3 [cross_file file_selector_platform_interface flutter]
- file_selector_platform_interface 2.6.1 [cross_file flutter http plugin_platform_interface]
- file_selector_windows 0.9.3+1 [cross_file file_selector_platform_interface flutter]
- firebase_analytics_platform_interface 3.8.2 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_analytics_web 0.5.5+9 [_flutterfire_internals firebase_analytics_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- firebase_app_check_platform_interface 0.1.0+8 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_app_check_web 0.1.0+8 [_flutterfire_internals firebase_app_check_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- firebase_auth_platform_interface 7.0.6 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 5.8.9 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser js meta]
- firebase_core_platform_interface 5.0.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.9.0 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_storage_platform_interface 5.1.1 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_storage_web 3.6.15 [_flutterfire_internals async firebase_core firebase_core_web firebase_storage_platform_interface flutter flutter_web_plugins http js meta]
- fixnum 1.1.0
- flutter_cache_manager 3.3.1 [clock collection file flutter http path path_provider rxdart sqflite uuid]
- flutter_colorpicker 1.0.3 [flutter]
- flutter_driver 0.0.0 [file flutter flutter_test fuchsia_remote_debug_protocol path meta vm_service webdriver async boolean_selector characters clock collection matcher material_color_utilities platform process source_span stack_trace stream_channel string_scanner sync_http term_glyph test_api vector_math web]
- flutter_gen_core 5.3.2 [path yaml mime xml dartx color collection json_annotation glob dart_style args pub_semver]
- flutter_inappwebview 5.8.0 [flutter]
- flutter_keyboard_visibility 5.4.1 [meta flutter_keyboard_visibility_platform_interface flutter_keyboard_visibility_linux flutter_keyboard_visibility_macos flutter_keyboard_visibility_web flutter_keyboard_visibility_windows flutter]
- flutter_keyboard_visibility_linux 1.0.0 [flutter_keyboard_visibility_platform_interface flutter]
- flutter_keyboard_visibility_macos 1.0.0 [flutter_keyboard_visibility_platform_interface flutter]
- flutter_keyboard_visibility_platform_interface 2.0.0 [flutter meta plugin_platform_interface]
- flutter_keyboard_visibility_web 2.0.0 [flutter_keyboard_visibility_platform_interface flutter_web_plugins flutter]
- flutter_keyboard_visibility_windows 1.0.0 [flutter_keyboard_visibility_platform_interface flutter]
- flutter_plugin_android_lifecycle 2.0.17 [flutter]
- flutter_web_plugins 0.0.0 [flutter characters collection material_color_utilities meta vector_math web]
- frontend_server_client 3.2.0 [async path]
- fuchsia_remote_debug_protocol 0.0.0 [process vm_service file meta path platform]
- gal_linux 0.0.1-dev-3 [flutter gal path]
- glob 2.1.2 [async collection file path string_scanner]
- google_identity_services_web 0.2.2 [js meta]
- google_sign_in_android 6.1.20 [flutter google_sign_in_platform_interface]
- google_sign_in_ios 5.6.3 [flutter google_sign_in_platform_interface]
- google_sign_in_platform_interface 2.4.2 [flutter plugin_platform_interface quiver]
- google_sign_in_web 0.12.2+1 [flutter flutter_web_plugins google_identity_services_web google_sign_in_platform_interface http js]
- graphs 2.3.1 [collection]
- hive 2.2.3 [meta crypto]
- html 0.15.4 [csslib source_span]
- http 1.1.2 [async http_parser meta web]
- http_multi_server 3.2.1 [async]
- http_parser 4.0.2 [collection source_span string_scanner typed_data]
- image 4.1.3 [archive meta xml]
- image_picker_for_web 3.0.1 [flutter flutter_web_plugins image_picker_platform_interface mime]
- image_picker_ios 0.8.8+4 [flutter image_picker_platform_interface]
- image_picker_linux 0.2.1+1 [file_selector_linux file_selector_platform_interface flutter image_picker_platform_interface]
- image_picker_macos 0.2.1+1 [file_selector_macos file_selector_platform_interface flutter image_picker_platform_interface]
- image_picker_platform_interface 2.9.1 [cross_file flutter http plugin_platform_interface]
- image_picker_windows 0.2.1+1 [file_selector_platform_interface file_selector_windows flutter image_picker_platform_interface]
- integration_test 0.0.0 [flutter flutter_driver flutter_test path vm_service async boolean_selector characters clock collection fake_async file matcher material_color_utilities meta source_span stack_trace stream_channel string_scanner sync_http term_glyph test_api vector_math web webdriver]
- io 1.0.4 [meta path string_scanner]
- irondash_engine_context 0.4.0 [flutter plugin_platform_interface]
- irondash_message_channel 0.3.1 [flutter ffi]
- js 0.6.7 [meta]
- lints 3.0.0
- matcher 0.12.16 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.5.0 [collection]
- mime 1.0.4
- nested 1.0.0 [flutter]
- nm 0.5.0 [dbus]
- node_preamble 2.0.2
- octo_image 2.0.0 [flutter]
- package_config 2.1.0 [path]
- path_provider_android 2.2.1 [flutter path_provider_platform_interface]
- path_provider_foundation 2.3.1 [flutter path_provider_platform_interface]
- path_provider_linux 2.2.1 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_platform_interface 2.1.1 [flutter platform plugin_platform_interface]
- path_provider_windows 2.2.1 [ffi flutter path path_provider_platform_interface win32]
- petitparser 6.0.2 [meta]
- photo_view 0.14.0 [flutter]
- pixel_snap 0.1.4 [flutter]
- platform 3.1.2
- plugin_platform_interface 2.1.7 [meta]
- pointycastle 3.7.3 [collection convert js]
- pool 1.5.1 [async stack_trace]
- process 4.2.4 [file path platform]
- provider 6.1.1 [collection flutter nested]
- pub_semver 2.1.4 [collection meta]
- pubspec_parse 1.2.3 [checked_yaml collection json_annotation pub_semver yaml]
- quiver 3.2.1 [matcher]
- rxdart 0.27.7
- share_plus_platform_interface 3.3.1 [cross_file flutter meta mime plugin_platform_interface path_provider uuid]
- shelf 1.4.1 [async collection http_parser path stack_trace stream_channel]
- shelf_packages_handler 3.0.2 [path shelf shelf_static]
- shelf_static 1.1.2 [convert http_parser mime path shelf]
- shelf_web_socket 1.0.4 [shelf stream_channel web_socket_channel]
- sign_in_with_apple_platform_interface 1.0.0 [flutter plugin_platform_interface meta]
- sign_in_with_apple_web 1.0.1 [flutter flutter_web_plugins sign_in_with_apple_platform_interface js]
- sky_engine 0.0.99
- source_gen 1.4.0 [analyzer async build dart_style glob path source_span yaml]
- source_helper 1.3.4 [analyzer collection source_gen]
- source_map_stack_trace 2.1.1 [path source_maps stack_trace]
- source_maps 0.10.12 [source_span]
- source_span 1.10.0 [collection path term_glyph]
- sprintf 7.0.0
- sqflite_common 2.5.0+2 [synchronized path meta]
- stack_trace 1.11.1 [path]
- stream_channel 2.1.2 [async]
- stream_transform 2.1.0
- string_scanner 1.2.0 [source_span]
- super_clipboard 0.7.3 [flutter collection meta super_native_extensions]
- super_native_extensions 0.7.3 [flutter flutter_web_plugins meta ffi collection js path uuid irondash_engine_context irondash_message_channel device_info_plus pixel_snap]
- sync_http 0.3.1
- synchronized 3.1.0
- term_glyph 1.2.1
- test_api 0.6.1 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph]
- test_core 0.5.9 [analyzer args async boolean_selector collection coverage frontend_server_client glob io meta package_config path pool source_map_stack_trace source_maps source_span stack_trace stream_channel test_api vm_service yaml]
- time 2.1.3 [clock]
- timing 1.0.1 [json_annotation]
- typed_data 1.3.2 [collection]
- universal_html 2.2.4 [async csslib charcode collection html meta source_span typed_data universal_io]
- universal_io 2.2.2 [collection meta typed_data]
- url_launcher 6.2.1 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- url_launcher_android 6.2.0 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.2.1 [flutter url_launcher_platform_interface]
- url_launcher_linux 3.1.0 [flutter url_launcher_platform_interface]
- url_launcher_macos 3.1.0 [flutter url_launcher_platform_interface]
- url_launcher_platform_interface 2.2.0 [flutter plugin_platform_interface]
- url_launcher_web 2.2.1 [flutter flutter_web_plugins url_launcher_platform_interface web]
- url_launcher_windows 3.1.0 [flutter url_launcher_platform_interface]
- uuid 4.2.1 [crypto sprintf meta]
- vector_math 2.1.4
- video_player 2.8.1 [flutter html video_player_android video_player_avfoundation video_player_platform_interface video_player_web]
- video_player_android 2.4.10 [flutter video_player_platform_interface]
- video_player_avfoundation 2.5.2 [flutter video_player_platform_interface]
- video_player_platform_interface 6.2.1 [flutter plugin_platform_interface]
- video_player_web 2.1.2 [flutter flutter_web_plugins video_player_platform_interface]
- vm_service 11.10.0
- watcher 1.1.0 [async path]
- web 0.3.0
- web_socket_channel 2.4.0 [async crypto stream_channel]
- webdriver 3.0.2 [matcher path stack_trace sync_http]
- webkit_inspection_protocol 1.2.1 [logging]
- win32 5.1.1 [ffi]
- win32_registry 1.1.2 [ffi win32]
- xdg_directories 1.0.3 [meta path]
- xml 6.5.0 [collection meta petitparser]
- yaml 3.1.2 [collection source_span string_scanner]
- youtube_player_flutter 8.1.2 [flutter flutter_inappwebview]
```

</details>

---

**Comment by burnermanx** [comment] 2023-12-07 20:16
Do you have an error log? I'm facing same problem, maybe.

When I try to build I'm receiving this error:
```
'IPHONEOS_DEPLOYMENT_TARGET' is set to 11.0, but the range of supported deployment target versions is 12.0 to 17.0.99. (In target 'Flutter' from object 'Pods')
```

**Comment by freshtechtips** [comment] 2023-12-07 20:39
> Do you have an error log? I'm facing same problem, maybe.
> 
> When I try to build I'm receiving this error:
> ```
> 'IPHONEOS_DEPLOYMENT_TARGET' is set to 11.0, but the range of supported deployment target versions is 12.0 to 17.0.99. (In target 'Flutter' from object 'Pods')
> ```
> 
> Try to use flutter run or build with `-v` modifier.

Hi. The error you are facing is easy to fix
You will have to increase the minimum version in podfile and Xcode project

**Comment by darshankawar** [comment] 2023-12-08 10:13
Thanks for the report @freshtechtips 
Can you take a look at [this](https://github.com/firebase/flutterfire/issues/9799#issuecomment-1300424854) solution and check if it helps in your case to resolve the issue ?

**Comment by freshtechtips** [comment] 2023-12-12 12:47
When building using Xcode: 

![image](https://github.com/firebase/flutterfire/assets/73608287/f1da19df-0f9d-4ffd-a59a-f0341b97bba9)

It doesn't show any errors at all and it's not related to the warrnings

**Comment by darshankawar** [comment] 2023-12-13 10:58
I got below errors:

<img width="386" alt="Screenshot 2023-12-13 at 4 27 34 PM" src="https://github.com/firebase/flutterfire/assets/67046386/5be5f03b-2e2e-4272-a69a-798ec7651a44">

**Comment by freshtechtips** [comment] 2023-12-13 10:59
> I got below errors:
> 
> <img width="386" alt="Screenshot 2023-12-13 at 4 27 34 PM" src="https://github.com/firebase/flutterfire/assets/67046386/5be5f03b-2e2e-4272-a69a-798ec7651a44">
> 

Are you using the latest version of Xcode?? Because I didn't face that error

**Comment by darshankawar** [comment] 2023-12-13 11:06
No, I am on 13.2.1

**Comment by freshtechtips** [comment] 2023-12-13 11:19
> No, I am on 13.2.1

This project always uses the latest versions

If I'm unable to help you reproduce the error and you can't fix it

We can close it

I'm sure there will be another person that will report with more info

**Comment by darshankawar** [comment] 2023-12-14 10:16
Closing the issue may not be an ideal solution and without any way of reproducing the issue, we can only assume it's a configuration issue. Can you try to run flutterfire CLI again using the latest dev release?

```
dart pub global activate flutterfire_cli 0.3.0-dev.18 --overwrite
flutterfire configure
```

**Comment by freshtechtips** [comment] 2023-12-14 12:52
> Closing the issue may not be an ideal solution and without any way of reproducing the issue, we can only assume it's a configuration issue. Can you try to run flutterfire CLI again using the latest dev release?
> 
> ```
> dart pub global activate flutterfire_cli 0.3.0-dev.18 --overwrite
> flutterfire configure
> ```

Sure thing, thank you for your understanding

**Comment by freshtechtips** [comment] 2023-12-14 13:28
Still getting the exact same build error

![image](https://github.com/firebase/flutterfire/assets/73608287/7bd7aa62-51f0-4142-b1f1-4c80c884e5f5)

Please notice that after adding the `firebase_crashlytics` the macOS app will not build even after removing it, the only solution is to recreate the macOS project or remove anything related to firebase_crashlytics

![image](https://github.com/firebase/flutterfire/assets/73608287/241adbc0-b010-45c7-85ee-af754ef36217)

**Comment by darshankawar** [comment] 2023-12-15 11:00
@freshtechtips 
From the original description error log you shared, I see below entries in it:

`Pods/Pods.xcodeproj` so want to confirm if you are opening Runner.xcworkspace or Runner.xcodeproj ?

**Comment by freshtechtips** [comment] 2023-12-15 11:03
> @freshtechtips 
> From the original description error log you shared, I see below entries in it:
> 
> `Pods/Pods.xcodeproj` so want to confirm if you are opening Runner.xcworkspace or Runner.xcodeproj ?

No, I'm just running from Flutter Run directly 

The unknown build error also happens when build in Xcode ane open using Xcworkspace

Do you want to use anydesk and debug it on my machine so you see more details about the bug?

**Comment by darshankawar** [comment] 2023-12-18 11:42
I am unable to replicate the reported issue, but keeping this open for team's input / tracking.

**Comment by russellwheatley** [comment] 2023-12-19 10:07
I'm fairly sure it is a result of this problem that has been fixed and merged in the FlutterFire CLI: https://github.com/invertase/flutterfire_cli/pull/245

However, it has not been released yet. Please follow this channel https://github.com/invertase/flutterfire_cli/issues/14.
 We will announce the latest FlutterFire version in that channel which you can use to configure your project that ought to fix your problem 👍

**Closed by russellwheatley** 2023-12-19 10:07 UTC
Labels: type: bug, plugin: crashlytics, platform: macos
