### ISSUE TITLE
🐛 [firebase_messaging] Firebase Installations Service is unavailable. Please try again later. and Topic sync or token retrieval failed on hard failure exceptions: FIS_AUTH_ERROR. Won't retry the operation.

### ISSUE THREAD

**Issue by HencyPithadiya** [firebase/flutterfire#10242] opened 2023-01-10 06:29 UTC
```
E/FirebaseInstanceId( 6476): 	at java.lang.Thread.run(Thread.java:923)
E/FirebaseInstanceId( 6476): Caused by: com.google.firebase.installations.FirebaseInstallationsException: Firebase Installations Service is unavailable. Please try again later.
E/FirebaseInstanceId( 6476): 	at com.google.firebase.installations.remote.FirebaseInstallationServiceClient.createFirebaseInstallation(FirebaseInstallationServiceClient.java:208)
E/FirebaseInstanceId( 6476): 	at com.google.firebase.installations.FirebaseInstallations.registerFidWithServer(FirebaseInstallations.java:536)
E/FirebaseInstanceId( 6476): 	at com.google.firebase.installations.FirebaseInstallations.doNetworkCallIfNecessary(FirebaseInstallations.java:390)
E/FirebaseInstanceId( 6476): 	at com.google.firebase.installations.FirebaseInstallations.lambda$doRegistrationOrRefresh$3$com-google-firebase-installations-FirebaseInstallations(FirebaseInstallations.java:375)
E/FirebaseInstanceId( 6476): 	at com.google.firebase.installations.FirebaseInstallations$$ExternalSyntheticLambda2.run(Unknown Source:4)
E/FirebaseInstanceId( 6476): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/FirebaseInstanceId( 6476): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/FirebaseInstanceId( 6476): 	... 1 more

(HTTPLog)-Static: isSBSettingEnabled false
E/FirebaseInstanceId( 6476): Topic sync or token retrieval failed on hard failure exceptions: FIS_AUTH_ERROR. Won't retry the operation.
E/flutter ( 6476): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: [firebase_messaging/unknown] java.io.IOException: FIS_AUTH_ERROR
E/flutter ( 6476): #0      StandardMethodCodec.decodeEnvelope
package:flutter/…/services/message_codecs.dart:653
E/flutter ( 6476): #1      MethodChannel._invokeMethod
package:flutter/…/services/platform_channel.dart:296
E/flutter ( 6476): <asynchronous suspension>
E/flutter ( 6476): #2      MethodChannel.invokeMapMethod
package:flutter/…/services/platform_channel.dart:499
E/flutter ( 6476): <asynchronous suspension>
E/flutter ( 6476): #3      MethodChannelFirebaseMessaging.getToken
package:firebase_messaging_platform_interface/…/method_channel/method_channel_messaging.dart:224
E/flutter ( 6476): <asynchronous suspension>

```

**Comment by darshankawar** [comment] 2023-01-10 11:49
@HencyPithadiya 
You can try the following steps to see if this may help with the error:

- This may be caused by having the wrong configuration file in your app (for example, if you switched Firebase projects). You can try doing Build > Clean Project then Build > Rebuild Project to make sure that the build cache is clean and the correct config file is used.
- Make sure your device or emulator has Google Play Services added.
- Make sure your device or emulator is connected to wifi or any ISP.

In addition, these references may provide more insights about this issue:

[E/FirebaseInstanceId: Failed to get FIS auth token](https://stackoverflow.com/questions/60635672/e-firebaseinstanceid-failed-to-get-fis-auth-token)
[Android Error when communicating with the Firebase Installations server API](https://stackoverflow.com/questions/61453640/android-error-when-communicating-with-the-firebase-installations-server-api)
https://github.com/FirebaseExtended/flutterfire/issues/3163

Closing from here, as this is a plugin issue, but could be setup / config or server issue. You may also reach out to [firebase support](https://firebase.google.com/support) for further resolution.

**Closed by darshankawar** 2023-01-10 11:49 UTC
Labels: type: bug, Needs Attention, in triage
