### ISSUE TITLE
[PLUGIN_NAME_HERE]: <YOUR TITLE HERE>

### ISSUE THREAD

**Issue by tamiljasmi** [firebase/flutterfire#13399] opened 2024-09-25 09:49 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Other

### Which platforms are affected?

iOS

### Description

Here is Flutter Doctor derails.
options.
lathamac@lathamac ~ % flutter doctor  
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.3, on macOS 15.0 24A335 darwin-x64, locale
    en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
[✓] Chrome - develop for the web
[!] Android Studio (not installed)
[✓] VS Code (version 1.93.1)
[✓] Connected device (3 available)
[✓] Network resources

! Doctor found issues in 1 category.
----------------------------------------------------
When i run the project facing issue.

Launching lib/main.dart on iPhone 16 Plus in debug mode...
Xcode build done.                                           18.4s
Failed to build iOS app
Lexical or Preprocessor Issue (Xcode): Include of non-modular header inside framework module 'firebase_auth.FLTAuthStateChannelStreamHandler': '/Users/lathamac/moisystem/ios/Pods/Headers/Public/Firebase/Firebase.h'
/Users/lathamac/.pub-cache/hosted/pub.dev/firebase_auth-5.3.0/ios/Classes/Private/FLTAuthStateChannelStreamHandler.h:12:8
Please assist how to fix the issue.

### Reproducing the issue

Full error details

Launching lib/main.dart on iPhone 16 Plus in debug mode...
Xcode build done.                                           18.4s
Failed to build iOS app
Lexical or Preprocessor Issue (Xcode): Include of non-modular header inside framework module 'firebase_auth.FLTAuthStateChannelStreamHandler': '/Users/lathamac/moisystem/ios/Pods/Headers/Public/Firebase/Firebase.h'
/Users/lathamac/.pub-cache/hosted/pub.dev/firebase_auth-5.3.0/ios/Classes/Private/FLTAuthStateChannelStreamHandler.h:12:8

Lexical or Preprocessor Issue (Xcode): Include of non-modular header inside framework module 'firebase_auth.PigeonParser': '/Users/lathamac/moisystem/ios/Pods/Headers/Public/Firebase/Firebase.h'
/Users/lathamac/.pub-cache/hosted/pub.dev/firebase_auth-5.3.0/ios/Classes/Private/PigeonParser.h:6:8

Lexical or Preprocessor Issue (Xcode): Include of non-modular header inside framework module 'firebase_auth.FLTIdTokenChannelStreamHandler': '/Users/lathamac/moisystem/ios/Pods/Headers/Public/Firebase/Firebase.h'
/Users/lathamac/.pub-cache/hosted/pub.dev/firebase_auth-5.3.0/ios/Classes/Private/FLTIdTokenChannelStreamHandler.h:12:8

Lexical or Preprocessor Issue (Xcode): Include of non-modular header inside framework module 'firebase_auth.FLTPhoneNumberVerificationStreamHandler': '/Users/lathamac/moisystem/ios/Pods/Headers/Public/Firebase/Firebase.h'
/Users/lathamac/.pub-cache/hosted/pub.dev/firebase_auth-5.3.0/ios/Classes/Private/FLTPhoneNumberVerificationStreamHandler.h:12:8

Lexical or Preprocessor Issue (Xcode): Include of non-modular header inside framework module 'firebase_auth.FLTFirebaseAuthPlugin': '/Users/lathamac/moisystem/ios/Pods/Headers/Public/Firebase/Firebase.h'
/Users/lathamac/.pub-cache/hosted/pub.dev/firebase_auth-5.3.0/ios/Classes/Public/FLTFirebaseAuthPlugin.h:6:8

Could not build the application for the simulator.
Error launching application on iPhone 16 Plus.

Exited (1).

### Firebase Core version

3.5.0

### Flutter Version

3.24.3

### Relevant Log Output

```shell
Launching lib/main.dart on iPhone 16 Plus in debug mode...
Xcode build done.                                           18.4s
Failed to build iOS app
Lexical or Preprocessor Issue (Xcode): Include of non-modular header inside framework module 'firebase_auth.FLTAuthStateChannelStreamHandler': '/Users/lathamac/moisystem/ios/Pods/Headers/Public/Firebase/Firebase.h'
/Users/lathamac/.pub-cache/hosted/pub.dev/firebase_auth-5.3.0/ios/Classes/Private/FLTAuthStateChannelStreamHandler.h:12:8

Lexical or Preprocessor Issue (Xcode): Include of non-modular header inside framework module 'firebase_auth.PigeonParser': '/Users/lathamac/moisystem/ios/Pods/Headers/Public/Firebase/Firebase.h'
/Users/lathamac/.pub-cache/hosted/pub.dev/firebase_auth-5.3.0/ios/Classes/Private/PigeonParser.h:6:8

Lexical or Preprocessor Issue (Xcode): Include of non-modular header inside framework module 'firebase_auth.FLTIdTokenChannelStreamHandler': '/Users/lathamac/moisystem/ios/Pods/Headers/Public/Firebase/Firebase.h'
/Users/lathamac/.pub-cache/hosted/pub.dev/firebase_auth-5.3.0/ios/Classes/Private/FLTIdTokenChannelStreamHandler.h:12:8

Lexical or Preprocessor Issue (Xcode): Include of non-modular header inside framework module 'firebase_auth.FLTPhoneNumberVerificationStreamHandler': '/Users/lathamac/moisystem/ios/Pods/Headers/Public/Firebase/Firebase.h'
/Users/lathamac/.pub-cache/hosted/pub.dev/firebase_auth-5.3.0/ios/Classes/Private/FLTPhoneNumberVerificationStreamHandler.h:12:8

Lexical or Preprocessor Issue (Xcode): Include of non-modular header inside framework module 'firebase_auth.FLTFirebaseAuthPlugin': '/Users/lathamac/moisystem/ios/Pods/Headers/Public/Firebase/Firebase.h'
/Users/lathamac/.pub-cache/hosted/pub.dev/firebase_auth-5.3.0/ios/Classes/Public/FLTFirebaseAuthPlugin.h:6:8

Could not build the application for the simulator.
Error launching application on iPhone 16 Plus.

Exited (1).
```

### Flutter dependencies

here is Pubspec.yaml file code

name: moisystem
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.5.3

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  firebase_core: ^3.5.0
  firebase_auth: ^5.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package

### Additional context and comments

No issue when i never use  firebase_auth: ^5.3.0 on pubspec.yaml.

The error is appear when entered f firebase_auth: ^5.3.0.

**Comment by SelaseKay** [comment] 2024-09-25 10:11
Duplicate of: [13323](https://github.com/firebase/flutterfire/issues/13323)

**Closed by SelaseKay** 2024-09-25 10:11 UTC
Labels: type: bug, Needs Attention
