### ISSUE TITLE
🐛 [firebase_messaging] FirebaseException ([firebase_messaging/unknown] 

### ISSUE THREAD

**Issue by RoyalCoder88** [firebase/flutterfire#9904] opened 2022-11-10 17:02 UTC
Hi just updated **firebase_messaging** to  14.1.0, and now I'm getting an android java exception

**Error:**
```
Exception has occurred.
FirebaseException ([firebase_messaging/unknown] Attempt to invoke virtual method 'java.lang.Object android.content.Context.getSystemService(java.lang.String)' on a null object reference)
```
![Screenshot 2022-11-10 165048](https://user-images.githubusercontent.com/6507433/201159775-89f635ac-3b94-4708-b942-527355829ede.png)

**My use case:**

```
  setnotification() async {
    FirebaseMessaging messaging = FirebaseMessaging.instance;

    NotificationSettings settings = await messaging.requestPermission(
      alert: true,
      announcement: false,
      badge: true,
      carPlay: false,
      criticalAlert: false,
      provisional: false,
      sound: true,
    );

    if (settings.authorizationStatus == AuthorizationStatus.authorized) {
    } else if (settings.authorizationStatus ==
    } else {}
  }
```

**My flutter doctor:**

```
[√] Flutter (Channel stable, 3.3.7, on Microsoft Windows [Version 10.0.22621.819], locale en-GB)
    • Flutter version 3.3.7 on channel stable at C:\tools\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e99c9c7cd9 (9 days ago), 2022-11-01 16:59:00 -0700
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\burac\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.11.19)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    • Visual Studio Build Tools 2019 version 16.11.32901.82
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[√] VS Code (version 1.73.1)
    • VS Code at C:\Users\burac\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.52.0

[√] Connected device (4 available)
    • SM A908B (mobile) • RFCMA02W5WT • android-arm64  • Android 12 (API 31)
    • Windows (desktop) • windows     • windows-x64    • Microsoft Windows [Version 10.0.22621.819]
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 107.0.5304.106
    • Edge (web)        • edge        • web-javascript • Microsoft Edge 106.0.1370.34

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

Please help me or guide me on how to fix this issue, thanks in advance!

**Comment by darshankawar** [comment] 2022-11-11 07:25
> updated **firebase_messaging** to ^0.7.0+5

This is very old version. Latest version is `^14.1.0`. You'll need to upgrade to latest and try again to see if you still get same error or not.

**Comment by ne3Vubeki** [comment] 2022-11-11 08:32
I have the same
firebase_messaging: ^14.1.0

**Comment by samirasalah** [comment] 2022-11-13 12:41
I have the same, any solution ?

**Comment by samirasalah** [comment] 2022-11-13 12:49
> I have the same firebase_messaging: ^14.1.0
> 
> This only happens in android. For some reason, 2 threads are launched in android and when `await FirebaseMessaging.instance.requestPermission(` is fired again, an exception occurs: `[firebase_messaging/unknown] Attempt to invoke virtual method 'java.lang.Object android.content.Context.getSystemService(java.lang.String )' on a null object reference`. At the expense of threads, it is not yet clear, in IOS this is not. But the error occurs in the second thread, after the method is triggered in the first one.

I have the same issue, do you find any solution ?

**Comment by RoyalCoder88** [comment] 2022-11-13 13:18
> > updated **firebase_messaging** to ^0.7.0+5
> 
> This is very old version. Latest version is `^14.1.0`. You'll need to upgrade to the latest and try again to see if you still get same error or not.

Sorry, the version is  **14.1.0**, my mistake...no solution to fix this so far :( can you help me please?

**Comment by samirasalah** [comment] 2022-11-13 13:22
> > > updated **firebase_messaging** to ^0.7.0+5
> > 
> > 
> > This is very old version. Latest version is `^14.1.0`. You'll need to upgrade to the latest and try again to see if you still get same error or not.
> 
> Sorry, the version is **14.1.0**, my mistake...no solution to fix this so far :( can you help me please?

II'm looking for the solution, I'll let you know if there's any news.
Thank you for the answer

**Comment by Tom3652** [comment] 2022-11-13 16:11
I am having the same issue and was going to make an issue, but i add it here simply : 

```
I/flutter (15433): [firebase_messaging/unknown] Attempt to invoke virtual method 'java.lang.Object android.content.Context.getSystemService(java.lang.String)' on a null object reference
I/flutter (15433): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:653:7)
I/flutter (15433): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:296:18)
I/flutter (15433): <asynchronous suspension>
I/flutter (15433): #2      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:499:43)
I/flutter (15433): <asynchronous suspension>
I/flutter (15433): #3      MethodChannelFirebaseMessaging.getNotificationSettings (package:firebase_messaging_platform_interface/src/method_channel/method_channel_messaging.dart:243:36)
I/flutter (15433): <asynchronous suspension>
```

Using the method right before requesting permission : 

```
 NotificationSettings notificationSettings = await FirebaseMessaging.instance.getNotificationSettings();
```

I am using the latest version of the plugin `14.1.0`

**Comment by samirasalah** [comment] 2022-11-13 20:28
`E/flutter ( 7029): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: [firebase_messaging/unknown] Attempt to invoke virtual method 'java.lang.Object android.content.Context.getSystemService(java.lang.String)' on a null object reference
E/flutter ( 7029): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:653)
E/flutter ( 7029): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:296)
E/flutter ( 7029): <asynchronous suspension>
E/flutter ( 7029): #2      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:499)
E/flutter ( 7029): <asynchronous suspension>
E/flutter ( 7029): #3      MethodChannelFirebaseMessaging.getNotificationSettings (package:firebase_messaging_platform_interface/src/method_channel/method_channel_messaging.dart:243)

**Comment by samirasalah** [comment] 2022-11-13 20:28
Same issue :(

**Comment by manishrelani** [comment] 2022-11-14 04:53
i m using flutter v3.3.7 and firebase_messaging: 14.0.3 without ^ working fine.

if you cannot run the project, use this temporarily.

**Comment by darshankawar** [comment] 2022-11-14 10:10
Thanks for the updates here. This seems to be happening on Android currently based on the report and console error log and also based on https://github.com/firebase/flutterfire/issues/9904#issuecomment-1312766318 and https://github.com/firebase/flutterfire/issues/9904#issuecomment-1311389064

Keeping this issue open and for further insights from the team.

/cc @russellwheatley

**Comment by samirasalah** [comment] 2022-11-14 10:19
> Thanks for the updates here. This seems to be happening on Android currently based on the report and console error log and also based on [#9904 (comment)](https://github.com/firebase/flutterfire/issues/9904#issuecomment-1312766318) and [#9904 (comment)](https://github.com/firebase/flutterfire/issues/9904#issuecomment-1311389064)
> 
> Keeping this issue open and for further insights from the team.
> 
> /cc @russellwheatley

The issue has been resolved with 
`NotificationSettings notificationSettings = await FirebaseMessaging.instance.getNotificationSettings();`

But the onBackgroundMessage function no longer works

**Comment by RoyalCoder88** [comment] 2022-11-15 12:14
Hi @darshankawar , can you please take a look of this problem, thanks in advance!

**Comment by RoyalCoder88** [comment] 2022-11-15 12:31
Guys, how looks you **android/app/build.gradle**? 
I think the problem it's related with it, for example my **build.gradle** :

```
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}
def keystoreProperties = new Properties()
def keystorePropertiesFile = rootProject.file('key.properties')
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

android {
    // minSdkVersion 28
    compileSdkVersion 33

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        applicationId "com.mycomp.myapp"
        minSdkVersion 28
        targetSdkVersion 31
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        //multiDexEnabled true
    }

    signingConfigs {
        release {
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
            storePassword keystoreProperties['storePassword']
            storeFile file("myKeyTest.jks")
        }
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
            signingConfig signingConfigs.release
        }
    }
}

flutter {
    source '../..'
}


dependencies {
    implementation project(':unityLibrary')

    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.1.0-alpha4'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.0-alpha4'
    //implementation 'com.google.firebase:firebase-core:16.0.1'
    implementation 'com.google.firebase:firebase-bom:31.0.2'
    implementation 'com.google.android.gms:play-services-ads:21.3.0'
    implementation 'androidx.work:work-runtime-ktx:2.7.0'
    //implementation 'com.android.support:multidex:1.0.3'
}
apply plugin: 'com.google.gms.google-services'
```

If I uncomment `implementation 'com.google.firebase:firebase-core:16.0.1'` build failed, comment/uncomment `implementation 'com.google.firebase:firebase-bom:31.0.2'` let me build the app, but the problem with **firebase_messaging** still for me :(

**Comment by RoyalCoder88** [comment] 2022-11-15 12:42
> > Thanks for the updates here. This seems to be happening on Android currently based on the report and console error log and also based on [#9904 (comment)](https://github.com/firebase/flutterfire/issues/9904#issuecomment-1312766318) and [#9904 (comment)](https://github.com/firebase/flutterfire/issues/9904#issuecomment-1311389064)
> > Keeping this issue open and for further insights from the team.
> > /cc @russellwheatley
> 
> The issue has been resolved with `NotificationSettings notificationSettings = await FirebaseMessaging.instance.getNotificationSettings();`
> 
> But the onBackgroundMessage function no longer works

Thanks @samirasalah works for me as well this way, I will test **onBackgroundMessage** and reply later, thanks again!

**Comment by RoyalCoder88** [comment] 2022-11-15 22:13
*No, no fix have the same error :(

**Comment by darshankawar** [comment] 2022-11-17 08:16
Maybe related : https://github.com/firebase/flutterfire/issues/9912

**Comment by samirasalah** [comment] 2022-11-17 09:00
`// Copyright 2022, the Chromium project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

// ignore_for_file: require_trailing_commas

import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:translater/routes/app_routes.dart';

/// Requests & displays the current user permissions for this device.
class Permissions extends StatefulWidget {
  @override
  State<StatefulWidget> createState() => _Permissions();
}

class _Permissions extends State<Permissions> {
  bool _requested = false;
  bool _fetching = false;
  late NotificationSettings _settings;

  Future<void> requestPermissions() async {
    setState(() {
      _fetching = true;
    });

    NotificationSettings settings =
    await FirebaseMessaging.instance.requestPermission();

    setState(() {
      _requested = true;
      _fetching = false;
      _settings = settings;
    });
  }

  Future<void> checkPermissions() async {
    setState(() {
      _fetching = true;
    });

    NotificationSettings settings =
    await FirebaseMessaging.instance.getNotificationSettings();

    setState(() {
      _requested = true;
      _fetching = false;
      _settings = settings;
    });

    Get.offAllNamed(AppRoutes.home);
  }

  Widget row(String title, String value) {
    return Container(
      margin: const EdgeInsets.only(bottom: 8),
      child: Row(
        mainAxisAlignment: MainAxisAlignment.spaceBetween,
        children: [
          Text('$title:', style: const TextStyle(fontWeight: FontWeight.bold)),
          Text(value),
        ],
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    if (_fetching) {
      return const CircularProgressIndicator();
    }

    if (!_requested) {
      return ElevatedButton(
          onPressed: requestPermissions,
          child: const Text('Request Permissions'));
    }

    return Column(children: [
      row('Authorization Status', statusMap[_settings.authorizationStatus]!),
      if (defaultTargetPlatform == TargetPlatform.iOS) ...[
        row('Alert', settingsMap[_settings.alert]!),
        row('Announcement', settingsMap[_settings.announcement]!),
        row('Badge', settingsMap[_settings.badge]!),
        row('Car Play', settingsMap[_settings.carPlay]!),
        row('Lock Screen', settingsMap[_settings.lockScreen]!),
        row('Notification Center', settingsMap[_settings.notificationCenter]!),
        row('Show Previews', previewMap[_settings.showPreviews]!),
        row('Sound', settingsMap[_settings.sound]!),
      ],
      ElevatedButton(
          onPressed: checkPermissions, child: const Text('Reload Permissions')),
    ]);
  }
}

/// Maps a [AuthorizationStatus] to a string value.
const statusMap = {
  AuthorizationStatus.authorized: 'Authorized',
  AuthorizationStatus.denied: 'Denied',
  AuthorizationStatus.notDetermined: 'Not Determined',
  AuthorizationStatus.provisional: 'Provisional',
};

/// Maps a [AppleNotificationSetting] to a string value.
const settingsMap = {
  AppleNotificationSetting.disabled: 'Disabled',
  AppleNotificationSetting.enabled: 'Enabled',
  AppleNotificationSetting.notSupported: 'Not Supported',
};

/// Maps a [AppleShowPreviewSetting] to a string value.
const previewMap = {
  AppleShowPreviewSetting.always: 'Always',
  AppleShowPreviewSetting.never: 'Never',
  AppleShowPreviewSetting.notSupported: 'Not Supported',
  AppleShowPreviewSetting.whenAuthenticated: 'Only When Authenticated',
};
`


@darshankawar 
@RoyalCoder88 
You can check in this page how the requestPermission is done. I think it should be moved to the build or initState

**Comment by Lyokone** [comment] 2022-11-24 10:15
Hey 👋 
Can you try to reproduce in 14.1.1? We reverted the changes from 14.1.0 in it.

**Comment by Tom3652** [comment] 2022-11-24 10:35
It's working again for me in `14.1.1` :)

**Closed** 2022-11-24 10:36 UTC
Labels: type: bug, blocked: customer-response, plugin: messaging, platform: android, type: crash
