### ISSUE TITLE
[firebase_messaging]: After the app is terminated/swiped away, onBackgroundMessage only fires after a second notification on iOS

### ISSUE THREAD

**Issue by ViniciusSossela** [firebase/flutterfire#11500] opened 2023-08-19 20:27 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you aware of the differences between iOS and Android background message handling?

- [X] I understand that iOS and Android background messages behave differently, and I've designed my application with that in mind.

### Do you have an active Apple Developer account?

- [X] I have an active Apple Developer account.

### Are you using a physical iOS device to test background messages?

- [X] I am using a physical iOS device to test background messages.

### Have you enabled "Remote Notifications" & "Background Mode" (Checking options for "Background Processing" & "Remote Notifications") in your app's Xcode project?

![Screenshot 2023-08-19 at 16 11 28](https://github.com/firebase/flutterfire/assets/4993276/bc9a7c51-f8b7-47b0-8133-ea0508a7ae69)

### Have you created an APNs key in your Apple Developer account & uploaded this APNs key to your Firebase console?

![Screenshot 2023-08-19 at 16 13 15](https://github.com/firebase/flutterfire/assets/4993276/914e9b5d-20c1-478f-8ff3-7c77ce439256)

### Have you disabled method swizzling for Firebase in your app?

there is no FirebaseAppDelegateProxyEnabled in info.plist

### Are you sending messages to your app from the Firebase Admin SDK?

yes, contentAvailable is set to true, also priority to high

### Have you requested permission from the user to receive notifications?

- [X] I have the relevant permission to receive notifications.

### Have you used the 'Console' application on your macOS device to check if the iOS device's system is throttling your background messages?

default	16:18:09.123914-0300	SpringBoard	Received incoming message on topic com.kodefy.myapp at priority 10
default	16:18:09.144908-0300	SpringBoard	[com.kodefy.myapp] Received remote notification request 087B-1FF7 [ waking: 0, hasAlertContent: 1, hasSound: 0 hasBadge: 0 hasContentAvailable: 1 hasMutableContent: 0 pushType: Alert]
default	16:18:09.144968-0300	SpringBoard	[com.kodefy.myapp] Process delivery of push notification 087B-1FF7
default	16:18:09.145031-0300	SpringBoard	[com.kodefy.myapp] Request DUET delivers content-available push notification to application
default	16:18:09.145091-0300	SpringBoard	SUBMITTING: com.apple.pushLaunch.com.kodefy.myapp:2D9295
default	16:18:09.145478-0300	SpringBoard	[com.kodefy.myapp] Badge can be set for notification 087B-1FF7: 0 [ canBadge: 1 badgeNumber: (null) ]
default	16:18:09.145783-0300	SpringBoard	Getting effectiveSectionInfo for section identifier: com.kodefy.myapp
default	16:18:09.145889-0300	SpringBoard	[com.kodefy.myapp] Getting effective section info
default	16:18:09.145946-0300	dasd	Submitted Activity: com.apple.pushLaunch.com.kodefy.myapp:2D9295 at priority 10 <private>
default	16:18:09.146667-0300	SpringBoard	[com.kodefy.myapp] Got effective section info [ hasResult: 1 ]
default	16:18:09.146740-0300	SpringBoard	Getting effectiveSectionInfo for section identifier: com.kodefy.myapp
default	16:18:09.146806-0300	SpringBoard	[com.kodefy.myapp] Getting effective section info
default	16:18:09.166501-0300	SpringBoard	[com.kodefy.myapp] Got effective section info [ hasResult: 1 ]
default	16:18:09.166716-0300	SpringBoard	[com.kodefy.myapp] Saving notification 087B-1FF7: YES [ hasAlertContent: YES, shouldPresentAlert: YES settingsShouldSave: YES]
default	16:18:09.167058-0300	dasd	com.apple.pushLaunch.com.kodefy.myapp:2D9295:[
	{name: ApplicationPolicy, policyWeight: 50.000, response: {Decision: Absolutely Must Proceed, Score: 1.00, Rationale: [{[appIsForeground]: Required:1.00, Observed:1.00},]}}
 ], FinalDecision: Absolutely Must Proceed}
default	16:18:09.173681-0300	dasd	[FBSSystemService][0xd58a] Sending request to open "com.kodefy.myapp"
default	16:18:09.200371-0300	SpringBoard	[com.kodefy.myapp] Delivered user visible push notification 087B-1FF7
default	16:18:09.200454-0300	SpringBoard	[FBSystemService][0xd58a] Received request to open "com.kodefy.myapp" from dasd:94.
default	16:18:09.200576-0300	SpringBoard	Received trusted open application request for "com.kodefy.myapp" from <FBProcess: 0x14b3e3520; daemon<com.apple.dasd>:94(v116)>.
default	16:18:09.200690-0300	SpringBoard	[com.kodefy.myapp] Load 0 pending notification dictionaries
default	16:18:09.201421-0300	SpringBoard	[com.kodefy.myapp] Adding notification 087B-1FF7 [ hasAlertContent: 1, shouldPresentAlert: 1 hasSound: 0 shouldPlaySound: 1 ]; interruption-level: 1; destinations 398: (
    NotificationCenter,
    LockScreen,
    Alert,
    Spoken,
    Forwarding
)

### Additional context and comments

After the app is terminated/swiped away, onBackgroundMessage only is fired after the second notification on iOS.

Every time that the app is closed/swiped away, we need to send a first notification that will be displayed to the user but not fires the `onBackgroundMessage handler`. Then the second notification will also be displayed to the user and at this time it will fire the onBackgroundMessage handler... 

Is this the expected behavior?

```
@pragma('vm:entry-point')
Future<void> _messagingBackgroundHandler(remoteMessage) async {
   await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  FirebaseFirestore.instance.collection('push').add({'push': 1});
}
```

**Comment by ItayBarFaye** [comment] 2023-08-20 10:23
Also for me something with entity not register.

**Comment by rajkumar61194** [comment] 2023-08-20 13:51
@pragma('vm:entry-point')
Future<void> _messagingBackgroundHandler(remoteMessage) async {
   await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  FirebaseFirestore.instance.collection('push').add({'push': 1});
}

The above method is not triggering when iOS app closed or terminated. 

Working case: 

If no other app is running it works well.

Not working case:

If any other app is running it is not triggering.

I'm facing this issue in ios not an Android side. Android is working well.

Please fix it.

**Comment by ViniciusSossela** [comment] 2023-08-20 18:25
@rajkumar61194 in our case, even with other apps running/opened the `_messagingBackgroundHandler` is not triggered on the first time, only the second notification fires the handler.

**Comment by rajkumar61194** [comment] 2023-08-21 02:02
@ViniciusSossela It looks like a flutter plugin pug in iOS side.

**Comment by darshankawar** [comment] 2023-08-21 12:24
@ViniciusSossela 
Looks like you are hitting https://github.com/firebase/flutterfire/issues/11336 ? You can check underlying comments from Russell for reference and check if it helps in your case or not.

**Comment by russellwheatley** [comment] 2023-08-21 12:28
@ViniciusSossela - That PR would fix the issue if anything. Are you running on the latest?

**Comment by ViniciusSossela** [comment] 2023-08-21 12:54
> @ViniciusSossela Looks like you are hitting #11336 ? You can check underlying comments from Russell for reference and check if it helps in your case or not.

Thanks for the response, I already have checked the message sender example:
https://github.com/firebase/flutterfire/blob/master/packages/firebase_messaging/firebase_messaging/example/scripts/send-message.js

And yes we also are sending the notification with content-available, e priority, but we are using `rust`
<img width="812" alt="Screenshot 2023-08-21 at 09 50 45" src="https://github.com/firebase/flutterfire/assets/4993276/24ab001d-1a50-436b-be5b-479e5db6dc11">

Also, we are using this for a long time, and just these days we notice this issue.

@russellwheatley 
yes we are using the latest `firebase_messaging 14.6.6.`
<img width="676" alt="Screenshot 2023-08-21 at 09 53 55" src="https://github.com/firebase/flutterfire/assets/4993276/1404b2cb-0f14-462b-8c20-b3c20f2cfb2d">

**Comment by ViniciusSossela** [comment] 2023-08-21 12:56
> @ViniciusSossela - That PR would fix the issue if anything. Are you running on the latest? firebase_messaging 14.6.6.

The notification always is shown/displayed to the user... But the handler is just fired in the second message sent.

**Comment by rajkumar61194** [comment] 2023-08-21 13:29
The message notification is received in all cases but the **_messagingBackgroundHandler** is not triggering if any other app is running.

**Comment by ItayBarFaye** [comment] 2023-08-21 13:36
Also using the latest, when app is terminated, first notification not been displayed.

**Comment by ViniciusSossela** [comment] 2023-08-21 15:16
@russellwheatley 
@darshankawar 
https://github.com/firebase/flutterfire/issues/11336#issuecomment-1665748679
The problem is not with the notification not being shown.

As @blakewood84 said in this comment:
https://github.com/firebase/flutterfire/issues/11336#issuecomment-1665748679

  The problem is that the FIRST notification is not firing the handler when the app is in the terminated state on iOS. We always need a second notification to fire the handler.

**Comment by ViniciusSossela** [comment] 2023-08-22 11:46
@russellwheatley 
Could you simulate this issue?

**Comment by darshankawar** [comment] 2023-08-22 11:51
> The message notification is received in all cases but the **_messagingBackgroundHandler** is not triggering if any other app is running in **iOS** at that time handler is not trigerring.

@rajkumar61194 
You might be hitting same issues as below:

https://github.com/firebase/flutterfire/issues/10929
https://github.com/firebase/flutterfire/issues/9625

**Comment by ViniciusSossela** [comment] 2023-08-22 15:00
@darshankawar 
Let me ask one thing about this example:
https://github.com/firebase/flutterfire/blob/master/packages/firebase_messaging/firebase_messaging/example/scripts/send-message.js

In this case, does the notification considered a BACKGROUND NOTIFICATION because of the content-available flag? Or it won't be considered BACKGROUND because of the notification code:

```
notification: {
        title: 'A great title',
        body: 'Great content',
      },
```

If it is considered as a BACKGROUND NOTIFICATION, the notification also can be considered as low-priority right?

`The system treats background notifications as low priority: you can use them to refresh your app’s content, but the system doesn’t guarantee their delivery. In addition, the system may throttle the delivery of background notifications if the total number becomes excessive. The number of background notifications allowed by the system depends on current conditions, but don’t try to send more than two or three per hour.`

https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/pushing_background_updates_to_your_app


So if the priority of the business is to deliver the notification instead of processing background stuff? We shouldn't add the flag `content-available`, is this affirmation correct?

**Comment by ViniciusSossela** [comment] 2023-08-23 10:12
> @ViniciusSossela `content-available` field is used to represent APNS payload. When a notification or data message is sent and this is set to `true`, an inactive client app is awoken. Does it help to answer your question ?

Not entirely. So 'content-available' is set to true to send data. The priority of it will be low as said in the documentation. Am I Right?
`
The system treats background notifications as low priority: you can use them to refresh your app’s content, but the system doesn’t guarantee their delivery. In addition, the system may throttle the delivery of background notifications if the total number becomes excessive. The number of background notifications allowed by the system depends on current conditions, but don’t try to send more than two or three per hour.
`

Also, this question doesn't answer this issue about not triggering the background handler, ok? 

Did you reproduce the issue? Are in your tests the background handler triggered on the first notification when terminated on iOS?

**Comment by darshankawar** [comment] 2023-08-24 10:43
Thanks for the feedback @ViniciusSossela 
I tried using plugin example running with latest version on iOS device, but I can't seem to replicate the behavior you reported. After app was terminated by swiping away, the [documentation](https://firebase.google.com/docs/cloud-messaging/flutter/receive) says below:

`On iOS, if the user swipes away the application from the app switcher, it must be manually reopened for background messages to start working again.`

If we go by above statement and try to open the app manually and then trigger a notification, does it call the handler or if you push another notification then only the handler is called ?

**Comment by ViniciusSossela** [comment] 2023-08-24 11:10
> Thanks for the feedback @ViniciusSossela I tried using plugin example running with latest version on iOS device, but I can't seem to replicate the behavior you reported. After app was terminated by swiping away, the [documentation](https://firebase.google.com/docs/cloud-messaging/flutter/receive) says below:
> 
> `On iOS, if the user swipes away the application from the app switcher, it must be manually reopened for background messages to start working again.`
> 
> If we go by above statement and try to open the app manually and then trigger a notification, does it call the handler or if you push another notification then only the handler is called ?

@darshankawar 
Thanks for the answer.

To simulate the issue you must not manually open the app. You should swipe away the app, and just send the notification.

About that:
`On iOS, if the user swipes away the application from the app switcher, it must be manually reopened for background messages to start working again.`

We already knew about that statement. But it's strange because it is not a requirement in any other documentation/language (Native Android, and iOS/Swift), just in the Flutter one. Is it a Flutter our plugin limitation?

For example, on the same page, just not in the flutter section, there isn't such a limitation.
https://firebase.google.com/docs/cloud-messaging/ios/receive

And also, this is not true:
`On iOS, if the user swipes away the application from the app switcher, it must be manually reopened for background messages to start working again.`

Because if we DO NOT open the app manually, why does the SECOND notification trigger the handler? 
We did not manually open the app, and even so, the handler was triggered.... why just int the FIRST one it is not triggered?

**Comment by darshankawar** [comment] 2023-08-25 10:36
> Try to send a second notification without MANUALLY opening the app. You will see that the handler is triggered.
> So basically we do not need to open it manually to get it back to work, right?

With this step, I see that the handler is being triggered. 
For overall behavior reported and whether to know what should be the intended behavior as compared to the reported one, keeping this issue open for team's input.

/cc @russellwheatley

**Comment by CAJazzer** [comment] 2023-08-29 21:26
Same issue for me. Using FlutterAppBadger to add a badge in the onBackgroundMessage handler.   Badge is only added after a second message is sent while app is terminated.  
Flutter:
```
@pragma('vm:entry-point')
Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message) async {
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  // Update the badge
  FlutterAppBadger.updateBadgeCount(1);
}
```



Testing with firebase-admin in Node.js using:

```
const admin = require('firebase-admin');
 admin.initializeApp({
  credential: admin.credential.cert(myCert)
 });
admin.messaging().send(message);
```

message with both notification and data. 
```
message = {
  token: myTokenPassed,
  notification: {
    title: 'Hello from California',
    body: 'Not A bad place'
  },
  data: { topic: 'topic_29' },
  apns: { 
  	payload: { 
  		aps: { 
  			contentAvailable: true,
  		} 
  	}
  }
};
```

**Comment by ViniciusSossela** [comment] 2023-09-05 11:02
Still not working on firebase_messaging 14.6.7

**Comment by russellwheatley** [comment] 2023-09-05 11:12
@ViniciusSossela -  I've just ran the example app in release mode, and added an API call to a local server to the background message handler. I swiped away the app into a terminated state and sent a message. I received an API call on my local server on the first message sent. I've done this a number of times and I cannot reproduce your issue. I am using nodejs script to [send a message](https://github.com/firebase/flutterfire/blob/master/packages/firebase_messaging/firebase_messaging/example/scripts/send-message.js).

**Comment by ViniciusSossela** [comment] 2023-09-05 11:53
> @ViniciusSossela - I've just ran the example app in release mode, and added an API call to a local server to the background message handler. I swiped away the app into a terminated state and sent a message. I received an API call on my local server on the first message sent. I've done this a number of times and I cannot reproduce your issue. I am using nodejs script to [send a message](https://github.com/firebase/flutterfire/blob/master/packages/firebase_messaging/firebase_messaging/example/scripts/send-message.js).

Thank you for your answer @russellwheatley 

To make sure, I am not having a problem with API calls, every call to the API is okay.

AFTER you SWIPED AWAY your app on an iOS phone, has the FIRST notification sent by your API triggered the `_messagingBackgroundHandler` ? 

* So here are the steps:
1 - Swipe away your app
2 - Call the API to send the FIRST message after swiped away
3 - The message will be displayed but `WILL NOT` trigger the `_messagingBackgroundHandler`
4 - Call AGAIN the API to send the SECOND message after swiped away
5 - The message will be displayed `AND WILL` TRIGGER the `_messagingBackgroundHandler`

In our case, ONLY the SECOND API notification sent triggered the `_messagingBackgroundHandler`.

**Comment by russellwheatley** [comment] 2023-09-05 12:33
@ViniciusSossela - This is the point. I use a very simple server (a simple node express server that logs when called) to check the `_messagingBackgroundHandler` is being triggered from a terminated state, otherwise, I'm not sure how I would check as I can't receive logs. The `_messagingBackgroundHandler` is being triggered on the first message sent when the app is in a terminated state.

**Comment by ViniciusSossela** [comment] 2023-09-05 12:41
> @ViniciusSossela - This is the point. I use a very simple server (a simple node express server that logs when called) to check the `_messagingBackgroundHandler` is being triggered from a terminated state, otherwise, I'm not sure how I would check as I can't receive logs. The `_messagingBackgroundHandler` is being triggered on the first message sent when the app is in a terminated state.

Nice.

I have been adding a document to the Firestore collection to check the `_messagingBackgroundHandler` is being triggered.

Will do a simple API call to check if it changes something....

**Comment by ViniciusSossela** [comment] 2023-09-08 13:34
> @ViniciusSossela - This is the point. I use a very simple server (a simple node express server that logs when called) to check the `_messagingBackgroundHandler` is being triggered from a terminated state, otherwise, I'm not sure how I would check as I can't receive logs. The `_messagingBackgroundHandler` is being triggered on the first message sent when the app is in a terminated state.


@russellwheatley 
Just tried with a simple API call, and got the same behavior as I had with the FIRESTORE. 
Only the second notification triggers the background handler.

Main file:
```
Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  FirebaseMessaging.onBackgroundMessage(_backgroundHandler);

  AppInjection.inject(_getIt);

  await AppNotification.initialize(_involvexpApikey);

  runApp(ComparinApp());
}

```


Handler:
```
@pragma('vm:entry-point')
Future<void> _backgroundHandler(remoteMessage) async {
  final response = await http.post(
    Uri.parse('https://us-central1-xxxxx-xxxx.cloudfunctions.net/api/log'),
    body: {},
  );

  if (response.statusCode == 200) {
    print('log enviado');
  } else {
    print('log não enviado');
  }
}
```

The Google Function API Triggered on the handler:
`https://us-central1-xxxxx-xxxx.cloudfunctions.net/api/log`
![Screenshot 2023-09-08 at 10 16 05](https://github.com/firebase/flutterfire/assets/4993276/38d215e4-5772-4cc8-be1d-835eeeaee471)


The Google Function Log:
<img width="871" alt="Screenshot 2023-09-08 at 09 55 25" src="https://github.com/firebase/flutterfire/assets/4993276/257dc19b-b819-40ed-aab2-589f4322ff37">


The steps:
1 - Run the app on release mode.
2 - Swipe away the app
3 - Send the 1st Notification
4 - Send the 2nd Notification

Only got the log from the 2nd notification.

**Comment by ViniciusSossela** [comment] 2023-09-08 14:15
@russellwheatley 

Removing the following code allowed the 1st notification to trigger the handler.
`Zone.current.run(() async {}`

Not sure why, but it seems to be working without the Zone.

**Comment by fridaychukwuamaka** [comment] 2023-09-11 13:58
@ViniciusSossela, I am experiencing the same thing. Were you able to get around it. What iOS are you testing it on, mine is iOS 17.

**Comment by ntaworking** [comment] 2023-09-28 02:17
> > @ViniciusSossela - This is the point. I use a very simple server (a simple node express server that logs when called) to check the `_messagingBackgroundHandler` is being triggered from a terminated state, otherwise, I'm not sure how I would check as I can't receive logs. The `_messagingBackgroundHandler` is being triggered on the first message sent when the app is in a terminated state.
> 
> @russellwheatley Just tried with a simple API call, and got the same behavior as I had with the FIRESTORE. Only the second notification triggers the background handler on iOS.
> 
> Main file:
> 
> ```
> Future<void> main() async {
>   Zone.current.run(() async {
>     WidgetsFlutterBinding.ensureInitialized();
> 
>     FlutterError.onError = CrashReport().recordFlutterError;
> 
>     await Firebase.initializeApp(
>       options: DefaultFirebaseOptions.currentPlatform,
>     );
> 
>     AppInjection.inject(_getIt);
> 
>     await AppNotification.initialize(_involvexpApikey);
>     FirebaseMessaging.onBackgroundMessage(_backgroundHandler);
> 
>     runApp(XXXXApp());
>   });
> }
> ```
> 
> Handler:
> 
> ```
> @pragma('vm:entry-point')
> Future<void> _backgroundHandler(remoteMessage) async {
>   final response = await http.post(
>     Uri.parse('https://us-central1-xxxxx-xxxx.cloudfunctions.net/api/log'),
>     body: {},
>   );
> 
>   if (response.statusCode == 200) {
>     print('log enviado');
>   } else {
>     print('log não enviado');
>   }
> }
> ```
> 
> The Google Function API Triggered on the handler: `https://us-central1-xxxxx-xxxx.cloudfunctions.net/api/log` ![Screenshot 2023-09-08 at 10 16 05](https://user-images.githubusercontent.com/4993276/266621855-38d215e4-5772-4cc8-be1d-835eeeaee471.png)
> 
> The Google Function Log: <img alt="Screenshot 2023-09-08 at 09 55 25" width="871" src="https://user-images.githubusercontent.com/4993276/266625575-257dc19b-b819-40ed-aab2-589f4322ff37.png">
> 
> The steps: 1 - Run the app on release mode. 2 - Swipe away the app 3 - Send the 1st Notification 4 - Send the 2nd Notification
> 
> Only got the log from the 2nd notification.

Couldn't even get any notifications the first time.
I'm checking on iOS 16.6.1
My request by PostMan:
```
{
    "to": "my_token",
    "content_available": true,
    "data": {
        "title": "Thank you!",
        "body": "Thank you!",
        "transfer_page": "HOME"
    }
}
```
Response: 
```
{
    "multicast_id": 3947782428538422640,
    "success": 1,
    "failure": 0,
    "canonical_ids": 0,
    "results": [
        {
            "message_id": "1695866869332751"
        }
    ]
}
```

**Comment by ntaworking** [comment] 2023-09-28 08:25
I have faced same issue.

**Comment by ViniciusSossela** [comment] 2023-09-28 21:21
I just checked again and Unfortunately, it still is happening, even after I deleted  `Zone.current.run(() async {}`.

I'm going to do more tests.
@russellwheatley 
Is your background fn still being triggered on the first notification on iOS after closing/swiping away?

**Comment by ntaworking** [comment] 2023-09-29 03:59
Someone please confirm: Does this problem occurs on Android native?

**Comment by russellwheatley** [comment] 2023-09-29 09:07
> I just checked again and Unfortunately, it still is happening, even after I deleted `Zone.current.run(() async {}`.
> 
> I'm going to do more tests. @russellwheatley Is your background fn still being triggered on the first notification on iOS after closing/swiping away?

@ViniciusSossela - Yes, it is still being triggered for the first notification

**Comment by ntaworking** [comment] 2023-09-29 09:46
> > I just checked again and Unfortunately, it still is happening, even after I deleted `Zone.current.run(() async {}`.
> > I'm going to do more tests. @russellwheatley Is your background fn still being triggered on the first notification on iOS after closing/swiping away?
> 
> @ViniciusSossela - Yes, it is still being triggered for the first notification

Can you give me a example code?

**Comment by russellwheatley** [comment] 2023-09-29 10:38
I'm just using the example app in firebase_messaging plugin

**Comment by superwch1** [comment] 2023-10-03 14:29
I am also facing the same issue here.
I use flutter_local_notification and firebase_messaging, the first notification not showing but subsequent notifications work properly.

**Comment by Nic-DB** [comment] 2023-10-06 15:12
hi I'm facing the same issue. I have sentry logging enabled and getting this message:
'The OS watchdog terminated your app, possibly because it overused RAM'.
Maybe can be helpful.

**Comment by ricnaaru** [comment] 2023-11-10 05:10
The solution is pretty simple actually. I have been working round and round for this. And finally..

So the solution is simply put his code on your main method, and that's it.

`FirebaseMessaging.onBackgroundMessage(backgroundMessageHandler);`

The first notification will call main() method on Flutter, but it won't last long because the app may have logic to initialize data, to spawn UI, etc. But having that method above to register background message in the first place when main method is called, that first notification will magically trigger the static method that you registered.

**Comment by DennisKragekjaer** [comment] 2023-12-14 17:19
Same here

**Comment by russellwheatley** [comment] 2023-12-19 13:28
Closing out as  I haven't been able to reproduce and the solution is probably down to not activating:
```dart
FirebaseMessaging.onBackgroundMessage(backgroundMessageHandler);
```

early enough in your app (i.e. in your `main()` function.

**Closed by russellwheatley** 2023-12-19 13:28 UTC
Labels: type: bug, plugin: messaging, platform: ios, Needs Attention

**Comment by Gobmichet** [comment] 2024-01-10 12:33
> The solution is pretty simple actually. I have been working round and round for this. And finally..
> 
> So the solution is simply put his code on your main method, and that's it.
> 
> `FirebaseMessaging.onBackgroundMessage(backgroundMessageHandler);`
> 
> The first notification will call main() method on Flutter, but it won't last long because the app may have logic to initialize data, to spawn UI, etc. But having that method above to register background message in the first place when main method is called, that first notification will magically trigger the static method that you registered.

How can you test it @ricnaaru plz ?
'cause if you "terminate/kill" the iOS app, then you won't have any stackTrace anymore in AndroidStudio...

Can you tell me how you achieve such tests please ?
via Xcode maybe ?

Thanks in advance !

**Comment by maharramg** [comment] 2024-01-18 23:59
> Same issue for me. Using FlutterAppBadger to add a badge in the onBackgroundMessage handler. Badge is only added after a second message is sent while app is terminated. Flutter:
> 
> ```
> @pragma('vm:entry-point')
> Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message) async {
>   await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
>   // Update the badge
>   FlutterAppBadger.updateBadgeCount(1);
> }
> ```
> 
> Testing with firebase-admin in Node.js using:
> 
> ```
> const admin = require('firebase-admin');
>  admin.initializeApp({
>   credential: admin.credential.cert(myCert)
>  });
> admin.messaging().send(message);
> ```
> 
> message with both notification and data.
> 
> ```
> message = {
>   token: myTokenPassed,
>   notification: {
>     title: 'Hello from California',
>     body: 'Not A bad place'
>   },
>   data: { topic: 'topic_29' },
>   apns: { 
>   	payload: { 
>   		aps: { 
>   			contentAvailable: true,
>   		} 
>   	}
>   }
> };
> ```
> 
> ** CORRECTION ** I added storing a SharedPreferences object for the BadgeCount in the onBackground handler and now it is working every time. Strange.

@CAJazzer I am also implementing the same app badge incrementation for my app. Can I please see the _firebaseMessagingBackgroundHandler function with the whole SharedPreferences implementation?
