### ISSUE TITLE
🐛 [firebase_dynamic_links] Unpredictable behaviour of dynamic link

### ISSUE THREAD

**Issue by sneha-tandri** [firebase/flutterfire#10774] opened 2023-04-12 05:48 UTC
## Bug report

**Describe the bug**
I am building an app in VScode using flutter. I am trying to add an email link sign in in my app. In android, the dynamic link received in the mail sometimes redirects to the app correctly and other times it shows a security error "Deceptive site ahead". If I proceed to visit the unsafe site, then the website is redirecting me to the Playstore, and as my app is not on the Playstore yet, it shows "The requested url was not found." I am using
    firebase_core: ^2.9.0
    firebase_auth: ^4.4.0
    firebase_dynamic_links: ^5.1.0

### Steps to reproduce

1. Set up email link sign in
2. Handle dynamic link inside the app
3. try to click on email link
4. Error: Deceptive site ahead

### Expected behavior

The dynamic link clicked should always redirect to the app.

---

## Additional context

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>
Dart SDK 3.0.0-266.0.dev
Flutter SDK 3.8.0-16.0.pre.38
kinesis_locate 1.0.0+1

dependencies:
- async 2.10.0 [collection meta]
- cupertino_icons 1.0.5
- dio 5.1.0 [http_parser meta path]
- email_validator 2.1.17
- firebase_auth 4.4.0 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 2.9.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_dynamic_links 5.1.0 [firebase_core firebase_core_platform_interface firebase_dynamic_links_platform_interface flutter meta plugin_platform_interface]
- flutter 0.0.0 [characters collection js material_color_utilities meta vector_math sky_engine]
- flutter_bloc 8.1.2 [flutter bloc provider]
- google_fonts 4.0.3 [flutter http path_provider crypto]
- material_design_icons_flutter 6.0.7096 [flutter]

dev dependencies:
- flutter_launcher_icons 0.13.0 [args checked_yaml cli_util image json_annotation path yaml]
- flutter_lints 2.0.1 [lints]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters collection js matcher material_color_utilities meta source_span stream_channel string_scanner term_glyph]

transitive dependencies:
- _flutterfire_internals 1.1.0 [collection firebase_core firebase_core_platform_interface flutter meta]
- archive 3.3.7 [crypto path pointycastle]
- args 2.4.0
- bloc 8.1.1 [meta]
- boolean_selector 2.1.1 [source_span string_scanner]
- characters 1.3.0
- checked_yaml 2.0.2 [json_annotation source_span yaml]
- cli_util 0.4.0 [meta path]
- clock 1.1.1
- collection 1.17.1
- convert 3.1.1 [typed_data]
- crypto 3.0.2 [typed_data]
- fake_async 1.3.1 [clock collection]
- ffi 2.0.1
- file 6.1.4 [meta path]
- firebase_auth_platform_interface 6.13.0 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 5.3.0 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core_platform_interface 4.6.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.3.0 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_dynamic_links_platform_interface 0.2.4 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta vector_math]
- http 0.13.5 [async http_parser meta path]
- http_parser 4.0.2 [collection source_span string_scanner typed_data]
- image 4.0.15 [archive meta xml]
- intl 0.17.0 [clock path]
- js 0.6.7 [meta]
- json_annotation 4.8.0 [meta]
- lints 2.0.1
- matcher 0.12.14 [meta stack_trace]
- material_color_utilities 0.2.0
- meta 1.9.0
- nested 1.0.0 [flutter]
- path 1.8.3
- path_provider 2.0.13 [flutter path_provider_android path_provider_foundation path_provider_linux path_provider_platform_interface path_provider_windows]
- path_provider_android 2.0.24 [flutter path_provider_platform_interface]
- path_provider_foundation 2.1.3 [flutter path_provider_platform_interface]
- path_provider_linux 2.1.10 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_platform_interface 2.0.6 [flutter platform plugin_platform_interface]
- path_provider_windows 2.1.5 [ffi flutter path path_provider_platform_interface win32]
- petitparser 5.3.0 [meta]
- platform 3.1.0
- plugin_platform_interface 2.1.4 [meta]
- pointycastle 3.7.2 [collection convert js]
- process 4.2.4 [file path platform]
- provider 6.0.5 [collection flutter nested]
- sky_engine 0.0.99
- source_span 1.9.1 [collection path term_glyph]
- stack_trace 1.11.0 [path]
- stream_channel 2.1.1 [async]
- string_scanner 1.2.0 [source_span]
- term_glyph 1.2.1
- test_api 0.4.18 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.1 [collection]
- vector_math 2.1.4
- win32 3.1.3 [ffi]
- xdg_directories 1.0.0 [meta path process]
- xml 6.2.2 [collection meta petitparser]
- yaml 3.1.1 [collection source_span string_scanner]
</details>

---

**Comment by darshankawar** [comment] 2023-04-12 11:38
Thanks for the report @sneha-tandri 
Looking at the error you are receiving `Deceptive site ahead`, it doesn't seem to be a plugin or caused by it, but could be due to the setup / config you have in place. Take a look at [this](https://stackoverflow.com/questions/74997861/firebase-sign-in-with-email-link-suspicious-dangerous) SO link and see if it helps in your case.

I am going ahead and closing, as this doesn't seem to be actionable from plugin side. If you disagree, write in comments and I'll reopen it.

**Closed by darshankawar** 2023-04-12 11:38 UTC
Labels: type: bug, Needs Attention, in triage

**Comment by sneha-tandri** [comment] 2023-04-13 04:32
The behaviour is unpredictable, it works sometimes and doesn't work other times. This unpredictability makes me think the problem is not in the setup. Apart from this, while trying to send an email link, I keep getting "Error sending email verification [firebase_auth/too-many-requests] We have blocked all requests from this device due to unusual activity. Try again later." even though I haven't requested a lot of times.

**Comment by sneha-tandri** [comment] 2023-04-20 16:00
Hi! So the issue came up for a bit, and then the link started behaving as expected again. But today when I tried signing in again, it is not working yet again. I do not know whet is causing this unpredictable behaviour, as if is due to the setup that I have, it should be throwing this message "Deceptive site ahead" every single time. Please help me out on this.
