### ISSUE TITLE
🐛 [flutterfire_ui 0.4.1] Error: Method 'addPostFrameCallback' cannot be called on 'SchedulerBinding?' because it is potentially null.

### ISSUE THREAD

**Issue by MarcVanDaele90** [firebase/flutterfire#8700] opened 2022-05-18 10:08 UTC
## Bug report

**Describe the bug**
When trying to use the newly release version flutterfire_ui 0.4.1, I get the following build error

```
../../../.pub-cache/hosted/pub.dartlang.org/flutterfire_ui-0.4.1/lib/src/auth/screens/email_verification_screen.dart:96:31: Error: Method 'addPostFrameCallback' cannot be called on 'SchedulerBinding?' because it is potentially null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../../snap/flutter/common/flutter/packages/flutter/lib/src/scheduler/binding.dart').
Try calling using ?. instead.
    SchedulerBinding.instance.addPostFrameCallback(_sendEmailVerification);
                              ^^^^^^^^^^^^^^^^^^^^
```
Maybe this is an issue on my side though it persists after calling flutter clean/flutter pub get

I noticed that at least on the master branch, the line was changed to
```
    SchedulerBinding.instance!.addPostFrameCallback(_sendEmailVerification);
```
but I don't know whether you are releaseing from the master branch

### Sample project

---

## Additional context

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.5, on Linux Mint 20.2 5.13.0-40-generic, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.66.2)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.16.2
Flutter SDK 2.10.5
wijsr_backend 0.0.1

dependencies:
- cloud_firestore 3.1.15 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_interface flutter meta]
- firebase 9.0.2 [http http_parser js]
- firebase_analytics 9.1.7 [firebase_analytics_platform_interface firebase_analytics_web firebase_core firebase_core_platform_interface flutter]
- firebase_auth 3.3.18 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- flutter 0.0.0 [characters collection material_color_utilities meta typed_data vector_math sky_engine]
- flutter_facebook_auth 4.3.0 [flutter flutter_facebook_auth_platform_interface flutter_facebook_auth_web]
- flutterfire_ui 0.4.1 [cloud_firestore collection crypto desktop_webview_auth email_validator firebase_auth firebase_core firebase_database firebase_dynamic_links flutter flutter_facebook_auth flutter_localizations flutter_svg google_sign_in sign_in_with_apple twitter_login]
- google_sign_in 5.3.0 [flutter google_sign_in_android google_sign_in_ios google_sign_in_platform_interface google_sign_in_web]
- process_run 0.12.3+2 [path collection charcode string_scanner yaml meta args pub_semver synchronized]
- tekartik_app_flutter_sembast 0.5.1 [flutter sembast sembast_web sembast_sqflite path_provider path tekartik_app_flutter_sqflite tekartik_lints_flutter]

dev dependencies:
- flutter_lints 1.0.4 [lints]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher material_color_utilities meta source_span stream_channel string_scanner term_glyph typed_data]

transitive dependencies:
- args 2.3.0
- async 2.8.2 [collection meta]
- boolean_selector 2.1.0 [source_span string_scanner]
- characters 1.2.0
- charcode 1.3.1
- clock 1.1.0
- cloud_firestore_platform_interface 5.5.6 [collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 2.6.15 [cloud_firestore_platform_interface collection firebase_core firebase_core_web flutter flutter_web_plugins js]
- collection 1.15.0
- crypto 3.0.2 [typed_data]
- desktop_webview_auth 0.0.7 [crypto flutter http]
- email_validator 2.0.1
- fake_async 1.2.0 [clock collection]
- ffi 1.1.2
- file 6.1.2 [meta path]
- firebase_analytics_platform_interface 3.1.5 [firebase_core flutter meta plugin_platform_interface]
- firebase_analytics_web 0.4.0+12 [firebase_analytics_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- firebase_auth_platform_interface 6.2.6 [firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 3.3.15 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core 1.16.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_core_platform_interface 4.4.0 [collection flutter meta plugin_platform_interface]
- firebase_core_web 1.6.4 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_database 9.0.14 [firebase_core firebase_core_platform_interface firebase_database_platform_interface firebase_database_web flutter]
- firebase_database_platform_interface 0.2.1+6 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_database_web 0.2.0+13 [firebase_core firebase_core_web firebase_database_platform_interface flutter flutter_web_plugins js]
- firebase_dynamic_links 4.2.3 [firebase_core firebase_core_platform_interface firebase_dynamic_links_platform_interface flutter meta plugin_platform_interface]
- firebase_dynamic_links_platform_interface 0.2.3+2 [firebase_core flutter meta plugin_platform_interface]
- flutter_facebook_auth_platform_interface 3.1.0 [flutter plugin_platform_interface]
- flutter_facebook_auth_web 3.1.0 [flutter flutter_web_plugins js flutter_facebook_auth_platform_interface]
- flutter_localizations 0.0.0 [flutter intl characters clock collection material_color_utilities meta path typed_data vector_math]
- flutter_svg 1.0.3 [flutter meta path_drawing vector_math xml]
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta typed_data vector_math]
- google_sign_in_android 5.2.6 [flutter google_sign_in_platform_interface]
- google_sign_in_ios 5.2.6 [flutter google_sign_in_platform_interface]
- google_sign_in_platform_interface 2.1.2 [flutter quiver]
- google_sign_in_web 0.10.1 [flutter flutter_web_plugins google_sign_in_platform_interface js]
- http 0.13.4 [async http_parser meta path]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
- idb_shim 2.0.1 [sembast collection path js meta]
- intl 0.17.0 [clock path]
- js 0.6.3
- lints 1.0.1
- matcher 0.12.11 [stack_trace]
- material_color_utilities 0.1.3
- meta 1.7.0
- path 1.8.0
- path_drawing 1.0.0 [vector_math meta path_parsing flutter]
- path_parsing 1.0.0 [vector_math meta]
- path_provider 2.0.9 [flutter path_provider_android path_provider_ios path_provider_linux path_provider_macos path_provider_platform_interface path_provider_windows]
- path_provider_android 2.0.13 [flutter path_provider_platform_interface]
- path_provider_ios 2.0.8 [flutter path_provider_platform_interface]
- path_provider_linux 2.1.5 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_macos 2.0.5 [flutter path_provider_platform_interface]
- path_provider_platform_interface 2.0.3 [flutter platform plugin_platform_interface]
- path_provider_windows 2.0.5 [ffi flutter path path_provider_platform_interface win32]
- petitparser 4.4.0 [meta]
- platform 3.1.0
- plugin_platform_interface 2.1.2 [meta]
- process 4.2.4 [file path platform]
- pub_semver 2.1.1 [collection meta]
- quiver 3.0.1+1 [matcher]
- sembast 3.2.0 [meta path synchronized]
- sembast_sqflite 2.0.1 [sembast sqflite_common meta collection]
- sembast_web 2.0.1+1 [sembast idb_shim]
- sign_in_with_apple 3.3.0 [flutter meta sign_in_with_apple_platform_interface sign_in_with_apple_web]
- sign_in_with_apple_platform_interface 1.0.0 [flutter plugin_platform_interface meta]
- sign_in_with_apple_web 1.0.1 [flutter flutter_web_plugins sign_in_with_apple_platform_interface js]
- sky_engine 0.0.99
- source_span 1.8.1 [collection path term_glyph]
- sqflite 2.0.2+1 [flutter sqflite_common path]
- sqflite_common 2.2.1+1 [synchronized path meta]
- sqflite_common_ffi 2.1.1 [sqlite3 sqflite_common synchronized path meta]
- sqlite3 1.5.1 [collection ffi meta]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.0 [charcode source_span]
- synchronized 3.0.0+2
- tekartik_app_flutter_sqflite 0.5.1 [flutter sqflite sqflite_common_ffi sqflite_common process_run]
- tekartik_lints_flutter 0.1.2 [flutter_lints]
- term_glyph 1.2.0
- test_api 0.4.8 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- twitter_login 4.2.3 [flutter crypto http]
- typed_data 1.3.0 [collection]
- vector_math 2.1.1
- win32 2.5.2 [ffi]
- xdg_directories 0.2.0+1 [meta path process]
- xml 5.3.1 [collection meta petitparser]
- yaml 3.1.0 [collection source_span string_scanner]
```

</details>

---

**Comment by MarcVanDaele90** [comment] 2022-05-18 11:57
@Fieora Thanks for the update! Any idea when this fix will be released?

**Comment by darshankawar** [comment] 2022-05-18 12:38
Duplicate of https://github.com/firebase/flutterfire/issues/8700

See https://github.com/firebase/flutterfire/issues/8666#issuecomment-1125906200 and original flutter issue comment https://github.com/flutter/flutter/issues/103561#issuecomment-1129356149 and check out [this](https://docs.flutter.dev/development/tools/sdk/release-notes/release-notes-3.0.0#if-you-see-warnings-about-bindings) link for various solutions

Closing.

**Closed by darshankawar** 2022-05-18 12:38 UTC
Labels: type: bug, Needs Attention, in triage
