### ISSUE TITLE
🐛 [firebase_auth] TypeError: Cannot read properties of undefined (reading 'settings')

### ISSUE THREAD

**Issue by shovelmn12** [firebase/flutterfire#9097] opened 2022-07-14 08:20 UTC
## Bug report

**Describe the bug**
```
When trying to authenticate a user in flutter web using FirebaseAuth.signInWithPhoneNumber() I get an error saying:
TypeError: Cannot read properties of undefined (reading 'settings')
firebase_auth.js line 8390:
        this._recaptchaLoader = this.auth.settings.appVerificationDisabledForTesting
            ? new MockReCaptchaLoaderImpl()
            : new ReCaptchaLoaderImpl();

```
Was working before I upgraded to latest version

### Steps to reproduce

need to test will update with code later

### Expected behavior

User authenticates using phone number

### Sample project

Providing a minimal example project which demonstrates the bug in isolation from your main App _greatly_ enhances the chance of a timely fix.
Please link to the public repository URL.

---

## Additional context

My code:

```
await _auth.signInWithPhoneNumber(phone, RecaptchaVerifier());
```
I also tried without `RecaptchaVerifier()` parameter

html scripts:

```
<script src="https://www.gstatic.com/firebasejs/9.9.0/firebase-app.js"></script>
<script src="https://www.gstatic.com/firebasejs/9.9.0/firebase-analytics.js"></script>
<script src="https://www.gstatic.com/firebasejs/9.9.0/firebase-auth.js"></script>
<script src="https://www.gstatic.com/firebasejs/9.9.0/firebase-firestore.js"></script>

<!-- Firebase Configuration -->
<script>
      firebase.initializeApp({
        apiKey: "...",
        authDomain: "...",
        projectId: "...",
        storageBucket: "..."
        messagingSenderId: "...",
        appId: "...",
        measurementId: "..."
      });
</script>
```
I also run init from dart code:
```
FirebaseCore.initializeApp(
    options: const FirebaseOptions(
        apiKey: "...",
        authDomain: "...",
        projectId: "...",
        storageBucket: "..."
        messagingSenderId: "...",
        appId: "...",
        measurementId: "...",
      ),
)
```

Full error:

```
TypeError: Cannot read properties of undefined (reading 'settings')
https://www.gstatic.com/firebasejs/9.9.0/firebase-auth.js 8390:43                           new RecaptchaVerifier
../packages/firebase_auth_web/src/interop/auth.dart 998:32                                  new
../packages/firebase_auth_web/src/firebase_auth_web_recaptcha_verifier_factory.dart 89:30   new
../packages/firebase_auth_web/src/firebase_auth_web_recaptcha_verifier_factory.dart 101:12  delegateFor
../packages/firebase_auth/src/recaptcha_verifier.dart 57:16                                 new
../packages/sdk/auth.dart 155:65                                                            _webLogin
../dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54                       runBody
../dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 123:5                       _async
../packages/sdk/auth.dart 148:25                                                            [_webLogin]
../packages/sdk/auth.dart 77:11                                                             login
../packages/blocs/login/bloc.dart 51:30                                                     <fn>
../dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54                       runBody
../dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 123:5                       _async
../packages/blocs/login/bloc.dart 43:17                                                     <fn>
../core/lib/login/model.freezed.dart 321:19                                                 maybeMap
../packages/blocs/login/bloc.dart 42:32                                                     send
../packages/app/screens/auth/login/actions/login.dart 9:28                                  <fn>
../packages/flutter/src/material/ink_well.dart 1005:21                                      [_handleTap]
../packages/flutter/src/gestures/recognizer.dart 198:24                                     invokeCallback
../packages/flutter/src/gestures/tap.dart 613:48                                            handleTapUp
../packages/flutter/src/gestures/tap.dart 298:5                                             [_checkUp]
../packages/flutter/src/gestures/tap.dart 232:7                                             handlePrimaryPointer
../packages/flutter/src/gestures/recognizer.dart 563:9                                      handleEvent
../packages/flutter/src/gestures/pointer_router.dart 94:12                                  [_dispatch]
../packages/flutter/src/gestures/pointer_router.dart 139:9                                  <fn>
../dart-sdk/lib/_internal/js_dev_runtime/private/linked_hash_map.dart 21:13                 forEach
../packages/flutter/src/gestures/pointer_router.dart 137:17                                 [_dispatchEventToRoutes]
../packages/flutter/src/gestures/pointer_router.dart 123:7                                  route
../packages/flutter/src/gestures/binding.dart 445:19                                        handleEvent
../packages/flutter/src/gestures/binding.dart 425:14                                        dispatchEvent
../packages/flutter/src/rendering/binding.dart 329:11                                       dispatchEvent
../packages/flutter/src/gestures/binding.dart 380:7                                         [_handlePointerEventImmediately]
../packages/flutter/src/gestures/binding.dart 344:5                                         handlePointerEvent
../packages/flutter/src/gestures/binding.dart 302:7                                         [_flushPointerEventQueue]
../packages/flutter/src/gestures/binding.dart 285:32                                        [_handlePointerDataPacket]
../lib/_engine/engine/platform_dispatcher.dart 1105:13                                      invoke1
../lib/_engine/engine/platform_dispatcher.dart 185:5                                        invokeOnPointerDataPacket
../lib/_engine/engine/pointer_binding.dart 130:39                                           [_onPointerData]
../lib/_engine/engine/pointer_binding.dart 543:18                                           <fn>
../lib/_engine/engine/pointer_binding.dart 496:21                                           <fn>
../lib/_engine/engine/pointer_binding.dart 210:16                                           loggedHandler
```

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.4, on macOS 12.4 21F79 darwin-arm, locale en-NO)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] IntelliJ IDEA Community Edition (version 2022.1.3)
[✓] VS Code (version 1.69.1)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.17.5
Flutter SDK 3.0.4
app 0.0.1+1

dependencies:
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- theme 0.0.1 [flutter build_context visibility_detector flutter_web_frame wouter blocs localizations utils]

dev dependencies:
- flutter_lints 1.0.4 [lints]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher material_color_utilities meta source_span stream_channel string_scanner term_glyph]

transitive dependencies:
- _fe_analyzer_shared 40.0.0 [meta]
- analyzer 4.1.0 [_fe_analyzer_shared collection convert crypto glob meta package_config path pub_semver source_span watcher yaml]
- args 2.3.1
- async 2.8.2 [collection meta]
- bloc 8.0.3 [meta]
- blocs 0.0.1 [flutter flutter_bloc provider sdk utils localizations]
- boolean_selector 2.1.0 [source_span string_scanner]
- build 2.3.0 [analyzer async convert crypto glob logging meta path]
- build_config 1.0.0 [checked_yaml json_annotation path pubspec_parse yaml]
- build_context 3.0.0 [flutter]
- characters 1.2.0
- charcode 1.3.1
- checked_yaml 2.0.1 [json_annotation source_span yaml]
- clock 1.1.0
- cloud_firestore 3.3.0 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_interface flutter meta]
- cloud_firestore_platform_interface 5.6.0 [collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 2.7.0 [cloud_firestore_platform_interface collection firebase_core firebase_core_web flutter flutter_web_plugins js]
- collection 1.16.0
- convert 3.0.2 [typed_data]
- core 0.0.1 [flutter freezed_annotation json_annotation tuple cloud_firestore localizations]
- crypto 3.0.2 [typed_data]
- dart_style 2.2.3 [analyzer args path pub_semver source_span]
- fake_async 1.3.0 [clock collection]
- file 6.1.2 [meta path]
- firebase_analytics 9.2.0 [firebase_analytics_platform_interface firebase_analytics_web firebase_core firebase_core_platform_interface flutter]
- firebase_analytics_platform_interface 3.2.0 [firebase_core flutter meta plugin_platform_interface]
- firebase_analytics_web 0.4.1 [firebase_analytics_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- firebase_auth 3.4.2 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_auth_platform_interface 6.3.2 [firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 4.0.0 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core 1.19.2 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_core_platform_interface 4.4.3 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 1.7.0 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- flutter_bloc 8.0.1 [flutter bloc provider]
- flutter_contacts 1.1.5 [flutter]
- flutter_localizations 0.0.0 [flutter intl characters clock collection material_color_utilities meta path vector_math]
- flutter_web_frame 0.0.3 [flutter]
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta vector_math]
- freezed_annotation 2.0.3 [collection json_annotation meta]
- glob 2.1.0 [async collection file path string_scanner]
- http_parser 4.0.1 [collection source_span string_scanner typed_data]
- i18n 3.4.1 [build build_config dart_style yaml quick_log]
- intl 0.17.0 [clock path]
- js 0.6.4
- json_annotation 4.6.0 [meta]
- lints 1.0.1
- listenable_stream 1.1.0 [rxdart flutter]
- localizations 0.0.1 [flutter flutter_localizations i18n utils]
- logger 1.1.0
- logging 1.0.2
- matcher 0.12.11 [stack_trace]
- material_color_utilities 0.1.4
- meta 1.7.0
- mime 1.0.2
- nested 1.0.0 [flutter]
- package_config 2.1.0 [path]
- path 1.8.1
- path_to_regexp 0.4.0
- plugin_platform_interface 2.1.2 [meta]
- provider 6.0.3 [collection flutter nested]
- pub_semver 2.1.1 [collection meta]
- pubspec_parse 1.2.0 [checked_yaml collection json_annotation pub_semver yaml]
- quick_log 5.2.1 [path rxdart]
- quiver 3.1.0 [matcher]
- rxdart 0.27.4
- sdk 0.0.1 [flutter firebase_core firebase_auth cloud_firestore firebase_analytics rxdart core utils]
- share_plus 4.0.9 [meta mime flutter share_plus_platform_interface share_plus_linux share_plus_macos share_plus_windows share_plus_web]
- share_plus_linux 3.0.0 [share_plus_platform_interface file flutter meta url_launcher]
- share_plus_macos 3.0.1 [share_plus_platform_interface flutter]
- share_plus_platform_interface 3.0.3 [flutter meta mime plugin_platform_interface]
- share_plus_web 3.0.1 [share_plus_platform_interface url_launcher flutter flutter_web_plugins meta]
- share_plus_windows 3.0.1 [share_plus_platform_interface flutter meta url_launcher]
- sky_engine 0.0.99
- source_span 1.8.2 [collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.0 [charcode source_span]
- term_glyph 1.2.0
- test_api 0.4.9 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- tuple 2.0.0 [quiver]
- typed_data 1.3.1 [collection]
- url_launcher 6.1.3 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- url_launcher_android 6.0.17 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.0.17 [flutter url_launcher_platform_interface]
- url_launcher_linux 3.0.1 [flutter url_launcher_platform_interface]
- url_launcher_macos 3.0.1 [flutter url_launcher_platform_interface]
- url_launcher_platform_interface 2.1.0 [flutter plugin_platform_interface]
- url_launcher_web 2.0.12 [flutter flutter_web_plugins url_launcher_platform_interface]
- url_launcher_windows 3.0.1 [flutter url_launcher_platform_interface]
- url_strategy 0.2.0 [flutter_web_plugins]
- utils 0.0.1 [flutter rxdart listenable_stream url_strategy flutter_contacts intl share_plus characters collection logger core]
- vector_math 2.1.2
- visibility_detector 0.2.2 [flutter]
- watcher 1.0.1 [async path]
- wouter 0.1.8 [flutter freezed_annotation provider path path_to_regexp collection]
- yaml 3.1.1 [collection source_span string_scanner]
```

</details>

---

**Comment by HoaLebao** [comment] 2022-07-14 09:18
I got the same issue after upgraded flutter and pub. It worked properly before.

Flutter doctor:
[√] Flutter (Channel stable, 3.0.5, on Microsoft Windows [Version 10.0.19043.1766], locale en-US)
    • Flutter version 3.0.5 
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (15 hours ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

pub:
  firebase_auth: ^3.4.2
  firebase_core: ^1.19.2

**Comment by HoaLebao** [comment] 2022-07-14 11:03
> @shovelmn12 @HoaLebao Try below solutions and see if they work for you:
> 
> [#7999 (comment)](https://github.com/firebase/flutterfire/issues/7999#issuecomment-1042951914) [#7999 (comment)](https://github.com/firebase/flutterfire/issues/7999#issuecomment-1046197711)

I am not sure if your solution works because I didn't declare Js files in the index.html. What I did is to roll back to previous version of firebase packages in the pubspec.yaml and it is working properly again.

Pub:
  firebase_auth: 3.4.1
  firebase_auth_platform_interface: 6.3.1
  firebase_core: 1.19.1
  firebase_core_web: 1.6.6

**Comment by edhom** [comment] 2022-07-14 11:20
@darshankawar `firebase_auth_web v4.0.0` uses Firebase v9 JS SDK. https://github.com/firebase/flutterfire/issues/7999#issuecomment-1042951914 and https://github.com/firebase/flutterfire/issues/7999#issuecomment-1046197711 suggest to import `8.10.0`, does that work? 

We're also facing problems after updating to `firebase_auth 3.4.2`. In our case `Error: FirebaseError: Firebase: Error (auth/argument-error).`

**Comment by shovelmn12** [comment] 2022-07-14 12:16
I tried importing v8.10.0 v8.10.1 and v9.9.0 none of them worked

**Comment by binlebin** [comment] 2022-07-14 21:16
Pump, I have the same problem after upgrading to firebase_auth: 3.4.2

**Comment by darshankawar** [comment] 2022-07-18 09:36
Thanks for the update. Using firebase_auth plugin [example](https://github.com/firebase/flutterfire/tree/master/packages/firebase_auth/firebase_auth/example) and running on latest master `(Channel master, 3.1.0-0.0.pre.1698)` with below dependency versions, trying to `signInWithPhoneNumber()` is giving below error, same as reported above:

```
  firebase_auth: ^3.4.2
  firebase_auth_web: ^4.0.0
  firebase_core: ^1.19.2
```

<details>
<summary> console error log </summary>

```
dhs@Dhss-MacBook-Pro firebase_auth_example % flutter run -d chrome
Launching lib/main.dart on Chrome in debug mode...
Waiting for connection from debug service on Chrome...             20.0s
This app is linked to the debug service: ws://127.0.0.1:51230/cPk9ioz20eM=/ws
Debug service listening on ws://127.0.0.1:51230/cPk9ioz20eM=/ws

Running with unsound null safety
For more information see https://dart.dev/null-safety/unsound-null-safety

🔥  To hot restart changes while running, press "r" or "R".
For a more detailed help message, press "h". To quit, press "q".

An Observatory debugger and profiler on Chrome is available at: http://127.0.0.1:51230/cPk9ioz20eM=
Flutter Web Bootstrap: Auto
The Flutter DevTools debugger and profiler on Chrome is available at: http://127.0.0.1:9100?uri=http://127.0.0.1:51230/cPk9ioz20eM=
TypeError: Cannot read properties of undefined (reading 'auth')
packages/firebase_auth_web/src/interop/auth.dart 24:26                                                        getAuthInstance
packages/firebase_auth_web/firebase_auth_web.dart 98:22                                                       get [_delegate]
packages/firebase_auth_web/firebase_auth_web.dart 53:8                                                        new
packages/firebase_auth_web/firebase_auth_web.dart 103:12                                                      delegateFor
packages/firebase_auth_platform_interface/src/platform_interface/platform_interface_firebase_auth.dart 55:64  instanceFor
packages/firebase_auth/src/firebase_auth.dart 23:55                                                           get [_delegate]
packages/firebase_auth/src/firebase_auth.dart 134:21                                                          useAuthEmulator
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54                                            runBody
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 123:5                                            _async
packages/firebase_auth/src/firebase_auth.dart 123:31                                                          useAuthEmulator
packages/triage/main.dart 22:31                                                                               main$
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50                                            <fn>
dart-sdk/lib/async/zone.dart 1653:54                                                                          runUnary
dart-sdk/lib/async/future_impl.dart 147:18                                                                    handleValue
dart-sdk/lib/async/future_impl.dart 766:44                                                                    handleValueCallback
dart-sdk/lib/async/future_impl.dart 795:13                                                                    _propagateToListeners
dart-sdk/lib/async/future_impl.dart 566:5                                                                     [_completeWithValue]
dart-sdk/lib/async/future.dart 528:22                                                                         <fn>
dart-sdk/lib/async/zone.dart 1653:54                                                                          runUnary
dart-sdk/lib/async/future_impl.dart 147:18                                                                    handleValue
dart-sdk/lib/async/future_impl.dart 766:44                                                                    handleValueCallback
dart-sdk/lib/async/future_impl.dart 795:13                                                                    _propagateToListeners
dart-sdk/lib/async/future_impl.dart 566:5                                                                     [_completeWithValue]
dart-sdk/lib/async/future_impl.dart 639:7                                                                     callback
dart-sdk/lib/async/schedule_microtask.dart 40:11                                                              _microtaskLoop
dart-sdk/lib/async/schedule_microtask.dart 49:5                                                               _startMicrotaskLoop
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 166:15                                           <fn>

```

</details>

**Comment by russellwheatley** [comment] 2022-07-19 08:20
I took a look at this and reproduced on the web JS SDK. See here: https://github.com/firebase/firebase-js-sdk/issues/6445 Will update this channel once I receive feedback 👍

**Comment by shovelmn12** [comment] 2022-07-19 10:03
I just tried to revert to old packages:
```
  firebase_core: ^1.17.1
  firebase_auth: ^3.3.19
  cloud_firestore: ^3.1.17
  firebase_analytics: ^9.1.9
```
and:
```
<script src="https://www.gstatic.com/firebasejs/8.10.0/firebase-app.js"></script>
<script src="https://www.gstatic.com/firebasejs/8.10.0/firebase-analytics.js"></script>
<script src="https://www.gstatic.com/firebasejs/8.10.0/firebase-auth.js"></script>
<script src="https://www.gstatic.com/firebasejs/8.10.0/firebase-firestore.js"></script>
```

But still getting the same error.
Also I noticed that v9.9.0 packages are loaded in the web:
<img width="231" alt="Screenshot 2022-07-19 at 12 01 07" src="https://user-images.githubusercontent.com/39903489/179724724-11d092f2-53e9-4e41-9939-a98709f13cd4.png">

**Comment by tedcrimson** [comment] 2022-07-19 10:11
> I just tried to revert to old packages:
> ```
>   firebase_core: ^1.17.1
>   firebase_auth: ^3.3.19
>   cloud_firestore: ^3.1.17
>   firebase_analytics: ^9.1.9
> ```
> and:
> ```
> <script src="https://www.gstatic.com/firebasejs/8.10.0/firebase-app.js"></script>
> <script src="https://www.gstatic.com/firebasejs/8.10.0/firebase-analytics.js"></script>
> <script src="https://www.gstatic.com/firebasejs/8.10.0/firebase-auth.js"></script>
> <script src="https://www.gstatic.com/firebasejs/8.10.0/firebase-firestore.js"></script>
> ```
> 
> But still getting the same error.
> Also I noticed that v9.9.0 packages are loaded in the web:
> <img width="231" alt="Screenshot 2022-07-19 at 12 01 07" src="https://user-images.githubusercontent.com/39903489/179724724-11d092f2-53e9-4e41-9939-a98709f13cd4.png">

Can you downgrade firebase_core_web and firebase_auth_web versions as well?

**Comment by nbpatel94** [comment] 2022-07-20 04:41
Same issue i am facing

**Comment by monkeydaichan** [comment] 2022-07-20 04:42
Same issue i am facing

**Comment by russellwheatley** [comment] 2022-07-20 08:18
Hey folks, this issue has now been resolved. We needed to pass in auth instance to `RecaptchaVerifier` [here](https://github.com/firebase/flutterfire/blob/master/packages/firebase_auth/firebase_auth_web/lib/src/interop/auth.dart#L997) which was merged with the [multi factor authentication PR](https://github.com/firebase/flutterfire/pull/9044). We will be releasing a new version tomorrow 🙏

**Closed by russellwheatley** 2022-07-20 08:18 UTC
Labels: type: bug, plugin: auth, platform: web, type: crash

**Comment by mklepaczko** [comment] 2022-07-20 09:03
Thanks for the update, waiting for it:)

**Comment by kekko7072** [comment] 2022-07-20 20:25
+ 1

**Comment by mklepaczko** [comment] 2022-07-21 13:21
firebase_auth 3.5.0 published, works great :)
Thanks for the fix.

**Comment by tedcrimson** [comment] 2022-07-22 09:01
```
Because firebase_auth >=3.5.0 depends on firebase_auth_platform_interface ^6.4.0 which depends on collection ^1.16.0, firebase_auth >=3.5.0 requires collection ^1.16.0.
And because every version of flutter from sdk depends on collection 1.15.0, firebase_auth >=3.5.0 is incompatible with flutter from SDK.
```

Flutter (Channel stable, 2.10.3, on Mac OS X 10.15.7 19H1419 darwin-x64,locale en-US)

**Comment by cedvdb** [comment] 2022-07-22 11:25
Is anyone else disconnected after hot restart after the fix ?

**Comment by mklepaczko** [comment] 2022-07-22 11:32
> Is anyone else unauthenticated after hot restart with the fix ?

Yeah... hard week for the firebase auth team, another big bug...
https://github.com/firebase/flutterfire/issues/9089#issuecomment-1192341089
