### ISSUE TITLE
FirebaseMessaging.onMessage.listen is called twice

### ISSUE THREAD

**Issue by mkassir95** [firebase/flutterfire#9962] opened 2022-11-18 10:59 UTC
FirebaseMessaging.onMessage.listen is called twice

**Comment by darshankawar** [comment] 2022-11-18 13:14
Closing as duplicate of https://github.com/firebase/flutterfire/issues/9912. Please upgrade plugin version to latest to see the fix.

**Closed by darshankawar** 2022-11-18 13:14 UTC
Labels: type: bug, Needs Attention, in triage
