### ISSUE TITLE
🐛 [firebase_auth] 'PigeonParser.h' file not found flutter macOS

### ISSUE THREAD

**Issue by suysoftware** [firebase/flutterfire#11722] opened 2023-10-17 18:15 UTC
I update new firebase auth in flutter but when I tried build my app ı got this exception.

/Users/suy/.pub-cache/hosted/pub.dev/firebase_auth-4.11.0/macos/Classes/PigeonParser.m:5:9: fatal error: 'PigeonParser.h' file not found
#import "PigeonParser.h"
        ^~~~~~~~~~~~~~~~

<details><summary>Flutter Doctor</summary>
<p>
Doctor summary (to see all details, run flutter doctor -v):

- [✓] Flutter (Channel stable, 3.13.6, on macOS 13.3.1 22E772610a darwin-arm64, locale en-TR)
- [✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
- [✓] Xcode - develop for iOS and macOS (Xcode 14.2)
- [✓] Chrome - develop for the web
- [!] Android Studio (version 2022.1)
      - ✗ Unable to find bundled Java version.
- [✓] Android Studio (version 2020.3)
- [✓] VS Code (version 1.74.3)
- [✓] VS Code (version 1.83.0)
- [✓] Connected device (2 available)
- [✓] Network resources
</p>
</details>

**Comment by Martinaude** [comment] 2023-10-18 09:49
Same issue on my side - had to revert back to 4.10.1 for app to build successfully.

**Comment by darshankawar** [comment] 2023-10-18 10:33
Closing this as a duplicate of https://github.com/firebase/flutterfire/issues/11720. Please follow-up in that issue for further updates.

**Closed by darshankawar** 2023-10-18 10:33 UTC
Labels: type: bug, Needs Attention, in triage
