### ISSUE TITLE
🐛 [firebase] crashes on release mode

### ISSUE THREAD

**Issue by shovelmn12** [firebase/flutterfire#11952] opened 2023-11-27 20:01 UTC
## Bug report

**Describe the bug**

When running flutter in release mode the app crashes when using minify.

Error details:

```
E/AndroidRuntime(21852): FATAL EXCEPTION: ScionFrontendApi
E/AndroidRuntime(21852): Process: me.stackby.app, PID: 21852
E/AndroidRuntime(21852): java.lang.ExceptionInInitializerError
E/AndroidRuntime(21852): 	at com.google.android.gms.measurement.internal.z2.<init>(Unknown Source:38)
E/AndroidRuntime(21852): 	at com.google.android.gms.measurement.internal.j2.<init>(SourceFile:184)
E/AndroidRuntime(21852): 	at com.google.android.gms.measurement.internal.j2.e(SourceFile:1)
E/AndroidRuntime(21852): 	at com.google.android.gms.measurement.internal.AppMeasurementDynamiteService.initialize(SourceFile:1)
E/AndroidRuntime(21852): 	at com.google.android.gms.internal.measurement.n0.a(SourceFile:109)
E/AndroidRuntime(21852): 	at com.google.android.gms.internal.measurement.h0.run(Unknown Source:12)
E/AndroidRuntime(21852): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
E/AndroidRuntime(21852): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
E/AndroidRuntime(21852): 	at java.lang.Thread.run(Thread.java:1012)
E/AndroidRuntime(21852): Caused by: java.lang.RuntimeException: java.lang.NoSuchMethodException: A1.g.values []
E/AndroidRuntime(21852): 	at java.lang.Enum.enumValues(Enum.java:315)
E/AndroidRuntime(21852): 	at java.lang.Enum.-$$Nest$smenumValues(Unknown Source:0)
E/AndroidRuntime(21852): 	at java.lang.Enum$1.create(Enum.java:322)
E/AndroidRuntime(21852): 	at java.lang.Enum$1.create(Enum.java:320)
E/AndroidRuntime(21852): 	at libcore.util.BasicLruCache.get(BasicLruCache.java:63)
E/AndroidRuntime(21852): 	at java.lang.Enum.getSharedConstants(Enum.java:334)
E/AndroidRuntime(21852): 	at java.lang.Class.getEnumConstantsShared(Class.java:4036)
E/AndroidRuntime(21852): 	at java.util.EnumMap.getKeyUniverse(EnumMap.java:749)
E/AndroidRuntime(21852): 	at java.util.EnumMap.<init>(EnumMap.java:136)
E/AndroidRuntime(21852): 	at com.google.android.gms.measurement.internal.x2.<init>(SourceFile:1)
E/AndroidRuntime(21852): 	at com.google.android.gms.measurement.internal.x2.<clinit>(Unknown Source:5)
```

### Expected behavior

not crash while using minify

## Additional context

Seems like minify causes the issue.
I am not the only one with the issue:

https://github.com/firebase/flutterfire/issues/11483
https://github.com/firebase/flutterfire/issues/9376
https://github.com/firebase/flutterfire/issues/11134
https://stackoverflow.com/questions/74954512/crash-with-appmeasurementdynamiteservice

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 3.16.0, on macOS 14.1.1 23B81 darwin-x64, locale en-NO)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✓] Android Studio (version 2022.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.1)
[✓] IntelliJ IDEA Community Edition (version 2023.2.1)
[✓] VS Code (version 1.84.2)
[✓] Connected device (1 available)
[✓] Network resources

• No issues found!

```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 3.2.0
Flutter SDK 3.16.0
stack_app 1.0.0+1

dependencies:
- android_id 0.3.6 [flutter]
- auth0_flutter 1.3.1 [auth0_flutter_platform_interface flutter flutter_web_plugins js]
- bloc_concurrency 0.2.2 [bloc stream_transform]
- cached_network_image 3.3.0 [cached_network_image_platform_interface cached_network_image_web flutter flutter_cache_manager octo_image]
- collection 1.18.0
- connectivity_plus 5.0.2 [flutter flutter_web_plugins connectivity_plus_platform_interface js meta nm]
- country_code 1.0.0
- device_info_plus 9.1.1 [device_info_plus_platform_interface ffi file flutter flutter_web_plugins meta win32 win32_registry]
- duration 3.0.13
- firebase_analytics 10.7.1 [firebase_analytics_platform_interface firebase_analytics_web firebase_core firebase_core_platform_interface flutter]
- firebase_core 2.23.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_crashlytics 3.4.5 [firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface flutter stack_trace]
- firebase_messaging 14.7.5 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- firebase_remote_config 4.3.5 [firebase_core firebase_core_platform_interface firebase_remote_config_platform_interface firebase_remote_config_web flutter]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math web sky_engine]
- flutter_bloc 8.1.3 [bloc flutter provider]
- flutter_localizations 0.0.0 [flutter intl characters clock collection material_color_utilities meta path vector_math web]
- fpdart 1.1.0
- freezed_annotation 2.4.1 [collection json_annotation meta]
- i18n 4.0.8 [build build_config dart_style yaml quick_log glob]
- intl 0.18.1 [clock meta path]
- json_annotation 4.8.1 [meta]
- logger 2.0.2+1
- package_info_plus 5.0.1 [ffi flutter flutter_web_plugins http meta path package_info_plus_platform_interface web win32]
- permission_handler 11.1.0 [flutter meta permission_handler_android permission_handler_apple permission_handler_html permission_handler_windows permission_handler_platform_interface]
- provider 6.1.1 [collection flutter nested]
- rxdart 0.27.7
- shimmer 3.0.0 [flutter]
- timeago_flutter 3.6.0 [timeago flutter]
- url_launcher 6.2.1 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- uuid 4.2.1 [crypto sprintf meta]
- video_player 2.8.1 [flutter html video_player_android video_player_avfoundation video_player_platform_interface video_player_web]
- web_socket_channel 2.4.0 [async crypto stream_channel]
- wouter 0.1.8 [flutter freezed_annotation provider path path_to_regexp collection rxdart]

dev dependencies:
- bloc_test 9.1.5 [bloc diff_match_patch meta mocktail test]
- build_runner 2.4.6 [analyzer args async build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style frontend_server_client glob graphs http_multi_server io js logging meta mime package_config path pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web_socket_channel yaml]
- flutter_lints 3.0.1 [lints]
- flutter_test 0.0.0 [flutter test_api matcher path fake_async clock stack_trace vector_math async boolean_selector characters collection material_color_utilities meta source_span stream_channel string_scanner term_glyph web]
- freezed 2.4.5 [analyzer build build_config collection meta source_gen freezed_annotation json_annotation]
- json_serializable 6.7.1 [analyzer async build build_config collection json_annotation meta path pub_semver pubspec_parse source_gen source_helper]
- mocktail 1.0.1 [collection matcher test_api]
- patrol 3.0.3 [equatable flutter flutter_test http json_annotation meta patrol_finders shelf test_api]

dependency overrides:
- _fe_analyzer_shared 65.0.0 [meta]
- analyzer 6.3.0 [_fe_analyzer_shared collection convert crypto glob meta package_config path pub_semver source_span watcher yaml]
- auth0_flutter_platform_interface 1.3.1 [flutter plugin_platform_interface]
- http 1.1.1 [async http_parser meta web]
- material_color_utilities 0.8.0 [collection]
- meta 1.11.0
- web 0.4.0

transitive dependencies:
- _flutterfire_internals 1.3.13 [collection firebase_core firebase_core_platform_interface flutter meta]
- args 2.4.2
- async 2.11.0 [collection meta]
- bloc 8.1.2 [meta]
- boolean_selector 2.1.1 [source_span string_scanner]
- build 2.4.1 [analyzer async convert crypto glob logging meta package_config path]
- build_config 1.1.1 [checked_yaml json_annotation path pubspec_parse yaml]
- build_daemon 4.0.1 [built_collection built_value crypto http_multi_server logging path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 2.4.1 [analyzer async build collection convert crypto graphs logging package_config path pool pub_semver stream_transform yaml]
- build_runner_core 7.2.11 [async build build_config build_resolvers collection convert crypto glob graphs json_annotation logging meta package_config path pool timing watcher yaml]
- built_collection 5.1.1
- built_value 8.7.0 [built_collection collection fixnum meta]
- cached_network_image_platform_interface 3.0.0 [flutter flutter_cache_manager]
- cached_network_image_web 1.1.0 [cached_network_image_platform_interface flutter flutter_cache_manager]
- characters 1.3.0
- checked_yaml 2.0.3 [json_annotation source_span yaml]
- clock 1.1.1
- code_builder 4.8.0 [built_collection built_value collection matcher meta]
- connectivity_plus_platform_interface 1.2.4 [flutter meta plugin_platform_interface]
- convert 3.1.1 [typed_data]
- coverage 1.7.1 [args logging package_config path source_maps stack_trace vm_service]
- crypto 3.0.3 [typed_data]
- csslib 1.0.0 [source_span]
- dart_style 2.3.4 [analyzer args collection path pub_semver source_span]
- dbus 0.7.10 [args ffi meta xml]
- device_info_plus_platform_interface 7.0.0 [flutter meta plugin_platform_interface]
- diff_match_patch 0.4.1
- equatable 2.0.5 [collection meta]
- fake_async 1.3.1 [clock collection]
- ffi 2.1.0
- file 7.0.0 [meta path]
- firebase_analytics_platform_interface 3.8.1 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_analytics_web 0.5.5+8 [_flutterfire_internals firebase_analytics_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- firebase_core_platform_interface 5.0.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.8.1 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_crashlytics_platform_interface 3.6.13 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_platform_interface 4.5.14 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 3.5.14 [_flutterfire_internals firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]
- firebase_remote_config_platform_interface 1.4.13 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_remote_config_web 1.4.13 [firebase_core firebase_core_web firebase_remote_config_platform_interface flutter flutter_web_plugins js]
- fixnum 1.1.0
- flutter_cache_manager 3.3.1 [clock collection file flutter http path path_provider rxdart sqflite uuid]
- flutter_web_plugins 0.0.0 [flutter characters collection material_color_utilities meta vector_math web]
- frontend_server_client 3.2.0 [async path]
- glob 2.1.2 [async collection file path string_scanner]
- graphs 2.3.1 [collection]
- html 0.15.4 [csslib source_span]
- http_multi_server 3.2.1 [async]
- http_parser 4.0.2 [collection source_span string_scanner typed_data]
- io 1.0.4 [meta path string_scanner]
- js 0.6.7 [meta]
- lints 3.0.0
- logging 1.2.0
- matcher 0.12.16 [async meta stack_trace term_glyph test_api]
- mime 1.0.4
- nested 1.0.0 [flutter]
- nm 0.5.0 [dbus]
- node_preamble 2.0.2
- octo_image 2.0.0 [flutter]
- package_config 2.1.0 [path]
- package_info_plus_platform_interface 2.0.1 [flutter meta plugin_platform_interface]
- path 1.8.3
- path_provider 2.1.1 [flutter path_provider_android path_provider_foundation path_provider_linux path_provider_platform_interface path_provider_windows]
- path_provider_android 2.2.1 [flutter path_provider_platform_interface]
- path_provider_foundation 2.3.1 [flutter path_provider_platform_interface]
- path_provider_linux 2.2.1 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_platform_interface 2.1.1 [flutter platform plugin_platform_interface]
- path_provider_windows 2.2.1 [ffi flutter path path_provider_platform_interface win32]
- path_to_regexp 0.4.0
- patrol_finders 2.0.1+1 [flutter flutter_test meta]
- permission_handler_android 12.0.1 [flutter permission_handler_platform_interface]
- permission_handler_apple 9.2.0 [flutter permission_handler_platform_interface]
- permission_handler_html 0.1.0+1 [flutter flutter_web_plugins permission_handler_platform_interface]
- permission_handler_platform_interface 4.0.2 [flutter meta plugin_platform_interface]
- permission_handler_windows 0.2.0 [flutter permission_handler_platform_interface]
- petitparser 6.0.1 [meta]
- platform 3.1.3
- plugin_platform_interface 2.1.7 [meta]
- pool 1.5.1 [async stack_trace]
- pub_semver 2.1.4 [collection meta]
- pubspec_parse 1.2.3 [checked_yaml collection json_annotation pub_semver yaml]
- quick_log 5.3.1 [path rxdart]
- shelf 1.4.1 [async collection http_parser path stack_trace stream_channel]
- shelf_packages_handler 3.0.2 [path shelf shelf_static]
- shelf_static 1.1.2 [convert http_parser mime path shelf]
- shelf_web_socket 1.0.4 [shelf stream_channel web_socket_channel]
- sky_engine 0.0.99
- source_gen 1.4.0 [analyzer async build dart_style glob path source_span yaml]
- source_helper 1.3.4 [analyzer collection source_gen]
- source_map_stack_trace 2.1.1 [path source_maps stack_trace]
- source_maps 0.10.12 [source_span]
- source_span 1.10.0 [collection path term_glyph]
- sprintf 7.0.0
- sqflite 2.3.0 [flutter sqflite_common path]
- sqflite_common 2.5.0+2 [synchronized path meta]
- stack_trace 1.11.1 [path]
- stream_channel 2.1.2 [async]
- stream_transform 2.1.0
- string_scanner 1.2.0 [source_span]
- synchronized 3.1.0
- term_glyph 1.2.1
- test 1.24.9 [analyzer async boolean_selector collection coverage http_multi_server io js matcher node_preamble package_config path pool shelf shelf_packages_handler shelf_static shelf_web_socket source_span stack_trace stream_channel test_api test_core typed_data web_socket_channel webkit_inspection_protocol yaml]
- test_api 0.6.1 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph]
- test_core 0.5.9 [analyzer args async boolean_selector collection coverage frontend_server_client glob io meta package_config path pool source_map_stack_trace source_maps source_span stack_trace stream_channel test_api vm_service yaml]
- timeago 3.6.0 [intl]
- timing 1.0.1 [json_annotation]
- typed_data 1.3.2 [collection]
- url_launcher_android 6.2.0 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.2.1 [flutter url_launcher_platform_interface]
- url_launcher_linux 3.1.0 [flutter url_launcher_platform_interface]
- url_launcher_macos 3.1.0 [flutter url_launcher_platform_interface]
- url_launcher_platform_interface 2.2.0 [flutter plugin_platform_interface]
- url_launcher_web 2.2.1 [flutter flutter_web_plugins url_launcher_platform_interface web]
- url_launcher_windows 3.1.0 [flutter url_launcher_platform_interface]
- vector_math 2.1.4
- video_player_android 2.4.10 [flutter video_player_platform_interface]
- video_player_avfoundation 2.5.2 [flutter video_player_platform_interface]
- video_player_platform_interface 6.2.1 [flutter plugin_platform_interface]
- video_player_web 2.1.2 [flutter flutter_web_plugins video_player_platform_interface]
- vm_service 13.0.0
- watcher 1.1.0 [async path]
- webkit_inspection_protocol 1.2.1 [logging]
- win32 5.1.0 [ffi]
- win32_registry 1.1.2 [ffi win32]
- xdg_directories 1.0.3 [meta path]
- xml 6.4.2 [collection meta petitparser]
- yaml 3.1.2 [collection source_span string_scanner]
```

</details>

---

### Temp solution

Disable minify in `app/build.gradle`:

```
            minifyEnabled false
            shrinkResources false
```

**Comment by danagbemava-nc** [comment] 2023-11-28 11:43
Closing this as a duplicate of https://github.com/firebase/flutterfire/issues/11483

**Closed by danagbemava-nc** 2023-11-28 11:43 UTC
Labels: type: bug, Needs Attention, in triage

**Comment by shovelmn12** [comment] 2023-11-28 14:16
Why is it marked as not planned ?

**Comment by danagbemava-nc** [comment] 2023-11-29 11:06
This issue in particular is marked as not planned because it will be addressed in a different issue. It doesn't mean the issue itself will not be fixed.
