### ISSUE TITLE
[firebase_messaging]:  FirebaseMessaging.onBackgroundMessage method does not execute when a notification is received on iOS

### ISSUE THREAD

**Issue by VictorJGarciaMartin** [firebase/flutterfire#16882] opened 2024-12-15 19:44 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you aware of the differences between iOS and Android background message handling?

- [X] I understand that iOS and Android background messages behave differently, and I've designed my application with that in mind.

### Do you have an active Apple Developer account?

- [X] I have an active Apple Developer account.

### Are you using a physical iOS device to test background messages?

- [X] I am using a physical iOS device to test background messages.

### Have you enabled "Remote Notifications" & "Background Mode" (Checking options for "Background Processing" & "Remote Notifications") in your app's Xcode project?

<img width="1785" alt="captura_pantalla_1" src="https://github.com/user-attachments/assets/11f76e59-1213-4b51-a0d2-7e90f1e0bcbc" />

### Have you created an APNs key in your Apple Developer account & uploaded this APNs key to your Firebase console?

<img width="1539" alt="captura_pantalla_2" src="https://github.com/user-attachments/assets/1577a610-7106-4310-9e75-e68f2c61c714" />

### Have you disabled method swizzling for Firebase in your app?

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CADisableMinimumFrameDurationOnPhone</key>
	<true/>
	<key>CFBundleDevelopmentRegion</key>
	<string>$(DEVELOPMENT_LANGUAGE)</string>
	<key>CFBundleDisplayName</key>
	<string>Prueba Notificaciones Cabb</string>
	<key>CFBundleExecutable</key>
	<string>$(EXECUTABLE_NAME)</string>
	<key>CFBundleIdentifier</key>
	<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>prueba_notificaciones_cabb</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>$(FLUTTER_BUILD_NAME)</string>
	<key>CFBundleSignature</key>
	<string>????</string>
	<key>CFBundleVersion</key>
	<string>$(FLUTTER_BUILD_NUMBER)</string>
	<key>LSRequiresIPhoneOS</key>
	<true/>
	<key>UIApplicationSupportsIndirectInputEvents</key>
	<true/>
	<key>UIBackgroundModes</key>
	<array>
		<string>remote-notification</string>
		<string>processing</string>
	</array>
	<key>UILaunchStoryboardName</key>
	<string>LaunchScreen</string>
	<key>UIMainStoryboardFile</key>
	<string>Main</string>
	<key>UISupportedInterfaceOrientations</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
	<key>UISupportedInterfaceOrientations~ipad</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationPortraitUpsideDown</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
</dict>
</plist>

### Are you sending messages to your app from the Firebase Admin SDK?

<img width="1294" alt="captura_pantalla_3" src="https://github.com/user-attachments/assets/a654fabc-4d60-496c-9620-a8d4bd8b1219" />

{
    "message":{

        "token": "fRnryDj7g0q7s6wrIt8irz:APA91bH568t1LjB1YLXD3HyjrvEmJra72kZYOvsROFqkPzcT952AewSlxRlsANLnb2zpBx4uiyPNnNVBz-0EoX92YYwGErpdpv8x4FTfKDqw01OueNbtPV4",
        "notification": {
            "body" :" prueba 1000","title": ""},
            "data" : {
                "titulo" :" prueba 1000",
                "cuerpo": "",
                "id_cabb":"1111"
            },
            "apns":{
                "headers":{
                    "apns-priority": "5"
                },
                "payload":{
                    "aps":{
                        "content_available": "true"
                    }
                }
            }
        }
}

### Have you requested permission from the user to receive notifications?

- [X] I have the relevant permission to receive notifications.

### Have you used the 'Console' application on your macOS device to check if the iOS device's system is throttling your background messages?

<img width="1624" alt="captura_pantalla_4" src="https://github.com/user-attachments/assets/63438c3f-7889-4267-b392-9f0f54226b18" />

por omisión	20:22:47.843451+0100	SpringBoard	Received incoming message on topic com.cabb.pruebaNotificacionesCABB at priority 5
por omisión	20:22:47.854233+0100	SpringBoard	[com.cabb.pruebaNotificacionesCABB] Received remote notification request 3251-70A9 [ waking: 0, hasAlertContent: 1, hasSound: 0 hasBadge: 0 hasContentAvailable: 0 hasMutableContent: 0 pushType: Alert]
por omisión	20:22:47.854361+0100	SpringBoard	[com.cabb.pruebaNotificacionesCABB] Process delivery of push notification 3251-70A9
por omisión	20:22:47.854597+0100	SpringBoard	[com.cabb.pruebaNotificacionesCABB] Badge can be set for notification 3251-70A9: 0 [ canBadge: 1 badgeNumber: (null) ]
por omisión	20:22:47.854698+0100	SpringBoard	Getting effectiveSectionInfo for section identifier: com.cabb.pruebaNotificacionesCABB
por omisión	20:22:47.854806+0100	SpringBoard	[com.cabb.pruebaNotificacionesCABB] Getting effective section info
por omisión	20:22:47.855722+0100	SpringBoard	[com.cabb.pruebaNotificacionesCABB] Got effective section info [ hasResult: 1 ]
por omisión	20:22:47.855818+0100	SpringBoard	Getting effectiveSectionInfo for section identifier: com.cabb.pruebaNotificacionesCABB
por omisión	20:22:47.855905+0100	SpringBoard	[com.cabb.pruebaNotificacionesCABB] Getting effective section info
por omisión	20:22:47.856658+0100	SpringBoard	[com.cabb.pruebaNotificacionesCABB] Got effective section info [ hasResult: 1 ]
por omisión	20:22:47.856848+0100	SpringBoard	[com.cabb.pruebaNotificacionesCABB] Saving notification 3251-70A9: YES [ hasAlertContent: YES, shouldPresentAlert: YES settingsShouldSave: YES pipelineState: pending]
por omisión	20:22:47.882747+0100	SpringBoard	[com.cabb.pruebaNotificacionesCABB] Delivered user visible push notification 3251-70A9
por omisión	20:22:47.888974+0100	SpringBoard	[com.cabb.pruebaNotificacionesCABB] Load 0 pending notification dictionaries
por omisión	20:22:47.890043+0100	SpringBoard	[com.cabb.pruebaNotificacionesCABB] Adding notification 3251-70A9 [ hasAlertContent: 1, shouldPresentAlert: 1 hasSound: 0 shouldPlaySound: 1 ]; interruption-level: 1; destinations 398: (
    NotificationCenter,
    LockScreen,
    Alert,
    Spoken,
    Forwarding
); contentDate: (null)
por omisión	20:22:47.890984+0100	SpringBoard	[com.cabb.pruebaNotificacionesCABB] Starting add notification pipeline for 3251-70A9
por omisión	20:22:47.893063+0100	SpringBoard	[create, [id=3251-70A9, time=2024-12-15 19:22:47, bundle=com.cabb.pruebaNotificacionesCABB], Time elapsed=0.000 sec]: Request: Starting
por omisión	20:22:47.893284+0100	SpringBoard	[create, [id=3251-70A9, time=2024-12-15 19:22:47, bundle=com.cabb.pruebaNotificacionesCABB], Time elapsed=0.001 sec]: Running step 'Step: UserNotificationsCore.IntelligenceActor, index: 0'. Remaining steps after this step: 1'
por omisión	20:22:47.893475+0100	SpringBoard	[create, [id=3251-70A9, time=2024-12-15 19:22:47, bundle=com.cabb.pruebaNotificacionesCABB], Time elapsed=0.001 sec]: Starting step 'Step: UserNotificationsCore.IntelligenceActor, index: 0'
por omisión	20:22:47.897074+0100	SpringBoard	Skip indexing: [id=3251-70A9, time=2024-12-15 19:22:47, bundle=com.cabb.pruebaNotificacionesCABB], reason=platformEligibility
por omisión	20:22:47.897736+0100	SpringBoard	[create, [id=3251-70A9, time=2024-12-15 19:22:47, bundle=com.cabb.pruebaNotificacionesCABB], Time elapsed=0.003 sec]: Calling out to completion with success([id=29505F1A-3CAD-4158-AF55-95EDFCF7B58B, time=2024-12-15 19:22:47, bundle=com.cabb.pruebaNotificacionesCABB]) from 'run(_:_:completion:)'
por omisión	20:22:47.898237+0100	SpringBoard	[create, [id=3251-70A9, time=2024-12-15 19:22:47, bundle=com.cabb.pruebaNotificacionesCABB], Time elapsed=0.003 sec]: Success for 'Step: UserNotificationsCore.IntelligenceActor, index: 0'.
por omisión	20:22:47.898493+0100	SpringBoard	[create, [id=3251-70A9, time=2024-12-15 19:22:47, bundle=com.cabb.pruebaNotificacionesCABB], Time elapsed=0.003 sec]: Running step 'Step: UserNotificationsCore.BehaviorResolutionActor, index: 1'. Remaining steps after this step: 0'
por omisión	20:22:47.898751+0100	SpringBoard	[create, [id=3251-70A9, time=2024-12-15 19:22:47, bundle=com.cabb.pruebaNotificacionesCABB], Time elapsed=0.003 sec]: Starting step 'Step: UserNotificationsCore.BehaviorResolutionActor, index: 1'
por omisión	20:22:47.899940+0100	SpringBoard	[com.apple.usernotifications.pipeline:D301345C-0F6F-4115-B39E-E425699DA64C] Resolving behavior for event, details=<DNDMutableClientEventDetails: 0x3028f2180; identifier: '29505F1A-3CAD-4158-AF55-95EDFCF7B58B'; bundleIdentifier: com.cabb.pruebaNotificacionesCABB; platform: unknown; type: Default; urgency: Default; sender: (null); threadIdentifier: 0; filterCritera: (null); notifyAnyway: 0; behavior: Default; forwardingBehavior: (null); title: (null); subtitle: (null); body: 75216B51192F548C>
por omisión	20:22:47.903284+0100	SpringBoard	[com.apple.usernotifications.pipeline:D301345C-0F6F-4115-B39E-E425699DA64C] Resolved event, details=<DNDMutableClientEventDetails: 0x3028f2180; identifier: '29505F1A-3CAD-4158-AF55-95EDFCF7B58B'; bundleIdentifier: com.cabb.pruebaNotificacionesCABB; platform: unknown; type: Default; urgency: Default; sender: (null); threadIdentifier: 0; filterCritera: (null); notifyAnyway: 0; behavior: Default; forwardingBehavior: (null); title: (null); subtitle: (null); body: 75216B51192F548C> behavior=<DNDClientEventBehavior: 0x300b72220; eventDetails: <DNDClientEventDetails: 0x3028c4b00; identifier: '29505F1A-3CAD-4158-AF55-95EDFCF7B58B'; bundleIdentifier: com.cabb.pruebaNotificacionesCABB; platform: unknown; type: Default; urgency: Default; sender: (null); threadIdentifier: 0; filterCritera: (null); notifyAnyway: 0; behavior: Default; forwardingBehavior: (null); title: (null); subtitle: (null); body: 75216B51192F548C>; interruptionSuppression: none; intelligentBehavior: unused; resolutionReason: disabled; activeModeUUID: (null)>
por omisión	20:22:47.903500+0100	donotdisturbd	Event was resolved: resolution=<DNDSEventBehaviorResolution: 0x5d03b10c0; UUID: 978ED170-C4A5-4DD3-AD7B-FAC3E4833DD5; date: 2024-12-15 19:22:47 +0000; eventBehavior: <DNDClientEventBehavior: 0x5d0984210; eventDetails: <DNDClientEventDetails: 0x5d0827700; identifier: '29505F1A-3CAD-4158-AF55-95EDFCF7B58B'; bundleIdentifier: com.cabb.pruebaNotificacionesCABB; platform: unknown; type: Default; urgency: Default; sender: (null); threadIdentifier: 0; filterCritera: (null); notifyAnyway: 0; behavior: Default; forwardingBehavior: (null); title: (null); subtitle: (null); body: 75216B51192F548C>; interruptionSuppression: none; intelligentBehavior: unused; resolutionReason: disabled; activeModeUUID: (null)>; clientIdentifier: 'com.apple.usernotifications.pipeline'; outcome: allowed; reason: disabled>
por omisión	20:22:47.903867+0100	SpringBoard	[create, [id=3251-70A9, time=2024-12-15 19:22:47, bundle=com.cabb.pruebaNotificacionesCABB], Time elapsed=0.005 sec]: Calling out to completion with success([id=29505F1A-3CAD-4158-AF55-95EDFCF7B58B, time=2024-12-15 19:22:47, bundle=com.cabb.pruebaNotificacionesCABB]) from 'run(_:_:completion:)'
por omisión	20:22:47.904676+0100	SpringBoard	[create, [id=3251-70A9, time=2024-12-15 19:22:47, bundle=com.cabb.pruebaNotificacionesCABB], Time elapsed=0.005 sec]: Success for 'Step: UserNotificationsCore.BehaviorResolutionActor, index: 1'.
por omisión	20:22:47.904827+0100	SpringBoard	[create, [id=3251-70A9, time=2024-12-15 19:22:47, bundle=com.cabb.pruebaNotificacionesCABB], Time elapsed=0.005 sec]: Request: Completed
por omisión	20:22:47.905419+0100	SpringBoard	[create, [id=3251-70A9, time=2024-12-15 19:22:47, bundle=com.cabb.pruebaNotificacionesCABB], Time elapsed=0.005 sec]: Request: Calling completion delegate
por omisión	20:22:47.905955+0100	SpringBoard	[create, [id=3251-70A9, time=2024-12-15 19:22:47, bundle=com.cabb.pruebaNotificacionesCABB], Time elapsed=0.005 sec]: Request: Calling pipeline completion with success
por omisión	20:22:47.906058+0100	SpringBoard	[com.cabb.pruebaNotificacionesCABB] Completed add notification pipeline for 3251-70A9
por omisión	20:22:47.906208+0100	SpringBoard	BBDataProviderProxy com.cabb.pruebaNotificacionesCABB has enqueued a bulletin request
por omisión	20:22:47.906428+0100	SpringBoard	[com.cabb.pruebaNotificacionesCABB] Badge can be set for notification 3251-70A9: 0 [ canBadge: 1 badgeNumber: (null) ]
por omisión	20:22:47.906770+0100	SpringBoard	Getting effectiveSectionInfo for section identifier: com.cabb.pruebaNotificacionesCABB
por omisión	20:22:47.906908+0100	SpringBoard	[com.cabb.pruebaNotificacionesCABB] Getting effective section info
por omisión	20:22:47.907041+0100	SpringBoard	BBDataProviderProxy com.cabb.pruebaNotificacionesCABB is now sending enqueued bulletin request to BBServer
por omisión	20:22:47.908864+0100	SpringBoard	[com.cabb.pruebaNotificacionesCABB] Got effective section info [ hasResult: 1 ]
por omisión	20:22:47.908956+0100	SpringBoard	Getting effectiveSectionInfo for section identifier: com.cabb.pruebaNotificacionesCABB
por omisión	20:22:47.909029+0100	SpringBoard	[com.cabb.pruebaNotificacionesCABB] Getting effective section info
por omisión	20:22:47.911562+0100	SpringBoard	Publishing bulletin for section <com.cabb.pruebaNotificacionesCABB>: subsectionIDs: (null), bulletinID = <B2CBC260-8D28-4CA6-95B9-F82BFE9C5630>, expiration date = <Sun Dec 22 20:22:47 2024>, expiration events <0>
por omisión	20:22:47.915852+0100	SpringBoard	Attempt gateway BBObserverGatewayLocalName for bulletin B2CBC260-8D28-4CA6-95B9-F82BFE9C5630 in section com.cabb.pruebaNotificacionesCABB
por omisión	20:22:47.915946+0100	SpringBoard	Gateway BBObserverGatewayLocalName sending add bulletin lights and sirens YES for B2CBC260-8D28-4CA6-95B9-F82BFE9C5630 in section com.cabb.pruebaNotificacionesCABB with timeout 20.000000 WITH handler
por omisión	20:22:47.916060+0100	SpringBoard	Gateway BBObserverGatewayLocalName add timer (Sun Dec 15 20:23:07 2024) for bulletin B2CBC260-8D28-4CA6-95B9-F82BFE9C5630 in section com.cabb.pruebaNotificacionesCABB
por omisión	20:22:47.916155+0100	SpringBoard	Gateway BBObserverGatewayLocalName start timer (Sun Dec 15 20:23:07 2024) for out for bulletin B2CBC260-8D28-4CA6-95B9-F82BFE9C5630 in section 

com.cabb.pruebaNotificacionesCABB
por omisión	20:22:47.920581+0100	SpringBoard	<private> adding bulletin 3251-70A9 for feed 19499 in section com.cabb.pruebaNotificacionesCABB playLightsAndSirens: YES
por omisión	20:22:47.921802+0100	SpringBoard	Gateway BBObserverGatewayLocalName received DID play lights and sirens for bulletin B2CBC260-8D28-4CA6-95B9-F82BFE9C5630 in section com.cabb.pruebaNotificacionesCABB
por omisión	20:22:47.921905+0100	SpringBoard	Gateway BBObserverGatewayLocalName invalidated timer (Sun Dec 15 20:23:07 2024) for out for bulletin B2CBC260-8D28-4CA6-95B9-F82BFE9C5630 in section com.cabb.pruebaNotificacionesCABB
por omisión	20:22:47.922718+0100	SpringBoard	[com.cabb.pruebaNotificacionesCABB] Got effective section info [ hasResult: 1 ]
por omisión	20:22:47.922969+0100	SpringBoard	[com.cabb.pruebaNotificacionesCABB] Saving notification 3251-70A9: YES [ hasAlertContent: YES, shouldPresentAlert: YES settingsShouldSave: YES pipelineState: completed]
por omisión	20:22:47.924525+0100	SpringBoard	Gateway enumerator received from BBObserverGatewayLocalName DID play lights and sirens for B2CBC260-8D28-4CA6-95B9-F82BFE9C5630 in section com.cabb.pruebaNotificacionesCABB currently NOT cancelled
por omisión	20:22:47.924624+0100	SpringBoard	Attempt gateway GizmoGateway for bulletin B2CBC260-8D28-4CA6-95B9-F82BFE9C5630 in section com.cabb.pruebaNotificacionesCABB
por omisión	20:22:47.924704+0100	SpringBoard	Gateway GizmoGateway sending add bulletin lights and sirens NO for B2CBC260-8D28-4CA6-95B9-F82BFE9C5630 in section com.cabb.pruebaNotificacionesCABB with NO timeout and NO handler
por omisión	20:22:47.925118+0100	SpringBoard	Gateway enumerator received from GizmoGateway DID NOT play lights and sirens for B2CBC260-8D28-4CA6-95B9-F82BFE9C5630 in section com.cabb.pruebaNotificacionesCABB currently NOT cancelled
por omisión	20:22:47.925235+0100	SpringBoard	Gateway enumerator was completed for bulletin B2CBC260-8D28-4CA6-95B9-F82BFE9C5630 in section com.cabb.pruebaNotificacionesCABB
por omisión	20:22:47.928215+0100	SpringBoard	NCBulletinNotificationSource adding bulletin 3251-70A9 for feed 19499 in section com.cabb.pruebaNotificacionesCABB
por omisión	20:22:47.944736+0100	SpringBoard	Posting notification id: 3251-70A9; section: com.cabb.pruebaNotificacionesCABB; thread: BA9F-31D2; category: ; timestamp: 2024-12-15 19:22:47 +0000; interruption-level: active; priorityStatus: unknown; summaryStatus: unknown; relevance-score: 0.00; filter-criteria: (null); actions: [ minimal: 0 (0 text), default: 0 (0 text) ]; destinations: [ {(
    BulletinDestinationCoverSheet,
    BulletinDestinationBanner,
    BulletinDestinationNotificationCenter,
    BulletinDestinationLockScreen
)} ]
por omisión	20:22:47.946995+0100	SpringBoard	Notification Root List [NCNotificationRootLegacyList] Section for new request 3251-70A9 for Group List [com.cabb.pruebaNotificacionesCABB:BA9F-31D2] is Incoming
por omisión	20:22:47.947088+0100	SpringBoard	Incoming Section [NCNotificationStructuredSectionList] inserting notification request 3251-70A9 in new group Group List [com.cabb.pruebaNotificacionesCABB:BA9F-31D2]
por omisión	20:22:47.947323+0100	SpringBoard	Group List [com.cabb.pruebaNotificacionesCABB:BA9F-31D2] inserting notification request 3251-70A9 at index 0
por omisión	20:22:47.947431+0100	SpringBoard	Incoming Section [NCNotificationStructuredSectionList] inserting notificationGroup Group List [com.cabb.pruebaNotificacionesCABB:BA9F-31D2] at index 0
error	20:22:47.947532+0100	SpringBoard	Incoming Section [NCNotificationStructuredSectionList] thread 'Group List [com.cabb.pruebaNotificacionesCABB:BA9F-31D2]' in 'Incoming' is not reveal correctly; isRevealed: 1; revealPercentage: 0.000000
por omisión	20:22:47.961334+0100	SpringBoard	[com.cabb.pruebaNotificacionesCABB] Load 0 pending notification dictionaries

### Additional context and comments

When I send a notification to the app and it is in the foreground everything works correctly.
When the app is in the background, the notification arrives correctly and is displayed, but the FirebaseMessaging.onBackgroundMessage method is not executed.

The mobile device has IOS version 18.1.1

The flutter version is :

> - Flutter 3.27.0 • channel stable • https://github.com/flutter/flutter.git
> - Framework • revision 8495dee1fd (5 days ago) • 2024-12-10 14:23:39 -0800
> - Engine • revision 83bacfc525
> - Tools • Dart 3.6.0 • DevTools 2.40.2

Firebasemessaging version is:

- > firebase_messaging: ^15.1.6
- > firebase_core: ^3.8.1

**Comment by SelaseKay** [comment] 2024-12-16 13:25
Hi @VictorJGarciaMartin, I believe this is a duplicate of https://github.com/firebase/flutterfire/issues/16853

**Closed by SelaseKay** 2024-12-16 13:25 UTC
Labels: type: bug, plugin: messaging, platform: ios, Needs Attention

**Comment by VictorJGarciaMartin** [comment] 2024-12-17 04:53
I've been looking at case #16853 and I don't think it has the same problem as I described. In my case the notification arrives correctly and is displayed. If I click on the notification the application opens. What happens is that when the notification arrives the method 

@pragma('vm:entry-point')
Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message) async {
  // If you're going to use other Firebase services in the background, such as Firestore,
  // make sure you call `initializeApp` before using other Firebase services.
  await Firebase.initializeApp();

  debugPrint("Aplicacion en SEGUNDO PLANO. message: ${message.messageId}");
}
is not executed.


I would appreciate any help on this matter

**Comment by SelaseKay** [comment] 2024-12-17 06:37
Hi @VictorJGarciaMartin, my apologies for referencing the wrong issue earlier. Here's an existing issue that describes the same problem: https://github.com/firebase/flutterfire/issues/16878.
