### ISSUE TITLE
🐛 [cloud_firestore_platform_interface] Type Mismatch Error: FieldValue.increment Causes 'double' not a subtype of 'int?' on Deserialization

### ISSUE THREAD

**Issue by nbergemann** [firebase/flutterfire#12436] opened 2024-03-06 08:53 UTC
## Bug report

**Describe the bug**
When using FieldValue.increment(1) to update a numeric field in a Firestore document, the updated field is stored as a double, not an integer as expected. This behavior results in a type mismatch error (Unhandled Exception: type 'double' is not a subtype of type 'int?' in type cast) when attempting to deserialize the field value directly into an integer (int?) in Dart. The issue occurs even though the increment operation is performed with an integer value (1 in this case), suggesting that the incremented value should also be treated as an integer during deserialization.

```
Unhandled Exception: type 'double' is not a subtype of type 'int?' in type cast
#0      TheApp.build.<anonymous closure>
```

### Steps to reproduce

```
Future<void> main() async {
  WidgetsBinding widgetsBinding = WidgetsFlutterBinding.ensureInitialized();
  await initFirebase(emulate: kDebugMode);

  runApp(TheApp());
}

class TheApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: ElevatedButton(
            onPressed: () async {
              try {
                // Update operation
                FirebaseFirestore firestore = FirebaseFirestore.instance;
                DocumentReference documentReference =
                    firestore.collection('counters').doc('yourDocumentId');
                final doc = await documentReference.get();
                if (!doc.exists) {
                  await documentReference.set(<String, dynamic>{});
                }
                await documentReference.update({'counter': FieldValue.increment(1)});

                // Attempt to fetch and deserialize the updated document
                DocumentSnapshot snapshot = await documentReference.get();
                Map<dynamic, dynamic>? data = snapshot.data() as Map<dynamic, dynamic>?;
                if (data != null) {
                  // Directly deserialize 'counter' field within fromFirestore
                  int? counter = data['counter'] as int?;
                  print('Deserialized counter value: $counter');
                }
              } on Exception catch (error, stackTrace) {
                debugPrint(error.toString());
                debugPrintStack(stackTrace: stackTrace);
              }
            },
            child: Text('Increment Counter and Deserialize'),
          ),
        ),
      ),
    );
  }
}
```
in pubspec.yaml use `cloud_firestore_platform_interface: 6.1.8` and`cloud_firestore: ^4.15.5`
### Expected behavior

The FieldValue.increment(1) operation should increment the field value as an integer, and it should be possible to deserialize the updated field value directly into an int? without encountering a type mismatch error. If the operation results in a value that is inherently a double (e.g., FieldValue.increment(1.0)), then the behavior is understandable. However, for integer increments, the expected behavior is that the value remains an integer.

### Sample project

Providing a minimal example project which demonstrates the bug in isolation from your main App _greatly_ enhances the chance of a timely fix.
Please link to the public repository URL.

---

## Additional context

When using `cloud_firestore_platform_interface` version `6.1.7` no error gets thrown

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 3.19.2, on macOS 14.2.1 23C71 darwin-arm64, locale en-DE)
    • Flutter version 3.19.2 on channel stable at /opt/homebrew/Caskroom/flutter/3.0.5/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7482962148 (7 days ago), 2024-02-27 16:51:22 -0500
    • Engine revision 04817c99c9
    • Dart version 3.3.0
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/nilsbergemann/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/nilsbergemann/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.14.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] IntelliJ IDEA Community Edition (version 2023.3.4)
    • IntelliJ at /Users/nilsbergemann/Applications/IntelliJ IDEA Community Edition.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.87.0)
    • VS Code at /Users/nilsbergemann/Workspace/Visual Studio Code.app/Contents
    • Flutter extension version 3.84.0

[✓] Connected device (4 available)
    • iPhone SE (3rd generation) (mobile) • 83386A71-C4CE-4C6B-806B-9E20E7DEA875 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-2 (simulator)
    • iPhone 15 Pro Max (mobile)          • 9A7C84A7-EF58-48F3-A0D4-66BEEF13EB93 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-2 (simulator)
    • macOS (desktop)                     • macos                                • darwin-arm64   • macOS 14.2.1 23C71 darwin-arm64
    • Chrome (web)                        • chrome                               • web-javascript • Google Chrome 122.0.6261.94
    ! Error: Browsing on the local area network for NB‘s iPhone. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

**Comment by Lyokone** [comment] 2024-03-06 09:54
Hello, thanks for the report, it was caused by yesterday's update. You can pin on cloud_firestore_platform_interface 6.1.7 while I'm fixing that.

**Comment by jonmountjoy** [comment] 2024-03-07 09:28
I had a similar issue just now - where I was storing an int, and it was being stored as a double.  
Everything broke - and hours later I find this. 
If it is the same issue, can we get a test added that ensures an int is stored as an int?

When I pinned to 6.1.7 the problem went away.

**Comment by Lyokone** [comment] 2024-03-07 11:15
It has been fixes with #12444, will be released as part of next week release

**Closed** 2024-03-07 11:15 UTC
Labels: type: bug, Needs Attention

**Comment by jonmountjoy** [comment] 2024-03-07 11:26
Thank you @Lyokone 👍 💯

**Comment by wasilni2022** [comment] 2024-03-07 17:11
Same here. The whole project broke.

Thank you, @Lyokone. 
We really need that update ASAP.

**Comment by Lyokone** [comment] 2024-03-07 18:12
@wasilni2022 if blocking, you can always add to your `pubspec.yaml`, we will release tomorrow 
```
cloud_firestore_platform_interface: 6.1.7
```

**Comment by ZippyRainbow** [comment] 2024-03-31 04:11
Hi @Lyokone,
Just checking you saw my message from 3 weeks ago saying this issue is not fixed?
The number which is stored in Firestore is a Double when you do a Increment from version 4.15.7 onwards.
It can be hard to see from the Firebase Console as it shows it as a Integer there, but if you read the database it shows it has been converted to a double.
I have added code into my App to check if it has been stored as a double and to convert to a Int, but it would be nice to have it fixed. Any ideas? I think just removing the 4.15.7 & 4.17.8 changes are best for now as it is not as important as fixing the Big Int Change.
