### ISSUE TITLE
[📚] link to flutterfire ui is wrong

### ISSUE THREAD

**Issue by graemep-nz** [firebase/flutterfire#10469] opened 2023-02-16 10:52 UTC
On this web page there is a link to flutterfire  UI that gives a 404 error
https://firebaseopensource.com/projects/firebase/flutterfire/

the link is
[FlutterFire UI](https://github.com/firebase/flutterfire/tree/master/packages/flutterfire_ui/readme.md) (beta)

**Comment by darshankawar** [comment] 2023-02-16 11:42
Duplicate of https://github.com/firebase/flutterfire/issues/10459

**Closed by darshankawar** 2023-02-16 11:42 UTC
Labels: type: documentation, good first issue, in triage
