### ISSUE TITLE
🐛 FirebaseRemoteConfig: ChromeProxyService: Failed to evaluate expression 'FirebaseRemoteConfig': InternalError: No frame with index 30. 

### ISSUE THREAD

**Issue by xErik** [firebase/flutterfire#8674] opened 2022-05-13 09:37 UTC
## Bug report

**Describe the bug**

Using VS Code and running a local Web-Debug session, this error is shown in the Debug Console:

```
ChromeProxyService: Failed to evaluate expression 'FirebaseRemoteConfig': InternalError: No frame with index 30.
ChromeProxyService: Failed to evaluate expression 'await': InternalError: No frame with index 30.
```

The browser shows _Paused_ in Dart Dev Tools. If I click resume, everything works fine. VS Code seems to intercept some event and pauses the execution.

This happens with the latest versions of Chrome and Edge. VS Code is also up to date.

### Steps to reproduce

On the first call off this line works without problems, however, after a minute or so, VS Code gives the errors stated above:

`await FirebaseRemoteConfig.instance.fetchAndActivate();`

---

### Flutter doctor

<details><summary>Click To Expand</summary>

```
[√] Flutter (Channel stable, 3.0.0, on Microsoft Windows [Version 10.0.19044.1645], locale en-DE)[X] Android toolchain - develop for Android devices
    X Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed  
      instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[√] Chrome - develop for the web
[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default   
      components
[!] Android Studio (not installed)
[√] VS Code (version 1.67.1)
[√] Connected device (3 available)
[√] HTTP Host Availability
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.17.0
Flutter SDK 3.0.0
com_my_app 1.0.0+1

dependencies:
- cupertino_icons 1.0.4
- firebase_analytics 9.1.7 [firebase_analytics_platform_interface firebase_analytics_web firebase_core firebase_core_platform_interface flutter]
- firebase_core 1.16.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_remote_config 2.0.6 [firebase_core firebase_core_platform_interface firebase_remote_config_platform_interface firebase_remote_config_web flutter]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]     
- flutter_local_notifications 9.5.2 [clock flutter flutter_local_notifications_linux flutter_local_notifications_platform_interface timezone]
- get 4.6.1 [flutter]
- logger 1.1.0

dev dependencies:
- flutter_lints 2.0.1 [lints]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher material_color_utilities meta source_span stream_channel string_scanner term_glyph]

transitive dependencies:
- args 2.3.1
- async 2.8.2 [collection meta]
- boolean_selector 2.1.0 [source_span string_scanner]
- characters 1.2.0
- charcode 1.3.1
- clock 1.1.0
- collection 1.16.0
- dbus 0.7.3 [args ffi meta xml]
- fake_async 1.3.0 [clock collection]
- ffi 1.1.2
- file 6.1.2 [meta path]
- firebase_analytics_platform_interface 3.1.5 [firebase_core flutter meta plugin_platform_interface]
- firebase_analytics_web 0.4.0+12 [firebase_analytics_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- firebase_core_platform_interface 4.3.0 [collection flutter meta plugin_platform_interface]     
- firebase_core_web 1.6.3 [firebase_core_platform_interface flutter flutter_web_plugins js meta] 
- firebase_remote_config_platform_interface 1.1.5 [firebase_core flutter meta plugin_platform_interface]
- firebase_remote_config_web 1.0.11 [firebase_core firebase_core_web firebase_remote_config_platform_interface flutter flutter_web_plugins js]
- flutter_local_notifications_linux 0.4.2 [flutter flutter_local_notifications_platform_interface dbus path xdg_directories]
- flutter_local_notifications_platform_interface 5.0.0 [flutter plugin_platform_interface]       
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta vector_math]
- js 0.6.4
- lints 2.0.0
- matcher 0.12.11 [stack_trace]
- material_color_utilities 0.1.4
- meta 1.7.0
- path 1.8.1
- petitparser 5.0.0 [meta]
- platform 3.1.0
- plugin_platform_interface 2.1.2 [meta]
- process 4.2.4 [file path platform]
- sky_engine 0.0.99
- source_span 1.8.2 [collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.0 [charcode source_span]
- term_glyph 1.2.0
- test_api 0.4.9 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- timezone 0.8.0 [path]
- vector_math 2.1.2
- xdg_directories 0.2.0+1 [meta path process]
- xml 5.4.1 [collection meta petitparser]
```

</details>

---

**Comment by darshankawar** [comment] 2022-05-13 11:26
@xErik 
The error you are getting `ChromeProxyService: Failed to evaluate expression` seems not related to flutterfire plugin, but was a dart issue that was fixed recently :  https://github.com/flutter/flutter/issues/101224. Apologies for redirecting you here.

The fix seems to be already part of stable, but can you go through that issue one more time and update your dart sdk constraint and see if it helps to resolve ?

I am going ahead and closing this as the issue isn't related to flutterfire plugin.

**Closed by darshankawar** 2022-05-13 11:26 UTC
Labels: type: bug, Needs Attention, in triage
