### ISSUE TITLE
Getting Firebase Platform Exception When Migrating Flutter To 3.19.1

### ISSUE THREAD

**Issue by mrazamerchant** [firebase/flutterfire#12394] opened 2024-02-26 16:59 UTC
## Bug report

**Describe the bug**
i have a project where i use to work on flutter 3.16.0 and its working fine but when i migrated  my flutter from 3.16.0 to current latest version 3.19.1 and i got firebase exception.

The Error i got on debug console :
D/FlutterGeolocator( 3804): Flutter engine connected. Connected engine count 1
E/flutter ( 3804): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(null-error, Host platform returned null value for non-null return value., null, null)
E/flutter ( 3804): #0      FirebaseCoreHostApi.optionsFromResource (package:firebase_core_platform_interface/src/pigeon/messages.pigeon.dart:248:7)
E/flutter ( 3804): <asynchronous suspension>
E/flutter ( 3804): #1      MethodChannelFirebase.initializeApp (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:89:25)

These are my gradle configuration images:
https://github.com/firebase/flutterfire/assets/140117432/4a118bcb-4ca8-4c82-861a-88f55607e9d0
https://github.com/firebase/flutterfire/assets/140117432/8778d6ff-c60c-4aa0-80d9-9a8c638a4e57
https://github.com/firebase/flutterfire/assets/140117432/704b77b9-5338-4ce0-bf81-61a402500461
https://github.com/firebase/flutterfire/assets/140117432/c1853a23-dd91-49cc-8201-07dfbc6a94c3

I used official article to migrate flutter to 3.19.1.
https://docs.flutter.dev/release/breaking-changes/flutter-gradle-plugin-apply

**Remember my project running fine on 3.16.0**
Please provide quick solution as i need to upgrade my project thanks in advance.

**Comment by danagbemava-nc** [comment] 2024-02-27 10:15
Please do not file multiple issues for the same bug report. 

Closing this as as a duplicate of https://github.com/firebase/flutterfire/issues/12393

**Closed by danagbemava-nc** 2024-02-27 10:15 UTC
Labels: type: bug, Needs Attention, in triage
