### ISSUE TITLE
🐛 [PLUGIN_NAME_HERE] flutter for android  ,The SDK has not been initialized, make sure to call FacebookSdk.sdkInitialize() first

### ISSUE THREAD

**Issue by zhangyugoon** [firebase/flutterfire#11825] opened 2023-11-03 03:26 UTC
Our flutter APP integrates firebase, and in Android apps, when exiting the APP, there is a high probability of error:

========================================================================================

```
: java.lang.RuntimeException: Unable to destroy activity {com.XXXX.YYYY/com.XXXX.YYYY.MainActivity}: The SDK has not been initialized, make sure to call FacebookSdk.sdkInitialize() first.
E/AndroidRuntime(13477): 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:6080)
E/AndroidRuntime(13477): 	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:6113)
E/AndroidRuntime(13477): 	at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:47)
E/AndroidRuntime(13477): 	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
E/AndroidRuntime(13477): 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
E/AndroidRuntime(13477): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
E/AndroidRuntime(13477): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2574)
E/AndroidRuntime(13477): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(13477): 	at android.os.Looper.loopOnce(Looper.java:226)
E/AndroidRuntime(13477): 	at android.os.Looper.loop(Looper.java:313)
E/AndroidRuntime(13477): 	at android.app.ActivityThread.main(ActivityThread.java:8757)
E/AndroidRuntime(13477): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(13477): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
E/AndroidRuntime(13477): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
E/AndroidRuntime(13477): Caused by: The SDK has not been initialized, make sure to call FacebookSdk.sdkInitialize() first.
E/AndroidRuntime(13477): 	at com.facebook.internal.Validate.sdkInitialized(Validate.kt:129)
E/AndroidRuntime(13477): 	at com.facebook.login.LoginManager.<init>(LoginManager.kt:1398)
E/AndroidRuntime(13477): 	at com.facebook.login.LoginManager$Companion.getInstance(LoginManager.kt:1319)
E/AndroidRuntime(13477): 	at com.facebook.login.LoginManager.getInstance(Unknown Source:2)
E/AndroidRuntime(13477): 	at ru.innim.flutter_login_facebook.FlutterLoginFacebookPlugin._resetActivity(FlutterLoginFacebookPlugin.java:78)
E/AndroidRuntime(13477): 	at ru.innim.flutter_login_facebook.FlutterLoginFacebookPlugin.onDetachedFromActivity(FlutterLoginFacebookPlugin.java:54)
E/AndroidRuntime(13477): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.detachFromActivity(FlutterEngineConnectionRegistry.java:387)
E/AndroidRuntime(13477): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onDetach(FlutterActivityAndFragmentDelegate.java:749)
E/AndroidRuntime(13477): 	at io.flutter.embedding.android.FlutterActivity.onDestroy(FlutterActivity.java:908)
E/AndroidRuntime(13477): 	at android.app.Activity.performDestroy(Activity.java:8864)
E/AndroidRuntime(13477): 	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1419)
E/AndroidRuntime(13477): 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:6067)
E/AndroidRuntime(13477): 	... 13 more
```

this in our pubspec.yaml config: 

```
 # firebase core
  firebase_core: ^2.20.0
  # firebase push
  firebase_messaging: ^14.7.2
  # firebase服务
  firebase_auth: ^4.12.0
```

**Comment by danagbemava-nc** [comment] 2023-11-03 10:29
Hi @zhangyugoon, this is caused by the `flutter_login_facebook` not any of the firebase plugins. 

You should report this issue on their repo. 

Closing from here as this does not belong here.

**Closed by danagbemava-nc** 2023-11-03 10:29 UTC
Labels: type: bug, Needs Attention, in triage
