### ISSUE TITLE
🐛 [firebase_messaging] AOS FirebaseMessaging.onMessageOpenedApp Not Working

### ISSUE THREAD

**Issue by minjinDelable** [firebase/flutterfire#10517] opened 2023-02-23 11:57 UTC
### flutter doctor 
[✓] Flutter (Channel stable, 3.3.8, on macOS 13.0.1 22A400 darwin-arm, locale
    ko-KR)
[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.1)
[✓] VS Code (version 1.74.3)
[✓] Connected device (4 available)
    ! Error: (null) needs to connect to determine its availability. Check the
      connection between the device and its companion iPhone, and the connection
      between the iPhone and Xcode. Both devices may also need to be restarted
      and unlocked. (code 1)
[✓] HTTP Host Availability

my project setting

Androidmanifest.xml 
```java
 <uses-permission android:name="android.permission.INTERNET"/>
    <!-- Permissions options for the `contacts` group -->
    <uses-permission android:name="android.permission.READ_CONTACTS"/>
    <uses-permission android:name="android.permission.WRITE_CONTACTS"/>
    <uses-permission android:name="android.permission.GET_ACCOUNTS"/>

    <!-- Permissions options for the `camera` group -->
    <uses-permission android:name="android.permission.CAMERA"/>

    <!-- Permissions options for the `access notification policy` group -->
    <uses-permission android:name="android.permission.ACCESS_NOTIFICATION_POLICY"/>
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>
    <uses-permission android:name="android.permission.VIBRATE"/>
    <uses-permission android:name="android.permission.WAKE_LOCK"/>
    <uses-permission android:name="android.permission.USE_FULL_SCREEN_INTENT"/>
...
<meta-data
                android:name="com.google.firebase.messaging.default_notification_channel_id"
                android:value="@string/default_notification_channel_id" />
        <meta-data
                android:name="firebase_messaging_auto_init_enabled"
                android:value="false" />
        <meta-data
                android:name="firebase_analytics_collection_enabled"
                android:value="false" />
...

```

styles.xml code here
```java
<string name="default_notification_channel_id" translatable="false">default</string>
```

my flutter code here
```dart
FirebaseMessaging.onMessageOpenedApp.listen((RemoteMessage event) async {
      logger.d('FirebaseMessageManager onMessageOpenedApp: $event');
      showNegativeToast('FirebaseMessageManager onMessageOpenedApp');
      final Map<String, dynamic> map = event.data;
      final bool isRegister = Get.isRegistered<BottomNavigationController>();
      if (isRegister) {
        if (map.containsKey('notificationType')) {
          checkMessageAndMovePage(event);
        }
      }
    }, onDone: () {
      logger.d('done');
    }, onError: (dynamic data) {
      logger.d('Error $data');
    });
  }

...
main 

void main() async {
  await init();
  runApp(const MyApp());
}

Future<void> init() async {
  getXInit();
  WidgetsFlutterBinding.ensureInitialized();
  await firebaseInitialization.then((FirebaseApp value) {
    Get.put(FirebaseAuthManager());
  });
  await initFirebaseManager();
  await storageManager.firstRunCheck();
  await initFacebook();
  initKakao();
  await appSetting.init();
  networkManager.init();
  SystemChrome.setSystemUIOverlayStyle(const SystemUiOverlayStyle(
    statusBarColor: Colors.transparent, // 투명색
  ));
  FirebaseMessaging.onBackgroundMessage(_firebaseMessagingBackgroundHandler);
  FirebaseMessageManager().terminateApp();
  FirebaseMessageManager().registerOnMessage();
  FirebaseMessageManager().registerOnMessageOpenedApp();
  registerMessage();
}

```

Ios responds normally.
But what's sent from the server doesn't respond.
Ironically, it responds to test messages from firebase.

What did I miss?

i used package version
here
firebase_messaging: ^14.2.5
flutter_local_notifications: ^12.0.2

**Comment by MerryOscar** [comment] 2023-03-10 09:49
This is the same issue as https://github.com/firebase/flutterfire/issues/9211 which has been open since July 2022.

@darshankawar do we have any updates - seems like a pretty critical issue with the firebase_messaging plugin.

**Comment by darshankawar** [comment] 2023-03-13 11:56
The issue is still open @MerryOscar, but thanks for linking the original issue. I'll close this in favor of it. You may follow-up in the linked issue. I'll forward that issue for team's attention and for any insights from them.

**Closed by darshankawar** 2023-03-13 11:56 UTC
Labels: type: bug, blocked: customer-response, in triage
