### ISSUE TITLE
🐛 [Flutter_Auth 4.7.1] dev.flutter.pigeon.FirebaseAuthUserHostApi.getIdToken(10673): Failed to handle message

### ISSUE THREAD

**Issue by mbebs** [firebase/flutterfire#11315] opened 2023-07-18 14:44 UTC
## Bug report

**Describe the bug**
After upgrading my dependencies from Firebase_Auth 4.1.3 to 4.7.1 am getting my app crash everytime i try to get the idToken of the current user. Here's the code that crashes everytime.

```
E/BasicMessageChannel#dev.flutter.pigeon.FirebaseAuthUserHostApi.getIdToken(10673): Failed to handle message
E/BasicMessageChannel#dev.flutter.pigeon.FirebaseAuthUserHostApi.getIdToken(10673): java.lang.IllegalStateException: Task is not yet complete
E/BasicMessageChannel#dev.flutter.pigeon.FirebaseAuthUserHostApi.getIdToken(10673): 	at com.google.android.gms.common.internal.Preconditions.checkState(com.google.android.gms:play-services-basement@@18.2.0:2)
E/BasicMessageChannel#dev.flutter.pigeon.FirebaseAuthUserHostApi.getIdToken(10673): 	at com.google.android.gms.tasks.zzw.zzf(com.google.android.gms:play-services-tasks@@18.0.2:1)
E/BasicMessageChannel#dev.flutter.pigeon.FirebaseAuthUserHostApi.getIdToken(10673): 	at com.google.android.gms.tasks.zzw.getResult(com.google.android.gms:play-services-tasks@@18.0.2:1)
E/BasicMessageChannel#dev.flutter.pigeon.FirebaseAuthUserHostApi.getIdToken(10673): 	at io.flutter.plugins.firebase.auth.FlutterFirebaseAuthUser.getIdToken(FlutterFirebaseAuthUser.java:95)
E/BasicMessageChannel#dev.flutter.pigeon.FirebaseAuthUserHostApi.getIdToken(10673): 	at io.flutter.plugins.firebase.auth.GeneratedAndroidFirebaseAuth$FirebaseAuthUserHostApi.lambda$setup$1(GeneratedAndroidFirebaseAuth.java:3256)
E/BasicMessageChannel#dev.flutter.pigeon.FirebaseAuthUserHostApi.getIdToken(10673): 	at io.flutter.plugins.firebase.auth.GeneratedAndroidFirebaseAuth$FirebaseAuthUserHostApi$$ExternalSyntheticLambda5.onMessage(Unknown Source:2)
E/BasicMessageChannel#dev.flutter.pigeon.FirebaseAuthUserHostApi.getIdToken(10673): 	at io.flutter.plugin.common.BasicMessageChannel$IncomingMessageHandler.onMessage(BasicMessageChannel.java:217)
E/BasicMessageChannel#dev.flutter.pigeon.FirebaseAuthUserHostApi.getIdToken(10673): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/BasicMessageChannel#dev.flutter.pigeon.FirebaseAuthUserHostApi.getIdToken(10673): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/BasicMessageChannel#dev.flutter.pigeon.FirebaseAuthUserHostApi.getIdToken(10673): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/BasicMessageChannel#dev.flutter.pigeon.FirebaseAuthUserHostApi.getIdToken(10673): 	at android.os.Handler.handleCallback(Handler.java:942)
E/BasicMessageChannel#dev.flutter.pigeon.FirebaseAuthUserHostApi.getIdToken(10673): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/BasicMessageChannel#dev.flutter.pigeon.FirebaseAuthUserHostApi.getIdToken(10673): 	at android.os.Looper.loopOnce(Looper.java:201)
E/BasicMessageChannel#dev.flutter.pigeon.FirebaseAuthUserHostApi.getIdToken(10673): 	at android.os.Looper.loop(Looper.java:288)
E/BasicMessageChannel#dev.flutter.pigeon.FirebaseAuthUserHostApi.getIdToken(10673): 	at android.app.ActivityThread.main(ActivityThread.java:7872)
E/BasicMessageChannel#dev.flutter.pigeon.FirebaseAuthUserHostApi.getIdToken(10673): 	at java.lang.reflect.Method.invoke(Native Method)
E/BasicMessageChannel#dev.flutter.pigeon.FirebaseAuthUserHostApi.getIdToken(10673): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/BasicMessageChannel#dev.flutter.pigeon.FirebaseAuthUserHostApi.getIdToken(10673): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

### Steps to reproduce

```
Future<void> getToken() async {
   var token = await FirebaseAuth.instance.currentUser?.getIdToken();
   print("token: $token");
  }
```

### Expected behavior

I expect to get the current user's idtoken for use in jwt

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.10.6, on Microsoft Windows [Version 10.0.19045.3269], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web                                                
[!] Visual Studio - develop for Windows (Visual Studio Community 2022 17.5.4)   
    X Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop development with C++" workload, and include these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools                                                                                                                          
         - If there are multiple build tool versions available, install the latest                                                                                           
        C++ CMake tools for Windows                                                                                                                                          
        Windows 10 SDK                                                                                                                                                       
[!] Android Studio (version 3.6)                                                                                                                                             
    X Unable to determine bundled Java version.                                                                                                                              
[√] Android Studio (version 2022.2)                                                                                                                                          
[√] VS Code, 64-bit edition (version 1.79.2)
[√] Connected device (4 available)
[√] Network resources

```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 3.0.6
Flutter SDK 3.10.6
myApp 1.0.2+7
|-- android_path_provider 0.3.0
|   '-- flutter...
|-- animate_icons 2.0.0
|   '-- flutter...
|-- app_links 3.4.3
|   |-- flutter...
|   |-- flutter_web_plugins...
|   '-- plugin_platform_interface...
|-- auto_size_text 3.0.0
|   '-- flutter...
|-- beamer 1.5.6
|   |-- flutter...
|   '-- flutter_web_plugins...
|-- cached_network_image 3.2.3
|   |-- cached_network_image_platform_interface 2.0.0
|   |   |-- flutter...
|   |   '-- flutter_cache_manager...
|   |-- cached_network_image_web 1.0.2
|   |   |-- cached_network_image_platform_interface...
|   |   |-- flutter...
|   |   '-- flutter_cache_manager...
|   |-- octo_image 1.0.2
|   |   |-- flutter_blurhash 0.7.0
|   |   |   '-- flutter...
|   |   '-- flutter...
|   |-- flutter...
|   '-- flutter_cache_manager...
|-- cloud_firestore 4.8.3
|   |-- cloud_firestore_platform_interface 5.15.3
|   |   |-- _flutterfire_internals...
|   |   |-- collection...
|   |   |-- firebase_core...
|   |   |-- flutter...
|   |   |-- meta...
|   |   '-- plugin_platform_interface...
|   |-- cloud_firestore_web 3.6.3
|   |   |-- _flutterfire_internals...
|   |   |-- cloud_firestore_platform_interface...
|   |   |-- collection...
|   |   |-- firebase_core...
|   |   |-- firebase_core_web...
|   |   |-- flutter...
|   |   |-- flutter_web_plugins...
|   |   '-- js...
|   |-- collection...
|   |-- firebase_core...
|   |-- firebase_core_platform_interface...
|   |-- flutter...
|   '-- meta...
|-- cupertino_icons 1.0.5
|-- custom_utils 0.0.34
|   |-- async 2.11.0
|   |   |-- collection...
|   |   '-- meta...
|   |-- flexi_chip 1.0.8
|   |   |-- animated_checkmark 1.0.1
|   |   |   '-- flutter...
|   |   |-- widget_event 1.2.5
|   |   |   '-- flutter...
|   |   '-- flutter...
|   |-- intl 0.18.1
|   |   |-- clock...
|   |   |-- meta...
|   |   '-- path...
|   |-- sizer 2.0.15
|   |   |-- universal_io 2.2.2
|   |   |   |-- collection...
|   |   |   |-- meta...
|   |   |   '-- typed_data...
|   |   '-- flutter...
|   |-- url_launcher 6.1.12
|   |   |-- url_launcher_android 6.0.36
|   |   |   |-- flutter...
|   |   |   '-- url_launcher_platform_interface...
|   |   |-- url_launcher_ios 6.1.4
|   |   |   |-- flutter...
|   |   |   '-- url_launcher_platform_interface...
|   |   |-- url_launcher_linux 3.0.5
|   |   |   |-- flutter...
|   |   |   '-- url_launcher_platform_interface...
|   |   |-- url_launcher_macos 3.0.6
|   |   |   |-- flutter...
|   |   |   '-- url_launcher_platform_interface...
|   |   |-- url_launcher_platform_interface 2.1.3
|   |   |   |-- flutter...
|   |   |   '-- plugin_platform_interface...
|   |   |-- url_launcher_web 2.0.18
|   |   |   |-- flutter...
|   |   |   |-- flutter_web_plugins...
|   |   |   '-- url_launcher_platform_interface...
|   |   |-- url_launcher_windows 3.0.7
|   |   |   |-- flutter...
|   |   |   '-- url_launcher_platform_interface...
|   |   '-- flutter...
|   '-- flutter...
|-- device_info 2.0.3
|   |-- device_info_platform_interface 2.0.1
|   |   |-- flutter...
|   |   |-- meta...
|   |   '-- plugin_platform_interface...
|   '-- flutter...
|-- dio 5.3.0
|   |-- http_parser 4.0.2
|   |   |-- typed_data 1.3.2
|   |   |   '-- collection...
|   |   |-- collection...
|   |   |-- source_span...
|   |   '-- string_scanner...
|   |-- path 1.8.3
|   |-- async...
|   '-- meta...
|-- dotted_border 2.0.0+3
|   |-- path_drawing 1.0.1
|   |   |-- flutter...
|   |   |-- meta...
|   |   |-- path_parsing...
|   |   '-- vector_math...
|   '-- flutter...
|-- extended_image 8.0.2
|   |-- extended_image_library 3.5.3
|   |   |-- http_client_helper 3.0.0
|   |   |   '-- http...
|   |   |-- crypto...
|   |   |-- flutter...
|   |   |-- js...
|   |   |-- path...
|   |   '-- path_provider...
|   |-- flutter...
|   '-- meta...
|-- file_picker 5.3.2
|   |-- flutter_plugin_android_lifecycle 2.0.15
|   |   '-- flutter...
|   |-- flutter_web_plugins 0.0.0
|   |   |-- characters...
|   |   |-- collection...
|   |   |-- flutter...
|   |   |-- js...
|   |   |-- material_color_utilities...
|   |   |-- meta...
|   |   '-- vector_math...
|   |-- plugin_platform_interface 2.1.4
|   |   '-- meta...
|   |-- win32 5.0.5
|   |   '-- ffi...
|   |-- ffi...
|   |-- flutter...
|   '-- path...
|-- firebase_auth 4.7.1
|   |-- firebase_auth_platform_interface 6.16.0
|   |   |-- _flutterfire_internals...
|   |   |-- collection...
|   |   |-- firebase_core...
|   |   |-- flutter...
|   |   |-- meta...
|   |   '-- plugin_platform_interface...
|   |-- firebase_auth_web 5.6.1
|   |   |-- firebase_auth_platform_interface...
|   |   |-- firebase_core...
|   |   |-- firebase_core_web...
|   |   |-- flutter...
|   |   |-- flutter_web_plugins...
|   |   |-- http_parser...
|   |   |-- js...
|   |   '-- meta...
|   |-- firebase_core...
|   |-- firebase_core_platform_interface...
|   |-- flutter...
|   '-- meta...
|-- firebase_core 2.15.0
|   |-- firebase_core_web 2.6.0
|   |   |-- firebase_core_platform_interface...
|   |   |-- flutter...
|   |   |-- flutter_web_plugins...
|   |   |-- js...
|   |   '-- meta...
|   |-- firebase_core_platform_interface...
|   |-- flutter...
|   '-- meta...
|-- firebase_dynamic_links 5.3.4
|   |-- firebase_dynamic_links_platform_interface 0.2.6+4
|   |   |-- _flutterfire_internals...
|   |   |-- firebase_core...
|   |   |-- flutter...
|   |   |-- meta...
|   |   '-- plugin_platform_interface...
|   |-- firebase_core...
|   |-- firebase_core_platform_interface...
|   |-- flutter...
|   |-- meta...
|   '-- plugin_platform_interface...
|-- firebase_messaging 14.6.5
|   |-- firebase_core_platform_interface 4.8.0
|   |   |-- collection...
|   |   |-- flutter...
|   |   |-- flutter_test...
|   |   |-- meta...
|   |   '-- plugin_platform_interface...
|   |-- firebase_messaging_platform_interface 4.5.4
|   |   |-- _flutterfire_internals 1.3.4
|   |   |   |-- collection...
|   |   |   |-- firebase_core...
|   |   |   |-- firebase_core_platform_interface...
|   |   |   |-- flutter...
|   |   |   '-- meta...
|   |   |-- firebase_core...
|   |   |-- flutter...
|   |   |-- meta...
|   |   '-- plugin_platform_interface...
|   |-- firebase_messaging_web 3.5.4
|   |   |-- _flutterfire_internals...
|   |   |-- firebase_core...
|   |   |-- firebase_core_web...
|   |   |-- firebase_messaging_platform_interface...
|   |   |-- flutter...
|   |   |-- flutter_web_plugins...
|   |   |-- js...
|   |   '-- meta...
|   |-- firebase_core...
|   |-- flutter...
|   '-- meta...
|-- firebase_storage 11.2.5
|   |-- firebase_storage_platform_interface 4.4.4
|   |   |-- collection...
|   |   |-- firebase_core...
|   |   |-- flutter...
|   |   |-- meta...
|   |   '-- plugin_platform_interface...
|   |-- firebase_storage_web 3.6.5
|   |   |-- _flutterfire_internals...
|   |   |-- async...
|   |   |-- firebase_core...
|   |   |-- firebase_core_web...
|   |   |-- firebase_storage_platform_interface...
|   |   |-- flutter...
|   |   |-- flutter_web_plugins...
|   |   |-- http...
|   |   |-- js...
|   |   '-- meta...
|   |-- firebase_core...
|   |-- firebase_core_platform_interface...
|   '-- flutter...
|-- flare_flutter 3.0.2
|   |-- collection...
|   |-- flutter...
|   '-- meta...
|-- flutter 0.0.0
|   |-- characters 1.3.0
|   |-- collection 1.17.1
|   |-- js 0.6.7
|   |   '-- meta...
|   |-- material_color_utilities 0.2.0
|   |-- meta 1.9.1
|   |-- sky_engine 0.0.99
|   '-- vector_math 2.1.4
|-- flutter_app_badger 1.5.0
|   '-- flutter...
|-- flutter_cache_manager 3.3.1
|   |-- file 6.1.4
|   |   |-- meta...
|   |   '-- path...
|   |-- rxdart 0.27.7
|   |-- sqflite 2.2.8+4
|   |   |-- sqflite_common 2.4.5+1
|   |   |   |-- synchronized 3.1.0
|   |   |   |-- meta...
|   |   |   '-- path...
|   |   |-- flutter...
|   |   '-- path...
|   |-- uuid 3.0.7
|   |   '-- crypto...
|   |-- clock...
|   |-- collection...
|   |-- flutter...
|   |-- http...
|   |-- path...
|   '-- path_provider...
|-- flutter_downloader 1.10.5
|   '-- flutter...
|-- flutter_linkify 6.0.0
|   |-- linkify 5.0.0
|   '-- flutter...
|-- flutter_local_notifications 15.1.0+1
|   |-- clock 1.1.1
|   |-- flutter_local_notifications_linux 4.0.0+1
|   |   |-- dbus 0.7.8
|   |   |   |-- args...
|   |   |   |-- ffi...
|   |   |   |-- meta...
|   |   |   '-- xml...
|   |   |-- ffi...
|   |   |-- flutter...
|   |   |-- flutter_local_notifications_platform_interface...
|   |   |-- path...
|   |   '-- xdg_directories...
|   |-- flutter_local_notifications_platform_interface 7.0.0+1
|   |   |-- flutter...
|   |   '-- plugin_platform_interface...
|   |-- timezone 0.9.2
|   |   '-- path...
|   '-- flutter...
|-- flutter_stripe 9.2.2
|   |-- stripe_android 9.2.1
|   |   '-- flutter...
|   |-- stripe_ios 9.2.1
|   |   '-- flutter...
|   |-- stripe_platform_interface 9.2.2
|   |   |-- freezed_annotation 2.4.1
|   |   |   |-- collection...
|   |   |   |-- json_annotation...
|   |   |   '-- meta...
|   |   |-- json_annotation 4.8.1
|   |   |   '-- meta...
|   |   |-- flutter...
|   |   |-- meta...
|   |   '-- plugin_platform_interface...
|   |-- flutter...
|   '-- meta...
|-- flutter_svg 2.0.7
|   |-- vector_graphics 1.1.7
|   |   |-- flutter...
|   |   '-- vector_graphics_codec...
|   |-- vector_graphics_codec 1.1.7
|   |-- vector_graphics_compiler 1.1.7
|   |   |-- path_parsing 1.0.1
|   |   |   |-- meta...
|   |   |   '-- vector_math...
|   |   |-- xml 6.3.0
|   |   |   |-- petitparser 5.4.0
|   |   |   |   '-- meta...
|   |   |   |-- collection...
|   |   |   '-- meta...
|   |   |-- args...
|   |   |-- meta...
|   |   '-- vector_graphics_codec...
|   '-- flutter...
|-- flutter_test 0.0.0
|   |-- boolean_selector 2.1.1
|   |   |-- source_span...
|   |   '-- string_scanner...
|   |-- fake_async 1.3.1
|   |   |-- clock...
|   |   '-- collection...
|   |-- matcher 0.12.15
|   |   |-- async...
|   |   |-- meta...
|   |   |-- stack_trace...
|   |   |-- term_glyph...
|   |   '-- test_api...
|   |-- source_span 1.9.1
|   |   |-- collection...
|   |   |-- path...
|   |   '-- term_glyph...
|   |-- stack_trace 1.11.0
|   |   '-- path...
|   |-- stream_channel 2.1.1
|   |   '-- async...
|   |-- string_scanner 1.2.0
|   |   '-- source_span...
|   |-- term_glyph 1.2.1
|   |-- test_api 0.5.1
|   |   |-- async...
|   |   |-- boolean_selector...
|   |   |-- collection...
|   |   |-- matcher...
|   |   |-- meta...
|   |   |-- source_span...
|   |   |-- stack_trace...
|   |   |-- stream_channel...
|   |   |-- string_scanner...
|   |   '-- term_glyph...
|   |-- async...
|   |-- characters...
|   |-- clock...
|   |-- collection...
|   |-- flutter...
|   |-- js...
|   |-- material_color_utilities...
|   |-- meta...
|   |-- path...
|   '-- vector_math...
|-- get 4.6.5
|   '-- flutter...
|-- get_storage 2.1.1
|   |-- flutter...
|   |-- get...
|   '-- path_provider...
|-- google_fonts 5.1.0
|   |-- crypto 3.0.3
|   |   '-- typed_data...
|   |-- flutter...
|   |-- http...
|   '-- path_provider...
|-- google_sign_in 6.1.4
|   |-- google_sign_in_android 6.1.18
|   |   |-- flutter...
|   |   '-- google_sign_in_platform_interface...
|   |-- google_sign_in_ios 5.6.2
|   |   |-- flutter...
|   |   '-- google_sign_in_platform_interface...
|   |-- google_sign_in_platform_interface 2.4.1
|   |   |-- quiver 3.2.1
|   |   |   '-- matcher...
|   |   |-- flutter...
|   |   '-- plugin_platform_interface...
|   |-- google_sign_in_web 0.12.0+2
|   |   |-- google_identity_services_web 0.2.1
|   |   |   |-- js...
|   |   |   '-- meta...
|   |   |-- flutter...
|   |   |-- flutter_web_plugins...
|   |   |-- google_sign_in_platform_interface...
|   |   |-- http...
|   |   '-- js...
|   '-- flutter...
|-- http 1.1.0
|   |-- async...
|   |-- http_parser...
|   '-- meta...
|-- image_picker 1.0.1
|   |-- image_picker_android 0.8.7+3
|   |   |-- flutter...
|   |   |-- flutter_plugin_android_lifecycle...
|   |   '-- image_picker_platform_interface...
|   |-- image_picker_for_web 2.2.0
|   |   |-- flutter...
|   |   |-- flutter_web_plugins...
|   |   |-- image_picker_platform_interface...
|   |   '-- mime...
|   |-- image_picker_ios 0.8.8
|   |   |-- flutter...
|   |   '-- image_picker_platform_interface...
|   |-- image_picker_linux 0.2.1
|   |   |-- file_selector_linux 0.9.2
|   |   |   |-- cross_file...
|   |   |   |-- file_selector_platform_interface...
|   |   |   '-- flutter...
|   |   |-- file_selector_platform_interface 2.6.0
|   |   |   |-- cross_file...
|   |   |   |-- flutter...
|   |   |   |-- http...
|   |   |   '-- plugin_platform_interface...
|   |   |-- flutter...
|   |   '-- image_picker_platform_interface...
|   |-- image_picker_macos 0.2.1
|   |   |-- file_selector_macos 0.9.3+1
|   |   |   |-- cross_file...
|   |   |   |-- file_selector_platform_interface...
|   |   |   '-- flutter...
|   |   |-- file_selector_platform_interface...
|   |   |-- flutter...
|   |   '-- image_picker_platform_interface...
|   |-- image_picker_platform_interface 2.8.0
|   |   |-- cross_file 0.3.3+4
|   |   |   |-- js...
|   |   |   '-- meta...
|   |   |-- flutter...
|   |   |-- http...
|   |   '-- plugin_platform_interface...
|   |-- image_picker_windows 0.2.1
|   |   |-- file_selector_windows 0.9.3
|   |   |   |-- cross_file...
|   |   |   |-- file_selector_platform_interface...
|   |   |   '-- flutter...
|   |   |-- file_selector_platform_interface...
|   |   |-- flutter...
|   |   '-- image_picker_platform_interface...
|   '-- flutter...
|-- launch_review 3.0.1
|   '-- flutter...
|-- lottie 2.5.0
|   |-- archive 3.3.7
|   |   |-- pointycastle 3.7.3
|   |   |   |-- collection...
|   |   |   |-- convert...
|   |   |   '-- js...
|   |   |-- crypto...
|   |   '-- path...
|   |-- flutter...
|   |-- path...
|   '-- vector_math...
|-- nb_utils 6.0.0
|   |-- connectivity_plus 4.0.1
|   |   |-- connectivity_plus_platform_interface 1.2.4
|   |   |   |-- flutter...
|   |   |   |-- meta...
|   |   |   '-- plugin_platform_interface...
|   |   |-- nm 0.5.0
|   |   |   '-- dbus...
|   |   |-- flutter...
|   |   |-- flutter_web_plugins...
|   |   |-- js...
|   |   '-- meta...
|   |-- fluttertoast 8.2.2
|   |   |-- flutter...
|   |   '-- flutter_web_plugins...
|   |-- flutter...
|   '-- shared_preferences...
|-- open_file 3.3.2
|   |-- ffi 2.0.2
|   '-- flutter...
|-- palette_generator 0.3.3+2
|   |-- collection...
|   |-- flutter...
|   '-- path...
|-- path_provider 2.0.15
|   |-- path_provider_android 2.0.27
|   |   |-- flutter...
|   |   '-- path_provider_platform_interface...
|   |-- path_provider_foundation 2.2.4
|   |   |-- flutter...
|   |   '-- path_provider_platform_interface...
|   |-- path_provider_linux 2.1.11
|   |   |-- xdg_directories 1.0.1
|   |   |   |-- meta...
|   |   |   '-- path...
|   |   |-- ffi...
|   |   |-- flutter...
|   |   |-- path...
|   |   '-- path_provider_platform_interface...
|   |-- path_provider_platform_interface 2.0.6
|   |   |-- platform 3.1.0
|   |   |-- flutter...
|   |   '-- plugin_platform_interface...
|   |-- path_provider_windows 2.1.7
|   |   |-- ffi...
|   |   |-- flutter...
|   |   |-- path...
|   |   |-- path_provider_platform_interface...
|   |   '-- win32...
|   '-- flutter...
|-- percent_indicator 4.2.3
|   '-- flutter...
|-- pigeon 10.1.3
|   |-- analyzer 5.13.0
|   |   |-- _fe_analyzer_shared 61.0.0
|   |   |   '-- meta...
|   |   |-- convert 3.1.1
|   |   |   '-- typed_data...
|   |   |-- glob 2.1.2
|   |   |   |-- async...
|   |   |   |-- collection...
|   |   |   |-- file...
|   |   |   |-- path...
|   |   |   '-- string_scanner...
|   |   |-- package_config 2.1.0
|   |   |   '-- path...
|   |   |-- pub_semver 2.1.4
|   |   |   |-- collection...
|   |   |   '-- meta...
|   |   |-- watcher 1.1.0
|   |   |   |-- async...
|   |   |   '-- path...
|   |   |-- collection...
|   |   |-- crypto...
|   |   |-- meta...
|   |   |-- path...
|   |   |-- source_span...
|   |   '-- yaml...
|   |-- args 2.4.2
|   |-- yaml 3.1.2
|   |   |-- collection...
|   |   |-- source_span...
|   |   '-- string_scanner...
|   |-- collection...
|   |-- meta...
|   '-- path...
|-- pusher_client 2.0.0
|   '-- flutter...
|-- share 2.0.4
|   |-- mime 1.0.4
|   |-- flutter...
|   '-- meta...
|-- shared_preferences 2.2.0
|   |-- shared_preferences_android 2.2.0
|   |   |-- flutter...
|   |   '-- shared_preferences_platform_interface...
|   |-- shared_preferences_foundation 2.3.2
|   |   |-- flutter...
|   |   '-- shared_preferences_platform_interface...
|   |-- shared_preferences_linux 2.3.0
|   |   |-- file...
|   |   |-- flutter...
|   |   |-- path...
|   |   |-- path_provider_linux...
|   |   |-- path_provider_platform_interface...
|   |   '-- shared_preferences_platform_interface...
|   |-- shared_preferences_platform_interface 2.3.0
|   |   |-- flutter...
|   |   '-- plugin_platform_interface...
|   |-- shared_preferences_web 2.2.0
|   |   |-- flutter...
|   |   |-- flutter_web_plugins...
|   |   '-- shared_preferences_platform_interface...
|   |-- shared_preferences_windows 2.3.0
|   |   |-- file...
|   |   |-- flutter...
|   |   |-- path...
|   |   |-- path_provider_platform_interface...
|   |   |-- path_provider_windows...
|   |   '-- shared_preferences_platform_interface...
|   '-- flutter...
'-- water_drop_nav_bar 2.2.0+5
    '-- flutter...

```

</details>

---

**Comment by bhumkong** [comment] 2023-07-18 15:02
Duplicate of https://github.com/firebase/flutterfire/issues/11297

**Comment by danagbemava-nc** [comment] 2023-07-19 10:44
Closing this as a duplicate of https://github.com/firebase/flutterfire/issues/11297

**Closed by danagbemava-nc** 2023-07-19 10:44 UTC
Labels: type: bug, Needs Attention, in triage
