### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'settings')🐛 (getting this issue only for flutter web)

### ISSUE THREAD

**Issue by harischandra7** [firebase/flutterfire#9128] opened 2022-07-17 12:17 UTC
recaptcha_verifier.ts:116 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'settings')
    at new RecaptchaVerifier (recaptcha_verifier.ts:116:39)
    at RecaptchaVerifier.new (auth.dart:998:32)
    at new firebase_auth_web_recaptcha_verifier_factory.RecaptchaVerifierFactoryWeb.new (firebase_auth_web_recaptcha_verifier_factory.dart:89:30)
    at firebase_auth_web_recaptcha_verifier_factory.RecaptchaVerifierFactoryWeb.__.delegateFor (firebase_auth_web_recaptcha_verifier_factory.dart:101:12)
    at RecaptchaVerifier.new (recaptcha_verifier.dart:57:16)
    at firebase_auth.FirebaseAuth.__.signInWithPhoneNumber (firebase_auth.dart:610:18)
    at signInWithPhoneNumber.next (<anonymous>)
    at runBody (async_patch.dart:84:54)
    at Object._async [as async] (async_patch.dart:123:5)
    at firebase_auth.FirebaseAuth.__.signInWithPhoneNumber (firebase_auth.dart:602:51)
    at auth_repository.AuthRepository.new.signInWithPhoneNumber (auth_repository.dart:144:31)
    at signInWithPhoneNumber.next (<anonymous>)
    at runBody (async_patch.dart:84:54)
    at Object._async [as async] (async_patch.dart:123:5)
    at auth_repository.AuthRepository.new.signInWithPhoneNumber (auth_repository.dart:140:72)
    at phone_number_sign_in_or_sign_up_cubit.PhoneNumberSignInCubit.new.signInOrSignUpWithPhoneNumber (phone_number_sign_in_or_sign_up_cubit.dart:77:45)
    at signInOrSignUpWithPhoneNumber.next (<anonymous>)
    at runBody (async_patch.dart:84:54)
    at Object._async [as async] (async_patch.dart:123:5)
    at phone_number_sign_in_or_sign_up_cubit.PhoneNumberSignInCubit.new.signInOrSignUpWithPhoneNumber (phone_number_sign_in_or_sign_up_cubit.dart:43:37)
    at login_with_phone.dart:250:38
    at tap.TapGestureRecognizer.new.invokeCallback (recognizer.dart:198:24)
    at tap.TapGestureRecognizer.new.handleTapUp (tap.dart:613:48)
    at [_checkUp] (tap.dart:298:5)
    at tap.TapGestureRecognizer.new.handlePrimaryPointer (tap.dart:232:7)
    at tap.TapGestureRecognizer.new.handleEvent (recognizer.dart:563:9)
    at [_dispatch] (pointer_router.dart:94:12)
    at pointer_router.dart:139:9
    at LinkedMap.new.forEach (linked_hash_map.dart:21:13)
    at [_dispatchEventToRoutes] (pointer_router.dart:137:17)
    at pointer_router.PointerRouter.new.route (pointer_router.dart:123:7)
    at binding$5.WidgetsFlutterBinding.new.handleEvent (binding.dart:445:19)
    at binding$5.WidgetsFlutterBinding.new.dispatchEvent (binding.dart:425:14)
    at binding$5.WidgetsFlutterBinding.new.dispatchEvent (binding.dart:329:11)
    at [_handlePointerEventImmediately] (binding.dart:380:7)
    at binding$5.WidgetsFlutterBinding.new.handlePointerEvent (binding.dart:344:5)
    at [_flushPointerEventQueue] (binding.dart:302:7)
    at [_handlePointerDataPacket] (binding.dart:285:32)
    at Object.invoke1 (platform_dispatcher.dart:1105:13)
    at _engine.EnginePlatformDispatcher.__.invokeOnPointerDataPacket (platform_dispatcher.dart:185:5)
    at [_onPointerData] (pointer_binding.dart:130:39)
    at pointer_binding.dart:543:18
    at pointer_binding.dart:496:21
    at loggedHandler (pointer_binding.dart:210:16)
    
    
    ## 
    General view of code 

##----- firebase initialization----

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

## signinWithPhone

class AuthRepository {
  final FirebaseAuth _firebaseAuth = locator.get<FirebaseAuth>();

  signInWithPhoneNumber(required String phoneNumber)async{
    final _confirmationResult =
          await _firebaseAuth.signInWithPhoneNumber(phoneNumber);

  }
}

##------ init.dart ----
import 'dart:developer';
import 'dart:io';

import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:dio/dio.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_messaging/firebase_messaging.dart';

GetIt locator = GetIt.instance;

 class Init {
  static Future<void> initialize() async {
    setPathUrlStrategy();
    await _initializeFirebase();

  }

  static Future<void> _initializeFirebase() async {
    log("initializing firebase...");
    WidgetsFlutterBinding.ensureInitialized();
    try {
      final res = await Firebase.initializeApp(
        options: DefaultFirebaseOptions.currentPlatform,
      );
      log(res.toString());

    } on FirebaseException catch (e) {
      log("error ==> ${e.toString()}");
    } catch (e) {
      log(e.toString());
    }
    // }
  }

  static Future<void> _registerServices() async {
    locator.registerLazySingleton(() {
      final Dio _dio = Dio(
        BaseOptions(
          contentType: 'application/json',
          responseType: ResponseType.json,
        ),
      );
      _dio.interceptors.add(AppInterceptors());
      return _dio;
    });
    // locator.registerLazySingleton<AppRouter>(
    //     () => AppRouter(authRouteGuard: AuthRouteGuard(AuthRepository())));
    locator.registerLazySingleton<AppRouter>(() => AppRouter());
    locator.registerLazySingleton<FirebaseAuth>(() => FirebaseAuth.instance);
    locator.registerLazySingleton<FirebaseFirestore>(
      () => FirebaseFirestore.instance,
    );
    locator.registerLazySingleton<FirebaseMessaging>(
      () => FirebaseMessaging.instance,
    );
  }

}

Note: This issue is there only on flutter web.  same initialization is working perfectly fine for email login  web and all auth feature on mobile.

**Comment by Ipicon** [comment] 2022-07-17 15:36
https://github.com/firebase/flutterfire/issues/9123

**Comment by darshankawar** [comment] 2022-07-18 10:52
Closing this as duplicate of https://github.com/firebase/flutterfire/issues/9097

**Closed by darshankawar** 2022-07-18 10:52 UTC
Labels: type: bug, Needs Attention, in triage
