### ISSUE TITLE
bug build jdk 11

### ISSUE THREAD

**Issue by rezadevelopers2** [firebase/flutterfire#10525] opened 2023-02-25 05:52 UTC
android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java:39: error: cannot access BroadcastReceiver
      flutterEngine.getPlugins().add(new io.flutter.plugins.firebase.messaging.FlutterFirebaseMessagingPlugin());
                                ^
  class file for android.content.BroadcastReceiver not found

**Comment by darshankawar** [comment] 2023-02-27 12:35
Closing as duplicate of https://github.com/firebase/flutterfire/issues/8324.
Please check https://github.com/firebase/flutterfire/issues/8324#issuecomment-1079818361 for solution.

**Closed by darshankawar** 2023-02-27 12:35 UTC
Labels: type: bug, Needs Attention, in triage
