### ISSUE TITLE
🐛 [firebase_dynamic_links] plus symbol in parameter comes from firebase decoded

### ISSUE THREAD

**Issue by beerline** [firebase/flutterfire#8925] opened 2022-06-16 20:29 UTC
Hello firebase team!

When I get deeplink from firebase originally encoded symbol `+` comes in decoded format i.e. as `+` instead `%2b`

### Example:
I am using base64 in query parameter in url `https://somdomain.com/path?hash=sRbw2%2Bsavatb7vPtIsZBeA%3D%3D`
decoded hash: `sRbw2+savatb7vPtIsZBeA==`
 
Deeplink looks like: 
```
https://somedomain.com.page.link?link=https%3A%2F%2Fsomedomain.com%2Fpath%3Fhash%3DsRbw2%2Bsavatb7vPtIsZBeA%3D%3D&apn=com.somedomain&ibi=com.somedomain
```

Handle deeplink
```dart
FirebaseDynamicLinks.instance.onLink.listen(
  (PendingDynamicLinkData? dynamicLink) async {
    final deepLink = dynamicLink?.link;
    if (deepLink != null) {
      await Globals.appRouter.navigateNamed('${deepLink.path}?${deepLink.query}');
    }
  },
  onError: (dynamic error) {
    print(error.toString());
  },
);
```

**Debug values:**
`deepLink.toString()`: `https://somedomain.com/path?hash=sRbw2+savatb7vPtIsZBeA%3D%3D` 
`deepLink.query`: `hash=sRbw2+savatb7vPtIsZBeA%3D%3D`
`deepLink.queryParameters['hash']`: `sRbw2 savatb7vPtIsZBeA==` here `+` replaced with `space`

As you can see `=` symbols stay in encoded format, but `+` is decoded

### Expected behavior

`+` should be encoded as `%2b`

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 3.0.1, on Mac OS X 10.15.7 19H2 darwin-x64, locale ru-RU)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[!] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    ✗ Flutter requires Xcode 13 or higher.
      Download the latest version or update via the Mac App Store.
    ! CocoaPods 1.10.0 out of date (1.11.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2019.2)
[✓] VS Code (version 1.58.2)
[✓] Connected device (4 available)
[✓] HTTP Host Availability
```

</details>

---

### Flutter dependencies

<details><summary>Click To Expand</summary>

```
Dart SDK 2.17.1
Flutter SDK 3.0.1

dependencies:
- add_2_calendar 2.1.3 [flutter]
- auto_route 4.0.1 [flutter path collection meta universal_html]
- bloc 7.2.1 [meta]
- carousel_slider 4.1.1 [flutter]
- catcher 0.7.0 [flutter flutter_web_plugins fluttertoast device_info_plus device_info_plus_platform_interface package_info_plus mailer dio flutter_mailer logging sentry universal_io]
- clock 1.1.0
- connectivity_plus 2.3.2 [flutter connectivity_plus_platform_interface connectivity_plus_linux connectivity_plus_macos connectivity_plus_web connectivity_plus_windows]
- cupertino_icons 1.0.4
- device_info_plus 3.2.3 [flutter device_info_plus_platform_interface device_info_plus_macos device_info_plus_linux device_info_plus_web device_info_plus_windows]
- device_preview 1.1.0 [flutter flutter_localizations provider device_frame freezed_annotation json_annotation shared_preferences collection]
- dio 4.0.6 [http_parser path]
- dropdown_search 4.0.1 [flutter]
- equatable 2.0.3 [collection meta]
- facebook_app_events 0.16.0 [flutter]
- file_picker 4.6.0 [flutter flutter_web_plugins flutter_plugin_android_lifecycle plugin_platform_interface ffi path win32]
- firebase_analytics 9.1.9 [firebase_analytics_platform_interface firebase_analytics_web firebase_core firebase_core_platform_interface flutter]
- firebase_core 1.17.1 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_crashlytics 2.8.1 [firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface flutter stack_trace]
- firebase_dynamic_links 4.2.5 [firebase_core firebase_core_platform_interface firebase_dynamic_links_platform_interface flutter meta plugin_platform_interface]
- firebase_messaging 11.4.1 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- fl_chart 0.50.6 [flutter equatable]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- flutter_bloc 7.3.3 [flutter bloc provider]
- flutter_blurhash 0.7.0 [flutter]
- flutter_facebook_auth 4.3.4 [flutter flutter_facebook_auth_platform_interface flutter_facebook_auth_web]
- flutter_inappwebview 5.4.3+7 [flutter]
- flutter_layout_grid 2.0.1 [flutter collection meta quiver]
- flutter_localizations 0.0.0 [flutter intl characters clock collection material_color_utilities meta path vector_math]
- flutter_rating_bar 4.0.1 [flutter]
- flutter_secure_storage 5.0.2 [meta flutter flutter_secure_storage_linux flutter_secure_storage_macos flutter_secure_storage_platform_interface flutter_secure_storage_web flutter_secure_storage_windows]
- flutter_svg 1.1.0 [flutter meta path_drawing vector_math xml]
- flutter_switch 0.3.2 [flutter]
- flutter_widget_from_html_core 0.8.5+3 [csslib flutter fwfh_text_style html]
- get_it 7.2.0 [async collection]
- google_sign_in 5.3.2 [flutter google_sign_in_android google_sign_in_ios google_sign_in_platform_interface google_sign_in_web]
- hive 2.2.1 [meta crypto]
- hydrated_bloc 7.1.0 [bloc hive meta synchronized]
- image_picker 0.8.5+3 [flutter image_picker_android image_picker_for_web image_picker_ios image_picker_platform_interface]
- in_app_purchase 3.0.4 [flutter in_app_purchase_android in_app_purchase_platform_interface in_app_purchase_storekit]
- infinite_scroll_pagination 3.2.0 [flutter sliver_tools]
- injectable 1.5.3 [get_it]
- json_annotation 4.5.0 [meta]
- mime 1.0.2
- mobile_scanner 2.0.0 [flutter flutter_web_plugins js]
- new_version 0.3.0 [flutter package_info_plus http html url_launcher collection]
- package_info_plus 1.4.2 [flutter package_info_plus_platform_interface package_info_plus_linux package_info_plus_macos package_info_plus_windows package_info_plus_web]
- path_provider 2.0.10 [flutter path_provider_android path_provider_ios path_provider_linux path_provider_macos path_provider_platform_interface path_provider_windows]
- pdfx 2.0.1+2 [flutter flutter_web_plugins plugin_platform_interface js device_info_plus uuid meta extension synchronized universal_platform photo_view vector_math]
- permission_handler 9.2.0 [flutter meta permission_handler_android permission_handler_apple permission_handler_windows permission_handler_platform_interface]
- pull_to_refresh 2.0.0 [flutter]
- reactive_forms 12.0.0 [flutter intl]
- retrofit 3.0.1+1 [dio meta]
- retry 3.1.0
- rxdart 0.27.4
- scroll_to_index 3.0.1 [flutter]
- share_plus 4.0.5 [meta mime flutter share_plus_platform_interface share_plus_linux share_plus_macos share_plus_windows share_plus_web]
- shared_preferences 2.0.15 [flutter shared_preferences_android shared_preferences_ios shared_preferences_linux shared_preferences_macos shared_preferences_platform_interface shared_preferences_web shared_preferences_windows]
- shimmer 2.0.0 [flutter]
- sign_in_with_apple 3.3.0 [flutter meta sign_in_with_apple_platform_interface sign_in_with_apple_web]
- signature 5.0.1 [flutter image]
- sliver_tools 0.2.6 [flutter]
- socket_io_client 2.0.0-beta.4-nullsafety.0 [logging socket_io_common js]
- ua_client_hints 1.1.0 [flutter]
- url_launcher 6.1.2 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- waterfall_flow 3.0.2 [collection extended_list_library flutter]
- youtube_player_iframe 2.3.0 [flutter flutter_inappwebview url_launcher]

dev dependencies:
- auto_route_generator 4.0.0 [build source_gen analyzer path build_runner code_builder dart_style auto_route]
- bloc_test 8.5.0 [bloc diff_match_patch meta mocktail test]
- build_runner 2.1.11 [args async analyzer build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style frontend_server_client glob graphs http_multi_server io js logging meta mime package_config path pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web_socket_channel yaml]
- dart_code_metrics 4.15.2 [analyzer analyzer_plugin ansicolor args collection crypto file glob html meta path source_span xml yaml]
- derry 1.4.3 [args console equatable ffi path string_similarity yaml]
- flutter_launcher_icons 0.9.2 [args image path yaml]
- flutter_lints 2.0.1 [lints]
- flutter_native_splash 2.2.2 [args flutter flutter_web_plugins image js lint meta path universal_io xml yaml]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher material_color_utilities meta source_span stream_channel string_scanner term_glyph]
- golden_toolkit 0.13.0 [flutter flutter_test meta]
- http_mock_adapter 0.3.2 [collection dio http_parser]
- injectable_generator 1.5.2 [build source_gen path glob analyzer code_builder dart_style injectable collection]
- integration_test 0.0.0 [flutter flutter_driver flutter_test path vm_service archive async boolean_selector characters charcode clock collection crypto fake_async file matcher material_color_utilities meta source_span stack_trace stream_channel string_scanner sync_http term_glyph test_api typed_data vector_math webdriver]
- json_serializable 6.2.0 [analyzer async build build_config collection json_annotation meta path pub_semver pubspec_parse source_gen source_helper]
- mocktail 0.2.0 [collection matcher test]
- network_image_mock 2.1.0 [flutter mockito]
- retrofit_generator 3.0.1+1 [dio source_gen built_collection code_builder tuple retrofit analyzer dart_style build]

dependency overrides:
- catcher 0.7.0 [flutter flutter_web_plugins fluttertoast device_info_plus device_info_plus_platform_interface package_info_plus mailer dio flutter_mailer logging sentry universal_io]
- pull_to_refresh 2.0.0 [flutter]

transitive dependencies:
- _fe_analyzer_shared 31.0.0 [meta]
- analyzer 2.8.0 [_fe_analyzer_shared cli_util collection convert crypto glob meta package_config path pub_semver source_span watcher yaml]
- analyzer_plugin 0.8.0 [analyzer collection dart_style pub_semver yaml]
- ansicolor 2.0.1
- archive 3.1.11 [crypto path]
- args 2.3.1
- async 2.8.2 [collection meta]
- boolean_selector 2.1.0 [source_span string_scanner]
- build 2.3.0 [analyzer async convert crypto glob logging meta path]
- build_config 1.0.0 [checked_yaml json_annotation path pubspec_parse yaml]
- build_daemon 3.1.0 [built_collection built_value http_multi_server logging path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 2.0.6 [analyzer async build crypto graphs logging path package_config pool pub_semver stream_transform yaml]
- build_runner_core 7.2.3 [async build build_config build_resolvers collection convert crypto glob graphs json_annotation logging meta path package_config pool timing watcher yaml]
- built_collection 5.1.1
- built_value 8.3.2 [built_collection collection fixnum meta]
- characters 1.2.0
- charcode 1.3.1
- checked_yaml 2.0.1 [json_annotation source_span yaml]
- cli_util 0.3.5 [meta path]
- code_builder 4.1.0 [built_collection built_value collection matcher meta]
- collection 1.16.0
- connectivity_plus_linux 1.3.1 [flutter connectivity_plus_platform_interface meta nm]
- connectivity_plus_macos 1.2.2 [connectivity_plus_platform_interface flutter]
- connectivity_plus_platform_interface 1.2.1 [flutter meta plugin_platform_interface]
- connectivity_plus_web 1.2.1 [connectivity_plus_platform_interface flutter_web_plugins flutter]
- connectivity_plus_windows 1.2.1 [connectivity_plus_platform_interface flutter]
- console 4.1.0 [vector_math]
- convert 3.0.2 [typed_data]
- coverage 1.2.0 [args logging package_config path source_maps stack_trace vm_service]
- cross_file 0.3.3+1 [js meta]
- crypto 3.0.1 [collection typed_data]
- csslib 0.17.2 [source_span]
- dart_style 2.2.1 [analyzer args path pub_semver source_span]
- dbus 0.7.4 [args ffi meta xml]
- device_frame 1.1.0 [freezed_annotation flutter]
- device_info_plus_linux 2.1.1 [device_info_plus_platform_interface file flutter meta]
- device_info_plus_macos 2.2.3 [device_info_plus_platform_interface flutter]
- device_info_plus_platform_interface 2.3.0+1 [flutter meta plugin_platform_interface]
- device_info_plus_web 2.1.0 [device_info_plus_platform_interface flutter_web_plugins flutter]
- device_info_plus_windows 2.1.1 [device_info_plus_platform_interface ffi flutter win32]
- diff_match_patch 0.4.1
- extended_list_library 3.0.0 [flutter]
- extension 0.2.0
- fake_async 1.3.0 [clock collection]
- ffi 1.2.1
- file 6.1.2 [meta path]
- firebase_analytics_platform_interface 3.1.7 [firebase_core flutter meta plugin_platform_interface]
- firebase_analytics_web 0.4.0+14 [firebase_analytics_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- firebase_core_platform_interface 4.4.0 [collection flutter meta plugin_platform_interface]
- firebase_core_web 1.6.4 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_crashlytics_platform_interface 3.2.7 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_dynamic_links_platform_interface 0.2.3+3 [firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_platform_interface 3.5.1 [firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 2.4.1 [firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]
- fixnum 1.0.1
- flutter_driver 0.0.0 [file flutter flutter_test fuchsia_remote_debug_protocol path meta vm_service webdriver archive async boolean_selector characters charcode clock collection crypto matcher material_color_utilities platform process source_span stack_trace stream_channel string_scanner sync_http term_glyph test_api typed_data vector_math]
- flutter_facebook_auth_platform_interface 3.1.2 [flutter plugin_platform_interface]
- flutter_facebook_auth_web 3.1.2 [flutter flutter_web_plugins js flutter_facebook_auth_platform_interface]
- flutter_mailer 2.0.1 [flutter]
- flutter_plugin_android_lifecycle 2.0.6 [flutter]
- flutter_secure_storage_linux 1.1.0 [flutter flutter_secure_storage_platform_interface]
- flutter_secure_storage_macos 1.1.0 [flutter flutter_secure_storage_platform_interface]
- flutter_secure_storage_platform_interface 1.0.0 [flutter plugin_platform_interface]
- flutter_secure_storage_web 1.0.2 [flutter flutter_web_plugins flutter_secure_storage_platform_interface js]
- flutter_secure_storage_windows 1.1.2 [flutter flutter_secure_storage_platform_interface]
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta vector_math]
- fluttertoast 8.0.9 [flutter flutter_web_plugins]
- freezed_annotation 2.0.3 [collection json_annotation meta]
- frontend_server_client 2.1.3 [async path]
- fuchsia_remote_debug_protocol 0.0.0 [process vm_service file meta path platform]
- fwfh_text_style 2.7.3+2 [flutter]
- glob 2.0.2 [async collection file path string_scanner]
- google_sign_in_android 5.2.8 [flutter google_sign_in_platform_interface]
- google_sign_in_ios 5.3.1 [flutter google_sign_in_platform_interface]
- google_sign_in_platform_interface 2.1.3 [flutter quiver]
- google_sign_in_web 0.10.1+2 [flutter flutter_web_plugins google_sign_in_platform_interface js]
- graphs 2.1.0 [collection]
- html 0.15.0 [csslib source_span]
- http 0.13.4 [async http_parser meta path]
- http_multi_server 3.2.0 [async]
- http_parser 4.0.1 [collection source_span string_scanner typed_data]
- image 3.2.0 [archive meta xml]
- image_picker_android 0.8.4+13 [flutter flutter_plugin_android_lifecycle image_picker_platform_interface]
- image_picker_for_web 2.1.8 [flutter flutter_web_plugins image_picker_platform_interface]
- image_picker_ios 0.8.5+5 [flutter image_picker_platform_interface]
- image_picker_platform_interface 2.5.0 [cross_file flutter http plugin_platform_interface]
- in_app_purchase_android 0.2.2+6 [collection flutter in_app_purchase_platform_interface json_annotation]
- in_app_purchase_platform_interface 1.3.1 [flutter plugin_platform_interface]
- in_app_purchase_storekit 0.3.0+8 [collection flutter in_app_purchase_platform_interface json_annotation]
- intl 0.17.0 [clock path]
- io 1.0.3 [meta path string_scanner]
- js 0.6.4
- lint 1.8.2
- lints 2.0.0
- logging 1.0.2
- mailer 5.1.1 [async logging intl mime path pedantic meta]
- matcher 0.12.11 [stack_trace]
- material_color_utilities 0.1.4
- meta 1.7.0
- mockito 5.2.0 [analyzer build code_builder collection dart_style matcher meta path source_gen test_api]
- nested 1.0.0 [flutter]
- nm 0.5.0 [dbus]
- node_preamble 2.0.1
- package_config 2.0.2 [path]
- package_info_plus_linux 1.0.5 [package_info_plus_platform_interface flutter path]
- package_info_plus_macos 1.3.0 [flutter]
- package_info_plus_platform_interface 1.0.2 [flutter meta plugin_platform_interface]
- package_info_plus_web 1.0.5 [flutter flutter_web_plugins http meta package_info_plus_platform_interface]
- package_info_plus_windows 1.0.5 [package_info_plus_platform_interface ffi flutter win32]
- path 1.8.1
- path_drawing 1.0.0 [vector_math meta path_parsing flutter]
- path_parsing 1.0.0 [vector_math meta]
- path_provider_android 2.0.14 [flutter path_provider_platform_interface]
- path_provider_ios 2.0.9 [flutter path_provider_platform_interface]
- path_provider_linux 2.1.7 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_macos 2.0.6 [flutter path_provider_platform_interface]
- path_provider_platform_interface 2.0.4 [flutter platform plugin_platform_interface]
- path_provider_windows 2.0.7 [ffi flutter path path_provider_platform_interface win32]
- pedantic 1.11.1
- permission_handler_android 9.0.2+1 [flutter permission_handler_platform_interface]
- permission_handler_apple 9.0.4 [flutter permission_handler_platform_interface]
- permission_handler_platform_interface 3.7.0 [flutter meta plugin_platform_interface]
- permission_handler_windows 0.1.0 [flutter permission_handler_platform_interface]
- petitparser 5.0.0 [meta]
- photo_view 0.13.0 [flutter]
- platform 3.1.0
- plugin_platform_interface 2.1.2 [meta]
- pool 1.5.0 [async stack_trace]
- process 4.2.4 [file path platform]
- provider 6.0.3 [collection flutter nested]
- pub_semver 2.1.1 [collection meta]
- pubspec_parse 1.2.0 [checked_yaml collection json_annotation pub_semver yaml]
- quiver 3.1.0 [matcher]
- sentry 6.5.1 [http meta stack_trace uuid]
- share_plus_linux 3.0.0 [share_plus_platform_interface file flutter meta url_launcher]
- share_plus_macos 3.0.1 [share_plus_platform_interface flutter]
- share_plus_platform_interface 3.0.3 [flutter meta mime plugin_platform_interface]
- share_plus_web 3.0.1 [share_plus_platform_interface url_launcher flutter flutter_web_plugins meta]
- share_plus_windows 3.0.1 [share_plus_platform_interface flutter meta url_launcher]
- shared_preferences_android 2.0.12 [flutter shared_preferences_platform_interface]
- shared_preferences_ios 2.1.1 [flutter shared_preferences_platform_interface]
- shared_preferences_linux 2.1.1 [file flutter path path_provider_linux path_provider_platform_interface shared_preferences_platform_interface]
- shared_preferences_macos 2.0.4 [flutter shared_preferences_platform_interface]
- shared_preferences_platform_interface 2.0.0 [flutter]
- shared_preferences_web 2.0.4 [flutter flutter_web_plugins shared_preferences_platform_interface]
- shared_preferences_windows 2.1.1 [file flutter path path_provider_platform_interface path_provider_windows shared_preferences_platform_interface]
- shelf 1.3.0 [async collection http_parser path stack_trace stream_channel]
- shelf_packages_handler 3.0.0 [path shelf shelf_static]
- shelf_static 1.1.0 [convert http_parser mime path shelf]
- shelf_web_socket 1.0.1 [shelf stream_channel web_socket_channel]
- sign_in_with_apple_platform_interface 1.0.0 [flutter plugin_platform_interface meta]
- sign_in_with_apple_web 1.0.1 [flutter flutter_web_plugins sign_in_with_apple_platform_interface js]
- sky_engine 0.0.99
- socket_io_common 2.0.0 [logging]
- source_gen 1.2.2 [analyzer async build dart_style glob meta path source_span yaml]
- source_helper 1.3.2 [analyzer collection source_gen]
- source_map_stack_trace 2.1.0 [path stack_trace source_maps]
- source_maps 0.10.10 [source_span]
- source_span 1.8.2 [collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- stream_transform 2.0.0
- string_scanner 1.1.0 [charcode source_span]
- string_similarity 2.0.0
- sync_http 0.3.0
- synchronized 3.0.0+2
- term_glyph 1.2.0
- test 1.20.2 [analyzer async boolean_selector collection coverage http_multi_server io js node_preamble package_config path pool shelf shelf_packages_handler shelf_static shelf_web_socket source_span stack_trace stream_channel typed_data web_socket_channel webkit_inspection_protocol yaml test_api test_core]
- test_api 0.4.9 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- test_core 0.4.11 [analyzer async args boolean_selector collection coverage frontend_server_client glob io meta package_config path pool source_map_stack_trace source_maps source_span stack_trace stream_channel vm_service yaml matcher test_api]
- timing 1.0.0 [json_annotation]
- tuple 2.0.0 [quiver]
- typed_data 1.3.0 [collection]
- universal_html 2.0.8 [async csslib charcode collection html meta source_span typed_data universal_io]
- universal_io 2.0.4 [collection crypto meta typed_data]
- universal_platform 1.0.0+1
- url_launcher_android 6.0.17 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.0.17 [flutter url_launcher_platform_interface]
- url_launcher_linux 3.0.1 [flutter url_launcher_platform_interface]
- url_launcher_macos 3.0.1 [flutter url_launcher_platform_interface]
- url_launcher_platform_interface 2.0.5 [flutter plugin_platform_interface]
- url_launcher_web 2.0.11 [flutter flutter_web_plugins url_launcher_platform_interface]
- url_launcher_windows 3.0.1 [flutter url_launcher_platform_interface]
- uuid 3.0.6 [crypto]
- vector_math 2.1.2
- vm_service 8.2.2
- watcher 1.0.1 [async path]
- web_socket_channel 2.2.0 [async crypto stream_channel]
- webdriver 3.0.0 [archive matcher path stack_trace sync_http]
- webkit_inspection_protocol 1.1.0 [logging]
- win32 2.6.1 [ffi]
- xdg_directories 0.2.0+1 [meta path process]
- xml 6.1.0 [collection meta petitparser]
- yaml 3.1.1 [collection source_span string_scanner]
```

</details>

---

**Comment by maheshmnj** [comment] 2022-06-17 07:20
Hi @beerline, Thanks for filing the issue. Could you please help me with the reproducible steps to reproduce the issue, along with the version of the firebase dynamic links plugin you are using? Also, what target platform is this issue on?

Thanks

**Comment by beerline** [comment] 2022-06-17 07:45
Hi @maheshmnj!
Thank you for response!

I am using `firebase_dynamic_links: ^4.2.3`
Target platform Android.

Steps to reproduce:
1. add following code to `main.dart`
```dart
FirebaseDynamicLinks.instance.onLink.listen(
  (PendingDynamicLinkData? dynamicLink) async {
    final deepLink = dynamicLink?.link;
    if (deepLink != null) {
      Navigator.of(context).pushNamed('${deepLink.path}?${deepLink.query}');
    }
  },
  onError: (dynamic error) {
    print(error.toString());
  },
);
```
2. replace `somedomain.com` and `com.somedomain` with your domains from fire base console for deeplink `https://somedomain.com.page.link?link=https%3A%2F%2Fsomedomain.com%2Fpath%3Fhash%3DsRbw2%2Bsavatb7vPtIsZBeA%3D%3D&apn=com.somedomain&ibi=com.somedomain`
3. generate QR code for link 
4. scan QR code by camera app

**Comment by darshankawar** [comment] 2022-06-20 12:55
@beerline 
Thanks for the update. I think this behavior need to be reported in https://github.com/firebase/firebase-android-sdk/issues/ because flutterfire is just a wrapper around native SDKs and uses the incoming data as-is, so most probably the encoding should happen at server side. I see a similar issue open in that repo for your reference: https://github.com/firebase/firebase-android-sdk/issues/959. See if it is related to your case. https://github.com/firebase/firebase-android-sdk/issues/959#issuecomment-636481633

Closing for now. If you disagree, write in comments and I'll reopen it.

**Closed by darshankawar** 2022-06-20 12:55 UTC
Labels: type: bug, Needs Attention, in triage
