### ISSUE TITLE
🐛 [firebase_remote_config] _remoteConfig.getInt('paramName')  return 0 on app launch first time

### ISSUE THREAD

**Issue by hpsolver** [firebase/flutterfire#9454] opened 2022-09-01 13:44 UTC
## Bug report

**Describe the bug**
remoteConfig.getInt('paramName')  return 0 on app launch only first time.

**Comment by darshankawar** [comment] 2022-09-02 10:30
@hpsolver 
When you open a new issue, please try to use new issue template and fill out requested details so that we'll have enough info to work with. 

Based on one liner info you provided, we are not sure on which platform are you getting this behavior, so please provide `flutter doctor -v`, plugin version, platform and complete minimal reproducible code sample that shows this behavior.

**Comment by hpsolver** [comment] 2022-09-02 10:32
![Uploading image.png…]()

**Comment by hpsolver** [comment] 2022-09-02 10:35
Here is code : 

Future<void> _initConfig() async {

    await _remoteConfig.setDefaults({"dailySmsQuota": 20});

    await _remoteConfig.setConfigSettings(RemoteConfigSettings(
      fetchTimeout: const Duration(seconds: 10),
      minimumFetchInterval: const Duration(minutes: 10),
    ));


    _fetchConfig();
  }

  // Fetching, caching, and activating remote config
  void _fetchConfig() async {
    await _remoteConfig.fetchAndActivate();
  }

  @override
  void initState() {
    super.initState();
    _initConfig();
    }
    
    
     print("Quota ${_remoteConfig.getInt('parameterName')}");

**Comment by darshankawar** [comment] 2022-09-02 11:46
What's the expected result are you looking for on app launch for the first time ?

Also, the image you were trying to upload didn't upload completely, as I can't see it.

**Comment by hpsolver** [comment] 2022-09-02 13:07
Here is my expected value : 
<img width="812" alt="image" src="https://user-images.githubusercontent.com/25339734/188152597-b1284247-2410-4f9d-8835-73e727da685d.png">

**Comment by hpsolver** [comment] 2022-09-02 13:10
And i got one more issue for example right now "dailySmsQuota" value is 20 and i will Update it to 30 then in app it old value 20 for some time

**Comment by hpsolver** [comment] 2022-09-02 13:10
it take time to reflect in app ?

**Comment by darshankawar** [comment] 2022-09-05 11:12
> it take time to reflect in app ?

Since you are fetching it from server, it will take as long as fetch takes and is not in control of the plugin / flutterfire.





> return 0 on app launch only first time.

About this, even the param value is being fetched remotely so it must be coming in from the server before being used by the plugin. Hence I suggest you to ask / reach out to firebase support as to know further about why it returns 0 upon app launch and that too only for the first time.

Closing from here. If you disagree, write in comments and I'll reopen it.

**Closed by darshankawar** 2022-09-05 11:12 UTC
Labels: type: bug, Needs Attention, in triage
