### ISSUE TITLE
🐛 [firebase_storage/channel_error] Unable to establish connection on channel.

### ISSUE THREAD

**Issue by Sneh-Paghdal** [firebase/flutterfire#11821] opened 2023-11-02 15:26 UTC
Logs :
```
W/System  (31169): Ignoring header X-Firebase-Locale because its value was null.
W/LocalRequestInterceptor(31169): Error getting App Check token; using placeholder token instead. Error: com.google.firebase.FirebaseException: Error returned from API. code: 403 body: App attestation failed.
W/System  (31169): Ignoring header X-Firebase-Locale because its value was null.
W/LocalRequestInterceptor(31169): Error getting App Check token; using placeholder token instead. Error: com.google.firebase.FirebaseException: Too many attempts.
D/FirebaseAuth(31169): Notifying id token listeners about user ( ojpb09q6wvesJh3gJwY2iLMDedA3 ).
D/FirebaseAuth(31169): Notifying auth state listeners about user ( ojpb09q6wvesJh3gJwY2iLMDedA3 ).
I/flutter (31169): ojpb09q6wvesJh3gJwY2iLMDedA3
W/StorageUtil(31169): Error getting App Check token; using placeholder token instead. Error: com.google.firebase.FirebaseException: Too many attempts.
D/UploadTask(31169): Waiting 0 milliseconds
W/StorageUtil(31169): Error getting App Check token; using placeholder token instead. Error: com.google.firebase.FirebaseException: Too many attempts.
D/UploadTask(31169): Increasing chunk size to 524288
D/UploadTask(31169): Waiting 0 milliseconds
W/StorageUtil(31169): Error getting App Check token; using placeholder token instead. Error: com.google.firebase.FirebaseException: Too many attempts.
D/UploadTask(31169): Increasing chunk size to 1048576
D/UploadTask(31169): Waiting 0 milliseconds
W/StorageUtil(31169): Error getting App Check token; using placeholder token instead. Error: com.google.firebase.FirebaseException: Too many attempts.
D/UploadTask(31169): Increasing chunk size to 2097152
D/UploadTask(31169): Waiting 0 milliseconds
W/StorageUtil(31169): Error getting App Check token; using placeholder token instead. Error: com.google.firebase.FirebaseException: Too many attempts.
**I/flutter (31169): [firebase_storage/channel-error] Unable to establish connection on channel.
[log] [firebase_storage/channel-error] Unable to establish connection on channel.**
```

```
Code : 
class StorageMethods{

  final FirebaseAuth _auth = FirebaseAuth.instance;
  final FirebaseStorage _storage = FirebaseStorage.instance;

  Future<String> uploadImageToStorage(String childName, Uint8List file, bool isPost) async {
    Reference ref = _storage.ref().child(childName).child(_auth.currentUser!.uid);
    UploadTask uploadTask = ref.putData(file);
    TaskSnapshot snap = await uploadTask;
    String downloadUrl = await snap.ref.getDownloadURL();
    log(downloadUrl);
    return downloadUrl;
  }

}
```

I am uploading image on firebase storage and then retriving the download link (ref.getDownloadUrl), error is ocuring. It's working correctly in web only error is coming in android. 

also i have correctly initialized app,

```
WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: const FirebaseOptions(
        apiKey: "key",
        appId: "id",
        messagingSenderId: "id",
        projectId: 'id',
      storageBucket: 'bucket'
    )
  );
  await FirebaseAppCheck.instance.activate(
    webProvider: ReCaptchaV3Provider('recaptcha-v3-site-key'),
    androidProvider: AndroidProvider.debug,
    appleProvider: AppleProvider.appAttest,
  );
```

Please respond.

**Comment by darshankawar** [comment] 2023-11-03 10:24
@Sneh-Paghdal 
Looking at the crash log, it shows below entries:


```
Error getting App Check token; using placeholder token instead. Error: com.google.firebase.FirebaseException: Error returned from API. code: 403 body: App attestation failed.


Error getting App Check token; using placeholder token instead. Error: com.google.firebase.FirebaseException: Too many attempts.
```

Indicating it is coming from firebase_app_check and most probably related to your setup / config and not a bug from plugin itself. Check and confirm that you have properly setup / config'ed app check as mentioned in the [documentation](https://firebase.google.com/docs/app-check/flutter/default-providers).

Based on the logs, I'll close this as not a bug in plugin, but related to your app check config. You can also file this in support channels like StackOverflow.  If you disagree, write in comments and I'll reopen it.

**Closed by darshankawar** 2023-11-03 10:24 UTC
Labels: type: bug, Needs Attention, in triage
