### ISSUE TITLE
🐛 [firebase_storage]  [firebase_storage/unknown] An unknown error occurred, please check the server response.

### ISSUE THREAD

**Issue by sudama-221** [firebase/flutterfire#9480] opened 2022-09-06 10:40 UTC
I am Japanese. I'm a beginner, so there are some things I'm unfamiliar with.
sorry
## Bug report
**Describe the bug**
I want to upload an image to firebase cloud storage, but I couldn't because of an unknown error.
I've been struggling with this for a week.
Help me.

### Steps to reproduce

```dart
import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';

import 'dart:io';
import 'dart:convert';
import 'package:firebase_storage/firebase_storage.dart';
import 'package:image_picker/image_picker.dart';
import 'package:path_provider/path_provider.dart';

class MainPage extends StatefulWidget {
  @override
  State<MainPage> createState() => _MainPageState();
}

class _MainPageState extends State<MainPage> {
  Image? _img;
  Text? _text;

  // ダウンロード処理
  Future<void> _download() async {
    // ファイルのダウンロード
    FirebaseStorage storage = FirebaseStorage.instance;
    Reference imageRef = storage.ref().child("DL").child("flutter.png");
    String imageUrl = await imageRef.getDownloadURL();
    Reference textRef = storage.ref("DL/hello.txt");
    var data = await textRef.getData();

    // 画面に反映
    setState(() {
      _img = Image.network(imageUrl);
      _text = Text(ascii.decode(data!));
    });

    // ローカルにもファイルを書き込み
    Directory appDocDir = await getApplicationDocumentsDirectory();
    File downloadToFile = File("${appDocDir.path}/download-logo.png");
    try {
      await imageRef.writeToFile(downloadToFile);
    } catch (e) {
      print(e);
    }
  }

  // アップロード処理
  void _upload() async {
    // imagePickerで画像を選択する
    final pickerFile =
        await ImagePicker().pickImage(source: ImageSource.gallery);
    if (pickerFile == null) {
      return;
    }
    File file = File(pickerFile.path);
    FirebaseStorage storage = FirebaseStorage.instance;
    try {
      await storage.ref("UL/upload-pic2.png").putFile(file);
      setState(() {
        _text = const Text("UploadDone");
      });
    } catch (e) {
      print(e);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: Text('images'),
        ),
        body: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              if (_img != null) _img!,
              if (_text != null) _text!,
            ],
          ),
        ),
        floatingActionButton:
            Row(mainAxisAlignment: MainAxisAlignment.spaceEvenly, children: [
          FloatingActionButton(
            onPressed: _download,
            child: const Icon(Icons.download_outlined),
          ),
          FloatingActionButton(
            onPressed: _upload,
            child: const Icon(Icons.upload_outlined),
          ),
        ]));
  }
}

```

The settings are below
> pubspec.yaml
```
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  firebase_core: ^1.21.1
  cloud_firestore: ^3.4.6
  firebase_auth: ^3.7.0
  firebase_storage: ^10.3.7
  image_picker: ^0.8.5+3
  path_provider: ^2.0.11
```

> ios/podfile
```
# Uncomment this line to define a global platform for your project
platform :ios, '11.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  pod 'FirebaseFirestore', :git => 'https://github.com/invertase/firestore-ios-sdk-frameworks.git', :tag => '9.4.0'
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end

```

The rule settings for firebase cloud storage are as follows
```
rules_version = '2';
service firebase.storage {
  match /b/{bucket}/o {
    match /{allPaths=**} {
      allow read, write: if
          request.time < timestamp.date(2022, 10, 6);
    }
  }
}
```

I also tried this and got an error
```
rules_version = '2';
service firebase.storage {
  match /b/{bucket}/o {
    match /{allPaths=**} {
      allow read, write: if true;
    }
  }
}
```

#### if i try on android
I can upload images but the following is in the debug console
```
E/SurfaceSyncer( 5902): Failed to find sync for id=1
E/SurfaceSyncer( 5902): Failed to find sync for id=2
E/SurfaceSyncer( 5902): Failed to find sync for id=3
E/StorageUtil( 5902): error getting token java.util.concurrent.ExecutionException: com.google.firebase.internal.api.FirebaseNoSignedInUserException: Please sign in before trying to get a token.
W/StorageUtil( 5902): Error getting App Check token; using placeholder token instead. Error: com.google.firebase.FirebaseException: No AppCheckProvider installed.
W/NetworkRequest( 5902): no auth token for request
```

#### In the case of ios simulator it is not possible due to an error
```
 [firebase_storage/unknown] An unknown error occurred, please check the server response.
```

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.0, on macOS 12.5 21G72 darwin-x64, locale ja-JP)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.70.2)
[✓] Connected device (4 available)
[✓] HTTP Host Availability

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.18.0
Flutter SDK 3.3.0
flutter_application_3 1.0.0+1

dependencies:
- cloud_firestore 3.4.6 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_interface flutter meta]
- cupertino_icons 1.0.5
- firebase_app_check 0.0.7 [firebase_app_check_platform_interface firebase_app_check_web firebase_core firebase_core_platform_interface flutter]
- firebase_auth 3.7.0 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 1.21.1 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_storage 10.3.7 [firebase_core firebase_core_platform_interface firebase_storage_platform_interface firebase_storage_web flutter]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- image_picker 0.8.5+3 [flutter image_picker_android image_picker_for_web image_picker_ios image_picker_platform_interface]
- path_provider 2.0.11 [flutter path_provider_android path_provider_ios path_provider_linux path_provider_macos path_provider_platform_interface path_provider_windows]

dev dependencies:
- flutter_lints 2.0.1 [lints]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters collection matcher material_color_utilities meta source_span stream_channel string_scanner term_glyph]

transitive dependencies:
- async 2.9.0 [collection meta]
- boolean_selector 2.1.0 [source_span string_scanner]
- characters 1.2.1
- clock 1.1.1
- cloud_firestore_platform_interface 5.7.3 [collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 2.8.6 [cloud_firestore_platform_interface collection firebase_core firebase_core_web flutter flutter_web_plugins js]
- collection 1.16.0
- cross_file 0.3.3+1 [js meta]
- fake_async 1.3.1 [clock collection]
- ffi 2.0.1
- file 6.1.4 [meta path]
- firebase_app_check_platform_interface 0.0.4+15 [firebase_core flutter meta plugin_platform_interface]
- firebase_app_check_web 0.0.6+4 [firebase_app_check_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- firebase_auth_platform_interface 6.6.0 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 4.3.0 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core_platform_interface 4.5.1 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 1.7.2 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_storage_platform_interface 4.1.15 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_storage_web 3.3.5 [async firebase_core firebase_core_web firebase_storage_platform_interface flutter flutter_web_plugins http js meta]
- flutter_plugin_android_lifecycle 2.0.7 [flutter]
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta vector_math]
- http 0.13.5 [async http_parser meta path]
- http_parser 4.0.1 [collection source_span string_scanner typed_data]
- image_picker_android 0.8.5+2 [flutter flutter_plugin_android_lifecycle image_picker_platform_interface]
- image_picker_for_web 2.1.8 [flutter flutter_web_plugins image_picker_platform_interface]
- image_picker_ios 0.8.6 [flutter image_picker_platform_interface]
- image_picker_platform_interface 2.6.1 [cross_file flutter http plugin_platform_interface]
- intl 0.17.0 [clock path]
- js 0.6.4
- lints 2.0.0
- matcher 0.12.12 [stack_trace]
- material_color_utilities 0.1.5
- meta 1.8.0
- path 1.8.2
- path_provider_android 2.0.20 [flutter path_provider_platform_interface]
- path_provider_ios 2.0.11 [flutter path_provider_platform_interface]
- path_provider_linux 2.1.7 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_macos 2.0.6 [flutter path_provider_platform_interface]
- path_provider_platform_interface 2.0.4 [flutter platform plugin_platform_interface]
- path_provider_windows 2.1.3 [ffi flutter path path_provider_platform_interface win32]
- platform 3.1.0
- plugin_platform_interface 2.1.2 [meta]
- process 4.2.4 [file path platform]
- sky_engine 0.0.99
- source_span 1.9.0 [collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.1 [source_span]
- term_glyph 1.2.1
- test_api 0.4.12 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.1 [collection]
- vector_math 2.1.2
- win32 3.0.0 [ffi]
- xdg_directories 0.2.0+2 [meta path process]
```

</details>

---

**Comment by darshankawar** [comment] 2022-09-06 11:59
Thanks for the report @sudama-221 
From the error log, it seems atleast on Android side, the error is meaningful and is throwing:

```
E/StorageUtil( 5902): error getting token java.util.concurrent.ExecutionException: com.google.firebase.internal.api.FirebaseNoSignedInUserException: Please sign in before trying to get a token.
W/StorageUtil( 5902): Error getting App Check token; using placeholder token instead. Error: com.google.firebase.FirebaseException: No AppCheckProvider installed.
W/NetworkRequest( 5902): no auth token for request
```

But on iOS:

It throws a general unknown error: `[firebase_storage/unknown] An unknown error occurred, please check the server response.`

But it does indicate that it might be related to server's response while trying to fetch the data through dart, but somehow the server isn't able to provide the data.

Do you have fast internet connection / service provider ? Can you also perhaps try on a different fast network or with a different service provider and see if you still get same error or not ?

**Comment by sudama-221** [comment] 2022-09-07 02:46
Thank you for your answer

When I logged in with firebase auth on Android, I got the following error
```
W/StorageUtil(12776): Error getting App Check token; using placeholder token instead. Error: com.google.firebase.FirebaseException: No AppCheckProvider installed.
D/TrafficStats(12776): tagSocket(119) with statsTag=0xffffffff, statsUid=-1
W/StorageUtil(12776): Error getting App Check token; using placeholder token instead. Error: com.google.firebase.FirebaseException: No AppCheckProvider installed.
```
On iOS I get the same error even if I log in

Do you need AppCheck?

The connection environment is using Wi-Fi

I tried it with a new program, but it didn't work.
I'm trying the iOS simulator on iphone 13 pro, is it related?

**Comment by sudama-221** [comment] 2022-09-07 06:28
I got this error when I tried the example of the library called firebase_storage.
[https://pub.dev/packages/firebase_storage](https://pub.dev/packages/firebase_storage)
```
WARNING: Unable to set the Firebase Storage emulator settings. These must be set before any usages of Firebase Storage. If you see this log after a hot reload/restart you can safely ignore it.
flutter: [firebase_storage/unknown] An unknown error occurred, please check the server response.
```
There are other people also struggling with the same error.
[https://www.reddit.com/r/flutterhelp/comments/wty1z2/firebase_storage_emulator_doesnt_work_with_ios/](https://www.reddit.com/r/flutterhelp/comments/wty1z2/firebase_storage_emulator_doesnt_work_with_ios/)
[https://stackoverflow.com/questions/73434335/storage-emulator-issue-unhandled-exception-firebase-storage-unknown-an-unkno](https://stackoverflow.com/questions/73434335/storage-emulator-issue-unhandled-exception-firebase-storage-unknown-an-unkno)

Please give me a solution!

**Comment by darshankawar** [comment] 2022-09-07 08:27
> W/StorageUtil(12776): Error getting App Check token; using placeholder token instead. Error: com.google.firebase.FirebaseException: No AppCheckProvider installed.

For this, try [this](https://stackoverflow.com/a/72900234) solution and see if it helps.



> WARNING: Unable to set the Firebase Storage emulator settings. These must be set before any usages of Firebase Storage. If you see this log after a hot reload/restart you can safely ignore it.
> flutter: [firebase_storage/unknown] An unknown error occurred, please check the server response.

This could be related to firebase tools and not with client (flutterfire). Can you confirm what version of firebase tools are you using. Make sure they are on latest versions. 

> I got this error when I tried the example of the library called firebase_storage.

We aren't doing anything with storage emulators and the warning / error seems to be coming from firebase tools as I mentioned earlier and you should reach out to them for further resolution. https://github.com/firebase/firebase-tools/issues

**Comment by sudama-221** [comment] 2022-09-07 08:34
Thank you for your answer.

After trying various things by myself, I succeeded with [putData]

I'll post the code for anyone else wondering.
```
final ImagePicker picker = ImagePicker();
    final XFile? image = await picker.pickImage(source: ImageSource.gallery);
    imgFile = File(image!.path);
final metadata = SettableMetadata(
        contentType: 'image/jpeg',
        // contentType: 'image/png',
        customMetadata: {'picked-file-path': imgFile.path},
      );
      UploadTask uploadTask;
      Reference ref =
          FirebaseStorage.instance.ref().child('books').child('/hogehoge.jpg');

      try {
        uploadTask = ref.putData(await imgFile.readAsBytes(), metadata);
        imgUrl = await (await uploadTask).ref.getDownloadURL();
      } catch (e) {
        print(e.toString());
      }
```

I didn't need AppCheck.
Thank you very much for taking the consultation.
Answer helped me.

**Comment by darshankawar** [comment] 2022-09-07 09:38
Good to know the issue is resolved. Closing.

**Closed by darshankawar** 2022-09-07 09:38 UTC
Labels: type: bug, Needs Attention, in triage
