### ISSUE TITLE
🐛 [firebase_storage] StorageUtil: Error getting App Check token

### ISSUE THREAD

**Issue by Tom3652** [firebase/flutterfire#10830] opened 2023-04-23 09:55 UTC
## Bug report

**Describe the bug**

`firebase_storage` seems to not be able to fetch the App check token on Android when the method : `FirebaseAppCheck.instance.getToken()` Is actually returning a correct / valid app check token. 

Here is the full trace reproductible with the debug token : 

```
Performing hot restart...
Syncing files to device moto g 8 power...
Restarted application in 6 333ms.
[log] Token : eyJlcnJvciI6IlVOS05PV05fRVJST1IifQ==
W/StorageUtil(21457): no auth token for request
W/StorageUtil(21457): Error getting App Check token; using placeholder token instead. Error: com.google.firebase.FirebaseException: Too many attempts.
W/NetworkRequest(21457): no auth token for request
D/UploadTask(21457): Waiting 0 milliseconds
W/StorageUtil(21457): no auth token for request
W/StorageUtil(21457): Error getting App Check token; using placeholder token instead. Error: com.google.firebase.FirebaseException: Too many attempts.
W/NetworkRequest(21457): no auth token for request
D/UploadTask(21457): Increasing chunk size to 524288
D/UploadTask(21457): Waiting 0 milliseconds
I/flutter (21457): Progress for task : 1 : 3.384109258561676 %
W/StorageUtil(21457): no auth token for request
W/StorageUtil(21457): Error getting App Check token; using placeholder token instead. Error: com.google.firebase.FirebaseException: Too many attempts.
W/NetworkRequest(21457): no auth token for request
D/UploadTask(21457): Increasing chunk size to 1048576
D/UploadTask(21457): Waiting 0 milliseconds
I/flutter (21457): Progress for task : 1 : 10.152327775685029 %
W/StorageUtil(21457): no auth token for request
W/StorageUtil(21457): Error getting App Check token; using placeholder token instead. Error: com.google.firebase.FirebaseException: Too many attempts.
W/NetworkRequest(21457): no auth token for request
```

And with `AndroidProvider.playIntegrity` : 

```
Launching lib/main.dart on moto g 8 power in debug mode...
Running Gradle task 'assembleDebug'...
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
Installing build/app/outputs/flutter-apk/app-debug.apk...
Debug service listening on ws://127.0.0.1:58176/awM8efaMP2Q=/ws
Syncing files to device moto g 8 power...
I/PlayCore(25263): UID: [10271]  PID: [25263] IntegrityService : requestIntegrityToken(IntegrityTokenRequest{nonce=ARDLlMQPwgeDsHkyVmn2bLJc28e-gAWnFx9She0xrNBIkjD8zLINgUGtPuCiE_V0zjIDi8RaWyGKqfDLraeCI0HOHQu9TrnBZmI87NgCYTbVUeyvlNDin4-3nExKt8EOP-VOL8Nt45pS_z48EABS7sEGEZU4lCdQc5EbtbR7Fdrys5s=, cloudProjectNumber=499879109367})
I/PlayCore(25263): UID: [10271]  PID: [25263] IntegrityService : Initiate binding to the service.
I/PlayCore(25263): UID: [10271]  PID: [25263] IntegrityService : ServiceConnectionImpl.onServiceConnected(ComponentInfo{com.android.vending/com.google.android.finsky.integrityservice.IntegrityService})
I/PlayCore(25263): UID: [10271]  PID: [25263] IntegrityService : linkToDeath
I/PlayCore(25263): UID: [10271]  PID: [25263] OnRequestIntegrityTokenCallback : onRequestIntegrityToken
I/PlayCore(25263): UID: [10271]  PID: [25263] IntegrityService : Unbind from service.
[log] Token : eyJlcnJvciI6IlVOS05PV05fRVJST1IifQ==
W/StorageUtil(25263): no auth token for request
W/StorageUtil(25263): Error getting App Check token; using placeholder token instead. Error: com.google.firebase.FirebaseException: Too many attempts.
I/TetheringManager(25263): registerTetheringEventCallback:com.fbstoragetest.firebasestoragetest
W/NetworkRequest(25263): no auth token for request
I/flutter (25263): Progress for task : 1 : 0.0 %
I/flutter (25263): Progress for task : 1 : 0.0 %
D/UploadTask(25263): Waiting 0 milliseconds
W/StorageUtil(25263): no auth token for request
W/StorageUtil(25263): Error getting App Check token; using placeholder token instead. Error: com.google.firebase.FirebaseException: Too many attempts.
W/NetworkRequest(25263): no auth token for request
D/UploadTask(25263): Increasing chunk size to 524288
D/UploadTask(25263): Waiting 0 milliseconds
I/flutter (25263): Progress for task : 1 : 3.384109258561676 %
W/StorageUtil(25263): no auth token for request
W/StorageUtil(25263): Error getting App Check token; using placeholder token instead. Error: com.google.firebase.FirebaseException: Too many attempts.
W/NetworkRequest(25263): no auth token for request
D/UploadTask(25263): Increasing chunk size to 1048576
D/UploadTask(25263): Waiting 0 milliseconds
I/flutter (25263): Progress for task : 1 : 10.152327775685029 %
W/StorageUtil(25263): no auth token for request
W/StorageUtil(25263): Error getting App Check token; using placeholder token instead. Error: com.google.firebase.FirebaseException: Too many attempts.
W/NetworkRequest(25263): no auth token for request
```

### Steps to reproduce

1. Add Firebase storage and App Check to your project
2. Register your android app with a debug token and Play Integrity
3. You can just run `  FirebaseAppCheck.instance.activate(androidProvider: AndroidProvider.playIntegrity);` the second time to see the same issue with Play Integrity
4. Make a request to firebase storage and see the stack trace 

### Expected behavior

Firebase Storage should make the appropriate requests for App Check regarding quotas or limits to avoid such errors, especially when `FirebaseAppCheck.instance.getToken()` is working fine at the same time.

### Sample project

```
import 'dart:async';
import 'dart:io';

import 'package:firebase_app_check/firebase_app_check.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_storage/firebase_storage.dart';
import 'package:firebasestoragetest/firebase_options.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  FirebaseAppCheck.instance.activate(
    androidProvider: kDebugMode ? AndroidProvider.debug : AndroidProvider.playIntegrity
  );
  runApp(const TestApp());
}

class TestApp extends StatefulWidget {
  const TestApp({Key? key}) : super(key: key);

  @override
  _TestAppState createState() => _TestAppState();
}

class _TestAppState extends State<TestApp> {
  final List<UploadTask> task = [];

  Future<void> init() async {
    String token = await FirebaseAppCheck.instance.getToken() ?? "";
    log("Token : $token");
  }

  @override
  void initState() {
    init();
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Stack(
          children: [
            ListView.builder(
              cacheExtent: 30000,
              itemBuilder: (ctx, index) {
                return ShowUploadWidget(task: task[index], count: task.length);
              },
              itemCount: task.length,
            ),
            if (task.length <= 20)
              Center(
                child: GestureDetector(
                  onTap: () async {
                    XFile? picked = await ImagePicker().pickVideo(source: ImageSource.gallery);
                    if (picked != null) {

                        UploadTask main = FirebaseStorage.instance
                            .ref()
                            .child("test")
                            .putFile(File(picked.path));
                        main.catchError((error) {

                        });
                        task.add(main);
                      setState(() {});
                    }
                  },
                  child: Container(
                    width: 200,
                    height: 200,
                    color: Colors.blue,
                    child: const Center(child: Text("Pick video")),
                  ),
                ),
              ),
          ],
        ),
      ),
    );
  }
}

class ShowUploadWidget extends StatefulWidget {
  const ShowUploadWidget({Key? key, required this.task, required this.count})
      : super(key: key);

  final UploadTask task;
  final int count;

  @override
  State<ShowUploadWidget> createState() => _ShowUploadWidgetState();
}

class _ShowUploadWidgetState extends State<ShowUploadWidget> {
  double progress = 0;
  late StreamSubscription subscription;

  String? error;

  void initListener() {
    subscription = widget.task.snapshotEvents.listen((event) {
      setState(() {
        progress = event.bytesTransferred / event.totalBytes * 100;
        print("Progress for task : ${widget.count} : $progress %");
      });
    });
    widget.task.catchError((e) {
      if (mounted) {
        setState(() {
          print('e : $e');
          error = e.toString();
        });
      }
    });
  }

  @override
  void dispose() {
    subscription.cancel();
    super.dispose();
  }

  @override
  void initState() {
    initListener();
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Center(
      child: error != null ? Text("Error : $error") : Text("Uploading : $progress"),
    );
  }
}
```
---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.12, on macOS 13.3.1 22E261 darwin-x64, locale fr-FR)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.77.3)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.19.6
Flutter SDK 3.7.12
firebasestoragetest 1.0.0+1

dependencies:
- firebase_app_check 0.1.2+2 [firebase_app_check_platform_interface firebase_app_check_web firebase_core firebase_core_platform_interface flutter]
- firebase_core 2.10.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_storage 11.1.1 [firebase_core firebase_core_platform_interface firebase_storage_platform_interface firebase_storage_web flutter]
- flutter 0.0.0 [characters collection js material_color_utilities meta vector_math sky_engine]
- image_picker 0.8.7+4 [flutter image_picker_android image_picker_for_web image_picker_ios image_picker_platform_interface]

dev dependencies:
- flutter_lints 1.0.4 [lints]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters collection js matcher material_color_utilities meta source_span stream_channel string_scanner term_glyph]

transitive dependencies:
- _flutterfire_internals 1.1.1 [collection firebase_core firebase_core_platform_interface flutter meta]
- async 2.10.0 [collection meta]
- boolean_selector 2.1.1 [source_span string_scanner]
- characters 1.2.1
- clock 1.1.1
- collection 1.17.0
- cross_file 0.3.3+4 [js meta]
- fake_async 1.3.1 [clock collection]
- firebase_app_check_platform_interface 0.0.6+1 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_app_check_web 0.0.8+1 [_flutterfire_internals firebase_app_check_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- firebase_core_platform_interface 4.6.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.3.0 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_storage_platform_interface 4.2.1 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_storage_web 3.4.1 [_flutterfire_internals async firebase_core firebase_core_web firebase_storage_platform_interface flutter flutter_web_plugins http js meta]
- flutter_plugin_android_lifecycle 2.0.9 [flutter]
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta vector_math]
- http 0.13.5 [async http_parser meta path]
- http_parser 4.0.2 [collection source_span string_scanner typed_data]
- image_picker_android 0.8.6+7 [flutter flutter_plugin_android_lifecycle image_picker_platform_interface]
- image_picker_for_web 2.1.12 [flutter flutter_web_plugins image_picker_platform_interface]
- image_picker_ios 0.8.7+3 [flutter image_picker_platform_interface]
- image_picker_platform_interface 2.6.3 [cross_file flutter http plugin_platform_interface]
- js 0.6.5 [meta]
- lints 1.0.1
- matcher 0.12.13 [meta stack_trace]
- material_color_utilities 0.2.0
- meta 1.8.0
- path 1.8.2
- plugin_platform_interface 2.1.4 [meta]
- sky_engine 0.0.99
- source_span 1.9.1 [collection path term_glyph]
- stack_trace 1.11.0 [path]
- stream_channel 2.1.1 [async]
- string_scanner 1.2.0 [source_span]
- term_glyph 1.2.1
- test_api 0.4.16 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.1 [collection]
- vector_math 2.1.4
```

</details>

---

**Comment by darshankawar** [comment] 2023-04-24 11:39
Thanks for the report @Tom3652 

Looking at the logs, it is showing `W/NetworkRequest(21457): no auth token for request`, for which I am wondering if this is occuring due to outage in firebase auth https://status.firebase.google.com/incidents/UY1LTFan8X5oybhphzfV related to play integrity.

If by any chance, by the time the outage is restored, the dashboard showed this:

<img width="939" alt="Screenshot 2023-04-24 at 5 07 40 PM" src="https://user-images.githubusercontent.com/67046386/233985538-5162b709-e17b-4b45-ad53-d3d9e9910590.png">

After this is restored, please run your scenario again to see if you still get the same error or not.

**Comment by Tom3652** [comment] 2023-04-24 13:56
Alright it's also the same with `firebase_database` : 

```
W/FirebaseContextProvider( 3863): Error getting App Check token. Error: com.google.firebase.FirebaseException: Error returned from API. code: 403 body: App attestation failed.
```

I am pretty sure this is linked, i will make the test on my test project.

**Comment by Tom3652** [comment] 2023-04-25 10:37
Hi @darshankawar, i have deleted the comment because i was unable to reproduce with `firebase_database` and i am also not sure that `FirebaseContextProvider` is a class of `firebase_database`. 
I have simply not checked but i am not sure that this is linked anymore... But you are right we can keep the log here.

I see that the firebase status incident you mentioned is still ongoing, so i will update here after it's resolve and re test.

**Comment by Tom3652** [comment] 2023-05-02 10:54
Hi @darshankawar, the incident seems to be resolved but i am still seeing the same error, reproductible 100% :/

**Comment by darshankawar** [comment] 2023-05-04 09:45
Thanks for the update. Keeping this issue open for team's input and attention.

**Comment by aliKashoa-cs** [comment] 2024-01-02 20:51
is there i fix i have the same problem

**Comment by russellwheatley** [comment] 2024-01-04 10:03
Hi @Tom3652 - I setup play integrity on a test Flutter app and I did not reproduce this exception. My sense is possibly a configuration problem. It's been quite a while since you raised this issue so I wanted to know whether you were able to resolve it?

**Comment by Tom3652** [comment] 2024-01-04 10:49
Hey @russellwheatley, i have just tested it in my app right now after upgrading all the plugins to the latest version and i am seeing the same log :/ 
It's weird because i am pretty sure i have setup play integrity correctly since i am seeing requests in the GCP console as i have mentioned in my other issue #11629

Note : this happens with both ` kDebugMode ? AndroidProvider.debug : AndroidProvider.playIntegrity`  so with both the debug config or Play Integrity.

In the same app i have 2 behaviors : 

- HTTP Cloud Functions : When i send my app check token to my cloud function and validate it there in python, it's working fine the tokens are almost all valid at 99%. 

- Firebase Storage : i have not the hand on how the app check token is sent / retrieved and i am seeing this log `W/StorageUtil(25263): Error getting App Check token; using placeholder token instead. Error: com.google.firebase.FirebaseException: Too many attempts.` with a `Too many attempts` even if it's the first and only request made. 

Note : if i run the sample code i have provided i am getting the same log, what else can i do to confirm / refute that i have a correct Play Integrity / App check debug setup ?

**Comment by russellwheatley** [comment] 2024-01-04 11:14
@Tom3652 - are your requests being verified? 

Although this log doesn't look great:
```
W/StorageUtil(25263): Error getting App Check token; using placeholder token instead. Error: com.google.firebase.FirebaseException: Too many attempts.
```

It is actually a warning log, not an error.

**Comment by Tom3652** [comment] 2024-01-04 14:12
> @Tom3652 - are your requests being verified?

Yes they are at 99% in the Cloud Functions because sometimes i have a token expired error but it's very rare honestly. 
It must be a race condition between the moment it's fetched on the device and it expires the time it reaches the server 😅

For the other requests than Cloud Functions i don't really know but here is the GCP screenshot for the past hours :
 
![Capture d’écran 2024-01-04 à 15 10 01](https://github.com/firebase/flutterfire/assets/32631467/a68b5d1d-664c-43ca-89bd-9fbdfe1d1b8e)

Play integrity has 12.7% errors

**Comment by russellwheatley** [comment] 2024-01-04 15:06
Thanks for reporting. As mentioned, I don't think you should worry about a warning log particularly if your requests are being verified. If, however, you think it shouldn't be logged, you could open an issue on the firebase-android-sdk where it is produced. I'm going to close this issue as there is nothing actionable from FlutterFire 👍

**Closed by russellwheatley** 2024-01-04 15:06 UTC
Labels: type: bug, plugin: storage, Needs Attention, plugin: app_check

**Comment by quanshuli** [comment] 2024-01-18 00:02
i think this might still be a bug. the `listAll()` or `list()` method for firebase cloud storage is returning empty list for me and there is no other information except this one. but haven't found a method to fix it.
