### ISSUE TITLE
Firebase_crashlytics: The crash stacktrace is not deobfuscated

### ISSUE THREAD

**Issue by 4ntoine** [firebase/flutterfire#8964] opened 2022-06-25 09:23 UTC
## Bug report

The crash stacktrace is not deobfuscated.

### Steps to reproduce

1. Go to firebase console
2. See the stacktrace as follows:
```
Fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: Bad state: Cannot add event after closing. Error thrown null.
       at _StreamController.add(_StreamController.java:595)
       at _Rb.add(_Rb.java:867)
       at ._Zj(.java:1434)
       at _Fc.runUnary(_Fc.java:1335)
       at _Fc.fRa(_Fc.java:1244)
       at _BufferingStreamSubscription._ieb(_BufferingStreamSubscription.java:341)
       at _BufferingStreamSubscription._add(_BufferingStreamSubscription.java:271)
       at _hc._add(_hc.java:123)
       at _kc._Veb(_kc.java:253)
       at _hc._Veb(_hc.java:153)
       at ._Zj(.java:1434)
       at _Fc.runUnary(_Fc.java:1335)
       at _Fc.fRa(_Fc.java:1244)
       at _BufferingStreamSubscription._ieb(_BufferingStreamSubscription.java:341)
       at _BufferingStreamSubscription._add(_BufferingStreamSubscription.java:271)
       at _hc._add(_hc.java:123)
       at _jc._Veb(_jc.java:218)
       at _hc._Veb(_hc.java:153)
       at ._Zj(.java:1434)
       at _Fc.runUnary(_Fc.java:1335)
       at _Fc.fRa(_Fc.java:1244)
       at _BufferingStreamSubscription._ieb(_BufferingStreamSubscription.java:341)
       at _BufferingStreamSubscription._add(_BufferingStreamSubscription.java:271)
       at _hc._add(_hc.java:123)
       at _jc._Veb(_jc.java:218)
       at _hc._Veb(_hc.java:153)
       at ._Zj(.java:1434)
       at _Fc.runUnary(_Fc.java:1335)
       at _Fc.fRa(_Fc.java:1244)
       at _BufferingStreamSubscription._ieb(_BufferingStreamSubscription.java:341)
       at _Yb.zdb(_Yb.java:591)
       at _bc.pdb(_bc.java:706)
       at _Wb.tdb.<fn>(tdb.java:663)
       at ._Wj(.java:1418)
       at _Fc.oRa(_Fc.java:1328)
       at _Fc.eRa(_Fc.java:1236)
       at _Fc.jRa.<fn>(jRa.java:1276)
       at ._Wj(.java:1426)
       at _Fc.oRa(_Fc.java:1328)
       at _Fc.eRa(_Fc.java:1236)
       at _Fc.jRa.<fn>(jRa.java:1276)
       at ._yj(.java:40)
       at ._zj(.java:49)
```

### Expected behavior

Dart code stacktrae with proper class names, methods and lines.

### Sample project

Providing a minimal example project which demonstrates the bug in isolation from your main App _greatly_ enhances the chance of a timely fix.
Please link to the public repository URL.

---

## Additional context

package-lock.json:
```
..
firebase_crashlytics:
    dependency: "direct main"
    description:
      name: firebase_crashlytics
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.8.2"
  firebase_crashlytics_platform_interface:
    dependency: transitive
    description:
      name: firebase_crashlytics_platform_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.2.8"
..
```
---

### Flutter doctor

<details>

```
> flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 3.1.0-0.0.pre.1354, on macOS 11.6 20G165 darwin-x64, locale ru-RU)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[!] Xcode - develop for iOS and macOS (Xcode 13.0)
    ! CocoaPods 1.10.2 out of date (1.11.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.6)
[✓] Android Studio (version 2021.1)
[✓] Android Studio (version 3.1)
[✓] Android Studio (version 4.2)
[✓] IntelliJ IDEA Community Edition (version 2021.2.4)
[✓] IntelliJ IDEA Community Edition (version 2019.1)
[✓] IntelliJ IDEA Community Edition (version 2019.3.1)
[✓] VS Code (version 1.68.1)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

! Doctor found issues in 1 category.
```
</details>

---

### Flutter dependencies

<details>

```
> flutter pub deps -- --style=compact
Dart SDK 2.18.0-216.0.dev
Flutter SDK 3.1.0-0.0.pre.1354
arduino_studio 1.4.0+74

dependencies:
- arduino_cli_dart 0.0.1 [flutter grpc protobuf]
- arduino_studio_mvp 0.1.0 [flutter io]
- clipboard 0.1.3 [flutter]
- code_text_field 1.0.2 [flutter linked_scroll_controller highlight flutter_highlight]
- cupertino_icons 1.0.5
- firebase_analytics 9.1.10 [firebase_analytics_platform_interface firebase_analytics_web firebase_core firebase_core_platform_interface flutter]
- firebase_core 1.18.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_crashlytics 2.8.2 [firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface flutter stack_trace]
- firebase_remote_config 2.0.9 [firebase_core firebase_core_platform_interface firebase_remote_config_platform_interface firebase_remote_config_web flutter]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- flutter_html 2.2.1 [html csslib flutter_layout_grid video_player chewie webview_flutter chewie_audio flutter_svg flutter_math_fork collection numerus flutter]
- google_mobile_ads 1.3.0 [meta flutter]
- in_app_purchase 3.0.6 [flutter in_app_purchase_android in_app_purchase_platform_interface in_app_purchase_storekit]
- introduction_screen 3.0.2 [flutter dots_indicator collection]
- io 1.0.3 [meta path string_scanner]
- package_info_plus 1.4.2 [flutter package_info_plus_platform_interface package_info_plus_linux package_info_plus_macos package_info_plus_windows package_info_plus_web]
- provider 6.0.3 [collection flutter nested]
- shared_preferences 2.0.15 [flutter shared_preferences_android shared_preferences_ios shared_preferences_linux shared_preferences_macos shared_preferences_platform_interface shared_preferences_web shared_preferences_windows]
- url_launcher 6.1.3 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- usb_serial 0.4.0 [flutter async collection]
- uuid 3.0.6 [crypto]

dev dependencies:
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters collection matcher material_color_utilities meta source_span stream_channel string_scanner term_glyph]

transitive dependencies:
- archive 3.3.0 [crypto path]
- async 2.9.0 [collection meta]
- boolean_selector 2.1.0 [source_span string_scanner]
- characters 1.2.1
- chewie 1.3.4 [cupertino_icons flutter provider video_player wakelock]
- chewie_audio 1.3.0 [cupertino_icons flutter video_player]
- clock 1.1.1
- collection 1.16.0
- crypto 3.0.2 [typed_data]
- csslib 0.17.2 [source_span]
- dots_indicator 2.1.0 [flutter]
- fake_async 1.3.1 [clock collection]
- ffi 1.2.1
- file 6.1.2 [meta path]
- firebase_analytics_platform_interface 3.1.8 [firebase_core flutter meta plugin_platform_interface]
- firebase_analytics_web 0.4.0+15 [firebase_analytics_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- firebase_core_platform_interface 4.4.1 [collection flutter meta plugin_platform_interface]
- firebase_core_web 1.6.5 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_crashlytics_platform_interface 3.2.8 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_remote_config_platform_interface 1.1.8 [firebase_core flutter meta plugin_platform_interface]
- firebase_remote_config_web 1.0.14 [firebase_core firebase_core_web firebase_remote_config_platform_interface flutter flutter_web_plugins js]
- fixnum 1.0.1
- flutter_highlight 0.7.0 [flutter highlight]
- flutter_layout_grid 1.0.6 [flutter collection meta quiver]
- flutter_math_fork 0.5.0 [flutter flutter_svg provider meta collection tuple]
- flutter_svg 0.23.0+1 [flutter meta path_drawing vector_math xml]
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta vector_math]
- googleapis_auth 1.3.1 [crypto http http_parser]
- grpc 3.0.2 [archive async crypto fixnum googleapis_auth meta http http2 protobuf]
- highlight 0.7.0 [collection]
- html 0.15.0 [csslib source_span]
- http 0.13.4 [async http_parser meta path]
- http2 2.0.0
- http_parser 4.0.1 [collection source_span string_scanner typed_data]
- in_app_purchase_android 0.2.2+8 [collection flutter in_app_purchase_platform_interface json_annotation]
- in_app_purchase_platform_interface 1.3.1 [flutter plugin_platform_interface]
- in_app_purchase_storekit 0.3.0+10 [collection flutter in_app_purchase_platform_interface json_annotation]
- js 0.6.4
- json_annotation 4.5.0 [meta]
- linked_scroll_controller 0.2.0 [flutter]
- matcher 0.12.11 [stack_trace]
- material_color_utilities 0.1.5
- meta 1.8.0
- nested 1.0.0 [flutter]
- numerus 1.1.1
- package_info_plus_linux 1.0.5 [package_info_plus_platform_interface flutter path]
- package_info_plus_macos 1.3.0 [flutter]
- package_info_plus_platform_interface 1.0.2 [flutter meta plugin_platform_interface]
- package_info_plus_web 1.0.5 [flutter flutter_web_plugins http meta package_info_plus_platform_interface]
- package_info_plus_windows 1.0.5 [package_info_plus_platform_interface ffi flutter win32]
- path 1.8.2
- path_drawing 0.5.1+1 [vector_math meta path_parsing flutter]
- path_parsing 0.2.1 [vector_math meta]
- path_provider_linux 2.1.7 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_platform_interface 2.0.4 [flutter platform plugin_platform_interface]
- path_provider_windows 2.0.7 [ffi flutter path path_provider_platform_interface win32]
- petitparser 5.0.0 [meta]
- platform 3.1.0
- plugin_platform_interface 2.1.2 [meta]
- process 4.2.4 [file path platform]
- protobuf 2.1.0 [fixnum collection meta]
- quiver 3.1.0 [matcher]
- shared_preferences_android 2.0.12 [flutter shared_preferences_platform_interface]
- shared_preferences_ios 2.1.1 [flutter shared_preferences_platform_interface]
- shared_preferences_linux 2.1.1 [file flutter path path_provider_linux path_provider_platform_interface shared_preferences_platform_interface]
- shared_preferences_macos 2.0.4 [flutter shared_preferences_platform_interface]
- shared_preferences_platform_interface 2.0.0 [flutter]
- shared_preferences_web 2.0.4 [flutter flutter_web_plugins shared_preferences_platform_interface]
- shared_preferences_windows 2.1.1 [file flutter path path_provider_platform_interface path_provider_windows shared_preferences_platform_interface]
- sky_engine 0.0.99
- source_span 1.9.0 [collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.1 [source_span]
- term_glyph 1.2.1
- test_api 0.4.9 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- tuple 2.0.0 [quiver]
- typed_data 1.3.1 [collection]
- url_launcher_android 6.0.17 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.0.17 [flutter url_launcher_platform_interface]
- url_launcher_linux 3.0.1 [flutter url_launcher_platform_interface]
- url_launcher_macos 3.0.1 [flutter url_launcher_platform_interface]
- url_launcher_platform_interface 2.1.0 [flutter plugin_platform_interface]
- url_launcher_web 2.0.12 [flutter flutter_web_plugins url_launcher_platform_interface]
- url_launcher_windows 3.0.1 [flutter url_launcher_platform_interface]
- vector_math 2.1.2
- video_player 2.4.5 [flutter html video_player_android video_player_avfoundation video_player_platform_interface video_player_web]
- video_player_android 2.3.6 [flutter video_player_platform_interface]
- video_player_avfoundation 2.3.5 [flutter video_player_platform_interface]
- video_player_platform_interface 5.1.3 [flutter plugin_platform_interface]
- video_player_web 2.0.10 [flutter flutter_web_plugins video_player_platform_interface]
- wakelock 0.6.1+2 [flutter meta wakelock_macos wakelock_platform_interface wakelock_web wakelock_windows]
- wakelock_macos 0.4.0 [flutter flutter_web_plugins wakelock_platform_interface]
- wakelock_platform_interface 0.3.0 [flutter meta]
- wakelock_web 0.4.0 [flutter flutter_web_plugins js wakelock_platform_interface]
- wakelock_windows 0.2.0 [flutter wakelock_platform_interface win32]
- webview_flutter 2.8.0 [flutter webview_flutter_android webview_flutter_platform_interface webview_flutter_wkwebview]
- webview_flutter_android 2.8.14 [flutter webview_flutter_platform_interface]
- webview_flutter_platform_interface 1.9.1 [flutter meta plugin_platform_interface]
- webview_flutter_wkwebview 2.8.1 [flutter path webview_flutter_platform_interface]
- win32 2.6.1 [ffi]
- xdg_directories 0.2.0+1 [meta path process]
- xml 5.4.1 [collection meta petitparser]
```

</details>

---

**Comment by 4ntoine** [comment] 2022-06-27 14:55
@darshankawar I'm on the latest version of firebase crashlytics, so i'm not sure why the issue is marked as fixed/closed. Is there anything i can do to try? I've checked everything i could so i have no idea what's wrong

**Comment by darshankawar** [comment] 2022-06-28 07:09
Thanks for the update. Did you try as mentioned in [this](https://github.com/firebase/flutterfire/issues/2644#issuecomment-746217634) comment and see if it works or not ?

**Comment by 4ntoine** [comment] 2022-06-28 08:59
@darshankawar i've tried it. as you can see the stacktrace on the provided link and in my case are very different: in my case it seems that it's half deobfuscated, but some classes mapping are just not found. Also i don't understand why all the files in my  stack trace are .java, but they are .dart essentially.

**Comment by darshankawar** [comment] 2022-06-28 10:35
Thanks for the feedback. Keeping this issue open and labeling.

/cc @russellwheatley. For your reference: https://github.com/firebase/flutterfire/issues/8964#issuecomment-1167258554
Also, another similar issue: https://github.com/firebase/flutterfire/issues/8934

**Comment by russellwheatley** [comment] 2022-06-28 10:57
Hey @4ntoine, the `.java` file extension is the Firebase Crashlytics backend using the incorrect file extension unfortunately. Have you also followed this advice about [android setup](https://firebase.google.com/docs/crashlytics/get-deobfuscated-reports?platform=flutter)?

**Comment by russellwheatley** [comment] 2022-06-28 12:10
Dart code has to be manually deobfuscated at the moment. Follow this [comment](https://github.com/firebase/flutterfire/issues/2644). This is a duplicate of https://github.com/firebase/flutterfire/issues/8934, and can be tracked in that issue.

**Closed by russellwheatley** 2022-06-28 12:10 UTC
Labels: type: bug, plugin: crashlytics, platform: android

**Comment by 4ntoine** [comment] 2022-06-28 12:50
My Android setup is (almost) correct.

android/build.gradle:
```
buildscript {
    ext.kotlin_version = '1.5.31'
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:4.2.2'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.3.10'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.8.1'
    }
}
...
```

android/app/build.gradle:
```
...
apply plugin: 'com.google.gms.google-services'
apply plugin: 'com.google.firebase.crashlytics'
...
```

The only difference with the doc (link you've provided) is that my "apply" section **is not at the bottom of the file**. if i put it at the bottom i'm getting a build error:
```
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/asmirnov/Documents/dev/src/project/android/app/build.gradle' line: 51

* What went wrong:
A problem occurred evaluating project ':app'.
> No signature of method: build_44ma4qfthd5bjssmqoulji13i.android() is applicable for argument types: (build_44ma4qfthd5bjssmqoulji13i$_run_closure4) values: [build_44ma4qfthd5bjssmqoulji13i$_run_closure4@44b02e53]

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 11s
```

**Comment by 4ntoine** [comment] 2022-06-28 12:52
I don't think it's a duplicate of #8934 as there you can indeed see a binary code stack trace with addesses, all that binary stuff. In my case it feel like almost deobfuscated code.

**Comment by 4ntoine** [comment] 2022-06-28 13:26
btw i've noted my app (android part) is written in Kotlin and in the [examples](https://github.com/firebase/flutterfire/tree/master/packages/firebase_crashlytics/firebase_crashlytics/example/android) it's always Java. Is Kotlin supported?

**Comment by 4ntoine** [comment] 2022-06-29 18:44
BTW i've found i moved `apply .. crashlytics` plugin section at the **top** of the file and in the doc it's expected to be in the **bottom**. Not sure it makes a difference. See https://github.com/firebase/flutterfire/issues/8999#issuecomment-1170343368
