### ISSUE TITLE
[Firebase Auth]: [firebase_auth/unknown] An internal error has occurred. [ BILLING_NOT_ENABLED ]

### ISSUE THREAD

**Issue by choi-seung-min** [firebase/flutterfire#13272] opened 2024-09-04 09:12 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Auth

### Which platforms are affected?

Android, iOS

### Description

I've completed implementing Firebase Auth with phone verification and google, apple.
It has no problems until this error shows up.

After call ```FirebaseAuth.instance.verifyPhoneNumber``` method, ```verificationFailed``` callback is called.
FirebaseException says: '[firebase_auth/unknown] An internal error has occurred. [ BILLING_NOT_ENABLED ]'.

I've checked phone authentification sms usage (which is 0).
And I turned my GCP api key (android / ios)to no restriction.

It's not working on both ios and android.

Android log:
```
E/FirebaseAuth(25111): [SmsRetrieverHelper] SMS verification code request failed: unknown status code: 17499 BILLING_NOT_ENABLED
D/FirebaseAuth(25111): Invoking original failure callbacks after phone verification failure for +82 01040743235, error - An internal error has occurred. [ BILLING_NOT_ENABLED ]
I/flutter (25111): Verification Failed
I/flutter (25111): [firebase_auth/unknown] An internal error has occurred. [ BILLING_NOT_ENABLED ]
```

ios log:
```
flutter: Verification Failed
flutter: [firebase_auth/internal-error] An internal error has occurred, print and inspect the error details for more information.
```

But it works only when I add test phone number and verify code to firebase console.

### Reproducing the issue

    await FirebaseAuth.instance.verifyPhoneNumber(
      // maximum time out 120 seconds
      timeout: const Duration(minutes: 2),
      //+82 for korean telephone code
      phoneNumber: '+82 ${phoneNumberController.text}',
      verificationCompleted: (PhoneAuthCredential credential) {
        print('Verification Completed');
      },
      verificationFailed: (FirebaseAuthException e) {
        print('Verification Failed');
        print(e.toString());
      },
      codeSent: (String verificationId, int? resendToken) {
        print('Code Sent');
        print(verificationId);
        codeVerificationId = verificationId;
        print(resendToken.toString());
      },
      codeAutoRetrievalTimeout: (String verificationId) {
        print('Code Auto Retrieval Timeout');
        print(verificationId);
      },
    );

### Firebase Core version

3.2.0

### Flutter Version

3.22.3

### Relevant Log Output

```shell
Android log:

E/FirebaseAuth(25111): [SmsRetrieverHelper] SMS verification code request failed: unknown status code: 17499 BILLING_NOT_ENABLED
D/FirebaseAuth(25111): Invoking original failure callbacks after phone verification failure for +82 01040743235, error - An internal error has occurred. [ BILLING_NOT_ENABLED ]
I/flutter (25111): Verification Failed
I/flutter (25111): [firebase_auth/unknown] An internal error has occurred. [ BILLING_NOT_ENABLED ]
```

ios log:
```
flutter: Verification Failed
flutter: [firebase_auth/internal-error] An internal error has occurred, print and inspect the error details for more information.
```

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Dart SDK 3.4.4
Flutter SDK 3.22.3
suldak_suldak 1.0.0+1

dependencies:
- cached_network_image 3.3.1 [cached_network_image_platform_interface cached_network_image_web flutter flutter_cache_manager octo_image]
- cupertino_icons 1.0.6
- datepicker_dropdown 0.0.9 [flutter]
- dio 5.4.2+1 [async http_parser meta path]
- dots_indicator 2.1.2 [flutter]
- el_tooltip 2.0.0 [flutter]
- firebase_analytics 11.2.0 [firebase_analytics_platform_interface firebase_analytics_web firebase_core firebase_core_platform_interface flutter]
- firebase_auth 5.1.2 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 3.2.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_crashlytics 4.0.3 [firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface flutter stack_trace]
- firebase_messaging 15.0.3 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- flutter_local_notifications 17.2.2 [clock flutter flutter_local_notifications_linux flutter_local_notifications_platform_interface timezone]
- flutter_naver_login 1.9.0 [flutter]
- flutter_svg 2.0.10+1 [flutter http vector_graphics vector_graphics_codec vector_graphics_compiler]
- get 4.6.6 [flutter]
- get_storage 2.1.1 [flutter get path_provider]
- google_sign_in 6.2.1 [flutter google_sign_in_android google_sign_in_ios google_sign_in_platform_interface google_sign_in_web]
- iamport_flutter 0.10.18 [flutter iamport_webview_flutter url_launcher uni_links json_annotation]
- image_picker 1.0.8 [flutter image_picker_android image_picker_for_web image_picker_ios image_picker_linux image_picker_macos image_picker_platform_interface image_picker_windows]
- infinite_scroll_pagination 4.0.0 [flutter flutter_staggered_grid_view sliver_tools]
- intl 0.19.0 [clock meta path]
- introduction_screen 3.1.14 [flutter collection dots_indicator flutter_keyboard_visibility]
- kakao_flutter_sdk 1.9.1+2 [flutter kakao_flutter_sdk_common kakao_flutter_sdk_auth kakao_flutter_sdk_share kakao_flutter_sdk_navi kakao_flutter_sdk_talk kakao_flutter_sdk_template kakao_flutter_sdk_user kakao_flutter_sdk_friend]
- keyboard_actions 4.2.0 [flutter]
- permission_handler 11.3.1 [flutter meta permission_handler_android permission_handler_apple permission_handler_html permission_handler_windows permission_handler_platform_interface]
- sign_in_with_apple 5.0.0 [flutter meta sign_in_with_apple_platform_interface sign_in_with_apple_web]
- smooth_page_indicator 1.1.0 [flutter]
- syncfusion_flutter_datepicker 21.2.3 [flutter intl syncfusion_flutter_core]
- url_launcher 6.2.6 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]

dev dependencies:
- build_runner 2.4.9 [analyzer args async build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style frontend_server_client glob graphs http_multi_server io js logging meta mime package_config path pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web_socket_channel yaml]
- change_app_package_name 1.3.0
- flutter_gen_runner 5.4.0 [flutter_gen_core build collection crypto glob path]
- flutter_lints 2.0.3 [lints]
- flutter_test 0.0.0 [flutter test_api matcher path fake_async clock stack_trace vector_math leak_tracker_flutter_testing async boolean_selector characters collection leak_tracker leak_tracker_testing material_color_utilities meta source_span stream_channel string_scanner term_glyph vm_service]

transitive dependencies:
- _fe_analyzer_shared 64.0.0 [meta]
- _flutterfire_internals 1.3.39 [collection firebase_core firebase_core_platform_interface flutter meta]
- analyzer 6.2.0 [_fe_analyzer_shared collection convert crypto glob meta package_config path pub_semver source_span watcher yaml]
- args 2.4.2
- asn1lib 1.5.2
- async 2.11.0 [collection meta]
- boolean_selector 2.1.1 [source_span string_scanner]
- build 2.4.1 [analyzer async convert crypto glob logging meta package_config path]
- build_config 1.1.1 [checked_yaml json_annotation path pubspec_parse yaml]
- build_daemon 4.0.1 [built_collection built_value crypto http_multi_server logging path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 2.4.2 [analyzer async build collection convert crypto graphs logging package_config path pool pub_semver stream_transform yaml]
- build_runner_core 7.3.0 [async build build_config build_resolvers collection convert crypto glob graphs json_annotation logging meta package_config path pool timing watcher yaml]
- built_collection 5.1.1
- built_value 8.9.1 [built_collection collection fixnum meta]
- cached_network_image_platform_interface 4.0.0 [flutter flutter_cache_manager]
- cached_network_image_web 1.1.1 [cached_network_image_platform_interface flutter flutter_cache_manager]
- characters 1.3.0
- checked_yaml 2.0.3 [json_annotation source_span yaml]
- clock 1.1.1
- code_builder 4.10.0 [built_collection built_value collection matcher meta]
- collection 1.18.0
- color 3.0.0
- convert 3.1.1 [typed_data]
- cross_file 0.3.4+1 [meta web]
- crypto 3.0.3 [typed_data]
- dart_style 2.3.6 [analyzer args collection path pub_semver source_span]
- dartx 1.2.0 [characters collection crypto meta path time]
- dbus 0.7.10 [args ffi meta xml]
- encrypt 5.0.3 [args asn1lib clock collection crypto pointycastle]
- fake_async 1.3.1 [clock collection]
- ffi 2.1.0
- file 7.0.0 [meta path]
- file_selector_linux 0.9.2+1 [cross_file file_selector_platform_interface flutter]
- file_selector_macos 0.9.4 [cross_file file_selector_platform_interface flutter]
- file_selector_platform_interface 2.6.2 [cross_file flutter http plugin_platform_interface]
- file_selector_windows 0.9.3+1 [cross_file file_selector_platform_interface flutter]
- firebase_analytics_platform_interface 4.2.0 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_analytics_web 0.5.9 [_flutterfire_internals firebase_analytics_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins]
- firebase_auth_platform_interface 7.4.2 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 5.12.4 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser meta web]
- firebase_core_platform_interface 5.1.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.17.3 [firebase_core_platform_interface flutter flutter_web_plugins meta web]
- firebase_crashlytics_platform_interface 3.6.39 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_platform_interface 4.5.41 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 3.8.11 [_flutterfire_internals firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins meta web]
- fixnum 1.1.0
- flutter_cache_manager 3.3.1 [clock collection file flutter http path path_provider rxdart sqflite uuid]
- flutter_gen_core 5.4.0 [path yaml mime xml dartx color collection json_annotation glob dart_style args pub_semver]
- flutter_keyboard_visibility 6.0.0 [meta flutter_keyboard_visibility_platform_interface flutter_keyboard_visibility_linux flutter_keyboard_visibility_macos flutter_keyboard_visibility_web flutter_keyboard_visibility_windows flutter]
- flutter_keyboard_visibility_linux 1.0.0 [flutter_keyboard_visibility_platform_interface flutter]
- flutter_keyboard_visibility_macos 1.0.0 [flutter_keyboard_visibility_platform_interface flutter]
- flutter_keyboard_visibility_platform_interface 2.0.0 [flutter meta plugin_platform_interface]
- flutter_keyboard_visibility_web 2.0.0 [flutter_keyboard_visibility_platform_interface flutter_web_plugins flutter]
- flutter_keyboard_visibility_windows 1.0.0 [flutter_keyboard_visibility_platform_interface flutter]
- flutter_local_notifications_linux 4.0.1 [dbus ffi flutter flutter_local_notifications_platform_interface path xdg_directories]
- flutter_local_notifications_platform_interface 7.2.0 [flutter plugin_platform_interface]
- flutter_plugin_android_lifecycle 2.0.19 [flutter]
- flutter_staggered_grid_view 0.7.0 [flutter]
- flutter_web_plugins 0.0.0 [flutter characters collection material_color_utilities meta vector_math]
- frontend_server_client 4.0.0 [async path]
- glob 2.1.2 [async collection file path string_scanner]
- google_identity_services_web 0.3.1+3 [meta web]
- google_sign_in_android 6.1.22 [flutter google_sign_in_platform_interface]
- google_sign_in_ios 5.7.5 [flutter google_sign_in_platform_interface]
- google_sign_in_platform_interface 2.4.5 [flutter plugin_platform_interface]
- google_sign_in_web 0.12.4+1 [flutter flutter_web_plugins google_identity_services_web google_sign_in_platform_interface http web]
- graphs 2.3.1 [collection]
- http 1.2.2 [async http_parser meta web]
- http_multi_server 3.2.1 [async]
- http_parser 4.0.2 [collection source_span string_scanner typed_data]
- iamport_webview_flutter 3.0.6 [flutter]
- image_picker_android 0.8.9+6 [flutter flutter_plugin_android_lifecycle image_picker_platform_interface]
- image_picker_for_web 3.0.2 [flutter flutter_web_plugins image_picker_platform_interface mime]
- image_picker_ios 0.8.9+2 [flutter image_picker_platform_interface]
- image_picker_linux 0.2.1+1 [file_selector_linux file_selector_platform_interface flutter image_picker_platform_interface]
- image_picker_macos 0.2.1+1 [file_selector_macos file_selector_platform_interface flutter image_picker_platform_interface]
- image_picker_platform_interface 2.9.3 [cross_file flutter http plugin_platform_interface]
- image_picker_windows 0.2.1+1 [file_selector_platform_interface file_selector_windows flutter image_picker_platform_interface]
- io 1.0.4 [meta path string_scanner]
- js 0.6.7 [meta]
- json_annotation 4.8.1 [meta]
- kakao_flutter_sdk_auth 1.9.1+2 [flutter json_annotation dio shared_preferences platform crypto kakao_flutter_sdk_common]
- kakao_flutter_sdk_common 1.9.1+2 [flutter flutter_web_plugins json_annotation dio shared_preferences shared_preferences_foundation platform crypto encrypt]
- kakao_flutter_sdk_friend 1.9.1+2 [flutter json_annotation dio kakao_flutter_sdk_user webview_flutter webview_flutter_android webview_flutter_wkwebview]
- kakao_flutter_sdk_navi 1.9.1+2 [flutter json_annotation dio platform kakao_flutter_sdk_common]
- kakao_flutter_sdk_share 1.9.1+2 [flutter json_annotation dio platform kakao_flutter_sdk_template]
- kakao_flutter_sdk_talk 1.9.1+2 [flutter json_annotation dio kakao_flutter_sdk_auth kakao_flutter_sdk_user kakao_flutter_sdk_template]
- kakao_flutter_sdk_template 1.9.1+2 [flutter json_annotation kakao_flutter_sdk_common]
- kakao_flutter_sdk_user 1.9.1+2 [flutter flutter_web_plugins json_annotation dio kakao_flutter_sdk_auth]
- leak_tracker 10.0.4 [clock collection meta path vm_service]
- leak_tracker_flutter_testing 3.0.3 [flutter leak_tracker leak_tracker_testing matcher meta]
- leak_tracker_testing 3.0.1 [leak_tracker matcher meta]
- lints 2.1.1
- logging 1.2.0
- matcher 0.12.16+1 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.8.0 [collection]
- meta 1.12.0
- mime 1.0.5
- octo_image 2.0.0 [flutter]
- package_config 2.1.0 [path]
- path 1.9.0
- path_parsing 1.0.1 [vector_math meta]
- path_provider 2.1.2 [flutter path_provider_android path_provider_foundation path_provider_linux path_provider_platform_interface path_provider_windows]
- path_provider_android 2.2.2 [flutter path_provider_platform_interface]
- path_provider_foundation 2.3.2 [flutter path_provider_platform_interface]
- path_provider_linux 2.2.1 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_platform_interface 2.1.2 [flutter platform plugin_platform_interface]
- path_provider_windows 2.2.1 [ffi flutter path path_provider_platform_interface win32]
- permission_handler_android 12.0.12 [flutter permission_handler_platform_interface]
- permission_handler_apple 9.4.5 [flutter permission_handler_platform_interface]
- permission_handler_html 0.1.3+2 [flutter flutter_web_plugins permission_handler_platform_interface web]
- permission_handler_platform_interface 4.2.2 [flutter meta plugin_platform_interface]
- permission_handler_windows 0.2.1 [flutter permission_handler_platform_interface]
- petitparser 6.0.2 [meta]
- platform 3.1.4
- plugin_platform_interface 2.1.8 [meta]
- pointycastle 3.7.4 [collection convert js]
- pool 1.5.1 [async stack_trace]
- pub_semver 2.1.4 [collection meta]
- pubspec_parse 1.2.3 [checked_yaml collection json_annotation pub_semver yaml]
- rxdart 0.27.7
- shared_preferences 2.2.2 [flutter shared_preferences_android shared_preferences_foundation shared_preferences_linux shared_preferences_platform_interface shared_preferences_web shared_preferences_windows]
- shared_preferences_android 2.2.1 [flutter shared_preferences_platform_interface]
- shared_preferences_foundation 2.3.5 [flutter shared_preferences_platform_interface]
- shared_preferences_linux 2.3.2 [file flutter path path_provider_linux path_provider_platform_interface shared_preferences_platform_interface]
- shared_preferences_platform_interface 2.3.2 [flutter plugin_platform_interface]
- shared_preferences_web 2.3.0 [flutter flutter_web_plugins shared_preferences_platform_interface web]
- shared_preferences_windows 2.3.2 [file flutter path path_provider_platform_interface path_provider_windows shared_preferences_platform_interface]
- shelf 1.4.1 [async collection http_parser path stack_trace stream_channel]
- shelf_web_socket 1.0.4 [shelf stream_channel web_socket_channel]
- sign_in_with_apple_platform_interface 1.0.0 [flutter plugin_platform_interface meta]
- sign_in_with_apple_web 1.0.1 [flutter flutter_web_plugins sign_in_with_apple_platform_interface js]
- sky_engine 0.0.99
- sliver_tools 0.2.12 [flutter]
- source_span 1.10.0 [collection path term_glyph]
- sprintf 7.0.0
- sqflite 2.3.2 [flutter sqflite_common path]
- sqflite_common 2.5.3 [synchronized path meta]
- stack_trace 1.11.1 [path]
- stream_channel 2.1.2 [async]
- stream_transform 2.1.0
- string_scanner 1.2.0 [source_span]
- syncfusion_flutter_core 21.2.10 [vector_math flutter]
- synchronized 3.1.0+1
- term_glyph 1.2.1
- test_api 0.7.0 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph]
- time 2.1.4 [clock]
- timezone 0.9.4 [path]
- timing 1.0.1 [json_annotation]
- typed_data 1.3.2 [collection]
- uni_links 0.5.1 [flutter uni_links_platform_interface uni_links_web]
- uni_links_platform_interface 1.0.0 [flutter plugin_platform_interface]
- uni_links_web 0.1.0 [flutter flutter_web_plugins uni_links_platform_interface]
- url_launcher_android 6.2.2 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.3.0 [flutter url_launcher_platform_interface]
- url_launcher_linux 3.1.1 [flutter url_launcher_platform_interface]
- url_launcher_macos 3.2.0 [flutter url_launcher_platform_interface]
- url_launcher_platform_interface 2.3.0 [flutter plugin_platform_interface]
- url_launcher_web 2.3.1 [flutter flutter_web_plugins url_launcher_platform_interface web]
- url_launcher_windows 3.1.1 [flutter url_launcher_platform_interface]
- uuid 4.3.3 [crypto sprintf meta fixnum]
- vector_graphics 1.1.11+1 [flutter http vector_graphics_codec]
- vector_graphics_codec 1.1.11+1
- vector_graphics_compiler 1.1.11+1 [args meta path_parsing xml vector_graphics_codec path]
- vector_math 2.1.4
- vm_service 14.2.1
- watcher 1.1.0 [async path]
- web 0.5.1
- web_socket_channel 2.4.0 [async crypto stream_channel]
- webview_flutter 4.7.0 [flutter webview_flutter_android webview_flutter_platform_interface webview_flutter_wkwebview]
- webview_flutter_android 3.16.0 [flutter webview_flutter_platform_interface]
- webview_flutter_platform_interface 2.10.0 [flutter meta plugin_platform_interface]
- webview_flutter_wkwebview 3.13.0 [flutter path webview_flutter_platform_interface]
- win32 5.2.0 [ffi]
- xdg_directories 1.0.4 [meta path]
- xml 6.5.0 [collection meta petitparser]
- yaml 3.1.2 [collection source_span string_scanner]


```

</details>

**Comment by SelaseKay** [comment] 2024-09-04 11:00
Hi @choi-seung-min , I'm unable to reproduce this on my end. is it a test number?

**Comment by SelaseKay** [comment] 2024-09-04 11:05
Also, what payment plan are you on currently?

**Comment by choi-seung-min** [comment] 2024-09-04 12:06
@SelaseKay Hello, It worked on test number. But not worked on non-test (real) phone number.
I'm currently using spark plan.

**Comment by SelaseKay** [comment] 2024-09-04 12:19
Kindly switch to blaze plan.

**Comment by wrteam-aayush** [comment] 2024-09-05 06:13
Hello @SelaseKay,

I'm also facing same the same issue. However it should work with the Spark plan as the Phone Authentication allows 10 free OTP SMS per day which should work without having a billing account or Blaze plan subscription, as it does work for my other Firebase projects.

Let me know if there's a fix for this.

Thanks.

**Comment by khushab** [comment] 2024-09-05 06:58
Hi @SelaseKay,
I am facing the same issue. I currently have Spark plan which has a limit 10 sms/day but I am getting the error even if the limit has not surpassed. 

Kindly let me know to fix this.

Thank you.

**Comment by gopalkking** [comment] 2024-09-05 15:44
same issue yesterday Coming this error  [Firebase Auth]: [firebase_auth/unknown] An internal error has occurred. [ BILLING_NOT_ENABLED ] 
How to fix this ?

**Comment by techdostmobile** [comment] 2024-09-06 06:00
I'm also facing same issue in my flutter project 

E/FirebaseAuth( 9570): [SmsRetrieverHelper] SMS verification code request failed: unknown status code: 17499 BILLING_NOT_ENABLED
D/FirebaseAuth( 9570): Invoking original failure callbacks after phone verification failure for +918755996723, error - An internal error has occurred. [ BILLING_NOT_ENABLED ]
I/flutter ( 9570): An internal error has occurred. [ BILLING_NOT_ENABLED ]

How to fix this ?

**Comment by Casaemiro** [comment] 2024-09-06 07:43
Hi @SelaseKay I'm facing the same issue with next js
{
  "error": {
    "code": 400,
    "message": "BILLING_NOT_ENABLED",
    "errors": [
      {
        "message": "BILLING_NOT_ENABLED",
        "domain": "global",
        "reason": "invalid"
      }
    ]
  }
}

**Comment by wisdomrider** [comment] 2024-09-06 08:03
Same issue with me.

<img width="1321" alt="image" src="https://github.com/user-attachments/assets/0db715bc-665c-492a-9700-16a0ac145867">

**Comment by wisdomrider** [comment] 2024-09-06 08:04
Same issue with me getting this

`"Client error: `POST https:\/\/www.google` resulted in a `400 Bad Request` response:\n{\n  \"error\": {\n    \"code\": 400,\n    \"message\": \"BILLING_NOT_ENABLED\",\n    \"errors\": [\n      {\n        \"message\": \"BILLIN (truncated...)\n"
[Fri Sep  6 13:48:02 2024] 127.0.0.1:61488 Closing`

**Comment by SelaseKay** [comment] 2024-09-06 08:25
![Screenshot 2024-09-06 at 09 09 16](https://github.com/user-attachments/assets/59696c80-c2b8-4d21-bdfc-8f1dde1ef6de)

What plan are you on currently?

**Comment by russellwheatley** [comment] 2024-09-06 08:29
Hey everyone, the root cause appears to be that you're all on Spark plans which is the free tier. You only get 10 free sms messages per day. If you think that you haven't reached that limit and are seeing this exception, feel free to reach out to [Firebase support](https://firebase.google.com/support) and raise the question whether this limit has changed. 

In any event, this is not fixable from FlutterFire. The response if coming from the Firebase server. Please reach out to Firebase support.

**Comment by choi-seung-min** [comment] 2024-09-06 11:31
Hello, I found some kind of workaround.
Go to your Google Cloud Platform and make payment profile for your firebase project.
This solution is working, but I think firebase spark plan should work without this payment profile.
It worked without payment profile for mounth(maybe 2~3) and is suddenly came out.

**Comment by russellwheatley** [comment] 2024-09-06 12:07
@choi-seung-min - please raise this with [Firebase support](https://firebase.google.com/support) 🙏

**Comment by Fayyaz009** [comment] 2024-09-06 15:36
Facing the exactly same issue  test phone no is working but real phone no not working, im on spark plan[free] if anyone found the solution please tell the solution

**Comment by hjdev-codes** [comment] 2024-09-06 18:26
is anyone found the solution please let me know. for creating payment method in GCP we have to add our credit card info. as a tester i don't thing its worth. it should be free as they are written on there website.

**Comment by Fayyaz009** [comment] 2024-09-07 05:06
ok i have contacted firebase support and the response was this sadlty authentication now required blaza plan, its no longer available on spark plan anymore. read the firebase response email below    


Hello Muhammad,

I hope you are doing great. Thank you for reaching out to Firebase Support, this is Hugo and I will be happy to help you out.

We’re sorry to hear that you’re having issues with the Firebase Phone Authentication service.

Regarding the problem, we sent an email a few weeks ago informing that all projects utilizing Firebase Phone Authentication (SMS) must be linked to a Cloud Billing account starting from September 1, 2024. We apologize if you missed our email, we’d like to improve our methods to communicate with the community so any recommendations you have for us in that matter are much appreciated if you have any. As for the email, it is stated that without Blaze Plan enabled you will no longer be able to use the Phone Authentication service, which means that adding a payment method to your project is now a prerequisite to be able to use the service. For further clarification regarding Phone Authentication Billing, please check [this information](https://cloud.google.com/identity-platform/pricing).

Please let me know if this information was helpful for you. If you have any other questions or issues, please do not hesitate to [reach out to us](https://firebase.google.com/support).

Thank you very much and have a nice day.

Regards,

Hugo Varela.

**Comment by kkbughunter** [comment] 2024-09-07 14:47
But in the **[Pricing plans page](https://firebase.google.com/pricing)** they have mentioned the **Spark plan** has 10 SMS sent/day.

**Comment by Fayyaz009** [comment] 2024-09-07 15:03
They have started this criterial from last saturday date 1 sep 2024 sadly now phone authentication requires blaze plan enable you wont be charged for first 10 otp sms/day its like the same spark plan

**Comment by sheehanmunim** [comment] 2024-09-08 00:52
I do have billing enabled but I'm still getting the error

**Comment by Avik-Bera-scorpion23** [comment] 2024-09-12 06:17
![Selected photo](https://github.com/user-attachments/assets/53bdbf2a-14db-472e-acc9-5f977e4b8da7)
I got this warning after call this ( await auth().signInWithPhoneNumber( phn ); ) function. in recat native cli

**Comment by ADEELAHMAD256** [comment] 2024-09-28 06:46
> same issue yesterday Coming this error [Firebase Auth]: [firebase_auth/unknown] An internal error has occurred. [ BILLING_NOT_ENABLED ] How to fix this ?

I have same problem. did you find any solution? if yes then please guide me

**Comment by Fayyaz009** [comment] 2024-09-28 18:05
> > same issue yesterday Coming this error [Firebase Auth]: [firebase_auth/unknown] An internal error has occurred. [ BILLING_NOT_ENABLED ] How to fix this ?
> 
> I have same problem. did you find any solution? if yes then please guide me

You have to wnable blaze plane

**Comment by kartikeyapandey20** [comment] 2024-09-28 20:36
I have purchased the blaze plan still facing the billing not enabled issue I don't understand why this happening even thought I have blaze plan

**Comment by russellwheatley** [comment] 2024-09-30 08:10
@Fayyaz009 - thank you for the update. As mentioned in the [response from Firebase support](https://github.com/firebase/flutterfire/issues/13272#issuecomment-2335044967) you must have your Firebase project linked to a billing account for Phone Authentication (SMS). Closing this issue out.

**Closed by russellwheatley** 2024-09-30 08:10 UTC
Labels: plugin: auth, resolution: solution-provided, platform: all

**Comment by Ajitcool008** [comment] 2024-10-03 20:55
Add your card on google console for payment and this problem will solve.

**Comment by hakeemdeggs** [comment] 2024-10-17 15:38
Hey guys, This is the issue. I hope this helps. I think as developers we need to do a better job at checking our 
emails 😂 

![Screenshot 2024-10-17 at 9 37 18 AM](https://github.com/user-attachments/assets/ad72f6cf-97f4-4acf-a89e-0a81e96a7882)
