### ISSUE TITLE
PlatformException (PlatformException(ERROR_INVALID_CREDENTIAL, The supplied auth credential is incorrect, malformed or has expired., {}, null))

### ISSUE THREAD

**Issue by cumody** [firebase/flutterfire#12044] opened 2023-12-15 17:59 UTC
## PlatformException 

**I have been using signIn with email and password i'm trying to handle the the exception when the user entered invalid email and password**
 

<details>

```

Future<void> loginWithEmail(String email, String password) async {
    emit(LoginLoading());
    try {
      UserCredential userCredential =
          await _authService.signInWithEmailAndPassword(email, password);
      emit(LoginSuccess(userCredential.user!));
    } on FirebaseAuthException catch (e) {
      // Handle Firebase exceptions
      String errorMessage = _handleFirebaseAuthException(e);
      emit(LoginFailure(errorMessage));
    } on PlatformException catch (e) {
      if (e.code == 'ERROR_INVALID_CREDENTIAL') {
        emit(ErrorInvalidCredential());
      }
      emit(LoginFailure(_handlePlatformException(e)));
    } catch (e) {
      emit(LoginFailure("An unexpected error occurred"));
    }
  }

  String _handlePlatformException(PlatformException e) {
    // Handle specific platform exceptions
    // The error handling here depends on the specific exceptions you expect
    // For instance, handling Google Sign-In or Apple Sign-In errors
    switch (e.code) {
      case 'ERROR_GOOGLE_SIGN_IN_FAILED':
        return "Google sign-in failed. Please try again.";
      // ERROR_INVALID_CREDENTIAL
      case 'ERROR_INVALID_CREDENTIAL':
        return "Invalid Email Credentials.";
      // Add more cases as needed
      default:
        return "An error occurred on the platform side: ${e.message}";
    }
  }

  String _handleFirebaseAuthException(FirebaseAuthException e) {
    switch (e.code) {
      case 'network-request-failed':
        return "Network error. Please check your connection.";
      case 'user-disabled':
        return "Your account has been disabled.";
      case 'user-not-found':
      case 'wrong-password':
        return "Incorrect email or password.";
      // Add more cases as needed
      default:
        return "An error occurred. Please try again.";
    }
  }

```
Click To Expand</summary>

**Comment by darshankawar** [comment] 2023-12-18 10:05
@cumody 
Usually the error indicates a config issue and not a bug in the plugin, as the plugin code is correctly catching the exception when such case is triggered. You'll need to check your config / settings and confirm that it is correct and there are nothing missing.

Also, your question is better suited for support channels like StackOverflow, so please ask the same there.
Closing from here. If you disagree, write in comments and I'll reopen it.

**Closed by darshankawar** 2023-12-18 10:05 UTC
Labels: type: bug, Needs Attention, in triage
