### ISSUE TITLE
[firebase_ crashlytics]: <Lexical or Preprocessor Issue (Xcode): Include of non-modular header inside framework module 'firebase_crashlytics.Crashlytics_Platform'>

### ISSUE THREAD

**Issue by shilpanavale** [firebase/flutterfire#13375] opened 2024-09-20 12:27 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Crashlytics

### Which platforms are affected?

iOS

### Description

Getting this issue while run my project on iPhone 16 Pro.

### Reproducing the issue

Run Flutter build command for iOS
Get the error

### Firebase Core version

3.5.0

### Flutter Version

3.24.3

### Relevant Log Output

```shell
Failed to build iOS app
Lexical or Preprocessor Issue (Xcode): Include of non-modular header inside framework module 'firebase_crashlytics.Crashlytics_Platform': '/Users/Desktop/Code/ios/Pods/Headers/Public/Firebase/Firebase.h'
/Users/.pub-cache/hosted/pub.dev/firebase_crashlytics-4.1.2/ios/Classes/Crashlytics_Platform.h:20:8

Lexical or Preprocessor Issue (Xcode): Include of non-modular header inside framework module 'firebase_crashlytics.ExceptionModel_Platform': '/Users/Desktop/Code/ios/Pods/Headers/Public/Firebase/Firebase.h'
/Users/.pub-cache/hosted/pub.dev/firebase_crashlytics-4.1.2/ios/Classes/ExceptionModel_Platform.h:20:8

Could not build the application for the simulator.
Error launching application on iPhone 16 Pro.
```

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Replace this line with the contents of your `flutter pub deps -- --style=compact`.

```

</details>

**Comment by SelaseKay** [comment] 2024-09-20 14:50
Duplicate of: [13323](https://github.com/firebase/flutterfire/issues/13323)

**Closed by SelaseKay** 2024-09-20 14:50 UTC
Labels: type: bug, Needs Attention
