### ISSUE TITLE
🐛 [firebase_auth] Error while logging to the facebook account .

### ISSUE THREAD

**Issue by harryandroiddev** [firebase/flutterfire#10940] opened 2023-05-11 05:21 UTC
## Bug report

**Graph API access for app was disabled due to a Platform Policy violation.
My facebook app is restricted so testing in development mode with test user .
I have integrated the fb login with firebase using flutter_login_facebook: ^1.8.0 this plugin  ,  and followed  the steps carefully    , but while login to the account it shows error  ([firebase_auth/invalid-credential] Invalid access_token, error code 43) . but i checked the token on facebook developer site with debugger which shows that the token is valid . i think there is some problem on the firebase side .

I have checked  for the app id and app secret on the firebase console are matched with the facebook dev app.**

### Steps to reproduce

`
```
Future<User> signinWithFacebook() async {
    final fb = FacebookLogin();
    final response = await fb.logIn(
      permissions: [
        FacebookPermission.publicProfile,
        FacebookPermission.email,
        FacebookPermission.userFriends
      ],
    );

    switch (response.status) {
      case FacebookLoginStatus.success:
        develop.log('Facebook login ${response}');
        final accessToken = response.accessToken;

        final userCredential = await _firebaseAuth.signInWithCredential(     //**the exception occurs here** 
          FacebookAuthProvider.credential(accessToken!.token),
        );
        return userCredential.user!;

      case FacebookLoginStatus.cancel:
        throw 'Login canceled by the user';

      case FacebookLoginStatus.error:
        throw FirebaseAuthException(
          code: 'ERROR_FACEBOOK_LOGIN',
          message: response.error?.developerMessage,
        );

      default:
        throw UnimplementedError();
    }
  }
`
```

### Flutter doctor

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.12, on macOS 13.0 22A8380 darwin-arm64, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] VS Code (version 1.78.1)
[✓] Connected device (4 available)
[✓] HTTP Host Availability
```

</details>

---

### Flutter dependencies

<details><summary>Click To Expand</summary>

```
Dart SDK 2.19.6
Flutter SDK 3.7.12
myapp 3.6.2+1

dependencies:
- app_links 3.2.0 [flutter app_links_platform_interface app_links_web app_links_windows app_links_macos]
- audio_service 0.18.7 [audio_service_platform_interface audio_service_web audio_session rxdart flutter_cache_manager clock js flutter flutter_web_plugins]
- audiotagger 2.2.1 [flutter]
- auto_size_text 3.0.0 [flutter]
- bottom_picker 1.9.1 [flutter]
- cached_network_image 3.2.1 [flutter flutter_cache_manager octo_image cached_network_image_platform_interface cached_network_image_web]
- carousel_slider 4.1.1 [flutter]
- connectivity_plus 2.3.6+1 [flutter connectivity_plus_platform_interface connectivity_plus_linux connectivity_plus_macos connectivity_plus_web connectivity_plus_windows]
- cupertino_icons 1.0.5
- dart_des 1.0.2
- device_info 2.0.3 [flutter device_info_platform_interface]
- device_info_plus 4.0.0 [flutter device_info_plus_platform_interface device_info_plus_macos device_info_plus_linux device_info_plus_web device_info_plus_windows]
- file_picker 4.6.1 [flutter flutter_web_plugins flutter_plugin_android_lifecycle plugin_platform_interface ffi path win32]
- firebase_auth 4.5.0 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 2.11.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_messaging 14.5.0 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- flip_card 0.6.0 [flutter]
- flutter 0.0.0 [characters collection js material_color_utilities meta vector_math sky_engine]
- flutter_archive 5.0.0 [flutter]
- flutter_displaymode 0.4.0 [flutter]
- flutter_facebook_auth 5.0.11 [flutter flutter_facebook_auth_platform_interface flutter_facebook_auth_web facebook_auth_desktop]
- flutter_html 3.0.0-alpha.5 [html csslib collection numerus flutter]
- flutter_local_notifications 9.9.1 [clock flutter flutter_local_notifications_linux flutter_local_notifications_platform_interface timezone]
- flutter_localizations 0.0.0 [flutter intl characters clock collection js material_color_utilities meta path vector_math]
- flutter_login_facebook 1.8.0 [flutter list_ext]
- flutter_native_splash 2.2.8 [args flutter flutter_web_plugins html image js lint meta path universal_io xml yaml]
- get_it 7.2.0 [async collection]
- google_sign_in 5.4.1 [flutter google_sign_in_android google_sign_in_ios google_sign_in_platform_interface google_sign_in_web]
- hive 2.2.3 [meta crypto]
- hive_flutter 1.1.0 [flutter hive path_provider path]
- html_unescape 2.0.0
- in_app_update 3.0.0 [flutter]
- internet_connection_checker 0.0.1+4
- just_audio 0.9.28 [just_audio_platform_interface just_audio_web audio_session rxdart path path_provider async uuid crypto meta flutter]
- just_audio_libwinmedia 0.0.4+1 [flutter just_audio_platform_interface libwinmedia]
- loader_overlay 2.0.10 [flutter back_button_interceptor]
- marquee 2.2.3 [fading_edge_scrollview flutter]
- material_design_icons_flutter 5.0.6996 [flutter]
- on_audio_query 2.6.1 [on_audio_query_platform_interface on_audio_query_web flutter]
- package_info 2.0.2 [flutter]
- palette_generator 0.3.3+2 [collection flutter path]
- path_provider 2.0.11 [flutter path_provider_android path_provider_ios path_provider_linux path_provider_macos path_provider_platform_interface path_provider_windows]
- permission_handler 10.0.0 [flutter meta permission_handler_android permission_handler_apple permission_handler_windows permission_handler_platform_interface]
- provider 6.0.3 [collection flutter nested]
- salomon_bottom_bar 3.3.1 [flutter]
- share_plus 4.1.0 [meta mime flutter share_plus_platform_interface share_plus_linux share_plus_macos share_plus_windows share_plus_web]
- sign_in_with_apple 4.1.0 [flutter meta sign_in_with_apple_platform_interface sign_in_with_apple_web]
- simple_html_css 4.0.0 [flutter html_unescape xml]
- sliding_up_panel 2.0.0+1 [flutter]
- supabase 0.3.6 [functions_client gotrue postgrest realtime_client storage_client]
- uni_links 0.5.1 [flutter uni_links_platform_interface uni_links_web]
- url_launcher 6.1.5 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- uuid 3.0.6 [crypto]
- youtube_explode_dart 1.12.0 [collection freezed_annotation html http http_parser json_annotation meta xml]

dev dependencies:
- change_app_package_name 1.1.0
- flutter_launcher_icons 0.10.0 [args checked_yaml cli_util image json_annotation path yaml]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters collection js matcher material_color_utilities meta source_span stream_channel string_scanner term_glyph]
- lint 1.10.0
- msix 3.6.3 [flutter args yaml path package_config get_it image cli_util cli_dialog pub_semver]

dependency overrides:
- firebase_messaging_platform_interface 4.4.0 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]

transitive dependencies:
- _flutterfire_internals 1.2.0 [collection firebase_core firebase_core_platform_interface flutter meta]
- app_links_macos 1.0.0 [flutter app_links_platform_interface]
- app_links_platform_interface 1.0.2 [flutter plugin_platform_interface]
- app_links_web 1.0.0 [flutter flutter_web_plugins app_links_platform_interface]
- app_links_windows 1.0.0 [flutter app_links_platform_interface]
- archive 3.3.1 [crypto path]
- args 2.3.1
- async 2.10.0 [collection meta]
- audio_service_platform_interface 0.1.0 [flutter plugin_platform_interface meta]
- audio_service_web 0.1.1 [audio_service_platform_interface rxdart js flutter flutter_web_plugins]
- audio_session 0.1.10 [flutter flutter_web_plugins rxdart meta]
- back_button_interceptor 6.0.1 [collection flutter]
- boolean_selector 2.1.1 [source_span string_scanner]
- cached_network_image_platform_interface 1.0.0 [flutter flutter_cache_manager]
- cached_network_image_web 1.0.1 [flutter flutter_cache_manager cached_network_image_platform_interface]
- characters 1.2.1
- checked_yaml 2.0.1 [json_annotation source_span yaml]
- cli_dialog 0.5.0 [dart_console]
- cli_util 0.3.5 [meta path]
- clock 1.1.1
- collection 1.17.0
- connectivity_plus_linux 1.3.1 [flutter connectivity_plus_platform_interface meta nm]
- connectivity_plus_macos 1.2.4 [connectivity_plus_platform_interface flutter]
- connectivity_plus_platform_interface 1.2.1 [flutter meta plugin_platform_interface]
- connectivity_plus_web 1.2.3 [connectivity_plus_platform_interface flutter_web_plugins flutter]
- connectivity_plus_windows 1.2.2 [connectivity_plus_platform_interface flutter]
- crypto 3.0.2 [typed_data]
- csslib 0.17.2 [source_span]
- dart_console 1.1.1 [ffi win32 intl]
- dbus 0.7.4 [args ffi meta xml]
- device_info_platform_interface 2.0.1 [flutter meta plugin_platform_interface]
- device_info_plus_linux 2.1.1 [device_info_plus_platform_interface file flutter meta]
- device_info_plus_macos 2.2.3 [device_info_plus_platform_interface flutter]
- device_info_plus_platform_interface 2.6.1 [flutter meta plugin_platform_interface]
- device_info_plus_web 2.1.0 [device_info_plus_platform_interface flutter_web_plugins flutter]
- device_info_plus_windows 2.1.1 [device_info_plus_platform_interface ffi flutter win32]
- facebook_auth_desktop 0.0.9 [flutter http flutter_secure_storage flutter_facebook_auth_platform_interface]
- fading_edge_scrollview 3.0.0 [flutter]
- fake_async 1.3.1 [clock collection]
- ffi 1.2.1
- file 6.1.4 [meta path]
- firebase_auth_platform_interface 6.14.0 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 5.4.0 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core_platform_interface 4.7.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.4.0 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_messaging_web 3.4.0 [_flutterfire_internals firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]
- flutter_blurhash 0.7.0 [flutter]
- flutter_cache_manager 3.3.0 [clock collection file flutter http path path_provider pedantic rxdart sqflite uuid]
- flutter_facebook_auth_platform_interface 4.1.1 [flutter plugin_platform_interface]
- flutter_facebook_auth_web 4.1.1 [flutter flutter_web_plugins js flutter_facebook_auth_platform_interface]
- flutter_local_notifications_linux 0.5.1 [flutter flutter_local_notifications_platform_interface dbus path xdg_directories]
- flutter_local_notifications_platform_interface 5.0.0 [flutter plugin_platform_interface]
- flutter_plugin_android_lifecycle 2.0.7 [flutter]
- flutter_secure_storage 8.0.0 [flutter flutter_secure_storage_linux flutter_secure_storage_macos flutter_secure_storage_platform_interface flutter_secure_storage_web flutter_secure_storage_windows meta]
- flutter_secure_storage_linux 1.1.3 [flutter flutter_secure_storage_platform_interface]
- flutter_secure_storage_macos 3.0.0 [flutter flutter_secure_storage_platform_interface]
- flutter_secure_storage_platform_interface 1.0.1 [flutter plugin_platform_interface]
- flutter_secure_storage_web 1.1.1 [flutter flutter_secure_storage_platform_interface flutter_web_plugins js]
- flutter_secure_storage_windows 2.0.0 [flutter flutter_secure_storage_platform_interface]
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta vector_math]
- freezed_annotation 2.1.0 [collection json_annotation meta]
- functions_client 0.0.1-dev.5 [http]
- google_sign_in_android 6.1.0 [flutter google_sign_in_platform_interface]
- google_sign_in_ios 5.5.0 [flutter google_sign_in_platform_interface]
- google_sign_in_platform_interface 2.3.0 [flutter plugin_platform_interface quiver]
- google_sign_in_web 0.10.2 [flutter flutter_web_plugins google_sign_in_platform_interface js]
- gotrue 0.2.3 [http jwt_decode universal_io]
- html 0.15.0 [csslib source_span]
- http 0.13.5 [async http_parser meta path]
- http_parser 4.0.1 [collection source_span string_scanner typed_data]
- id3 1.0.2
- image 3.2.0 [archive meta xml]
- intl 0.17.0 [clock path]
- js 0.6.5 [meta]
- json_annotation 4.6.0 [meta]
- just_audio_platform_interface 4.2.0 [flutter plugin_platform_interface]
- just_audio_web 0.4.7 [just_audio_platform_interface flutter flutter_web_plugins]
- jwt_decode 0.3.1
- libwinmedia 0.0.7 [ffi path]
- list_ext 1.0.4 [quiver collection]
- matcher 0.12.13 [meta stack_trace]
- material_color_utilities 0.2.0
- meta 1.8.0
- mime 1.0.2
- nested 1.0.0 [flutter]
- nm 0.5.0 [dbus]
- numerus 1.1.1
- octo_image 1.0.2 [flutter flutter_blurhash]
- on_audio_query_platform_interface 1.4.0 [plugin_platform_interface flutter]
- on_audio_query_web 1.3.2+2 [on_audio_query_platform_interface path id3 flutter flutter_web_plugins]
- package_config 2.1.0 [path]
- path 1.8.2
- path_provider_android 2.0.20 [flutter path_provider_platform_interface]
- path_provider_ios 2.0.11 [flutter path_provider_platform_interface]
- path_provider_linux 2.1.7 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_macos 2.0.6 [flutter path_provider_platform_interface]
- path_provider_platform_interface 2.0.4 [flutter platform plugin_platform_interface]
- path_provider_windows 2.0.7 [ffi flutter path path_provider_platform_interface win32]
- pedantic 1.11.1
- permission_handler_android 10.0.0 [flutter permission_handler_platform_interface]
- permission_handler_apple 9.0.4 [flutter permission_handler_platform_interface]
- permission_handler_platform_interface 3.7.0 [flutter meta plugin_platform_interface]
- permission_handler_windows 0.1.0 [flutter permission_handler_platform_interface]
- petitparser 5.0.0 [meta]
- platform 3.1.0
- plugin_platform_interface 2.1.4 [meta]
- postgrest 0.1.11 [http]
- process 4.2.4 [file path platform]
- pub_semver 2.1.1 [collection meta]
- quiver 3.1.0 [matcher]
- realtime_client 0.1.15 [collection web_socket_channel]
- rxdart 0.27.5
- share_plus_linux 3.0.0 [share_plus_platform_interface file flutter meta url_launcher]
- share_plus_macos 3.0.1 [share_plus_platform_interface flutter]
- share_plus_platform_interface 3.0.3 [flutter meta mime plugin_platform_interface]
- share_plus_web 3.0.1 [share_plus_platform_interface url_launcher flutter flutter_web_plugins meta]
- share_plus_windows 3.0.1 [share_plus_platform_interface flutter meta url_launcher]
- sign_in_with_apple_platform_interface 1.0.0 [flutter plugin_platform_interface meta]
- sign_in_with_apple_web 1.0.1 [flutter flutter_web_plugins sign_in_with_apple_platform_interface js]
- sky_engine 0.0.99
- source_span 1.9.1 [collection path term_glyph]
- sqflite 2.0.3+1 [flutter sqflite_common path]
- sqflite_common 2.2.1+1 [synchronized path meta]
- stack_trace 1.11.0 [path]
- storage_client 0.0.6+2 [http http_parser mime universal_io]
- stream_channel 2.1.1 [async]
- string_scanner 1.2.0 [source_span]
- synchronized 3.0.0+3
- term_glyph 1.2.1
- test_api 0.4.16 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- timezone 0.8.0 [path]
- typed_data 1.3.1 [collection]
- uni_links_platform_interface 1.0.0 [flutter plugin_platform_interface]
- uni_links_web 0.1.0 [flutter flutter_web_plugins uni_links_platform_interface]
- universal_io 2.0.4 [collection crypto meta typed_data]
- url_launcher_android 6.0.18 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.0.17 [flutter url_launcher_platform_interface]
- url_launcher_linux 3.0.1 [flutter url_launcher_platform_interface]
- url_launcher_macos 3.0.1 [flutter url_launcher_platform_interface]
- url_launcher_platform_interface 2.1.0 [flutter plugin_platform_interface]
- url_launcher_web 2.0.13 [flutter flutter_web_plugins url_launcher_platform_interface]
- url_launcher_windows 3.0.1 [flutter url_launcher_platform_interface]
- vector_math 2.1.4
- web_socket_channel 2.2.0 [async crypto stream_channel]
- win32 2.6.1 [ffi]
- xdg_directories 0.2.0+2 [meta path process]
- xml 6.1.0 [collection meta petitparser]
- yaml 3.1.1 [collection source_span string_scanner]
```

</details>

---

**Comment by darshankawar** [comment] 2023-05-11 11:45
> ([firebase_auth/invalid-credential] Invalid access_token, error code 43)

@harryandroiddev 
By any chance, the user is already logged in which might be resulting in this error ?

Have you also made sure that the app is properly setup in Facebook developer console ? Looks like `firebase_auth` is catching the exception correctly as invalid-credential, so it must be working properly at firebase end. You may probably need to revisit the config and see if anything's wrong or missed while integrating it with firebase_auth.

**Comment by harryandroiddev** [comment] 2023-05-11 12:05
I have tried calling out signout method if there is any user logged is and have checked
`var user = _firebaseAuth.currentUser` 

it return null so there is user logged in .

**Comment by darshankawar** [comment] 2023-05-12 11:41
Thanks for the update. As I mentioned previously, the plugin seems to be catching the exception properly and throwing the said error. If it would have been an issue with the plugin, it probably would have thrown `unhandled exception`, but here it says `firebase_auth/invalid-credential` and stating `Invalid access_token, error code 43`. You'll probably need to find what does error code 43 mean that will give you an idea further.

**Comment by harryandroiddev** [comment] 2023-05-15 07:21
But even i get this exception , on my facebook app with same credentials that i used to login in my app , i got a notifcation that you have logged in with facebook , but i dont know why i am getting this exception from firebase auth , i have rechecked all the steps even though it is not working , earlier there were no issue .

**Comment by darshankawar** [comment] 2023-05-15 12:45
@harryandroiddev 
From the [official documentation](https://firebase.google.com/docs/auth/flutter/federated-auth#facebook) on the usage of social media logins using firebase_auth, the recommended plugin is https://pub.dev/packages/flutter_facebook_auth so please try using this and see if you get expected behavior or not.

**Comment by harryandroiddev** [comment] 2023-05-18 09:59
Yes i have tried it , and it also throws the same error . The user gets logged in with facebook succesfully but on the firebase it is showing error . unable to login with firebase auth .

**Comment by papalardo** [comment] 2023-05-18 23:39
I did have same problem. So, I did create new app on facebook console and I did change flutter app with this new credentials.
Works normally.
Then, Facebook says "You can continue to use it in development mode.", but not works.
I will contact Facebook about this.

**Comment by darshankawar** [comment] 2023-05-23 11:00
@harryandroiddev Per above comment, it seems to be an issue with Facebook so you may want to reach out Facebook support for further resolution.

**Comment by andirihs** [comment] 2023-06-04 14:24
@harryandroiddev @papalardo
I'm facing the same issue. On flutter web I'm able to login a Facebook test user using ``signInWithPopup()``. 
On mobile get ``AuthCredentials`` with a ``accessToken`` from Facebook after login. However, when using these credentials to ``signInWithCredential()`` then I get an ``invalid-credential`` exception from firestore auth. 
Did one of you found what caused this issue?

**Comment by salim97** [comment] 2023-06-06 02:41
+1

**Comment by darshankawar** [comment] 2023-06-06 11:08
Keeping this issue open and labeling for team's input on  reported behavior.

**Comment by papalardo** [comment] 2023-06-06 16:37
> @harryandroiddev @papalardo I'm facing the same issue. On flutter web I'm able to login a Facebook test user using `signInWithPopup()`. On mobile I get `AuthCredentials` with a `accessToken` from Facebook after login. However, when using these credentials to `signInWithCredential()` then I get an `invalid-credential` exception from firestore auth. Did one of you found what caused this issue?

I made some changes at facebook request, submitted a new version, and Facebook put my application into production.
When they tested it, it worked fine. 
I didn't change anything in the Facebook login flow, it still works after Facebook allowed me to change the application to production on the Facebook Developers panel.

**Comment by andirihs** [comment] 2023-06-07 15:05
@papalardo: After your reply I insisted that Facebook put my app into production before they test again. After some back and froth they agreed and tested successfully 🎉. Thank you! 

There must be an issue with the processing of the ``accessToken`` which Facebook sdk provide on mobile platforms when the Facebook app-mode is not live. Either the mobile Facebook sdk provide a invalid token in this scenario or the firebase auth plugin is not able to handle this token correctly. 

@darshankawar: Tell me if you need more information from my side.

**Comment by Lyokone** [comment] 2023-11-28 14:52
Closing this since the issue seems to be caused by Facebook's handling of non-live apps, feel free to reopen if needed.

**Closed by Lyokone** 2023-11-28 14:52 UTC
Labels: type: bug, plugin: auth
