### ISSUE TITLE
🐛 [firebase_messaging] io.flutter.plugins.firebase.messaging.p.c java.lang.NullPointerException java.lang.RuntimeException

### ISSUE THREAD

**Issue by marslannasr7koncepts** [firebase/flutterfire#9663] opened 2022-10-03 12:20 UTC
Getting this error in Playstore Crashes Logs.

Exception more detail

```
Exception java.lang.RuntimeException: Unable to create service io.flutter.plugins.firebase.messaging.FlutterFirebaseMessagingBackgroundService: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.SharedPreferences android.content.Context.getSharedPreferences(java.lang.String, int)' on a null object reference
  at android.app.ActivityThread.handleCreateService (ActivityThread.java:4823)
  at android.app.ActivityThread.access$3000 (ActivityThread.java:260)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2470)
  at android.os.Handler.dispatchMessage (Handler.java:110)
  at android.os.Looper.loop (Looper.java:219)
  at android.app.ActivityThread.main (ActivityThread.java:8668)
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:513)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1109)
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.SharedPreferences android.content.Context.getSharedPreferences(java.lang.String, int)' on a null object reference
  at io.flutter.plugins.firebase.messaging.p.c
  at io.flutter.plugins.firebase.messaging.p.o
  at io.flutter.plugins.firebase.messaging.FlutterFirebaseMessagingBackgroundService.onCreate
  at android.app.ActivityThread.handleCreateService (ActivityThread.java:4809)
```

**Comment by darshankawar** [comment] 2022-10-03 12:55
Closing this as duplicate of https://github.com/firebase/flutterfire/issues/9332

**Closed by darshankawar** 2022-10-03 12:55 UTC
Labels: type: bug, Needs Attention, in triage
