### ISSUE TITLE
🐛 [firebase_auth] TypeError: Cannot read properties of undefined (reading 'appVerificationDisabledForTesting')

### ISSUE THREAD

**Issue by jeprojects** [firebase/flutterfire#11485] opened 2023-08-17 05:22 UTC
## Bug report

**Describe the bug**
When using verifyPhoneNumber() on web (tested working on iOS) an exception is thrown

`
[firebase_auth/unknown] An unknown error occurred: TypeError: Cannot read properties of undefined (reading 'appVerificationDisabledForTesting')
`

### Steps to reproduce

1. Call verifyPhoneNumber() as per normal

### Expected behavior

It should send an SMS verification code to the entered phone number

## Additional context

Started happening from `flutter_auth 4.7.0`

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.0, on macOS 12.6.6 21G646 darwin-x64, locale en-AU)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] IntelliJ IDEA Community Edition (version 2022.1)
[✓] VS Code (version 1.80.1)
[✓] Connected device (2 available)
[✓] Network resources

• No issues found!

```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
- firebase_auth 4.7.3 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_auth_platform_interface 6.16.2 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 5.6.3 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser js meta]
- firebase_core_platform_interface 4.8.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.7.0 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_storage_platform_interface 4.4.5 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_storage_web 3.6.6 [_flutterfire_internals async firebase_core firebase_core_web firebase_storage_platform_interface flutter flutter_web_plugins http js meta]

```

</details>

---

**Comment by drklrd56** [comment] 2023-08-17 06:06
Facing the same issue on firebase_auth v4.7.3 when I call the verifyPhoneNo function on flutter web. 

<img width="1102" alt="Screenshot 2023-08-17 at 11 04 23 AM" src="https://github.com/firebase/flutterfire/assets/79784855/b0da4a16-1d06-4c90-bebe-d90c5fe90c78">

**Comment by danagbemava-nc** [comment] 2023-08-17 10:34
Hi @jeprojects, please provide the code sample you're using in a repo that we can clone so that we can investigate this. 

Please note that for web, you should be using signInWithPhoneNumber instead of verifyPhoneNumber. See https://firebase.google.com/docs/auth/flutter/phone-auth#web_signinwithphonenumber

**Comment by karen1au** [comment] 2023-08-17 15:00
Facing the same issue, `verifyPhoneNumber` worked before v4.7.3. I've tried using `signInWithPhoneNumber`, it doesn't go past `_delegate.signInWithPhoneNumber` and does not exit `signInWithPhoneNumber` method

**Comment by PROGrand** [comment] 2023-08-17 15:04
Setting previous version in `index.html` solves `signInWithPhoneNumber` problem. (But not tested again other stuff)
```html
<head>
 ...
    <script>window.flutterfire_web_sdk_version = '9.22.1';</script>
</head>
```

**Comment by lisovyk** [comment] 2023-08-17 15:43
> Setting previous version in `index.html` solves `signInWithPhoneNumber` problem. (But not tested again other stuff)
> 
> ```
> <head>
>  ...
>     <script>window.flutterfire_web_sdk_version = '9.22.1';</script>
> </head>
> ```

Fixes it for me on web project, `firebase_auth 4.7.1`

**Comment by OthmanShaker** [comment] 2023-08-17 15:47
> Fixes it for me on web project, `firebase_auth 4.7.1`

didnt for me , all i did was do flutter upgrade and even reverting now doesnt solve it anymore

**Comment by karen1au** [comment] 2023-08-17 15:49
> Setting previous version in `index.html` solves `signInWithPhoneNumber` problem. (But not tested again other stuff)
> 
> ```
> <head>
>  ...
>     <script>window.flutterfire_web_sdk_version = '9.22.1';</script>
> </head>
> ```

This works on 4.7.3 as well but with a flutter warning... Which means something in the update is not compatible with the latest SDK 🤔 
```
 WARNING: FlutterFire for Web is explicitly tested against Firebase JS SDK version "10.1.0"
            but your currently specifying "9.22.1" by either the imported Firebase JS SDKs in your web/index.html
```

**Comment by OthmanShaker** [comment] 2023-08-17 17:02
> > Setting previous version in `index.html` solves `signInWithPhoneNumber` problem. (But not tested again other stuff)
> > ```
> > <head>
> >  ...
> >     <script>window.flutterfire_web_sdk_version = '9.22.1';</script>
> > </head>
> > ```
> 
> This works on 4.7.3 as well but with a flutter warning... Which means something in the update is not compatible with the latest SDK 🤔
> 
> ```
>  WARNING: FlutterFire for Web is explicitly tested against Firebase JS SDK version "10.1.0"
>             but your currently specifying "9.22.1" by either the imported Firebase JS SDKs in your web/index.html
> ```

this worked for me aswell , with the same warnning

**Comment by jeprojects** [comment] 2023-08-18 01:38
> Setting previous version in `index.html` solves `signInWithPhoneNumber` problem. (But not tested again other stuff)
> 
> ```
> <head>
>  ...
>     <script>window.flutterfire_web_sdk_version = '9.22.1';</script>
> </head>
> ```

It fixes it for me with `verifyPhoneNumber()` on the web.

**Comment by NefariousNiru** [comment] 2023-08-18 09:31
`<script>window.flutterfire_web_sdk_version = '9.22.1';</script>`

Works with`signInWithPhoneNumber()` on Web for me. However like everyone else I still get a warning.


WARNING: FlutterFire for Web is explicitly tested against Firebase JS SDK version "10.1.0"
            but your currently specifying "9.22.1" by either the imported Firebase JS SDKs in your web/index.html
            file or by providing an override - this may lead to unexpected issues in your application. It is recommended that you change all of the versions of the
            Firebase JS SDK version "10.1.0":
            If you override the version manually:
              change:
                <script>window.flutterfire_web_sdk_version = '9.22.1';</script>
              to:
                <script>window.flutterfire_web_sdk_version = '10.1.0';</script>
            If you import the Firebase scripts in index.html, instead allow FlutterFire to manage this for you by removing
            any Firebase scripts in your web/index.html file:
                e.g. remove: <script src="https://www.gstatic.com/firebasejs/9.22.1/firebase-app.js"></script>

**Comment by davidmigloz** [comment] 2023-08-18 10:50
[`9.23.0`](https://firebase.google.com/support/release-notes/js#version_9230_-_june_21_2023) is the latest version 9.x version. It also seems to work.

**Comment by danagbemava-nc** [comment] 2023-08-18 11:24
Is anyone facing this issue when they use `signInWithPhoneNumber `?

**Comment by davidmigloz** [comment] 2023-08-18 11:30
I believe it affects both:
- Phone authentication
- Or phone as a second factor

**Comment by jeprojects** [comment] 2023-08-18 11:32
@danagbemava-nc by the looks of the comments, most of them.

**Comment by anthonyhunter** [comment] 2023-08-20 01:23
Same here

I suspect this because of https://github.com/firebase/firebase-js-sdk/pull/7326/files

The parameters to `RecaptchaVerifier()` where reordered in SDK but corresponding change not yet made in FlutterFire.

**Comment by joshhsiao333** [comment] 2023-08-20 06:39
I noticed in firebase 10.0.0 releaselog: 
reordered RecaptchaVerifier parameters so auth is "the first parameter".
soluation:
Put auth as first parameter of RecaptchaVerifier object resolved this issue.

**Comment by danagbemava-nc** [comment] 2023-08-21 11:10
Thanks all for your patience, I can reproduce the issue using the plugin example code. 

cc @russellwheatley

**Comment by shobith** [comment] 2023-08-23 22:42
Hope someone can guide that PR to a quick resolution, I need this fix :(

**Comment by HandsonOmbiro** [comment] 2023-08-24 04:43
This issue is pending. Even after adding:
` <script>window.flutterfire_web_sdk_version = '9.22.1';</script>` or the 9.23.0 as suggested by @davidmigloz, 
1. You get the warning below: 

` WARNING: FlutterFire for Web is explicitly tested against Firebase JS SDK version "10.1.0"
            but your currently specifying "9.23.0" by either the imported Firebase JS SDKs in your web/index.html    
            file or by providing an override - this may lead to unexpected issues in your application. It is
            recommended that you change all of the versions of the
            Firebase JS SDK version "10.1.0":

            If you override the version manually:
              change:
                <script>window.flutterfire_web_sdk_version = '9.23.0';</script>
              to:
                <script>window.flutterfire_web_sdk_version = '10.1.0';</script>

            If you import the Firebase scripts in index.html, instead allow FlutterFire to manage this for you by    
            removing
            any Firebase scripts in your web/index.html file:
                e.g. remove: <script src="https://www.gstatic.com/firebasejs/9.23.0/firebase-app.js"></script> `
for which you find the script was added manually as advised
2. The web sms authentication (when using Firebase Emulators now completely does not send the generated 6 character OTP code. 

One major thing to note: This started failing immediately after upgrading from Flutter 3.10.6 to Flutter 3.13.0>

Note that the packages are all up to the latest. 

This issue should remain open. I have checked on the rearranged `RecapchaVerifier` but I do not see how the rearranging will force a warnig to change flutter web sdk from 19. I did even try the latest SDK, the error persisit.
I could see a new Flutter 3.13.1 which addresses another issue (132711). I had also experienced but it is not addressing this particular issue (the fixes above may be working with JavaScript, but not with Flutter projects.

**Comment by rahmanrezaee** [comment] 2023-08-28 11:38
Same issue with 10.1.0 
is any solution??

**Comment by dannycortesv** [comment] 2023-08-28 22:13
This doesn't work for me with latest firebase_auth version, it works with these ones:

 firebase_auth: 4.6.3
 firebase_auth_web: 5.5.3
firebase_auth_platform_interface:  6.15.3

and using  <script>window.flutterfire_web_sdk_version = '9.23.0';</script> before closing head

**Comment by prologikus** [comment] 2023-08-29 09:07
this issue is still present [3.13.1]

**Closed** 2023-08-30 08:46 UTC
Labels: type: bug, plugin: auth, platform: web

**Comment by HandsonOmbiro** [comment] 2023-08-31 14:44
I have tested with flutter sdk 3.10.6 and 3.13.0 and 3.13.2 and come to a conclusion, the issue is with:   firebase_auth: ^4.7.0 and above. 
While they have merged some changes to that effect with   firebase_auth: ^4.9.0, and with respect to this: [https://github.com/firebase/flutterfire/pull/11514], The two are not on the same page: so I have manually used:   **firebase_auth: ^4.6.3** for my SMS authentication to again work in the local firebase emulator.

**Comment by lisovyk** [comment] 2023-09-01 08:35
The issue is fixed for me on:
`firebase_auth: ^4.9.0` 
`Flutter 3.13.0`

Don't forget to comment out the fix in index.html if you made it.

**Comment by Hs809** [comment] 2023-09-11 10:00
I am getting the same issue on signInWithPhoneNumber, using Firebase 10.3.1 
Did anyone get any solution for the web?

**Comment by Hs809** [comment] 2023-09-11 10:42
> I am getting the same issue on signInWithPhoneNumber, using Firebase 10.3.1 Did anyone get any solution for the web?

I resolved this issue by degrading the firebase version to 9.14.0 Hope this helps you out

**Comment by anthonyhunter** [comment] 2023-09-11 11:05
Fixed for me on Android, iOS and web
`flutter: "3.13.3"`
`firebase_auth: "4.9.0"`
