### ISSUE TITLE
🐛 [cloud_functions] Can't call 2nd gen functions due to missing `httpsCallableFromURL` method

### ISSUE THREAD

**Issue by jhuleatt** [firebase/flutterfire#10541] opened 2023-02-28 22:04 UTC
## Bug report

**Describe the bug**
2nd gen callable functions don't yet have stable URLs, so [an extra argument is needed to get the callable instance](https://firebase.google.com/docs/functions/beta/callable#call_the_function). Since FlutterFire doesn't support this, it isn't currently possible to call 2nd gen callable functions using FlutterFire.

### Expected behavior

FlutterFire offers a function that takes a callable function's URL as an argument, similar to iOS' `httpsCallable(URL)` overload, the JS SDK's `httpsCallableFromURL`, and Android's `getHttpsCallableFromUrl`.

## Additional context

1st gen functions have stable, guessable `cloudfunctions.net` URLs, so the client SDKs don't need to be told what a function's URL is. We're working on adding stable URLs to 2nd gen functions, but until they're available, URLs look like `https://<functionName>-<randomHash>-<region>.a.run.app/addMessage` and aren't guessable.

**Comment by jbaptisteroesch** [comment] 2023-04-17 22:36
Hi,
I tested this solution for Gen2 functions. It appears that depending on the region, it may or may not work. I tested it on eu-west-3 and it did not work, but on eu-west-1 it did work. I'm not sure what the cause of this discrepancy is, but [this article led me to wonder if the problem might be related to the location](https://cloud.google.com/run/docs/mapping-custom-domains). It's possible that the location isn't related at all, but it's worth considering.

**Comment by Lyokone** [comment] 2023-04-18 11:40
Hi, 
You can find the list of supported region here: https://firebase.google.com/docs/reference/functions/2nd-gen/node/firebase-functions.md#supportedregion

It doesn't appear that eu-west-3 is part of this list.

**Comment by Lyokone** [comment] 2023-04-18 11:42
I'm closing this issue since Cloud Function Gen 2 has landed on the SDK.

**Closed by Lyokone** 2023-04-18 11:42 UTC
Labels: type: enhancement, plugin: functions, type: missing-feature
