### ISSUE TITLE
🐛 [firebase_analytics_web] screen_view/page_view event is not being shown in Firebase console

### ISSUE THREAD

**Issue by deepak786** [firebase/flutterfire#8709] opened 2022-05-19 11:39 UTC
Referenced issue: https://github.com/firebase/flutterfire/issues/4910

When running the Flutter web app and enabling the "GA Debug", Screen View events are being shown in the browser console. But they are not being shown in the Firebase console.

When the web page is refreshed or opened then only the page_view event is shown in the Firebase console. After that, if you navigate to a new Route via Flutter code then only the browser console shows the screen events.

Browser console screenshot
![Screen Shot 2022-05-19 at 5 05 29 PM](https://user-images.githubusercontent.com/14223997/169284223-347c3ddc-a600-473c-ad3c-2a70aaf9e43e.png)

Analytics DebugView
![Screen Shot 2022-05-19 at 5 06 51 PM](https://user-images.githubusercontent.com/14223997/169284421-6b113b00-73ad-4fd4-9b63-e316ae814ba7.png)

Except for this screen_view event, the rest of the events are working fine.

**Comment by darshankawar** [comment] 2022-05-20 10:24
Closing this as duplicate of https://github.com/firebase/flutterfire/issues/8403

**Closed by darshankawar** 2022-05-20 10:24 UTC
Labels: type: bug, Needs Attention, in triage
