### ISSUE TITLE
🐛[ FirebaseAppCheck] MissingPluginException(No implementation found for method FirebaseAppCheck#registerTokenListener on channel plugins.flutter.io/firebase_app_check [web]

### ISSUE THREAD

**Issue by AhmedElghandour** [firebase/flutterfire#11777] opened 2023-10-25 16:06 UTC
## Bug report

**Describe the bug**
I am using Flutter web, It working fine on localhost but when trying it on a release domain (using firebase hosting) it gets me this error :
- MissingPluginException(No implementation found for method FirebaseAppCheck#registerTokenListener on channel plugins.flutter.io/firebase_app_check
- Unsupported operation: Platform._operatingSystem

## Additional context

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

[✓] Flutter (Channel stable, 3.13.1, on macOS 13.0.1 22A400 darwin-arm64, locale en-EG)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.74.3)
[✓] Connected device (4 available)
[✓] Network resources

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

Dart SDK 3.1.0
Flutter SDK 3.13.1
volunteerrequests 1.0.0+1

dependencies:
- adaptive_breakpoints 0.1.6 [flutter]
- bloc 8.1.2 [meta]
- cloud_firestore 4.11.0 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_interface flutter meta]
- cloud_functions 4.5.1 [cloud_functions_platform_interface cloud_functions_web firebase_core firebase_core_platform_interface flutter]
- cupertino_icons 1.0.6
- dropdown_search 5.0.6 [flutter]
- dual_screen 1.0.4 [flutter]
- equatable 2.0.5 [collection meta]
- firebase_app_check 0.2.1+2 [firebase_app_check_platform_interface firebase_app_check_web firebase_core firebase_core_platform_interface flutter]
- firebase_auth 4.11.1 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 2.20.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_database 10.3.1 [firebase_core firebase_core_platform_interface firebase_database_platform_interface firebase_database_web flutter]
- firebase_storage 11.3.1 [firebase_core firebase_core_platform_interface firebase_storage_platform_interface firebase_storage_web flutter]
- flow_builder 0.0.9 [flutter]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math web sky_engine]
- flutter_bloc 8.1.3 [bloc flutter provider]
- flutter_easyloading 3.0.5 [flutter flutter_spinkit]
- flutter_svg 1.1.6 [flutter meta path_drawing vector_math xml]
- formz 0.4.1
- intl 0.17.0 [clock path]
- quds_popup_menu 0.0.1+1 [flutter quds_ui_kit]
- url_launcher 6.1.7 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]

dev dependencies:
- flutter_lints 2.0.3 [lints]
- flutter_test 0.0.0 [flutter test_api matcher path fake_async clock stack_trace vector_math async boolean_selector characters collection material_color_utilities meta source_span stream_channel string_scanner term_glyph web]

transitive dependencies:
- _flutterfire_internals 1.3.10 [collection firebase_core firebase_core_platform_interface flutter meta]
- async 2.11.0 [collection meta]
- boolean_selector 2.1.1 [source_span string_scanner]
- characters 1.3.0
- clock 1.1.1
- cloud_firestore_platform_interface 6.0.1 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 3.8.1 [_flutterfire_internals cloud_firestore_platform_interface collection firebase_core firebase_core_web flutter flutter_web_plugins js]
- cloud_functions_platform_interface 5.5.4 [firebase_core flutter meta plugin_platform_interface]
- cloud_functions_web 4.6.4 [cloud_functions_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- collection 1.17.2
- fake_async 1.3.1 [clock collection]
- firebase_app_check_platform_interface 0.1.0+4 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_app_check_web 0.1.0+4 [_flutterfire_internals firebase_app_check_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- firebase_auth_platform_interface 7.0.1 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 5.8.4 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser js meta]
- firebase_core_platform_interface 5.0.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.8.1 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_database_platform_interface 0.2.5+9 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_database_web 0.2.3+9 [firebase_core firebase_core_web firebase_database_platform_interface flutter flutter_web_plugins js]
- firebase_storage_platform_interface 4.4.9 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_storage_web 3.6.10 [_flutterfire_internals async firebase_core firebase_core_web firebase_storage_platform_interface flutter flutter_web_plugins http js meta]
- flutter_spinkit 5.2.0 [flutter]
- flutter_web_plugins 0.0.0 [flutter characters collection material_color_utilities meta vector_math web]
- http 1.1.0 [async http_parser meta]
- http_parser 4.0.2 [collection source_span string_scanner typed_data]
- js 0.6.7 [meta]
- lints 2.1.1
- matcher 0.12.16 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.5.0 [collection]
- meta 1.9.1
- nested 1.0.0 [flutter]
- path 1.8.3
- path_drawing 1.0.1 [vector_math meta path_parsing flutter]
- path_parsing 1.0.1 [vector_math meta]
- petitparser 5.4.0 [meta]
- plugin_platform_interface 2.1.6 [meta]
- provider 6.0.5 [collection flutter nested]
- quds_ui_kit 0.0.7+10 [flutter]
- sky_engine 0.0.99
- source_span 1.10.0 [collection path term_glyph]
- stack_trace 1.11.0 [path]
- stream_channel 2.1.1 [async]
- string_scanner 1.2.0 [source_span]
- term_glyph 1.2.1
- test_api 0.6.0 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph]
- typed_data 1.3.2 [collection]
- url_launcher_android 6.1.0 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.1.5 [flutter url_launcher_platform_interface]
- url_launcher_linux 3.0.6 [flutter url_launcher_platform_interface]
- url_launcher_macos 3.0.7 [flutter url_launcher_platform_interface]
- url_launcher_platform_interface 2.1.5 [flutter plugin_platform_interface]
- url_launcher_web 2.0.20 [flutter flutter_web_plugins url_launcher_platform_interface]
- url_launcher_windows 3.0.8 [flutter url_launcher_platform_interface]
- vector_math 2.1.4
- web 0.1.4-beta
- xml 6.3.0 [collection meta petitparser]

</details>

---

**Comment by AhmedElghandour** [comment] 2023-10-26 10:51
Actually, no i tried all these steps but no clue, the error showing that there is a function that is not implemented in web. 

here is the implementation for Enterprise but still not working

  await FirebaseAppCheck.instance
      .activate(
    // androidProvider: AndroidProvider.debug,
    // appleProvider: AppleProvider.debug,
    webProvider: ReCaptchaEnterpriseProvider(kWebRecaptchaSiteKey),
  );

**Comment by darshankawar** [comment] 2023-10-27 08:00
Thanks for the update @AhmedElghandour 
Can you provide the complete error log that shows the reported error ?


> * MissingPluginException(No implementation found for method FirebaseAppCheck#registerTokenListener on channel plugins.flutter.io/firebase_app_check
> * Unsupported operation: Platform._operatingSystem

**Comment by AhmedElghandour** [comment] 2023-10-29 14:46
Sure, @darshankawar 

Uncaught MissingPluginException(No implementation found for method FirebaseAppCheck#registerTokenListener on channel plugins.flutter.io/firebase_app_check)
    at Object.c ("website link"/main.dart.js:4039:19)
    at "website link"/main.dart.js:69405:15
    at atj.a ("website link"/main.dart.js:5359:62)
    at atj.$2 ("website link"/main.dart.js:38998:14)
    at asC.$1 ("website link"/main.dart.js:38992:21)
    at aql.ap7 ("website link"/main.dart.js:39860:34)
    at aql.uX ("website link"/main.dart.js:39862:21)
    at anu.$0 ("website link"/main.dart.js:39423:11)
    at Object.wc ("website link"/main.dart.js:5491:40)
    at a9.oh ("website link"/main.dart.js:39358:3)
    
    
Uncaught Unsupported operation: Platform._operatingSystem
    at Object.c ("website link"/main.dart.js:4039:19)
    at Object.aQl ("website link"/main.dart.js:27281:15)
    at Object.aQm ("website link"/main.dart.js:27282:16)
    at "website link"/main.dart.js:93725:23
    at a.<computed> [as auy] ("website link"/main.dart.js:32:36)
    at "website link"/main.dart.js:93728:24
    at a.<computed> [as aGU] ("website link"/main.dart.js:32:36)
    at"website link"/main.dart.js:45312:6
    at atj.a ("website link"/main.dart.js:5359:62)
    at atj.$2 ("website link"/main.dart.js:38998:14)

**Comment by darshankawar** [comment] 2023-10-30 11:10
Thanks for the log @AhmedElghandour 
I am unable to replicate this using the plugin example.
From the logs, I see `("website link"/main.dart.js`. There's a space between `website link` which might be the reason. Can you remove the space and run your scenario again to check if it helps or not ?

**Comment by htsuruo** [comment] 2023-11-01 14:35
@AhmedElghandour @darshankawar 

Same problem.
Do we have to prepare for using App Check except activation?

I just implement with `activate()` method.
```dart
 await FirebaseAppCheck.instance.activate(
    webProvider: ReCaptchaEnterpriseProvider(
      '[MY_PUBLIC_KEY],
    ),
  );
```

`firebase_app_check` version is here:

```yaml
  firebase_app_check:
    dependency: "direct main"
    description:
      name: firebase_app_check
      sha256: "25d3a2fe73243221080c6dec26d3bd1b0556d765265e64a385a9e354888d4284"
      url: "https://pub.dev"
    source: hosted
    version: "0.2.1+2"
  firebase_app_check_platform_interface:
    dependency: transitive
    description:
      name: firebase_app_check_platform_interface
      sha256: ae61e0af37dd2d08f6796c579306c5864c58940231b4b40e4bf96abe9a6c82de
      url: "https://pub.dev"
    source: hosted
    version: "0.1.0+4"
  firebase_app_check_web:
    dependency: transitive
    description:
      name: firebase_app_check_web
      sha256: caa5014067bae9f4d56c763638708199435a6f24db4c5f485caa68cc99637aff
      url: "https://pub.dev"
    source: hosted
    version: "0.1.0+4"
```

You can see this problem following my website.
https://nippo.htsuruo.com/
<img width="1250" alt="image" src="https://github.com/firebase/flutterfire/assets/12729025/8a637de2-d4d8-423d-a32f-f90e7979aa44">

**Comment by htsuruo** [comment] 2023-11-04 01:36
@AhmedElghandour @darshankawar

> I am using Flutter web, It working fine on localhost but when trying it on a release domain (using firebase hosting) it gets me this error :

I tried to debug some patterns, and then it is found that following behavior:

| Case | Command | Result |
|--------|--------|--------|
| `localhost` with Debug Mode | `flutter run -d chrome` | OK |
| `localhost` with Release Mode | `flutter run --release -d chrome` | OK |
| Deployed `Firebase Hosting` with Release Mode | `flutter build` |  NG | 

I'm not sure but I think that this problem may be caused by Firebase Hosting? 🤔

**Comment by darshankawar** [comment] 2023-11-07 11:38
Based on the originally reported behavior and also above finding, keeping the issue open for team's attention and tracking.

**Comment by htsuruo** [comment] 2023-11-07 22:40
I found a little related issue.
https://github.com/flutter/flutter/issues/44600

It seems that this issue is caused by not Firebase Hosting but `flutter build web` command.

**Comment by EmreKaratopuk** [comment] 2023-11-17 14:24
same issue, any solutions?

**Comment by htsuruo** [comment] 2023-11-18 02:15
This problem may be caused by something related to the cache in the build process. When I specified the `Dart2jsOptimization` option as follows, my app hosted on Firebase worked fine. 
However, when I built the app again without this option, it still worked fine.

```yaml
# Setting `Dart2jsOptimization=00` is like debug mode.
flutter build web --dart-define=Dart2jsOptimization=00

# This also seems to work fine, when you try again.
flutter build web
```

Therefore, I suspect that the Dart2jsOptimization option helps to clear a problematic cache, and this issue occurs rarely in build optimizations.

The Dart2jsOptimization option specifies the optimization level for JavaScript code compilation. The default level of Dart2jsOptimization is [04](https://github.com/flutter/flutter/blob/89692884a1ac0077a1d62917e22a5d5e4383b9d9/packages/flutter_tools/lib/src/web/compiler_config.dart#L61), which represents the highest level of optimization. For more information, visit: https://dart.dev/tools/dart-compile#js

**Comment by EmreKaratopuk** [comment] 2023-11-18 09:41
That method worked for me too, thank you. It can be used as a temporary solution.

**Comment by htsuruo** [comment] 2023-11-18 11:34
@EmreKaratopuk 

>It can be used as a temporary solution.

After applying this method and repeatedly building with flutter build web, in my case,  the problem has not occurred again. Therefore, I believe you won't need to use this method in the future. However, I'm unsure about the exact cause.

**Comment by EmreKaratopuk** [comment] 2023-11-18 12:00
As far as I understand, this method compiles dart code in an unoptimized way, and it stays unoptimized even if `flutter build web` command is executed later on without `--dart-define=Dart2jsOptimization=00` flag (because the app still can access undeleted implementations of methods like `registerTokenListener`.

**Comment by htsuruo** [comment] 2023-11-18 12:30
@EmreKaratopuk 

> it stays unoptimized even if flutter build web command is executed later on without --dart-define=Dart2jsOptimization=00 flag

I think `flutter build web` command is executed with optimization even after executing this method.
Because when I tried to build using `--dart-define=Dart2jsOptimization=04`, which is equivalent to without Dart2jsOptimization, it still worked fine.

```sh
flutter build web --dart-define=Dart2jsOptimization=04
```

So, I have come to the conclusion that there is something wrong cache in the build process.

> access undeleted implementations of methods like registerTokenListener

I'm not sure, but it seems that `registerTokenListener` is removed in the release build in our case.
It causes rarely under a specific condition because it has been [reported](https://github.com/firebase/flutterfire/issues/11777#issuecomment-1784963764) that @darshankawar cannot reproduce this problem.

**Comment by Lyokone** [comment] 2024-06-28 07:28
I'll close this since a solution has been providing and it's not directly related to FlutterFire but Dart2JS.
Feel free to open a new issue if you are still struggling with this.

**Closed by Lyokone** 2024-06-28 07:28 UTC
Labels: type: bug, platform: web, plugin: app_check
