### ISSUE TITLE
🐛 [firebase_messaging] [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value

### ISSUE THREAD

**Issue by MohammadAsef** [firebase/flutterfire#11597] opened 2023-09-16 07:13 UTC
## Bug report

**Describe the bug**
I want to handle the notification comes from firebase I did with foreground and it works fine but when I set onBackground  handler it just throw this error. 

**logs

E/flutter ( 7754): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
E/flutter ( 7754): #0      MethodChannelFirebaseMessaging.registerBackgroundMessageHandler
package:firebase_messaging_platform_interface/…/method_channel/method_channel_messaging.dart:201
E/flutter ( 7754): #1      FirebaseMessagingPlatform.onBackgroundMessage=
package:firebase_messaging_platform_interface/…/platform_interface/platform_interface_messaging.dart:107
E/flutter ( 7754): #2      FirebaseMessaging.onBackgroundMessage
package:firebase_messaging/src/messaging.dart:73

**Comment by danagbemava-nc** [comment] 2023-09-18 10:58
Hi @MohammadAsef, please provide the code you use to handle background messages. Please also provide the versions of the firebase plugins that you're using along with the output of `flutter doctor -v`. 

Thank you

**Comment by MohammadAsef** [comment] 2023-09-19 03:15
code for handling the background message is just simple I called onBackground method and inside it just a simple print statement.
`````
FirebaseMessaging.onBackgroundMessage((message) async {
        print("${message.notification}");
      });
``````

currently I am using firebase_messaging: ^14.6.7

Here is my flutter doctor -v result

````
$ flutter doctor -v
[√] Flutter (Channel stable, 3.10.6, on Microsoft Windows [Version 10.0.18363.1198], locale en-US)
    • Flutter version 3.10.6 on channel stable at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (10 weeks ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at E:\Android Studio\android-sdk-windows
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = E:\Android Studio\android-sdk-windows
    • Java binary at: C:\Program Files\Java\jdk-11.0.14\bin\java
    • Java version Java(TM) SE Runtime Environment 18.9 (build 11.0.14+8-LTS-263)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[!] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 49.0.1
    • Dart plugin version 192.8052
    X Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[√] VS Code, 64-bit edition (version 1.49.0)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.16.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.18363.1198]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 117.0.5938.88
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 116.0.1938.54

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
````

Also I am using vs code for development

**Comment by danagbemava-nc** [comment] 2023-09-19 09:56
Hi @MohammadAsef, that is not the correct way to setup the background message handler. See the example app for how to set this up properly https://github.com/firebase/flutterfire/blob/master/packages/firebase_messaging/firebase_messaging/example/lib/main.dart

**Comment by MohammadAsef** [comment] 2023-09-21 04:04
But I want to show my own title and body instead of main notification. for example if title of notification is "ChatNoti" then I want to show "New Message" in notification bar as title not "ChatNoti". like this for body either I want to change the body either. Is it possible ?

**Comment by danagbemava-nc** [comment] 2023-09-21 10:03
Please provide a complete minimal reproducible code sample in a repo that we can clone so that we can investigate this issue. 

Thank you

**Comment by MohammadAsef** [comment] 2023-09-29 05:38
would you please explain me what does below method do in your package:

**Comment by danagbemava-nc** [comment] 2023-09-29 10:37
Hi @MohammadAsef, that property is not expected to be null if the app is setup properly to handle background messages. I just tested the firebase_messaging example app and everything works just as expected. 

Please provide the code sample you're experiencing the issue with in a repo that we can clone so that we can investigate this issue. 

Thank you

**Comment by MohammadAsef** [comment] 2023-09-30 03:53
Finally could solve my problem thanks for your help. it was missing something in manifest file. But Now it show me two notification one is I show by FlutterLocalNotificationPlugin and one is show by system how can I prevent system notification and only show my local notification ????

**Comment by danagbemava-nc** [comment] 2023-10-02 10:37
Kindly check https://stackoverflow.com/questions/67820474/double-notifications-in-flutter-firebase-messaging  to see if it helps. 

For now, I'll be closing this since the original report for this issue has been resolved.

**Closed by danagbemava-nc** 2023-10-02 10:37 UTC
Labels: type: bug, Needs Attention, in triage
