### ISSUE TITLE
🐛 [firebase_auth] Crash when calling user.getIdToken(true)

### ISSUE THREAD

**Issue by cto-seak-global** [firebase/flutterfire#11311] opened 2023-07-18 09:59 UTC
## Bug report

**Describe the bug**
Android only: When the ID token is refreshed by calling `user.getIdToken(true)`, the app crashes with the message

```
PlatformException (PlatformException(channel-error, Unable to establish connection on channel., null, null))
```

and the app closes, even if the invocation is in a try/catch block.

### Steps to reproduce

1. Get the current author using `auth.currentUser`
2. Invoke `user.getIdToken(true)`
3. Observe the crash

### Expected behavior

No crash

## Additional context

This is Version 4.7.1, which lists a fix for a related crash.

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 3.10.6, on macOS 12.6 21G115 darwin-arm64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.80.1)
[✓] Connected device (3 available)
    ! Error: Failed to prepare the device for development. This operation can fail if the version of the OS on the device is incompatible with the installed version of Xcode. You may also need to restart your Mac
      and device in order to correctly detect compatibility. (code 806)
[✓] Network resources

• No issues found!

```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 3.0.6
Flutter SDK 3.10.6
safe 3.0.1+1001

dependencies:
- another_flushbar 1.12.30 [flutter]
- auto_size_text 3.0.0 [flutter]
- background_fetch 1.1.6 [flutter]
- badges 3.1.1 [flutter]
- battery_plus 4.0.1 [flutter flutter_web_plugins battery_plus_platform_interface meta upower]
- cached_network_image 3.2.3 [flutter flutter_cache_manager octo_image cached_network_image_platform_interface cached_network_image_web]
- camera 0.10.5+2 [camera_android camera_avfoundation camera_platform_interface camera_web flutter flutter_plugin_android_lifecycle quiver]
- cloud_firestore 4.8.3 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_interface flutter meta]
- cloud_functions 4.3.4 [cloud_functions_platform_interface cloud_functions_web firebase_core firebase_core_platform_interface flutter]
- collection 1.17.1
- connectivity_plus 4.0.1 [flutter flutter_web_plugins connectivity_plus_platform_interface js meta nm]
- country_code_picker 3.0.0 [flutter collection]
- country_icons 2.0.2 [flutter]
- cupertino_icons 1.0.5
- dartx 1.1.0 [characters collection crypto meta path time]
- date_format 2.0.7
- device_info 2.0.3 [flutter device_info_platform_interface]
- devicelocale 0.6.0 [flutter flutter_web_plugins]
- easy_localization 3.0.2 [flutter shared_preferences intl args path easy_logger flutter_localizations]
- email_validator 2.1.17
- firebase_analytics 10.4.4 [firebase_analytics_platform_interface firebase_analytics_web firebase_core firebase_core_platform_interface flutter]
- firebase_auth 4.7.1 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 2.15.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_crashlytics 3.3.4 [firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface flutter stack_trace]
- firebase_dynamic_links 5.3.4 [firebase_core firebase_core_platform_interface firebase_dynamic_links_platform_interface flutter meta plugin_platform_interface]
- firebase_messaging 14.6.5 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- firebase_storage 11.2.5 [firebase_core firebase_core_platform_interface firebase_storage_platform_interface firebase_storage_web flutter]
- flutter 0.0.0 [characters collection js material_color_utilities meta vector_math sky_engine]
- flutter_appauth 6.0.1 [flutter flutter_appauth_platform_interface]
- flutter_background_geolocation 4.11.1 [flutter collection background_fetch]
- flutter_keyboard_visibility 5.4.1 [meta flutter_keyboard_visibility_platform_interface flutter_keyboard_visibility_linux flutter_keyboard_visibility_macos flutter_keyboard_visibility_web flutter_keyboard_visibility_windows flutter]
- flutter_libphonenumber 2.1.4 [flutter flutter_libphonenumber_android flutter_libphonenumber_ios flutter_libphonenumber_platform_interface flutter_libphonenumber_web]
- flutter_localizations 0.0.0 [flutter intl characters clock collection js material_color_utilities meta path vector_math]
- flutter_secure_storage 8.0.0 [flutter flutter_secure_storage_linux flutter_secure_storage_macos flutter_secure_storage_platform_interface flutter_secure_storage_web flutter_secure_storage_windows meta]
- flutter_slidable 3.0.0 [flutter]
- flutter_spinkit 5.2.0 [flutter]
- flutter_svg 2.0.7 [flutter vector_graphics vector_graphics_codec vector_graphics_compiler]
- flutter_touch_spin 2.0.0 [flutter intl]
- get_it 7.6.0 [async collection]
- google_maps_flutter 2.3.1 [flutter google_maps_flutter_android google_maps_flutter_ios google_maps_flutter_platform_interface google_maps_flutter_web]
- google_mlkit_commons 0.5.0 [flutter]
- google_mlkit_face_detection 0.8.0 [flutter google_mlkit_commons]
- hive 2.2.3 [meta crypto]
- hive_flutter 1.1.0 [flutter hive path_provider path]
- http 1.1.0 [async http_parser meta]
- http_parser 4.0.2 [collection source_span string_scanner typed_data]
- image_cropper 5.0.0 [flutter image_cropper_platform_interface image_cropper_for_web]
- image_picker 1.0.1 [flutter image_picker_android image_picker_for_web image_picker_ios image_picker_linux image_picker_macos image_picker_platform_interface image_picker_windows]
- intl 0.18.1 [clock meta path]
- json_annotation 4.8.1 [meta]
- latlong2 0.9.0 [intl]
- meta 1.9.1
- package_info_plus 4.0.2 [ffi flutter flutter_web_plugins http meta path package_info_plus_platform_interface win32]
- page_transition 2.0.9 [flutter]
- path 1.8.3
- path_provider 2.0.15 [flutter path_provider_android path_provider_foundation path_provider_linux path_provider_platform_interface path_provider_windows]
- percent_indicator 4.2.3 [flutter]
- permission_handler 10.4.3 [flutter meta permission_handler_android permission_handler_apple permission_handler_windows permission_handler_platform_interface]
- petitparser 5.4.0 [meta]
- pin_code_fields 8.0.1 [flutter]
- provider 6.0.5 [collection flutter nested]
- quiver 3.2.1 [matcher]
- retry 3.1.2
- rflutter_alert 2.0.7 [flutter]
- rxdart 0.27.7
- shared_preferences 2.2.0 [flutter shared_preferences_android shared_preferences_foundation shared_preferences_linux shared_preferences_platform_interface shared_preferences_web shared_preferences_windows]
- sms_autofill 2.3.0 [pin_input_text_field flutter]
- solid_bottom_sheet 0.1.10 [flutter]
- synchronized 3.1.0
- timeago 3.5.0 [intl]
- timezone 0.9.2 [path]
- tuple 2.0.2
- uni_links 0.5.1 [flutter uni_links_platform_interface uni_links_web]
- url_launcher 6.1.12 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- webview_flutter 4.2.2 [flutter webview_flutter_android webview_flutter_platform_interface webview_flutter_wkwebview]

dev dependencies:
- analyzer 6.0.0 [_fe_analyzer_shared collection convert crypto glob meta package_config path pub_semver source_span watcher yaml]
- build_resolvers 2.2.1 [analyzer async build collection crypto graphs logging package_config path pool pub_semver stream_transform yaml]
- build_runner 2.4.6 [analyzer args async build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style frontend_server_client glob graphs http_multi_server io js logging meta mime package_config path pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web_socket_channel yaml]
- flutter_driver 0.0.0 [file flutter flutter_test fuchsia_remote_debug_protocol path meta vm_service webdriver async boolean_selector characters clock collection js matcher material_color_utilities platform process source_span stack_trace stream_channel string_scanner sync_http term_glyph test_api vector_math]
- flutter_launcher_icons 0.13.1 [args checked_yaml cli_util image json_annotation path yaml]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters collection js matcher material_color_utilities meta source_span stream_channel string_scanner term_glyph]
- hive_generator 2.0.0 [build source_gen hive analyzer source_helper]
- integration_test 0.0.0 [flutter flutter_driver flutter_test path vm_service async boolean_selector characters clock collection fake_async file js matcher material_color_utilities meta source_span stack_trace stream_channel string_scanner sync_http term_glyph test_api vector_math webdriver]
- lints 2.1.1
- mockito 5.4.2 [analyzer build code_builder collection dart_style matcher meta path source_gen test_api]
- test 1.24.4 [analyzer async boolean_selector collection coverage http_multi_server io js matcher node_preamble package_config path pool shelf shelf_packages_handler shelf_static shelf_web_socket source_span stack_trace stream_channel test_api test_core typed_data web_socket_channel webkit_inspection_protocol yaml]

dependency overrides:
- analyzer 6.0.0 [_fe_analyzer_shared collection convert crypto glob meta package_config path pub_semver source_span watcher yaml]
- intl 0.18.1 [clock meta path]
- matcher 0.12.16 [async meta stack_trace term_glyph test_api]
- test 1.24.4 [analyzer async boolean_selector collection coverage http_multi_server io js matcher node_preamble package_config path pool shelf shelf_packages_handler shelf_static shelf_web_socket source_span stack_trace stream_channel test_api test_core typed_data web_socket_channel webkit_inspection_protocol yaml]
- test_api 0.5.2 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]

transitive dependencies:
- _fe_analyzer_shared 62.0.0 [dart_internal meta]
- _flutterfire_internals 1.3.4 [collection firebase_core firebase_core_platform_interface flutter meta]
- archive 3.3.7 [crypto path pointycastle]
- args 2.4.2
- async 2.11.0 [collection meta]
- battery_plus_platform_interface 1.2.2 [flutter meta plugin_platform_interface]
- boolean_selector 2.1.1 [source_span string_scanner]
- build 2.4.1 [analyzer async convert crypto glob logging meta package_config path]
- build_config 1.1.1 [checked_yaml json_annotation path pubspec_parse yaml]
- build_daemon 4.0.0 [built_collection built_value http_multi_server logging path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_runner_core 7.2.10 [async build build_config build_resolvers collection convert crypto glob graphs json_annotation logging meta package_config path pool timing watcher yaml]
- built_collection 5.1.1
- built_value 8.6.1 [built_collection collection fixnum meta]
- cached_network_image_platform_interface 2.0.0 [flutter flutter_cache_manager]
- cached_network_image_web 1.0.2 [flutter flutter_cache_manager cached_network_image_platform_interface]
- camera_android 0.10.8+3 [camera_platform_interface flutter flutter_plugin_android_lifecycle stream_transform]
- camera_avfoundation 0.9.13+2 [camera_platform_interface flutter stream_transform]
- camera_platform_interface 2.5.1 [cross_file flutter plugin_platform_interface stream_transform]
- camera_web 0.3.1+4 [camera_platform_interface flutter flutter_web_plugins stream_transform]
- characters 1.3.0
- checked_yaml 2.0.3 [json_annotation source_span yaml]
- cli_util 0.4.0 [meta path]
- clock 1.1.1
- cloud_firestore_platform_interface 5.15.3 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 3.6.3 [_flutterfire_internals cloud_firestore_platform_interface collection firebase_core firebase_core_web flutter flutter_web_plugins js]
- cloud_functions_platform_interface 5.4.4 [firebase_core flutter meta plugin_platform_interface]
- cloud_functions_web 4.5.4 [cloud_functions_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- code_builder 4.5.0 [built_collection built_value collection matcher meta]
- connectivity_plus_platform_interface 1.2.4 [flutter meta plugin_platform_interface]
- convert 3.1.1 [typed_data]
- coverage 1.6.3 [args logging package_config path source_maps stack_trace vm_service]
- cross_file 0.3.3+4 [js meta]
- crypto 3.0.3 [typed_data]
- csslib 1.0.0 [source_span]
- dart_internal 0.2.8
- dart_style 2.3.2 [analyzer args path pub_semver source_span]
- dbus 0.7.8 [args ffi meta xml]
- device_info_platform_interface 2.0.1 [flutter meta plugin_platform_interface]
- easy_logger 0.0.2 [flutter]
- fake_async 1.3.1 [clock collection]
- ffi 2.0.2
- file 6.1.4 [meta path]
- file_selector_linux 0.9.2 [cross_file file_selector_platform_interface flutter]
- file_selector_macos 0.9.3+1 [cross_file file_selector_platform_interface flutter]
- file_selector_platform_interface 2.6.0 [cross_file flutter http plugin_platform_interface]
- file_selector_windows 0.9.3 [cross_file file_selector_platform_interface flutter]
- firebase_analytics_platform_interface 3.6.4 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_analytics_web 0.5.4+4 [_flutterfire_internals firebase_analytics_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- firebase_auth_platform_interface 6.16.0 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 5.6.1 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser js meta]
- firebase_core_platform_interface 4.8.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.6.0 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_crashlytics_platform_interface 3.6.4 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_dynamic_links_platform_interface 0.2.6+4 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_platform_interface 4.5.4 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 3.5.4 [_flutterfire_internals firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]
- firebase_storage_platform_interface 4.4.4 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_storage_web 3.6.5 [_flutterfire_internals async firebase_core firebase_core_web firebase_storage_platform_interface flutter flutter_web_plugins http js meta]
- fixnum 1.1.0
- flutter_appauth_platform_interface 6.0.0 [flutter plugin_platform_interface]
- flutter_blurhash 0.7.0 [flutter]
- flutter_cache_manager 3.3.1 [clock collection file flutter http path path_provider rxdart sqflite uuid]
- flutter_keyboard_visibility_linux 1.0.0 [flutter_keyboard_visibility_platform_interface flutter]
- flutter_keyboard_visibility_macos 1.0.0 [flutter_keyboard_visibility_platform_interface flutter]
- flutter_keyboard_visibility_platform_interface 2.0.0 [flutter meta plugin_platform_interface]
- flutter_keyboard_visibility_web 2.0.0 [flutter_keyboard_visibility_platform_interface flutter_web_plugins flutter]
- flutter_keyboard_visibility_windows 1.0.0 [flutter_keyboard_visibility_platform_interface flutter]
- flutter_libphonenumber_android 1.0.1 [flutter flutter_libphonenumber_platform_interface]
- flutter_libphonenumber_ios 1.1.3 [flutter flutter_libphonenumber_platform_interface]
- flutter_libphonenumber_platform_interface 1.0.0 [flutter plugin_platform_interface]
- flutter_libphonenumber_web 1.0.0 [flutter flutter_web_plugins flutter_libphonenumber_platform_interface js]
- flutter_plugin_android_lifecycle 2.0.15 [flutter]
- flutter_secure_storage_linux 1.1.3 [flutter flutter_secure_storage_platform_interface]
- flutter_secure_storage_macos 3.0.0 [flutter flutter_secure_storage_platform_interface]
- flutter_secure_storage_platform_interface 1.0.1 [flutter plugin_platform_interface]
- flutter_secure_storage_web 1.1.1 [flutter flutter_secure_storage_platform_interface flutter_web_plugins js]
- flutter_secure_storage_windows 2.0.0 [flutter flutter_secure_storage_platform_interface]
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta vector_math]
- frontend_server_client 3.2.0 [async path]
- fuchsia_remote_debug_protocol 0.0.0 [process vm_service file meta path platform]
- glob 2.1.2 [async collection file path string_scanner]
- google_maps 6.3.0 [js js_wrapping meta]
- google_maps_flutter_android 2.4.15 [flutter flutter_plugin_android_lifecycle google_maps_flutter_platform_interface stream_transform]
- google_maps_flutter_ios 2.2.3 [flutter google_maps_flutter_platform_interface stream_transform]
- google_maps_flutter_platform_interface 2.3.0 [collection flutter plugin_platform_interface stream_transform]
- google_maps_flutter_web 0.5.1 [flutter flutter_web_plugins google_maps google_maps_flutter_platform_interface sanitize_html stream_transform]
- graphs 2.3.1 [collection]
- html 0.15.4 [csslib source_span]
- http_multi_server 3.2.1 [async]
- image 4.0.17 [archive meta xml]
- image_cropper_for_web 3.0.0 [flutter flutter_web_plugins image_cropper_platform_interface js]
- image_cropper_platform_interface 5.0.0 [flutter plugin_platform_interface http]
- image_picker_android 0.8.7+3 [flutter flutter_plugin_android_lifecycle image_picker_platform_interface]
- image_picker_for_web 2.2.0 [flutter flutter_web_plugins image_picker_platform_interface mime]
- image_picker_ios 0.8.8 [flutter image_picker_platform_interface]
- image_picker_linux 0.2.1 [file_selector_linux file_selector_platform_interface flutter image_picker_platform_interface]
- image_picker_macos 0.2.1 [file_selector_macos file_selector_platform_interface flutter image_picker_platform_interface]
- image_picker_platform_interface 2.8.0 [cross_file flutter http plugin_platform_interface]
- image_picker_windows 0.2.1 [file_selector_platform_interface file_selector_windows flutter image_picker_platform_interface]
- io 1.0.4 [meta path string_scanner]
- js 0.6.7 [meta]
- js_wrapping 0.7.4 [js]
- logging 1.2.0
- material_color_utilities 0.2.0
- mime 1.0.4
- nested 1.0.0 [flutter]
- nm 0.5.0 [dbus]
- node_preamble 2.0.2
- octo_image 1.0.2 [flutter flutter_blurhash]
- package_config 2.1.0 [path]
- package_info_plus_platform_interface 2.0.1 [flutter meta plugin_platform_interface]
- path_parsing 1.0.1 [vector_math meta]
- path_provider_android 2.0.27 [flutter path_provider_platform_interface]
- path_provider_foundation 2.2.4 [flutter path_provider_platform_interface]
- path_provider_linux 2.1.11 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_platform_interface 2.0.6 [flutter platform plugin_platform_interface]
- path_provider_windows 2.1.7 [ffi flutter path path_provider_platform_interface win32]
- permission_handler_android 10.3.2 [flutter permission_handler_platform_interface]
- permission_handler_apple 9.1.4 [flutter permission_handler_platform_interface]
- permission_handler_platform_interface 3.11.3 [flutter meta plugin_platform_interface]
- permission_handler_windows 0.1.3 [flutter permission_handler_platform_interface]
- pin_input_text_field 4.5.1 [flutter]
- platform 3.1.0
- plugin_platform_interface 2.1.4 [meta]
- pointycastle 3.7.3 [collection convert js]
- pool 1.5.1 [async stack_trace]
- process 4.2.4 [file path platform]
- pub_semver 2.1.4 [collection meta]
- pubspec_parse 1.2.3 [checked_yaml collection json_annotation pub_semver yaml]
- sanitize_html 2.0.0 [html meta]
- shared_preferences_android 2.2.0 [flutter shared_preferences_platform_interface]
- shared_preferences_foundation 2.3.2 [flutter shared_preferences_platform_interface]
- shared_preferences_linux 2.3.0 [file flutter path path_provider_linux path_provider_platform_interface shared_preferences_platform_interface]
- shared_preferences_platform_interface 2.3.0 [flutter plugin_platform_interface]
- shared_preferences_web 2.2.0 [flutter flutter_web_plugins shared_preferences_platform_interface]
- shared_preferences_windows 2.3.0 [file flutter path path_provider_platform_interface path_provider_windows shared_preferences_platform_interface]
- shelf 1.4.1 [async collection http_parser path stack_trace stream_channel]
- shelf_packages_handler 3.0.2 [path shelf shelf_static]
- shelf_static 1.1.2 [convert http_parser mime path shelf]
- shelf_web_socket 1.0.4 [shelf stream_channel web_socket_channel]
- sky_engine 0.0.99
- source_gen 1.4.0 [analyzer async build dart_style glob path source_span yaml]
- source_helper 1.3.4 [analyzer collection source_gen]
- source_map_stack_trace 2.1.1 [path source_maps stack_trace]
- source_maps 0.10.12 [source_span]
- source_span 1.9.1 [collection path term_glyph]
- sqflite 2.2.8+4 [flutter sqflite_common path]
- sqflite_common 2.4.5+1 [synchronized path meta]
- stack_trace 1.11.0 [path]
- stream_channel 2.1.1 [async]
- stream_transform 2.1.0
- string_scanner 1.2.0 [source_span]
- sync_http 0.3.1
- term_glyph 1.2.1
- test_core 0.5.4 [analyzer args async boolean_selector collection coverage frontend_server_client glob io meta package_config path pool source_map_stack_trace source_maps source_span stack_trace stream_channel test_api vm_service yaml]
- time 2.1.3 [clock]
- timing 1.0.1 [json_annotation]
- typed_data 1.3.2 [collection]
- uni_links_platform_interface 1.0.0 [flutter plugin_platform_interface]
- uni_links_web 0.1.0 [flutter flutter_web_plugins uni_links_platform_interface]
- upower 0.7.0 [dbus]
- url_launcher_android 6.0.36 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.1.4 [flutter url_launcher_platform_interface]
- url_launcher_linux 3.0.5 [flutter url_launcher_platform_interface]
- url_launcher_macos 3.0.6 [flutter url_launcher_platform_interface]
- url_launcher_platform_interface 2.1.3 [flutter plugin_platform_interface]
- url_launcher_web 2.0.18 [flutter flutter_web_plugins url_launcher_platform_interface]
- url_launcher_windows 3.0.7 [flutter url_launcher_platform_interface]
- uuid 3.0.7 [crypto]
- vector_graphics 1.1.7 [flutter vector_graphics_codec]
- vector_graphics_codec 1.1.7
- vector_graphics_compiler 1.1.7 [args meta path_parsing xml vector_graphics_codec]
- vector_math 2.1.4
- vm_service 11.3.0
- watcher 1.1.0 [async path]
- web_socket_channel 2.4.0 [async crypto stream_channel]
- webdriver 3.0.2 [matcher path stack_trace sync_http]
- webkit_inspection_protocol 1.2.0 [logging]
- webview_flutter_android 3.9.0 [flutter webview_flutter_platform_interface]
- webview_flutter_platform_interface 2.4.0 [flutter meta plugin_platform_interface]
- webview_flutter_wkwebview 3.7.0 [flutter path webview_flutter_platform_interface]
- win32 4.1.4 [ffi]
- xdg_directories 1.0.1 [meta path]
- xml 6.3.0 [collection meta petitparser]
- yaml 3.1.2 [collection source_span string_scanner]

```

</details>

---

**Comment by danagbemava-nc** [comment] 2023-07-18 10:31
I can reproduce the crash using the plugin sample code and adding a call on the profile page to call user.getIdToken(true); 

```
 TextButton(
                        onPressed: () async {
                         final token =  await user.getIdToken(true);

                         print("token: $token");
                        },
                        child: const Text('Get Id Token'),
                      ),
```

<details>
<summary>logs</summary>

```
Launching lib/main.dart on Pixel 7 in debug mode...
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
Connecting to VM Service at ws://127.0.0.1:58564/c0yEFi39N_I=/ws
I/se.auth.example(30939): Compiler allocated 4413KB to compile void android.view.ViewRootImpl.performTraversals()
E/BasicMessageChannel#dev.flutter.pigeon.FirebaseAuthUserHostApi.getIdToken(30939): Failed to handle message
E/BasicMessageChannel#dev.flutter.pigeon.FirebaseAuthUserHostApi.getIdToken(30939): java.lang.IllegalStateException: Task is not yet complete
E/BasicMessageChannel#dev.flutter.pigeon.FirebaseAuthUserHostApi.getIdToken(30939): 	at com.google.android.gms.common.internal.Preconditions.checkState(com.google.android.gms:play-services-basement@@18.2.0:2)
E/BasicMessageChannel#dev.flutter.pigeon.FirebaseAuthUserHostApi.getIdToken(30939): 	at com.google.android.gms.tasks.zzw.zzf(com.google.android.gms:play-services-tasks@@18.0.2:1)
E/BasicMessageChannel#dev.flutter.pigeon.FirebaseAuthUserHostApi.getIdToken(30939): 	at com.google.android.gms.tasks.zzw.getResult(com.google.android.gms:play-services-tasks@@18.0.2:1)
E/BasicMessageChannel#dev.flutter.pigeon.FirebaseAuthUserHostApi.getIdToken(30939): 	at io.flutter.plugins.firebase.auth.FlutterFirebaseAuthUser.getIdToken(FlutterFirebaseAuthUser.java:95)
E/BasicMessageChannel#dev.flutter.pigeon.FirebaseAuthUserHostApi.getIdToken(30939): 	at io.flutter.plugins.firebase.auth.GeneratedAndroidFirebaseAuth$FirebaseAuthUserHostApi$-CC.lambda$setup$1(GeneratedAndroidFirebaseAuth.java:3256)
E/BasicMessageChannel#dev.flutter.pigeon.FirebaseAuthUserHostApi.getIdToken(30939): 	at io.flutter.plugins.firebase.auth.GeneratedAndroidFirebaseAuth$FirebaseAuthUserHostApi$$ExternalSyntheticLambda9.onMessage(Unknown Source:2)
E/BasicMessageChannel#dev.flutter.pigeon.FirebaseAuthUserHostApi.getIdToken(30939): 	at io.flutter.plugin.common.BasicMessageChannel$IncomingMessageHandler.onMessage(BasicMessageChannel.java:217)
E/BasicMessageChannel#dev.flutter.pigeon.FirebaseAuthUserHostApi.getIdToken(30939): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/BasicMessageChannel#dev.flutter.pigeon.FirebaseAuthUserHostApi.getIdToken(30939): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/BasicMessageChannel#dev.flutter.pigeon.FirebaseAuthUserHostApi.getIdToken(30939): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/BasicMessageChannel#dev.flutter.pigeon.FirebaseAuthUserHostApi.getIdToken(30939): 	at android.os.Handler.handleCallback(Handler.java:942)
E/BasicMessageChannel#dev.flutter.pigeon.FirebaseAuthUserHostApi.getIdToken(30939): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/BasicMessageChannel#dev.flutter.pigeon.FirebaseAuthUserHostApi.getIdToken(30939): 	at android.os.Looper.loopOnce(Looper.java:201)
E/BasicMessageChannel#dev.flutter.pigeon.FirebaseAuthUserHostApi.getIdToken(30939): 	at android.os.Looper.loop(Looper.java:288)
E/BasicMessageChannel#dev.flutter.pigeon.FirebaseAuthUserHostApi.getIdToken(30939): 	at android.app.ActivityThread.main(ActivityThread.java:7918)
E/BasicMessageChannel#dev.flutter.pigeon.FirebaseAuthUserHostApi.getIdToken(30939): 	at java.lang.reflect.Method.invoke(Native Method)
E/BasicMessageChannel#dev.flutter.pigeon.FirebaseAuthUserHostApi.getIdToken(30939): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/BasicMessageChannel#dev.flutter.pigeon.FirebaseAuthUserHostApi.getIdToken(30939): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
E/flutter (30939): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: [firebase_auth/channel-error] Unable to establish connection on channel.
E/flutter (30939): #0      FirebaseAuthUserHostApi.getIdToken
E/flutter (30939): <asynchronous suspension>
E/flutter (30939): #1      MethodChannelUser.getIdToken
E/flutter (30939): <asynchronous suspension>
E/flutter (30939): #2      _ProfilePageState.build.<anonymous closure>
E/flutter (30939): <asynchronous suspension>
E/flutter (30939):
W/System  (30939): Ignoring header X-Firebase-Locale because its value was null.
D/TrafficStats(30939): tagSocket(133) with statsTag=0xffffffff, statsUid=-1
D/FirebaseAuth(30939): Notifying id token listeners about user ( NviciwXJrjXbznzWDgSbdwT3Tt63 ).
D/AndroidRuntime(30939): Shutting down VM
E/AndroidRuntime(30939): FATAL EXCEPTION: main
E/AndroidRuntime(30939): Process: io.flutter.plugins.firebase.auth.example, PID: 30939
E/AndroidRuntime(30939): java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime(30939): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:435)
E/AndroidRuntime(30939): 	at io.flutter.plugin.common.BasicMessageChannel$IncomingMessageHandler$1.reply(BasicMessageChannel.java:222)
E/AndroidRuntime(30939): 	at io.flutter.plugins.firebase.auth.GeneratedAndroidFirebaseAuth$FirebaseAuthUserHostApi$2.success(GeneratedAndroidFirebaseAuth.java:3247)
E/AndroidRuntime(30939): 	at io.flutter.plugins.firebase.auth.GeneratedAndroidFirebaseAuth$FirebaseAuthUserHostApi$2.success(GeneratedAndroidFirebaseAuth.java:3244)
E/AndroidRuntime(30939): 	at io.flutter.plugins.firebase.auth.FlutterFirebaseAuthUser.lambda$getIdToken$1(FlutterFirebaseAuthUser.java:88)
E/AndroidRuntime(30939): 	at io.flutter.plugins.firebase.auth.FlutterFirebaseAuthUser$$ExternalSyntheticLambda2.onComplete(Unknown Source:2)
E/AndroidRuntime(30939): 	at com.google.android.gms.tasks.zzi.run(com.google.android.gms:play-services-tasks@@18.0.2:1)
E/AndroidRuntime(30939): 	at android.os.Handler.handleCallback(Handler.java:942)
E/AndroidRuntime(30939): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(30939): 	at android.os.Looper.loopOnce(Looper.java:201)
E/AndroidRuntime(30939): 	at android.os.Looper.loop(Looper.java:288)
E/AndroidRuntime(30939): 	at android.app.ActivityThread.main(ActivityThread.java:7918)
E/AndroidRuntime(30939): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(30939): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/AndroidRuntime(30939): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
I/Process (30939): Sending signal. PID: 30939 SIG: 9
Lost connection to device.
Exited
```
</details>

/cc @Lyokone

**Comment by danagbemava-nc** [comment] 2023-07-18 10:38
Turns out there's an existing issue tracking this in https://github.com/firebase/flutterfire/issues/11297. 

Closing from here as duplicate.

**Closed by danagbemava-nc** 2023-07-18 10:38 UTC
Labels: type: bug, plugin: auth, platform: android, type: crash
