### ISSUE TITLE
I cant use sms authentication after turn on app check and play integrity 

### ISSUE THREAD

**Issue by snosey** [firebase/flutterfire#10467] opened 2023-02-16 09:47 UTC
I cant user sms authentication after turn on app check and play integrity 
everything was working well, but after turn it on alwayes give me error of missing client identifier.

i had added sha1 & 256 from play console to firebase and 
problem still exist. 
please i need help because app is already published 

![WhatsApp Image 2023-02-16 at 2 40 27 AM](https://user-images.githubusercontent.com/11752936/219329539-e4d2c6c4-eb5d-4c1f-84e8-a1eb1c7a907c.jpeg)

**Comment by snosey** [comment] 2023-02-16 09:59
also i tried to enable saftey net and get this error , although i am the owner of project !
<img width="1152" alt="Screenshot 2023-02-16 at 11 58 28 AM" src="https://user-images.githubusercontent.com/11752936/219332668-51503ad6-3626-4c25-896b-91ced1a5093f.png">

**Comment by darshankawar** [comment] 2023-02-16 11:11
@snosey 
Can you provide complete error log in properly formatted text ? Please avoid posting screenshots.
Also, which device are you seeing this error on ? Does it have Google play services enabled ?

From the above screenshot, have you enabled SafetyNet instead of Play integrity ?

**Comment by snosey** [comment] 2023-02-16 11:17
i cant enable safteyNet , keep telling me you are not the owner ￼



and thats is error which show for the user
￼

altough i have enabled play integrity and put SHA1 & 256 in firebase console from google play

￼

￼

i cant solve the problem :( please help me

**Comment by snosey** [comment] 2023-02-16 11:21
sorry about screenshot, but to understand the problem because i cant solve it for 48 hours. and users cant signup

**Comment by darshankawar** [comment] 2023-02-17 11:18
> Can you provide complete error log in properly formatted text ? 
> Also, which device are you seeing this error on ? Does it have Google play services enabled ?

Please provide these details.

**Comment by snosey** [comment] 2023-02-17 11:20
Error is:[firebase_auth/missing-client-identifier] This request is missing a valid app identifier, 
 meaning that neither SafetyNet checks nor reCAPTCHA checks succeeded. 
 Please try again, or check the logcat for more details.

although they have
Google play services enabled

**Comment by sarasini** [comment] 2023-02-17 11:54
I have the same problem: I cant enable safteyNet, Firebase keep telling me I'm not the owner

**Comment by darshankawar** [comment] 2023-02-21 09:03
I am going ahead and labeling this for team's attention for expected behavior. A similar issue that was reported earlier: https://github.com/firebase/flutterfire/issues/10174

/cc @Lyokone for thoughts.

**Comment by santa112358** [comment] 2023-02-23 06:45
Same. There's no way to avoid reCAPTCHA in new firebase project.

**Comment by OziTFA** [comment] 2023-02-27 20:20
SafetyNet migration deadline was June 2023 [https://developer.android.com/training/safetynet/deprecation-timeline](about) Is it related with this ?

**Comment by mihir-concetto** [comment] 2023-03-01 09:54
> Error is:[firebase_auth/missing-client-identifier] This request is missing a valid app identifier, meaning that neither SafetyNet checks nor reCAPTCHA checks succeeded. Please try again, or check the logcat for more details.
> 
> although they have Google play services enabled

Please add your play console SHA1 and SHA256 in Project Setting and in Play Integrity

**Comment by OziTFA** [comment] 2023-03-01 10:01
> 

both added, still same for me

**Comment by nicks258** [comment] 2023-03-02 14:22
Same for me tried each and every solution enabling `Play App check` `Google Play Integrity API` adding SHA256 and SHA1 keys to firebase console but still seeing reCAPTCHA screen Please help we have a release ahead.

**Comment by hed5meg** [comment] 2023-03-06 04:59
I'm in the same boat. Can't release because SafetyNet is deprecated and I CANNOT enable it for my project, but it is required to avoid the reCAPTCHA screen. Please help!

**Comment by russellwheatley** [comment] 2023-03-07 15:09
Hey @snosey, are you sure you've added the SHA-1 & SHA-256 key for debug **and** release mode to the app in your Firebase console? That would be the first port of call.

Have you also enabled "Android Device Verification" in your google console (GCP)? If not, please enable, and re-download your android service file, replace the existing one, run `flutter clean` & rebuild app.

**Comment by tangsongjun** [comment] 2023-03-09 03:39
I hava the same error
  com.google.firebase.auth.FirebaseAuthException: This request is missing a valid app identifier, meaning that neither SafetyNet checks nor reCAPTCHA checks succeeded. Please try again, or check the logcat for more details.
        at com.google.android.gms.internal.firebase-auth-api.zzxc.zza(com.google.firebase:firebase-auth@@21.1.0:28)
        at com.google.android.gms.internal.firebase-auth-api.zzxw.zza(com.google.firebase:firebase-auth@@21.1.0:1)
        at com.google.android.gms.internal.firebase-auth-api.zzxx.run(com.google.firebase:firebase-auth@@21.1.0:3)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7870)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

**Comment by OziTFA** [comment] 2023-03-09 07:22
@russellwheatley there is no any "Android Device Verification" API service in GCP, it is removed. Also adding SHA-1 & SHA-256 not working as well

**Comment by russellwheatley** [comment] 2023-03-09 10:54
@OziTFA 
<img width="1480" alt="Screenshot 2023-03-09 at 10 41 49" src="https://user-images.githubusercontent.com/16018629/224000325-f6e4ec9d-5494-47eb-87ea-e0d6259f6cef.png">

It is deprecated, not removed. [See documentation](https://firebase.google.com/docs/auth/android/phone-auth#enable-app-verification)

Quote:
> In the Google Cloud Console, enable the [Android Device Verification (DEPRECATED) API](https://console.cloud.google.com/apis/library/androidcheck.googleapis.com) for your project. The default Firebase API Key will be used, and needs to be allowed to access the DeviceCheck API.

**Comment by OziTFA** [comment] 2023-03-09 11:26
@russellwheatley 
![ss](https://user-images.githubusercontent.com/77070056/224009806-258f5f97-9d32-4462-bd18-d000355cfa54.png)

**Comment by sivaprasadnk** [comment] 2023-03-09 11:47
Firebase sms authentication not working ( no otp sending)  as device verification api is deprecated . What's the solution to this?

**Comment by meshivanshsinghh** [comment] 2023-03-16 06:33
any idea regarding this? same for me too

**Comment by sachin3072004** [comment] 2023-03-25 06:36
I have enabled the play integrity and added SHA-1 and SHA-256. But I am getting the following error on android device. **[Error: [auth/missing-client-identifier] This request is missing a valid app identifier, meaning that neither SafetyNet checks nor reCAPTCHA checks succeeded.**

**Comment by Lyokone** [comment] 2023-03-31 08:27
Can you check with the latest version of firebase_core 2.9.0. It contains fixes on the Android Native side that could fix this.

**Comment by renttooApp** [comment] 2023-04-15 14:35
still not working

**Comment by AndrewTran2018** [comment] 2023-04-26 04:18
I'm integrating Play Integrity into my firebase app. And facing "This request is missing a valid app identifier, meaning that Play Integrity checks, SafetyNet checks, and reCAPTCHA checks were unsuccessful"

please help.

**Comment by AndrewTran2018** [comment] 2023-04-26 04:19
> I'm integrating Play Integrity into my firebase app. And facing "This request is missing a valid app identifier, meaning that Play Integrity checks, SafetyNet checks, and reCAPTCHA checks were unsuccessful"
> 
> please help.

My app is using SMS phone to verify login

**Comment by MujibBasha** [comment] 2023-05-14 02:23
I have enabled the play integrity and added SHA-1 and SHA-256. But I am getting the following error on android device. [Error: [auth/missing-client-identifier] This request is missing a valid app identifier, meaning that neither SafetyNet checks nor reCAPTCHA checks succeeded.

**Comment by MujibBasha** [comment] 2023-05-14 02:45
any idea regarding this?

**Comment by zyruva** [comment] 2023-05-18 09:19
My app was working perfectly until a few days ago (we havent made any changes to it) the phone auth stopped working and im getting a "Vertification failed: (missing-client-identifier): This request is missing a valid app identifier, meaning that Play Integrity checks, and reCAPTCHA checks were unsuccessful. Please try again, or check the logcat for more details." message.
I have everything updated, all flutter firebase packages are updated to the latest versions (i have seen some dependencies have been updated like firebase_auth_platform_interface)
All my debug, release SHA-1 & SHA-2 from my local machine and from Google Play are added to my project settings for that specific app + App Check
The phone auth works well when debugging on an emulator, but as soon as i debug on a physical device or use a release version, it doesnt work.
Any solution to this now ? and how can this suddenly occur if there were no changes made to the app ? are there some breaking changes on Firebase side ?

**Comment by shadysamir** [comment] 2023-05-25 11:17
I am getting recaptcha on Android and iOS since I enabled appcheck (not enforced) and migrated to Play Integrity and Identity Platform

**Comment by imanamirshah** [comment] 2023-06-15 17:38
Facing the same issue for phone auth. The following error appears on console when trying to log in via emulator. This request is missing a valid app identifier, meaning that Play Integrity checks, and reCAPTCHA checks were unsuccessful. Added SHA-1 and SHA-256 keys from Google Play Console and appSigning to firebase but error still occurs. Any one knows how to get around it?

**Comment by andberto** [comment] 2023-07-09 15:02
@imanamirshah i'm facing the same issue, did you manage to solve it?

**Comment by ishitgami** [comment] 2023-07-10 06:12
@andberto find any solution?

**Comment by andberto** [comment] 2023-07-12 13:41
@ishitgami no, no clue how to solve this issue

**Comment by pipboy9000** [comment] 2023-07-18 08:04
Also getting this, bump

**Comment by duduBaiao** [comment] 2023-07-19 13:23
This is happening to me as well, on a new project.

My old project, which still has the "Android Device Verification" enabled, is working fine.

**Comment by duduBaiao** [comment] 2023-07-19 14:30
I was able to get around this issue by unprotecting my API key, which everybody knows is not advisable. 🤷‍♂️

**Comment by sushantdhumal** [comment] 2023-07-20 11:45
I am facing similar issue but my scenario is different. Everything works fine for me when user downloads app from playstore and logs in (I am using phone auth. Play integrity API and app check is enabled). But when user logs out and tries to login again, 

> This request is missing a valid app identifier, meaning that Play Integrity checks, and reCAPTCHA checks were unsuccessful.

 this error occurs. Uses has to uninstall app and install again from play store to login again. Please help

I am calling `FirebaseAuth.instance.signOut()` on log out button.

**Comment by Juniorlpes** [comment] 2023-07-24 15:06
> snosey
I had missing-client-identifier when I setted
`FirebaseAuth.instance
          ..setSettings(
            appVerificationDisabledForTesting: true,
          ),`

**Comment by yasinByasin** [comment] 2023-08-08 11:24
still facing the same issue 
this request is missing a valid app identifier, meaning that play safetynet checks

**Comment by yasinByasin** [comment] 2023-08-08 14:19
check if you are Enable reCAPTCHA Enterprise API

**Comment by yousefak007** [comment] 2023-09-08 18:29
> Same problem




I/PlayCore(27490): UID: [14368]  PID: [27490] IntegrityService : requestIntegrityToken(IntegrityTokenRequest{nonce=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx, cloudProjectNumber=xxxxxxxxxxxxx})
I/PlayCore(27490): UID: [14368]  PID: [27490] IntegrityService : Initiate binding to the service.
I/PlayCore(27490): UID: [14368]  PID: [27490] IntegrityService : ServiceConnectionImpl.onServiceConnected(ComponentInfo{com.android.vending/com.google.android.finsky.integrityservice.IntegrityService})
I/PlayCore(27490): UID: [14368]  PID: [27490] IntegrityService : linkToDeath
I/PlayCore(27490): UID: [14368]  PID: [27490] OnRequestIntegrityTokenCallback : onRequestIntegrityToken
I/PlayCore(27490): UID: [14368]  PID: [27490] IntegrityService : Unbind from service.
W/System  (27490): Ignoring header X-Firebase-Locale because its value was null.
2
I/System.out(27490): (HTTPLog)-Static: isSBSettingEnabled false





**E/FirebaseAuth(27490): [SmsRetrieverHelper] SMS verification code request failed: unknown status code: 18002 Invalid PlayIntegrity token; app not Recognized by Play Store.

D/FirebaseAuth(27490): Re-triggering phone verification with Recaptcha flow forced for phone number +967xxxxxxxxx**


I/zzf     (27490): ForceRecaptchaFlow from phoneAuthOptions = true, ForceRecaptchaFlow from firebaseSettings = false

W/JavaBinder(27490): BinderProxy is being destroyed but the application did not call unlinkToDeath to unlink all of its death recipients beforehand.  Releasing leaked death recipient: com.google.android.play.integrity.internal.n
I/zygote64(27490): Do full code cache collection, code=247KB, data=174KB
I/zygote64(27490): After code cache collection, code=238KB, data=144KB
W/System  (27490): Ignoring header X-Firebase-Locale because its value was null.
D/ViewRootImpl@756c5f5[RecaptchaActivity](27490): setView = DecorView@c11f8a[RecaptchaActivity] TM=true MM=false
D/ViewRootImpl@756c5f5[RecaptchaActivity](27490): dispatchAttachedToWindow


**E/FirebaseAuth(27490): [SmsRetrieverHelper] SMS verification code request failed: unknown status code: 17499 Error code:39
I/flutter (27490): [firebase_auth/unknown] An internal error has occurred. [ Error code:39 ]**

**Comment by Muitsu** [comment] 2023-09-19 07:40
Got the same problem here

E/FirebaseAuth( 2349): [SmsRetrieverHelper] SMS verification code request failed: unknown status code: 17093 null

[log] [firebase_auth/missing-client-identifier] This request is missing a valid app identifier, meaning that Play Integrity checks, and reCAPTCHA checks were unsuccessful. Please try again, or check the logcat for more details.

Need help :(

**Comment by AlexeyRottCr** [comment] 2023-09-28 13:29
Same problem. Encountered this issue

**Comment by softdevomar** [comment] 2023-09-30 04:06
This request is missing a valid app identifier, meaning that Play Integrity checks, and reCAPTCHA checks were unsuccessful. Please try again, or check the logcat for more details.
need help

**Comment by satishs22** [comment] 2023-10-01 22:56
I'm getting the same error, did anyone manage to find a solution for this?

**Comment by nehal076** [comment] 2023-10-11 05:16
I just created this new project and Authentication is by default integrated with the Identity Platform.
I have my app on Play Store but users are unable to authenticate with their phone number.
I have done all the required steps.

1. I have added SHA keys from Play Console to my project.
2. I have added my system SHA keys to my project.
3. I have added `implementation 'com.google.android.play:integrity:1.1.0'` in build.gradle file
4. I have enabled the Play Integrity API on Google Cloud Console.

I am getting the error: 
`This request is missing a valid app identifier, meaning that neither safetyNet checks nor reCAPTCHA checks succeeded`

**Comment by skylvsme** [comment] 2023-10-11 15:58
I've been experiencing this error during a long time of development of my application and now I'm able to tell how I resolved it 🎉.

First of all, I got the error in following conditions:
- Application is not released anywhere. It's just in development stage
- I have my backend deployed on Google Cloud Project corresponding to Firebase Project
- Firebase Project is set up with my Android app using FlutterFire CLI
- SHA256 fingerprint of debug key is set for both Play Integrity and SafetyNet
- Authentication is set for SMS
- Test phone numbers are added
- Versions of Flutter Firebase packages are:
```yaml
  firebase_core: ^2.16.0
  firebase_auth: ^4.10.0
  firebase_messaging: ^14.6.8
```
Authentication worked properly only with test phone numbers. Trying to send an SMS to real phone numbers cause the mentioned error "This request is missing a valid app identifier".

After some investigation, I'm done with these steps:
1. Create release keystore by the official [Flutter guide](https://docs.flutter.dev/deployment/android#signing-the-app) and sign an Android release flavor with it.
2. Migrate Firebase Authentication to Google Identity Platform.

And after these steps I've managed to use real phone numbers to send SMS OTPs. The only issue with that is popping up browser window telling "Verifying you're not a robot". I'm also trying to avoid it with integrating App Check to Flutter App and reinforcing Authentication with it. But this, I would say, not a topic of the issue.

I don't really know is issue related to usage of debug keystore or Firebase Authentication wasn't migrated to identity platform, so you can try do it yourself.

**Comment by RamzanTingku** [comment] 2023-10-24 13:15
Hi, I am getting this error when trying to verify phone number with OTP.

Here is what I did to solve this:

1. Added both release and debug SHA 1 key to Firebase App Settings
2. Added SHA 1 to Google API Key and made that unrestricted
3. Registered Play Integrity in FIrebase

Here are some of my code snippets:

```
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
  await FirebaseAppCheck.instance.activate(
      androidProvider: AndroidProvider.playIntegrity,
      appleProvider: AppleProvider.debug
  );
  runApp(MainApp());
}

await FirebaseAuth.instance.verifyPhoneNumber(
    phoneNumber: 'XXXXXXXXXXX',
    verificationCompleted: (PhoneAuthCredential credential) {},
    verificationFailed: (FirebaseAuthException e) {},
    codeSent: (String verificationId, int? resendToken) {},
    codeAutoRetrievalTimeout: (String verificationId) {},
  );
```

after that it tried to load captcha, but it returns from browser with verifying and show this error:
`[firebase_auth/missing-client-identifier] This request is missing a valid app identifier, meaning that Play Integrity checks, and reCAPTCHA checks were unsuccessful. Please try again, or check the logcat for more details`

Here are the dependencies I used:

- firebase_core: ^2.8.0
- firebase_messaging: ^14.3.0
- firebase_crashlytics: ^3.0.17
-  firebase_auth: ^4.3.0
-  firebase_app_check: ^0.1.3

And Flutter Version is:
`Flutter version 3.7.12`

I am stuck in at app production. Can you please help me with this?

**Comment by mohmmed750** [comment] 2023-11-18 17:44
Facing the same issue

**Comment by nntjvit** [comment] 2023-11-30 02:49
Facing the same issue too :(

**Comment by Shahir1730623** [comment] 2023-12-09 06:55
I have been facing the same issue. 
```void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
  await FirebaseAppCheck.instance.activate(
      webProvider: ReCaptchaV3Provider('recaptcha-v3-site-key'),
      androidProvider: AndroidProvider.playIntegrity,
      appleProvider: AppleProvider.debug
  );
  runApp(MainApp());
}

// build.gradle
dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'com.android.support:multidex:1.0.3'
    implementation 'androidx.appcompat:appcompat:1.2.0'
    implementation(platform("com.google.firebase:firebase-bom:32.6.0"))
    implementation 'com.google.firebase:firebase-auth-ktx'
    implementation 'com.google.android.play:integrity:1.3.0'
    implementation 'androidx.browser:browser:1.3.0'
}

// Otp Screen
sendOtp() async{
    await firebaseAuth.verifyPhoneNumber(
      phoneNumber: widget.userPhoneNumber!,
      verificationCompleted: (PhoneAuthCredential credential) async {
        pinController.setText(credential.smsCode!);
      },

      verificationFailed: (FirebaseAuthException e) {
        debugPrint("Error ${e.toString()}");
        debugPrint("Error ${e.message}");
        if (e.code == 'invalid-phone-number') {
          debugPrint('The provided phone number is not valid.');
        }

      },

      codeSent: (String verificationId, int? resendToken) {
        verifyId = verificationId;
        resendTokenForOtp = resendToken ?? 0;
      },

      timeout: const Duration(seconds: 25),
      forceResendingToken: resendTokenForOtp,


      codeAutoRetrievalTimeout: (String verificationId) {},
    );
  }

```

**Comment by bytebruno** [comment] 2023-12-17 14:58
We have this open since Feb... No official resolution yet?

**Comment by russellwheatley** [comment] 2023-12-18 15:55
I have not been able to reproduce the OPs issue I'm afraid. Just to clarify:
```
Error is:[firebase_auth/missing-client-identifier] This request is missing a valid app identifier
```
This exception is being reported when verifying telephone number in conjunction with App Check enforcement. If you are still seeing this exception, please provide a reproduction. Thanks.

**Comment by Shahir1730623** [comment] 2023-12-19 07:08
> I have not been able to reproduce the OPs issue I'm afraid. Just to clarify:
> 
> ```
> Error is:[firebase_auth/missing-client-identifier] This request is missing a valid app identifier
> ```
> 
> This exception is being reported when verifying telephone number in conjunction with App Check enforcement. If you are still seeing this exception, please provide a reproduction. Thanks.

Error Logs:
E/FirebaseAuth( 8493): [SmsRetrieverHelper] SMS verification code request failed: unknown status code: 17093 null
D/FirebaseAuth( 8493): Invoking original failure callbacks after phone verification failure for +8801715799289, error - This request is missing a valid app identifier, meaning that Play Integrity checks, and reCAPTCHA checks were unsuccessful. Please try again, or check the logcat for more details.
I/flutter ( 8493): Error [firebase_auth/missing-client-identifier] This request is missing a valid app identifier, meaning that Play Integrity checks, and reCAPTCHA checks were unsuccessful. Please try again, or check the logcat for more details.
I/flutter ( 8493): Error This request is missing a valid app identifier, meaning that Play Integrity checks, and reCAPTCHA checks were unsuccessful. Please try again, or check the logcat for more details.

```  
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
  await FirebaseAppCheck.instance.activate(
    webProvider: ReCaptchaV3Provider('recaptcha-v3-site-key'),
    androidProvider: AndroidProvider.playIntegrity,
    appleProvider: AppleProvider.appAttest,
  );
}

// Will send otp at start
  sendOtp() async{
    await firebaseAuth.verifyPhoneNumber(
      phoneNumber: widget.userPhoneNumber!,
      verificationCompleted: (PhoneAuthCredential credential) async {
        pinController.setText(credential.smsCode!);
      },

      verificationFailed: (FirebaseAuthException e) {
        debugPrint("Error ${e.toString()}");
        debugPrint("Error ${e.message}");
        if (e.code == 'invalid-phone-number') {
          debugPrint('The provided phone number is not valid.');
        }

      },

      codeSent: (String verificationId, int? resendToken) {
        verifyId = verificationId;
        resendTokenForOtp = resendToken ?? 0;
      },

      timeout: const Duration(seconds: 25),
      forceResendingToken: resendTokenForOtp,


      codeAutoRetrievalTimeout: (String verificationId) {},
    );
  }

  // Will be executed when user inputs 6 digits otp
  loginUser() async {
   showDialog(
        context: context,
        barrierDismissible: false,
        builder: (BuildContext context){
          return ProgressDialog(message: "Validating User...");
        }
    );

    try{
      PhoneAuthCredential credential = PhoneAuthProvider.credential(verificationId: verifyId, smsCode: code);
      final User? firebaseUser = (
          // Sign the user in (or link) with the credential
          await firebaseAuth.signInWithCredential(credential
          ).catchError((message){
            Navigator.pop(context);
            Fluttertoast.showToast(msg: "Error" + message);
          })
      ).user;

      if(firebaseUser != null){
        SharedPreferences prefs = await SharedPreferences.getInstance();
        DatabaseReference reference = FirebaseDatabase.instance.ref().child(userType!);
        reference.child(firebaseAuth.currentUser!.uid).once().then((userKey) async {
          final snapshot = userKey.snapshot;
          // If doctor is registered
          if (snapshot.exists && loggedInUser == "Doctor") {
            prefs.setString('loggedInUser', loggedInUser!);
            Navigator.push(context, MaterialPageRoute(builder: (context) => const SplashScreen()));
          }

          // New Doctor
          else if(!snapshot.exists && loggedInUser == "Doctor") {
            doctorProcess();
          }

          // If user is patient or consultant and registered
          else if (snapshot.exists && (loggedInUser == "Patient" || loggedInUser == "Consultant")) {
            prefs.setString('loggedInUser', loggedInUser!);
            Navigator.push(context, MaterialPageRoute(builder: (context) => const SplashScreen()));
          }

          // If user is patient
          else if (!snapshot.exists && loggedInUser == "Patient") {
            patientProcess(firebaseUser,prefs);
          }

        });
      }

    }

    catch(e){
      Navigator.pop(context);
      Fluttertoast.showToast(msg: "Wrong Credentials! Try Again",toastLength: Toast.LENGTH_LONG);
    }

  }


// build.gradle
dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'com.android.support:multidex:1.0.3'
    implementation 'androidx.appcompat:appcompat:1.2.0'
    implementation(platform("com.google.firebase:firebase-bom:32.6.0"))
    implementation 'com.google.firebase:firebase-auth-ktx'
    implementation 'com.google.android.play:integrity:1.3.0'
    implementation 'androidx.browser:browser:1.3.0'
}

```

Unfortunately, I receive this error when the sendOTP() is executed.

**Comment by russellwheatley** [comment] 2023-12-19 08:54
I can't reproduce. I would recreate the app SHA-1 key from keystore for auth and double check the SHA-256 app signing key  required for app check (typically received from the Google Play console). Also follow the instructions carefully here: https://firebase.google.com/docs/auth/android/phone-auth

**Comment by Shahir1730623** [comment] 2023-12-19 12:52
> I can't reproduce. I would recreate the app SHA-1 key from keystore for auth and double check the SHA-256 app signing key required for app check (typically received from the Google Play console). Also follow the instructions carefully here: https://firebase.google.com/docs/auth/android/phone-auth


There was a key restriction on android api key from google play console. 
I have removed the restriction in the following way
<img width="585" alt="Screenshot 2023-12-19 at 6 51 50 PM" src="https://github.com/firebase/flutterfire/assets/110086058/2d38edda-d057-4909-9e42-e6c27d0c53e4">

For now that error has been removed but I am facing new error. 

W/LocalRequestInterceptor(11202): Error getting App Check token; using placeholder token instead. Error: com.google.firebase.FirebaseException: Error returned from API. code: 403 body: App attestation failed.
E/FirebaseAuth(11202): [SmsRetrieverHelper] SMS verification code request failed: unknown status code: 17499 Error code:39

**Comment by Andrew-Bekhiet** [comment] 2023-12-28 23:26
Looking at the Enabled APIs and Services dashboard in GCP, you can see that Firebase App Check API requests have 100% error rate
![Screenshot](https://github.com/firebase/flutterfire/assets/40571928/a97f8630-6811-456f-8b22-897883769a53)

Inspecting logcat:
![Screenshot](https://github.com/firebase/flutterfire/assets/40571928/084a6477-e2fc-42ff-83eb-3e1a9a3c2d78)

I've added SHA256 and SHA1 for both debug and release certificates to firebase and gcp apis and services

**Comment by reglabel** [comment] 2024-01-09 17:27
Facing the same issue here 😟

**Comment by Andrew-Bekhiet** [comment] 2024-01-10 16:25
Using @Shahir1730623 solution fixed the issue

It turns out that PlayIntegrity works only when the app is on play store, if it is not published on Play Store reCaptcha flow is triggered which uses the same API key as the primary Android key created by firebase, which has to be unrestricted so that reCaptcha flow succeeds

So this should be a workaround because now I can't restrict my Android API key to only android apps because of recaptcha flow sharing the same API key with android app

**Comment by reglabel** [comment] 2024-01-11 13:07
I tested it after publishing on the Play Store, and indeed, it worked now! I'm not sure if it made a difference, but I also removed this line (I think it could have been interfering with the reCAPTCHA verification): 

`FirebaseAuth.getInstance().firebaseAuthSettings.forceRecaptchaFlowForTesting(true)`

I hope this tip can be helpful to someone! 🥳

**Comment by rajSapkota26** [comment] 2024-01-23 02:06
Hi, I am getting this error when trying to verify phone number with OTP.

Here is what I did to solve this:

1Added both release and debug SHA 1 && SHA 256 key to Firebase App Settings
2Added SHA 1 && SHA 256 to Google API Key and made that unrestricted
3Registered Play Integrity in FIrebase
4 add SHA1 && SHA 256 in play integrity on app check firebase
com.google.firebase.auth.FirebaseAuthException: This request is missing a valid app identifier, meaning that Play Integrity checks, and reCAPTCHA checks were unsuccessful. Please try again, or check the logcat for more details.
2024-01-23 07:45:49.693  7435-7435  System.err       	at com.google.android.gms.internal.firebase-auth-api.zzach.zza(com.google.firebase:firebase-auth@@22.3.1:39)
2024-01-23 07:45:49.693  7435-7435  System.err    	at com.google.android.gms.internal.firebase-auth-api.zzadb.zza(com.google.firebase:firebase-auth@@22.3.1:3)
2024-01-23 07:45:49.693  7435-7435  System.err              	at com.google.android.gms.internal.firebase-auth-api.zzade.run(com.google.firebase:firebase-auth@@22.3.1:4)
2024-01-23 07:45:49.693  7435-7435  System.err        	at android.os.Handler.handleCallback(Handler.java:942)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:211)
at android.os.Looper.loop(Looper.java:300)
at android.app.ActivityThread.main(ActivityThread.java:8410)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)

**Comment by QuentinSc** [comment] 2024-02-06 17:51
We need an updated documentation, clear steps

**Comment by Sumit258000** [comment] 2024-02-07 06:13
Any update on this issue @darshankawar

**Comment by Kapil619** [comment] 2024-02-09 12:40
> Hi, I am getting this error when trying to verify phone number with OTP.
> 
> Here is what I did to solve this:
> 
> 1Added both release and debug SHA 1 && SHA 256 key to Firebase App Settings 2Added SHA 1 && SHA 256 to Google API Key and made that unrestricted 3Registered Play Integrity in FIrebase 4 add SHA1 && SHA 256 in play integrity on app check firebase com.google.firebase.auth.FirebaseAuthException: This request is missing a valid app identifier, meaning that Play Integrity checks, and reCAPTCHA checks were unsuccessful. Please try again, or check the logcat for more details. 2024-01-23 07:45:49.693 7435-7435 System.err at com.google.android.gms.internal.firebase-auth-api.zzach.zza(com.google.firebase:firebase-auth@@22.3.1:39) 2024-01-23 07:45:49.693 7435-7435 System.err at com.google.android.gms.internal.firebase-auth-api.zzadb.zza(com.google.firebase:firebase-auth@@22.3.1:3) 2024-01-23 07:45:49.693 7435-7435 System.err at com.google.android.gms.internal.firebase-auth-api.zzade.run(com.google.firebase:firebase-auth@@22.3.1:4) 2024-01-23 07:45:49.693 7435-7435 System.err at android.os.Handler.handleCallback(Handler.java:942) at android.os.Handler.dispatchMessage(Handler.java:99) at android.os.Looper.loopOnce(Looper.java:211) at android.os.Looper.loop(Looper.java:300) at android.app.ActivityThread.main(ActivityThread.java:8410) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)

Hi, I'm encountering the  same error . Did you figured any workaround?

**Comment by Kapil619** [comment] 2024-02-17 16:34
I finally solved my issue by doing the same old traditional process.
You just want to ensure that the correct SHA keys are included in the firebase console.
In my case, I had added the SHA keys but those were generated by a keystore or a jks file .
But the sha keys you want to generate should be correct ones which would be generated by running the
 `./gradlew SigningReport ` for a flutter application.

After running the above command. You will get the correct SHA keys which are the Release keys as well as the Debug keys .
These are the only keys you have to put in the firebase console and nothing else.

**Comment by Andrew-Bekhiet** [comment] 2024-02-17 19:03
> > Using @Shahir1730623 solution fixed the issue
> > It turns out that PlayIntegrity works only when the app is on play store, if it is not published on Play Store reCaptcha flow is triggered which uses the same API key as the primary Android key created by firebase, which has to be unrestricted so that reCaptcha flow succeeds
> > So this should be a workaround because now I can't restrict my Android API key to only android apps because of recaptcha flow sharing the same API key with android app
> 
> By published on play store you mean also in testing?

I didn't try, so I don't know

**Comment by JakeSeo** [comment] 2024-02-21 00:54
any update on this? I also keep getting this error. It's weird that it works on some devices and it does not on some. I'm testing on a release apk. Here's a screen shot from Firebase App Check API of google cloud console. The error % is 100 or close to a 100 on those methods.. this doesn't seem right

<img width="1486" alt="Screenshot 2024-02-21 at 9 44 48 AM" src="https://github.com/firebase/flutterfire/assets/10471865/b000bc93-cfa8-4e0b-b5d7-0ac5c4111bbb">

**Comment by nehal076** [comment] 2024-02-21 03:56
I solved this issue by deleting the Firebase project and creating a completely new one.

**Comment by russellwheatley** [comment] 2024-02-22 12:20
Closing out as it cannot be reproduced, it is clear that it is a setup issue rather than a bug. If you have a reproduction, I will reopen the issue. Thanks.

**Closed by russellwheatley** 2024-02-22 12:20 UTC
Labels: type: bug, blocked: customer-response, plugin: auth, platform: android, plugin: app_check

**Comment by CORDEA** [comment] 2024-02-23 05:34
https://github.com/firebase/flutterfire/issues/10467#issuecomment-1648090820

This comment works fine for me. reCAPTCHA will launch after removing this option.
A few months ago, I added this option to make SMS auth work on development environment, but for now, it seems better without this. I hope this helps someone.

**Comment by DatUET** [comment] 2024-02-27 07:29
I'm not sure, but I solved this problem by going to GCP -> selecting project -> APIs & Services -> Credentials -> Delete Android key (auto created by Firebase) and create a new key. Then return to Firebase Console and reload the google-services.json file.

**Comment by jose920405** [comment] 2024-02-27 19:56
In my case, this was caused because I was using a different account on Firebase. It should be the same account in your google could, firebase and google play console. I thought the apps were linked internally via the package name but it wasn't

**Comment by dipanshparmar** [comment] 2024-03-21 10:40
> I'm not sure, but I solved this problem by going to GCP -> select project -> APIs & Services -> Credentials -> Delete Android key (auto created by Firebase) and create a new key with the same name delete. Then return to Firebase Console and redownload the google-services.json file.

I had to update the new key manually in `google-services.json` file and had to clean `(Build -> Clean Project)` the project.
