### ISSUE TITLE
🐛 [firebase_core] Windows Linker issues with _std_find_trivial

### ISSUE THREAD

**Issue by DionJChapman** [firebase/flutterfire#11212] opened 2023-07-03 02:46 UTC
## Bug report

**Describe the bug**
When building an app for Windows that includes Firebase usage such as auth and real-time-database using firebase_core

### Steps to reproduce

1. Write an App that includes Firebase using firebase_core
2. Debug App
3. See build errors

### Expected behavior

The app should build and debug normaly

### Sample project

Providing a minimal example project which demonstrates the bug in isolation from your main App _greatly_ enhances the chance of a timely fix.
Please link to the public repository URL.

---

## Additional context

```
firebase_app.lib(d3d7d08a438878e74aeb2cbaaedfc967_flatbuffers.dir_Debug_idl_parser.obj) : error LNK2019: unresolved external symbol __std_find_trivial_8 referenced in function "struct f_b_flatbuffers::StructDef * * __cdecl __std_find_trivial<struct f_b_flatbuffers::StructDef *,unsigned __int64>(struct f_b_flatbuffers::StructDef * *,struct f_b_flatbuffers::StructDef * *,unsigned __int64)" (??$__std_find_trivial@PEAUStructDef@f_b_flatbuffers@@_K@@YAPEAPEAUStructDef@f_b_flatbuffers@@PEAPEAU01@0_K@Z) [S:\Development\gitHub\PlatformToDo\platformtodo\build\windows\plugins\firebase_core\firebase_core_plugin.vcxproj]
firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_cleanup_notifier.obj) : error LNK2001: unresolved external symbol __std_find_trivial_8 [S:\Development\gitHub\PlatformToDo\platformtodo\build\windows\plugins\firebase_core\firebase_core_plugin.vcxproj]
firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_heartbeat_storage_desktop.obj) : error LNK2019: unresolved external symbol __std_find_trivial_1 referenced in function "char const * __cdecl __std_find_trivial<char const ,unsigned char>(char const *,char const *,unsigned char)" (??$__std_find_trivial@$$CBDE@@YAPEBDPEBD0E@Z) [S:\Development\gitHub\PlatformToDo\platformtodo\build\windows\plugins\firebase_core\firebase_core_plugin.vcxproj]
S:\Development\gitHub\PlatformToDo\platformtodo\build\windows\plugins\firebase_core\Debug\firebase_core_plugin.dll : fatal error LNK1120: 2 unresolved externals [S:\Development\gitHub\PlatformToDo\platformtodo\build\windows\plugins\firebase_core\firebase_core_plugin.vcxproj]
Exception: Build process failed.
```
---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.10.5, on Microsoft Windows [Version 10.0.22000.2057], locale en-AU)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.8.6)
[√] Android Studio (version 2022.2)
[√] IntelliJ IDEA Ultimate Edition (version 2020.1)
[√] VS Code (version 1.79.2)
[√] Connected device (3 available)
[√] Network resources

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 3.0.5
Flutter SDK 3.10.5
platformtodo 1.0.0+1

dependencies:
- cloud_functions 4.3.3 [cloud_functions_platform_interface cloud_functions_web firebase_core firebase_core_platform_interface flutter]
- cupertino_icons 1.0.5
- easy_splash_screen 1.0.4 [flutter]
- firebase_auth 4.6.3 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 2.14.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_database 10.2.3 [firebase_core firebase_core_platform_interface firebase_database_platform_interface firebase_database_web flutter]
- flutter 0.0.0 [characters collection js material_color_utilities meta vector_math sky_engine]
- flutter_colorpicker 1.0.3 [flutter]
- flutter_launcher_icons 0.13.1 [args checked_yaml cli_util image json_annotation path yaml]
- flutter_localization 0.1.12 [flutter flutter_web_plugins flutter_localizations plugin_platform_interface shared_preferences]
- flutter_localizations 0.0.0 [flutter intl characters clock collection js material_color_utilities meta path vector_math]
- intl 0.18.0 [clock meta path]
- material_design_icons_flutter 7.0.7296 [flutter]
- package_info_plus 4.0.2 [ffi flutter flutter_web_plugins http meta path package_info_plus_platform_interface win32]
- page_transition 2.0.9 [flutter]
- percent_indicator 4.2.3 [flutter]
- responsive_builder 0.7.0 [flutter provider]
- system_theme 2.2.0 [system_theme_web flutter]
- word_generator 0.4.3 [flutter]

dev dependencies:
- flutter_lints 2.0.2 [lints]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters collection js matcher material_color_utilities meta source_span stream_channel string_scanner term_glyph]

transitive dependencies:
- _flutterfire_internals 1.3.3 [collection firebase_core firebase_core_platform_interface flutter meta]
- archive 3.3.7 [crypto path pointycastle]
- args 2.4.2
- async 2.11.0 [collection meta]
- boolean_selector 2.1.1 [source_span string_scanner]
- characters 1.3.0
- checked_yaml 2.0.3 [json_annotation source_span yaml]
- cli_util 0.4.0 [meta path]
- clock 1.1.1
- cloud_functions_platform_interface 5.4.3 [firebase_core flutter meta plugin_platform_interface]
- cloud_functions_web 4.5.3 [cloud_functions_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- collection 1.17.1
- convert 3.1.1 [typed_data]
- crypto 3.0.3 [typed_data]
- fake_async 1.3.1 [clock collection]
- ffi 2.0.2
- file 6.1.4 [meta path]
- firebase_auth_platform_interface 6.15.3 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 5.5.3 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser js meta]
- pointycastle 3.7.3 [collection convert js]
- process 4.2.4 [file path platform]
- provider 6.0.5 [collection flutter nested]
- shared_preferences 2.2.0 [flutter shared_preferences_android shared_preferences_foundation shared_preferences_linux shared_preferences_platform_interface shared_preferences_web shared_preferences_windows]
- shared_preferences_android 2.2.0 [flutter shared_preferences_platform_interface]
- shared_preferences_foundation 2.3.0 [flutter shared_preferences_platform_interface]
- shared_preferences_linux 2.3.0 [file flutter path path_provider_linux path_provider_platform_interface shared_preferences_platform_interface]
- shared_preferences_platform_interface 2.3.0 [flutter plugin_platform_interface]
- shared_preferences_web 2.2.0 [flutter flutter_web_plugins shared_preferences_platform_interface]
- shared_preferences_windows 2.3.0 [file flutter path path_provider_platform_interface path_provider_windows shared_preferences_platform_interface]
- sky_engine 0.0.99
- source_span 1.9.1 [collection path term_glyph]
- stack_trace 1.11.0 [path]
- stream_channel 2.1.1 [async]
- string_scanner 1.2.0 [source_span]
- system_theme_web 0.0.2 [flutter flutter_web_plugins]
- term_glyph 1.2.1
- test_api 0.5.1 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.2 [collection]
- vector_math 2.1.4
- win32 5.0.5 [ffi]
- xdg_directories 1.0.0 [meta path process]
- xml 6.3.0 [collection meta petitparser]
- yaml 3.1.2 [collection source_span string_scanner]
```

</details>

---

**Comment by danagbemava-nc** [comment] 2023-07-03 10:27
Hi @DionJChapman, this is a duplicate of https://github.com/firebase/flutterfire/issues/10992. 

Kindly follow up in the original issue for updates. 

Closing from here. 

Thank you

**Closed by danagbemava-nc** 2023-07-03 10:27 UTC
Labels: type: bug, Needs Attention, in triage

**Comment by Levi-Lesches** [comment] 2023-07-05 02:22
I'm also having this issue. @danagbemava-nc, the issue you linked is about not having NuGet installed when developing for Windows, and Flutter failing to download it. This seems to be a different error entirely, and NuGet isn't what's failing here.

**Comment by danagbemava-nc** [comment] 2023-07-05 10:06
@Levi-Lesches, not entirely, if you look at my comment reproducing the issue https://github.com/firebase/flutterfire/issues/10992#issuecomment-1568372285, it's not related to nuget. It may have started out that way, but the nuget issue was not related to flutterfire
