### ISSUE TITLE
🐛 [firebase_app_check] Allow manual setting of app check token in debug mode

### ISSUE THREAD

**Issue by jt274** [firebase/flutterfire#12376] opened 2024-02-22 17:37 UTC
In the Android and iOS sections of the App Check docs, there are instructions to configure the App Check debug provider for unit testing in a CI environment. Links:

https://firebase.google.com/docs/app-check/android/debug-provider#ci
https://firebase.google.com/docs/app-check/ios/debug-provider#ci

There are no similar instructions or available methods for App Check in flutter. This makes it difficult to perform an automated test on an app that requires App Check in multiple environments, such as real devices or emulators in Firebase Test Lab. In these situations, a token is printed to console and must be manually added to the Firebase console for each device, instead of all sharing the same token.

The feature should be added to the flutter package as simply as possible. For example:

`FirebaseAppCheck.instance.setDebugProviderToken(MY_TOKEN);`

**Comment by marcellocamara** [comment] 2024-06-30 22:25
> @jt274 
> FirebaseAppCheck.instance.setDebugProviderToken(MY_TOKEN);

This method will allow us to simplify the use of the same token in a project with many developers.
Adds token by token (each developer generating one), it's a bad way.

**Comment by adonisRodxander** [comment] 2024-10-09 00:01
Any updates or workarount?

**Comment by russellwheatley** [comment] 2024-11-19 10:53
Hey folks, this is actually a duplicate of this issue: https://github.com/firebase/flutterfire/issues/11719

Could you please add your thumbs up on that issue. We are considering this feature so it is worth your time. Thanks 🙏

**Closed by russellwheatley** 2024-11-19 10:53 UTC
Labels: type: enhancement, type: missing-feature, plugin: app_check, platform: all
