### ISSUE TITLE
🐛 [Firebase_auth] firebase auth giving error on latest version

### ISSUE THREAD

**Issue by alihassan143** [firebase/flutterfire#11355] opened 2023-07-24 04:55 UTC
## Bug report
```
Lexical or Preprocessor Issue (Xcode): 'messages.g.h' file not found
/Users/mac/.pub-cache/hosted/pub.dev/firebase_auth-4.7.1/ios/Classes/messages.g.m:3:8
```
**Plugin version**
 ```
 firebase_core: ^2.15.0
  firebase_auth: ^4.7.1
```

**Comment by danagbemava-nc** [comment] 2023-07-24 12:28
Closing this as a duplicate of https://github.com/firebase/flutterfire/issues/11285.

**Closed by danagbemava-nc** 2023-07-24 12:28 UTC
Labels: type: bug, Needs Attention, in triage
