### ISSUE TITLE
[📚]  The README.md has a broken link for the text "FlutterFire UI"

### ISSUE THREAD

**Issue by adsouza** [firebase/flutterfire#10590] opened 2023-03-13 00:18 UTC
The README.md has a broken link for the text "FlutterFire UI".

**Comment by itsashishrath** [comment] 2023-03-13 09:07
I am a beginner and i wanted to contribute to this issue. I went through [Firebase official Link](https://firebase.flutter.dev/docs/ui/overview/) where it is mentioned referring to this repository for latest information.
Is the documentation page shifted somewhere else or is it to be created from scratch? Any suggestion or advices would be helpful.

**Comment by adsouza** [comment] 2023-03-13 10:13
I posed this very question at
https://github.com/firebase/flutterfire/discussions/6978 & am hoping for an
answer.

**Comment by darshankawar** [comment] 2023-03-13 10:42
Closing as duplicate of https://github.com/firebase/flutterfire/issues/10459



> I am a beginner and i wanted to contribute to this issue. I went through [Firebase official Link](https://firebase.flutter.dev/docs/ui/overview/) where it is mentioned referring to this repository for latest information.
> Is the documentation page shifted somewhere else or is it to be created from scratch? Any suggestion or advices would be helpful.

Please take a look at https://github.com/firebase/flutterfire#contributing

**Closed by darshankawar** 2023-03-13 10:42 UTC
Labels: type: documentation, good first issue, in triage
