### ISSUE TITLE
🐛 Cloud Firebase 

### ISSUE THREAD

**Issue by MesharSuliman** [firebase/flutterfire#8871] opened 2022-06-09 19:59 UTC
## Bug report

Hello 
  
   this link projecit -- https://github.com/MesharSuliman/All-in-one

1- Problem with List DropDown - if page link with main.dart no problem but if another link not work this example for DropDown List - kindly check the attach
 
![Screen Shot 1443-11-10 at 10 53 59 PM](https://user-images.githubusercontent.com/94109963/172932985-5f6dc720-9627-43d6-a69b-015e3f35d799.png)

https://user-images.githubusercontent.com/94109963/172933261-049f5e0a-1bff-48e8-982e-60fc8479da5f.mov

**Comment by maheshmnj** [comment] 2022-06-10 12:22
Hi @MesharSuliman, I looked at your code sample the dropdown doesn't work because the list passed to your dropdown is empty.  

Notice that  your function returns a Stream

> Stream<List<SectionModel>> getAllSection() {


and if you try to debug this function you will notice that, this line is never completed and Section is either null or empty

>    List<SectionModel> Section =
        await FirebaseManager.shared.getAllSection().first;

```dart
  _getData() async {
    List<SectionModel> Section =
        await FirebaseManager.shared.getAllSection().first;

    setState(() {
      downMenuItem = Section.map((item) => DropdownMenuItem(
          child: Text(item.title), value: item.uid.toString())).toList();

      if (widget.uid != null) {
        DropDownItem = widget.uid;
      }
    });
  }
``` 



I would suggest debugging `getAllSection` method where the bug lies, If you need further help please ask on forums like StackOverflow. Closing as this is not a bug with firestore but with your code.

**Closed by maheshmnj** 2022-06-10 12:22 UTC
Labels: type: bug, Needs Attention, in triage

**Comment by MROOT-user** [comment] 2022-06-11 05:02
# root

A new Flutter project.
    ✗ Due to an error, the doctor check did not complete. If the error message below is not
      helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    ✗ ProcessException: Failed to find "pkg-config" in the search path.
        Command: pkg-config

## Getting Started
  test --mod
This project is a starting point for a Flutter application.

A few resources to get you started if this is your first Flutter project:

- [Lab: Write your first Flutter app](https://docs.flutter.dev/get-started/codelab)
- [Cookbook: Useful Flutter samples](https://docs.flutter.dev/cookbook)

For help getting started with Flutter development, view the
[online documentation](https://docs.flutter.dev/), which offers tutorials,
samples, guidance on mobile development, and a full API reference.


Br,
Meshari

**Comment by maheshmnj** [comment] 2022-06-13 04:36
> ok if u don't support why close issue

@MesharSuliman This is not actionable on our end, Meaning there's no Change in the flutter fire docs or SDK/plugin would help to make the bug go away.
