### ISSUE TITLE
[firebase_dynamic_links] [iOS] Deeplinks do not work if they are clicked while the app is killed

### ISSUE THREAD

**Issue by tudor07** [firebase/flutterfire#9110] opened 2022-07-15 07:36 UTC
I have a deeplink that when clicked is supposed to open a specific screen.

**On Android all scenarios work perfectly.**

On iOS I see the following behaviours:

**Working scenario:**
If the app was already opened, but was put in background, if I click the deeplink, it works fine, the app is put to foreground and shows my custom screen for the opened deeplink path. These are the steps:
1. Open my app normally (tap app icon)
2. Put the app to background (I just dissmiss my app to go to iOS main menu, note: I do not kill my app from memory)
3. I go and open another app where I have my deeplink (eg. Messages or Mail)
4. Tap the deeplink
5. My app is brought to foreground and the correct screen is shown according to the tapped deeplink path

**Broken scenario:**
1. Kill my app from memory (from app switcher, swipe up on my app so it's killed)
2. I go and open another app where I have my deeplink (eg. Messages or Mail)
3. Tap the deeplink
4. My app opens on the first default screen, the custom screen for the deeplink is not shown (other way to put it: my handler for the deeplink is **not** called, `onLink`/`getInitialLink` **not** called)

Minimal code to reproduce:
<details>
  <summary>main.dart</summary>
  
  ```
  import 'dart:async';
  
  import 'package:flutter/material.dart';
  import 'package:firebase_core/firebase_core.dart';
  
  void main() async {
    WidgetsFlutterBinding.ensureInitialized();
  
      await Firebase.initializeApp(
        options: FirebaseOptions(
          apiKey: 'apiKey',
          appId: 'appId',
          messagingSenderId: 'messagingSenderId',
          projectId: 'projectId',
          authDomain: 'authDomain',
          databaseURL: 'databaseURL',
          storageBucket: 'storageBucket',
          measurementId: 'measurementId',
          androidClientId: 'androidClientId',
          iosClientId: 'iosClientId',
          iosBundleId: 'iosBundleId',
        ),
    );
  
  
    runApp(MyApp());
  }
  ```
</details>

<details>
  <summary>my_app.dart</summary>
  
  ```
  import 'package:firebase_dynamic_links/firebase_dynamic_links.dart';
  import 'package:flutter/material.dart';
  import 'package:flutter/services.dart';
  
  class MyApp extends StatefulWidget {
    MyApp({
      Key key,
    }) : super(key: key);
  
    @override
    _MyAppState createState() => _MyAppState();
  }
  
  class _MyAppState extends State<MyApp> {
    @override
    void initState() {
      super.initState();
  
      FirebaseDynamicLinks.instance.onLink.listen(_handleDeepLink);
      _getInitialLink();
    }
  
    Future<void> _getInitialLink() async {
      final PendingDynamicLinkData data =
          await FirebaseDynamicLinks.instance.getInitialLink();
      _handleDeepLink(data);
    }
  
    @override
    Widget build(BuildContext context) {
      // return app widgets...
    }
  
    Future<dynamic> _handleDeepLink(PendingDynamicLinkData linkData) async {
      final Uri deepLink = linkData?.link;
      if (deepLink == null) {
        return;
      }
  
      if (deepLink.path == '/my/custom/path') {
        Navigator.of(context).pushNamed(MyCustomScreen.routeName);
      }
    }
  }
  ```
</details>

<details>
  <summary>flutter doctor</summary>
  
  ```
  Doctor summary (to see all details, run flutter doctor -v):
  [✓] Flutter (Channel stable, 2.10.3, on macOS 12.4 21F79 darwin-arm, locale en-RO)
  [✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
  [✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
  [✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
      ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
  [✓] Android Studio (version 2021.2)
  [✓] Android Studio (version 2021.2)
  [✓] IntelliJ IDEA Community Edition (version 2022.1.3)
  [✓] IntelliJ IDEA Community Edition (version 2022.1.2)
  [✓] IntelliJ IDEA Ultimate Edition (version EAP IC-222.3244.4)
  [✓] IntelliJ IDEA Ultimate Edition (version EAP IC-222.3048.13)
  [✓] VS Code (version 1.69.0)
  [✓] Connected device (1 available)
  [✓] HTTP Host Availability
  ```
</details>

Firebase libs:
```
firebase_core: 1.19.2
firebase_dynamic_links: 4.3.2
```

**Comment by darshankawar** [comment] 2022-07-15 11:21
Thanks for the detailed report @tudor07 


> 4\. (other way to put it: my handler for the deeplink is **not** called, `onLink`/`getInitialLink` **not** called)

Does this mean `getInitialLink()` is `null` and `onLink()` is not called at all ?

Are you using dart initialization for your project or manual setup using google services file (GoogleService-Info.plist) ?

If the latter, are you using `<key>FirebaseDynamicLinksCustomDomains</key>` in info.plist file ?

**Comment by tudor07** [comment] 2022-07-19 11:59
1. Yes - `getInitialLink` is `null`, `onLink` not called
2. Yes - I use Dart initialization (no `.plist` file)
3. Yes, I have that entry in the `Info.plist` file

**Comment by darshankawar** [comment] 2022-07-20 10:40
Thanks for the update. Can you take a look at [this](https://github.com/firebase/flutterfire/issues/6913#issuecomment-1094101508) solution and see if it works in your case ?

Also check [this](https://github.com/firebase/flutterfire/issues/8926#issuecomment-1168735810) comment from team member indicating that initializing  with `flutterfire configure` may not support all firebase products yet, so maybe you can try the same scenario using `GoogleService-Info.plist` ?

**Comment by tudor07** [comment] 2022-07-20 13:26
I already had the `Firebase Installations API` added to my API key.
Using `GoogleService-Info.plist` is not an option for my project.

**Comment by darshankawar** [comment] 2022-07-21 11:18
From your `flutter doctor`, I see that you are on `2.10.3`. Can you possibly upgrade to latest stable and try ?
Also, what iOS version are you seeing this on ? I am trying to know if this is iOS specific or not.

**Comment by tudor07** [comment] 2022-07-21 11:41
I'm using `iOS 15.5`

**Comment by darshankawar** [comment] 2022-07-22 11:01
@tudor07 
From the code sample you shared earlier, specially below section:

```
Future<void> _getInitialLink() async {
    final PendingDynamicLinkData data =
        await FirebaseDynamicLinks.instance.getInitialLink();
    _handleDeepLink(data);
  }



Future<dynamic> _handleDeepLink(PendingDynamicLinkData linkData) async {
    final Uri deepLink = linkData?.link;
    if (deepLink == null) {
      return;
    }

    if (deepLink.path == '/my/custom/path') {
      Navigator.of(context).pushNamed(MyCustomScreen.routeName);
    }
  }  
```

Can you try to first check if `linkData` is `null`  and if not, what it prints and then something like below ?

```
if (linkData != null) {
  print (`initial link $linkData`);
  }

  final Uri deepLink = linkData?.link;

  if (deepLink != null) {
   // your routing logic here
  }
```

**Comment by matthewfx** [comment] 2022-07-26 22:25
I have had the same problem. However, once I tested it with a real device instead of the simulator the initial link wasn't null. @darshankawar It would be nice if you could make it work on the simulator too though :)

**Comment by tudor07** [comment] 2022-07-27 07:34
@matthewfx  I tested on a real device

**Comment by matthewfx** [comment] 2022-07-27 07:37
@tudor07 uh oh... in that case I wonder why it sometimes works and sometimes doesn't... Quite concerning to be honest :(

**Comment by tudor07** [comment] 2022-07-27 09:02
@darshankawar `linkData` is null

**Comment by darshankawar** [comment] 2022-07-27 10:22
Thanks for the update. Using the code sample provided, I am getting same behavior.

**Comment by russellwheatley** [comment] 2022-07-28 14:57
I've just tested this with and without the `GoogleService-Info.plist` file, and it works when the app is killed (i.e. the deep link is present). I'm going to update the Dynamic Links example app so you can test it for yourself (double check what possible config you may have set incorrectly) as there a few things that need updating. A couple of things that are necessary:

1. It needs to be run in release mode (i.e. `flutter run --release`)
2. It needs to run on an actual device.

**Comment by tudor07** [comment] 2022-08-01 06:46
@russellwheatley so you are saying that you can't reproduce this issue?

**Comment by russellwheatley** [comment] 2022-08-01 12:46
I have updated the dynamic link example app. I think you should be able to run it on a device and check. Check out this branch locally: https://github.com/firebase/flutterfire/pull/9250

Here is the dynamic link: https://reactnativefirebase.page.link/bFkn

If you run:
1. melos boostrap in root of project.
2. run the dynamic link example app in release mode: `flutter run --no-pub --release` on an iOS device.
3. Kill the app and click on the above noted link.
4. The app should open up and immediately take you to a screen via `onLink` [here](https://github.com/firebase/flutterfire/blob/c5d288b388cfd4180896ef9fc2a004c84ccbc017/packages/firebase_dynamic_links/firebase_dynamic_links/example/lib/main.dart#L60)
5. The screen simply has the text node "Hello, World!" which is this widget [here](https://github.com/firebase/flutterfire/blob/c5d288b388cfd4180896ef9fc2a004c84ccbc017/packages/firebase_dynamic_links/firebase_dynamic_links/example/lib/main.dart#L188-L202)

**Comment by tudor07** [comment] 2022-08-02 07:04
I'll check but @darshankawar said he is also able to reproduce my issue, it would be great if he can also try the above example. It would be helpful to try on as many devices as we can.

**Comment by darshankawar** [comment] 2022-08-02 07:27
I'll re-verify and confirm.

**Comment by darshankawar** [comment] 2022-08-02 10:36
@tudor07 
Based on @russellwheatley's comment earlier, I verified by running `firebase_dynamic_links` plugin example in release mode on iOS device (iphone 6s, OS 15.3.1) and was able to see expected behavior. See below:


https://user-images.githubusercontent.com/67046386/182354969-a81864af-9222-45da-a35d-983b106fe49d.MP4


I am on latest master version.

**Comment by tudor07** [comment] 2022-08-02 14:26
Yes, same with that one

**Comment by russellwheatley** [comment] 2022-08-02 14:30
@tudor07 You're using this branch https://github.com/firebase/flutterfire/pull/9250?

**Comment by russellwheatley** [comment] 2022-08-02 14:32
Could you also change the default browser as well to chrome and see if that makes a difference.

**Comment by tudor07** [comment] 2022-08-03 07:12
I am using `@russell/dynamic-9110` branch:
```
❯ git branch
* @russell/dynamic-9110
```

I get the same behaviour with Chrome.

Btw, this behaviour is for links generated inside the app, if I use `reactnativefirebase.page.link/bFkn` specifically I get to`invertase.io/helloworld` which is a `404` page.

**Comment by russellwheatley** [comment] 2022-08-03 07:35
If you get the link `invertase.io/helloworld` then it worked correctly. That is the deeplink:
<img width="730" alt="Screenshot 2022-08-03 at 08 31 15" src="https://user-images.githubusercontent.com/16018629/182550404-a62e5d4a-f7a2-4b17-9d19-a0e03214007c.png">

It is a 404 hence why we use just the path to push you to another screen to show you it works: https://github.com/firebase/flutterfire/blob/master/packages/firebase_dynamic_links/firebase_dynamic_links/example/lib/main.dart#L60

**Comment by maciejbrzezinski** [comment] 2022-08-03 09:09
I'm working on two apps at the moment and I spotted the same problem in one of them :v 

That's weird, because scenarios when app is installed from app store or link is clicked when the app is in background works fine. Problem happens only when the app is terminated. 

I also compared the two apps configs few times and I couldn't spot anything suspicious.

I performed two tests with usage of app_links package on my apps. Both scenarios were launched by clicking dynamic link  from terminated state. There was release mode and this launch option checked in XCode:
![Screen Shot 2022-08-03 at 11 03 46 AM](https://user-images.githubusercontent.com/34410554/182569459-cbe9b38e-2946-4cbb-b748-eea2c7dbca12.png)

Code that I've used in both apps:

```
FirebaseDynamicLinks.instance
        .getInitialLink()
        .then((value) => print('getInitialLink: $value'))
        .onError((error, stackTrace) => print(error));

    _appLinks.getInitialAppLink().then((value) {
      print('app link: $value');
      if (value != null) {
        try {
          FirebaseDynamicLinks.instance.getDynamicLink(value).then(
              (dynamicLink) => print('app link as dynamic: $dynamicLink'));
        } catch (e) {
          print(e);
        }
      }
    });

    FirebaseDynamicLinks.instance.onLink
        .listen((event) async => print('onLink: $event'));
```

And there are results: 
Working app:
![Screen Shot 2022-08-03 at 10 54 59 AM](https://user-images.githubusercontent.com/34410554/182568801-9a7bf6a9-ad0d-4743-9ed0-05940ca3863b.png)

Not working. You can see that onLink is not called, but the app_links plugin works fine:
![Screen Shot 2022-08-03 at 10 53 57 AM](https://user-images.githubusercontent.com/34410554/182568877-8bdca420-ae84-4ac5-8352-aa8f54f5c12a.png)

**Comment by tudor07** [comment] 2022-08-03 09:14
@russellwheatley shouldn't it open the app? My issue was about opening the app and getting clicked linked.

**Comment by russellwheatley** [comment] 2022-08-03 11:27
@tudor07  Yes, it will open your app, and the deep link received is the one I mentioned.

**Comment by tudor07** [comment] 2022-08-04 06:34
@russellwheatley that's not what it happens with the `example` app, so how can I reproduce my issue using it?
In my app, I want my app to open.
In the `example` app, a webpage is opened even though the app is installed.

**Comment by russellwheatley** [comment] 2022-08-04 08:47
are you running in `flutter run --no-pub --release` mode? Have you followed every one of [these steps](https://github.com/firebase/flutterfire/issues/9110#issuecomment-1201156205) exactly?

**Comment by krishna700** [comment] 2022-08-06 11:04
I am also facing this issue. 
The dynamic link opens the app correctly, but doesn't navigate when app is in terminated state. So initial link is definitely null. 

This is a very crucial feature. Please help.

> [✓] Flutter (Channel stable, 2.10.5, on macOS 12.4 21F79 darwin-arm, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.69.2)
[✓] Connected device (1 available)
[✓] HTTP Host Availability


> firebase_core: ^1.20.0
  firebase_messaging: ^12.0.1
  firebase_analytics: ^9.3.0
  firebase_crashlytics: ^2.8.6
  firebase_dynamic_links: ^4.3.3
  firebase_performance: ^0.8.2+1

**Comment by ArkadiuszDatka** [comment] 2022-08-08 09:08
Similarly for me, but it works correctly on android and ios <= 15.5, but it does not work on ios 15.6. @krishna700 if you can verify that you can run on an older ios version.

**Comment by russellwheatley** [comment] 2022-08-08 09:30
@ArkadiuszDatka - My device uses iOS 15.6. It works.

**Comment by krishna700** [comment] 2022-08-08 09:36
I checked in a device running 15.4.1, it doesn't work in terminated state.

**Comment by ArkadiuszDatka** [comment] 2022-08-08 15:00
@krishna700   you can check your link if it has the correct format (I missed the efr parameter set - https://firebase.google.com/docs/dynamic-links/create-manually#parameters) and check if the bundleID for release mode is actually the one that it is configured for dynamic link - it worked for me

**Comment by ArkadiuszDatka** [comment] 2022-08-10 18:14
@krishna700 try adding 2s delay before FirebaseDynamicLinks.instance.getInitialLink()

**Comment by holyboom1** [comment] 2022-08-12 18:57
i'm found temporary solution this problem...
i'm use library app_links 
`  Future<String?> getInitialLink() async {
    final _appLinks = AppLinks();
    final PendingDynamicLinkData? linkData = await FirebaseDynamicLinks.instance.getInitialLink();
    if (linkData != null) {
      return linkData.link.queryParameters[payload];
    } else {
      final Uri? uri = await _appLinks.getInitialAppLink();
      if (uri != null) {
        final PendingDynamicLinkData? appLinkData = await FirebaseDynamicLinks.instance.getDynamicLink(uri);
        if (appLinkData != null) {
          return appLinkData.link.queryParameters[payload];
        }
      }
    }
    return null;
  }`

and we also can add platform  check

**Closed** 2022-09-22 12:47 UTC
Labels: type: bug, plugin: dynamic_links, platform: ios
