### ISSUE TITLE
 [firebase_messaging] Firebase getToken not work on an iOS simulator, but it works with a real device

### ISSUE THREAD

**Issue by kenguyenduc** [firebase/flutterfire#13575] opened 2024-10-31 03:22 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Messaging

### Which platforms are affected?

iOS

### Description

 [firebase_messaging] Firebase getToken not work on an iOS simulator, but it works with a real device
- I use:
  firebase_messaging: ^15.1.3
  firebase_core: ^3.6.0
- Flutter doctor -v: 
 [✓] Flutter (Channel stable, 3.24.3, on macOS 15.0.1 24A348 darwin-arm64, locale en-VN)
    • Flutter version 3.24.3 on channel stable at /Users/admin/fvm/versions/3.24.3
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2663184aa7 (7 weeks ago), 2024-09-11 16:27:48 -0500
    • Engine revision 36335019a8
    • Dart version 3.5.3
    • DevTools version 2.37.3
[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16A242d
    • CocoaPods version 1.15.2

ERROR LOG:
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: [firebase_messaging/unknown] An unknown error has occurred.
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:648:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334:18)
<asynchronous suspension>
#2      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:534:43)
<asynchronous suspension>
#3      MethodChannelFirebaseMessaging.getToken (package:firebase_messaging_platform_interface/src/method_channel/method_channel_messaging.dart:248:11)
<asynchronous suspension>

### Reproducing the issue

ERROR LOG:
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: [firebase_messaging/unknown] An unknown error has occurred.
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:648:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334:18)
<asynchronous suspension>
#2      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:534:43)
<asynchronous suspension>
#3      MethodChannelFirebaseMessaging.getToken (package:firebase_messaging_platform_interface/src/method_channel/method_channel_messaging.dart:248:11)
<asynchronous suspension>

### Firebase Core version

3.6.0

### Flutter Version

3.24.3

### Relevant Log Output

```shell
ERROR LOG:
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: [firebase_messaging/unknown] An unknown error has occurred.
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:648:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334:18)
<asynchronous suspension>
#2      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:534:43)
<asynchronous suspension>
#3      MethodChannelFirebaseMessaging.getToken (package:firebase_messaging_platform_interface/src/method_channel/method_channel_messaging.dart:248:11)
<asynchronous suspension>
```

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Replace this line with the contents of your `flutter pub deps -- --style=compact`.

```

</details>

**Comment by SelaseKay** [comment] 2024-10-31 06:51
Duplicate of: https://github.com/firebase/flutterfire/issues/13558

**Closed by SelaseKay** 2024-10-31 06:51 UTC
Labels: type: bug, Needs Attention

**Comment by MhamadHwidi7** [comment] 2024-11-11 08:53
I have resolved it 
in iOS , use getAPNSToken instead of getToken and it will be work 

like this ,
import 'package:firebase_messaging/firebase_messaging.dart';

class LogInCustomerParams {
  final String email;
  final String password;
  String? fcmToken;

  LogInCustomerParams({required this.email, required this.password});
  
  Future<void> fetchFcmToken() async {
    FirebaseMessaging messaging = FirebaseMessaging.instance;
    fcmToken = await messaging.getAPNSToken(); /// getAPNSToken instead of getToken
  }


  Map<String, dynamic> toJson() => {
        "email": email,
        "password": password,
        "fcmtoken": fcmToken,
      };
}

**Comment by Aburafik** [comment] 2024-11-15 10:29
> I have resolved it in iOS , use getAPNSToken instead of getToken and it will be work
> 
> like this , import 'package:firebase_messaging/firebase_messaging.dart';
> 
> class LogInCustomerParams { final String email; final String password; String? fcmToken;
> 
> LogInCustomerParams({required this.email, required this.password});
> 
> Future fetchFcmToken() async { FirebaseMessaging messaging = FirebaseMessaging.instance; fcmToken = await messaging.getAPNSToken(); /// getAPNSToken instead of getToken }
> 
> Map<String, dynamic> toJson() => { "email": email, "password": password, "fcmtoken": fcmToken, }; }

does it work on simulator too?

**Comment by MhamadHwidi7** [comment] 2024-11-15 12:38
Yes , it works 👍🏻
