### ISSUE TITLE
🐛 [Firebase_core] - No implementation found for method Firebase#initializeCore on channel plugins.flutter.io/firebase_core

### ISSUE THREAD

**Issue by alelav79** [firebase/flutterfire#9013] opened 2022-07-01 10:02 UTC
## Bug report

Problems after upgrade packages

from
   firebase_core: ^1.17.1
  firebase_messaging: ^11.4.1
to
  firebase_core: ^1.19.0
  firebase_messaging: ^11.4.3

### Steps to reproduce

1. Edit lines  

  firebase_core: ^1.19.0
  firebase_messaging: ^11.4.3

in pubspec.yaml

2. in CLI

flutter clean
flutter pub get

3. Start debug , the app starts but it shows this exception error

No implementation found for method Firebase#initializeCore on channel plugins.flutter.io/firebase_core

related to line in code :

await Firebase.initializeApp();

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
λ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.0.2, on Microsoft Windows [Versione 10.0.19044.1766], locale it-IT)
[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.0.5)
[√] Android Studio (version 2020.3)
[√] VS Code (version 1.68.1)
[√] Connected device (4 available)
[√] HTTP Host Availability

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.17.3
Flutter SDK 3.0.2
renatatravel 0.8.5+4

dependencies:
- animated_splash_screen 1.2.0 [flutter page_transition]
- badges 2.0.2 [flutter]
- cached_network_image 3.2.1 [flutter flutter_cache_manager octo_image cached_network_image_platform_interface cached_network_image_web]
- carousel_slider 4.0.0 [flutter]
- cupertino_icons 1.0.4
- datetime_picker_formfield 2.0.0 [flutter intl]
- equatable 2.0.3 [collection meta]
- firebase_core 1.19.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_messaging 11.4.3 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]        
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- flutter_bloc 8.0.1 [flutter bloc provider]
- flutter_braintree 2.3.1 [flutter meta]
- flutter_feathersjs 4.0.4+4 [flutter socket_io_client dio shared_preferences event_bus]
- flutter_localizations 0.0.0 [flutter intl characters clock collection material_color_utilities meta path vector_math]
- geolocator 8.2.1 [flutter geolocator_platform_interface geolocator_android geolocator_apple geolocator_web geolocator_windows]
- get_it 7.2.0 [async collection]
- google_fonts 2.3.1 [flutter http path_provider crypto]
- google_maps_flutter 2.1.8 [flutter flutter_plugin_android_lifecycle google_maps_flutter_platform_interface]
- http 0.13.4 [async http_parser meta path]
- im_stepper 0.1.3 [flutter]
- intl 0.17.0 [clock path]
- overlay_support 2.0.1 [flutter async]
- page_transition 2.0.5 [flutter]
- path_provider 2.0.11 [flutter path_provider_android path_provider_ios path_provider_linux path_provider_macos path_provider_platform_interface path_provider_windows]
- provider 6.0.2 [collection flutter nested]
- shared_preferences 2.0.13 [flutter shared_preferences_android shared_preferences_ios shared_preferences_linux shared_preferences_macos shared_preferences_platform_interface shared_preferences_web shared_preferences_windows]
- sqflite 2.0.2+1 [flutter sqflite_common path]

dev dependencies:
- flutter_lints 1.0.4 [lints]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher material_color_utilities meta source_span stream_channel string_scanner term_glyph]

transitive dependencies:
- async 2.8.2 [collection meta]
- bloc 8.0.3 [meta]
- boolean_selector 2.1.0 [source_span string_scanner]
- cached_network_image_platform_interface 1.0.0 [flutter flutter_cache_manager]
- cached_network_image_web 1.0.1 [flutter flutter_cache_manager cached_network_image_platform_interface]
- characters 1.2.0
- charcode 1.3.1
- clock 1.1.0
- collection 1.16.0
- crypto 3.0.1 [collection typed_data]
- dio 4.0.6 [http_parser path]
- event_bus 2.0.0
- fake_async 1.3.0 [clock collection]
- ffi 1.1.2
- file 6.1.2 [meta path]
- firebase_core_platform_interface 4.4.1 [collection flutter meta plugin_platform_interface]
- firebase_core_web 1.6.5 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_messaging_platform_interface 3.5.3 [firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 2.4.3 [firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]
- flutter_blurhash 0.7.0 [flutter]
- flutter_cache_manager 3.3.0 [clock collection file flutter http path path_provider pedantic rxdart sqflite uuid]
- flutter_plugin_android_lifecycle 2.0.5 [flutter]
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta vector_math]
- geolocator_android 3.1.8 [flutter geolocator_platform_interface]
- geolocator_apple 2.1.3 [flutter geolocator_platform_interface]
- geolocator_platform_interface 4.0.5 [flutter plugin_platform_interface vector_math meta]
- geolocator_web 2.1.5 [flutter flutter_web_plugins geolocator_platform_interface]
- geolocator_windows 0.1.1 [flutter geolocator_platform_interface]
- google_maps_flutter_platform_interface 2.2.0 [collection flutter plugin_platform_interface stream_transform]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
- js 0.6.4
- lints 1.0.1
- logging 1.0.2
- matcher 0.12.11 [stack_trace]
- material_color_utilities 0.1.4
- meta 1.7.0
- nested 1.0.0 [flutter]
- octo_image 1.0.2 [flutter flutter_blurhash]
- path 1.8.1
- path_provider_android 2.0.12 [flutter path_provider_platform_interface]
- path_provider_ios 2.0.8 [flutter path_provider_platform_interface]
- path_provider_linux 2.1.5 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_macos 2.0.5 [flutter path_provider_platform_interface]
- path_provider_platform_interface 2.0.3 [flutter platform plugin_platform_interface]
- path_provider_windows 2.0.5 [ffi flutter path path_provider_platform_interface win32]
- pedantic 1.11.1
- platform 3.1.0
- plugin_platform_interface 2.1.2 [meta]
- process 4.2.4 [file path platform]
- rxdart 0.27.4
- shared_preferences_android 2.0.11 [flutter shared_preferences_platform_interface]
- shared_preferences_ios 2.1.0 [flutter shared_preferences_platform_interface]
- shared_preferences_linux 2.1.0 [file flutter path path_provider_linux path_provider_platform_interface shared_preferences_platform_interface]
- shared_preferences_macos 2.0.3 [flutter shared_preferences_platform_interface]
- shared_preferences_platform_interface 2.0.0 [flutter]
- shared_preferences_web 2.0.3 [flutter flutter_web_plugins shared_preferences_platform_interface]
- shared_preferences_windows 2.1.0 [file flutter path path_provider_platform_interface path_provider_windows shared_preferences_platform_interface]
- sky_engine 0.0.99
- socket_io_client 1.0.2 [socket_io_common js logging]
- socket_io_common 1.0.1 [logging]
- source_span 1.8.2 [collection path term_glyph]
- sqflite_common 2.2.1+1 [synchronized path meta]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- stream_transform 2.0.0
- string_scanner 1.1.0 [charcode source_span]
- synchronized 3.0.0+2
- term_glyph 1.2.0
- test_api 0.4.9 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.0 [collection]
- uuid 3.0.6 [crypto]
- vector_math 2.1.2
- win32 2.4.4 [ffi]
- xdg_directories 0.2.0+1 [meta path process]
```

</details>

---

**Comment by saileshbro** [comment] 2022-07-01 10:17
@darshankawar  Its the issue with the latest release, working fine with the last version.

**Comment by Zazo032** [comment] 2022-07-01 10:22
Probably a duplicate of #9012

**Comment by darshankawar** [comment] 2022-07-01 11:10
Closing this as a duplicate of https://github.com/firebase/flutterfire/issues/9012

**Closed by darshankawar** 2022-07-01 11:10 UTC
Labels: type: bug, Needs Attention, in triage
