### ISSUE TITLE
[firebase_analytics] Not recognizing Android app for new projects

### ISSUE THREAD

**Issue by marcellocamara** [firebase/flutterfire#12388] opened 2024-02-25 14:25 UTC
## Bug report

Hello, team.

I recently launched a new project, at stores, and discovered that Analytics is not recognizing the Android project as it should. It's only metrifying iOS project, identifying users online. Not working for Android.

![real-project](https://github.com/firebase/flutterfire/assets/18273071/6ab8ce61-e296-44f2-9527-351e3f3bc6ae)

So, I decided to made an exemple project to share with us
Example project: https://github.com/marcellocamara/issues/tree/master/Flutter3ImperativeApply

And the same problem, not recognizing Android at real time analytics:

![Real-time](https://github.com/firebase/flutterfire/assets/18273071/2a90ef6f-1d6e-4dc0-8418-09f95d51231d)

There is a new way to add Firebase at the projects, just using the flutterfire CLI. There is no necessity of add manual lines of code at gradle files, as before. Follow this documentation: https://firebase.google.com/docs/flutter/setup
See that is no gradle new lines of code for android native project.

### Steps to reproduce

1. Go to the example project and validate all the data (I recommend you create a new one to share it correctly on your firebase)
2. Launch Android app
3. See the analytics dashboard to see if Android app appears as user online

### Expected behavior

Analytics recognizing Android apps with online users and record users events.

### Sample project

https://github.com/marcellocamara/issues/tree/master/Flutter3ImperativeApply

---

## Additional context

I don't know the problem. But the only thing that is complety new, is the android gradle, for the new projects, as the migration guide: https://docs.flutter.dev/release/breaking-changes/flutter-gradle-plugin-apply

Could be this ?

---

### Flutter doctor

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 3.19.1, on macOS 14.3.1 23D60 darwin-x64, locale pt-BR)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.1)
[✓] Connected device (2 available)
[✓] Network resources

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 3.3.0
Flutter SDK 3.19.1
flutter3imperativeapply 1.0.0+1

dependencies:
- cupertino_icons 1.0.6
- firebase_analytics 10.8.6 [firebase_analytics_platform_interface firebase_analytics_web firebase_core firebase_core_platform_interface flutter]
- firebase_core 2.25.4 [firebase_core_platform_interface firebase_core_web flutter meta]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]

dev dependencies:
- flutter_lints 3.0.1 [lints]
- flutter_test 0.0.0 [flutter test_api matcher path fake_async clock stack_trace vector_math leak_tracker_flutter_testing async boolean_selector characters collection leak_tracker leak_tracker_testing material_color_utilities meta source_span stream_channel string_scanner term_glyph vm_service]

transitive dependencies:
- _flutterfire_internals 1.3.22 [collection firebase_core firebase_core_platform_interface flutter meta]
- async 2.11.0 [collection meta]
- boolean_selector 2.1.1 [source_span string_scanner]
- characters 1.3.0
- clock 1.1.1
- collection 1.18.0
- fake_async 1.3.1 [clock collection]
- firebase_analytics_platform_interface 3.9.6 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_analytics_web 0.5.5+18 [_flutterfire_internals firebase_analytics_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- firebase_core_platform_interface 5.0.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.11.4 [firebase_core_platform_interface flutter flutter_web_plugins js meta web]
- flutter_web_plugins 0.0.0 [flutter characters collection material_color_utilities meta vector_math]
- js 0.6.7 [meta]
- leak_tracker 10.0.0 [clock collection meta path vm_service]
- leak_tracker_flutter_testing 2.0.1 [flutter leak_tracker leak_tracker_testing matcher meta]
- leak_tracker_testing 2.0.1 [leak_tracker matcher meta]
- lints 3.0.0
- matcher 0.12.16+1 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.8.0 [collection]
- meta 1.11.0
- path 1.9.0
- plugin_platform_interface 2.1.8 [meta]
- sky_engine 0.0.99
- source_span 1.10.0 [collection path term_glyph]
- stack_trace 1.11.1 [path]
- stream_channel 2.1.2 [async]
- string_scanner 1.2.0 [source_span]
- term_glyph 1.2.1
- test_api 0.6.1 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph]
- vector_math 2.1.4
- vm_service 13.0.0
- web 0.4.2
```

</details>

---

**Comment by dmvvilela** [comment] 2024-02-26 02:22
Same here, on the terminal it says something like "app_id not found, analytics disabled".

Tried reconfiguring with flutterfire cli and nothing.. still only ios working.

**Comment by darshankawar** [comment] 2024-02-26 11:30
@marcellocamara @dmvvilela 
I recently had verified using plugin example with which I observed that the `test_event` were being captured properly as I commented [here](https://github.com/firebase/flutterfire/issues/12178#issuecomment-1905722614).
You may check the plugin example and see if using it, you still get same behavior as reported or not.

**Comment by marcellocamara** [comment] 2024-02-26 12:04
> @marcellocamara @dmvvilela I recently had verified using plugin example with which I observed that the `test_event` were being captured properly as I commented [here](https://github.com/firebase/flutterfire/issues/12178#issuecomment-1905722614). You may check the plugin example and see if using it, you still get same behavior as reported or not.

Hi, @darshankawar!

This is a different scenario. 
Check the example android antive code and this migration guide: https://docs.flutter.dev/release/breaking-changes/flutter-gradle-plugin-apply
I've checked the example code project that you've tested. The gradle configurations is totally different.

**Comment by darshankawar** [comment] 2024-02-27 10:20
Thanks for the details @marcellocamara 
I am verifying based on the info you shared above.
Meantime, can you also [try](https://stackoverflow.com/a/60915019) this and see if it sends the data from client or not ?

**Comment by DouglasMedeiros** [comment] 2024-02-28 01:15
Same here :(

Any solution?

**Comment by marcellocamara** [comment] 2024-02-28 01:29
> Thanks for the details @marcellocamara I am verifying based on the info you shared above. Meantime, can you also [try](https://stackoverflow.com/a/60915019) this and see if it sends the data from client or not ?

@darshankawar , done your suggestion without success. I've tested on my production app. But the gradle settings and CLI used to configure the firebase is the same as the example project [here](https://github.com/marcellocamara/issues/tree/master/Flutter3ImperativeApply).

![Captura de Tela 2024-02-27 às 22 24 27](https://github.com/firebase/flutterfire/assets/18273071/25d56348-a312-4e07-b018-6f923d05843e)

<details><summary>Logs</summary>

```
cello@MacBook-Pro-de-Marcello loterias % adb shell setprop debug.firebase.analytics.app marcello.dev.loterias
cello@MacBook-Pro-de-Marcello loterias % adb shell setprop log.tag.FA VERBOSE
cello@MacBook-Pro-de-Marcello loterias % adb shell setprop log.tag.FA-SVC VERBOSE
cello@MacBook-Pro-de-Marcello loterias % adb logcat -v time -s FA FA-SVC
--------- beginning of main
02-25 00:16:13.041 I/FA      (19920): App measurement initialized, version: 84008
02-25 00:16:13.042 I/FA      (19920): To enable debug logging run: adb shell setprop log.tag.FA VERBOSE
02-25 00:16:13.042 I/FA      (19920): To enable faster debug mode event logging run:
02-25 00:16:13.042 I/FA      (19920):   adb shell setprop debug.firebase.analytics.app com.google.android.apps.youtube.music
02-25 00:18:40.202 V/FA      (20203): Deferring to Google Analytics for Firebase for event data collection. https://firebase.google.com/docs/analytics
02-25 00:18:41.277 I/FA      (20203): App measurement initialized, version: 84008
02-25 00:18:41.278 I/FA      (20203): To enable debug logging run: adb shell setprop log.tag.FA VERBOSE
02-25 00:18:41.279 I/FA      (20203): To enable faster debug mode event logging run:
02-25 00:18:41.279 I/FA      (20203):   adb shell setprop debug.firebase.analytics.app marcello.dev.loterias
02-25 00:18:41.336 E/FA      (20203): Missing google_app_id. Firebase Analytics disabled. See https://goo.gl/NAOOOI
02-25 00:18:53.123 E/FA-SVC  (14900): Missing google_app_id. Firebase Analytics disabled. See https://goo.gl/NAOOOI
02-25 00:18:53.183 E/FA-SVC  (14900): Missing google_app_id. Firebase Analytics disabled. See https://goo.gl/NAOOOI
02-25 00:18:53.623 E/FA-SVC  (14900): Missing google_app_id. Firebase Analytics disabled. See https://goo.gl/NAOOOI
02-25 00:29:19.647 V/FA      (21505): Deferring to Google Analytics for Firebase for event data collection. https://firebase.google.com/docs/analytics
02-25 00:29:20.138 I/FA      (21505): App measurement initialized, version: 84008
02-25 00:29:20.139 I/FA      (21505): To enable debug logging run: adb shell setprop log.tag.FA VERBOSE
02-25 00:29:20.139 I/FA      (21505): To enable faster debug mode event logging run:
02-25 00:29:20.139 I/FA      (21505):   adb shell setprop debug.firebase.analytics.app marcello.dev.loterias
02-25 00:29:20.174 E/FA      (21505): Missing google_app_id. Firebase Analytics disabled. See https://goo.gl/NAOOOI
02-25 00:29:24.128 I/FA      (21621): App measurement initialized, version: 85001
02-25 00:29:24.128 I/FA      (21621): To enable debug logging run: adb shell setprop log.tag.FA VERBOSE
02-25 00:29:24.128 I/FA      (21621): To enable faster debug mode event logging run:
02-25 00:29:24.128 I/FA      (21621):   adb shell setprop debug.firebase.analytics.app com.google.android.youtube
02-25 00:29:32.208 E/FA-SVC  (14900): Missing google_app_id. Firebase Analytics disabled. See https://goo.gl/NAOOOI
02-25 00:29:32.238 E/FA-SVC  (14900): Missing google_app_id. Firebase Analytics disabled. See https://goo.gl/NAOOOI
02-25 00:29:32.731 E/FA-SVC  (14900): Missing google_app_id. Firebase Analytics disabled. See https://goo.gl/NAOOOI
02-25 00:44:35.527 I/FA      (22209): App measurement initialized, version: 84008
02-25 00:44:35.527 I/FA      (22209): To enable debug logging run: adb shell setprop log.tag.FA VERBOSE
02-25 00:44:35.527 I/FA      (22209): To enable faster debug mode event logging run:
02-25 00:44:35.527 I/FA      (22209):   adb shell setprop debug.firebase.analytics.app com.google.android.apps.youtube.music
02-25 00:44:42.460 V/FA      (22499): Deferring to Google Analytics for Firebase for event data collection. https://firebase.google.com/docs/analytics
02-25 00:44:44.262 I/FA      (22499): App measurement initialized, version: 84008
02-25 00:44:44.262 I/FA      (22499): To enable debug logging run: adb shell setprop log.tag.FA VERBOSE
02-25 00:44:44.272 I/FA      (22499): To enable faster debug mode event logging run:
02-25 00:44:44.272 I/FA      (22499):   adb shell setprop debug.firebase.analytics.app marcello.dev.loterias
02-25 00:44:44.336 E/FA      (22499): Missing google_app_id. Firebase Analytics disabled. See https://goo.gl/NAOOOI
02-25 00:44:49.797 I/FA      (22499): Application backgrounded at: timestamp_millis: 1708832685687
02-25 00:48:37.862 V/FA      (23240): Deferring to Google Analytics for Firebase for event data collection. https://firebase.google.com/docs/analytics
02-25 00:48:38.244 I/FA      (23240): App measurement initialized, version: 84008
02-25 00:48:38.244 I/FA      (23240): To enable debug logging run: adb shell setprop log.tag.FA VERBOSE
02-25 00:48:38.245 I/FA      (23240): To enable faster debug mode event logging run:
02-25 00:48:38.245 I/FA      (23240):   adb shell setprop debug.firebase.analytics.app marcello.dev.loterias
02-25 00:48:38.252 E/FA      (23240): Missing google_app_id. Firebase Analytics disabled. See https://goo.gl/NAOOOI
02-25 00:48:51.535 E/FA-SVC  (14900): Missing google_app_id. Firebase Analytics disabled. See https://goo.gl/NAOOOI
02-25 00:48:51.551 E/FA-SVC  (14900): Missing google_app_id. Firebase Analytics disabled. See https://goo.gl/NAOOOI
02-25 00:48:52.028 E/FA-SVC  (14900): Missing google_app_id. Firebase Analytics disabled. See https://goo.gl/NAOOOI
02-25 10:52:51.355 I/FA      (24178): App measurement initialized, version: 84008
02-25 10:52:51.357 I/FA      (24178): To enable debug logging run: adb shell setprop log.tag.FA VERBOSE
02-25 10:52:51.358 I/FA      (24178): To enable faster debug mode event logging run:
02-25 10:52:51.358 I/FA      (24178):   adb shell setprop debug.firebase.analytics.app marcello.dev.flutter3imperativeapply
02-25 10:52:51.373 E/FA      (24178): Missing google_app_id. Firebase Analytics disabled. See https://goo.gl/NAOOOI
02-25 10:52:51.373 E/FA      (24178): Uploading is not possible. App measurement disabled
02-25 10:52:51.455 I/FA      (24178): Tag Manager is not found and thus will not be used
02-25 10:54:28.188 I/FA      (24438): App measurement initialized, version: 84008
02-25 10:54:28.189 I/FA      (24438): To enable debug logging run: adb shell setprop log.tag.FA VERBOSE
02-25 10:54:28.189 I/FA      (24438): To enable faster debug mode event logging run:
02-25 10:54:28.189 I/FA      (24438):   adb shell setprop debug.firebase.analytics.app com.google.android.apps.youtube.music
02-25 10:54:31.181 I/FA      (24441): App measurement initialized, version: 85001
02-25 10:54:31.181 I/FA      (24441): To enable debug logging run: adb shell setprop log.tag.FA VERBOSE
02-25 10:54:31.181 I/FA      (24441): To enable faster debug mode event logging run:
02-25 10:54:31.181 I/FA      (24441):   adb shell setprop debug.firebase.analytics.app com.google.android.youtube
02-25 10:55:04.839 I/FA      (24972): App measurement initialized, version: 84008
02-25 10:55:04.841 I/FA      (24972): To enable debug logging run: adb shell setprop log.tag.FA VERBOSE
02-25 10:55:04.843 I/FA      (24972): To enable faster debug mode event logging run:
02-25 10:55:04.843 I/FA      (24972):   adb shell setprop debug.firebase.analytics.app marcello.dev.flutter3imperativeapply
02-25 10:55:04.873 E/FA      (24972): Missing google_app_id. Firebase Analytics disabled. See https://goo.gl/NAOOOI
02-25 10:55:04.874 E/FA      (24972): Uploading is not possible. App measurement disabled
02-25 10:55:04.903 I/FA      (24972): Tag Manager is not found and thus will not be used
02-25 11:00:05.564 E/FA      (24972): Missing google_app_id. Firebase Analytics disabled. See https://goo.gl/NAOOOI
02-25 11:50:01.184 I/FA      (26172): App measurement initialized, version: 84008
02-25 11:50:01.184 I/FA      (26172): To enable debug logging run: adb shell setprop log.tag.FA VERBOSE
02-25 11:50:01.185 I/FA      (26172): To enable faster debug mode event logging run:
02-25 11:50:01.185 I/FA      (26172):   adb shell setprop debug.firebase.analytics.app marcello.dev.passwordmanager
02-25 11:50:02.328 I/FA      (26172): Tag Manager is not found and thus will not be used
02-25 11:50:07.532 W/FA-SVC  (14900): Service response is missing Install Referrer install timestamp
02-25 12:18:38.602 I/FA      (28084): App measurement initialized, version: 84008
02-25 12:18:38.602 I/FA      (28084): To enable debug logging run: adb shell setprop log.tag.FA VERBOSE
02-25 12:18:38.603 I/FA      (28084): To enable faster debug mode event logging run:
02-25 12:18:38.603 I/FA      (28084):   adb shell setprop debug.firebase.analytics.app marcello.dev.passwordmanager
02-25 16:13:18.858 I/FA      (28947): App measurement initialized, version: 85001
02-25 16:13:18.858 I/FA      (28947): To enable debug logging run: adb shell setprop log.tag.FA VERBOSE
02-25 16:13:18.859 I/FA      (28947): To enable faster debug mode event logging run:
02-25 16:13:18.859 I/FA      (28947):   adb shell setprop debug.firebase.analytics.app com.google.android.youtube
02-25 16:37:23.565 I/FA      (30728): App measurement initialized, version: 85001
02-25 16:37:23.565 I/FA      (30728): To enable debug logging run: adb shell setprop log.tag.FA VERBOSE
02-25 16:37:23.567 I/FA      (30728): To enable faster debug mode event logging run:
02-25 16:37:23.567 I/FA      (30728):   adb shell setprop debug.firebase.analytics.app com.google.android.youtube
02-26 01:39:33.693 V/FA      (32708): Deferring to Google Analytics for Firebase for event data collection. https://firebase.google.com/docs/analytics
02-26 01:39:34.667 I/FA      (32708): App measurement initialized, version: 84008
02-26 01:39:34.668 I/FA      (32708): To enable debug logging run: adb shell setprop log.tag.FA VERBOSE
02-26 01:39:34.670 I/FA      (32708): To enable faster debug mode event logging run:
02-26 01:39:34.670 I/FA      (32708):   adb shell setprop debug.firebase.analytics.app marcello.dev.loterias
02-26 01:39:34.678 E/FA      (32708): Missing google_app_id. Firebase Analytics disabled. See https://goo.gl/NAOOOI
02-26 01:39:57.928 E/FA-SVC  (14900): Missing google_app_id. Firebase Analytics disabled. See https://goo.gl/NAOOOI
02-26 01:39:58.035 E/FA-SVC  (14900): Missing google_app_id. Firebase Analytics disabled. See https://goo.gl/NAOOOI
02-26 01:45:32.611 W/FA-SVC  (14900): Interrupted in onRunTask while uploading
02-27 22:22:50.302 V/FA      ( 2031): Deferring to Google Analytics for Firebase for event data collection. https://firebase.google.com/docs/analytics
02-27 22:22:51.556 V/FA      ( 2031): App measurement disabled via the init parameters
02-27 22:22:51.560 I/FA      ( 2031): App measurement initialized, version: 84008
02-27 22:22:51.561 I/FA      ( 2031): To enable debug logging run: adb shell setprop log.tag.FA VERBOSE
02-27 22:22:51.561 I/FA      ( 2031): Faster debug mode event logging enabled. To disable, run:
02-27 22:22:51.561 I/FA      ( 2031):   adb shell setprop debug.firebase.analytics.app .none.
02-27 22:22:51.561 D/FA      ( 2031): Debug-level message logging enabled
02-27 22:22:51.570 E/FA      ( 2031): Missing google_app_id. Firebase Analytics disabled. See https://goo.gl/NAOOOI
02-27 22:22:51.580 D/FA      ( 2031): Resetting analytics data (FE)
02-27 22:22:51.582 D/FA      ( 2031): Analytics Storage consent is not granted
02-27 22:22:51.582 D/FA      ( 2031): Resetting session stitching token to null
02-27 22:22:51.583 V/FA      ( 2031): App measurement setting deferred collection: true
02-27 22:22:51.630 D/FA      ( 2031): Analytics Storage consent is not granted
02-27 22:22:51.630 D/FA      ( 2031): Resetting session stitching token to null
02-27 22:22:51.635 V/FA      ( 2031): Connecting to remote service
02-27 22:22:51.644 D/FA      ( 2031): Analytics Storage consent is not granted
02-27 22:22:51.644 D/FA      ( 2031): Resetting session stitching token to null
02-27 22:22:53.845 V/FA      ( 2031): Activity resumed, time: 12613736
02-27 22:22:53.872 D/FA      ( 2031): Event not sent since app measurement is disabled
02-27 22:22:53.872 V/FA      ( 2031): Connection attempt already in progress
02-27 22:22:54.933 D/FA      ( 2031): Connected to remote service
02-27 22:22:54.934 V/FA      ( 2031): Processing queued up service tasks: 2
02-27 22:22:54.961 V/FA-SVC  (14900): Setting consent, package, consent: marcello.dev.loterias, source=1P_INIT,ad_storage=denied,analytics_storage=denied
02-27 22:22:59.950 V/FA      ( 2031): Inactivity, disconnecting from the service
02-27 22:23:09.002 D/FA      ( 2031): Analytics Storage consent is not granted
02-27 22:23:09.003 D/FA      ( 2031): Resetting session stitching token to null
02-27 22:23:09.018 V/FA      ( 2031): Connecting to remote service
02-27 22:23:09.112 D/FA      ( 2031): Connected to remote service
02-27 22:23:09.144 V/FA      ( 2031): Processing queued up service tasks: 1
02-27 22:23:09.148 E/FA-SVC  (14900): Missing google_app_id. Firebase Analytics disabled. See https://goo.gl/NAOOOI
02-27 22:23:09.172 D/FA      ( 2031): Analytics Storage consent is not granted
02-27 22:23:09.173 D/FA      ( 2031): Resetting session stitching token to null
02-27 22:23:09.177 E/FA-SVC  (14900): Missing google_app_id. Firebase Analytics disabled. See https://goo.gl/NAOOOI
02-27 22:23:14.181 V/FA      ( 2031): Inactivity, disconnecting from the service
02-27 22:23:16.963 V/FA      ( 2031): Recording user engagement, ms: 23126
02-27 22:23:16.964 D/FA      ( 2031): Event not sent since app measurement is disabled
02-27 22:23:16.964 V/FA      ( 2031): Connecting to remote service
02-27 22:23:16.964 V/FA      ( 2031): Activity paused, time: 12636862
02-27 22:23:16.978 D/FA      ( 2031): Connected to remote service
02-27 22:23:16.979 V/FA      ( 2031): Processing queued up service tasks: 1
02-27 22:23:18.966 D/FA      ( 2031): Application going to the background
02-27 22:23:18.968 I/FA      ( 2031): Application backgrounded at: timestamp_millis: 1709083396964
02-27 22:23:20.263 V/FA      ( 2031): Activity resumed, time: 12640162
02-27 22:23:20.424 D/FA      ( 2031): Event not sent since app measurement is disabled
02-27 22:23:25.321 V/FA      ( 2031): Inactivity, disconnecting from the service
```

**Comment by russellwheatley** [comment] 2024-02-28 08:59
Hey @marcellocamara @dmvvilela - presumably this also fails on android in debug mode?

**Comment by marcellocamara** [comment] 2024-02-28 11:24
> Hey @marcellocamara @dmvvilela - presumably this also fails on android in debug mode?

Yes!
Just create a new flutter project using 3.19.1 (I used Android Studio, with Flutter plugin 78.0.1, Dart plugin 231.9411, to create it - instead of command line code) and use the `flutterfire_cli` to link Firebase. 
Only iOS will identify correctly.
Android did not identify some products as Analytics, Latests Release (only appears iOS), Debug View, etc

**Comment by russellwheatley** [comment] 2024-02-28 14:49
Could you try the dev version of flutterfire CLI (It's fairly stable at this point and should be upgraded at some point in the futre) which fixes [android build.gradle setup](https://github.com/invertase/flutterfire_cli/pull/254) for latest Flutter, @marcellocamara?

```
dart pub global activate flutterfire_cli 0.3.0-dev.19 --overwrite
```

Here is documentation for it: https://github.com/invertase/flutterfire_cli/blob/main/README.md

Let me know how it goes 🙏

**Comment by dmvvilela** [comment] 2024-02-28 15:51
Hey @russellwheatley shouldn't it just work with firebase_options.dart file?

Reconfiguring things with flutterfire is a problem to me at least, cause i need dev/prod environments. So everytime i reconfigure with flutterfire i have to make some manual changes.. and google plist file is just bad for this for example (and I end up having to delete it).

**Comment by russellwheatley** [comment] 2024-02-29 11:00
@dmvvilela - I recommend only using the firebase_options file for web platform. [See this comment](https://github.com/invertase/flutterfire_cli/issues/14#issuecomment-1270781026).

**Comment by MattyBoy4444** [comment] 2024-03-01 04:37
> cli

I tried with dev.19 and it still doesn't work

**Comment by marcellocamara** [comment] 2024-03-01 04:39
> @russellwheatley 
Could you try the dev version of flutterfire CLI (It's fairly stable at this point and should be upgraded at some point in the future) which fixes [android build.gradle setup](https://github.com/invertase/flutterfire_cli/pull/254) for latest Flutter, @marcellocamara?
> 
> ```
> dart pub global activate flutterfire_cli 0.3.0-dev.19 --overwrite
> ```
> 
> Here is documentation for it: https://github.com/invertase/flutterfire_cli/blob/main/README.md
> 
> Let me know how it goes 🙏

@russellwheatley 
I've tested your suggestion, with flutterfire_cli 0.3.0-dev.19 and the flutterfire configure does not change a single line of android native code...
Same result. Not recognizing Android at Firebase analytics.

The same thing is logged on console:
`E/FA (27897): Missing google_app_id. Firebase Analytics disabled. See https://goo.gl/NAOOOI`

**Comment by marcellocamara** [comment] 2024-03-01 14:11
Team, we have 3 points to discuss here

1) I don't think this thread should be closed until this is fixed
2) the flutterfire_cli is wrong
3) the documentation of migration guide is wrong for the current firebase packages

I've been messaging firebase support email and an angel, called Dani, helped with this suggestion:
![Captura de Tela 2024-03-01 às 11 02 04](https://github.com/firebase/flutterfire/assets/18273071/9afb0822-2880-4f94-9fe2-a216da848e2c)

So, what I did test:
change manually the android native code, just this two files: android/settings.gradle and android/app/build.gradle

settings.gradle
```
plugins {
    ...
    id "com.google.gms.google-services" version "4.4.0" apply false
}
```
build.gradle
```
plugins {
    ...
    id "com.google.gms.google-services"
}
```

And, the result: **NOT RECONIZING ANDROID APP**
![Captura de Tela 2024-03-01 às 10 59 12](https://github.com/firebase/flutterfire/assets/18273071/925100a5-d603-49f8-80f6-c6c15389ad38)

...

So, changing only the **google-services** version to `4.3.15` see this result:

![Captura de Tela 2024-03-01 às 10 01 41](https://github.com/firebase/flutterfire/assets/18273071/1eac919b-800b-4374-bf7d-5eb209baca26)

The point is: 
- Why flutterfire_cli is not setting this manual configuration on android native side ? For new developers, with new flutter, firebase packages and flutterfire_cli is not working. It's a big problem.
- Why the [migration guide](https://docs.flutter.dev/release/breaking-changes/flutter-gradle-plugin-apply) is telling devs to set the version 4.4.0 - *THAT IS NOT WORKING* ?

So, my problem is currently fixed. Bug this is a serious problem that Firebase team should work on.

**Comment by alldetectai** [comment] 2024-03-03 19:08
@marcellocamara is correct, the migration guide does not present a working migration for newer versions and flutterfire_cli does not work as expected. Changing the google-services version to 4.3.15 and making the edits to `settings.gradle` and `app/build.gradle` shown [in the previous post](https://github.com/firebase/flutterfire/issues/12388#issuecomment-1973275592) allows Firebase Analytics to function for Android.

**Comment by Lyokone** [comment] 2024-03-04 08:42
Hello, just migrated the example app for Analytics and I seem to get the correct result in the Analytics console. Can you check that you are using a similar configuration? https://github.com/firebase/flutterfire/pull/12425

**Comment by marcellocamara** [comment] 2024-03-04 12:31
> Hello, just migrated the example app for Analytics and I seem to get the correct result in the Analytics console. Can you check that you are using a similar configuration? #12425

@Lyokone it's not complety equal:
1) [your Firebase example coomited project build.gradle](https://github.com/firebase/flutterfire/blob/chore/migrate-analytics-android/packages/firebase_analytics/firebase_analytics/example/android/build.gradle) vs [my new Flutter 3.19.1 commited project gradle](https://github.com/marcellocamara/issues/blob/master/Flutter3ImperativeApply/android/build.gradle)✅ 
2) [your Firebase example commited project settings.gradle](https://github.com/firebase/flutterfire/blob/chore/migrate-analytics-android/packages/firebase_analytics/firebase_analytics/example/android/settings.gradle) vs [my new Flutter 3.19.1 commited project settings.gradle](https://github.com/marcellocamara/issues/blob/master/Flutter3ImperativeApply/android/settings.gradle)❌ 
3) [your Firebase example commited project app/build.gradle](https://github.com/firebase/flutterfire/blob/chore/migrate-analytics-android/packages/firebase_analytics/firebase_analytics/example/android/app/build.gradle) vs [my new Flutter 3.19.1 commited project app/build.gradle](https://github.com/marcellocamara/issues/blob/master/Flutter3ImperativeApply/android/app/build.gradle)❌ 

There is a big difference here: you're setting manually the android native code side. The `flutterfire_cli` **did not do** this. That is the big problem discussing here. Developers, only reading the documentation, will not set any native code configuration, as [this guide](https://firebase.google.com/docs/flutter/setup?platform=android) did not telling to do.

Another point is that [you tested with google-services 4.4.1](https://github.com/firebase/flutterfire/blob/chore/migrate-analytics-android/packages/firebase_analytics/firebase_analytics/example/android/settings.gradle#L22), I did with 4.4.0 (not works) and 4.3.15 (works) : 

Finishing, this line I don't know if something is wrong, but it's different from new example projects: https://github.com/firebase/flutterfire/blob/chore/migrate-analytics-android/packages/firebase_analytics/firebase_analytics/example/android/settings.gradle#L8

**Comment by alldetectai** [comment] 2024-03-04 15:53
@Lyokone your PR doesn't address the actual problem, does it? You are manually patching the android example files. A resolution that would appropriately close this issue would be one that addresses the issues with `flutterfire_cli` which is supposed to patch the android files, and this is the main issue here. So, if 4.4.1 works, then great - I haven't tested it yet. But, in any case - `flutterfire_cli` is supposed to patch the android files and it is not currently doing that.

**Comment by dmvvilela** [comment] 2024-03-04 20:23
@russellwheatley Only for web? This is what enables me to use dev and prod environment without having to create a bunch of shell files and making the DX absolutely horrible. Flutter fire has come a long way and I believe this is the best approach (and as for now everything works except for analytics). 

Now, this changing of google services version is not really a fix is it? Someone might need a different version. The underlying problem should be aimed.

**Comment by Lyokone** [comment] 2024-03-05 12:47
@alldetectai it's true that we have to update the CLI, and it will be coming 👍

**Comment by Mairramer** [comment] 2024-03-12 11:54
I don't know if I can put it here, but how do I work with flavor in this version?
In other projects I have the prod and stg folders, and it pulls the `google-services.json` file from each folder. But in this version I am being "forced" to place a single file in the root folder `android/app/...`

**Comment by russellwheatley** [comment] 2024-03-12 13:02
@marcellocamara - We have a fix for the latest gradle setup that has been merged: https://github.com/invertase/flutterfire_cli/pull/254

We just need to release. We have another fix for crashlytics de-obfuscating stack traces that we are looking to have merged soon: https://github.com/invertase/flutterfire_cli/pull/260

Once this has been merged, I will release another dev version and will update this channel.

I have a vague memory of leaving the [google services plugin at 4.3.15](https://github.com/invertase/flutterfire_cli/blob/main/packages/flutterfire_cli/lib/src/firebase/firebase_android_writes.dart#L35) because version `4.4.0` didn't work as intended. 

 I'll start the process of moving dev version to general release. In the meanwhile, I will let you know when I have another dev version release which ought to update gradle files (including `settings.gradle` file). Sorry for the confusion 🙏

**Comment by russellwheatley** [comment] 2024-03-12 16:28
@marcellocamara - We have just released the latest FlutterFire CLI dev version which you can install with the following command:
```
dart pub global activate flutterfire_cli 0.3.0-dev.20 --overwrite
```
This should update your gradle setup appropriately. Let me know how it goes, thanks

**Comment by skela** [comment] 2024-03-13 13:25
@russellwheatley  just a heads up, re-running configure or reconfigure via flutterfire_cli 0.3.0-dev.20 seems to add the google services line into plugins, even if its already there, resulting in duplicate lines.

**Comment by russellwheatley** [comment] 2024-03-13 14:31
@skela - thanks for the heads up! Do you mind opening an issue on: https://github.com/invertase/flutterfire_cli and I will address it. Thanks 😄

**Comment by marcellocamara** [comment] 2024-03-13 23:18
> @marcellocamara - We have just released the latest FlutterFire CLI dev version which you can install with the following command:
> 
> ```
> dart pub global activate flutterfire_cli 0.3.0-dev.20 --overwrite
> ```
> 
> This should update your gradle setup appropriately. Let me know how it goes, thanks

@russellwheatley now it works adding the `google-services.json` file and the `native code` below 👍🏻 

![Captura de Tela 2024-03-13 às 20 16 04](https://github.com/firebase/flutterfire/assets/18273071/a6eef451-483e-41f9-bd3c-2cbdcdee03e3)

![Captura de Tela 2024-03-13 às 20 16 18](https://github.com/firebase/flutterfire/assets/18273071/beba20e0-a968-40a8-80ce-c7dce1a04a8d)

**Comment by dmvvilela** [comment] 2024-03-14 03:01
> @marcellocamara - We have just released the latest FlutterFire CLI dev version which you can install with the following command:
> 
> ```
> dart pub global activate flutterfire_cli 0.3.0-dev.20 --overwrite
> ```
> 
> This should update your gradle setup appropriately. Let me know how it goes, thanks

Didn't work here, it didn't set anything on settings.gradle file.. just on build.gradle file

But I added it manually and now is compiling again..

**Comment by russellwheatley** [comment] 2024-03-14 08:53
@marcellocamara - the `firebase.json` file is by design. It allows you to run `flutterfire reconfigure` without all the arguments which will update all service files and write necessary dependencies in your gradle setup if you update your firebase project.

@dmvvilela - I have created an issue for latest gradle setup bugs. Could you please paste your `settings.gradle` file there and I can test/fix? Here is the issue: https://github.com/invertase/flutterfire_cli/issues/267

**Comment by skela** [comment] 2024-03-14 22:32
i've the same issues btw, tried every method and comment in this thread, but still not able to get it working.
even after the error about missing google app id goes away, im not getting anything to show up in the firebase debug view. (and yes i have enabled it using the adb command).

the only difference with this setup is that my project is a flutter project created like this:
`flutter create -t plugin --platforms android,ios yay`

flutter pub add commands done at the project root, app is in the example folder.

**Comment by russellwheatley** [comment] 2024-03-15 07:52
> @marcellocamara - We have just released the latest FlutterFire CLI dev version which you can install with the following command:
> 
> ```
> dart pub global activate flutterfire_cli 0.3.0-dev.20 --overwrite
> ```
> 
> This should update your gradle setup appropriately. Let me know how it goes, thanks

@skela - did you use the latest FlutterFire CLI as noted above and run `flutterfire configure`? Did you see the updates in gradle setup? (i.e. `settings.gradle` & `app/build.gradle`).

**Comment by russellwheatley** [comment] 2024-03-15 07:56
@skela - please update this issue with your problem: https://github.com/invertase/flutterfire_cli/issues/267

**Comment by russellwheatley** [comment] 2024-03-15 15:44
Closing out this issue as it is a configuration issue, not a bug in analytics plugin. Any further configuration issues ought to be addressed here: https://github.com/invertase/flutterfire_cli/issues/267

**Closed by russellwheatley** 2024-03-15 15:44 UTC
Labels: type: bug, plugin: analytics, Needs Attention
