### ISSUE TITLE
mach-o/utils.h file not found

### ISSUE THREAD

**Issue by khushAdmin** [firebase/flutterfire#11938] opened 2023-11-22 14:10 UTC
### Description
I implement firebase crashlatyics in android and iOS via firebase_crashlytics plugin.This plugin support android/iOS/macOS.But I try to run my flutter project in macOS with this the 'mach-o/utils.h' file not found issue occurred.

macos/Pods/FirebaseCrashlytics/Crashlytics/Shared/FIRCLSMachO/FIRCLSMachO.m:24:10: fatal error: 'mach-o/utils.h' file not found
#include <mach-o/utils.h>
         ^~~~~~~~~~~~~~~~

### Firebase SDK Version

10.9

### Xcode Version

14.3

### Installation Method

CocoaPods

### Firebas e Product(s)

Crashlytics

### Targeted Platforms

macOS

### If using Swift Package Manager, the project's Package.resolved

<details>
<summary>Expand <code>Package.resolved</code> snippet</summary>
<br>

```json

Replace this line with the contents of your Package.resolved.

```

</details>

### If using CocoaPods, the project's Podfile.lock

<details>
<summary>Expand <code>Podfile.lock</code> snippet</summary>
<br>

```yml

Replace this line with the contents of your Podfile.lock!

```

</details>

**Comment by paulb777** [comment] 2023-11-23 15:42
Transferred issue to the flutterfire repo, since it the problem is likely related to the flutter configuration

**Comment by danagbemava-nc** [comment] 2023-11-24 10:17
Closing this as a duplicate of https://github.com/firebase/flutterfire/issues/11936

**Closed by danagbemava-nc** 2023-11-24 10:17 UTC
Labels: in triage
