### ISSUE TITLE
🐛 [firebase_app_check] Debug token never created on iOS

### ISSUE THREAD

**Issue by mzkai** [firebase/flutterfire#8897] opened 2022-06-13 14:50 UTC
## Bug report
AppCheck is correctly registered and working for both iOS and Android in production and on physical devices. However, following the documentation on how to add a debug provider in a simulator, the debug token is never shown. This is the case whether or not I build and run the app directly through Xcode.

The documentation followed: **https://firebase.google.com/docs/app-check/ios/debug-provider**
This documentation is followed, as the Flutter doc simply points to the iOS setup (https://firebase.google.com/docs/app-check/flutter/debug-provider)

### Steps to reproduce
Following  the steps provided in the documentation, I have:

1) Added AppCheckDebugProviderFactory to my AppDelegate.swift file. I have not included _FirebaseApp.configure()_, as this does not seem to work with Flutter:
```
import UIKit
import Flutter
import Firebase

@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {
    GeneratedPluginRegistrant.register(with: self)

    let providerFactory = AppCheckDebugProviderFactory()
    AppCheck.setAppCheckProviderFactory(providerFactory)

    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }
}
```

2) Set -FIRDebugEnabled flag in Product > Scheme > Edit scheme in Xcode

![FIRDebugEnabled](https://user-images.githubusercontent.com/32619354/173375124-d631c558-7620-40bf-a2aa-e82ac22c0449.png)

3) Run application in Xcode (with the app deleted from the simulator before running, to ensure a fresh install)
Logs do not anywhere show, as would have been expected
```
[Firebase/AppCheck][I-FAA001001] Firebase App Check Debug Token:
123a4567-b89c-12d3-e456-789012345678
```

## Version
flutter: 3.0.2
firebase_app_check: ^0.0.6+13

**Comment by maheshmnj** [comment] 2022-06-14 11:46
Hi @mzkai,  Thanks for filing the issue. Your steps looks fine to me as per the docs, Strangely I am getting the below error on both physical device and the simulator whenever I enforce appcheck on cloud firestore.

```
[cloude/firestore/permission-denied] The caller does not have permission to execute the specified operation
```


Labeling this issue for further insights from the team.

<details>
<summary>code sample</summary>

```dart
// Copyright 2020, the Chromium project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_app_check/firebase_app_check.dart';

/// Requires that a Firestore emulator is running locally.
/// See https://firebase.flutter.dev/docs/firestore/usage#emulator-usage
bool USE_FIRESTORE_EMULATOR = true;

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
  await FirebaseAppCheck.instance.activate(
    webRecaptchaSiteKey: '6Lemcn0dAAAAABLkf6aiiHvpGD6x-zF3nOSDU2M',
  );
  if (USE_FIRESTORE_EMULATOR) {
    FirebaseFirestore.instance.useFirestoreEmulator('localhost', 8080);
  }
  runApp(MyApp());
}

final messages = FirebaseFirestore.instance.collection('messages').orderBy(
      'sentDateTime',
    );

class MessagesList extends StatefulWidget {
  const MessagesList({Key? key}) : super(key: key);

  @override
  _MessagesListState createState() => _MessagesListState();
}

class _MessagesListState extends State<MessagesList> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Firestore Messages'),
      ),
      body: StreamBuilder<QuerySnapshot>(
        stream: messages.snapshots(),
        builder: (context, snapshot) {
          if (snapshot.hasError) {
            return Center(
              child: Text(snapshot.error.toString()),
            );
          }

          if (!snapshot.hasData) {
            return const Center(child: CircularProgressIndicator());
          }

          final data = snapshot.data!.docs;

          return ListView.builder(
            itemCount: data.length,
            itemBuilder: (context, index) {
              final dateTime =
                  (data[index]['sentDateTime'] as Timestamp).toDate();
              return ListTile(
                title: Text(data[index]['message']),
                trailing: Text(dateTime.toString()),
              );
            },
          );
        },
      ),
    );
  }
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MessagesList(),
    );
  }
}
```
</details>

**Comment by darshankawar** [comment] 2022-06-20 10:52
Closing this as duplicate of https://github.com/firebase/flutterfire/issues/6872. Please follow-up in linked issue for further updates.

**Closed by darshankawar** 2022-06-20 10:52 UTC
Labels: type: bug, platform: ios, plugin: app_check
