### ISSUE TITLE
🐛 [firebase_storage] DownloadTask.snapshotEvents Never Terminates

### ISSUE THREAD

**Issue by harry-dickson** [firebase/flutterfire#11545] opened 2023-09-02 18:36 UTC
## Unexpected Infinite Stream

***Downloads should end eventually - in success or failure***

Well they do end, but the monitoring task doesn't seem to get the message.

It's not a biggie, but it was annoying - cost me some time to figure it out.
A quick fix would be to update the documentation to help out any poor, befuddled coders like me.

This never ends:
```dart
final Reference ref = storage.ref(path);
final DownloadTask task = ref.writeToFile(somewhere);
await for (final event in task.snapshotEvents) {
  // Do something - progress bar, whatever...
}
```
But this is okay:
```dart
await for (final event in task.snapshotEvents.takeWhile((i) => i.state == TaskState.running)) {
  // Do something - progress bar, whatever...
}
```

Same problem using classic `listen()`; no problem with `await task`.

### Steps to reproduce
Write a download routine including the above code.

### Expected behavior
I expect a DownloadTask's stream of monitoring events to terminate when the download completes.

### Sample project
You are out of luck here. 

---

## Additional context

Writing a robust downloader is tediously difficult  (well, tedious certainly.)

---

### Flutter doctor

I am all up to date :)

---

### Flutter dependencies

This won't help you :)

---

**Comment by Dampfwalze** [comment] 2023-12-27 15:40
The issue is, that the associated platform stream, behind the `Task.snapshotEvents` is never closed on the platform side.

The dirty way of fixing this would be to add `.takeWhile(...)` to the stream created in the constructor of `MethodChannelTask` in `firebase_storage_platform_interface`:

```dart
_stream = mapNativeStream()
        .takeWhile(
            (i) => i.state == TaskState.running || i.state == TaskState.paused)
        .asBroadcastStream(
            onListen: (sub) => sub.resume(), onCancel: (sub) => sub.pause());
```
On line 60:
https://github.com/firebase/flutterfire/blob/3eaae47faccf38fc5f3ec52a753858780a0e5efc/packages/firebase_storage/firebase_storage_platform_interface/lib/src/method_channel/method_channel_task.dart#L21-L69

But this would not fix the underlying problem. The platform itself should close its stream property, when the operation finishes, either with an error, or successfully.

For example, on android, this is the code that emits the snapshot events:

https://github.com/firebase/flutterfire/blob/3eaae47faccf38fc5f3ec52a753858780a0e5efc/packages/firebase_storage/firebase_storage/android/src/main/java/io/flutter/plugins/firebase/storage/TaskStateChannelStreamHandler.java#L34-L90

According to the [docs](https://api.flutter.dev/javadoc/io/flutter/plugin/common/EventChannel.EventSink.html), `EventSink` has an `endOfStream()` method, which closes the stream. This is never called from here. And I checked other implementations, they do not call this method either. On that note, `endOfStream()` should also be called after emitting an error, since a Dart `Stream` does not close automatically, after an error occurred.

**Closed** 2024-01-17 13:36 UTC
Labels: type: documentation, plugin: storage
