### ISSUE TITLE
🐛 [firebase_messaging] There is trying to call the onBackgroundMessage callback too early.

### ISSUE THREAD

**Issue by sirkalmi** [firebase/flutterfire#9581] opened 2022-09-21 07:34 UTC
The problem is iOS specific. The problem occurs if the application was previously deleted from the memory. In this case, when the onBackgroundMessage callback is called in the didReceiveRemoteNotification method, it is still too early, because it was not yet possible to call the FirebaseMessaging.onBackgroundMessage method on the flutter side.

I solved the problem with a delay, but it's not a very nice solution. Can you fix the problem, or can you advise on a better solution?

```objective_c
dispatch_after(dispatch_time(DISPATCH_TIME_NOW, 1 * NSEC_PER_SEC), dispatch_get_main_queue(), ^{
          [_channel invokeMethod:@"Messaging#onBackgroundMessage"
                             arguments:notificationDict
                                result:^(id _Nullable result) {
                                  @synchronized(self) {
                                    if (completed == NO) {
                                      completed = YES;
                                      completionHandler(UIBackgroundFetchResultNewData);
                                      if (backgroundTaskId != UIBackgroundTaskInvalid) {
                                        [application endBackgroundTask:backgroundTaskId];
                                        backgroundTaskId = UIBackgroundTaskInvalid;
                                      }
                                    }
                                  }
                                }];
      });
```

**Comment by darshankawar** [comment] 2022-09-21 10:34
@sirkalmi 
Can you provide `flutter doctor -v`, a minimal code sample along with steps to replicate and logs that shows the behavior ?

**Comment by sirkalmi** [comment] 2022-09-21 11:40
Output from flutter doctor:

[✓] Flutter (Channel stable, 3.3.2, on macOS 12.6 21G115 darwin-x64, locale hu-HU)
    • Flutter version 3.3.2 on channel stable at /Users/sirkalmi/Programok/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e3c29ec00c (7 days ago), 2022-09-14 08:46:55 -0500
    • Engine revision a4ff2c53d8
    • Dart version 2.18.1
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/sirkalmi/Programok/android-sdks/
    • Platform android-33, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A309
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Community Edition (version 2019.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (4 available)
    • sdk gphone x86 (mobile)   • emulator-5554                            • android-x86    • Android 11 (API 30) (emulator)
    • Mobile iPhone-ja (mobile) • 1d331ec4db8d495d84aa0e6afd2790d8ecc1555f • ios            • iOS 16.0 20A362
    • macOS (desktop)           • macos                                    • darwin-x64     • macOS 12.6 21G115 darwin-x64
    • Chrome (web)              • chrome                                   • web-javascript • Google Chrome 105.0.5195.125

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

Logging output after deletion from memory when the first push arrives:
14:59:26.923310+0200	Runner	push_debug_native application:didFinishLaunchingWithOptions
14:59:27.037193+0200	Runner	push_debug_native didReceiveRemoteNotification:fetchCompletionHandler
14:59:27.080037+0200	Runner	flutter: 14:59:27 DEBUG push_debug_flutter _initFirebaseServices
14:59:27.080969+0200	Runner	flutter: 14:59:27 DEBUG push_debug_flutter initFirebaseMessaging

You can see that the didReceiveRemoteNotification method was run too early, before initFirebaseMessaging.

And when the second push arrives, when FirebaseMessaging has already been initialized:
15:38:29.089695+0200	Runner	push_debug_native application:didFinishLaunchingWithOptions
15:38:29.241386+0200	Runner	flutter: 15:38:29 DEBUG push_debug_flutter _initFirebaseServices
15:38:29.242434+0200	Runner	flutter: 15:38:29 DEBUG push_debug_flutter initFirebaseMessaging
15:38:30.223824+0200	Runner	push_debug_native didReceiveRemoteNotification:fetchCompletionHandler
15:38:30.226038+0200	Runner	flutter: 15:38:30 DEBUG push_debug_flutter _onBackgroundMessage

Everything is fine here, this is the correct run order.

Code snippet from flutter side:

void main() async {
  flavorConfig = FlavorConfig(...),
  );
  run();
}

Future<void> run() async {
  WidgetsFlutterBinding.ensureInitialized();
  await initPackageInfo();
  await initStorageWrapper();
  await _initFlavorConfig();
  **await _initFirebaseServices();**
  await NotificationsController.initializeLocalNotifications();
  await _initSingletons();
  await _initWorker();
  await _initPreferredOrientations();
  await _initFlutterDownloader();
  _initGoogleMaps();
  runApp(await getApp());
}

Future<void> _initFirebaseServices() async {
  logger.d('push_debug _initFirebaseServices');
  await Firebase.initializeApp(options: F.firebaseOptions);
  ...
  await NotificationsController.initFirebaseMessaging();
}

static Future<void> initFirebaseMessaging() async {
    logger.d('push_debug initFirebaseMessaging');
    ...
    **FirebaseMessaging.onBackgroundMessage(_onBackgroundMessage);**
    FirebaseMessaging.onMessage.listen(_onMessage);
    ...
  }

Code snippet from iOS side:
@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
    override func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
    	NSLog("parking_push application:didFinishLaunchingWithOptions");
        if let googleServiceFileName: String = Bundle.main.object(forInfoDictionaryKey: "GoogleService-Info") as! String? {
            if let filePath = Bundle.main.path(forResource: googleServiceFileName, ofType: "plist") {
                if let fileopts = FirebaseOptions(contentsOfFile: filePath) {
                    NSLog("Loading GoogleService-Info configuration...")
                    FirebaseApp.configure(options: fileopts)
                }
            }
        }
        
        if let googleApiKey: String = Bundle.main.object(forInfoDictionaryKey: "GOOGLE_API_KEY") as! String? {
            GMSServices.provideAPIKey(googleApiKey)
        }
        
        GeneratedPluginRegistrant.register(with: self)

        SwiftAwesomeNotificationsPlugin.setPluginRegistrantCallback { registry in
				  SwiftAwesomeNotificationsPlugin.register(
					with: registry.registrar(forPlugin: "io.flutter.plugins.awesomenotifications.AwesomeNotificationsPlugin")!)
				  FLTSharedPreferencesPlugin.register(
					with: registry.registrar(forPlugin: "io.flutter.plugins.sharedpreferences.SharedPreferencesPlugin")!)
			  }
        
        FlutterDownloaderPlugin.setPluginRegistrantCallback({registry in
            if (!registry.hasPlugin("FlutterDownloaderPlugin")) {
                FlutterDownloaderPlugin.register(with: registry.registrar(forPlugin: "FlutterDownloaderPlugin")!)
            }
        })
        
        return super.application(application, didFinishLaunchingWithOptions: launchOptions)
    }

    override func application(_ application: UIApplication, didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {
        super.application(application, didRegisterForRemoteNotificationsWithDeviceToken: deviceToken)
        
        ...
        print("Received an APNs device token: \(readableToken)")
    }
    
    override func application(_ application: UIApplication, didFailToRegisterForRemoteNotificationsWithError error: Error) {
        super.application(application, didFailToRegisterForRemoteNotificationsWithError: error)
        
        print("PUSH registration failed: \(error)")
    }
}

**Comment by hatemragab** [comment] 2022-09-21 18:03
@sirkalmi 
Iam face same problem can you let me know where to put this code i want to try
```
dispatch_after(dispatch_time(DISPATCH_TIME_NOW, 1 * NSEC_PER_SEC), dispatch_get_main_queue(), ^{
          [_channel invokeMethod:@"Messaging#onBackgroundMessage"
                             arguments:notificationDict
                                result:^(id _Nullable result) {
                                  @synchronized(self) {
                                    if (completed == NO) {
                                      completed = YES;
                                      completionHandler(UIBackgroundFetchResultNewData);
                                      if (backgroundTaskId != UIBackgroundTaskInvalid) {
                                        [application endBackgroundTask:backgroundTaskId];
                                        backgroundTaskId = UIBackgroundTaskInvalid;
                                      }
                                    }
                                  }
                                }];
      });
```

**Comment by iosephmagno** [comment] 2022-09-21 19:28
@sirkalmi thanks for the effort!

@hatemragab 
1) Fork Flutterfire

2) Edit code here and push
https://github.com/firebase/flutterfire/blob/master/packages/firebase_messaging/firebase_messaging/ios/Classes/FLTFirebaseMessagingPlugin.m

3) Add your FirebaseMessaging fork to yalm:
firebase_messaging:
  git:
    url: https://github.com/your_project/flutterfire.git
    ref: master
    path: packages/firebase_messaging/firebase_messaging

**Unfortunately, I just tested it and it doesnt fix #9536. Code is a bit different but for us notifications work like before.**
@sirkalmi Does it fix 9536 for you?

**Comment by sirkalmi** [comment] 2022-09-22 05:43
> **Unfortunately, I just tested it and it doesnt fix #9536.** Code is a bit different but for us notifications work like before. @sirkalmi Does it fix 9536 for you? **I mean, you kill the app (not just move it to background) and then open a different app. Do notifications work in that specific condition?**

I didn't know about bug #9536, it doesn't fix it. :-(
I have other things to do today, but I'll debug #9536 as soon as I can.

**Comment by sirkalmi** [comment] 2022-09-22 05:47
@hatemragab 
> Iam face same problem can you let me know where to put this code i want to try

475. line:
https://github.com/firebase/flutterfire/blob/master/packages/firebase_messaging/firebase_messaging/ios/Classes/FLTFirebaseMessagingPlugin.m

**Comment by darshankawar** [comment] 2022-09-22 07:44
Thanks for the updates. I am keeping this issue open for team's insight on expected behavior.

/cc @russellwheatley

**Comment by iosephmagno** [comment] 2022-09-26 11:37
@sirkalmi Hello did you have a chance to debug it?

**Comment by sirkalmi** [comment] 2022-09-26 13:23
> @sirkalmi Hello did you have a chance to debug it?

No, because after clearing the application from memory, the connection to XCode's debugger is lost. Instead, I filled the code with logs, so it became visible where the processing gets stuck. I was clearly able to reproduce the bug and my fix works based on initial tester feedback.

**Comment by iosephmagno** [comment] 2022-09-26 16:07
Did testers kill app or just move it to background? We just tested again on another iphone: if app is killed and another app is opened, then notifications dont work.

**Comment by sirkalmi** [comment] 2022-09-27 06:07
> Did testers kill app or just move it to background? We just tested again on another iphone: if app is killed and another app is opened, then notifications dont work.

They killed it but didn't open a new app. There seems to be a difference between just killing it or opening a new app afterwards.

**Comment by iosephmagno** [comment] 2022-09-27 07:13
Yes, if you kill app, notifications still work untill you open a different app. This is why bug can go unnoticed at first glance

**Comment by russellwheatley** [comment] 2022-09-27 11:01
Hello everyone, we’ve reviewed the issues opened for iOS background messages and we want to make our position clear.

Android and iOS handle background messaging differently. The decision made by the iOS operating system whether messages reaches the relevant iOS event handler (and subsequently received by the Dart background messaging handler) is based on a number of criteria, such as: CPU usage, priority level (data-only messages are considered “low priority” by iOS, android does not), battery level, amount of messages being received by the app, background/terminated application state, etc. This is a fundamental difference between the platforms, and you need to be aware of them when designing your application.

One solution suggested for iOS data-only messages unreliability has been to add a NotificationExtension. But this will still not create parity with Android as you will still have to include a notification with your message (therefore not data-only). It will still render the original notification if you do not update/mutate the notification that comes through the system in a timely manner.  We are not currently considering this as a solution due to these limitations.

We also will not support non-FCM messages from third party packages. We specifically only support messages received from the Firebase APIs since we cannot guarantee that messages received from third party packages will not have any unintended side-effects  on other Firebase products such as messaging delivery reporting and Analytics data.

To help us triage and locate genuine issues that need to be addressed we have created a specific issue template for iOS background messages. If you believe you still have an issue that needs to be addressed, please create a new issue following [this template](https://github.com/firebase/flutterfire/issues/new?assignees=&labels=Needs+Attention%2Ctype%3A+bug%2Cplugin%3A+messaging%2Cplatform%3A+ios&template=ios_background_message_handling.yml&title=%5Bfirebase_messaging%5D%3A+%3CYOUR+TITLE+HERE%3E).

I will be closing this issue in favor of raising a new issue with the new template above. This template will help you provide us with all the information we need to investigate a potential issue with background messaging on iOS.

**Closed by russellwheatley** 2022-09-27 11:01 UTC
Labels: type: bug, plugin: messaging, platform: ios
