### ISSUE TITLE
PlatformException(channel-error, Unable to establish connection on channel., null, null)

### ISSUE THREAD

**Issue by evekeen** [firebase/flutterfire#9987] opened 2022-11-24 04:12 UTC
## Bug report

**Describe the bug**
The error happens when embedding Flutter into a FlutterViewController from an existing ios app. The standalone `flutter run` on the module works fine.

### Steps to reproduce
1. Create a flutter module (as in tutorial https://docs.flutter.dev/development/add-to-app/ios/project-setup)
2. Install firebase dependency
3. Call `await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);` from the module
4. Check `flutter run` - works fine
5. Create a flutter engine and run it from an existing ios app
```
class FlutterDependencies: ObservableObject {
  let engine = FlutterEngine(name: "flutter_engine")

  init() {
      engine.run()
  }
}
```
6. Launch the ios app
7. Error occurs in the logs
```
2022-11-23 23:00:39.719734-0500 acetrace[58192:4601661] [VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
#0      FirebaseCoreHostApi.initializeCore (package:firebase_core_platform_interface/src/pigeon/messages.pigeon.dart:203:7)
<asynchronous suspension>
#1      MethodChannelFirebase._initializeCore (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:29:44)
<asynchronous suspension>
#2      MethodChannelFirebase.initializeApp (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:73:7)
<asynchronous suspension>
#3      Firebase.initializeApp (package:firebase_core/src/firebase.dart:43:31)
<asynchronous suspension>
#4      main (package:acetrace_feed/main.dart:16:3)
<asynchronous suspension>
```

### Expected behavior
The flutter view controller works fine, Firebase app can be initialized from it.

### Flutter doctor

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.8, on macOS 12.6 21G115 darwin-arm, locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.2.1)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

! Doctor found issues in 1 category.
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.18.4
Flutter SDK 3.3.8
acetrace_feed 1.0.0+1

dependencies:
- cached_network_image 3.2.2 [flutter flutter_cache_manager octo_image cached_network_image_platform_interface cached_network_image_web]
- cloud_firestore 4.1.0 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_interface flutter meta]
- cloud_functions 4.0.5 [cloud_functions_platform_interface cloud_functions_web firebase_core firebase_core_platform_interface flutter]
- cupertino_icons 1.0.5
- firebase_auth 4.1.3 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 2.3.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_storage 11.0.6 [firebase_core firebase_core_platform_interface firebase_storage_platform_interface firebase_storage_web flutter]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- get_it 7.2.0 [async collection]
- stacked 3.0.0 [flutter get_it meta provider collection stacked_core universal_io]
- stacked_services 0.9.8 [flutter stacked_core get crypto]
- video_player 2.4.8 [flutter html video_player_android video_player_avfoundation video_player_platform_interface video_player_web]

dev dependencies:
- flutter_lints 2.0.1 [lints]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters collection matcher material_color_utilities meta source_span stream_channel string_scanner term_glyph]

transitive dependencies:
- _flutterfire_internals 1.0.9 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_interface flutter meta]
- async 2.9.0 [collection meta]
- boolean_selector 2.1.0 [source_span string_scanner]
- cached_network_image_platform_interface 2.0.0 [flutter flutter_cache_manager]
- cached_network_image_web 1.0.2 [flutter flutter_cache_manager cached_network_image_platform_interface]
- characters 1.2.1
- clock 1.1.1
- cloud_firestore_platform_interface 5.9.0 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 3.1.0 [_flutterfire_internals cloud_firestore_platform_interface collection firebase_core firebase_core_web flutter flutter_web_plugins js]
- cloud_functions_platform_interface 5.1.24 [firebase_core flutter meta plugin_platform_interface]
- cloud_functions_web 4.3.13 [cloud_functions_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- collection 1.16.0
- crypto 3.0.2 [typed_data]
- csslib 0.17.2 [source_span]
- fake_async 1.3.1 [clock collection]
- ffi 2.0.1
- file 6.1.4 [meta path]
- firebase_auth_platform_interface 6.11.3 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 5.1.3 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core_platform_interface 4.5.2 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.0.1 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_storage_platform_interface 4.1.24 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_storage_web 3.3.16 [_flutterfire_internals async firebase_core firebase_core_web firebase_storage_platform_interface flutter flutter_web_plugins http js meta]
- flutter_blurhash 0.7.0 [flutter]
- flutter_cache_manager 3.3.0 [clock collection file flutter http path path_provider pedantic rxdart sqflite uuid]
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta vector_math]
- get 4.6.5 [flutter]
- html 0.15.1 [csslib source_span]
- http 0.13.5 [async http_parser meta path]
- http_parser 4.0.2 [collection source_span string_scanner typed_data]
- intl 0.17.0 [clock path]
- js 0.6.4
- lints 2.0.1
- matcher 0.12.12 [stack_trace]
- material_color_utilities 0.1.5
- meta 1.8.0
- nested 1.0.0 [flutter]
- octo_image 1.0.2 [flutter flutter_blurhash]
- path 1.8.2
- path_provider 2.0.11 [flutter path_provider_android path_provider_ios path_provider_linux path_provider_macos path_provider_platform_interface path_provider_windows]
- path_provider_android 2.0.22 [flutter path_provider_platform_interface]
- path_provider_ios 2.0.11 [flutter path_provider_platform_interface]
- path_provider_linux 2.1.7 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_macos 2.0.6 [flutter path_provider_platform_interface]
- path_provider_platform_interface 2.0.5 [flutter platform plugin_platform_interface]
- path_provider_windows 2.1.3 [ffi flutter path path_provider_platform_interface win32]
- pedantic 1.11.1
- platform 3.1.0
- plugin_platform_interface 2.1.3 [meta]
- process 4.2.4 [file path platform]
- provider 6.0.4 [collection flutter nested]
- rxdart 0.27.7
- sky_engine 0.0.99
- source_span 1.9.0 [collection path term_glyph]
- sqflite 2.2.0+3 [flutter sqflite_common path]
- sqflite_common 2.4.0+2 [synchronized path meta]
- stack_trace 1.10.0 [path]
- stacked_core 1.2.4 [get_it]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.1 [source_span]
- synchronized 3.0.0+3
- term_glyph 1.2.1
- test_api 0.4.12 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.1 [collection]
- universal_io 2.0.4 [collection crypto meta typed_data]
- uuid 3.0.7 [crypto]
- vector_math 2.1.2
- video_player_android 2.3.9 [flutter video_player_platform_interface]
- video_player_avfoundation 2.3.7 [flutter video_player_platform_interface]
- video_player_platform_interface 5.1.4 [flutter plugin_platform_interface]
- video_player_web 2.0.12 [flutter flutter_web_plugins video_player_platform_interface]
- win32 3.1.1 [ffi]
- xdg_directories 0.2.0+2 [meta path process]
```

</details>

---

I've tried different combinations of firebase plugin versions, upgraded everything, `flutter clean`, `pod install`, etc - nothing helped.

It's interesting that if I comment the `Firebase.initializeApp`, the app will throw the exception in a completely different call as well:
```
2022-11-23 23:07:43.113417-0500 acetrace[58910:4611869] [VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
#0      AVFoundationVideoPlayerApi.initialize (package:video_player_avfoundation/src/messages.g.dart:272:7)
<asynchronous suspension>
2022-11-23 23:07:43.114007-0500 acetrace[58910:4611869] [VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
#0      AVFoundationVideoPlayerApi.create (package:video_player_avfoundation/src/messages.g.dart:296:7)
<asynchronous suspension>
#1      AVFoundationVideoPlayer.create (package:video_player_avfoundation/src/avfoundation_video_player.dart:65:37)
<asynchronous suspension>
#2      VideoPlayerController.initialize (package:video_player/video_player.dart:363:19)
<asynchronous suspension>
#3      Video.loadController (package:acetrace_feed/data/video.dart:52:5)
<asynchronous suspension>
#4      FeedViewModel.loadVideo (package:acetrace_feed/screens/feed_viewmodel.dart:48:5)
<asynchronous suspension>
2022-11-23 23:07:43.114246-0500 acetrace[58910:4611869] [VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
#0      PathProviderApi.getTemporaryPath (package:path_provider_ios/messages.g.dart:36:7)
<asynchronous suspension>
#1      getTemporaryDirectory (package:path_provider/path_provider.dart:55:24)
<asynchronous suspension>
#2      IOFileSystem.createDirectory (package:flutter_cache_manager/src/storage/file_system/file_system_io.dart:15:19)
<asynchronous suspension>
2022-11-23 23:07:43.114536-0500 acetrace[58910:4611869] [VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
#0      PathProviderApi.getApplicationSupportPath (package:path_provider_ios/messages.g.dart:60:7)
<asynchronous suspension>
#1      PathProviderIOS.getApplicationSupportPath (package:path_provider_ios/path_provider_ios.dart:27:26)
<asynchronous suspension>
#2      getApplicationSupportDirectory (package:path_provider/path_provider.dart:77:24)
<asynchronous suspension>
#3      CacheObjectProvider._getPath (package:flutter_cache_manager/src/storage/cache_info_repositories/cache_object_provider.dart:196:20)
<asynchronous suspension>
#4      CacheObjectProvider.open (package:flutter_cache_manager/src/storage/cache_info_repositories/cache_object_provider.dart:28:16)
<asynchronous suspension>
#5      CacheStore._getCacheDataFromDatabase (package:flutter_cache_manager/src/cache_store.dart:115:22)
<asynchronous suspension>
```

Please, help me figure this out

**Comment by darshankawar** [comment] 2022-11-24 10:43
Thanks for the report @evekeen
Can you try by adding `GeneratedPluginRegistrant.register(with: self)` in step 5 and see if it helps ?

**Comment by ShanthKumar** [comment] 2022-11-24 13:10
I am facing the same issue/error when i am trying to build the flutter app for windows desktop platform.
Error : Unable to establish connection on channel.

**Comment by evekeen** [comment] 2022-11-24 14:16
@darshankawar it helped! Thank you so much. I thought I didn't have plugins, so I skipped that line from the tutorial.
If I only asked this question 10 hours earlier :)

**Comment by danagbemava-nc** [comment] 2022-11-25 09:12
@ShanthKumar, kindly file a new issue and provide all the relevant information required to reproduce the issue. Your issue is unrelated to this issue. 

Closing this since a solution has been provided based on https://github.com/firebase/flutterfire/issues/9987#issuecomment-1326512492.

Thank you

**Closed by danagbemava-nc** 2022-11-25 09:12 UTC
Labels: type: bug, Needs Attention, in triage
