### ISSUE TITLE
🐛 [firebase_auth] Ignoring header X-Firebase-Locale because its value was null | FirebaseAuth not working on few devices

### ISSUE THREAD

**Issue by SuTechs** [firebase/flutterfire#10413] opened 2023-02-10 12:21 UTC
## Bug report

**Describe the bug**
Using flutter firebase auth and everything seems fine and working on most of the devices. But on one Infinix device(Infinix Hot 12 Play) the OTP is not getting sent and not even the function is getting executed. Also, the OTP is received after a very long time but yet no callback is called from auth.verifyPhoneNumber.

### Steps to reproduce

1. Run firebase_auth in Infinix Hot 12 play

### Expected behavior

After OTP is sent, it should give a callback to `codeSent` or if there's any error it should be logged.

### Sample project

```
try {
      await auth.verifyPhoneNumber(
        phoneNumber: phoneNumber,
        codeSent: (String verificationId, int? resendToken) {
          log('codeSent Verification Id = $verificationId');
          onCodeSent(verificationId);
        },
        verificationCompleted: (PhoneAuthCredential credential) async {
          log('hello verification auto completed ${credential.smsCode}');

          final user = await auth.signInWithCredential(credential);

          if (user.user != null) {
            final isNewUser = user.additionalUserInfo!.isNewUser;
            if (isNewUser) {
              debugPrint('Welcome New User: Adding to firestore!');
              await addUser(UserData(
                userId: user.user!.uid,
                phone: user.user!.phoneNumber!,
                createdAt: TimeUtils.nowMillis,
              ));
            }

            onAutoVerified(user.user!.uid);
          }
        },
        verificationFailed: (FirebaseAuthException e) {
          if (e.code == 'invalid-phone-number') {
            log('The provided phone number is not valid.');
            onVerificationFailed('The provided phone number is not valid.');
            return;
          }

          log('Error = ${e.message}');
          onVerificationFailed(
              e.message ?? "Something went wrong! [code: s032]");

          // Handle other errors
        },
        codeAutoRetrievalTimeout: (verificationId) {
          log('TimeOut Verification Id = $verificationId');
        },
      );
    } catch (e) {
      log('SendOTPError = $e');
    }
```

---

## Additional context

Even the released build from play store is not working on few devices.

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[√] Flutter (Channel beta, 3.7.0-1.5.pre, on Microsoft Windows [Version 10.0.22621.1194], locale en-IN)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.11.11)
[√] Android Studio (version 2022.1)
[√] IntelliJ IDEA Ultimate Edition (version 2022.3)
[√] Connected device (4 available)
[√] HTTP Host Availability

• No issues found!

```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.19.0-444.6.beta
Flutter SDK 3.7.0-1.5.pre
connect 1.0.0+3

dependencies:
- carousel_slider 4.2.1 [flutter]
- cloud_firestore 4.3.1 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_interface flutter meta]
- cupertino_icons 1.0.5
- dynamic_color 1.5.4 [flutter flutter_test material_color_utilities]
- firebase_app_check 0.1.1+8 [firebase_app_check_platform_interface firebase_app_check_web firebase_core firebase_core_platform_interface flutter] 
- firebase_auth 4.2.5 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 2.4.1 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_messaging 14.2.1 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- firebase_storage 11.0.10 [firebase_core firebase_core_platform_interface firebase_storage_platform_interface firebase_storage_web flutter]       
- flutter 0.0.0 [characters collection js material_color_utilities meta vector_math sky_engine]
- flutter_staggered_grid_view 0.6.2 [flutter]
- flutter_svg 1.1.6 [flutter meta path_drawing vector_math xml]
- freezed_annotation 2.2.0 [collection json_annotation meta]
- http 0.13.5 [async http_parser meta path]
- image_picker 0.8.6+1 [flutter image_picker_android image_picker_for_web image_picker_ios image_picker_platform_interface]
- json_annotation 4.8.0 [meta]
- lottie 2.2.0 [archive flutter path vector_math]
- pinput 2.2.21 [flutter smart_auth]
- provider 6.0.5 [collection flutter nested]
- shared_preferences 2.0.17 [flutter shared_preferences_android shared_preferences_foundation shared_preferences_linux shared_preferences_platform_interface shared_preferences_web shared_preferences_windows]
- timeago 3.3.0 [intl]
- typesense 0.3.0 [http crypto]
- url_launcher 6.1.8 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- webview_flutter 4.0.2 [flutter webview_flutter_android webview_flutter_platform_interface webview_flutter_wkwebview]

dev dependencies:
- build_runner 2.3.3 [args async analyzer build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_sty
le frontend_server_client glob graphs http_multi_server io js logging meta mime package_config path pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web_socket_channel yaml]
- flutter_lints 2.0.1 [lints]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters collection js matcher material_color_utilities meta source_span stream_channel string_scanner term_glyph]
- freezed 2.3.2 [analyzer build build_config collection meta source_gen freezed_annotation json_annotation]
- json_serializable 6.6.0 [analyzer async build build_config collection json_annotation meta path pub_semver pubspec_parse source_gen source_helper]

transitive dependencies:
- _fe_analyzer_shared 51.0.0 [meta]
- _flutterfire_internals 1.0.12 [collection firebase_core firebase_core_platform_interface flutter meta]
- analyzer 5.3.1 [_fe_analyzer_shared collection convert crypto glob meta package_config path pub_semver source_span watcher yaml]
- archive 3.3.5 [crypto path pointycastle]
- args 2.3.1
- async 2.10.0 [collection meta]
- boolean_selector 2.1.1 [source_span string_scanner]
- build 2.3.1 [analyzer async convert crypto glob logging meta path]
- build_config 1.1.1 [checked_yaml json_annotation path pubspec_parse yaml]
- build_daemon 3.1.0 [built_collection built_value http_multi_server logging path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 2.1.0 [analyzer async build crypto graphs logging path package_config pool pub_semver stream_transform yaml]
- build_runner_core 7.2.7 [async build build_config build_resolvers collection convert crypto glob graphs json_annotation logging meta path package_config pool timing watcher yaml]
- built_collection 5.1.1
- built_value 8.4.2 [built_collection collection fixnum meta]
- characters 1.2.1
- checked_yaml 2.0.1 [json_annotation source_span yaml]
- clock 1.1.1
- cloud_firestore_platform_interface 5.10.0 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 3.2.1 [_flutterfire_internals cloud_firestore_platform_interface collection firebase_core firebase_core_web flutter flutter_web_plugins js]
- code_builder 4.4.0 [built_collection built_value collection matcher meta]
- collection 1.17.0
- convert 3.1.1 [typed_data]
- cross_file 0.3.3+2 [js meta]
- crypto 3.0.2 [typed_data]
- dart_style 2.2.4 [analyzer args path pub_semver source_span]
- fake_async 1.3.1 [clock collection]
- ffi 2.0.1
- file 6.1.4 [meta path]
- firebase_app_check_platform_interface 0.0.5+11 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_app_check_web 0.0.7+11 [_flutterfire_internals firebase_app_check_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- firebase_auth_platform_interface 6.11.6 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 5.2.4 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]  
- firebase_core_platform_interface 4.5.2 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.1.0 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_messaging_platform_interface 4.2.10 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 3.2.11 [_flutterfire_internals firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]
- firebase_storage_platform_interface 4.1.26 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_storage_web 3.3.19 [_flutterfire_internals async firebase_core firebase_core_web firebase_storage_platform_interface flutter flutter_web_plugins http js meta]
- fixnum 1.0.1
- flutter_plugin_android_lifecycle 2.0.7 [flutter]
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta vector_math]
- frontend_server_client 3.2.0 [async path]
- glob 2.1.1 [async collection file path string_scanner]
- graphs 2.2.0 [collection]
- http_multi_server 3.2.1 [async]
- http_parser 4.0.2 [collection source_span string_scanner typed_data]
- image_picker_android 0.8.5+4 [flutter flutter_plugin_android_lifecycle image_picker_platform_interface]
- image_picker_for_web 2.1.10 [flutter flutter_web_plugins image_picker_platform_interface]
- image_picker_ios 0.8.6+4 [flutter image_picker_platform_interface]
- image_picker_platform_interface 2.6.2 [cross_file flutter http plugin_platform_interface]
- intl 0.17.0 [clock path]
- io 1.0.3 [meta path string_scanner]
- js 0.6.5 [meta]
- lints 2.0.1
- logging 1.1.0
- matcher 0.12.13 [meta stack_trace]
- material_color_utilities 0.2.0
- meta 1.8.0
- mime 1.0.3
- nested 1.0.0 [flutter]
- package_config 2.1.0 [path]
- path 1.8.2
- path_drawing 1.0.1 [vector_math meta path_parsing flutter]
- path_parsing 1.0.1 [vector_math meta]
- path_provider_linux 2.1.7 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_platform_interface 2.0.5 [flutter platform plugin_platform_interface]
- path_provider_windows 2.1.3 [ffi flutter path path_provider_platform_interface win32]
- petitparser 5.1.0 [meta]
- platform 3.1.0
- plugin_platform_interface 2.1.3 [meta]
- pointycastle 3.6.2 [collection convert js]
- pool 1.5.1 [async stack_trace]
- process 4.2.4 [file path platform]
- pub_semver 2.1.3 [collection meta]
- pubspec_parse 1.2.1 [checked_yaml collection json_annotation pub_semver yaml]
- shared_preferences_android 2.0.14 [flutter shared_preferences_platform_interface]
- shared_preferences_foundation 2.1.2 [flutter shared_preferences_platform_interface]
- shared_preferences_linux 2.1.2 [file flutter path path_provider_linux path_provider_platform_interface shared_preferences_platform_interface]    
- shared_preferences_platform_interface 2.1.0 [flutter plugin_platform_interface]
- shared_preferences_web 2.0.4 [flutter flutter_web_plugins shared_preferences_platform_interface]
- shared_preferences_windows 2.1.2 [file flutter path path_provider_platform_interface path_provider_windows shared_preferences_platform_interface]
- shelf 1.4.0 [async collection http_parser path stack_trace stream_channel]
- shelf_web_socket 1.0.3 [shelf stream_channel web_socket_channel]
- sky_engine 0.0.99
- smart_auth 1.0.8 [flutter flutter_web_plugins]
- source_gen 1.2.6 [analyzer async build dart_style glob meta path source_span yaml]
- source_helper 1.3.3 [analyzer collection source_gen]
- source_span 1.9.1 [collection path term_glyph]
- stack_trace 1.11.0 [path]
- stream_channel 2.1.1 [async]
- stream_transform 2.1.0
- string_scanner 1.2.0 [source_span]
- term_glyph 1.2.1
- test_api 0.4.16 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- timing 1.0.0 [json_annotation]
- typed_data 1.3.1 [collection]
- url_launcher_android 6.0.22 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.0.17 [flutter url_launcher_platform_interface]
- url_launcher_linux 3.0.1 [flutter url_launcher_platform_interface]
- url_launcher_macos 3.0.1 [flutter url_launcher_platform_interface]
- url_launcher_platform_interface 2.1.1 [flutter plugin_platform_interface]
- url_launcher_web 2.0.13 [flutter flutter_web_plugins url_launcher_platform_interface]
- url_launcher_windows 3.0.1 [flutter url_launcher_platform_interface]
- vector_math 2.1.4
- watcher 1.0.2 [async path]
- web_socket_channel 2.2.0 [async crypto stream_channel]
- webview_flutter_android 3.2.4 [flutter webview_flutter_platform_interface]
- webview_flutter_platform_interface 2.0.1 [flutter meta plugin_platform_interface]
- webview_flutter_wkwebview 3.0.5 [flutter path webview_flutter_platform_interface]
- win32 3.1.3 [ffi]
- xdg_directories 0.2.0+2 [meta path process]
- xml 6.2.2 [collection meta petitparser]
- yaml 3.1.1 [collection source_span string_scanner]

```

</details>

---

**Comment by darshankawar** [comment] 2023-02-10 13:11
@SuTechs 


> But on one Infinix device(Infinix Hot 12 Play) the OTP is not getting sent and not even the function is getting executed. Also, the OTP is received after a very long time but yet no callback is called from auth.verifyPhoneNumber.

This behavior seems to be happening on only a specific device and per your other comment, other the functionality seems to be working on other devices. This probably indicates that it may be not be an issue with the plugin, but could be specific to the device. Please check if there's any setting or config in the device that might be preventing OTP to not receive.

The plugin code is same for all devices and is not specific to a device, so I suggest you to reach out to firebase support for further resolution. See a similar log reported in this issue (not firebase_auth, but other plugin but you can go through underlying comments to see if there's anything missing from your end).
Closing this issue for now. If you get a concrete reproducible code sample (without third party plugin) that consistently replicates the behavior you are reporting, please provide relevant details mentioned in the template so that we can have a look at it again.

**Closed by darshankawar** 2023-02-10 13:11 UTC
Labels: type: bug, Needs Attention, in triage
