### ISSUE TITLE
[cloud_firestore]: <Streams stop working only in web after 5.0.0 and higher>

### ISSUE THREAD

**Issue by operationcyberstorm** [firebase/flutterfire#13328] opened 2024-09-13 09:48 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

cloud_firestore

### Which platforms are affected?

Web

### Description

All Streams stopped working in web version after upgrading cloud_firestore to 5.4.1. Starts only working again after downgrading to lower than 5.0.0.  On iOS and Android everything keeps working as before and no issues are detected 

We experimented with making the data inside of the builder nullable and not nullable but both just gives back the document does not not exist. 

## Steps to Reproduce the Issue

1. **Set Up Firebase Firestore**
   - Ensure that you have Firebase Firestore set up and connected to your Flutter project.
   - Use pub.dev cloud_firestore package minimum 5.0.0

2. **Implement Document Stream**
   - Create a method `documentStream<T>` which fetches and streams data from Firestore. Here's the code for this function:

   ```dart
   Stream<T> documentStream<T>({
     required String path,
     required T builder(Map<String, dynamic>? data, String documentID),
   }) {
     final reference = FirebaseFirestore.instance.doc(path);
     final snapshots = reference.snapshots();
     return snapshots.map((snapshot) => builder(snapshot.data(), snapshot.id));
   }

3. **Create a Stream for User Data**
Use the documentStream<T> method to build a stream for user data, as shown below:

```dart
Stream<UserData> userStream() => _service.documentStream(
  path: APIPath.userData(uid),
  builder: (data, documentId) => UserData.fromDS(documentId, data),
);
```

4. **Use StreamBuilder in a Flutter Widget**
To use the stream in the UI, implement a StreamBuilder widget to listen for changes to user data, only on web shows Document does not exist, but working on android and iOS. 

```dart
return StreamBuilder<UserData>(
  stream: userStream(uid),
  builder: (context, snapshot) {
    if (snapshot.connectionState == ConnectionState.waiting) {
      // Connection is waiting for data
      return Center(child: CircularProgressIndicator());
    } else if (snapshot.connectionState == ConnectionState.active) {
      // Active connection and receiving data
      if (snapshot.hasData) {
        final userData = snapshot.data!;
        // Build your UI with userData
        return Text('Welcome ${userData.name}');
      } else if (!snapshot.hasData || snapshot.data == null) {
        return Center(child: Text('Document does not exist.'));
      }
    } else if (snapshot.hasError) {
      // Handle errors
      return Center(child: Text('Error: ${snapshot.error}'));
    } else {
      // Default fallback if none of the above conditions match
      return Center(child: Text('Something went wrong.'));
    }
  }
);
```

### Firebase Core version

3.4.1

### Flutter Version

3.22.2

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Replace this line with the contents of your `flutter pub deps -- --style=compact`.

```

</details>

**Comment by SelaseKay** [comment] 2024-09-13 10:41
Hi @operationcyberstorm , I'm unable to reproduce this issue. Kindly share a full sample code or repo reproducing this issue.

**Comment by josh-burton** [comment] 2024-09-14 21:13
I think this issue may not be limited to firestore streams. It seems streams of auth changes for example have also stopped working.

**Comment by operationcyberstorm** [comment] 2024-09-16 08:17
> firestore streams. It seems streams of auth changes for example have also stopped

Hi Josh, good to hear we are not the only ones having this problems, did you find any workarounds for this so far?

**Comment by josh-burton** [comment] 2024-09-16 08:18
> > firestore streams. It seems streams of auth changes for example have also stopped
> 
> Hi Josh, good to hear we are not the only ones having this problems, did you find any workarounds for this so far?

Not so far. I spent some time trying to debug the issue but haven't found the cause yet and I'm not seeing any error logs.

**Comment by operationcyberstorm** [comment] 2024-09-16 08:20
We keep you updated if we figure out something new, we also do not see any error logs, just shows basically the doc is not existing.

**Comment by SelaseKay** [comment] 2024-09-16 08:29
Hi @operationcyberstorm , kindly provide a full sample code. I tried reproducing with the above code but I was unable to experience the behaviour you described.

**Comment by SelaseKay** [comment] 2024-09-18 15:49
I would appreciate it if you could create a minimal project that reproduces the issue.

**Comment by operationcyberstorm** [comment] 2024-09-19 08:35
This will take a while cause we are really busy, right now but send this to you as soon as possible

**Comment by SelaseKay** [comment] 2024-09-24 09:20
Hi @operationcyberstorm , I'll close this issue for now. Please don't hesitate to reach out once you have a reproducible code example, and we can revisit it. Thanks!

**Closed by SelaseKay** 2024-09-24 09:20 UTC
Labels: type: bug, plugin: cloud_firestore, platform: web, Needs Attention
