### ISSUE TITLE
🐛 [firebase_database] Xcode build fails after adding firebase_database

### ISSUE THREAD

**Issue by MatasRut** [firebase/flutterfire#8345] opened 2022-03-27 11:24 UTC
Hi, I'm using an M1 mac and I get Xcode build error `Module 'firebase_auth' not found` after adding firebase_database to my  `pubspec.yaml`. If I remove it, everything works fine, the code builds and I can use the auth plugin features so I believe the problem is with the database plugin.

### The error
`Parse Issue (Xcode): Module 'firebase_auth' not found` in `GeneratedPluginRegistrant`

### Additional context
libffi version: 3.4.2
cocoapods version: 1.11.3

<details>
  <summary>My Podfile</summary>
  
```
platform :ios, '10.0'
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
```

</details>

<details>
  <summary>My Podfile.lock</summary>
  
 ```
 PODS:
  - Firebase/Auth (8.11.0):
    - Firebase/CoreOnly
    - FirebaseAuth (~> 8.11.0)
  - Firebase/CoreOnly (8.11.0):
    - FirebaseCore (= 8.11.0)
  - Firebase/Database (8.11.0):
    - Firebase/CoreOnly
    - FirebaseDatabase (~> 8.11.0)
  - firebase_auth (3.3.11):
    - Firebase/Auth (= 8.11.0)
    - firebase_core
    - Flutter
  - firebase_core (1.12.0):
    - Firebase/CoreOnly (= 8.11.0)
    - Flutter
  - firebase_database (9.0.0):
    - Firebase/Database (= 8.11.0)
    - firebase_core
    - Flutter
  - FirebaseAuth (8.11.0):
    - FirebaseCore (~> 8.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 7.7)
    - GoogleUtilities/Environment (~> 7.7)
    - GTMSessionFetcher/Core (~> 1.5)
  - FirebaseCore (8.11.0):
    - FirebaseCoreDiagnostics (~> 8.0)
    - GoogleUtilities/Environment (~> 7.7)
    - GoogleUtilities/Logger (~> 7.7)
  - FirebaseCoreDiagnostics (8.14.0):
    - GoogleDataTransport (~> 9.1)
    - GoogleUtilities/Environment (~> 7.7)
    - GoogleUtilities/Logger (~> 7.7)
    - nanopb (~> 2.30908.0)
  - FirebaseDatabase (8.11.0):
    - FirebaseCore (~> 8.0)
    - leveldb-library (~> 1.22)
  - Flutter (1.0.0)
  - GoogleDataTransport (9.1.2):
    - GoogleUtilities/Environment (~> 7.2)
    - nanopb (~> 2.30908.0)
    - PromisesObjC (< 3.0, >= 1.2)
  - GoogleUtilities/AppDelegateSwizzler (7.7.0):
    - GoogleUtilities/Environment
    - GoogleUtilities/Logger
    - GoogleUtilities/Network
  - GoogleUtilities/Environment (7.7.0):
    - PromisesObjC (< 3.0, >= 1.2)
  - GoogleUtilities/Logger (7.7.0):
    - GoogleUtilities/Environment
  - GoogleUtilities/Network (7.7.0):
    - GoogleUtilities/Logger
    - "GoogleUtilities/NSData+zlib"
    - GoogleUtilities/Reachability
  - "GoogleUtilities/NSData+zlib (7.7.0)"
  - GoogleUtilities/Reachability (7.7.0):
    - GoogleUtilities/Logger
  - GTMSessionFetcher/Core (1.7.1)
  - leveldb-library (1.22.1)
  - nanopb (2.30908.0):
    - nanopb/decode (= 2.30908.0)
    - nanopb/encode (= 2.30908.0)
  - nanopb/decode (2.30908.0)
  - nanopb/encode (2.30908.0)
  - PromisesObjC (2.0.0)

DEPENDENCIES:
  - firebase_auth (from `.symlinks/plugins/firebase_auth/ios`)
  - firebase_core (from `.symlinks/plugins/firebase_core/ios`)
  - firebase_database (from `.symlinks/plugins/firebase_database/ios`)
  - Flutter (from `Flutter`)

SPEC REPOS:
  trunk:
    - Firebase
    - FirebaseAuth
    - FirebaseCore
    - FirebaseCoreDiagnostics
    - FirebaseDatabase
    - GoogleDataTransport
    - GoogleUtilities
    - GTMSessionFetcher
    - leveldb-library
    - nanopb
    - PromisesObjC

EXTERNAL SOURCES:
  firebase_auth:
    :path: ".symlinks/plugins/firebase_auth/ios"
  firebase_core:
    :path: ".symlinks/plugins/firebase_core/ios"
  firebase_database:
    :path: ".symlinks/plugins/firebase_database/ios"
  Flutter:
    :path: Flutter

SPEC CHECKSUMS:
  Firebase: 44dd9724c84df18b486639e874f31436eaa9a20c
  firebase_auth: bdfbd5b10da1db6d5eb6ae7dbda5d81365b9cc9d
  firebase_core: 443bccfd6aa6b42f07be365b500773dc69db2d87
  firebase_database: 2917b5dc256a1f4d249e03b385a0a17b0a4a7a08
  FirebaseAuth: d96d73aba85d192d7a7aa0b86dd6d7f8ec170b4b
  FirebaseCore: 2f4f85b453cc8fea4bb2b37e370007d2bcafe3f0
  FirebaseCoreDiagnostics: fd0c8490f34287229c1d6c103d3a55f81ec85712
  FirebaseDatabase: ff9b4c7bee14d9f561f26c64a28ac083989f03d5
  Flutter: 50d75fe2f02b26cc09d224853bb45737f8b3214a
  GoogleDataTransport: 629c20a4d363167143f30ea78320d5a7eb8bd940
  GoogleUtilities: e0913149f6b0625b553d70dae12b49fc62914fd1
  GTMSessionFetcher: 4577a4cc914a5a07c40a8a0ad0acc22080418c2d
  leveldb-library: 50c7b45cbd7bf543c81a468fe557a16ae3db8729
  nanopb: a0ba3315591a9ae0a16a309ee504766e90db0c96
  PromisesObjC: 68159ce6952d93e17b2dfe273b8c40907db5ba58

PODFILE CHECKSUM: fe0e1ee7f3d1f7d00b11b474b62dd62134535aea

COCOAPODS: 1.11.3
```

</details>

### Flutter doctor

<details>
  <summary>Click to Expand</summary>

```
[✓] Flutter (Channel stable, 2.10.3, on macOS 11.4 20F71 darwin-arm, locale en-LT)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[!] Android Studio (not installed)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.2)
[✓] Connected device (2 available)
[✓] HTTP Host Availability
```
</details>

### Flutter dependencies
<details>
  <summary>Click to Expand</summary>

```
Dart SDK 2.16.1
Flutter SDK 2.10.3

dependencies:
- cupertino_icons 1.0.4
- firebase_auth 3.3.11 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 1.12.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_database 9.0.8 [firebase_core firebase_core_platform_interface firebase_database_platform_interface firebase_database_web flutter]
- flutter 0.0.0 [characters collection material_color_utilities meta typed_data vector_math sky_engine]
- flutter_bloc 8.0.1 [flutter bloc provider]
- freezed 0.15.1+1 [analyzer build build_config collection meta source_gen freezed_annotation]
- freezed_annotation 0.15.0 [collection json_annotation meta]

dev dependencies:
- build_runner 2.1.8 [args async analyzer build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style frontend_server_client glob graphs http_multi_server io js logging meta mime package_config path pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web_socket_channel yaml]
- flutter_lints 1.0.4 [lints]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher material_color_utilities meta source_span stream_channel string_scanner term_glyph typed_data]

transitive dependencies:
- _fe_analyzer_shared 31.0.0 [meta]
- analyzer 2.8.0 [_fe_analyzer_shared cli_util collection convert crypto glob meta package_config path pub_semver source_span watcher yaml]
- args 2.3.0
- async 2.8.2 [collection meta]
- bloc 8.0.3 [meta]
- boolean_selector 2.1.0 [source_span string_scanner]
- build 2.2.1 [analyzer async convert crypto glob logging meta path]
- build_config 1.0.0 [checked_yaml json_annotation path pubspec_parse yaml]
- build_daemon 3.0.1 [built_collection built_value http_multi_server logging path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 2.0.6 [analyzer async build crypto graphs logging path package_config pool pub_semver stream_transform yaml]
- build_runner_core 7.2.3 [async build build_config build_resolvers collection convert crypto glob graphs json_annotation logging meta path package_config pool timing watcher yaml]
- built_collection 5.1.1
- built_value 8.1.4 [built_collection collection fixnum meta]
- characters 1.2.0
- charcode 1.3.1
- checked_yaml 2.0.1 [json_annotation source_span yaml]
- cli_util 0.3.5 [meta path]
- clock 1.1.0
- code_builder 4.1.0 [built_collection built_value collection matcher meta]
- collection 1.15.0
- convert 3.0.1 [typed_data]
- crypto 3.0.1 [collection typed_data]
- dart_style 2.2.1 [analyzer args path pub_semver source_span]
- fake_async 1.2.0 [clock collection]
- file 6.1.2 [meta path]
- firebase_auth_platform_interface 6.2.1 [firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 3.3.9 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core_platform_interface 4.2.5 [collection flutter meta plugin_platform_interface]
- firebase_core_web 1.6.1 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_database_platform_interface 0.2.1+1 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_database_web 0.2.0+7 [firebase_core firebase_core_web firebase_database_platform_interface flutter flutter_web_plugins js]
- fixnum 1.0.0
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta typed_data vector_math]
- frontend_server_client 2.1.2 [async path]
- glob 2.0.2 [async collection file path string_scanner]
- graphs 2.1.0 [collection]
- http_multi_server 3.2.0 [async]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
- intl 0.17.0 [clock path]
- io 1.0.3 [meta path string_scanner]
- js 0.6.3
- json_annotation 4.4.0 [meta]
- lints 1.0.1
- logging 1.0.2
- matcher 0.12.11 [stack_trace]
- material_color_utilities 0.1.3
- meta 1.7.0
- mime 1.0.1
- nested 1.0.0 [flutter]
- package_config 2.0.2 [path]
- path 1.8.0
- plugin_platform_interface 2.1.2 [meta]
- pool 1.5.0 [async stack_trace]
- provider 6.0.2 [collection flutter nested]
- pub_semver 2.1.1 [collection meta]
- pubspec_parse 1.2.0 [checked_yaml collection json_annotation pub_semver yaml]
- shelf 1.2.0 [async collection http_parser path stack_trace stream_channel]
- shelf_web_socket 1.0.1 [shelf stream_channel web_socket_channel]
- sky_engine 0.0.99
- source_gen 1.2.1 [analyzer async build dart_style glob meta path source_span yaml]
- source_span 1.8.1 [collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- stream_transform 2.0.0
- string_scanner 1.1.0 [charcode source_span]
- term_glyph 1.2.0
- test_api 0.4.8 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- timing 1.0.0 [json_annotation]
- typed_data 1.3.0 [collection]
- vector_math 2.1.1
- watcher 1.0.1 [async path]
- web_socket_channel 2.1.0 [async crypto stream_channel]
- yaml 3.1.0 [collection source_span string_scanner]

```
</details>

### What I have tried

- Running flutter clean in ios directory, also deleting the /Pods directory and rebuilding them
- Changing Xcode build target
- Creating a new project and copying over the pubspec.yaml. It builds fine at first, I copied the Podfile and Podfile.lock and symlinks directory to my project with no success. I then copied my code to the newly created project, the code was also built successfully but as soon as I logged in using firebase_auth, device connection was lost and the new project does not build anymore with the same Xcode error.

Hope this gets fixed or someone can advise me on what I should do as this issue has been a complete blocker.
Regards and thanks for your time.

**Comment by darshankawar** [comment] 2022-03-28 12:28
@MatasRut 
Try [this](https://github.com/firebase/flutterfire/issues/7831#issuecomment-1019654033) solution and see if it works for you.

**Comment by MatasRut** [comment] 2022-03-28 19:08
@darshankawar
I tried updating my Podfile as you suggested and also removing my ios folder completely and regenerating it with `flutter create .` but to no success. I then tried to build the app from `Runner.xcworkspace` as before I was doing it from `Runner.xcodeproj` the app builds successfully but then crashes a few seconds later with the following error:
<img width="1143" alt="Screenshot 2022-03-28 at 21 51 22" src="https://user-images.githubusercontent.com/78217506/160467696-55906289-21b8-4578-92f7-399bbe0e5929.png">
The error seems to be caused inside `FIRDatabase.m` on line 144 where reference path validation fails.

**Comment by darshankawar** [comment] 2022-03-29 12:17
@MatasRut 
Can you provide the entire error log in text format so that we can use it to debug further ?

**Comment by MatasRut** [comment] 2022-03-30 07:38
Hi, @darshankawar it turns out it was a problem within my code...
I was trying to access the database with `FirebaseDatabase.instance.ref();` expecting it to default the database path to `'/'` as null value is allowed here. I think it should either default to `'/'` or throw an error that would be clear. After changing the value to a certain path of the database, everything builds and works fine.

**Comment by darshankawar** [comment] 2022-03-30 09:53
Thanks for the update and glad to know the issue is resolved. 

> I think it should either default to `'/'` or throw an error that would be clear.

You may create a new issue for it

Closing this as resolved.

**Closed by darshankawar** 2022-03-30 09:53 UTC
Labels: type: bug, blocked: customer-response, in triage
