### ISSUE TITLE
🐛 [firebase_auth] Auth Reply already submitted Crash

### ISSUE THREAD

**Issue by RamsayGit** [firebase/flutterfire#11372] opened 2023-07-25 17:02 UTC
I'm getting this early crash (91% of crash events for this issue happened in the first 5 seconds of a user's session) happening frequently lately with the latest version of Firebase Auth 4.7.1:

```
Fatal Exception: java.lang.IllegalStateException: Reply already submitted
       at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:435)
       at io.flutter.plugin.common.BasicMessageChannel$IncomingMessageHandler$1.reply(BasicMessageChannel.java:222)
       at io.flutter.plugins.firebase.auth.GeneratedAndroidFirebaseAuth$FirebaseAuthUserHostApi$2.success(GeneratedAndroidFirebaseAuth.java:3247)
       at io.flutter.plugins.firebase.auth.GeneratedAndroidFirebaseAuth$FirebaseAuthUserHostApi$2.success(GeneratedAndroidFirebaseAuth.java:3244)
       at io.flutter.plugins.firebase.auth.FlutterFirebaseAuthUser.lambda$getIdToken$1(FlutterFirebaseAuthUser.java:88)
       at com.google.android.gms.tasks.zzi.run(com.google.android.gms:play-services-tasks@@18.0.2:1)
       at android.os.Handler.handleCallback(Handler.java:942)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8757)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```

Flutter doctor:
[✓] Flutter (Channel stable, 3.10.6, on Microsoft Windows [Version 10.0.22621.1992], locale en-US)
[✓] Windows Version (Installed version of Windows is version 10 or higher)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Chrome - develop for the web
[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.6.0)
[✓] Android Studio (version 2022.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.1)
[✓] Connected device (3 available)
[✓] Network resources

**Comment by austinn** [comment] 2023-07-25 18:56
I am also experiencing a crash. Looks like it's the new switch to `pigeon`. 

```
E/BasicMessageChannel#dev.flutter.pigeon.FirebaseAuthUserHostApi.getIdToken( 8320): Failed to handle message
E/BasicMessageChannel#dev.flutter.pigeon.FirebaseAuthUserHostApi.getIdToken( 8320): java.lang.IllegalStateException: Task is not yet complete
 	at com.google.android.gms.common.internal.Preconditions.checkState(com.google.android.gms:play-services-basement@@18.2.0:2)
 	at com.google.android.gms.tasks.zzw.zzf(com.google.android.gms:play-services-tasks@@18.0.2:1)
 	at com.google.android.gms.tasks.zzw.getResult(com.google.android.gms:play-services-tasks@@18.0.2:1)
 	at io.flutter.plugins.firebase.auth.FlutterFirebaseAuthUser.getIdToken(FlutterFirebaseAuthUser.java:95)
 	at io.flutter.plugins.firebase.auth.GeneratedAndroidFirebaseAuth$FirebaseAuthUserHostApi.lambda$setup$1(GeneratedAndroidFirebaseAuth.java:3256)
 	at io.flutter.plugins.firebase.auth.GeneratedAndroidFirebaseAuth$FirebaseAuthUserHostApi$$ExternalSyntheticLambda9.onMessage(Unknown Source:2)
 	at io.flutter.plugin.common.BasicMessageChannel$IncomingMessageHandler.onMessage(BasicMessageChannel.java:217)
 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
 	at android.os.Handler.handleCallback(Handler.java:958)
 	at android.os.Handler.dispatchMessage(Handler.java:99)
 	at android.os.Looper.loopOnce(Looper.java:205)
 	at android.os.Looper.loop(Looper.java:294)
 	at android.app.ActivityThread.main(ActivityThread.java:8170)
 	at java.lang.reflect.Method.invoke(Native Method)
 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
```

I also get an error in my try/catch over `getIdTokenResult()`, not sure if that's related or not

**Comment by austinn** [comment] 2023-07-25 19:10
> I also get an error in my try/catch over `getIdTokenResult()`, not sure if that's related or not

Just confirmed that it was `getIdTokenResult()`. I was doing this as soon as the user logged in, but it used to work prior to `4.7.0`

**Comment by rwrz** [comment] 2023-07-25 22:26
Seems it is refreshing the tokens every time, even if the refresh is set to false.

**Comment by RamsayGit** [comment] 2023-07-25 22:42
Sorry I did not understand what this means 'even if the refresh is set to
false'? the refresh token can be made to expire every 30 mins as a minimum
but App Check has to be on and security rules implemented.
In general the token will stop refreshing within a day or 2 days max if you
keep doing an app resume occasionally throughout the day and after that it
will be permanently stuck, and a permission denied error will be emitted as
shown in the screenshot I shared. If that does not happen it and you are
using a different firebase project then it might be due to the project
configuration differences, which is something I highlighted here
<https://github.com/RamsayGit/firebase-token-refresh-mcve>. You can also
just use the firebase project that my zip project references since it is
already setup.

Ramsay

**Comment by darshankawar** [comment] 2023-07-26 08:15
@RamsayGit and everyone facing the issue, You are likely hitting https://github.com/firebase/flutterfire/issues/11297 which has been fixed as of yesterday, https://github.com/firebase/flutterfire/pull/11362

Once a new plugin version is released, try it and see if it helps to fix the crash or not.
I'll close it for now in favor of the linked and fixed issue. If anyone disagree, write in comments and I'll reopen it.

**Closed by darshankawar** 2023-07-26 08:15 UTC
Labels: type: bug, Needs Attention, in triage
