### ISSUE TITLE
🐛 [firebase_auth]  need to be update to intl version 0.18.1

### ISSUE THREAD

**Issue by moinkhan780** [firebase/flutterfire#10880] opened 2023-05-01 11:32 UTC
## Bug report

Resolving dependencies...
Because no versions of phone_form_field match >7.1.0 <8.0.0 and phone_form_field 7.1.0 depends on flutter_localizations from sdk, phone_form_field ^7.1.0 requires flutter_localizations from sdk.
And because every version of flutter_localizations from sdk depends on intl 0.18.1, phone_form_field ^7.1.0 requires intl 0.18.1.
Because firebase_auth_web 5.3.2 depends on intl ^0.17.0 and no versions of firebase_auth_web match >5.3.2 <6.0.0, firebase_auth_web ^5.3.2 requires intl ^0.17.0.
Thus, phone_form_field ^7.1.0 is incompatible with firebase_auth_web ^5.3.2.
And because firebase_auth 4.4.2 depends on firebase_auth_web ^5.3.2 and no versions of firebase_auth match >4.4.2 <5.0.0, phone_form_field ^7.1.0 is incompatible with firebase_auth ^4.4.2.
So, because lillah depends on both firebase_auth ^4.4.2 and phone_form_field ^7.1.0, version solving failed.
pub get failed
command: "/Users/moinkhan/flutter/bin/cache/dart-sdk/bin/dart __deprecated_pub --directory . get --example"
pub env: {
  "FLUTTER_ROOT": "/Users/moinkhan/flutter",
  "PUB_ENVIRONMENT": "vscode.dart-code:flutter_cli:get",
  "PUB_CACHE": "/Users/moinkhan/.pub-cache",
}
exit code: 1

**Comment by darshankawar** [comment] 2023-05-02 12:50
Closing as duplicate of https://github.com/firebase/flutterfire/issues/10199.

**Closed by darshankawar** 2023-05-02 12:50 UTC
Labels: type: bug, Needs Attention, in triage
