### ISSUE TITLE
🐛 [firebase_ui_auth] An issue with dependency of the flutter_svg package has occurred.

### ISSUE THREAD

**Issue by Patrick386** [firebase/flutterfire#10816] opened 2023-04-19 06:23 UTC
An issue with dependency of the flutter_svg package has occurred.
Is it possible to update the packages to resolve the conflict?

```
Because pronto depends on firebase_ui_auth ^1.2.1 which depends on flutter_svg ^1.1.1, flutter_svg ^1.1.1 is required.
So, because pronto depends on flutter_svg ^2.0.2, version solving failed.
pub get failed
command: "C:\Dev\flutter\bin\cache\dart-sdk\bin\dart __deprecated_pub --directory . get --example"
pub env: {
  "FLUTTER_ROOT": "C:\Dev\flutter",
  "PUB_ENVIRONMENT": "flutter_cli:get",
  "PUB_CACHE": "C:\Users\SintPatrick\AppData\Local\Pub\Cache",
}
exit code: 1
```

**Comment by danagbemava-nc** [comment] 2023-04-19 08:53
Closing this as a duplicate of https://github.com/firebase/flutterfire/issues/10794. 

Kindly subscribe to the original issue for updates. 

Thank you

**Closed by danagbemava-nc** 2023-04-19 08:53 UTC
Labels: type: bug, Needs Attention, in triage
