### ISSUE TITLE
[firebase_messaging]: <Doesn’t work push notifications>

### ISSUE THREAD

**Issue by emanuelzallikodelabs** [firebase/flutterfire#11806] opened 2023-10-31 19:26 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you aware of the differences between iOS and Android background message handling?

- [X] I understand that iOS and Android background messages behave differently, and I've designed my application with that in mind.

### Do you have an active Apple Developer account?

- [X] I have an active Apple Developer account.

### Are you using a physical iOS device to test background messages?

- [X] I am using a physical iOS device to test background messages.

### Have you enabled "Remote Notifications" & "Background Mode" (Checking options for "Background Processing" & "Remote Notifications") in your app's Xcode project?

Yes I have enabled both of them

### Have you created an APNs key in your Apple Developer account & uploaded this APNs key to your Firebase console?

Yes I have created APNs key and uploaded

### Have you disabled method swizzling for Firebase in your app?

	<key>FirebaseAppDelegateProxyEnabled</key>
	<false/>

### Are you sending messages to your app from the Firebase Admin SDK?

same 

### Have you requested permission from the user to receive notifications?

- [X] I have the relevant permission to receive notifications.

### Have you used the 'Console' application on your macOS device to check if the iOS device's system is throttling your background messages?

-

### Additional context and comments

I get this error:
Unhandled Exception: [firebase_messaging/apns-token-not-set] APNS token has not been set yet. Please ensure the APNS token is available by calling `getAPNSToken()`.
 
when I try to call this method: getToken()

**Comment by darshankawar** [comment] 2023-11-01 10:44
@emanuelzallikodelabs 
The error indicates that an APNS token is required, but is missing in your app / configuration.

APNS token is a requirement for Firebase Messaging on Apple platform. [See documentation](https://firebase.google.com/docs/cloud-messaging/flutter/client) and warning section inside it.

Closing this issue, as it is not a bug.

**Closed by darshankawar** 2023-11-01 10:44 UTC
Labels: type: bug, plugin: messaging, platform: ios, Needs Attention, in triage
