### ISSUE TITLE
Error uploading file to Storage Emulator with 'firebase_storage' FlutterFire Package

### ISSUE THREAD

**Issue by Frank-D** [firebase/flutterfire#7186] opened 2021-10-16 14:25 UTC
Getting error when trying to upload file to Firebase Storage Emulator with 'firebase_storage' FlutterFire Package.

**[ENVIRONMENT INFO]**
- flutter: 2.5.2
- firebase_storage: ^10.0.5
- firebase-tools: 9.18.0
- emulator/simulator: ios simulator iphone 13
- os: macOS Big Sur 11.4
- code editor: vs code

**[STEPS TO REPRODUCE]**
1- Start the Firebase 'storage' emulator (+ optionally, the firebase 'auth' emulator as well, if your storage rules requires user to be authenticated in order to be allowed to upload files)
2- In your flutter app, run the following lines of code (if authentication required as stated above, authenticate your user against firebase auth before executing the file upload call):
```
await Firebase.initializeApp();
await FirebaseStorage.instance.useStorageEmulator("localhost", 9199); 
await FirebaseStorage.instance.ref().child("images").putFile(File("/tmp/any_file_or_image_path.png"));
```

**[EXPECTED BEHAVIOUR]**
The file is successfully uploaded to the storage emulator.

**[ACTUAL BEHAVIOUR]**
The file is 'not' uploaded to the storage emulator, and instead, I'm getting a warning message in the flutter app logs followed by an exception:
```
WARNING: Unable to set the Firebase Storage emulator settings. These must be set before any usages of Firebase Storage. If you see this log after a hot reload/restart you can safely ignore it.

[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: [firebase_storage/unauthorized] User is not authorized to perform the desired action.
```
I can confirm that my app user 'was' authenticated with firebase auth during the testing.
For the record, I do have the ootb storage.rules file in place and properly referenced in the firebase.json file on my local env. The storage emulator also starts successfully, and I can access its UI @ http://localhost:8081/storage, and manually upload files successfully using that same UI. The above 2 log messages are generated when I make the call to `...putFile(...)`, not before (especially the warning msg).

**[LINKED ISSUE(S)]**
Same error was filed by another member against `firebase-tools` project (..but we're unsure if the error is with the firebase-storage emulator, or with the FlutterFire 'firebase_storage' package..):
https://github.com/firebase/firebase-tools/issues/3765

Thanks

**Comment by nipunasudha** [comment] 2021-11-10 10:36
I have the exact same behavior & error in iOS simulator with Firebase emulator. Firebase storage version is `firebase_storage: ^10.1.0`

**Comment by russellwheatley** [comment] 2021-12-22 10:49
Hi @Frank-D, not much we can do about this one a far as I can tell. Once we've passed all the inputs to the iOS Storage SDK, it is up to that to pass along the auth token with the requests to the emulator which is where I believe the problem lies. Worth tracking https://github.com/firebase/firebase-tools/issues/3584 as mentioned above.

**Comment by jsdaniell** [comment] 2022-01-08 18:21
I'm also facing this problem, in my case the `storage.rules` used on emulator it's like this:

```rules
rules_version = '2';
service firebase.storage {
  match /b/{bucket}/o {
    match /{allPaths=**} {
      allow read, write: if true;
    }
  }
}
```

And even with this configuration this error happens:
`WARNING: Unable to set the Firebase Storage emulator settings. These must be set before any usages of Firebase Storage. If you see this log after a hot reload/restart you can safely ignore it.
`

The code used to configure the emulator it's like this:

```dart
  await FirebaseStorage.instance.useStorageEmulator(localhost, 9199);
```

Seems that's a problem on `firebase_storage` package, here's the versions of firebase libs on my `pubspec.yaml`

```yaml
  firebase_core: ^1.11.0
  cloud_firestore: ^3.1.6
  cloud_functions: ^3.2.4
  firebase_auth: ^3.3.4
  google_sign_in: ^5.2.1
  firebase_dynamic_links: ^4.0.3
  firebase_storage: ^10.2.5
```

**Comment by russellwheatley** [comment] 2022-01-12 14:06
> I'm also facing this problem, in my case the `storage.rules` used on emulator it's like this:
> 
> ```
> rules_version = '2';
> service firebase.storage {
>   match /b/{bucket}/o {
>     match /{allPaths=**} {
>       allow read, write: if true;
>     }
>   }
> }
> ```
> 
> And even with this configuration this error happens: `WARNING: Unable to set the Firebase Storage emulator settings. These must be set before any usages of Firebase Storage. If you see this log after a hot reload/restart you can safely ignore it. `
> 
> The code used to configure the emulator it's like this:
> 
> ```dart
>   await FirebaseStorage.instance.useStorageEmulator(localhost, 9199);
> ```
> 
> Seems that's a problem on `firebase_storage` package, here's the versions of firebase libs on my `pubspec.yaml`
> 
> ```yaml
>   firebase_core: ^1.11.0
>   cloud_firestore: ^3.1.6
>   cloud_functions: ^3.2.4
>   firebase_auth: ^3.3.4
>   google_sign_in: ^5.2.1
>   firebase_dynamic_links: ^4.0.3
>   firebase_storage: ^10.2.5
> ```

@jsdaniell, This warning is probably happening because you aren't using `storageEmulator()` early enough. [See here](https://firebase.flutter.dev/docs/storage/usage#emulator-usage).

**Comment by ggirotto** [comment] 2022-03-20 13:03
Facing the same issue. https://github.com/firebase/firebase-tools/issues/3584 was already merged and deploy, but the issue persists here. Every time I want to upload a file to the Storage emulator, it outputs:

`WARNING: Unable to set the Firebase Storage emulator settings. These must be set before any usages of Firebase Storage. If you see this log after a hot reload[/restart]() you can safely ignore it.`

And the storage error:

`[firebase_storage[/unknown]()] An unknown error occurred, please check the server response.`

**Comment by russellwheatley** [comment] 2022-03-22 11:58
@jsdaniell, you should await this function:

```dart
  if (useFirebaseEmulator) {
   await  _connectToFirebaseEmulator();
  }
``` 

@ggirotto, is that the full error? How are you initializing emulator?

**Comment by russellwheatley** [comment] 2022-03-22 13:42
What `firebase-tools` version are you on?

I think this issue might be stemming from the `firebase-tools` storage emulator as noted [here](https://github.com/invertase/react-native-firebase/pull/6122#issuecomment-1072000157). 

We've also just hit this problem in our iOS e2e CI tests [here](https://github.com/FirebaseExtended/flutterfire/runs/5643693908?check_suite_focus=true)

**Comment by ggirotto** [comment] 2022-03-22 14:10
> @ggirotto What `firebase-tools` version are you on?
> 
> I think this issue might be stemming from the `firebase-tools` storage emulator as noted [here](https://github.com/invertase/react-native-firebase/pull/6122#issuecomment-1072000157).
> 
> We've also just hit this problem in our iOS e2e CI tests [here](https://github.com/FirebaseExtended/flutterfire/runs/5643693908?check_suite_focus=true)

I'm using the latest version: `10.4.1`. It's necessary to wait a fix in the flutter plugin then? They recently launched support to multiple storage rules in the CLI, I'm not sure if this may have conflict with the current plugin version.

**Comment by russellwheatley** [comment] 2022-03-22 14:31
Seems like there is a bug with `firebase-tools`. You could try and install an earlier version (like `10.0.0` perhaps) and see if you still get the same error. That would also provide a reproducible bug to take to the `firebase-tools` repo .

**Comment by russellwheatley** [comment] 2022-05-05 09:22
Hey @Frank-D, a bunch of bug fixes were released on `firebase-tools` including the [auth issue](https://github.com/firebase/firebase-tools/issues/3584) you were experiencing. Could you let us know if your problem has been solved? Thanks!

**Comment by ggirotto** [comment] 2022-05-05 15:29
After upgrading `firebase-tools` the errors are gone here!

**Closed** 2022-05-05 16:34 UTC
Labels: blocked: customer-response, plugin: storage, platform: ios, blocked: firebase-sdk
