### ISSUE TITLE
🐛 [firebase_analytics] page/screen views are not being sent for web

### ISSUE THREAD

**Issue by steebchen** [firebase/flutterfire#8403] opened 2022-04-05 16:40 UTC
This is the same issue as #4910, but it was closed and locked. Ideally we could maybe re-open this one as it has more context and more people watching.

Basically, with the latest firebase_analytics: ^9.1.3 page/screen views are still not being sent properly. Yes, it might show in the debugger, but they never show up in Google Analytics, and you can verify this by running a Flutter app in the browser and not seeing any events sent to GA.

The best easy reproduction I can give is the project I'm working on, which is using the latest firebase_analytics version.

In the following video, you can see that:
1) On page load, there is a page_view event sent
2) When I navigate between pages, there are NO events send (this works on iOS+Android)
3) Other events, even custom ones, work, as shown towards the end of the video with the custom event 'connect'

https://user-images.githubusercontent.com/5013932/161806241-1d29c263-3ac1-436a-86c8-2f63e53d6a26.mov

I'm using the observer in the `navigatorObservers` parameter in the `MaterialApp` widget:

```dart
navigatorObservers: [
  FirebaseAnalyticsObserver(analytics: analytics),
],
```

```
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  graphql_flutter: ^5.0.1-beta.6
  intl: ^0.17.0
  syncfusion_flutter_charts: ^19.1.69+1
  provider: ^5.0.0
  cached_network_image: ^3.0.0
  infinite_scroll_pagination: ^3.1.0
  papercups_flutter: ^2.1.0+1
  firebase_core: ^1.13.1
  firebase_analytics: ^9.1.3
  firebase_dynamic_links: ^2.0.9
  firebase_performance: ^0.7.1
  flutter_custom_tabs: ^1.0.3
  sentry_flutter: ^6.0.1
  package_info_plus: ^1.0.6
  url_launcher: ^6.0.20
  purchases_flutter: ^3.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  artemis: ^7.0.0-beta.9
  build_runner: ^2.0.1
  json_serializable: ^4.1.0
  flutter_native_splash: ^1.2.0
  flutter_lints: ^1.0.4
```

```
❯ flutter doctor -v         
[✓] Flutter (Channel stable, 2.10.0, on macOS 12.3 21E230 darwin-arm, locale en-DE)
    • Flutter version 2.10.0 at /opt/homebrew/Caskroom/flutter/2.10.0/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5f105a6ca7 (9 weeks ago), 2022-02-01 14:15:42 -0800
    • Engine revision 776efd2034
    • Dart version 2.16.0
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/steebchen/Library/Android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 65.2.4
    • Dart plugin version 213.7306

[✓] Connected device (5 available)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

**Comment by darshankawar** [comment] 2022-04-06 10:25
@steebchen 
Thanks for the report. Please see [this](https://github.com/firebase/flutterfire/issues/7287) similar issue and [this](https://github.com/firebase/flutterfire/issues/7287#issuecomment-1084812431) issue comment from team member for your reference and accordingly, you'll need to reach out to firebase support for resolution. We can close this issue as duplicate of the linked one if you are ok with it and get any feedback from firebase support team.

**Comment by steebchen** [comment] 2022-04-06 16:52
@darshankawar I do not think we should close my issue as I don't think it's the same thing.

The difference from my perspective is that in your linked issue the events are sent but just not for whatever reason searchable in GA. However, the issue I reported here is that specifically screen events aren't actually sent from the browser to GA, but on mobile everything seems to work, and all other events in web are properly sent. I can see the events sent from mobile and the custom events from both mobile+web in GA4, it's just that as per my screen recording the event in the browser is never sent, so it must be a plugin issue or another kind of library issue as far as I understand.

Let me know if you have any more questions.

**Comment by darshankawar** [comment] 2022-04-07 11:04
@steebchen 
Thanks for the feedback. As I understand, the events are being triggered but are not captured properly at GA4, which I am not completely sure if falls under flutterfire to fix, but I'll keep this issue open for further insights from the team.

/cc @russellwheatley .  This is similar issue as https://github.com/firebase/flutterfire/issues/4910 in which the latest update was https://github.com/firebase/flutterfire/issues/4910#issuecomment-1026810073 and https://github.com/firebase/flutterfire/issues/4910#issuecomment-1026950892

**Comment by svanter** [comment] 2022-06-14 23:56
Hi @darshankawar /@russellwheatly I dug some more into this.

What is happening is setCurrentScreen on  the firebase analytics object does not currently work.
The navigation observer is correctly intercepting navigation changes and calling the interop layer, but that's where things break down. 

When I call setCurrentScreen in the chrome console, nothing happens, but when I call logEvent, that succeeds.

There are two paths here as I see it:
1) Migrate FirebaseAnalyticsObserver to call logEvent as specified in the deprecation details for setCurrentScreen. This happens in the dart layer.
2) Fix setCurrentScreen not working in the JS layer.

I prefer #1 as that would not rely on a deprecated codepath

**Closed** 2022-08-24 10:33 UTC
Labels: type: bug, plugin: analytics, platform: web

**Comment by steebchen** [comment] 2022-08-24 12:08
Thanks for fixing!
