### ISSUE TITLE
Add Privacy Manifests and code sign Frameworks for Apple

### ISSUE THREAD

**Issue by ChristianEdwardPadilla** [firebase/flutterfire#12320] opened 2024-02-12 23:15 UTC
Apple will be requiring apps to include more privacy-related reasoning for "third-party SDKs" in "Spring 2024": https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_data_use_in_privacy_manifests?language=objc

You can see these FlutterFire plugins included on the list of commonly used third-party SDKs here: https://developer.apple.com/support/third-party-SDK-requirements/

It's not clear if this will affect both iOS and macOS, or just iOS.

You can see examples of these manifests included in other popular Flutter plugins, for example shared_preferences: https://github.com/flutter/packages/blob/main/packages/shared_preferences/shared_preferences_foundation/darwin/Resources/PrivacyInfo.xcprivacy

**Comment by danagbemava-nc** [comment] 2024-02-13 11:00
I'm not sure if it will fine if this is done for just the iOS sdk or if this will have to be done in this sdk as well. 

This would apply to all the plugins in this repo. There is an issue tracking implementing this in the iOS sdk. See 
https://github.com/firebase/firebase-ios-sdk/issues/11490

cc @russellwheatley for further insight

**Comment by GJDK** [comment] 2024-02-20 05:44
Hi Team,

Any update on this?

**Comment by Lyokone** [comment] 2024-02-23 09:47
Hello, the underlying native ios SDK is planning to add privacy manifests before the mandatory date. To my understanding, you will just need to update the FlutterFire version once available to get privacy manifests added automatically.

**Comment by jamieastley** [comment] 2024-03-05 03:01
looks like this should be unblocked now as https://github.com/firebase/firebase-ios-sdk/issues/11490 was closed earlier, and privacy manifests are included as of the 10.22.0 release.

**Comment by Lyokone** [comment] 2024-03-11 13:55
Closing this issue since the latest firebase_core includes 10.22.0 release

**Comment by sbt-peds** [comment] 2024-03-27 06:07
@jamieastley @Lyokone Hello. Based on https://github.com/firebase/firebase-ios-sdk/issues/12238, it looks like both privacy manifest and code signing are required to fully comply with ios privacy policy, and the new firebase_core must be released for code singning, right?

**Comment by russellwheatley** [comment] 2024-03-27 08:52
@sbt-peds - thanks for sharing the link. I'll keep this open until code signing has also been completed upstream on the firebase-ios-sdk.

Please follow this link for further details: https://github.com/firebase/firebase-ios-sdk/issues/12238

**Comment by jamieastley** [comment] 2024-04-10 06:03
@russellwheatley codesigning should be available now in 10.24.0

https://github.com/firebase/firebase-ios-sdk/issues/12238#issuecomment-2046000115

**Comment by russellwheatley** [comment] 2024-04-10 08:38
@jamieastley - We are working on getting this updated. It isn't quite as straight forward as changing the SDK version. Hopefully, next week's release will have the update 🙏

**Comment by ChristianEdwardPadilla** [comment] 2024-04-10 15:04
Just want to flag a potential issue: while the underlying Firebase SDK includes a manifest firebase_messaging itself uses a Required Reason API, `NSUserDefaults` ([here](https://github.com/firebase/flutterfire/blob/213608cf7d889aeb60084ef5fb74a1e74178d7ba/packages/firebase_messaging/firebase_messaging/ios/Classes/FLTFirebaseMessagingPlugin.m#L174)). I think, to be safe, that firebase_messaging should add its own privacy manifest.

**Comment by paul678** [comment] 2024-04-17 12:06
I can confirm the above. The `firebase_messaging` plugin contains R.R API and it has no privacy manifest. It's also statically linked so it means it will show up as `Runner` when **ITMS-91053** is returned. 
Checking the symbols table to the runner using the plugin will show `NSUserDefaults` used, as soon as I remove it this will go away as expected.

Any plans to fix this issue as it's currently forcing all plugin users to create their own privacy manifest just to account for this 😢

**Comment by russellwheatley** [comment] 2024-04-17 12:40
@paul678 - thanks for the report, I'll get this updated 🙏

**Comment by jamieastley** [comment] 2024-04-17 23:07
@russellwheatley there's a forever-evolving [comment from the Flutter team](https://github.com/flutter/flutter/issues/131940#issuecomment-2006965339) here that has some ongoing updates around this that may help (point #2 iv.).

AFAIK there's no other easy ways to validate compliance without submitting a build, it's insane to me that this wasn't shipped in XCode prior to these requirements being enforced..

**Closed** 2024-04-23 07:57 UTC
Labels: type: enhancement, platform: ios
