### ISSUE TITLE
🐛 [Cloud_firestore] `firebase deploy` succeeds for version of plugin that is incompatible host environment.

### ISSUE THREAD

**Issue by polina-c** [firebase/flutterfire#11354] opened 2023-07-23 20:56 UTC
Code that access data, works locally, when I start the app with `flutter run --release` or with `dhttpd --path build/web/`, but does not work when hosted with Firebase, deployed with command `firebase deploy`.

Code:
```
import 'package:cloud_firestore/cloud_firestore.dart';
...
final json = (await _firestore.collection(name).doc(id).get()).data();
```

Error:
```
MissingPluginException(No implementation found for method DocumentReference#get on channel plugins.flutter.io/firebase_firestore)
```

What can be missing?

<img width="704" alt="Screenshot 2023-07-23 at 1 14 31 PM" src="https://github.com/firebase/flutterfire/assets/12115586/13268f00-af91-455f-a581-1c8876bd0a99">

**Comment by polina-c** [comment] 2023-07-23 21:00
This question is duplicated on SO: https://stackoverflow.com/questions/76750156/flutter-web-cannot-access-data-when-hosted-on-firebase

**Comment by polina-c** [comment] 2023-07-23 22:21
Okay, switching to flutter stable solved the problem.
Should `firebase deploy` fail if the version of plugin is not supported in firebase hosting?

**Comment by darshankawar** [comment] 2023-07-24 13:07
Thanks for the report @polina-c 


> Should `firebase deploy` fail if the version of plugin is not supported in firebase hosting?

I think this would be a question more for firebase-tools github repo here: https://github.com/firebase/firebase-tools/issues

**Comment by polina-c** [comment] 2023-08-07 02:48
Steps:

1. Switch to flutter master
2. Create application that reads/writes firebase data 
3. Test it locally 
4. Deploy to web with `firebase deploy`
5. Observe that the hosted application fails to access data without visible reason
6. Switch to flutter stable
7. Deploy to web with `firebase deploy`
5. Observe that the hosted application works well


Expected:
Item #4 should fail with message that the application is compiled with version of flutter that is not supported by hosting environment yet.

Does it help?

**Comment by darshankawar** [comment] 2023-08-07 11:43
Thanks for the detailed steps. I was able to replicate it as reported.

**Comment by Lyokone** [comment] 2023-11-15 14:12
Hi @polina-c, is it something that you are still experiencing? Thanks

**Comment by polina-c** [comment] 2023-11-15 17:27
> Hi @polina-c, is it something that you are still experiencing? Thanks

I am not experiencing it, because I know I should switch to stable channel of Flutter in order for deployment to work. Any other developer who uses Flutter master or beta channels, will experience the issue and will be frustrated.

**Comment by russellwheatley** [comment] 2023-12-21 10:24
We test FlutterFire against Flutter's stable channel. I think when you change channel to dev or stable channel, FlutterFire is at risk of not working as intended. I imagine more experienced devs would think to change to dev or master channel. The [documentation on Flutter](https://docs.flutter.dev/release/upgrade#the-stable-channel) itself makes clear:

> We recommend the stable channel for new users and for production app releases. 

I'm going to close this as I don't think there is anything to action.

**Closed by russellwheatley** 2023-12-21 10:24 UTC
Labels: type: bug, plugin: cloud_firestore, Needs Attention
