### ISSUE TITLE
I have updated the flutter to 3.10.2. I am facing the issue related to firebase.

### ISSUE THREAD

**Issue by HumayunZaib** [firebase/flutterfire#11061] opened 2023-05-31 06:15 UTC
## Bug report

**Describe the bug**
When I am trying to run it on Windows, It is the giving the below error.

### Steps to reproduce

flutter run output
firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_app_desktop.obj) : warning LNK4099: PDB 'firebase_app.pdb' was not found with 'firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_app_desktop.obj)' or at 'D:\Technupur\G-County\build\windows\plugins\firebase_core\Debug\firebase_app.pdb'; linking object as if no debug info [D:\Technupur\G-County\build\windows\plugins\firebase_core\firebase_core_plugin.vcxproj]
firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_log.obj) : warning LNK4099: PDB 'firebase_app.pdb' was not found with 'firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_log.obj)' or at 'D:\Technupur\G-County\build\windows\plugins\firebase_core\Debug\firebase_app.pdb'; linking object as if no debug info [D:\Technupur\G-County\build\windows\plugins\firebase_core\firebase_core_plugin.vcxproj]
firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_app_options.obj) : warning LNK4099: PDB 'firebase_app.pdb' was not found with 'firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_app_options.obj)' or at 'D:\Technupur\G-County\build\windows\plugins\firebase_core\Debug\firebase_app.pdb'; linking object as if no debug info [D:\Technupur\G-County\build\windows\plugins\firebase_core\firebase_core_plugin.vcxproj]
firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_app_common.obj) : warning LNK4099: PDB 'firebase_app.pdb' was not found with 'firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_app_common.obj)' or at 'D:\Technupur\G-County\build\windows\plugins\firebase_core\Debug\firebase_app.pdb'; linking object as if no debug info [D:\Technupur\G-County\build\windows\plugins\firebase_core\firebase_core_plugin.vcxproj]
firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_mutex_windows.obj) : warning LNK4099: PDB 'firebase_app.pdb' was not found with 'firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_mutex_windows.obj)' or at 'D:\Technupur\G-County\build\windows\plugins\firebase_core\Debug\firebase_app.pdb'; linking object as if no debug info [D:\Technupur\G-County\build\windows\plugins\firebase_core\firebase_core_plugin.vcxproj]
firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_date_provider.obj) : warning LNK4099: PDB 'firebase_app.pdb' was not found with 'firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_date_provider.obj)' or at 'D:\Technupur\G-County\build\windows\plugins\firebase_core\Debug\firebase_app.pdb'; linking object as if no debug info [D:\Technupur\G-County\build\windows\plugins\firebase_core\firebase_core_plugin.vcxproj]
firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_heartbeat_controller_desktop.obj) : warning LNK4099: PDB 'firebase_app.pdb' was not found with 'firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_heartbeat_controller_desktop.obj)' or at 'D:\Technupur\G-County\build\windows\plugins\firebase_core\Debug\firebase_app.pdb'; linking object as if no debug info [D:\Technupur\G-County\build\windows\plugins\firebase_core\firebase_core_plugin.vcxproj]
firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_log_stdio.obj) : warning LNK4099: PDB 'firebase_app.pdb' was not found with 'firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_log_stdio.obj)' or at 'D:\Technupur\G-County\build\windows\plugins\firebase_core\Debug\firebase_app.pdb'; linking object as if no debug info [D:\Technupur\G-County\build\windows\plugins\firebase_core\firebase_core_plugin.vcxproj]
firebase_app.lib(d3d7d08a438878e74aeb2cbaaedfc967_flatbuffers.dir_Debug_idl_parser.obj) : warning LNK4099: PDB 'flatbuffers.pdb' was not found with 'firebase_app.lib(d3d7d08a438878e74aeb2cbaaedfc967_flatbuffers.dir_Debug_idl_parser.obj)' or at 'D:\Technupur\G-County\build\windows\plugins\firebase_core\Debug\flatbuffers.pdb'; linking object as if no debug info [D:\Technupur\G-County\build\windows\plugins\firebase_core\firebase_core_plugin.vcxproj]
firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_google_services_resource.obj) : warning LNK4099: PDB 'firebase_app.pdb' was not found 
with 'firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_google_services_resource.obj)' or at 'D:\Technupur\G-County\build\windows\plugins\firebase_core\Debug\firebase_app.pdb'; linking object as if no debug info [D:\Technupur\G-County\build\windows\plugins\firebase_core\firebase_core_plugin.vcxproj]
firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_logger.obj) : warning LNK4099: PDB 'firebase_app.pdb' was not found with 'firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_logger.obj)' or at 'D:\Technupur\G-County\build\windows\plugins\firebase_core\Debug\firebase_app.pdb'; linking object as if no debug info [D:\Technupur\G-County\build\windows\plugins\firebase_core\firebase_core_plugin.vcxproj]
firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_callback.obj) : warning LNK4099: PDB 'firebase_app.pdb' was not found with 'firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_callback.obj)' or at 'D:\Technupur\G-County\build\windows\plugins\firebase_core\Debug\firebase_app.pdb'; linking object as if no debug info [D:\Technupur\G-County\build\windows\plugins\firebase_core\firebase_core_plugin.vcxproj]
firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_cleanup_notifier.obj) : warning LNK4099: PDB 'firebase_app.pdb' was not found with 'firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_cleanup_notifier.obj)' or at 'D:\Technupur\G-County\build\windows\plugins\firebase_core\Debug\firebase_app.pdb'; linking object as if no debug info [D:\Technupur\G-County\build\windows\plugins\firebase_core\firebase_core_plugin.vcxproj]
firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_util.obj) : warning LNK4099: PDB 'firebase_app.pdb' was not found with 'firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_util.obj)' or at 'D:\Technupur\G-County\build\windows\plugins\firebase_core\Debug\firebase_app.pdb'; linking object as if no debug info [D:\Technupur\G-County\build\windows\plugins\firebase_core\firebase_core_plugin.vcxproj]
firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_heartbeat_storage_desktop.obj) : warning LNK4099: PDB 'firebase_app.pdb' was not found with 'firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_heartbeat_storage_desktop.obj)' or at 'D:\Technupur\G-County\build\windows\plugins\firebase_core\Debug\firebase_app.pdb'; linking object as if no debug info [D:\Technupur\G-County\build\windows\plugins\firebase_core\firebase_core_plugin.vcxproj]
firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_scheduler.obj) : warning LNK4099: PDB 'firebase_app.pdb' was not found with 'firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_scheduler.obj)' or at 'D:\Technupur\G-County\build\windows\plugins\firebase_core\Debug\firebase_app.pdb'; linking object as if no debug info [D:\Technupur\G-County\build\windows\plugins\firebase_core\firebase_core_plugin.vcxproj]
firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_zlibwrapper.obj) : warning LNK4099: PDB 'firebase_app.pdb' was not found with 'firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_zlibwrapper.obj)' or at 'D:\Technupur\G-County\build\windows\plugins\firebase_core\Debug\firebase_app.pdb'; linking object as if no debug info [D:\Technupur\G-County\build\windows\plugins\firebase_core\firebase_core_plugin.vcxproj]
firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_base64.obj) : warning LNK4099: PDB 'firebase_app.pdb' was not found with 'firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_base64.obj)' or at 'D:\Technupur\G-County\build\windows\plugins\firebase_core\Debug\firebase_app.pdb'; linking object as if no debug info [D:\Technupur\G-County\build\windows\plugins\firebase_core\firebase_core_plugin.vcxproj]
firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_variant.obj) : warning LNK4099: PDB 'firebase_app.pdb' was not found with 'firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_variant.obj)' or at 'D:\Technupur\G-County\build\windows\plugins\firebase_core\Debug\firebase_app.pdb'; linking object as if no debug info [D:\Technupur\G-County\build\windows\plugins\firebase_core\firebase_core_plugin.vcxproj]
firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_variant_util.obj) : warning LNK4099: PDB 'firebase_app.pdb' was not found with 'firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_variant_util.obj)' or at 'D:\Technupur\G-County\build\windows\plugins\firebase_core\Debug\firebase_app.pdb'; linking object as if no debug info [D:\Technupur\G-County\build\windows\plugins\firebase_core\firebase_core_plugin.vcxproj]
firebase_app.lib(d3d7d08a438878e74aeb2cbaaedfc967_flatbuffers.dir_Debug_util.obj) : warning LNK4099: PDB 'flatbuffers.pdb' was not found with 'firebase_app.lib(d3d7d08a438878e74aeb2cbaaedfc967_flatbuffers.dir_Debug_util.obj)' or at 'D:\Technupur\G-County\build\windows\plugins\firebase_core\Debug\flatbuffers.pdb'; linking object as if no debug info [D:\Technupur\G-County\build\windows\plugins\firebase_core\firebase_core_plugin.vcxproj]
firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_reference_counted_future_impl.obj) : warning LNK4099: PDB 'firebase_app.pdb' was not found with 'firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_reference_counted_future_impl.obj)' or at 'D:\Technupur\G-County\build\windows\plugins\firebase_core\Debug\firebase_app.pdb'; linking object as if no debug info [D:\Technupur\G-County\build\windows\plugins\firebase_core\firebase_core_plugin.vcxproj]
firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_filesystem_desktop_windows.obj) : warning LNK4099: PDB 'firebase_app.pdb' was not found with 'firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_filesystem_desktop_windows.obj)' or at 'D:\Technupur\G-County\build\windows\plugins\firebase_core\Debug\firebase_app.pdb'; linking object as if no debug info [D:\Technupur\G-County\build\windows\plugins\firebase_core\firebase_core_plugin.vcxproj]
firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_thread_cpp11.obj) : warning LNK4099: PDB 'firebase_app.pdb' was not found with 'firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_thread_cpp11.obj)' or at 'D:\Technupur\G-County\build\windows\plugins\firebase_core\Debug\firebase_app.pdb'; linking object as if no debug info [D:\Technupur\G-County\build\windows\plugins\firebase_core\firebase_core_plugin.vcxproj]
firebase_app.lib(f6e938409d15d4e67858d89bcb981e00_zlibstatic.dir_Debug_deflate.obj) : warning LNK4099: PDB 'zlibstaticd.pdb' was not found with 'firebase_app.lib(f6e938409d15d4e67858d89bcb981e00_zlibstatic.dir_Debug_deflate.obj)' or at 'D:\Technupur\G-County\build\windows\plugins\firebase_core\Debug\zlibstaticd.pdb'; linking object as if no debug info [D:\Technupur\G-County\build\windows\plugins\firebase_core\firebase_core_plugin.vcxproj]
firebase_app.lib(f6e938409d15d4e67858d89bcb981e00_zlibstatic.dir_Debug_inflate.obj) : warning LNK4099: PDB 'zlibstaticd.pdb' was not found with 'firebase_app.lib(f6e938409d15d4e67858d89bcb981e00_zlibstatic.dir_Debug_inflate.obj)' or at 'D:\Technupur\G-County\build\windows\plugins\firebase_core\Debug\zlibstaticd.pdb'; linking object as if no debug info [D:\Technupur\G-County\build\windows\plugins\firebase_core\firebase_core_plugin.vcxproj]
firebase_app.lib(f6e938409d15d4e67858d89bcb981e00_zlibstatic.dir_Debug_crc32.obj) : warning LNK4099: PDB 'zlibstaticd.pdb' was not found with 'firebase_app.lib(f6e938409d15d4e67858d89bcb981e00_zlibstatic.dir_Debug_crc32.obj)' or at 'D:\Technupur\G-County\build\windows\plugins\firebase_core\Debug\zlibstaticd.pdb'; linking object as if no debug info [D:\Technupur\G-County\build\windows\plugins\firebase_core\firebase_core_plugin.vcxproj]
firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_gzipheader.obj) : warning LNK4099: PDB 'firebase_app.pdb' was not found with 'firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_gzipheader.obj)' or at 'D:\Technupur\G-County\build\windows\plugins\firebase_core\Debug\firebase_app.pdb'; linking object as if no debug info [D:\Technupur\G-County\build\windows\plugins\firebase_core\firebase_core_plugin.vcxproj]
firebase_app.lib(f6e938409d15d4e67858d89bcb981e00_zlibstatic.dir_Debug_adler32.obj) : warning LNK4099: PDB 'zlibstaticd.pdb' was not found with 'firebase_app.lib(f6e938409d15d4e67858d89bcb981e00_zlibstatic.dir_Debug_adler32.obj)' or at 'D:\Technupur\G-County\build\windows\plugins\firebase_core\Debug\zlibstaticd.pdb'; linking object as if no debug info [D:\Technupur\G-County\build\windows\plugins\firebase_core\firebase_core_plugin.vcxproj]
firebase_app.lib(f6e938409d15d4e67858d89bcb981e00_zlibstatic.dir_Debug_zutil.obj) : warning LNK4099: PDB 'zlibstaticd.pdb' was not found with 'firebase_app.lib(f6e938409d15d4e67858d89bcb981e00_zlibstatic.dir_Debug_zutil.obj)' or at 'D:\Technupur\G-County\build\windows\plugins\firebase_core\Debug\zlibstaticd.pdb'; linking object as if no debug info [D:\Technupur\G-County\build\windows\plugins\firebase_core\firebase_core_plugin.vcxproj]
firebase_app.lib(f6e938409d15d4e67858d89bcb981e00_zlibstatic.dir_Debug_trees.obj) : warning LNK4099: PDB 'zlibstaticd.pdb' was not found with 'firebase_app.lib(f6e938409d15d4e67858d89bcb981e00_zlibstatic.dir_Debug_trees.obj)' or at 'D:\Technupur\G-County\build\windows\plugins\firebase_core\Debug\zlibstaticd.pdb'; linking object as if no debug info [D:\Technupur\G-County\build\windows\plugins\firebase_core\firebase_core_plugin.vcxproj]
firebase_app.lib(f6e938409d15d4e67858d89bcb981e00_zlibstatic.dir_Debug_inftrees.obj) : warning LNK4099: PDB 'zlibstaticd.pdb' was not found with 'firebase_app.'; linking object as if no debug info [D:\Technupur\G-County\build\windows\plugins\firebase_core\firebase_core_plugin.vcxproj]
firebase_app.lib(f6e938409d15d4e67858d89bcb981e00_zlibstatic.dir_Debug_inffast.obj) : warning LNK4099: PDB 'zlibstaticd.pdb' was not found with 'firebase_app.lib(f6e938409d15d4e67858d89bcb981e00_zlibstatic.dir_Debug_inffast.obj)' or at 'D:\Technupur\G-County\build\windows\plugins\firebase_core\Debug\zlibstaticd.pdb'; linking object as if no debug info [D:\Technupur\G-County\build\windows\plugins\firebase_core\firebase_core_plugin.vcxproj]
firebase_app.lib(d3d7d08a438878e74aeb2cbaaedfc967_flatbuffers.dir_Debug_idl_parser.obj) : error LNK2019: unresolved external symbol __std_find_trivial_8 referenced in function "struct f_b_flatbuffers::StructDef * * __cdecl __std_find_trivial<struct f_b_flatbuffers::StructDef *,unsigned __int64>(struct f_b_flatbuffers::StructDef * *,struct f_b_flatbuffers::StructDef * *,unsigned __int64)" (??$__std_find_trivial@PEAUStructDef@f_b_flatbuffers@@_K@@YAPEAPEAUStructDef@f_b_flatbuffers@@PEAPEAU01@0_K@Z) [D:\Technupur\G-County\build\windows\plugins\firebase_core\firebase_core_plugin.vcxproj]
firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_cleanup_notifier.obj) : error LNK2001: unresolved external symbol __std_find_trivial_8 [D:\Technupur\G-County\build\windows\plugins\firebase_core\firebase_core_plugin.vcxproj]
firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_heartbeat_storage_desktop.obj) : error LNK2019: unresolved external symbol __std_find_trivial_1 referenced in function "char const * __cdecl __std_find_trivial<char const ,unsigned char>(char const *,char const *,unsigned char)" (??$__std_find_trivial@$$CBDE@@YAPEBDPEBD0E@Z) [D:\Technupur\G-County\build\windows\plugins\firebase_core\firebase_core_plugin.vcxproj]
D:\Technupur\G-County\build\windows\plugins\firebase_core\Debug\firebase_core_plugin.dll : fatal error LNK1120: 2 unresolved externals [D:\Technupur\G-County\build\windows\plugins\firebase_core\firebase_core_plugin.vcxproj]

**Comment by vivekeazework** [comment] 2023-05-31 06:39
I also found the same issue. working fine with android build

**Comment by danagbemava-nc** [comment] 2023-05-31 10:44
Closing this as a duplicate of https://github.com/firebase/flutterfire/issues/10992

**Closed by danagbemava-nc** 2023-05-31 10:44 UTC
Labels: type: bug, Needs Attention, in triage

**Comment by theprathyaksh** [comment] 2023-06-02 13:05
I too have the same issue, couldn't able to resolve

**Comment by NeSimix** [comment] 2023-06-15 11:21
same
