### ISSUE TITLE
[firebase_auth]: Windows build is broken again

### ISSUE THREAD

**Issue by cyberpwnn** [firebase/flutterfire#16813] opened 2024-12-03 00:27 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Auth

### Which platforms are affected?

Windows

### Description

C:...windows\flutter\ephemeral\cpp_client_wrapper\include\flutter\encodable_value.h(199,60): error C2665: 'std::variant<std::monostate,bool,int32_t,int64_t,double,std::string,std::vector<uint8_t,std::allocator<uint8_t>>,std::vector<int32_t,std::allocator<int>>,std::vector<int64_t,std::allocator<int64_t>>,std::vector<double,std::allocator<double>>,flutter::EncodableList,flutter::EncodableMap,flutter::CustomEncodableValue,std::vector<float,std::allocator<float>>>::variant': no overloaded function could convert all the argument types [C:...build\windows\x64\plugins\firebase_auth\firebase_auth_plugin.vcxproj]

### Reproducing the issue

Try to use firebase_auth on windows builds

### Firebase Core version

Whatever 5.3.3 depends on or latest (transitive)

### Flutter Version

3.24.5

### Relevant Log Output

```shell
C:...windows\flutter\ephemeral\cpp_client_wrapper\include\flutter\encodable_value.h(199,60): error C2665: 'std::variant<std::monostate,bool,int32_t,int64_t,double,std::string,std::vector<uint8_t,std::allocator<uint8_t>>,std::vector<int32_t,std::allocator<int>>,std::vector<int64_t,std::allocator<int64_t>>,std::vector<double,std::allocator<double>>,flutter::EncodableList,flutter::EncodableMap,flutter::CustomEncodableValue,std::vector<float,std::allocator<float>>>::variant': no overloaded function could convert all the argument types [C:...build\windows\x64\plugins\firebase_auth\firebase_auth_plugin.vcxproj]
```

### Flutter dependencies

literally firebase_auth

### Additional context and comments

C:...windows\flutter\ephemeral\cpp_client_wrapper\include\flutter\encodable_value.h(199,60): error C2665: 'std::variant<std::monostate,bool,int32_t,int64_t,double,std::string,std::vector<uint8_t,std::allocator<uint8_t>>,std::vector<int32_t,std::allocator<int>>,std::vector<int64_t,std::allocator<int64_t>>,std::vector<double,std::allocator<double>>,flutter::EncodableList,flutter::EncodableMap,flutter::CustomEncodableValue,std::vector<float,std::allocator<float>>>::variant': no overloaded function could convert all the argument types [C:...build\windows\x64\plugins\firebase_auth\firebase_auth_plugin.vcxproj]

**Comment by Boxsitter** [comment] 2024-12-03 20:17
I'm having the same issue. I have tried every troubleshooting step I can think of, no luck.

**Comment by SelaseKay** [comment] 2024-12-04 11:47
cc @russellwheatley

**Comment by StephanTLavavej** [comment] 2024-12-05 01:50
I believe this is a duplicate of: https://github.com/firebase/flutterfire/issues/16536#issuecomment-2518723562

**Comment by russellwheatley** [comment] 2024-12-05 11:02
@StephanTLavavej - thank you for the input. Closing out in favour of this issue: https://github.com/firebase/flutterfire/issues/16536

**Closed by russellwheatley** 2024-12-05 11:02 UTC
Labels: type: bug, plugin: auth, Needs Attention, platform: windows
