### ISSUE TITLE
🐛 [firebase_ui_auth] `flutter pub add` failed.

### ISSUE THREAD

**Issue by kanryu** [firebase/flutterfire#10826] opened 2023-04-21 10:13 UTC
## Bug report

**Describe the bug**
Adding firebase_ui_auth package fails.

### Steps to reproduce

```bash
$ flutter create sample
$ cd sample
$ flutter pub get
Resolving dependencies...
  material_color_utilities 0.2.0 (0.3.0 available)
  test_api 0.5.1 (0.5.2 available)
Got dependencies!
$ flutter pub add firebase_ui_auth
    Because firebase_auth >=3.6.2 <3.6.3 depends on firebase_auth_web ^4.2.2 and firebase_auth >=3.6.3 <3.6.4
      depends on firebase_auth_web ^4.2.3, firebase_auth >=3.6.2 <3.6.4 requires firebase_auth_web ^4.2.2.
    And because firebase_auth >=3.6.4 <3.7.0 depends on firebase_auth_web ^4.2.4, firebase_auth >=3.6.2 <3.7.0
      requires firebase_auth_web ^4.2.2.
    And because firebase_auth >=3.7.0 <3.8.0 depends on firebase_auth_web ^4.3.0 and firebase_auth >=3.8.0 <3.9.0
      depends on firebase_auth_web ^4.4.0, firebase_auth >=3.6.2 <3.9.0 requires firebase_auth_web ^4.2.2.
    And because firebase_auth >=3.9.0 <3.10.0 depends on firebase_auth_web ^4.4.1 and firebase_auth >=3.10.0
      <3.11.0 depends on firebase_auth_web ^4.5.0, firebase_auth >=3.6.2 <3.11.0 requires firebase_auth_web ^4.2.2.
    And because firebase_auth >=3.11.0 <3.11.2 depends on firebase_auth_web ^4.6.0 and firebase_ui_auth
      <1.0.0-dev.1 depends on firebase_auth ^3.6.2, firebase_ui_auth <1.0.0-dev.1 requires firebase_auth_web ^4.2.2 or
      firebase_auth ^3.11.2.
    And because firebase_ui_auth >=1.1.10 <1.1.11 depends on firebase_ui_localizations ^1.1.1 and firebase_ui_auth
      >=1.1.8 <1.1.10 depends on firebase_ui_localizations ^1.1.0, firebase_ui_auth <1.0.0-dev.1 or >=1.1.8 <1.1.11-∞
      requires firebase_auth_web ^4.2.2 or firebase_auth ^3.11.2 or firebase_ui_localizations ^1.1.0.
    And because firebase_ui_auth >=1.1.5 <1.1.8 depends on firebase_ui_localizations ^1.0.2 and firebase_ui_auth
      >=1.0.1 <1.1.5 depends on firebase_ui_localizations ^1.0.1, firebase_ui_auth <1.0.0-dev.1 or >=1.0.1 <1.1.11-∞
      requires firebase_auth_web ^4.2.2 or firebase_auth ^3.11.2 or firebase_ui_localizations ^1.0.1.
    And because firebase_ui_auth >=1.0.0 <1.0.1 depends on firebase_ui_localizations ^1.0.0 and firebase_ui_auth
      >=1.0.0-dev.1 <1.0.0 depends on firebase_ui_localizations ^1.0.0-dev.1, firebase_ui_auth <1.1.11 requires
      firebase_auth_web ^4.2.2 or firebase_auth ^3.11.2 or firebase_ui_localizations ^1.0.0-dev.1.
    And because firebase_ui_auth >=1.1.11 <1.2.0 depends on firebase_ui_localizations ^1.2.0 and firebase_auth
      ^3.11.2 depends on firebase_auth_web ^4.6.1, firebase_ui_auth <1.2.0 requires firebase_auth_web ^4.2.2 or
      firebase_ui_localizations ^1.0.0-dev.1.
    And because firebase_auth_web >=1.0.0 <5.2.2 depends on intl ^0.17.0 and firebase_ui_localizations
      >=1.0.0-dev.1 depends on intl ^0.17.0, firebase_ui_auth <1.2.0 requires intl ^0.17.0.
(1) So, because every version of firebase_ui_auth depends on flutter_localizations from sdk which depends on intl
      0.18.0, firebase_ui_auth <1.2.0 is forbidden.

    Because every version of flutter_localizations from sdk depends on intl 0.18.0 and firebase_ui_localizations
      >=1.0.0-dev.1 depends on intl ^0.17.0, flutter_localizations from sdk is incompatible with
      firebase_ui_localizations >=1.0.0-dev.1.
    And because firebase_ui_auth >=1.2.0 depends on firebase_ui_localizations ^1.3.0 and every version of
      firebase_ui_auth depends on flutter_localizations from sdk, firebase_ui_auth >=1.2.0 is forbidden.
    And because firebase_ui_auth <1.2.0 is forbidden (1), firebase_ui_auth is forbidden.
    So, because sample depends on firebase_ui_auth any, version solving failed.
```

### Expected behavior

Added optimal version of firebase_ui_auth
### Flutter doctor

Run `flutter doctor` and paste the output below:

```bash
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 3.10.0-3.0.pre.8, on Microsoft Windows [Version 10.0.22621.1555], locale ja-JP)
[✓] Windows Version (Installed version of Windows is version 10 or higher)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Chrome - develop for the web
[✓] Visual Studio - develop for Windows (Visual Studio Community 2022 17.5.3)
[✓] Android Studio (version 2022.1)
[✓] VS Code (version 1.77.3)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```

**Comment by danagbemava-nc** [comment] 2023-04-21 12:58
Hi @kanryu,
please check https://github.com/firebase/flutterfire/issues/10199#issuecomment-1368981937 issue comment for current workaround.

There's an open PR to upgrade intl to latest version that you can track for further updates: https://github.com/firebase/flutterfire/pull/10317

Since you are on the master channel, you can either force intl to version 0.18.0 using dependency_overrides as pointed out in https://github.com/firebase/flutterfire/issues/10199#issuecomment-1514249034 or you can switch to the stable version. 

Unfortunately, until a version of flutter stable has been published that uses intl: 0.18.0, the plugins cannot be updated. 

Closing this as a duplicate of https://github.com/firebase/flutterfire/issues/10199. 

Thank you

**Closed by danagbemava-nc** 2023-04-21 12:58 UTC
Labels: type: bug, Needs Attention, in triage
