### ISSUE TITLE
🐛 [firebase_app_check] Semantic Issue (Xcode): 'new' is unavailable

### ISSUE THREAD

**Issue by ljsharp** [firebase/flutterfire#10762] opened 2023-04-11 05:06 UTC
## Bug report

**Describe the bug**
Semantic Issue (Xcode): 'new' is unavailable
/Users/ljsharp/.pub-cache/hosted/pub.dev/firebase_app_check-0.1.2/ios/Classes/FLTAppCheckProvider.m:18:55

Semantic Issue (Xcode): 'new' is unavailable
/Users/ljsharp/.pub-cache/hosted/pub.dev/firebase_app_check-0.1.2/ios/Classes/FLTAppCheckProvider.m:22:53

Semantic Issue (Xcode): 'new' is unavailable
/Users/ljsharp/.pub-cache/hosted/pub.dev/firebase_app_check-0.1.2/ios/Classes/FLTAppCheckProvider.m:30:57

Could not build the application for the simulator.
Error launching application on iPhone 14 Pro.

### Steps to reproduce

1. Switch to ios directory and pod update
2. Install the package
3. Run the app and see the error

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.10, on macOS 13.3 22E252 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] VS Code (version 1.77.1)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
animations: ^2.0.7
  awesome_snackbar_content: ^0.1.0
  badges: ^3.0.0-beta.1
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  collection: ^1.17.0
  connectivity_plus: ^3.0.3
  cupertino_icons: ^1.0.2
  device_info_plus: ^8.0.0
  dio: ^5.1.1
  firebase_app_check: ^0.1.1+12
  firebase_auth: ^4.4.0
  firebase_core: ^2.9.0
  firebase_dynamic_links: ^5.0.14
  firebase_messaging: ^14.2.4
```

</details>

---

**Comment by danagbemava-nc** [comment] 2023-04-11 09:05
Closing this as a duplicate of https://github.com/firebase/flutterfire/issues/10694. 

Kindly upvote the original issue.

Thank you

**Closed by danagbemava-nc** 2023-04-11 09:05 UTC
Labels: type: bug, Needs Attention, in triage
