### ISSUE TITLE
[PLUGIN_NAME_HERE]: <YOUR TITLE HERE>

### ISSUE THREAD

**Issue by dackArrogant** [firebase/flutterfire#13389] opened 2024-09-24 06:08 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Description

Xcode 16.0
Could not build the precompiled application for the device.
Lexical or Preprocessor Issue (Xcode): Include of non-modular header inside framework module 'firebase_auth.FLTAuthStateChannelStreamHandler': '/Users/chunce/Desktop/春策/ccshort_better/ios/Pods/Headers/Public/Firebase/Firebase.h'
/Users/chunce/.pub-cache/hosted/pub.flutter-io.cn/firebase_auth-5.3.0/ios/Classes/Private/FLTAuthStateChannelStreamHandler.h:12:8

Lexical or Preprocessor Issue (Xcode): Include of non-modular header inside framework module 'firebase_auth.PigeonParser': '/Users/chunce/Desktop/春策/ccshort_better/ios/Pods/Headers/Public/Firebase/Firebase.h'
/Users/chunce/.pub-cache/hosted/pub.flutter-io.cn/firebase_auth-5.3.0/ios/Classes/Private/PigeonParser.h:6:8

Lexical or Preprocessor Issue (Xcode): Include of non-modular header inside framework module 'firebase_auth.FLTIdTokenChannelStreamHandler': '/Users/chunce/Desktop/春策/ccshort_better/ios/Pods/Headers/Public/Firebase/Firebase.h'
/Users/chunce/.pub-cache/hosted/pub.flutter-io.cn/firebase_auth-5.3.0/ios/Classes/Private/FLTIdTokenChannelStreamHandler.h:12:8

Lexical or Preprocessor Issue (Xcode): Include of non-modular header inside framework module 'firebase_auth.FLTPhoneNumberVerificationStreamHandler': '/Users/chunce/Desktop/春策/ccshort_better/ios/Pods/Headers/Public/Firebase/Firebase.h'
/Users/chunce/.pub-cache/hosted/pub.flutter-io.cn/firebase_auth-5.3.0/ios/Classes/Private/FLTPhoneNumberVerificationStreamHandler.h:12:8

Lexical or Preprocessor Issue (Xcode): Include of non-modular header inside framework module 'firebase_auth.FLTFirebaseAuthPlugin': '/Users/chunce/Desktop/春策/ccshort_better/ios/Pods/Headers/Public/Firebase/Firebase.h'
/Users/chunce/.pub-cache/hosted/pub.flutter-io.cn/firebase_auth-5.3.0/ios/Classes/Public/FLTFirebaseAuthPlugin.h:6:8

### Reproducing the issue

Could not build the precompiled application for the device.
Lexical or Preprocessor Issue (Xcode): Include of non-modular header inside framework module 'firebase_auth.FLTAuthStateChannelStreamHandler': '/Users/chunce/Desktop/春策/ccshort_better/ios/Pods/Headers/Public/Firebase/Firebase.h'
/Users/chunce/.pub-cache/hosted/pub.flutter-io.cn/firebase_auth-5.3.0/ios/Classes/Private/FLTAuthStateChannelStreamHandler.h:12:8

Lexical or Preprocessor Issue (Xcode): Include of non-modular header inside framework module 'firebase_auth.PigeonParser': '/Users/chunce/Desktop/春策/ccshort_better/ios/Pods/Headers/Public/Firebase/Firebase.h'
/Users/chunce/.pub-cache/hosted/pub.flutter-io.cn/firebase_auth-5.3.0/ios/Classes/Private/PigeonParser.h:6:8

Lexical or Preprocessor Issue (Xcode): Include of non-modular header inside framework module 'firebase_auth.FLTIdTokenChannelStreamHandler': '/Users/chunce/Desktop/春策/ccshort_better/ios/Pods/Headers/Public/Firebase/Firebase.h'
/Users/chunce/.pub-cache/hosted/pub.flutter-io.cn/firebase_auth-5.3.0/ios/Classes/Private/FLTIdTokenChannelStreamHandler.h:12:8

Lexical or Preprocessor Issue (Xcode): Include of non-modular header inside framework module 'firebase_auth.FLTPhoneNumberVerificationStreamHandler': '/Users/chunce/Desktop/春策/ccshort_better/ios/Pods/Headers/Public/Firebase/Firebase.h'
/Users/chunce/.pub-cache/hosted/pub.flutter-io.cn/firebase_auth-5.3.0/ios/Classes/Private/FLTPhoneNumberVerificationStreamHandler.h:12:8

Lexical or Preprocessor Issue (Xcode): Include of non-modular header inside framework module 'firebase_auth.FLTFirebaseAuthPlugin': '/Users/chunce/Desktop/春策/ccshort_better/ios/Pods/Headers/Public/Firebase/Firebase.h'
/Users/chunce/.pub-cache/hosted/pub.flutter-io.cn/firebase_auth-5.3.0/ios/Classes/Public/FLTFirebaseAuthPlugin.h:6:8

### Firebase Core version

3.5.0

### Flutter Version

3.5.1

### Relevant Log Output

```shell
Could not build the precompiled application for the device.
Lexical or Preprocessor Issue (Xcode): Include of non-modular header inside framework module 'firebase_auth.FLTAuthStateChannelStreamHandler': '/Users/chunce/Desktop/春策/ccshort_better/ios/Pods/Headers/Public/Firebase/Firebase.h'
/Users/chunce/.pub-cache/hosted/pub.flutter-io.cn/firebase_auth-5.3.0/ios/Classes/Private/FLTAuthStateChannelStreamHandler.h:12:8

Lexical or Preprocessor Issue (Xcode): Include of non-modular header inside framework module 'firebase_auth.PigeonParser': '/Users/chunce/Desktop/春策/ccshort_better/ios/Pods/Headers/Public/Firebase/Firebase.h'
/Users/chunce/.pub-cache/hosted/pub.flutter-io.cn/firebase_auth-5.3.0/ios/Classes/Private/PigeonParser.h:6:8

Lexical or Preprocessor Issue (Xcode): Include of non-modular header inside framework module 'firebase_auth.FLTIdTokenChannelStreamHandler': '/Users/chunce/Desktop/春策/ccshort_better/ios/Pods/Headers/Public/Firebase/Firebase.h'
/Users/chunce/.pub-cache/hosted/pub.flutter-io.cn/firebase_auth-5.3.0/ios/Classes/Private/FLTIdTokenChannelStreamHandler.h:12:8

Lexical or Preprocessor Issue (Xcode): Include of non-modular header inside framework module 'firebase_auth.FLTPhoneNumberVerificationStreamHandler': '/Users/chunce/Desktop/春策/ccshort_better/ios/Pods/Headers/Public/Firebase/Firebase.h'
/Users/chunce/.pub-cache/hosted/pub.flutter-io.cn/firebase_auth-5.3.0/ios/Classes/Private/FLTPhoneNumberVerificationStreamHandler.h:12:8

Lexical or Preprocessor Issue (Xcode): Include of non-modular header inside framework module 'firebase_auth.FLTFirebaseAuthPlugin': '/Users/chunce/Desktop/春策/ccshort_better/ios/Pods/Headers/Public/Firebase/Firebase.h'
/Users/chunce/.pub-cache/hosted/pub.flutter-io.cn/firebase_auth-5.3.0/ios/Classes/Public/FLTFirebaseAuthPlugin.h:6:8
```

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Replace this line with the contents of your `flutter pub deps -- --style=compact`.

```

</details>

### Additional context and comments

Could not build the precompiled application for the device.
Lexical or Preprocessor Issue (Xcode): Include of non-modular header inside framework module 'firebase_auth.FLTAuthStateChannelStreamHandler': '/Users/chunce/Desktop/春策/ccshort_better/ios/Pods/Headers/Public/Firebase/Firebase.h'
/Users/chunce/.pub-cache/hosted/pub.flutter-io.cn/firebase_auth-5.3.0/ios/Classes/Private/FLTAuthStateChannelStreamHandler.h:12:8

Lexical or Preprocessor Issue (Xcode): Include of non-modular header inside framework module 'firebase_auth.PigeonParser': '/Users/chunce/Desktop/春策/ccshort_better/ios/Pods/Headers/Public/Firebase/Firebase.h'
/Users/chunce/.pub-cache/hosted/pub.flutter-io.cn/firebase_auth-5.3.0/ios/Classes/Private/PigeonParser.h:6:8

Lexical or Preprocessor Issue (Xcode): Include of non-modular header inside framework module 'firebase_auth.FLTIdTokenChannelStreamHandler': '/Users/chunce/Desktop/春策/ccshort_better/ios/Pods/Headers/Public/Firebase/Firebase.h'
/Users/chunce/.pub-cache/hosted/pub.flutter-io.cn/firebase_auth-5.3.0/ios/Classes/Private/FLTIdTokenChannelStreamHandler.h:12:8

Lexical or Preprocessor Issue (Xcode): Include of non-modular header inside framework module 'firebase_auth.FLTPhoneNumberVerificationStreamHandler': '/Users/chunce/Desktop/春策/ccshort_better/ios/Pods/Headers/Public/Firebase/Firebase.h'
/Users/chunce/.pub-cache/hosted/pub.flutter-io.cn/firebase_auth-5.3.0/ios/Classes/Private/FLTPhoneNumberVerificationStreamHandler.h:12:8

Lexical or Preprocessor Issue (Xcode): Include of non-modular header inside framework module 'firebase_auth.FLTFirebaseAuthPlugin': '/Users/chunce/Desktop/春策/ccshort_better/ios/Pods/Headers/Public/Firebase/Firebase.h'
/Users/chunce/.pub-cache/hosted/pub.flutter-io.cn/firebase_auth-5.3.0/ios/Classes/Public/FLTFirebaseAuthPlugin.h:6:8

**Comment by SelaseKay** [comment] 2024-09-24 08:42
Duplicate of: [13323](https://github.com/firebase/flutterfire/issues/13323)

**Closed by SelaseKay** 2024-09-24 08:42 UTC
Labels: type: bug, Needs Attention
