### ISSUE TITLE
🐛 [FLUTTERFIRE_UI]  Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null

### ISSUE THREAD

**Issue by thisisyusub** [firebase/flutterfire#8793] opened 2022-05-28 20:42 UTC
## Bug report

**Describe the bug**
With Flutter 3.0, no need to check null safety in Bindings. Please remove it.

### Steps to reproduce
Just configure new firebase app with Flutter 3.0

**Comment by darshankawar** [comment] 2022-05-30 11:23
Closing as duplicate of https://github.com/firebase/flutterfire/issues/8784

**Closed by darshankawar** 2022-05-30 11:23 UTC
Labels: type: bug, Needs Attention, in triage
