### ISSUE TITLE
🐛 [firebase_analytics] How to disable firebase_analytics from getting android_id?

### ISSUE THREAD

**Issue by lizhuoyuan** [firebase/flutterfire#9606] opened 2022-09-23 07:45 UTC
I want to get the android_id only after the user agrees, or not.
Now detected "com.google.firebase.crashlytics.internal.common" gets android_id, what should I do?

**Comment by darshankawar** [comment] 2022-09-23 11:08
@lizhuoyuan 
I think your question is better suited for support channels like StackOverflow, where, a Firebaser can probably give you a solution.
Closing from here, as this is more of a `how to` question and not a bug or feature request.

**Closed by darshankawar** 2022-09-23 11:08 UTC
Labels: type: bug, Needs Attention, in triage

**Comment by lizhuoyuan** [comment] 2022-10-09 03:35
https://github.com/firebase/firebase-android-sdk/issues/3826

**Comment by lizhuoyuan** [comment] 2022-10-09 03:37
hey , I found https://github.com/firebase/firebase-android-sdk/pull/3840
But the flutter version of android is a dependent  "classpath 'com.google.firebase:firebase-crashlytics-gradle:2.9.2'", otherwise it will prompt an error, how can I ensure that the flutter version can use the updated code
