### ISSUE TITLE
Flutter IOS getInitialMessage return null

### ISSUE THREAD

**Issue by volkanustekidag** [firebase/flutterfire#11562] opened 2023-09-07 14:15 UTC
I am running FCM transactions in my Flutter application. All of these processes run on android. In iOS, messages are received and forwarded while the application is in the background or running. However, if the application is closed on my iOS device, clicking on the notification does not perform the expected redirection. here are my codes:

```
  @override
  void initState() {
    // TODO: implement initState
    super.initState();
    initFirebaseNotification();

    WidgetsBinding.instance.addPostFrameCallback((_) async {
      Future.delayed(const Duration(seconds: 2), () {
        setupInitialMessage();
      });
    });
  }

  Future<void> setupInitialMessage() async {
    RemoteMessage? remoteMessage =
        await FirebaseMessaging.instance.getInitialMessage();

    if (remoteMessage != null) {
      AppRouting.notificationPushRouting(remoteMessage.data);
    }
  }

```
AppDelegate:
```
import UIKit
import Flutter
import Firebase
import FirebaseMessaging

@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
    override func application(
        _ application: UIApplication,
        didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
    ) -> Bool {
        FirebaseApp.configure() // Firebase'i başlatın
        GeneratedPluginRegistrant.register(with: self)
        return super.application(application, didFinishLaunchingWithOptions: launchOptions)
    }

    override func applicationDidBecomeActive(_ application: UIApplication) {
        application.applicationIconBadgeNumber = 0
    }

    override func application(
        _ application: UIApplication,
        didReceiveRemoteNotification userInfo: [AnyHashable: Any],
        fetchCompletionHandler completionHandler: @escaping (UIBackgroundFetchResult) -> Void
    ) {
        if let messageInfo = userInfo as? [String: Any] {
            Messaging.messaging().appDidReceiveMessage(messageInfo) 
        }
        completionHandler(.newData)
    }
}
```

### Flutter doctor

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.2, on macOS 13.4 22F66 darwin-arm64, locale en-TR)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.81.1)
[✓] Connected device (4 available)
[✓] Network resources

• No issues found!

**Comment by danagbemava-nc** [comment] 2023-09-08 11:01
Closing this as a duplicate of https://github.com/firebase/flutterfire/issues/11465

**Closed** 2023-09-08 11:02 UTC
Labels: type: bug, resolution: duplicate
