### ISSUE TITLE
[firebase_auth] Apple Sign In: invalid-credential error triggered by using a recently updated credential obtained from FirebaseAuthException(credential-already-in-use) exception during the signInWithCredential operation.

### ISSUE THREAD

**Issue by BogsBalangat** [firebase/flutterfire#11877] opened 2023-11-13 08:54 UTC
## Bug report

**Describe the bug**
I am getting the error "The supplied auth credential is malformed, has expired error" after I use the credential from the FirebaseAuthException(credential-already-in-use) to signInWithCredential for apple sign in.

### Steps to reproduce

Try this simple Firebase Auth Code:

```
try {
      await FirebaseAuth.instance.currentUser!
          .linkWithProvider(AppleAuthProvider());
    } on FirebaseAuthException catch (linkException) {
      if (linkException.code == 'credential-already-in-use') {
        ///This new credential comes from
        ///error.userInfo.AuthErrorUserInfoUpdatedCredentialKey
        final newCredential = linkException.credential!;
        try {
          await FirebaseAuth.instance.signInWithCredential(newCredential);
        } on FirebaseAuthException catch (signInException) {
          ///signInException here has firebase_auth/invalid-credential code
          ///and error message is
          ///The supplied auth credentialis malformed, has expired...
        }
      }
    }
```

### Expected behavior

The authentication flow here should be able to recover and allow signInWithCredential and not throw invalid-credentials exception.

### Flutter dependencies

firebase_core: 2.22.0
firebase_auth: 4.13.0

</details>

---

**Comment by PetrKubes97** [comment] 2023-11-13 12:46
I'm experiencing the same issue.

**Comment by danagbemava-nc** [comment] 2023-11-14 10:33
Closing this as a duplicate of https://github.com/firebase/flutterfire/issues/11841

**Closed by danagbemava-nc** 2023-11-14 10:33 UTC
Labels: type: bug, Needs Attention, in triage
