### ISSUE TITLE
[firebase_auth] error.credential is always null

### ISSUE THREAD

**Issue by SteadyAction** [firebase/flutterfire#11448] opened 2023-08-11 02:12 UTC
## Bug report

**Describe the bug**
```
  catch (error) {
      if (error is FirebaseAuthException && error.code == 'email-already-in-use') {
        await auth.signInWithCredential(error.credential!); // error.credential is now always null
      }
```

### Steps to reproduce
```
try {
    await user.linkWithCredential(credential);
} on FirebaseAuthException catch (e) {
     if (e.code == "credential-already-in-use") {
         // e.crediential is null here
    }
}
```
### Expected behavior

a new credential should not be `null` in the error by`error.credential`

This is a very critical issue....

**Comment by darshankawar** [comment] 2023-08-11 10:22
@SteadyAction 
Closing this as a duplicate of https://github.com/firebase/flutterfire/issues/11164. The original issue is assigned so you may subscribe to the issue for further updates.

**Closed by darshankawar** 2023-08-11 10:22 UTC
Labels: type: bug, Needs Attention, in triage
