### ISSUE TITLE
🐛 [firebase_auth] Potential race condition in `User.isAnonymous`

### ISSUE THREAD

**Issue by Pante** [firebase/flutterfire#11873] opened 2023-11-12 03:43 UTC
## Bug report

**Describe the bug**
On iOS, after linking an email address to an anonymous account, the `User` emitted by `FirebaseAuth.userChanges()` is in an invalid state. Specifically, `User.isAnonymous` is true while `User.email` is not null. Furthermore, only a single `User` is emitted from `FirebaseAuth.userChanges()`. Manually rebuilding the page seems to cause `User.isAnonymous` to flip to false. 

This leads me to assume there is a potential race condition where the `User` is emitted before the linking is fully processed.

### Expected behavior

`User.isAnonymous` should be false while `User.email` is not null.

### Sample project

```dart
class Foo extends StatelessWidget {
  final FirebaseAuth firebase;

  Foo(this.firebase);

  @override
  Widget build(BuildContext context) => Column(
    children: [
      StreamBuilder(
        stream: firebase.userChanges(),
        builder: (context, snapshot) => Text('email: ${snapshot.data?.email}, anonymous: ${snapshot.data?.isAnonymous}'),
      ),
      FloatingButton(
        content: const Text('Link'),
        onPressed: () async {
          final credential = EmailAuthProvider.credential(email: 'myEmail@email.com', password: 'myPassword');
          await firebase.currentUser?.linkWithCredential(credential);
        },
      ),
    ],
  );
}
```

---

## Additional context

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[!] Flutter (Channel stable, 3.13.9, on macOS 14.0 23A344 darwin-arm64, locale en-SG)
    • Flutter version 3.13.9 on channel stable at /Users/matthias/Documents/flutter
    ! Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart/3.1.5/libexec/bin/dart, which is not inside your current Flutter SDK checkout at
      /Users/matthias/Documents/flutter. Consider adding /Users/matthias/Documents/flutter/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d211f42860 (2 weeks ago), 2023-10-25 13:42:25 -0700
    • Engine revision 0545f8705d
    • Dart version 3.1.5
    • DevTools version 2.25.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/matthias/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Users/matthias/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.14.2

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 2022.3)
    • Android Studio at /Users/matthias/Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] IntelliJ IDEA Ultimate Edition (version 2023.2.5)
    • IntelliJ at /Users/matthias/Applications/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 76.3.4
    • Dart plugin version 232.10072.19

[✓] Connected device (2 available)
    • Overpriced Phone (mobile) • 00008030-0009195E1E41802E • ios          • iOS 17.0.3 21A360
    • macOS (desktop)           • macos                     • darwin-arm64 • macOS 14.0 23A344 darwin-arm64

[✓] Network resources
    • All expected network resources are available.
```

</details>

---

### Flutter dependencies

I cut out the irrelevant portions, please let me know if the full output is required. 

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
- firebase_analytics 10.5.1 [firebase_analytics_platform_interface firebase_analytics_web firebase_core firebase_core_platform_interface flutter]
- firebase_analytics_platform_interface 3.7.1 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_analytics_web 0.5.5+1 [_flutterfire_internals firebase_analytics_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- firebase_auth_platform_interface 6.19.1 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 5.8.2 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser js meta]
- firebase_core 2.17.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_core_platform_interface 4.8.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.8.0 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_remote_config 4.2.7 [firebase_core firebase_core_platform_interface firebase_remote_config_platform_interface firebase_remote_config_web flutter]
- firebase_remote_config_platform_interface 1.4.7 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_remote_config_web 1.4.7 [firebase_core firebase_core_web firebase_remote_config_platform_interface flutter flutter_web_plugins js]

```

</details>

---

**Comment by danagbemava-nc** [comment] 2023-11-13 11:20
Hi @Pante, this is a duplicate of https://github.com/firebase/flutterfire/issues/11520. 

Kindly subscribe to the original issue for updates. 

Closing from here. 

Thank you

**Closed by danagbemava-nc** 2023-11-13 11:20 UTC
Labels: type: bug, Needs Attention, in triage
