### ISSUE TITLE
🐛 [firebase_performance] Cannot resolve version on Android

### ISSUE THREAD

**Issue by hnvn** [firebase/flutterfire#11399] opened 2023-07-31 10:55 UTC
## Bug report

**Describe the bug**
Cannot build android project after upgrading the plugin to the latest version (0.9.2+4)

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDevDebugAarMetadata'.
> Could not resolve all files for configuration ':app:devDebugRuntimeClasspath'.
   > Could not find any version that matches com.google.firebase:firebase-sessions:[15.0.0, 16.0.0).
     Versions that do not match: 1.0.0
     Required by:
         project :app > project :firebase_performance > com.google.firebase:firebase-perf:20.4.0
```
---

### Flutter doctor

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.6, on macOS 13.4.1 22F770820d darwin-arm64, locale en-VN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.80.2)
[✓] Connected device (4 available)
[✓] Network resources
```

</details>

---

### Flutter dependencies

<details><summary>Click To Expand</summary>

```
dependencies:
- android_intent_plus 4.0.1 [flutter platform meta]
- android_path_provider 0.3.0 [flutter]
- another_transformer_page_view 2.0.1 [flutter]
- app_settings 5.0.0 [flutter plugin_platform_interface]
- async_wallpaper 2.0.3 [flutter fluttertoast]
- auto_route 7.7.1 [flutter path collection meta]
- auto_size_text 3.0.0 [flutter]
- babylonjs_viewer 1.1.4 [flutter webview_flutter]
- cached_network_image 3.2.3 [flutter flutter_cache_manager octo_image cached_network_image_platform_interface cached_network_image_web]
- chewie 1.7.0 [cupertino_icons flutter provider video_player wakelock_plus]
- cloud_firestore 4.8.4 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_interface flutter meta]
- connectivity_plus 4.0.1 [flutter flutter_web_plugins connectivity_plus_platform_interface js meta nm]
- country_code_picker 2.0.2 [flutter flutter_localizations modal_bottom_sheet universal_platform]
- cupertino_icons 1.0.5
- device_info_plus 9.0.2 [device_info_plus_platform_interface ffi file flutter flutter_web_plugins meta win32 win32_registry]
- diacritic 0.1.4
- dio 5.3.0 [async http_parser meta path]
- dotted_border 2.0.0+3 [flutter path_drawing]
- drift 1.7.1 [async convert collection js meta stream_channel sqlite3]
- file_picker 5.3.2 [flutter flutter_web_plugins flutter_plugin_android_lifecycle plugin_platform_interface ffi path win32]
- firebase_analytics 10.4.4 [firebase_analytics_platform_interface firebase_analytics_web firebase_core firebase_core_platform_interface flutter]
- firebase_app_check 0.1.5+1 [firebase_app_check_platform_interface firebase_app_check_web firebase_core firebase_core_platform_interface flutter]
- firebase_auth 4.7.2 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 2.15.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_dynamic_links 5.3.4 [firebase_core firebase_core_platform_interface firebase_dynamic_links_platform_interface flutter meta plugin_platform_interface]
- firebase_performance 0.9.2+4 [firebase_core firebase_core_platform_interface firebase_performance_platform_interface firebase_performance_web flutter]
- firebase_remote_config 4.2.4 [firebase_core firebase_core_platform_interface firebase_remote_config_platform_interface firebase_remote_config_web flutter]
- firebase_storage 11.2.5 [firebase_core firebase_core_platform_interface firebase_storage_platform_interface firebase_storage_web flutter]
- fl_chart 0.63.0 [equatable flutter]
- flutter 0.0.0 [characters collection js material_color_utilities meta vector_math sky_engine]
- flutter_downloader 1.10.4 [flutter]
- flutter_html 3.0.0-beta.2 [html csslib collection list_counter flutter]
- flutter_image_compress 2.0.3 [flutter flutter_image_compress_platform_interface flutter_image_compress_common flutter_image_compress_web]
- flutter_image_slideshow 0.1.4 [flutter]
- flutter_libphonenumber 2.1.4 [flutter flutter_libphonenumber_android flutter_libphonenumber_ios flutter_libphonenumber_platform_interface flutter_libphonenumber_web]
- flutter_localizations 0.0.0 [flutter intl characters clock collection js material_color_utilities meta path vector_math]
- flutter_markdown 0.6.17 [flutter markdown meta path]
- flutter_riverpod 2.3.6 [collection flutter meta riverpod state_notifier]
- flutter_slidable 3.0.0 [flutter]
- flutter_spinkit 5.2.0 [flutter]
- flutter_svg 2.0.7 [flutter vector_graphics vector_graphics_codec vector_graphics_compiler]
- freezed_annotation 2.4.1 [collection json_annotation meta]
- geolocator 9.0.2 [flutter geolocator_platform_interface geolocator_android geolocator_apple geolocator_web geolocator_windows]
- google_maps_flutter 2.3.1 [flutter google_maps_flutter_android google_maps_flutter_ios google_maps_flutter_platform_interface google_maps_flutter_web]
- google_place 0.4.7 [http]
- graphql 5.2.0-beta.5 [meta path gql gql_exec gql_link gql_http_link gql_transform_link gql_error_link gql_dedupe_link hive normalize http collection web_socket_channel stream_channel rxdart uuid]
- http 1.1.0 [async http_parser meta]
- image_cropper 5.0.0 [flutter image_cropper_platform_interface image_cropper_for_web]
- image_picker 1.0.1 [flutter image_picker_android image_picker_for_web image_picker_ios image_picker_linux image_picker_macos image_picker_platform_interface image_picker_windows]
- intl 0.18.1 [clock meta path]
- ionicons 0.2.2 [flutter]
- json_annotation 4.8.1 [meta]
- just_audio 0.9.34 [just_audio_platform_interface just_audio_web audio_session rxdart path path_provider async uuid crypto meta flutter]
- just_the_tooltip 0.0.12 [flutter]
- jwt_decoder 2.0.1
- lottie 2.4.0 [archive flutter path vector_math]
- marquee 2.2.3 [fading_edge_scrollview flutter]
- mobile_scanner 3.3.0 [flutter flutter_web_plugins js]
- oktoast 3.3.1 [flutter]
- onesignal_flutter 3.5.1 [flutter]
- open_mail_app 0.4.5 [platform url_launcher flutter]
- package_info_plus 4.0.2 [ffi flutter flutter_web_plugins http meta path package_info_plus_platform_interface win32]
- password_strength 0.2.0
- path 1.8.3
- path_provider 2.0.15 [flutter path_provider_android path_provider_foundation path_provider_linux path_provider_platform_interface path_provider_windows]
- percent_indicator 4.2.3 [flutter]
- permission_handler 10.4.2 [flutter meta permission_handler_android permission_handler_apple permission_handler_windows permission_handler_platform_interface]
- photo_view 0.14.0 [flutter]
- pin_code_fields 8.0.1 [flutter]
- pretty_dio_logger 1.3.1 [dio]
- pretty_print_json 1.0.1
- qr_flutter 4.1.0 [flutter qr]
- responsive_framework 1.1.0 [flutter collection]
- retrofit 4.0.1 [dio meta]
- rxdart 0.27.7
- screen_brightness 0.2.2 [flutter screen_brightness_platform_interface screen_brightness_android screen_brightness_ios screen_brightness_macos screen_brightness_windows]
- sensors_plus 3.0.2 [flutter flutter_web_plugins sensors_plus_platform_interface]
- sentry_flutter 7.8.0 [flutter flutter_web_plugins sentry package_info_plus meta]
- share_plus 3.0.4 [meta mime flutter share_plus_platform_interface share_plus_linux share_plus_macos share_plus_windows share_plus_web]
- shared_preferences 2.2.0 [flutter shared_preferences_android shared_preferences_foundation shared_preferences_linux shared_preferences_platform_interface shared_preferences_web shared_preferences_windows]
- shimmer 2.0.0 [flutter]
- sms_autofill 2.3.0 [pin_input_text_field flutter]
- social_share 2.3.1 [flutter path_provider]
- sqlite3_flutter_libs 0.5.15 [flutter]
- tab_indicator_styler 2.0.0 [flutter]
- timeago 3.5.0 [intl]
- url_launcher 6.1.12 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- webview_flutter 4.2.2 [flutter webview_flutter_android webview_flutter_platform_interface webview_flutter_wkwebview]
- youtube_player_iframe 4.0.4 [flutter meta webview_flutter webview_flutter_android webview_flutter_wkwebview url_launcher youtube_player_iframe_web]

dev dependencies:
- auto_route_generator 7.2.0 [build source_gen analyzer path build_runner code_builder dart_style xml args glob auto_route]
- build_runner 2.4.6 [analyzer args async build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style frontend_server_client glob graphs http_multi_server io js logging meta mime package_config path pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web_socket_channel yaml]
- drift_dev 1.7.1 [charcode collection recase meta path json_annotation stream_transform args logging cli_util yaml io drift sqlite3 sqlparser analyzer analyzer_plugin source_span package_config pub_semver build build_resolvers build_config dart_style source_gen]
- flutter_native_splash 2.3.1 [args flutter flutter_web_plugins js html image meta path universal_io xml yaml]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters collection js matcher material_color_utilities meta source_span stream_channel string_scanner term_glyph]
- freezed 2.4.0 [analyzer build build_config collection meta source_gen freezed_annotation json_annotation]
- json_serializable 6.7.1 [analyzer async build build_config collection json_annotation meta path pub_semver pubspec_parse source_gen source_helper]
- retrofit_generator 6.0.0+3 [analyzer build built_collection code_builder dart_style dio retrofit source_gen tuple]

dependency overrides:
- analyzer 5.13.0 [_fe_analyzer_shared collection convert crypto glob meta package_config path pub_semver source_span watcher yaml]
- flutter_lints 2.0.2 [lints]
- flutter_math_fork 0.7.1 [flutter flutter_svg provider meta collection tuple]
- flutter_svg 2.0.7 [flutter vector_graphics vector_graphics_codec vector_graphics_compiler]
- intl 0.18.1 [clock meta path]
- path 1.8.3
- provider 6.0.5 [collection flutter nested]
- video_player 2.7.0 [flutter html video_player_android video_player_avfoundation video_player_platform_interface video_player_web]

transitive dependencies:
- _fe_analyzer_shared 61.0.0 [meta]
- _flutterfire_internals 1.3.4 [collection firebase_core firebase_core_platform_interface flutter meta]
- analyzer_plugin 0.11.2 [analyzer collection dart_style pub_semver yaml]
- archive 3.3.7 [crypto path pointycastle]
- args 2.4.2
- async 2.11.0 [collection meta]
- audio_session 0.1.16 [flutter flutter_web_plugins rxdart meta]
- boolean_selector 2.1.1 [source_span string_scanner]
- build 2.4.1 [analyzer async convert crypto glob logging meta package_config path]
- build_config 1.1.1 [checked_yaml json_annotation path pubspec_parse yaml]
- build_daemon 4.0.0 [built_collection built_value http_multi_server logging path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 2.2.1 [analyzer async build collection crypto graphs logging package_config path pool pub_semver stream_transform yaml]
- build_runner_core 7.2.10 [async build build_config build_resolvers collection convert crypto glob graphs json_annotation logging meta package_config path pool timing watcher yaml]
- built_collection 5.1.1
- built_value 8.6.1 [built_collection collection fixnum meta]
- cached_network_image_platform_interface 2.0.0 [flutter flutter_cache_manager]
- cached_network_image_web 1.0.2 [flutter flutter_cache_manager cached_network_image_platform_interface]
- characters 1.3.0
- charcode 1.3.1
- checked_yaml 2.0.3 [json_annotation source_span yaml]
- cli_util 0.3.5 [meta path]
- clock 1.1.1
- cloud_firestore_platform_interface 5.15.3 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 3.6.3 [_flutterfire_internals cloud_firestore_platform_interface collection firebase_core firebase_core_web flutter flutter_web_plugins js]
- code_builder 4.5.0 [built_collection built_value collection matcher meta]
- collection 1.17.1
- connectivity_plus_platform_interface 1.2.4 [flutter meta plugin_platform_interface]
- convert 3.1.1 [typed_data]
- cross_file 0.3.3+4 [js meta]
- crypto 3.0.3 [typed_data]
- csslib 0.17.3 [source_span]
- dart_style 2.3.2 [analyzer args path pub_semver source_span]
- dbus 0.7.8 [args ffi meta xml]
- device_info_plus_platform_interface 7.0.0 [flutter meta plugin_platform_interface]
- equatable 2.0.5 [collection meta]
- fading_edge_scrollview 3.0.0 [flutter]
- fake_async 1.3.1 [clock collection]
- ffi 2.0.2
- file 6.1.4 [meta path]
- file_selector_linux 0.9.2 [cross_file file_selector_platform_interface flutter]
- file_selector_macos 0.9.3 [cross_file file_selector_platform_interface flutter]
- file_selector_platform_interface 2.6.0 [cross_file flutter http plugin_platform_interface]
- file_selector_windows 0.9.3 [cross_file file_selector_platform_interface flutter]
- firebase_analytics_platform_interface 3.6.4 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_analytics_web 0.5.4+4 [_flutterfire_internals firebase_analytics_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- firebase_app_check_platform_interface 0.0.9+1 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_app_check_web 0.0.11+1 [_flutterfire_internals firebase_app_check_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- firebase_auth_platform_interface 6.16.1 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 5.6.2 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser js meta]
- firebase_core_platform_interface 4.8.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.6.0 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_dynamic_links_platform_interface 0.2.6+4 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_performance_platform_interface 0.1.4+4 [_flutterfire_internals firebase_core flutter plugin_platform_interface]
- firebase_performance_web 0.1.4+4 [_flutterfire_internals firebase_core firebase_core_web firebase_performance_platform_interface flutter flutter_web_plugins js]
- firebase_remote_config_platform_interface 1.4.4 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_remote_config_web 1.4.4 [firebase_core firebase_core_web firebase_remote_config_platform_interface flutter flutter_web_plugins js]
- firebase_storage_platform_interface 4.4.4 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_storage_web 3.6.5 [_flutterfire_internals async firebase_core firebase_core_web firebase_storage_platform_interface flutter flutter_web_plugins http js meta]
- fixnum 1.1.0
- flutter_blurhash 0.7.0 [flutter]
- flutter_cache_manager 3.3.1 [clock collection file flutter http path path_provider rxdart sqflite uuid]
- flutter_image_compress_common 1.0.1 [flutter flutter_image_compress_platform_interface]
- flutter_image_compress_platform_interface 1.0.1 [flutter plugin_platform_interface cross_file]
- flutter_image_compress_web 0.1.3 [flutter flutter_web_plugins flutter_image_compress_platform_interface js]
- flutter_libphonenumber_android 1.0.1 [flutter flutter_libphonenumber_platform_interface]
- flutter_libphonenumber_ios 1.1.3 [flutter flutter_libphonenumber_platform_interface]
- flutter_libphonenumber_platform_interface 1.0.0 [flutter plugin_platform_interface]
- flutter_libphonenumber_web 1.0.0 [flutter flutter_web_plugins flutter_libphonenumber_platform_interface js]
- flutter_plugin_android_lifecycle 2.0.15 [flutter]
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta vector_math]
- fluttertoast 8.2.2 [flutter flutter_web_plugins]
- frontend_server_client 3.2.0 [async path]
- geolocator_android 4.2.0 [flutter geolocator_platform_interface uuid]
- geolocator_apple 2.2.7 [flutter geolocator_platform_interface]
- geolocator_platform_interface 4.0.7 [flutter plugin_platform_interface vector_math meta]
- geolocator_web 2.1.6 [flutter flutter_web_plugins geolocator_platform_interface]
- geolocator_windows 0.1.1 [flutter geolocator_platform_interface]
- glob 2.1.2 [async collection file path string_scanner]
- google_maps 6.3.0 [js js_wrapping meta]
- google_maps_flutter_android 2.4.15 [flutter flutter_plugin_android_lifecycle google_maps_flutter_platform_interface stream_transform]
- google_maps_flutter_ios 2.2.3 [flutter google_maps_flutter_platform_interface stream_transform]
- google_maps_flutter_platform_interface 2.2.7 [collection flutter plugin_platform_interface stream_transform]
- google_maps_flutter_web 0.5.1 [flutter flutter_web_plugins google_maps google_maps_flutter_platform_interface sanitize_html stream_transform]
- gql 1.0.1-alpha+1686240655988 [collection meta source_span yaml]
- gql_dedupe_link 2.0.4-alpha+1686240656097 [async gql_exec gql_link meta]
- gql_error_link 1.0.0 [async gql_exec gql_link meta]
- gql_exec 1.0.1-alpha+1686240655996 [collection gql meta]
- gql_http_link 1.0.1 [gql gql_exec gql_link http http_parser meta]
- gql_link 1.0.1-alpha+1686240656001 [gql gql_exec meta]
- gql_transform_link 1.0.0 [gql_exec gql_link]
- graphs 2.3.1 [collection]
- hive 2.2.3 [meta crypto]
- html 0.15.4 [csslib source_span]
- http_multi_server 3.2.1 [async]
- http_parser 4.0.2 [collection source_span string_scanner typed_data]
- image 4.0.17 [archive meta xml]
- image_cropper_for_web 3.0.0 [flutter flutter_web_plugins image_cropper_platform_interface js]
- image_cropper_platform_interface 5.0.0 [flutter plugin_platform_interface http]
- image_picker_android 0.8.7+3 [flutter flutter_plugin_android_lifecycle image_picker_platform_interface]
- image_picker_for_web 2.2.0 [flutter flutter_web_plugins image_picker_platform_interface mime]
- image_picker_ios 0.8.8 [flutter image_picker_platform_interface]
- image_picker_linux 0.2.1 [file_selector_linux file_selector_platform_interface flutter image_picker_platform_interface]
- image_picker_macos 0.2.1 [file_selector_macos file_selector_platform_interface flutter image_picker_platform_interface]
- image_picker_platform_interface 2.8.0 [cross_file flutter http plugin_platform_interface]
- image_picker_windows 0.2.1 [file_selector_platform_interface file_selector_windows flutter image_picker_platform_interface]
- io 1.0.4 [meta path string_scanner]
- js 0.6.7 [meta]
- js_wrapping 0.7.4 [js]
- just_audio_platform_interface 4.2.1 [flutter plugin_platform_interface]
- just_audio_web 0.4.8 [just_audio_platform_interface flutter flutter_web_plugins]
- lints 2.1.1
- list_counter 1.0.2
- logging 1.2.0
- markdown 7.1.0 [args meta]
- matcher 0.12.15 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.2.0
- meta 1.9.1
- mime 1.0.4
- modal_bottom_sheet 3.0.0-pre [flutter]
- nested 1.0.0 [flutter]
- nm 0.5.0 [dbus]
- normalize 0.8.2+1 [gql collection]
- octo_image 1.0.2 [flutter flutter_blurhash]
- package_config 2.1.0 [path]
- package_info_plus_platform_interface 2.0.1 [flutter meta plugin_platform_interface]
- path_drawing 1.0.1 [vector_math meta path_parsing flutter]
- path_parsing 1.0.1 [vector_math meta]
- path_provider_android 2.0.27 [flutter path_provider_platform_interface]
- path_provider_foundation 2.2.3 [flutter path_provider_platform_interface]
- path_provider_linux 2.1.11 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_platform_interface 2.0.6 [flutter platform plugin_platform_interface]
- path_provider_windows 2.1.7 [ffi flutter path path_provider_platform_interface win32]
- permission_handler_android 10.3.0 [flutter permission_handler_platform_interface]
- permission_handler_apple 9.1.3 [flutter permission_handler_platform_interface]
- permission_handler_platform_interface 3.11.1 [flutter meta plugin_platform_interface]
- permission_handler_windows 0.1.3 [flutter permission_handler_platform_interface]
- petitparser 5.4.0 [meta]
- pin_input_text_field 4.5.1 [flutter]
- platform 3.1.0
- plugin_platform_interface 2.1.4 [meta]
- pointycastle 3.7.3 [collection convert js]
- pool 1.5.1 [async stack_trace]
- process 4.2.4 [file path platform]
- pub_semver 2.1.4 [collection meta]
- pubspec_parse 1.2.3 [checked_yaml collection json_annotation pub_semver yaml]
- qr 3.0.1 [meta]
- recase 4.1.0
- riverpod 2.3.6 [meta stack_trace state_notifier]
- sanitize_html 2.0.0 [html meta]
- screen_brightness_android 0.1.0+2 [flutter screen_brightness_platform_interface]
- screen_brightness_ios 0.1.0 [flutter screen_brightness_platform_interface]
- screen_brightness_macos 0.1.0+1 [flutter screen_brightness_platform_interface]
- screen_brightness_platform_interface 0.1.0 [flutter plugin_platform_interface]
- screen_brightness_windows 0.1.1 [flutter screen_brightness_platform_interface]
- sensors_plus_platform_interface 1.1.3 [flutter meta plugin_platform_interface]
- sentry 7.8.0 [http meta stack_trace uuid]
- share_plus_linux 2.0.4 [share_plus_platform_interface file flutter meta url_launcher]
- share_plus_macos 2.1.0 [share_plus_platform_interface flutter]
- share_plus_platform_interface 2.1.0 [flutter meta mime plugin_platform_interface]
- share_plus_web 2.0.4 [share_plus_platform_interface url_launcher flutter flutter_web_plugins meta]
- share_plus_windows 2.0.3 [share_plus_platform_interface flutter meta url_launcher]
- shared_preferences_android 2.2.0 [flutter shared_preferences_platform_interface]
- shared_preferences_foundation 2.3.1 [flutter shared_preferences_platform_interface]
- shared_preferences_linux 2.3.0 [file flutter path path_provider_linux path_provider_platform_interface shared_preferences_platform_interface]
- shared_preferences_platform_interface 2.3.0 [flutter plugin_platform_interface]
- shared_preferences_web 2.2.0 [flutter flutter_web_plugins shared_preferences_platform_interface]
- shared_preferences_windows 2.3.0 [file flutter path path_provider_platform_interface path_provider_windows shared_preferences_platform_interface]
- shelf 1.4.1 [async collection http_parser path stack_trace stream_channel]
- shelf_web_socket 1.0.4 [shelf stream_channel web_socket_channel]
- sky_engine 0.0.99
- source_gen 1.4.0 [analyzer async build dart_style glob path source_span yaml]
- source_helper 1.3.4 [analyzer collection source_gen]
- source_span 1.9.1 [collection path term_glyph]
- sqflite 2.2.8+4 [flutter sqflite_common path]
- sqflite_common 2.4.5+1 [synchronized path meta]
- sqlite3 1.11.2 [collection ffi js meta path]
- sqlparser 0.22.0 [meta collection source_span charcode]
- stack_trace 1.11.0 [path]
- state_notifier 0.7.2+1 [meta]
- stream_channel 2.1.1 [async]
- stream_transform 2.1.0
- string_scanner 1.2.0 [source_span]
- synchronized 3.1.0
- term_glyph 1.2.1
- test_api 0.5.1 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- timing 1.0.1 [json_annotation]
- tuple 2.0.2
- typed_data 1.3.2 [collection]
- universal_io 2.2.2 [collection meta typed_data]
- universal_platform 1.0.0+1
- url_launcher_android 6.0.36 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.1.4 [flutter url_launcher_platform_interface]
- url_launcher_linux 3.0.5 [flutter url_launcher_platform_interface]
- url_launcher_macos 3.0.5 [flutter url_launcher_platform_interface]
- url_launcher_platform_interface 2.1.3 [flutter plugin_platform_interface]
- url_launcher_web 2.0.18 [flutter flutter_web_plugins url_launcher_platform_interface]
- url_launcher_windows 3.0.7 [flutter url_launcher_platform_interface]
- uuid 3.0.7 [crypto]
- vector_graphics 1.1.7 [flutter vector_graphics_codec]
- vector_graphics_codec 1.1.7
- vector_graphics_compiler 1.1.7 [args meta path_parsing xml vector_graphics_codec]
- vector_math 2.1.4
- video_player_android 2.4.9 [flutter video_player_platform_interface]
- video_player_avfoundation 2.4.6 [flutter video_player_platform_interface]
- video_player_platform_interface 6.1.0 [flutter plugin_platform_interface]
- video_player_web 2.0.16 [flutter flutter_web_plugins video_player_platform_interface]
- wakelock_plus 1.1.1 [flutter flutter_web_plugins meta wakelock_plus_platform_interface win32 dbus package_info_plus js]
- wakelock_plus_platform_interface 1.1.0 [flutter plugin_platform_interface meta]
- watcher 1.1.0 [async path]
- web_socket_channel 2.4.0 [async crypto stream_channel]
- webview_flutter_android 3.8.2 [flutter webview_flutter_platform_interface]
- webview_flutter_platform_interface 2.3.1 [flutter meta plugin_platform_interface]
- webview_flutter_wkwebview 3.6.2 [flutter path webview_flutter_platform_interface]
- win32 5.0.5 [ffi]
- win32_registry 1.1.1 [ffi win32]
- xdg_directories 1.0.0 [meta path process]
- xml 6.3.0 [collection meta petitparser]
- yaml 3.1.2 [collection source_span string_scanner]
- youtube_player_iframe_web 2.0.2 [flutter flutter_web_plugins webview_flutter_platform_interface]
```

</details>

---

**Comment by danagbemava-nc** [comment] 2023-07-31 12:53
Hi @hnvn, can you provide us with steps to reproduce or a complete minimal reproducible code sample in a repo that we can clone so that we can investigate this? I added the latest version of firebase_performance to a project and I could not reproduce the issue. 

Thank you

**Comment by hnvn** [comment] 2023-08-01 03:44
I created [this repo](https://github.com/hnvn/perf_bug.git) to reproduce the issue but it seems the conflict comes from other plugin (onesignal_flutter)

**Comment by danagbemava-nc** [comment] 2023-08-01 10:09
Hi @hnvn, I think there might be an issue with your setup. I checked the setup steps for [one signal ](https://documentation.onesignal.com/docs/flutter-sdk-setup)and your project included the onesignal-gradle-plugin but that is not included in the setup process in the official docs. I then checked the plugin example and they have removed the usage of the gradle plugin from it as well. See https://github.com/OneSignal/OneSignal-Flutter-SDK/issues/573 & https://github.com/OneSignal/OneSignal-Flutter-SDK/pull/588. I tested by removing the onesignal gradle plugin and it worked as well. 

You should try removing the onesignal gradle plugin from the project. You should also make sure the compileSdkVersion is set to 33. If you face issues with onesignal after removing the gradle plugin, you should report this on their repo. 

Closing from here as the root cause of the issue is a third-party plugin

**Closed by danagbemava-nc** 2023-08-01 10:09 UTC
Labels: type: bug, Needs Attention, in triage

**Comment by hnvn** [comment] 2023-08-01 10:48
@danagbemava-nc thanks for your suggestion, I will try and get back to you later

**Comment by hnvn** [comment] 2023-08-01 14:25
Confirm that the issue is not related to the plugin, it is my mistake of project configuration
