### ISSUE TITLE
🐛 [firebase_core] Multiple `Undefined symbol`'s when building for iOS

### ISSUE THREAD

**Issue by MichaelM97** [firebase/flutterfire#10709] opened 2023-04-02 20:13 UTC
## Bug report

**Describe the bug**
When building for iOS I get the following output:

<details><summary>Click To Expand</summary>

```
Launching lib/main.dart on iPhone 14 in debug mode...
Running pod install...
Running Xcode build...
Xcode build done.                                           80.5s
Failed to build iOS app
Error (Xcode): Undefined symbol: _$s19FirebaseSharedSwift0A11DataDecoderC0D16DecodingStrategyO4blobyA2EmFWC

Error (Xcode): Undefined symbol: _$s19FirebaseSharedSwift0A11DataDecoderC19KeyDecodingStrategyO14useDefaultKeysyA2EmFWC

Error (Xcode): Undefined symbol: _$s19FirebaseSharedSwift0A11DataDecoderC19keyDecodingStrategyAC03KeygH0OvsTj

Error (Xcode): Undefined symbol: _$s19FirebaseSharedSwift0A11DataDecoderC20DateDecodingStrategyO6customyAE10Foundation0F0Vs0E0_pKccAEmFWC

Error (Xcode): Undefined symbol: _$s19FirebaseSharedSwift0A11DataDecoderC20dataDecodingStrategyAC0dgH0OvsTj

Error (Xcode): Undefined symbol: _$s19FirebaseSharedSwift0A11DataDecoderC20dateDecodingStrategyAC04DategH0OvsTj

Error (Xcode): Undefined symbol: _$s19FirebaseSharedSwift0A11DataDecoderC23passthroughTypeResolverAA026StructureCodingPassthroughgH0_pXpvsTj

Error (Xcode): Undefined symbol: _$s19FirebaseSharedSwift0A11DataDecoderC34NonConformingFloatDecodingStrategyO5throwyA2EmFWC

Error (Xcode): Undefined symbol: _$s19FirebaseSharedSwift0A11DataDecoderC34nonConformingFloatDecodingStrategyAC03NonghiJ0OvsTj

Error (Xcode): Undefined symbol: _$s19FirebaseSharedSwift0A11DataDecoderC6decode_4fromxxm_yptKSeRzlFTj

Error (Xcode): Undefined symbol: _$s19FirebaseSharedSwift0A11DataDecoderC8userInfoSDys010CodingUserG3KeyVypGvsTj

Error (Xcode): Undefined symbol: _$s19FirebaseSharedSwift0A11DataEncoderC0D16EncodingStrategyO4blobyA2EmFWC

Error (Xcode): Undefined symbol: _$s19FirebaseSharedSwift0A11DataEncoderC19KeyEncodingStrategyO14useDefaultKeysyA2EmFWC

Error (Xcode): Undefined symbol: _$s19FirebaseSharedSwift0A11DataEncoderC19keyEncodingStrategyAC03KeygH0OvsTj

Error (Xcode): Undefined symbol: _$s19FirebaseSharedSwift0A11DataEncoderC20DateEncodingStrategyO6customyAEy10Foundation0F0V_s0E0_ptKccAEmFWC

Error (Xcode): Undefined symbol: _$s19FirebaseSharedSwift0A11DataEncoderC20dataEncodingStrategyAC0dgH0OvsTj

Error (Xcode): Undefined symbol: _$s19FirebaseSharedSwift0A11DataEncoderC20dateEncodingStrategyAC04DategH0OvsTj

Error (Xcode): Undefined symbol: _$s19FirebaseSharedSwift0A11DataEncoderC23passthroughTypeResolverAA026StructureCodingPassthroughgH0_pXpvsTj

Error (Xcode): Undefined symbol: _$s19FirebaseSharedSwift0A11DataEncoderC34NonConformingFloatEncodingStrategyO5throwyA2EmFWC

Error (Xcode): Undefined symbol: _$s19FirebaseSharedSwift0A11DataEncoderC34nonConformingFloatEncodingStrategyAC03NonghiJ0OvsTj

Error (Xcode): Undefined symbol: _$s19FirebaseSharedSwift0A11DataEncoderC6encodeyypxKSERzlFTj

Error (Xcode): Undefined symbol: _$s19FirebaseSharedSwift0A11DataEncoderC8userInfoSDys010CodingUserG3KeyVypGvsTj

Error (Xcode): Undefined symbol: _$s19FirebaseSharedSwift38StructureCodingPassthroughTypeResolverP02isfG0ySbqd__lFZTq

Could not build the application for the simulator.
Error launching application on iPhone 14.
```

</details>

This is when building with `firebase_core` version `^2.9.0` alongside the `FirebaseFirestore` pod version `10.7.0`:
```pod
$FirebaseSDKVersion = '10.7.0'
...
    pod 'FirebaseFirestore', :git => 'https://github.com/invertase/firestore-ios-sdk-frameworks.git', :tag => $FirebaseSDKVersion
```

### Steps to reproduce

Build the sample project linked below for iOS.

### Expected behavior

The app should build successfully for iOS as it does for Android.

### Sample project

https://github.com/MichaelM97/Flutter-Fire-Issue

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.9, on macOS 13.2.1 22D68 darwin-x64, locale
    en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] IntelliJ IDEA Community Edition (version 2022.1.4)
[✓] VS Code (version 1.63.0)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.19.6
Flutter SDK 3.7.9
flutter_fire_issue 1.0.0+1

dependencies:
- cloud_firestore 4.5.0 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_interface flutter meta]
- cloud_functions 4.1.0 [cloud_functions_platform_interface cloud_functions_web firebase_core firebase_core_platform_interface flutter]
- cupertino_icons 1.0.5
- firebase_analytics 10.2.0 [firebase_analytics_platform_interface firebase_analytics_web firebase_core firebase_core_platform_interface flutter]
- firebase_auth 4.4.0 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 2.9.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_crashlytics 3.1.0 [firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface flutter stack_trace]
- firebase_remote_config 4.0.0 [firebase_core firebase_core_platform_interface firebase_remote_config_platform_interface firebase_remote_config_web flutter]
- flutter 0.0.0 [characters collection js material_color_utilities meta vector_math sky_engine]

dev dependencies:
- flutter_lints 2.0.1 [lints]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters collection js matcher material_color_utilities meta source_span stream_channel string_scanner term_glyph]

transitive dependencies:
- _flutterfire_internals 1.1.0 [collection firebase_core firebase_core_platform_interface flutter meta]
- async 2.10.0 [collection meta]
- boolean_selector 2.1.1 [source_span string_scanner]
- characters 1.2.1
- clock 1.1.1
- cloud_firestore_platform_interface 5.12.0 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 3.4.0 [_flutterfire_internals cloud_firestore_platform_interface collection firebase_core firebase_core_web flutter flutter_web_plugins js]
- cloud_functions_platform_interface 5.2.0 [firebase_core flutter meta plugin_platform_interface]
- cloud_functions_web 4.4.0 [cloud_functions_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- collection 1.17.0
- fake_async 1.3.1 [clock collection]
- firebase_analytics_platform_interface 3.4.0 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_analytics_web 0.5.2 [_flutterfire_internals firebase_analytics_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- firebase_auth_platform_interface 6.13.0 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 5.3.0 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core_platform_interface 4.6.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.3.0 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_crashlytics_platform_interface 3.4.0 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_remote_config_platform_interface 1.2.0 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_remote_config_web 1.2.0 [firebase_core firebase_core_web firebase_remote_config_platform_interface flutter flutter_web_plugins js]
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta vector_math]
- http_parser 4.0.2 [collection source_span string_scanner typed_data]
- intl 0.17.0 [clock path]
- js 0.6.5 [meta]
- lints 2.0.1
- matcher 0.12.13 [meta stack_trace]
- material_color_utilities 0.2.0
- meta 1.8.0
- path 1.8.2
- plugin_platform_interface 2.1.4 [meta]
- sky_engine 0.0.99
- source_span 1.9.1 [collection path term_glyph]
- stack_trace 1.11.0 [path]
- stream_channel 2.1.1 [async]
- string_scanner 1.2.0 [source_span]
- term_glyph 1.2.1
- test_api 0.4.16 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.1 [collection]
- vector_math 2.1.4
```

</details>

---

**Comment by MichaelM97** [comment] 2023-04-03 12:28
> For your issue, try `pod repo update` and then run again to see if you still get same errors or not.

I ran `pod repo update` in the `/ios` folder & I'm still getting the same error output. I see that you're building for an iPhone 13, which iOS version is that running? I'm building for an iPhone 14 running iOS 16.2

**Comment by darshankawar** [comment] 2023-04-04 11:41
> which iOS version is that running?

15.2


Also, since I have been getting the error as mentioned earlier while running your repo, I commented out `firebase_crashlytics` package, ran `flutter pub get`, deleted `podfile.lock` and then the app again which compiled and ran properly:

```
Launching lib/main.dart on iPhone 13 in debug mode...
Running pod install...
Running Xcode build...
Xcode build done.                                           75.5s
Debug service listening on ws://127.0.0.1:61286/F1vLZxH81BQ=/ws
Syncing files to device iPhone 13...

```

**Comment by MichaelM97** [comment] 2023-04-05 10:50
> I commented out `firebase_crashlytics` package, ran `flutter pub get`, deleted `podfile.lock` and then the app again which compiled and ran properly:

Removing the `firebase_crashlytics` dependency, running `flutter clean` & `flutter pub get`, then deleting `Podfile.lock` did not work for me, I got the same error output.

I did the above steps after removing all Firebase dependencies apart from `firebase_core` and got a different error:
```
Failed to build iOS app
Error (Xcode): Undefined symbol: _pb_decode

Error (Xcode): Undefined symbol: _pb_encode

Error (Xcode): Undefined symbol: _pb_istream_from_buffer

Error (Xcode): Undefined symbol: _pb_release

Could not build the application for the simulator.
Error launching application on iPhone 14.
```

**Comment by darshankawar** [comment] 2023-04-05 11:35
This is strange. Can you do following:

Run `flutter clean`. Then cd into ios/ directory and run: `rm Podfile.lock && rm -rf Pods`. cd back into root of project and run `flutter pub get`

**Comment by MichaelM97** [comment] 2023-04-05 13:07
> This is strange. Can you do following:
> 
> Run `flutter clean`. Then cd into ios/ directory and run: `rm Podfile.lock && rm -rf Pods`. cd back into root of project and run `flutter pub get`

Did this & I'm still getting the same output. I've pushed the latest changes to my example project in this commit - https://github.com/MichaelM97/Flutter-Fire-Issue/commit/d378872eba78c419b075827b942a9110409a6d19

**Comment by darshankawar** [comment] 2023-04-06 12:28
Can you switch to latest master and try again ?

`flutter channel master`
`flutter upgrade`

**Comment by shafimuhammed** [comment] 2023-04-06 16:42
I had this same issue & I fixed by downgrading `firebase_remote_config: ^4.0.0` to `firebase_remote_config: ^3.0.3`. happy to help  ❤️

**Comment by Polar8ear** [comment] 2023-04-12 14:42
I dont think the issue should be closed since the root cause hasnt been fixed

**Comment by MichaelM97** [comment] 2023-04-12 19:56
> Can you switch to latest master and try again ?
> 
> `flutter channel master` `flutter upgrade`

I ran the following:
* flutter channel master
* flutter upgrade
* flutter clean
* cd into ios/ directory 
* rm Podfile.lock && rm -rf Pods
* cd back into root of project 
* flutter pub get

and got the following output when running the app:

```
Downloading ios tools...
Downloading ios-profile tools...
Downloading ios-release tools...
Launching lib/main.dart on iPhone 14 in debug mode...
Adding input path to Thin Binary build phase.
Running pod install...
Running Xcode build...
Xcode build done.                                           61.3s
Failed to build iOS app
Error (Xcode): Undefined symbol: _pb_decode

Error (Xcode): Undefined symbol: _pb_encode

Error (Xcode): Undefined symbol: _pb_istream_from_buffer

Error (Xcode): Undefined symbol: _pb_release

Could not build the application for the simulator.
Error launching application on iPhone 14.
```

<details><summary>flutter doctor output</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 3.10.0-4.0.pre.20, on macOS 13.2.1 22D68
    darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] IntelliJ IDEA Community Edition (version 2022.1.4)
[✓] VS Code (version 1.63.0)
[✓] Connected device (2 available)
[✓] Network resources

• No issues found!
```

</details>

**Comment by darshankawar** [comment] 2023-04-13 09:40
I am unable to replicate this running on my physical device and simulator. Maybe it is specific to iPhone 14 ?
Labeling for team's attention and thoughts.

/cc @Lyokone

**Comment by ramses-i** [comment] 2023-04-28 08:42
Any update on this? 

Im running into the same problem trying it on iOS 16.4 Emulator from MacBook Pro M2 Max.

I though it was something related to the iOS version or my project, so I downloaded iOS 15.2 that worked for @darshankawar and follow the steps mentioned but got the same result.

`
Launching lib/main.dart on iPhone 13 - 15.2 in debug mode...
Adding input path to Thin Binary build phase.
Running pod install...
Upgrading Pods-Runner-frameworks.sh
Running Xcode build...
Xcode build done.                                           14.7s
Failed to build iOS app
Error (Xcode): Undefined symbol: _pb_decode

Error (Xcode): Undefined symbol: _pb_encode

Error (Xcode): Undefined symbol: _pb_istream_from_buffer

Error (Xcode): Undefined symbol: _pb_release

Error (Xcode): Linker command failed with exit code 1 (use -v to see invocation)

Could not build the application for the simulator.
Error launching application on iPhone 13 - 15.2.
`

**Comment by russellwheatley** [comment] 2023-07-03 12:36
this works when you add cloud_firestore as a dependency. You also need to use the latest version of the firebase ios sdk which is `10.10.0`. Otherwise there is no point in this line which is the reason why it is breaking:

```
pod 'FirebaseFirestore', :git => 'https://github.com/invertase/firestore-ios-sdk-frameworks.git', :tag => $FirebaseSDKVersion
```

**Closed by russellwheatley** 2023-07-03 12:36 UTC
Labels: type: bug, plugin: core, platform: ios

**Comment by gemniaamir** [comment] 2023-07-05 09:02
> this works when you add cloud_firestore as a dependency. You also need to use the latest version of the firebase ios sdk which is `10.10.0`. Otherwise there is no point in this line which is the reason why it is breaking:
> 
> ```
> pod 'FirebaseFirestore', :git => 'https://github.com/invertase/firestore-ios-sdk-frameworks.git', :tag => $FirebaseSDKVersion
> ```

This worked for me as well. I was also facing same issue as mentioned above. By setting $FirebaseSDKVersion instead of version number solved issue

**Comment by eseidel** [comment] 2023-07-26 20:01
@felangel and @bryanoltman both hit this just now (on separate machines) trying to build https://github.com/felangel/bloc/tree/master/examples/flutter_firebase_login
