### ISSUE TITLE
🐛 [firebase_core] Firebase Core 2.14.0 fails to build on Windows

### ISSUE THREAD

**Issue by MahmoodAliL** [firebase/flutterfire#11255] opened 2023-07-11 08:36 UTC
## Bug report
```
cmake -E tar: error: ZIP decompression failed (-5)
CMake Error at flutter/ephemeral/.plugin_symlinks/firebase_core/windows/CMakeLists.txt:90 (add_subdirectory):
  The source directory

    C:/Users/mahmo/Desktop/Temp/firebase_core_windows_issue/build/windows/extracted/firebase_cpp_sdk

  does not contain a CMakeLists.txt file.


CMake Error at flutter/ephemeral/.plugin_symlinks/firebase_core/windows/CMakeLists.txt:95 (get_target_property):
  get_target_property() called with non-existent target "firebase_auth".


CMake Error at flutter/ephemeral/.plugin_symlinks/firebase_core/windows/CMakeLists.txt:96 (string):
  string sub-command REPLACE requires at least four arguments.
2

CMake Error at flutter/ephemeral/.plugin_symlinks/firebase_core/windows/CMakeLists.txt:97 (set_target_properties):
  set_target_properties Can not find target to add properties to:
  firebase_auth
2

CMake Error at flutter/ephemeral/.plugin_symlinks/firebase_core/windows/CMakeLists.txt:95 (get_target_property):
  get_target_property() called with non-existent target "firebase_database".


CMake Error at flutter/ephemeral/.plugin_symlinks/firebase_core/windows/CMakeLists.txt:96 (string):
  string sub-command REPLACE requires at least four arguments.


CMake Error at flutter/ephemeral/.plugin_symlinks/firebase_core/windows/CMakeLists.txt:97 (set_target_properties):
  set_target_properties Can not find target to add properties to:
  firebase_database
2

CMake Error at flutter/ephemeral/.plugin_symlinks/firebase_core/windows/CMakeLists.txt:95 (get_target_property):
  get_target_property() called with non-existent target "firebase_app".


CMake Error at flutter/ephemeral/.plugin_symlinks/firebase_core/windows/CMakeLists.txt:96 (string):
  string sub-command REPLACE requires at least four arguments.


CMake Error at flutter/ephemeral/.plugin_symlinks/firebase_core/windows/CMakeLists.txt:97 (set_target_properties):
  set_target_properties Can not find target to add properties to:
  firebase_app
2

Exception: Unable to generate build files
```
**Describe the bug**
After adding firebase_core 2.140 to a Flutter project that supports Windows, the Windows build will fail to compile 
### Steps to reproduce

1. Create a new project
2. Add the firebase_core package
3. run the app on the Windows channel

### Expected behavior

The app should build and run on windows
### Sample project

Please link to the public repository URL.
https://github.com/MahmoodAliL/firebase_core_windows_issue
---

## Additional context

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[√] Flutter (Channel stable, 3.10.5, on Microsoft Windows [Version 10.0.19044.3086], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.7.0 Preview 2.0)
[√] Android Studio (version 2021.2)
[√] VS Code (version 1.80.0)
[√] Connected device (3 available)
[√] Network resources

! Doctor found issues in 1 category.
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 3.0.5
Flutter SDK 3.10.5
firebase_core_windows_issue 0.1.0

dependencies:
- firebase_core 2.14.0 [firebase_core_platform_interface firebase_core_web flutter meta]       
- flutter 0.0.0 [characters collection js material_color_utilities meta vector_math sky_engine]

dev dependencies:
- flutter_lints 2.0.2 [lints]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters collection js matcher material_color_utilities meta source_span stream_channel string_scanner term_glyph]

transitive dependencies:
- async 2.11.0 [collection meta]
- boolean_selector 2.1.1 [source_span string_scanner]
- characters 1.3.0
- clock 1.1.1
- collection 1.17.1
- fake_async 1.3.1 [clock collection]
- firebase_core_platform_interface 4.8.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.6.0 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta vector_math]
- js 0.6.7 [meta]
- lints 2.1.1
- matcher 0.12.15 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.2.0
- meta 1.9.1
- path 1.8.3
- plugin_platform_interface 2.1.4 [meta]
- sky_engine 0.0.99
- source_span 1.9.1 [collection path term_glyph]
- stack_trace 1.11.0 [path]
- stream_channel 2.1.1 [async]
- string_scanner 1.2.0 [source_span]
- term_glyph 1.2.1
- test_api 0.5.1 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- vector_math 2.1.4```

</details>

---

**Comment by darshankawar** [comment] 2023-07-11 11:20
@MahmoodAliL 
Looks like duplicate of https://github.com/firebase/flutterfire/issues/10992. So please follow-up in it for further updates.
Maybe you can try [this](https://github.com/firebase/flutterfire/issues/10992#issuecomment-1596763383) and see if it helps in your case or not.

**Closed by darshankawar** 2023-07-11 11:20 UTC
Labels: type: bug, Needs Attention, in triage

**Comment by MahmoodAliL** [comment] 2023-07-11 13:38
None of these are helping me to fix the issue
