### ISSUE TITLE
[Firebase_ Analytics]: Event not sent since app measurement is disabled

### ISSUE THREAD

**Issue by changkuanlai** [firebase/flutterfire#13198] opened 2024-08-20 04:42 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Analytics

### Which platforms are affected?

Android

### Description

No problem on iOS platform, invalid statistics on Android。

I have already used CLI Flutterfire configure to configure the grade.

flutterfire -v

1.0.0

### Reproducing the issue

![image](https://github.com/user-attachments/assets/1bd1b306-481f-4c80-8358-3679cf7e13b0)
![image](https://github.com/user-attachments/assets/f2b845e8-6f06-4deb-a04b-b7b8c33e08db)

 ![1724128532336](https://github.com/user-attachments/assets/d17403e7-e2be-4145-9ca9-2e40e6bdceff)

### Firebase Core version

2.14.0

### Flutter Version

3.19.6

### Relevant Log Output

```shell
08-20 12:25:50.962 V/FA      (21671): onActivityCreated
08-20 12:25:50.992 I/FA      (21671): App measurement disabled via the manifest
08-20 12:25:50.993 I/FA      (21671): App measurement initialized, version: 87000
08-20 12:25:50.993 I/FA      (21671): To enable debug logging run: adb shell setprop log.tag.FA VERBOSE
08-20 12:25:50.994 I/FA      (21671): To enable faster debug mode event logging run:
08-20 12:25:50.994 I/FA      (21671):   adb shell setprop debug.firebase.analytics.app com.upseller.app
08-20 12:25:50.994 D/FA      (21671): Debug-level message logging enabled
08-20 12:25:51.002 V/FA      (21671): Detected application was in foreground
08-20 12:25:51.008 D/FA      (21671): Resetting session stitching token to not null
08-20 12:25:51.012 V/FA      (21671): Connecting to remote service
08-20 12:25:51.026 V/FA      (21671): Connection attempt already in progress
08-20 12:25:51.513 V/FA      (21671): Activity resumed, time: 12189702
08-20 12:25:51.514 D/FA      (21671): Event not sent since app measurement is disabled
08-20 12:25:51.514 V/FA      (21671): Connection attempt already in progress
08-20 12:25:51.609 D/FA      (21671): Connected to remote service
08-20 12:25:51.610 V/FA      (21671): Processing queued up service tasks: 3
08-20 12:25:51.632 V/FA-SVC  (17163): Saving default event parameters, appId, data size: com.upseller.app, 2
08-20 12:25:51.793 D/FA      (21671): Event not sent since app measurement is disabled
08-20 12:25:53.793 V/FA      (21671): Logging screen view with name, class: HomePage, HomePage
08-20 12:25:53.794 D/FA      (21671): Event not sent since app measurement is disabled
08-20 12:25:53.795 V/FA      (21671): Recording user engagement, ms: 2280
08-20 12:25:58.799 V/FA      (21671): Inactivity, disconnecting from the service
08-20 12:26:01.272 V/FA      (21671): Logging screen view with name, class: MLQuestionPage, MLQuestionPage
08-20 12:26:01.273 D/FA      (21671): Event not sent since app measurement is disabled
08-20 12:26:01.274 V/FA      (21671): Recording user engagement, ms: 7479
08-20 12:26:01.274 V/FA      (21671): Connecting to remote service
08-20 12:26:01.278 D/FA      (21671): Connected to remote service
08-20 12:26:01.279 V/FA      (21671): Processing queued up service tasks: 1
08-20 12:26:06.285 V/FA      (21671): Inactivity, disconnecting from the service
08-20 12:27:12.053 V/FA      (21671): Logging screen view with name, class: MLQuestionDetailPage, MLQuestionDetailPage
08-20 12:27:12.053 D/FA      (21671): Event not sent since app measurement is disabled
08-20 12:27:12.054 V/FA      (21671): Recording user engagement, ms: 70781
08-20 12:27:12.054 V/FA      (21671): Connecting to remote service
08-20 12:27:12.071 D/FA      (21671): Connected to remote service
08-20 12:27:12.072 V/FA      (21671): Processing queued up service tasks: 1
08-20 12:27:17.076 V/FA      (21671): Inactivity, disconnecting from the service
```

### Flutter dependencies

<details>
 Dart SDK 3.3.4
Flutter SDK 3.19.6
dependencies:
- animations 2.0.11 [flutter]
- audioplayers 6.0.0 [audioplayers_android audioplayers_darwin audioplayers_linux audioplayers_platform_interface audioplayers_web audioplayers_windows file flutter http meta path_provider synchronized uuid]
- camera 0.10.6 [camera_android camera_avfoundation camera_platform_interface camera_web flutter flutter_plugin_android_lifecycle]
- chat_bottom_container 0.1.0 [flutter plugin_platform_interface]
- connectivity_plus 4.0.2 [flutter flutter_web_plugins connectivity_plus_platform_interface js meta nm]
- cupertino_icons 1.0.6
- device_info_plus 9.1.2 [device_info_plus_platform_interface ffi file flutter flutter_web_plugins meta win32 win32_registry]
- dio 5.4.3+1 [async http_parser meta path]
- dio_cookie_manager 3.1.1 [cookie_jar dio]
- easy_refresh 3.4.0 [flutter path_drawing]
- encrypt 5.0.3 [args asn1lib clock collection crypto pointycastle]
- event_bus 2.0.0
- extended_image 8.2.0 [extended_image_library flutter meta]
- extended_text 13.0.2 [extended_text_library flutter]
- extended_text_field 14.0.0 [extended_text_library flutter]
- firebase_analytics 10.10.7 [firebase_analytics_platform_interface firebase_analytics_web firebase_core firebase_core_platform_interface flutter]
- firebase_core 2.32.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- flex_color_scheme 7.3.1 [flex_seed_scheme flutter meta]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- flutter_animated_dialog 2.0.1 [flutter]
- flutter_easyloading 3.0.5 [flutter flutter_spinkit]
- flutter_keychain 2.5.0 [flutter]
- flutter_local_notifications 16.3.3 [clock flutter flutter_local_notifications_linux flutter_local_notifications_platform_interface timezone]
- flutter_localizations 0.0.0 [flutter intl characters clock collection material_color_utilities meta path vector_math]
- flutter_markdown 0.7.1 [flutter markdown meta path]
- flutter_native_splash 2.4.0 [args flutter flutter_web_plugins html image meta path universal_io xml yaml ansicolor]
- flutter_parsed_text 2.2.1 [flutter]
- flutter_screenutil 5.9.0 [flutter]
- flutter_svg 2.0.10+1 [flutter http vector_graphics vector_graphics_codec vector_graphics_compiler]
- get 4.6.6 [flutter]
- getwidget 4.0.0 [flutter]
- go_router 13.2.4 [collection flutter flutter_web_plugins logging meta]
- google_mlkit_barcode_scanning 0.12.0 [flutter google_mlkit_commons]
- image_gallery_saver 2.0.3 [flutter]
- image_picker 0.8.9 [flutter image_picker_android image_picker_for_web image_picker_ios image_picker_linux image_picker_macos image_picker_platform_interface image_picker_windows]
- intl 0.18.1 [clock meta path]
- open_file 3.3.2 [flutter ffi]
- package_info_plus 8.0.0 [ffi flutter flutter_web_plugins http meta path package_info_plus_platform_interface web win32 clock]
- path_provider 2.1.3 [flutter path_provider_android path_provider_foundation path_provider_linux path_provider_platform_interface path_provider_windows]
- permission_handler 11.3.1 [flutter meta permission_handler_android permission_handler_apple permission_handler_html permission_handler_windows permission_handler_platform_interface]
- pinput 5.0.0 [flutter universal_platform]
- pull_to_refresh_flutter3 2.0.2 [flutter]
- quick_log 5.4.1 [path rxdart]
- scrollable_positioned_list 0.3.8 [flutter collection]
- shared_preferences 2.2.3 [flutter shared_preferences_android shared_preferences_foundation shared_preferences_linux shared_preferences_platform_interface shared_preferences_web shared_preferences_windows]
- tpns_flutter_plugin 1.3.1 [flutter]
- url_launcher 6.3.0 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- uuid 3.0.7 [crypto]
- video_player 2.8.6 [flutter html video_player_android video_player_avfoundation video_player_platform_interface video_player_web]
- webview_flutter 4.2.0 [flutter webview_flutter_android webview_flutter_platform_interface webview_flutter_wkwebview]
- wechat_assets_picker 9.1.0 [flutter wechat_picker_library extended_image photo_manager photo_manager_image_provider provider video_player]

dev dependencies:
- build_runner 2.4.9 [analyzer args async build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style frontend_server_client glob graphs http_multi_server io js logging meta mime package_config path pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web_socket_channel yaml]
- flutter_launcher_icons 0.13.1 [args checked_yaml cli_util image json_annotation path yaml]
- flutter_lints 3.0.2 [lints]

dependency overrides:
- watcher 1.0.0 [async path pedantic]

transitive dependencies:
- _fe_analyzer_shared 67.0.0 [meta]
- _flutterfire_internals 1.3.35 [collection firebase_core firebase_core_platform_interface flutter meta]
- analyzer 6.4.1 [_fe_analyzer_shared collection convert crypto glob meta package_config path pub_semver source_span watcher yaml]
- ansicolor 2.0.2
- archive 3.5.1 [crypto path]
- args 2.5.0
- asn1lib 1.5.3
- async 2.11.0 [collection meta]
- audioplayers_android 5.0.0 [audioplayers_platform_interface flutter]
- audioplayers_darwin 6.0.0 [audioplayers_platform_interface flutter]
- audioplayers_linux 4.0.0 [audioplayers_platform_interface flutter]
- audioplayers_platform_interface 7.0.0 [collection flutter meta plugin_platform_interface]
- audioplayers_web 5.0.0 [audioplayers_platform_interface flutter flutter_web_plugins web]
- audioplayers_windows 4.0.0 [audioplayers_platform_interface flutter]
- boolean_selector 2.1.1 [source_span string_scanner]
- build 2.4.1 [analyzer async convert crypto glob logging meta package_config path]
- build_config 1.1.1 [checked_yaml json_annotation path pubspec_parse yaml]
- build_daemon 4.0.1 [built_collection built_value crypto http_multi_server logging path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 2.4.2 [analyzer async build collection convert crypto graphs logging package_config path pool pub_semver stream_transform yaml]
- build_runner_core 7.3.0 [async build build_config build_resolvers collection convert crypto glob graphs json_annotation logging meta package_config path pool timing watcher yaml]
- built_collection 5.1.1
- built_value 8.9.2 [built_collection collection fixnum meta]
- camera_android 0.10.9+2 [camera_platform_interface flutter flutter_plugin_android_lifecycle stream_transform]
- camera_avfoundation 0.9.17+2 [camera_platform_interface flutter stream_transform]
- camera_platform_interface 2.8.0 [cross_file flutter plugin_platform_interface stream_transform]
- camera_web 0.3.5 [camera_platform_interface flutter flutter_web_plugins stream_transform web]
- characters 1.3.0
- checked_yaml 2.0.3 [json_annotation source_span yaml]
- cli_util 0.4.1 [meta path]
- clock 1.1.1
- code_builder 4.10.0 [built_collection built_value collection matcher meta]
- collection 1.18.0
- connectivity_plus_platform_interface 1.2.4 [flutter meta plugin_platform_interface]
- convert 3.1.1 [typed_data]
- cookie_jar 4.0.8 [meta universal_io]
- cross_file 0.3.4+1 [meta web]
- crypto 3.0.3 [typed_data]
- csslib 1.0.0 [source_span]
- dart_style 2.3.6 [analyzer args collection path pub_semver source_span]
- dbus 0.7.10 [args ffi meta xml]
- device_info_plus_platform_interface 7.0.0 [flutter meta plugin_platform_interface]
- extended_image_library 4.0.4 [crypto flutter http_client_helper js path path_provider web]
- extended_text_library 12.0.0 [flutter]
- fake_async 1.3.1 [clock collection]
- ffi 2.1.2
- file 7.0.0 [meta path]
- file_selector_linux 0.9.2+1 [cross_file file_selector_platform_interface flutter]
- file_selector_macos 0.9.4 [cross_file file_selector_platform_interface flutter]
- file_selector_platform_interface 2.6.2 [cross_file flutter http plugin_platform_interface]
- file_selector_windows 0.9.3+1 [cross_file file_selector_platform_interface flutter]
- firebase_analytics_platform_interface 3.10.8 [_flutterfire_internals firebase_core flutter meta plugin_platform_interface]
- firebase_analytics_web 0.5.7+7 [_flutterfire_internals firebase_analytics_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins]
- firebase_core_platform_interface 5.0.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.17.0 [firebase_core_platform_interface flutter flutter_web_plugins meta web]
- fixnum 1.1.0
- flex_seed_scheme 1.5.0 [collection flutter meta]
- flutter_local_notifications_linux 4.0.0+1 [dbus ffi flutter flutter_local_notifications_platform_interface path xdg_directories]
- flutter_local_notifications_platform_interface 7.1.0 [flutter plugin_platform_interface]
- flutter_plugin_android_lifecycle 2.0.19 [flutter]
- flutter_spinkit 5.2.1 [flutter]
- flutter_test 0.0.0 [flutter test_api matcher path fake_async clock stack_trace vector_math leak_tracker_flutter_testing async boolean_selector characters collection leak_tracker leak_tracker_testing material_color_utilities meta source_span stream_channel string_scanner term_glyph vm_service]
- flutter_web_plugins 0.0.0 [flutter characters collection material_color_utilities meta vector_math]
- frontend_server_client 4.0.0 [async path]
- glob 2.1.2 [async collection file path string_scanner]
- google_mlkit_commons 0.7.1 [flutter]
- graphs 2.3.1 [collection]
- html 0.15.4 [csslib source_span]
- http 1.2.1 [async http_parser meta web]
- http_client_helper 3.0.0 [http]
- http_multi_server 3.2.1 [async]
- http_parser 4.0.2 [collection source_span string_scanner typed_data]
- image 4.2.0 [archive meta xml]
- image_picker_android 0.8.12+1 [flutter flutter_plugin_android_lifecycle image_picker_platform_interface]
- image_picker_for_web 2.2.0 [flutter flutter_web_plugins image_picker_platform_interface mime]
- image_picker_ios 0.8.12 [flutter image_picker_platform_interface]
- image_picker_linux 0.2.1+1 [file_selector_linux file_selector_platform_interface flutter image_picker_platform_interface]
- image_picker_macos 0.2.1+1 [file_selector_macos file_selector_platform_interface flutter image_picker_platform_interface]
- image_picker_platform_interface 2.10.0 [cross_file flutter http plugin_platform_interface]
- image_picker_windows 0.2.1+1 [file_selector_platform_interface file_selector_windows flutter image_picker_platform_interface]
- io 1.0.4 [meta path string_scanner]
- js 0.6.7 [meta]
- json_annotation 4.9.0 [meta]
- leak_tracker 10.0.0 [clock collection meta path vm_service]
- leak_tracker_flutter_testing 2.0.1 [flutter leak_tracker leak_tracker_testing matcher meta]
- leak_tracker_testing 2.0.1 [leak_tracker matcher meta]
- lints 3.0.0
- logging 1.2.0
- markdown 7.2.2 [args meta]
- matcher 0.12.16+1 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.8.0 [collection]
- meta 1.11.0
- mime 1.0.5
- nested 1.0.0 [flutter]
- nm 0.5.0 [dbus]
- package_config 2.1.0 [path]
- package_info_plus_platform_interface 3.0.0 [flutter meta plugin_platform_interface]
- path 1.9.0
- path_drawing 1.0.1 [vector_math meta path_parsing flutter]
- path_parsing 1.0.1 [vector_math meta]
- path_provider_android 2.2.4 [flutter path_provider_platform_interface]
- path_provider_foundation 2.4.0 [flutter path_provider_platform_interface]
- path_provider_linux 2.2.1 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_platform_interface 2.1.2 [flutter platform plugin_platform_interface]
- path_provider_windows 2.2.1 [ffi flutter path path_provider_platform_interface win32]
- pedantic 1.11.1
- permission_handler_android 12.0.6 [flutter permission_handler_platform_interface]
- permission_handler_apple 9.4.4 [flutter permission_handler_platform_interface]
- permission_handler_html 0.1.1 [flutter flutter_web_plugins permission_handler_platform_interface]
- permission_handler_platform_interface 4.2.1 [flutter meta plugin_platform_interface]
- permission_handler_windows 0.2.1 [flutter permission_handler_platform_interface]
- petitparser 6.0.2 [meta]
- photo_manager 3.2.1 [flutter]
- photo_manager_image_provider 2.1.1 [flutter photo_manager]
- platform 3.1.4
- plugin_platform_interface 2.1.8 [meta]
- pointycastle 3.9.1 [collection convert js]
- pool 1.5.1 [async stack_trace]
- provider 6.1.2 [collection flutter nested]
- pub_semver 2.1.4 [collection meta]
- pubspec_parse 1.3.0 [checked_yaml collection json_annotation pub_semver yaml]
- rxdart 0.27.7
- shared_preferences_android 2.2.2 [flutter shared_preferences_platform_interface]
- shared_preferences_foundation 2.4.0 [flutter shared_preferences_platform_interface]
- shared_preferences_linux 2.3.2 [file flutter path path_provider_linux path_provider_platform_interface shared_preferences_platform_interface]
- shared_preferences_platform_interface 2.3.2 [flutter plugin_platform_interface]
- shared_preferences_web 2.3.0 [flutter flutter_web_plugins shared_preferences_platform_interface web]
- shared_preferences_windows 2.3.2 [file flutter path path_provider_platform_interface path_provider_windows shared_preferences_platform_interface]
- shelf 1.4.1 [async collection http_parser path stack_trace stream_channel]
- shelf_web_socket 1.0.4 [shelf stream_channel web_socket_channel]
- sky_engine 0.0.99
- source_span 1.10.0 [collection path term_glyph]
- stack_trace 1.11.1 [path]
- stream_channel 2.1.2 [async]
- stream_transform 2.1.0
- string_scanner 1.2.0 [source_span]
- synchronized 3.1.0+1
- term_glyph 1.2.1
- test_api 0.6.1 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph]
- timezone 0.9.3 [path]
- timing 1.0.1 [json_annotation]
- typed_data 1.3.2 [collection]
- universal_io 2.2.2 [collection meta typed_data]
- universal_platform 1.1.0
- url_launcher_android 6.3.2 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.3.0 [flutter url_launcher_platform_interface]
- url_launcher_linux 3.1.1 [flutter url_launcher_platform_interface]
- url_launcher_macos 3.2.0 [flutter url_launcher_platform_interface]
- url_launcher_platform_interface 2.3.2 [flutter plugin_platform_interface]
- url_launcher_web 2.3.1 [flutter flutter_web_plugins url_launcher_platform_interface web]
- url_launcher_windows 3.1.1 [flutter url_launcher_platform_interface]
- vector_graphics 1.1.11+1 [flutter http vector_graphics_codec]
- vector_graphics_codec 1.1.11+1
- vector_graphics_compiler 1.1.11+1 [args meta path_parsing xml vector_graphics_codec path]
- vector_math 2.1.4
- video_player_android 2.4.14 [flutter video_player_platform_interface]
- video_player_avfoundation 2.6.1 [flutter video_player_platform_interface]
- video_player_platform_interface 6.2.2 [flutter plugin_platform_interface]
- video_player_web 2.3.1 [flutter flutter_web_plugins video_player_platform_interface web]
- vm_service 13.0.0
- web 0.5.1
- web_socket_channel 2.4.5 [async crypto stream_channel web]
- webview_flutter_android 3.16.3 [flutter webview_flutter_platform_interface]
- webview_flutter_platform_interface 2.10.0 [flutter meta plugin_platform_interface]
- webview_flutter_wkwebview 3.13.1 [flutter path webview_flutter_platform_interface]
- wechat_picker_library 1.0.0 [flutter photo_manager]
- win32 5.5.0 [ffi]
- win32_registry 1.1.2 [ffi win32]
- xdg_directories 1.0.4 [meta path]
- xml 6.5.0 [collection meta petitparser]
- yaml 3.1.2 [collection source_span string_scanner]

</details>

**Comment by changkuanlai** [comment] 2024-08-20 04:43
![image](https://github.com/user-attachments/assets/a2a1ac49-e8ad-411f-9af0-f1330c7e2a03)

**Comment by SelaseKay** [comment] 2024-08-20 09:23
Hi @changkuanlai , I'm not able to reproduce this issue. Could you provide a minimal sample code reproducing this issue?

**Comment by changkuanlai** [comment] 2024-08-21 01:24
Crashlytics Android has no issues
![image](https://github.com/user-attachments/assets/d238caf7-eda4-4325-a032-f38aab2af2c4)


> Hi @changkuanlai , I'm not able to reproduce this issue. Could you provide a minimal sample code reproducing this issue?

I am unable to reproduce this issue. My other projects have used Android applicationId and sha-1 on other accounts but have already been removed. I deleted the project in the middle and changed the applicationId. Will there be any correlation.

**Comment by SelaseKay** [comment] 2024-08-21 07:27
Hi @changkuanlai . Since you're an unable to reproduce this issue, I'm going to go ahead and close it. Kindly refer to this [link](https://stackoverflow.com/questions/60607673/how-to-change-app-id-when-working-with-flutter-and-firebase) to see if it helps.

**Closed** 2024-08-21 07:27 UTC
Labels: type: bug, plugin: analytics, platform: android, Needs Attention
