### ISSUE TITLE
🐛 [firebase_messaging] The onMessage method is not called on iOS

### ISSUE THREAD

**Issue by sirkalmi** [firebase/flutterfire#8515] opened 2022-04-25 07:18 UTC
Since version 11.2.11, the onMessage method has not been called on iOS.
I don't think the following line should have been removed in [this commit](https://github.com/firebase/flutterfire/commit/54f5555edbedc553df30d7e32747e3b305fbe643).
493: [_channel invokeMethod:@"Messaging#onMessage" arguments:notificationDict];

Version 11.2.10 works well.

**Comment by sirkalmi** [comment] 2022-04-25 07:26
Sorry, now I see you've already recorded this bug.
https://github.com/firebase/flutterfire/issues/8378

**Comment by darshankawar** [comment] 2022-04-25 12:01
Closing as duplicate of https://github.com/firebase/flutterfire/issues/8378

**Closed by darshankawar** 2022-04-25 12:01 UTC
Labels: type: bug, Needs Attention, in triage
