### ISSUE TITLE
🐛 [firebase_firestore/firebase_auth/cloud_firestore/firebase_core] Unknown error occurs

### ISSUE THREAD

**Issue by accept1248** [firebase/flutterfire#9385] opened 2022-08-20 06:42 UTC
## Bug report

I have encountered the following error when I tried to login via Flutter Firebase Plugin.
Though the app doesn't crash, but user profile page is not refreshed even I logged in with different user.

<details>
<summary> error log </summary>

```

════════ Exception caught by services library ══════════════════════════════════
PlatformException(error, An error occurred while parsing query arguments, see native logs for more information. Please report this issue., null, null)
════════════════════════════════════════════════════════════════════════════════

**error log**

{
  "description": "Exception caught by services library",
  "type": "_FlutterErrorDetailsNode",
  "allowWrap": false,
  "objectId": "inspector-96",
  "valueId": "inspector-97",
  "properties": [
    {
      "description": "The following PlatformException was thrown while activating platform stream on channel plugins.flutter.io/firebase_firestore/query/ff937639-356a-44e2-80fd-f9bd27110ca5:",
      "type": "ErrorDescription",
      "showSeparator": false,
      "showName": false,
      "style": "flat",
      "allowNameWrap": true,
      "objectId": "inspector-98",
      "valueId": "inspector-99",
      "properties": [],
      "children": [],
      "defaultValue": "null",
      "missingIfNull": false,
      "propertyType": "List<Object>",
      "defaultLevel": "info"
    },
    {
      "description": "PlatformException(error, An error occurred while parsing query arguments, see native logs for more information. Please report this issue., null, null)",
      "type": "ErrorSummary",
      "showSeparator": false,
      "level": "summary",
      "showName": false,
      "style": "flat",
      "allowNameWrap": true,
      "objectId": "inspector-100",
      "valueId": "inspector-101",
      "properties": [],
      "children": [],
      "defaultValue": "null",
      "missingIfNull": false,
      "propertyType": "List<Object>",
      "defaultLevel": "summary"
    },
    {
      "description": "",
      "type": "ErrorSpacer",
      "name": "",
      "showName": false,
      "style": "singleLine",
      "allowNameWrap": true,
      "objectId": "inspector-102",
      "valueId": null,
      "properties": [],
      "children": [],
      "missingIfNull": false,
      "propertyType": "void",
      "defaultLevel": "info",
      "value": null
    },
    {
      "description": "",
      "type": "DiagnosticsStackTrace",
      "name": "When the exception was thrown, this was the stack",
      "style": "flat",
      "allowWrap": false,
      "objectId": "inspector-103",
      "valueId": "inspector-104",
      "properties": [
        {
          "description": "#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:653:7)",
          "type": "DiagnosticsProperty<void>",
          "name": "",
          "showName": false,
          "style": "singleLine",
          "allowWrap": false,
          "allowNameWrap": true,
          "objectId": "inspector-105",
          "valueId": null,
          "properties": [],
          "children": [],
          "missingIfNull": false,
          "propertyType": "void",
          "defaultLevel": "info",
          "value": null
        },
        {
          "description": "#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:296:18)",
          "type": "DiagnosticsProperty<void>",
          "name": "",
          "showName": false,
          "style": "singleLine",
          "allowWrap": false,
          "allowNameWrap": true,
          "objectId": "inspector-106",
          "valueId": null,
          "properties": [],
          "children": [],
          "missingIfNull": false,
          "propertyType": "void",
          "defaultLevel": "info",
          "value": null
        },
        {
          "description": "<asynchronous suspension>",
          "type": "DiagnosticsProperty<void>",
          "name": "",
          "showName": false,
          "style": "singleLine",
          "allowWrap": false,
          "allowNameWrap": true,
          "objectId": "inspector-107",
          "valueId": null,
          "properties": [],
          "children": [],
          "missingIfNull": false,
          "propertyType": "void",
          "defaultLevel": "info",
          "value": null
        },
        {
          "description": "#2      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:637:9)",
          "type": "DiagnosticsProperty<void>",
          "name": "",
          "showName": false,
          "style": "singleLine",
          "allowWrap": false,
          "allowNameWrap": true,
          "objectId": "inspector-108",
          "valueId": null,
          "properties": [],
          "children": [],
          "missingIfNull": false,
          "propertyType": "void",
          "defaultLevel": "info",
          "value": null
        },
        {
          "description": "<asynchronous suspension>",
          "type": "DiagnosticsProperty<void>",
          "name": "",
          "showName": false,
          "style": "singleLine",
          "allowWrap": false,
          "allowNameWrap": true,
          "objectId": "inspector-109",
          "valueId": null,
          "properties": [],
          "children": [],
          "missingIfNull": false,
          "propertyType": "void",
          "defaultLevel": "info",
          "value": null
        }
      ],
      "children": []
    }
  ],
  "children": [],
  "errorsSinceReload": 1,
  "renderedErrorText": "Another exception was thrown: PlatformException(error, An error occurred while parsing query arguments, see native logs for more information. Please report this issue., null, null)"
}

```

</details>

### Expected behavior

The app should display information of the logged in user based on firebase database.

### Sample project

The app is copy of the following repository.
See the branch 14_match_with_users
https://github.com/maxonflutter/flutter_dating_app_series

---

## Additional context

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, 3.1.0-0.0.pre.2362, on Microsoft Windows [Version 10.0.19043.1889], locale ja-JP)
[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[√] Chrome - develop for the web
[√] Android Studio (version 2021.2)
[√] VS Code (version 1.70.2)
[√] Connected device (4 available)
[√] HTTP Host Availability

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.19.0-112.0.dev
Flutter SDK 3.1.0-0.0.pre.2362
datingapp 1.0.0+1
|-- cloud_firestore 3.3.0
|   |-- cloud_firestore_platform_interface 5.7.0
|   |   |-- collection...
|   |   |-- firebase_core...
|   |   |-- flutter...
|   |   |-- meta...
|   |   '-- plugin_platform_interface...
|   |-- cloud_firestore_web 2.8.1
|   |   |-- cloud_firestore_platform_interface...
|   |   |-- collection...
|   |   |-- firebase_core...
|   |   |-- firebase_core_web...
|   |   |-- flutter...
|   |   |-- flutter_web_plugins...
|   |   '-- js...
|   |-- collection...
|   |-- firebase_core...
|   |-- firebase_core_platform_interface...
|   |-- flutter...
|   '-- meta...
|-- cupertino_icons 1.0.5
|-- equatable 2.0.3
|   |-- collection...
|   '-- meta...
|-- firebase_auth 3.5.1
|   |-- firebase_auth_platform_interface 6.4.0
|   |   |-- collection...
|   |   |-- firebase_core...
|   |   |-- flutter...
|   |   |-- meta...
|   |   '-- plugin_platform_interface...
|   |-- firebase_auth_web 4.1.1
|   |   |-- firebase_auth_platform_interface...
|   |   |-- firebase_core...
|   |   |-- firebase_core_web...
|   |   |-- flutter...
|   |   |-- flutter_web_plugins...
|   |   |-- http_parser 4.0.1
|   |   |   |-- collection...
|   |   |   |-- source_span...
|   |   |   |-- string_scanner...
|   |   |   '-- typed_data 1.3.1
|   |   |       '-- collection...
|   |   |-- intl...
|   |   |-- js...
|   |   '-- meta...
|   |-- firebase_core...
|   |-- firebase_core_platform_interface...
|   |-- flutter...
|   '-- meta...
|-- firebase_core 1.19.2
|   |-- firebase_core_platform_interface 4.5.0
|   |   |-- collection...
|   |   |-- flutter...
|   |   |-- flutter_test...
|   |   |-- meta...
|   |   '-- plugin_platform_interface 2.1.2
|   |       '-- meta...
|   |-- firebase_core_web 1.7.1
|   |   |-- firebase_core_platform_interface...
|   |   |-- flutter...
|   |   |-- flutter_web_plugins 0.0.0
|   |   |   |-- characters...
|   |   |   |-- collection...
|   |   |   |-- flutter...
|   |   |   |-- js...
|   |   |   |-- material_color_utilities...
|   |   |   |-- meta...
|   |   |   '-- vector_math...
|   |   |-- js 0.6.4
|   |   '-- meta...
|   |-- flutter...
|   '-- meta...
|-- firebase_storage 10.3.0
|   |-- firebase_core...
|   |-- firebase_core_platform_interface...
|   |-- firebase_storage_platform_interface 4.1.9
|   |   |-- collection...
|   |   |-- firebase_core...
|   |   |-- flutter...
|   |   |-- meta...
|   |   '-- plugin_platform_interface...
|   |-- firebase_storage_web 3.2.18
|   |   |-- async...
|   |   |-- firebase_core...
|   |   |-- firebase_core_web...
|   |   |-- firebase_storage_platform_interface...
|   |   |-- flutter...
|   |   |-- flutter_web_plugins...
|   |   |-- http...
|   |   |-- js...
|   |   '-- meta...
|   '-- flutter...
|-- flutter 0.0.0
|   |-- characters 1.2.1
|   |-- collection 1.16.0
|   |-- material_color_utilities 0.2.0
|   |-- meta 1.8.0
|   |-- sky_engine 0.0.99
|   '-- vector_math 2.1.2
|-- flutter_bloc 8.1.1
|   |-- bloc 8.1.0
|   |   '-- meta...
|   |-- flutter...
|   '-- provider 6.0.3
|       |-- collection...
|       |-- flutter...
|       '-- nested 1.0.0
|           '-- flutter...
|-- flutter_lints 1.0.4
|   '-- lints 1.0.1
|-- flutter_localizations 0.0.0
|   |-- characters...
|   |-- clock 1.1.1
|   |-- collection...
|   |-- flutter...
|   |-- intl...
|   |-- material_color_utilities...
|   |-- meta...
|   |-- path 1.8.2
|   '-- vector_math...
|-- flutter_svg 1.1.1
|   |-- flutter...
|   |-- meta...
|   |-- path_drawing 1.0.0
|   |   |-- flutter...
|   |   |-- meta...
|   |   |-- path_parsing 1.0.0
|   |   |   |-- meta...
|   |   |   '-- vector_math...
|   |   '-- vector_math...
|   |-- vector_math...
|   '-- xml 6.1.0
|       |-- collection...
|       |-- meta...
|       '-- petitparser 5.0.0
|           '-- meta...
|-- flutter_test 0.0.0
|   |-- async 2.9.0
|   |   |-- collection...
|   |   '-- meta...
|   |-- boolean_selector 2.1.0
|   |   |-- source_span...
|   |   '-- string_scanner...
|   |-- characters...
|   |-- clock...
|   |-- collection...
|   |-- fake_async 1.3.1
|   |   |-- clock...
|   |   '-- collection...
|   |-- flutter...
|   |-- matcher 0.12.12
|   |   '-- stack_trace...
|   |-- material_color_utilities...
|   |-- meta...
|   |-- path...
|   |-- source_span 1.9.1
|   |   |-- collection...
|   |   |-- path...
|   |   '-- term_glyph...
|   |-- stack_trace 1.10.0
|   |   '-- path...
|   |-- stream_channel 2.1.0
|   |   '-- async...
|   |-- string_scanner 1.1.1
|   |   '-- source_span...
|   |-- term_glyph 1.2.1
|   |-- test_api 0.4.12
|   |   |-- async...
|   |   |-- boolean_selector...
|   |   |-- collection...
|   |   |-- matcher...
|   |   |-- meta...
|   |   |-- source_span...
|   |   |-- stack_trace...
|   |   |-- stream_channel...
|   |   |-- string_scanner...
|   |   '-- term_glyph...
|   '-- vector_math...
|-- image_picker 0.8.5+3
|   |-- flutter...
|   |-- image_picker_android 0.8.5+1
|   |   |-- flutter...
|   |   |-- flutter_plugin_android_lifecycle 2.0.6
|   |   |   '-- flutter...
|   |   '-- image_picker_platform_interface...
|   |-- image_picker_for_web 2.1.8
|   |   |-- flutter...
|   |   |-- flutter_web_plugins...
|   |   '-- image_picker_platform_interface...
|   |-- image_picker_ios 0.8.5+5
|   |   |-- flutter...
|   |   '-- image_picker_platform_interface...
|   '-- image_picker_platform_interface 2.5.0
|       |-- cross_file 0.3.3+1
|       |   |-- js...
|       |   '-- meta...
|       |-- flutter...
|       |-- http 0.13.4
|       |   |-- async...
|       |   |-- http_parser...
|       |   |-- meta...
|       |   '-- path...
|       '-- plugin_platform_interface...
|-- intl 0.17.0
|   |-- clock...
|   '-- path...
|-- multi_select_flutter 4.1.2
|   |-- collection...
|   '-- flutter...
'-- step_progress_indicator 1.0.2
    '-- flutter...
```

</details>

---

**Comment by darshankawar** [comment] 2022-08-22 07:04
@accept1248 
The app you cloned doesn't seem to be uptodate with plugin versions it is using and seems to be using very old versions of flutterfire plugins.

<img width="279" alt="Screenshot 2022-08-22 at 12 30 53 PM" src="https://user-images.githubusercontent.com/67046386/185858951-50910622-fc60-42ef-9e03-2f77dcf5c8c1.png">

I suggest you to upgrade all flutterfire plugins to latest versions as below and try again. You might need to also update rest of the plugins to their latest versions for best possible user experience.

```
firebase_core: ^1.21.0
firebase_auth: ^3.6.4
firebase_storage: ^10.3.6
cloud_firestore: ^3.4.5
```

Also, the app seems to be using old integration with Firebase. So you need to make sure the Firebase integration is as per [latest documentation](https://firebase.google.com/docs/flutter/setup?platform=ios#available-plugins) and the integration is properly set-up at your end.

**Comment by accept1248** [comment] 2022-08-22 15:23
Hi, @darshankawar 
Thank you for your comment.
The Firebase packages I used in my app was not too old, though it was not the latest.
Please see Flutter dependencies.
I replaced all Firebase packages with the latest one you listed just to be sure, but the same error occurs again. 

Excuse me but, could you tell me which part of the app uses old integration with Firebase?

**Comment by darshankawar** [comment] 2022-08-23 09:56
@accept1248 
I have gone through the repo you shared above and it is hard to tell what exactly could be causing the issue you are facing, because there are lot of other factors in play such as third party plugins like cubit and bloc. 

The error could be pointing to https://github.com/maxonflutter/flutter_dating_app_series/blob/master/lib/repositories/database/database_repository.dart, but as I said, will be hard to analyze.

I suggest you to open this issue in dedicated repo and ask the repo owner about this error. If it is a genuine flutterfire plugins issue, we would be minimal reproducible code sample without any third party plugins that triggers the error you are seeing.

Closing for now.

**Closed by darshankawar** 2022-08-23 09:56 UTC
Labels: type: bug, Needs Attention, in triage
