### ISSUE TITLE
[firebase_auth]: error after update to iOS 18 and MacOS 15.0 

### ISSUE THREAD

**Issue by devnoaman** [firebase/flutterfire#13372] opened 2024-09-20 09:41 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Auth

### Which platforms are affected?

iOS

### Description

after updating to the latest version of iOS ad MacOS , I've faced this error 

`
Launching lib/main.dart on iPhone 16 Pro Max in debug mode...
Running pod install...                                             10.8s
Running Xcode build...                                                  
 └─Compiling, linking and signing...                         4.3s
Xcode build done.                                           173.0s
Failed to build iOS app
Lexical or Preprocessor Issue (Xcode): Include of non-modular header inside framework
module 'firebase_auth.FLTAuthStateChannelStreamHandler':
'/PATH/TO/PROJECT/ios/Pods/Headers/Public/Firebase/Fireb
ase.h'
/PATH/TO/PROJECT/.pub-cache/hosted/pub.dev/firebase_auth-5.3.0/ios/Classes/Private/FLTAu
thStateChannelStreamHandler.h:12:8

Lexical or Preprocessor Issue (Xcode): Include of non-modular header inside framework
module 'firebase_auth.PigeonParser':
'/PATH/TO/PROJECT/ios/Pods/Headers/Public/Firebase/Fireb
ase.h'
/Users/noaman/.pub-cache/hosted/pub.dev/firebase_auth-5.3.0/ios/Classes/Private/Pigeo
nParser.h:6:8

Lexical or Preprocessor Issue (Xcode): Include of non-modular header inside framework
module 'firebase_auth.FLTIdTokenChannelStreamHandler':
'/PATH/TO/PROJECT/ios/Pods/Headers/Public/Firebase/Fireb
ase.h'
/PATH/TO/PROJECT/.pub-cache/hosted/pub.dev/firebase_auth-5.3.0/ios/Classes/Private/FLTId
TokenChannelStreamHandler.h:12:8

Lexical or Preprocessor Issue (Xcode): Include of non-modular header inside framework
module 'firebase_auth.FLTPhoneNumberVerificationStreamHandler':
'/PATH/TO/PROJECT/ios/Pods/Headers/Public/Firebase/Fireb
ase.h'
/PATH/TO/PROJECT/.pub-cache/hosted/pub.dev/firebase_auth-5.3.0/ios/Classes/Private/FLTPh
oneNumberVerificationStreamHandler.h:12:8

Lexical or Preprocessor Issue (Xcode): Include of non-modular header inside framework
module 'firebase_auth.FLTFirebaseAuthPlugin':
'/PATH/TO/PROJECT/ios/Pods/Headers/Public/Firebase/Fireb
ase.h'
/PATH/TO/PROJECT/.pub-cache/hosted/pub.dev/firebase_auth-5.3.0/ios/Classes/Public/FLTFir
ebaseAuthPlugin.h:6:8

Could not build the application for the simulator.
Error launching application on iPhone 16 Pro Max.
`

### Reproducing the issue

I ve tried to add this to pod file but did not help 

`  installer.pods_project.build_configuration_list.build_configurations.each do |configuration|
    configuration.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
  end`

### Firebase Core version

3.4.0

### Flutter Version

Channel stable, 3.24.3

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

Replace this line with the contents of your `flutter pub deps -- --style=compact`.

```

</details>

**Comment by SelaseKay** [comment] 2024-09-20 09:56
Duplicate of: [13323](https://github.com/firebase/flutterfire/issues/13323)

**Closed by SelaseKay** 2024-09-20 09:56 UTC
Labels: type: bug, Needs Attention
