### ISSUE TITLE
🐛 [firebase_core] MissingPluginException on initialize Firebase

### ISSUE THREAD

**Issue by Andrushen** [firebase/flutterfire#9017] opened 2022-07-01 12:30 UTC
## Bug report

On `Firebase.initializeApp`
I get `MissingPluginException(No implementation found for method Firebase#initializeCore on channel plugins.flutter.io/firebase_core)`

### Steps to reproduce

1) flutter create appname
2) flutter pub add firebase_core 
3) flutterfire configure (in my case both android * ios) - create firebase projects for android & iOS
4) import firebase_core & add *await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform)*
5) get exception on Firebase.initializeApp for both platforms

### Sample project

<details><summary>Click To Expand main.dart</summary>

```
import 'package:firebase/firebase_options.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);
  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}

```

</details>

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 3.0.3, on macOS 11.5.2 20G95 darwin-x64, locale
    en-GB)
    • Flutter version 3.0.3 at /usr/local/Caskroom/flutter/2.5.1/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 676cefaaff (9 days ago), 2022-06-22 11:34:49 -0700
    • Engine revision ffe7b86a1e
    • Dart version 2.17.5
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0-rc1)
    • Android SDK at /Users/mac/SDK
    • Platform android-32, build-tools 32.0.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.61.2)
    • VS Code at /Users/mac/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (4 available)
    • Pixel 4a (mobile) • 15051JEC206908                       • android-arm64  • Android 12 (API 32)
    • iPhone 8 (mobile) • 8E01C944-0120-409D-83B4-F9AD3ACB250B • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-2
      (simulator)
    • macOS (desktop)   • macos                                • darwin-x64     • macOS 11.5.2 20G95 darwin-x64
    • Chrome (web)      • chrome                               • web-javascript • Google Chrome 103.0.5060.53

[✓] HTTP Host Availability
    • All required HTTP hosts are available
```

</details>

---

### Flutter run
`flutter run -v`

<details><summary>Click To Expand</summary>

```
[ +147 ms] E/flutter (25725): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: MissingPluginException(No
implementation found for method Firebase#initializeCore on channel plugins.flutter.io/firebase_core)
[        ] E/flutter (25725): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:165:7)
[        ] E/flutter (25725): <asynchronous suspension>
[        ] E/flutter (25725): #1      MethodChannel.invokeListMethod (package:flutter/src/services/platform_channel.dart:353:35)
[        ] E/flutter (25725): <asynchronous suspension>
[        ] E/flutter (25725): #2      MethodChannelFirebase._initializeCore
(package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:31:23)
[        ] E/flutter (25725): <asynchronous suspension>
[        ] E/flutter (25725): #3      MethodChannelFirebase.initializeApp
(package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:73:7)
[        ] E/flutter (25725): <asynchronous suspension>
[        ] E/flutter (25725): #4      Firebase.initializeApp (package:firebase_core/src/firebase.dart:40:31)
[        ] E/flutter (25725): <asynchronous suspension>
[        ] E/flutter (25725): #5      main (package:firebase/main.dart:7:3)
[        ] E/flutter (25725): <asynchronous suspension>
[        ] E/flutter (25725): 
```
</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.17.5
Flutter SDK 3.0.3
firebase 1.0.0+1

dependencies:
- cupertino_icons 1.0.5
- firebase_core 1.19.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]

dev dependencies:
- flutter_lints 2.0.1 [lints]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher material_color_utilities meta source_span stream_channel string_scanner term_glyph]

transitive dependencies:
- async 2.8.2 [collection meta]
- boolean_selector 2.1.0 [source_span string_scanner]
- characters 1.2.0
- charcode 1.3.1
- clock 1.1.0
- collection 1.16.0
- fake_async 1.3.0 [clock collection]
- firebase_core_platform_interface 4.4.1 [collection flutter meta plugin_platform_interface]
- firebase_core_web 1.6.5 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta vector_math]
- js 0.6.4
- lints 2.0.0
- matcher 0.12.11 [stack_trace]
- material_color_utilities 0.1.4
- meta 1.7.0
- path 1.8.1
- plugin_platform_interface 2.1.2 [meta]
- sky_engine 0.0.99
- source_span 1.8.2 [collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.0 [charcode source_span]
- term_glyph 1.2.0
- test_api 0.4.9 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- vector_math 2.1.2
```

</details>

**Comment by 2B1Kanobi** [comment] 2022-07-01 12:59
I have exactly the same problem!

**Comment by darshankawar** [comment] 2022-07-01 13:04
Closing this as duplicate of https://github.com/firebase/flutterfire/issues/9012

**Closed by darshankawar** 2022-07-01 13:04 UTC
Labels: type: bug, Needs Attention, in triage
