### ISSUE TITLE
[cloud_firestore_web] Expected a value of type 'DateTime?', but got one of type 'LegacyJavaScriptObject'

### ISSUE THREAD

**Issue by yarmel** [firebase/flutterfire#12286] opened 2024-02-05 09:31 UTC
After upgrading my dependencies to the latest versions, I can't run my web app correctly. When I try to convert a Timestamp object to DateTime, I receive an error:

```
Expected a value of type 'DateTime?', but got one of type 'LegacyJavaScriptObject'
```

The problem occurs only for the nested MAP with the Timestamp object. 
![nested](https://github.com/firebase/flutterfire/assets/8500505/ebca9381-b880-45f0-a72b-abd9405d2b7e)

My dependencies are updated, and I have tried to clean and rebuild, but without any luck.
I found a similar problem, and the issue is marked as CLOSED, but it's not resolved.

My pubspec.yaml

```
  # -> Firebase
  firebase_core: ^2.25.3
  firebase_auth: ^4.17.3
  firebase_storage: ^11.6.4
  firebase_remote_config: ^4.3.12
  firebase_messaging: ^14.7.14
  firebase_crashlytics: ^3.4.13
  firebase_analytics: ^10.8.4
  cloud_functions: ^4.6.4
  cloud_firestore: ^4.15.3
```

**Comment by FedeRotoli** [comment] 2024-02-05 11:08
I have the same error

**Comment by yarmel** [comment] 2024-02-05 13:53
> @yarmel Can you check [this](https://github.com/firebase/flutterfire/issues/12279#issuecomment-1926418517) comment and see if it helps in your case or not ? If not, please provide us reproducible code sample that we can use to verify it further.

Please try this code, to catch the error

```
Future<void> testTimestamps() async {
    try {
      Map<String, dynamic> data = {
        'timestamp': DateTime.now(),
        'logs': [
          {
            'createdAt': DateTime.now(),
          },
        ],
      };

      await db.collection('tests').doc('doc-id').set(data);

      final DocumentSnapshot<Map<String, dynamic>> doc =
          await FirebaseFirestore.instance.collection('tests').doc('doc-id').get();

      Map<String, dynamic> entityData = doc.data()!;
      Timestamp timestamp = entityData['timestamp'];

      // First level
      print('\nTimestamp: $timestamp');
      print('Timestamp: ${timestamp.runtimeType}');
      print('DateTime: ${timestamp.toDate()}');

      // Nested level

      print('\ncreatedAt Timestamp Value: ${entityData['logs'][0]['createdAt']}');
      print(
          'createdAt Datetime Value: ${(entityData['logs'][0]['createdAt'] as Timestamp).toDate()}');
      print('createdAt DateTime Type: ${(entityData['logs'][0]['createdAt']).runtimeType}');
    } catch (e) {
      print(e);
    }
  }
```

**Comment by Lyokone** [comment] 2024-02-05 15:25
I think it's a duplicate of https://github.com/firebase/flutterfire/issues/12279 which has a PR ready

**Closed** 2024-02-06 10:26 UTC
Labels: type: bug, Needs Attention, in triage
