### ISSUE TITLE
FlutterFirebaseMessagingPlugin.java uses unchecked or unsafe operations.

### ISSUE THREAD

**Issue by rtessler** [firebase/flutterfire#10122] opened 2022-12-15 14:02 UTC
## Bug report

while running flutter build appbundle I get

Note: /Users/roberttessler/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-14.1.4/android/src/main/java/io/flutter/plugins/firebase/messaging/FlutterFirebaseMessagingPlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

### Steps to reproduce

$ flutter build appbundle

### Expected behavior

no warning

### Sample project

Providing a minimal example project which demonstrates the bug in isolation from your main App _greatly_ enhances the chance of a timely fix.
Please link to the public repository URL.

---

## Additional context

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

**Comment by andresaalonso** [comment] 2022-12-15 21:13
Same here

**Comment by foxmid** [comment] 2022-12-16 00:07
same here :-(

**Comment by darshankawar** [comment] 2022-12-16 09:58
Closing this as duplicate of https://github.com/firebase/flutterfire/issues/8073. That issue is a consolidated tracker for such issues, so please follow-up in it for further updates.

**Closed by darshankawar** 2022-12-16 09:58 UTC
Labels: type: bug, Needs Attention, in triage
