### ISSUE TITLE
🐛 [firebase_auth, etc] version conflict with Firebase SDK 10.0.0

### ISSUE THREAD

**Issue by motucraft** [firebase/flutterfire#9792] opened 2022-10-26 02:55 UTC
## Bug report

**Describe the bug**
ML Kit SDK version conflicts and build fails. Firebase SDK 10.0.0
It worked fine until 9.6.0.

```
ios % pod install
Analyzing dependencies
firebase_auth: Using Firebase SDK version '10.0.0' defined in 'firebase_core'
firebase_core: Using Firebase SDK version '10.0.0' defined in 'firebase_core'
[!] CocoaPods could not find compatible versions for pod "GTMSessionFetcher/Core":
  In Podfile:
    firebase_auth (from `.symlinks/plugins/firebase_auth/ios`) was resolved to 4.0.2, which depends on
      Firebase/Auth (= 10.0.0) was resolved to 10.0.0, which depends on
        FirebaseAuth (~> 10.0.0) was resolved to 10.0.0, which depends on
          GTMSessionFetcher/Core (~> 2.1)

    mobile_scanner (from `.symlinks/plugins/mobile_scanner/ios`) was resolved to 0.0.1, which depends on
      GoogleMLKit/BarcodeScanning (~> 3.2.0) was resolved to 3.2.0, which depends on
        MLKitBarcodeScanning (~> 2.2.0) was resolved to 2.2.0, which depends on
          MLKitVision (~> 4.2) was resolved to 4.2.0, which depends on
            GTMSessionFetcher/Core (~> 1.1)
```

### Steps to reproduce

1. Use the following pubspec.yml
2. Run flutter pub get
3. Run pod install
4. See error or incorrect behavior

### Expected behavior

Successful build.

### Sample pubspec.yml

```yml
name: firebase_build_error
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  firebase_core: ^2.1.0
  firebase_auth: ^4.0.2
  mobile_scanner: ^3.0.0-beta.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
flutter:
  uses-material-design: true
```

---

## Additional context

There seems to be a problem with the MLKitVision podspec.
I do not know where to report this problem.

https://github.com/CocoaPods/Specs/blob/master/Specs/8/1/e/MLKitVision/4.2.0/MLKitVision.podspec.json

```json
    "GTMSessionFetcher/Core": [
      "~> 1.1"
    ],
```

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```zsh
% flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.5, on macOS 13.0 22A380 darwin-arm, locale ja-JP)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] Android Studio (version 2021.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.2.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.2.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.2.3)
[✓] VS Code (version 1.72.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```zsh
% flutter pub deps -- --style=compact
Dart SDK 2.18.2
Flutter SDK 3.3.5
firebase_build_error 1.0.0+1

dependencies:
- cupertino_icons 1.0.5
- firebase_auth 4.0.2 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 2.1.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math sky_engine]
- mobile_scanner 3.0.0-beta.1 [flutter flutter_web_plugins js]

dev dependencies:
- flutter_lints 2.0.1 [lints]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters collection matcher material_color_utilities meta source_span stream_channel string_scanner term_glyph]

transitive dependencies:
- _flutterfire_internals 1.0.5 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_interface flutter meta]
- async 2.9.0 [collection meta]
- boolean_selector 2.1.0 [source_span string_scanner]
- characters 1.2.1
- clock 1.1.1
- cloud_firestore_platform_interface 5.8.2 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 3.0.2 [_flutterfire_internals cloud_firestore_platform_interface collection firebase_core firebase_core_web flutter flutter_web_plugins js]
- collection 1.16.0
- fake_async 1.3.1 [clock collection]
- firebase_auth_platform_interface 6.10.4 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 5.0.2 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core_platform_interface 4.5.1 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.0.0 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta vector_math]
- http_parser 4.0.2 [collection source_span string_scanner typed_data]
- intl 0.17.0 [clock path]
- js 0.6.4
- lints 2.0.1
- matcher 0.12.12 [stack_trace]
- material_color_utilities 0.1.5
- meta 1.8.0
- path 1.8.2
- plugin_platform_interface 2.1.3 [meta]
- sky_engine 0.0.99
- source_span 1.9.0 [collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.1 [source_span]
- term_glyph 1.2.1
- test_api 0.4.12 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.1 [collection]
- vector_math 2.1.2

```

</details>

---

**Comment by danagbemava-nc** [comment] 2022-10-26 09:13
Hi @motucraft, unfortunately, there's is nothing for us to do here as the conflict is caused by `MLKitVision`. 
This issue has been reported in https://github.com/juliansteenbakker/mobile_scanner/issues/335 on the `mobile_scanner` repo and it appears that a bug has also been filed in the google tracker, see https://github.com/juliansteenbakker/mobile_scanner/issues/335#issuecomment-1286346905. 

I'll be closing this as there's nothing for the flutterfire team to do. 

Thank you

**Closed by danagbemava-nc** 2022-10-26 09:13 UTC
Labels: type: bug, Needs Attention, in triage

**Comment by motucraft** [comment] 2022-10-26 09:21
@danagbemava-nc 
Thanks to you, I found that it has been reported to google tracker.
But I don't know when it will be fixed... Thanks.

**Comment by motucraft** [comment] 2022-11-05 07:58
> Hi @motucraft, unfortunately, there's is nothing for us to do here as the conflict is caused by `MLKitVision`. This issue has been reported in [juliansteenbakker/mobile_scanner#335](https://github.com/juliansteenbakker/mobile_scanner/issues/335) on the `mobile_scanner` repo and it appears that a bug has also been filed in the google tracker, see [juliansteenbakker/mobile_scanner#335 (comment)](https://github.com/juliansteenbakker/mobile_scanner/issues/335#issuecomment-1286346905).
> 
> I'll be closing this as there's nothing for the flutterfire team to do.
> 
> Thank you

@danagbemava-nc
I can no longer access IssueTracker, which I was told about here, do you know why?

**Comment by anthonyhunter** [comment] 2022-11-11 00:45
See https://issuetracker.google.com/issues/254418199#comment48 for workaround
