### ISSUE TITLE
[firebase_crashlytics] Symbolication of obfuscated iOS Stack-Traces still not working

### ISSUE THREAD

**Issue by RCVZ** [firebase/flutterfire#12283] opened 2024-02-04 16:15 UTC
## Bug report

**Describe the bug**
I get obfuscated Stack traces like this:
<img width="1138" alt="Scherm­afbeelding 2024-02-04 om 17 05 52" src="https://github.com/firebase/flutterfire/assets/38441984/d8d6445f-d078-461c-9365-e7b007d3b2d8">

### Steps to reproduce

1. I integrated the firebase_crashlytics package and used flutterfire_cli to setup the project locally with two flavours dev and prod
2. I run a build in codemagic, and see in firebase crashlytics dashboard that the dSYM files have been added but without a version number
3. Firebase crashlytics dashboard still shows obfuscated Stack Traces

### Expected behavior

I can see the stack trace symbolicated.

---

## Additional context

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 3.16.9, on macOS 14.2 23C64 darwin-arm64, locale nl-NL)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.86.0)
[✓] Connected device (2 available)            
[✓] Network resources
```

</details>

---

**Comment by RCVZ** [comment] 2024-02-05 13:06
@darshankawar 

Yes, I have looked at those, and nothing in that helped my case. 

I did take a look in the dSYM.zip at the Info.plist 

The `CFBundleIdentifier`  shows `com.apple.xcode.dsym.com.adapt.app` 
Which is wrong it should be `com.adapt.app` as in the GoogleService-Info.plist which shows the correct bundle identifier.

In the Info.plist in the Runner directory I use the variable PRODUCT_BUNDLE_IDENTIFIER because of the flavors.

Any ideas why it would prepend `com.apple.xcode.dsym`  or is that normal behavior?

**Comment by darshankawar** [comment] 2024-02-06 12:26
Thanks for the feedback @RCVZ 
I am wondering if this is occuring due to flavors you are using in the app ?
Is there a way for you to check by removing flavors to confirm if the behavior still persist or not ?

**Comment by nicolasteixeira3856** [comment] 2024-02-08 12:53
I am encountering the same issues, currently utilizing flutter_flavorizr for flavor management in Flutter.

The command I use to build the app is as follows:

`flutter build ipa --flavor prod -t lib/main_prod.dart --obfuscate --split-debug-info=$(Build.SourcesDirectory)/debugsymbol
`

Although the 'debugsymbol' folder and corresponding .symbol file are generated successfully, I am unable to upload them due to an error. The error message displayed is:

```
java.io.IOException: Breakpad symbol generation failed (exit=1), see STDERR
	at com.google.firebase.crashlytics.buildtools.ndk.internal.breakpad.BreakpadSymbolGenerator.generateSymbols(BreakpadSymbolGenerator.java:133)
	at com.google.firebase.crashlytics.buildtools.Buildtools.generateNativeSymbolFiles(Buildtools.java:273)
	at com.google.firebase.crashlytics.buildtools.CommandLineHelper.executeGenerateSymbols(CommandLineHelper.java:185)
	at com.google.firebase.crashlytics.buildtools.CommandLineHelper.executeCommand(CommandLineHelper.java:118)
	at com.google.firebase.crashlytics.buildtools.CommandLineHelper.main(CommandLineHelper.java:65)
	at com.google.firebase.crashlytics.buildtools.Buildtools.main(Buildtools.java:111)
```

Based on similar issues, such as [8934](https://github.com/firebase/flutterfire/issues/8934) on GitHub, this error seems to be a known problem. I have verified that my script for uploading dsym files is functioning correctly, and they have been successfully uploaded to Firebase. However, I am uncertain of how to proceed further in resolving this issue.

This how my stack trace looks on Crashlytics dashboard:

![Captura de Tela 2024-02-08 às 09 46 11](https://github.com/firebase/flutterfire/assets/33877493/e307e58c-ba9a-476b-8d55-1217d940474a)

On Android both the stacktrace and the symbol upload works fine with the --obfuscate --split-debug-info flags.

**Comment by RCVZ** [comment] 2024-02-12 12:09
@darshankawar I can confirm that the stack traces are correctly deobfuscated without flavors.

**Comment by darshankawar** [comment] 2024-02-13 11:24
@RCVZ Thanks for the update. 
Can you try to re-configure using latest version of flutterfire CLI ? Based on https://github.com/invertase/flutterfire_cli/pull/247, it should be able to deobfuscate irrespective with or without flavors.

**Comment by RCVZ** [comment] 2024-02-14 16:08
@darshankawar  I'm already using flutterfire_cli 0.3.0-dev.19

**Comment by darshankawar** [comment] 2024-02-16 10:04
> 2\. I run a build in codemagic, and see in firebase crashlytics dashboard that the dSYM files have been added but without a version number

Thanks for the update. Is the behavior only occuring while running in CI/CD ? Or if you try locally as well, do you get same behavior ?

**Comment by RCVZ** [comment] 2024-02-19 09:21
@darshankawar 

This is both local and CI.

**Comment by darshankawar** [comment] 2024-02-19 11:05
Can you take a look at [this](https://github.com/firebase/flutterfire/issues/10994) with underlying comments and to check if it helps in your case or not ?

**Comment by RCVZ** [comment] 2024-02-19 12:30
@darshankawar 

My builds don't fail so how is exiting the upload script going to solve my problem? 

The problem is that there is something wrong with how the uploading/creation of the dSYMs is handled. Crashlystics can not match the versions when using flavors.

I'm not the only one experiencing this issue.

https://github.com/invertase/flutterfire_cli/issues/14#issuecomment-1934062227

https://github.com/invertase/flutterfire_cli/issues/14#issuecomment-1941147875

https://github.com/invertase/flutterfire_cli/issues/249

**Comment by darshankawar** [comment] 2024-02-20 10:58
Thanks for the update. Yes, I had gone through those comments from the issue which makes me think that the issue could be at the cli and not in the plugin itself, because if the cli tool supports the flavor feature, then the issue would probably get resolved.
Also, the command (`flutter build ipa`..) would also need to support it, so technically, it doesn't seem to be a plugin issue, because as you mentioned earlier, without `flavor`, you are able to get the expected behavior.

So I think it would be beneficial to follow-up in the cli tool repo for this.

**Comment by AhmedLSayed9** [comment] 2024-02-21 12:13
Same issue here using flavors.

**Comment by RCVZ** [comment] 2024-02-23 10:29
@AhmedLSayed9 I have commented on this issue in the CLI repo. Maybe let them know that you run into the same problems.

https://github.com/invertase/flutterfire_cli/issues/249

**Comment by russellwheatley** [comment] 2024-02-23 10:33
Yes, let's move this to the correct repository, please report to this issue: https://github.com/invertase/flutterfire_cli/issues/249. Thanks 👍

**Closed by russellwheatley** 2024-02-23 10:33 UTC
Labels: type: bug, Needs Attention, in triage
