### ISSUE TITLE
Fix these warning issues with flutter and this extension:

### ISSUE THREAD

**Issue by fisforfaheem** [firebase/flutterfire#11246] opened 2023-07-10 07:02 UTC
Note: /Users/4edoc/.pub-cache/hosted/pub.dev/firebase_messaging-14.6.2/android/src/main/java/io/flutter/plugins/firebase/messaging/FlutterFirebaseMessagingPlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: /Users/4edoc/.pub-cache/hosted/pub.dev/cloud_firestore-4.8.0/android/src/main/java/io/flutter/plugins/firebase/firestore/FlutterFirebaseFirestoreMessageCodec.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/4edoc/.pub-cache/hosted/pub.dev/cloud_firestore-4.8.0/android/src/main/java/io/flutter/plugins/firebase/firestore/FlutterFirebaseFirestoreMessageCodec.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

**Comment by danagbemava-nc** [comment] 2023-07-10 11:37
Hi @fisforfaheem, the issue regarding the deprecation notice for messaging is being tracked in https://github.com/firebase/flutterfire/issues/8073. Regarding cloud_firestore, a new version has been released. Can you try clearing your pub cache and running your project again to see if you still have the lines below in your app?

```
Note: /Users/4edoc/.pub-cache/hosted/pub.dev/cloud_firestore-4.8.0/android/src/main/java/io/flutter/plugins/firebase/firestore/FlutterFirebaseFirestoreMessageCodec.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/4edoc/.pub-cache/hosted/pub.dev/cloud_firestore-4.8.0/android/src/main/java/io/flutter/plugins/firebase/firestore/FlutterFirebaseFirestoreMessageCodec.java uses unchecked or unsafe operations.
```

**Comment by mcphee11** [comment] 2023-07-15 01:31
@danagbemava-nc I also have came accross this issue and updated both firebase_messaging: 14.6.5 and cloud_firestore: 4.8.3 which were both published 13hrs ago and the issue remains. It still builds ok but would be nice to have these cleaned up if possible.

**Comment by fisforfaheem** [comment] 2023-07-16 08:48
still getting these warnings in all packages from firebase

**Comment by danagbemava-nc** [comment] 2023-07-17 11:35
Thanks for the update. Closing this as a duplicate of #8073. Kindly leave a comment in the original issue so that the team is aware that this is still happening. 

Thank you

**Closed by danagbemava-nc** 2023-07-17 11:35 UTC
Labels: type: bug, Needs Attention, in triage
